### ISSUE TITLE
Whether there is a way to update the argo controller in k8s by self made images in the latest version 

### ISSUE THREAD

**Issue by bitzhuxb** [argoproj/argo#1001]
**FEATURE REQUEST**:

**What happened**:
In the document as follows:
`https://github.com/argoproj/argo/blob/master/CONTRIBUTING.md,` we can reinstall argo controller by using docker image, but in the latest version argo install was canceled, so, I want to know wether there is a way that we can update our controller by docker images, which is build by referring the page `https://github.com/argoproj/argo/blob/master/CONTRIBUTING.md`

**Comment by jessesuen** [comment]
The manifests can always be updated to use your own images, but some convenience was lost by removing the installer. I think a shell script in the hack directory to achieve the same affect (for dev purposes) makes sense to have.
