### ISSUE TITLE
BUG: Resubmission of a terminated workflow creates a new workflow that is already terminated.

### ISSUE THREAD

**Issue by nrmitchi** [argoproj/argo#1011]
BUG REPORT

**What happened**:
`argo resubmit` on a terminated job creates a new workflow that is already terminated.

**What you expected to happen**:
The newly created workflow is not terminated.

**How to reproduce it (as minimally and precisely as possible)**:
 - Create a workflow.
 - Terminate the workflow.
 - Resubmit the terminated workflow.
 - See that the newly created workflow is terminated.

**Environment**:
- Argo version:
```
$ argo version
argo: v2.2.0
  BuildDate: 2018-08-30T08:51:40Z
  GitCommit: af636ddd8455660f307d835814d3112b90815dfd
  GitTreeState: clean
  GitTag: v2.2.0
  GoVersion: go1.10.3
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version : v1.10.3
```
$ kubectl version -o yaml
clientVersion:
  buildDate: 2018-08-08T16:31:10Z
  compiler: gc
  gitCommit: bb9ffb1654d4a729bb4cec18ff088eacc153c239
  gitTreeState: clean
  gitVersion: v1.11.2
  goVersion: go1.10.3
  major: "1"
  minor: "11"
  platform: darwin/amd64
serverVersion:
  buildDate: 2018-05-21T09:05:37Z
  compiler: gc
  gitCommit: 2bba0127d85d5a46ab4b778548be28623b32d0b0
  gitTreeState: clean
  gitVersion: v1.10.3
  goVersion: go1.9.3
  major: "1"
  minor: "10"
  platform: linux/amd64
```

**Comment by jessesuen** [comment]
Resolved in 6f611cb9383610471f941b5cab4227ce8bfea7c5
