### ISSUE TITLE
git submodule get the wrong code

### ISSUE THREAD

**Issue by yijingzeng** [argoproj/argo#1017]
My project includes two submodules, this file (https://github.com/argoproj/argo/blob/master/workflow/artifacts/git/git.go) only checkout the main project and **do not** update my submodule. I got errors in argo log because the wrong code in the submodule.

**Comment by andreimc** [comment]
// Fixed now

**Comment by jessesuen** [comment]
Fixed in https://github.com/argoproj/argo/pull/1042
