### ISSUE TITLE
Argo API docs

### ISSUE THREAD

**Issue by lalarsson** [argoproj/argo#1036]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Feature request
**What happened**:
Found a swagger.json with only models
**What you expected to happen**:
Expected to find some paths as well :)
**How to reproduce it (as minimally and precisely as possible)**:
Go to where the swagger.json is [located](https://github.com/argoproj/argo/blob/master/api/openapi-spec/swagger.json)
**Anything else we need to know?**:
Awesome work 👍

**Comment by bhavin192** [comment]
https://godoc.org/github.com/argoproj/argo/pkg/apis/workflow/v1alpha1
This is better as you can jump to definitions as well.

**Comment by alexec** [comment]
Argo API docs can be found under `docs/openapi-spec/swagger.json`
