### ISSUE TITLE
ttlSecondsAfterFinished not working

### ISSUE THREAD

**Issue by bappr** [argoproj/argo#1043]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG

**What happened**:
`argo submit -n staging https://raw.githubusercontent.com/argoproj/argo/master/examples/gc-ttl.yaml` does not delete the workflow and associated pods after 10 seconds

**What you expected to happen**:
Workflow and pods should be deleted after 10 seconds.

**How to reproduce it (as minimally and precisely as possible)**:
`argo submit -n staging https://raw.githubusercontent.com/argoproj/argo/master/examples/gc-ttl.yaml`

**Anything else we need to know?**:

**Environment**:
- Argo version:
```
$ argo version
argo: v2.2.0
  BuildDate: 2018-08-30T08:51:40Z
  GitCommit: af636ddd8455660f307d835814d3112b90815dfd
  GitTreeState: clean
  GitTag: v2.2.0
  GoVersion: go1.10.3
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: 2018-06-27T22:29:25Z
  compiler: gc
  gitCommit: 91e7b4fd31fcd3d5f436da26c980becec37ceefe
  gitTreeState: clean
  gitVersion: v1.11.0
  goVersion: go1.10.3
  major: "1"
  minor: "11"
  platform: darwin/amd64
serverVersion:
  buildDate: 2018-08-02T23:42:40Z
  compiler: gc
  gitCommit: 9b635efce81582e1da13b35a7aa539c0ccb32987
  gitTreeState: clean
  gitVersion: v1.9.7-gke.5
  goVersion: go1.9.3b4
  major: "1"
  minor: 9+
  platform: linux/amd64
```

**Other debugging information (if applicable)**:
- workflow result:
```
$ argo get -n staging gc-ttl-vg2g7
Name:                gc-ttl-vg2g7
Namespace:           staging
ServiceAccount:      default
Status:              Succeeded
Created:             Mon Oct 15 14:58:08 +0800 (4 minutes ago)
Started:             Mon Oct 15 14:58:09 +0800 (4 minutes ago)
Finished:            Mon Oct 15 14:58:21 +0800 (3 minutes ago)
Duration:            12 seconds

STEP             PODNAME       DURATION  MESSAGE
 ✔ gc-ttl-vg2g7  gc-ttl-vg2g7  12s
```

**Comment by jessesuen** [comment]
This was because the manifests were not updated correctly to include delete permission in the RBAC. See issue #1004 for how to edit the role with the proper permissions. Also the new manifests have been updated to include this verb.

**Comment by bappr** [comment]
Indeed! Works perfectly, thanks!
