### ISSUE TITLE
Parameters and artifacts should support snake_case

### ISSUE THREAD

**Issue by bbc88ks** [argoproj/argo#1047]
Hi,

AFAIK the alphanumeric + '-' constraint is only required for the workflow name and any templates names because all kubernetes resources must follow DNS RFC.

We are trying to create workflows that seamlessly transition workflow parameters into app variables without having to explicitly define all of the possible variable permutations in the workflow yaml ( e.g. first step is `kubectl get wf mywf-o json` and then unwrap ['spec']['arguments']['parameters'] into an app config file). It's pretty common for configuration values to be snake case and parameter and artifact names should support it.

**Comment by jessesuen** [comment]
Fixed
