### ISSUE TITLE
ttlSecondsAfterFinished don't work well

### ISSUE THREAD

**Issue by mysteryHJJ** [argoproj/argo#1069]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG

**What happened**:  TTL works when I use single task without a dag task ( like gc-ttl.yaml ), but it dosen't work well when I submit a dag task. I set the  ttlSecondsAfterFinished: 43200 with dag，after time it did not gc

**What you expected to happen**:  gc work well

**Environment**:
- Argo version:
``` 
v2.2
```
- Kubernetes version :
```
v1.10
```

**Comment by jessesuen** [comment]
This feature is in argo v2.2 not v2.1

**Comment by jessesuen** [comment]
The original description stated it was tested against v2.1 and edited to say v2.2, but Argo v2.2 is working as expected, so long as sufficient delete privileges are given to the workflow-controller's service account. Please re-open if you can reproduce otherwise.
