### ISSUE TITLE
Argo UI not updating its workflow UI automatically in other namespace than default

### ISSUE THREAD

**Issue by hongkunyoo** [argoproj/argo#1101]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Bug report

**What happened**:
Submitting workflow to other namespace than `default` causes argo-ui not updating its workflow UI automatically.
The workflow ends successfully though.

It seems quite similar with this issue https://github.com/argoproj/argo/issues/933
But it only happens when a workflow is in other namespace than `default`.

**What you expected to happen**:
Updating its workflow UI automatically without refreshing the page.

**How to reproduce it (as minimally and precisely as possible)**:
1. Install argo in `argo` namespace
```
kubectl create ns argo
kubectl apply -n argo -f https://raw.githubusercontent.com/argoproj/argo/v2.2.1/manifests/install.yaml
```
2. Create new namespace named `dev`
```
kubectl create ns dev
```
3. Create rolebinding object for `dev:default` service account
```
kubectl create rolebinding default-admin --clusterrole=admin --serviceaccount=dev:default --namespace=dev
```
4. Submit a workflow to `dev` namespace
```
argo submit --namespace dev https://raw.githubusercontent.com/argoproj/argo/master/examples/coinflip.yaml
```
5. Watch Argo-UI workflow details page whether the workflow UI changes automatically.

**Anything else we need to know?**:
I have found out that the following URL gets pending while workflow runs in other namespace (in this case `dev`).
`http://$ARGO-UI-URL/api/workflows/live?namespace=dev&name=$NAME_OF_WF`
--> pending
if I submit a workflow in `default` namespace it responses with following data.
`http://$ARGO-UI-URL/api/workflows/live?namespace=default&name=$NAME_OF_WF`
--> 
<details><summary>Click here: log</summary>
<p>
```data:{"type":"ADDED","object":{"apiVersion":"argoproj.io/v1alpha1","kind":"Workflow","metadata":{"creationTimestamp":"2018-11-26T08:14:30Z","generateName":"coinflip-","generation":1,"labels":{"workflows.argoproj.io/completed":"true","workflows.argoproj.io/phase":"Succeeded"},"name":"coinflip-fkhg9","namespace":"default","resourceVersion":"8093662","selfLink":"/apis/argoproj.io/v1alpha1/namespaces/default/workflows/coinflip-fkhg9","uid":"4ca83aed-f153-11e8-822a-02d03df37d48"},"spec":{"arguments":{},"entrypoint":"coinflip","templates":[{"inputs":{},"metadata":{},"name":"coinflip","outputs":{},"steps":[[{"arguments":{},"name":"flip-coin","template":"flip-coin"}],[{"arguments":{},"name":"heads","template":"heads","when":"{{steps.flip-coin.outputs.result}} == heads"},{"arguments":{},"name":"tails","template":"tails","when":"{{steps.flip-coin.outputs.result}} == tails"}]]},{"inputs":{},"metadata":{},"name":"flip-coin","outputs":{},"script":{"command":["python"],"image":"python:alpine3.6","name":"","resources":{},"source":"import random\nresult = \"heads\" if random.randint(0,1) == 0 else \"tails\"\nprint(result)\n"}},{"container":{"args":["echo \"it was heads\""],"command":["sh","-c"],"image":"alpine:3.6","name":"","resources":{}},"inputs":{},"metadata":{},"name":"heads","outputs":{}},{"container":{"args":["echo \"it was tails\""],"command":["sh","-c"],"image":"alpine:3.6","name":"","resources":{}},"inputs":{},"metadata":{},"name":"tails","outputs":{}}]},"status":{"finishedAt":"2018-11-26T08:14:36Z","nodes":{"coinflip-fkhg9":{"children":["coinflip-fkhg9-778288827"],"displayName":"coinflip-fkhg9","finishedAt":"2018-11-26T08:14:36Z","id":"coinflip-fkhg9","name":"coinflip-fkhg9","outboundNodes":["coinflip-fkhg9-2992800083","coinflip-fkhg9-1405163971"],"phase":"Succeeded","startedAt":"2018-11-26T08:14:30Z","templateName":"coinflip","type":"Steps"},"coinflip-fkhg9-1405163971":{"boundaryID":"coinflip-fkhg9","displayName":"tails","finishedAt":"2018-11-26T08:14:35Z","id":"coinflip-fkhg9-1405163971","name":"coinflip-fkhg9[1].tails","phase":"Succeeded","startedAt":"2018-11-26T08:14:33Z","templateName":"tails","type":"Pod"},"coinflip-fkhg9-2796363958":{"boundaryID":"coinflip-fkhg9","children":["coinflip-fkhg9-845546398"],"displayName":"flip-coin","finishedAt":"2018-11-26T08:14:32Z","id":"coinflip-fkhg9-2796363958","name":"coinflip-fkhg9[0].flip-coin","outputs":{"result":"tails"},"phase":"Succeeded","startedAt":"2018-11-26T08:14:30Z","templateName":"flip-coin","type":"Pod"},"coinflip-fkhg9-2992800083":{"boundaryID":"coinflip-fkhg9","displayName":"heads","finishedAt":"2018-11-26T08:14:33Z","id":"coinflip-fkhg9-2992800083","message":"when 'tails == heads' evaluated false","name":"coinflip-fkhg9[1].heads","phase":"Skipped","startedAt":"2018-11-26T08:14:33Z","type":"Skipped"},"coinflip-fkhg9-778288827":{"boundaryID":"coinflip-fkhg9","children":["coinflip-fkhg9-2796363958"],"displayName":"[0]","finishedAt":"2018-11-26T08:14:33Z","id":"coinflip-fkhg9-778288827","name":"coinflip-fkhg9[0]","phase":"Succeeded","startedAt":"2018-11-26T08:14:30Z","type":"StepGroup"},"coinflip-fkhg9-845546398":{"boundaryID":"coinflip-fkhg9","children":["coinflip-fkhg9-2992800083","coinflip-fkhg9-1405163971"],"displayName":"[1]","finishedAt":"2018-11-26T08:14:36Z","id":"coinflip-fkhg9-845546398","name":"coinflip-fkhg9[1]","phase":"Succeeded","startedAt":"2018-11-26T08:14:33Z","type":"StepGroup"}},"phase":"Succeeded","startedAt":"2018-11-26T08:14:30Z"}}}```
</p>
</details>

**Environment**:
- Argo version:
```
argo: v2.1.1
  BuildDate: 2018-05-29T20:39:36Z
  GitCommit: ac241c95c13f08e868cd6f5ee32c9ce273e239ff
  GitTreeState: clean
  GitTag: v2.1.1
  GoVersion: go1.9.3
  Compiler: gc
  Platform: linux/amd64
```
- Kubernetes version :
```
clientVersion:
  buildDate: 2018-06-27T20:17:28Z
  compiler: gc
  gitCommit: 91e7b4fd31fcd3d5f436da26c980becec37ceefe
  gitTreeState: clean
  gitVersion: v1.11.0
  goVersion: go1.10.2
  major: "1"
  minor: "11"
  platform: linux/amd64
serverVersion:
  buildDate: 2018-10-05T16:36:14Z
  compiler: gc
  gitCommit: 4ed3216f3ec431b140b1d899130a69fc671678f4
  gitTreeState: clean
  gitVersion: v1.12.1
  goVersion: go1.10.4
  major: "1"
  minor: "12"
  platform: linux/amd64
```

Please let me know if I configured something wrong for this issue.
I've looked every (cluster)rolebinding object for argo whether if I omitted something but I can't find it.

**Comment by alexmt** [comment]
The issue has been fixed by https://github.com/argoproj/argo-ui/commit/4b78a7d6c5ff61ce1326320b274b8d2fdabf33f4 and will be available in v2.2.2. 

As workaround you might use pre-release image `argoproj/argoui:v2.2.1-37808b1`. If argo is running inside single namespace you will need to add `FORCE_NAMESPACE_ISOLATION` env variable: https://github.com/argoproj/argo/issues/1114#issuecomment-444741682
