### ISSUE TITLE
Git clone doesn't support branches. 

### ISSUE THREAD

**Issue by andreimc** [argoproj/argo#1107]
**Is this a BUG REPORT or FEATURE REQUEST?**:

FEATURE REQUEST

**What happened**:

When cloning, you should be able to specify a branch: eg develop and a revision eg HEAD, the current behaviour is to always clone revision from the main branch.

**What you expected to happen**:

When specifying branch it should be cloned of the branch itself, and check out the specified revision of the branch.

**Comment by jessesuen** [comment]
First, to avoid any confusion, the field name which we chose, `revision`, was meant to be used for all types of checkout targets (branch names, commit SHA, and symbolic references like HEAD).

@andreimc maybe I'm missing something, but isn't a branch name redundant if you know a git SHA? i.e. if a git commit SHA is specified, then branch name is irrelevant and potentially conflicting. The `revision` field of the git artifact is supposed to be semantically equivalent to:
```
git clone https://github.com/org/repo
git checkout <REVISION>
```
In the above, <REVISION> does not necessarily need to be a SHA, it can be a branch name.

**Comment by jessesuen** [comment]
Closing since cloning by branch should be working
