### ISSUE TITLE
error: no kind "Workflow" is registered for version "argoproj.io/v1alpha1"

### ISSUE THREAD

**Issue by Ark-kun** [argoproj/argo#1108]
**Is this a BUG REPORT or FEATURE REQUEST?**:

**What happened**:
I get the mentioned error when I try to use kubectl to control Argo workflow objects. In there some problem with Argo's CRD registration?

**What you expected to happen**:
I expect the command to work without errors.

**How to reproduce it (as minimally and precisely as possible)**:
```
$ kubectl logs wf/sequential-fc96k --namespace kubeflow
error: no kind "Workflow" is registered for version "argoproj.io/v1alpha1"
```
**Anything else we need to know?**:

**Environment**:
- Argo version:
```
$ argo version
argo: v2.2.0
  BuildDate: 2018-08-30T08:52:05Z
  GitCommit: af636ddd8455660f307d835814d3112b90815dfd
  GitTreeState: clean
  GitTag: v2.2.0
  GoVersion: go1.10.3
  Compiler: gc
  Platform: linux/amd64
```
- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: 2018-09-09T18:02:47Z
  compiler: gc
  gitCommit: a4529464e4629c21224b3d52edfe0ea91b072862
  gitTreeState: clean
  gitVersion: v1.11.3
  goVersion: go1.10.3
  major: "1"
  minor: "11"
  platform: linux/amd64
serverVersion:
  buildDate: 2018-11-10T20:22:02Z
  compiler: gc
  gitCommit: dc4f6dda6a08aae2108d7a7fdc2a44fa23900f4c
  gitTreeState: clean
  gitVersion: v1.9.7-gke.11
  goVersion: go1.9.3b4
  major: "1"
  minor: 9+
  platform: linux/amd64
```

**Comment by sshkel** [comment]
Hey @Ark-kun,
Not a contributor to this project, but in the absence of any comments I thought I'd share why I think you are seeing this behaviour.
There are 2 ways to implement Custom Resources in k8s as defined here: https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/
- CRDs
- API Aggregations
In both cases you create a Custom Resource Spec and a Controller that reconciles your resources. However, with API aggregations you need to register API service and k8s api server will proxy all requests for your resource to that service. CRDs are simpler and don't require you to run an api-server. Though as you might guess it comes with a cost. CRDs support only basic CRUD operations via k8s api, while aggregation api is much more flexible and can be extended to support something like grabbing logs. Here is a link to comparison of some features, logs is one of them. https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/#advanced-features-and-flexibility

Now looking at the manifests for argo it appears that it uses CRD approach as the Custom Resource spec lack any service definition https://github.com/argoproj/argo/blob/master/manifests/install.yaml#L2
Thus it can only support basic CRUD operations.

Please take it with a grain of salt. I am in no way an expert on this. 

A couple resources on this if you are interested:
Various patterns: https://itnext.io/comparing-kubernetes-api-extension-mechanisms-of-custom-resource-definition-and-aggregated-api-64f4ca6d0966
Api aggregation spotlight: https://www.youtube.com/watch?v=GUuFh-1t7os
Api aggregation example from the video above: https://github.com/kubernetes-incubator/service-catalog/blob/master/charts/catalog/templates/apiregistration.yaml

**Comment by Ark-kun** [comment]
@sshkel Thank you for you detailed answer. It was really enlightening!

**Comment by sshkel** [comment]
no problem :)

**Comment by tcolgate** [comment]
@Ark-kun @sshkel you can actually use the Go k8s.io/client-go , but you must register the argo schema
```go
import (
	argoScheme "github.com/argoproj/argo/pkg/client/clientset/versioned/scheme"
	"k8s.io/client-go/kubernetes/scheme"
)

func main(){
	argoScheme.AddToScheme(scheme.Scheme)
        ....
}
```
