### ISSUE TITLE
Daemon step + artifacts don't update workflow metadata

### ISSUE THREAD

**Issue by inc0** [argoproj/argo#1113]
**Is this a BUG REPORT or FEATURE REQUEST?**:

Bug

**What happened**:

When you add daemon step at beginning of workflow that will produce file sometime during execution (in my case redis database dump on local disk), and make this file output artifact, after workflow is done artifact seems to be saved to S3 (according to wait container log), but it's not visible in workflow metadata

**What you expected to happen**:
Artifact is available at the end of workflow

**How to reproduce it (as minimally and precisely as possible)**:

add 2 steps:
1. daemon: true -> some service that will touch file when it's called externally, make this file an output artifact
2. call service from step 1

Artifact won't be visible, but will be saved underneath

**Anything else we need to know?**:

Discussed here https://argoproj.slack.com/archives/C8J6SGN12/p1544034307062600

**Comment by alexmt** [comment]
time to fix it
