### ISSUE TITLE
[Feature Request] Improve compression performance

### ISSUE THREAD

**Issue by David-Development** [argoproj/argo#1122]
**What happened**:
When creating large output files (e.g. 7Gb+), the gzip command takes forever (compressing 4 files) (30-45min) as it is only running on a single thread while the cluster has 24 threads available on each node.

**What you expected to happen**:
It would be great if the gzip command runs in parallel and takes advantage of the processing power available. There are some parallel implementations of gzip out there. For example pigz (https://zlib.net/pigz/)

**Comment by alexec** [comment]
@David-Development this is rather an old issue. Can you please confirm if you have seen this since?

**Comment by David-Development** [comment]
@alexec Unfortunately I am no longer on the project so I can't confirm if this problem is still valid. If no one else has performance problems, feel free to close it!
