### ISSUE TITLE
Argo UI displays DAG in an odd way

### ISSUE THREAD

**Issue by ObeA** [argoproj/argo#1136]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Bug report.

**What happened**:
The UI displays the DAG in an odd way. 
![](https://imgur.com/BlF1V5Q.jpg)

**What you expected to happen**:
I expected the lines not to go all over the place. 

**How to reproduce it (as minimally and precisely as possible)**:
If you submit this workflow: [https://gist.github.com/ObeA/25e5ab80eb58b019d13222148ff135ba](https://gist.github.com/ObeA/25e5ab80eb58b019d13222148ff135ba)
You'll get probably get same the results as in the screenshot.

**Anything else we need to know?**:
I'm sorry for the names... I replaced them because it would tell something about the way we're trying to use Argo for our internal data pipeline.

It seems like dagre has trouble placing subpipeline-b because it depends on subpipeline-a which is run with 2 items. It looks like dagre is trying to place it between the two pipelines instead of placing it to the side (Like [this](https://i.imgur.com/01nTYQE.jpg) one). Maybe connecting the node to the "main" node would solve this?

**Environment**:
- Argo version:
```
$ argo version
argo: v2.2.1
  BuildDate: 2018-10-11T16:25:59Z
  GitCommit: 3b52b26190163d1f72f3aef1a39f9f291378dafb
  GitTreeState: clean
  GitTag: v2.2.1
  GoVersion: go1.10.3
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :
```
$ kubectl version -o yaml
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by ObeA** [comment]
I've tried to look into this. I couldn't find any real metadata issue. However I think there are some inconsistencies between StepGroups and DAGs. When I change the workflow to partially use steps instead of a DAG the result is a lot better. Steps do force a common point to be put before and after the steps, which causes the next step to be placed below the previous instead of next to it.

If you submit this workflow: [https://gist.github.com/ObeA/f1db2b8ec4c0a285845493742ed1b32f](https://gist.github.com/ObeA/f1db2b8ec4c0a285845493742ed1b32f)
You should get this:
![image](https://user-images.githubusercontent.com/2452105/50600180-98142200-0eb0-11e9-817a-9d5e80e8109f.png)

Some arrows are still placed a bit weird, but I guess that's just something in dagre we'll have to live with. I've tried to play around with other ways to connect the nodes, but haven't been able to found a way to improve the result yet.

**Comment by alexmt** [comment]
Working on it
