### ISSUE TITLE
Support HDFS Artifacts

### ISSUE THREAD

**Issue by dtaniwaki** [argoproj/argo#1140]
**Is this a BUG REPORT or FEATURE REQUEST?**:

FEATURE REQUEST

**What happened**:

My company uses HDFS w/ Kerberos auth as a storage for artifacts and want to use it easily in argo.

**Anything else we need to know?**:

I'm implementing it, so I will send a PR.

I'm also adding the HDFS support in argo-events.
https://github.com/argoproj/argo-events/issues/142

**Comment by dtaniwaki** [comment]
I have implemented the HDFS support in https://github.com/dtaniwaki/argo/tree/support-hdfs-artifacts but [the go hdfs client error](https://github.com/colinmarc/hdfs/issues/144) prevent me to test Kerberos authentication. I'll wait or work with the repo owner of the client.

**Comment by dtaniwaki** [comment]
I succeeded to use this HDFS artifact with the following patch for [kubernetes-HDFS](https://github.com/apache-spark-on-k8s/kubernetes-HDFS).

```patch
diff --git a/charts/hdfs-config-k8s/templates/configmap.yaml b/charts/hdfs-config-k8s/templates/configmap.yaml
index 379dab8..f02b692 100644
--- a/charts/hdfs-config-k8s/templates/configmap.yaml
+++ b/charts/hdfs-config-k8s/templates/configmap.yaml
@@ -34,7 +34,7 @@ data:
       </property>
       <property>
         <name>hadoop.rpc.protection</name>
-        <value>privacy</value>
+        <value>authentication</value>
       </property>
       <property>
         <name>hadoop.user.group.static.mapping.overrides</name>
@@ -74,7 +74,7 @@ data:
       </property>
       <property>
         <name>dfs.encrypt.data.transfer</name>
-        <value>true</value>
+        <value>false</value>
       </property>
       <property>
         <name>dfs.namenode.kerberos.principal</name>
```

**Comment by alexmt** [comment]
This is done. Thanks @dtaniwaki !

**Comment by BobLiu20** [comment]
@dtaniwaki  Hi guys. Thanks for your great work. Could you share me how to config the ConfigMap to use HDFS? I can't find any doc for this case.

**Comment by dtaniwaki** [comment]
@BobLiu20 
The commented-out lines in https://github.com/dtaniwaki/argo/blob/34ed28dda5a693d6d37a3c1d544d28a432a19f21/examples/hdfs-artifact.yaml#L41-L52 may help.
