### ISSUE TITLE
Possibility to define sub-pipelines with multiple yaml files 

### ISSUE THREAD

**Issue by marcadella** [argoproj/argo#1152]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST

I've been through the examples and could not find one where a pipeline is split in sub-pipelines each defined in its own yaml file. That would be helpful to manage/test big pipelines.

**Comment by nbren12** [comment]
I am interested in this too. Is this currently supported by argo?

**Comment by alexec** [comment]
Can you do this using workflow templates?

**Comment by nbren12** [comment]
Are you asking me? I'm not sure. I am just looking for anyway to split a pipeline across multiple yaml files.

**Comment by nbren12** [comment]
I think workflow templates are the right answer, so feel free to close this issue.
