### ISSUE TITLE
make fails with /usr/local/go/pkg/linux_amd64/os/user.a: permission denied

### ISSUE THREAD

**Issue by remster** [argoproj/argo#1154]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT
**What happened**:
```
[remek][~/.../github.com/argoproj/argo][master]$ make
CGO_ENABLED=0 go build -v -i -ldflags '-X github.com/argoproj/argo.version=2.3.0 -X github.com/argoproj/argo.buildDate=2019-01-04T13:29:20Z -X github.com/argoproj/argo.gitCommit=3561bff70ad6bfeca8967be6aa4ac24fbbc8ac27 -X github.com/argoproj/argo.gitTreeState=clean -X github.com/argoproj/argo/cmd/argo/commands.imageTag=latest' -o /home/remek/go/src/github.com/argoproj/argo/dist/argo ./cmd/argo
go build net: open /usr/local/go/pkg/linux_amd64/net.a: permission denied
go build os/user: open /usr/local/go/pkg/linux_amd64/os/user.a: permission denied
Makefile:61: recipe for target 'cli' failed
make: *** [cli] Error 1
[remek][~/.../github.com/argoproj/argo][master]$ ll /usr/local/go/pkg/linux_amd64/os/user.a
-rw-r--r-- 1 root root 135088 Dec 15 00:38 /usr/local/go/pkg/linux_amd64/os/user.a
[remek][~/.../github.com/argoproj/argo][master]$ 
```
**What you expected to happen**:
build to succeed
**How to reproduce it (as minimally and precisely as possible)**:
`make` on a Ubuntu 18.04 with golang installed as described [here](https://golang.org/doc/install#uninstall)
**Anything else we need to know?**:
it appears `make` tries to **write** to /usr/local/go/pkg/linux_amd64/os/user.a 
likely related to:
https://github.com/golang/go/issues/24674

You have closed a similar defect: https://github.com/argoproj/argo/issues/818
But that doesn't really solve them problem - I have just followed the official golang installation steps
and the problem persists.

**Environment**:
- Argo version:
```
when building latest: 3561bff70ad6bfeca8967be6aa4ac24fbbc8ac27
```
- Linux version :
```
Ubuntu 18.04 LTS
```
- Golang version :
```
[remek][~/go/src/github.com/argoproj]$ go version
go version go1.11.4 linux/amd64
```

**Comment by jessesuen** [comment]
The mentioned golang bug mentioned this is a golang 1.10 issue. Since we need to move to golang 1.11 will use this bug to handle the update.
