### ISSUE TITLE
make controller-image fails with No rule to make target 'controller'

### ISSUE THREAD

**Issue by remster** [argoproj/argo#1155]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT
**What happened**:
When building image on **minikube** as docker repo (i.e.: `eval $(minikube docker-env)`) and as instructed [here](https://github.com/argoproj/argo/blob/master/CONTRIBUTING.md).
```
[remek][~/.../github.com/argoproj/argo][master]$ make controller-image executor-image IMAGE_TAG=latest IMAGE_NAMESPACE=jessesuen DOCKER_PUSH=true
docker build -t argo-builder -f Dockerfile-builder .
Sending build context to Docker daemon  39.42kB
...
Successfully built f73583d2d77b
Successfully tagged argo-builder:latest
docker run --rm -v /home/remek/go/src/github.com/argoproj/argo:/root/go/src/github.com/argoproj/argo -v /home/remek/go/src/github.com/argoproj/argo/dist/pkg:/root/go/pkg -w /root/go/src/github.com/argoproj/argo argo-builder make controller
make: *** No rule to make target 'controller'.  Stop.
Makefile:128: recipe for target 'controller-linux' failed
make: *** [controller-linux] Error 2
```
full log attached
[argo_image_build.txt](https://github.com/argoproj/argo/files/2727335/argo_image_build.txt)

**What you expected to happen**:
Build to succeed
**How to reproduce it (as minimally and precisely as possible)**:
```make controller-image executor-image IMAGE_TAG=latest IMAGE_NAMESPACE=jessesuen DOCKER_PUSH=true```
**Anything else we need to know?**:

**Environment**:
- Argo version:
```
building master on sha 3561bff70ad6bfeca8967be6aa4ac24fbbc8ac27
```
- Kubernetes version :
```
N/A
```
- minikube version:
```
minikube version: v0.32.0
```

**Comment by jessesuen** [comment]
When using `eval $(minikube docker-env)`, it uses the minikube docker daemon as the remote docker host, which does not have access to the local files. We will be rewriting the makefile to not use Docker volume binding.
