### ISSUE TITLE
v2.2.1 manifest file references v2.2.0 docker images

### ISSUE THREAD

**Issue by dfarr** [argoproj/argo#1160]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Bug report

**What happened**:
Argo `v2.2.1` installed via the [GitHub manifest file](https://raw.githubusercontent.com/argoproj/argo/v2.2.1/manifests/install.yaml) references `v2.2.0` docker images for the following:
- argoproj/argoui
- argoproj/argoexec
- argoproj/workflow-controller

**What you expected to happen**:
Argo to install components with `v2.2.1` image.

**How to reproduce it (as minimally and precisely as possible)**:
```
$ kubectl apply -n argo -f https://raw.githubusercontent.com/argoproj/argo/v2.2.1/manifests/install.yaml
```

**Comment by alexmt** [comment]
v2.2.1 tag was pointing to wrong commit. It is fixed now.
