### ISSUE TITLE
Support initContainers

### ISSUE THREAD

**Issue by tcolgate** [argoproj/argo#1169]
**IFEATURE REQUEST?**:

I'm evaluating argo and noticed that the Workflow Spec doesn't allow for initContainers (it looks like you use an initContainer in the pods you generate, but don't allow additional ones to be provided).
Would you consider a PR to add this? We use initContainers for our secret injection, and it would be a lot easier if we could specify them directly.

We could add one via an mutating admission webhook, but I've avoided that so far.

**Comment by dtaniwaki** [comment]
I also want this feature, so I implemented it. 
https://github.com/argoproj/argo/pull/1183

**Comment by ghostsquad** [comment]
Sweet. Hope it gets merged!

Cheers,
Wes
