### ISSUE TITLE
Argo Workflows UI - Sort, group, filter support

### ISSUE THREAD

**Issue by ghostsquad** [argoproj/argo#1181]
*FEATURE REQUEST*
Argo 2.2.1

The Argo workflows UI does not offer a good way to group, sort, or filter workflows. It's basically just a static list, sorted by runtime (with the ability to filter on failures).

It would be great if this could be improved upon to group, sort, filter on name, label, timestamps, status, among other things. I suspect I'd have a hard time getting adoption for the tool if folks have problems finding their stuff.

**Comment by TewWe** [comment]
Isn't it a duplicate for this? https://github.com/argoproj/argo/issues/802

**Comment by ghostsquad** [comment]
Indeed. I'll post in that issue.
