### ISSUE TITLE
Argo controls in UI

### ISSUE THREAD

**Issue by buzzsurfr** [argoproj/argo#1182]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Feature Request

**What happened**:
Unable to control (make mutable changes) to argo workflows in UI.

**What you expected to happen**:
Per workflow, create buttons/menu for controls to delete, resubmit, resume, retry, suspend, or terminate a workflow.

**Anything else we need to know?**:
I'm willing to contribute!

**Environment**:
- Argo version:
```
$ argo version
argo: v2.2.1
  BuildDate: 2018-10-11T16:25:59Z
  GitCommit: 3b52b26190163d1f72f3aef1a39f9f291378dafb
  GitTreeState: clean
  GitTag: v2.2.1
  GoVersion: go1.10.3
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: "2018-12-13T19:44:10Z"
  compiler: gc
  gitCommit: eec55b9ba98609a46fee712359c7b5b365bdd920
  gitTreeState: clean
  gitVersion: v1.13.1
  goVersion: go1.11.2
  major: "1"
  minor: "13"
  platform: darwin/amd64
serverVersion:
  buildDate: "2018-12-06T23:13:14Z"
  compiler: gc
  gitCommit: 6bad6d9c768dc0864dab48a11653aa53b5a47043
  gitTreeState: clean
  gitVersion: v1.11.5-eks-6bad6d
  goVersion: go1.10.3
  major: "1"
  minor: 11+
  platform: linux/amd64
```

**Comment by paveq** [comment]
It would be nice to be able to submit workflow executions through the UI, making basis for CI system. This would require workflow template CRD (or workflow stored in configmap with specific labels), so selection and parameters can be applied through UI, or CLI.

This would separate building and maintaining of workflows from actual executions. Someone with access to execute a workflow would not need permission to alter the workflow steps.

**Comment by jessesuen** [comment]
We plan to have a more formalize API server which can handle this. Duping to https://github.com/argoproj/argo/issues/1331
