### ISSUE TITLE
Having multi container Templates / Workflow Steps

### ISSUE THREAD

**Issue by rummens** [argoproj/argo#1188]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST

**What happened**:
It seems that now each Workflow Step (template) can only have exactly one container. The resulting pod then also has only container. It would be benefical to be able to have multiple containers for each step, since Kubernetes support this (a Pod can have mutliple containers). This would allow us to have different containers talking to each other (inside one Pod).

**What you expected to happen**:
Instead of having only one "container" entry per template change it to "containers" and allow multiple images to be added. 

Another idea would be to create templates inside templates to allow multiple containers to be in the same pod.

**Anything else we need to know?**:
I am new to the project, so maybe there is already something similiar out there and I was just not able to find it :-)

Thanks
Marcel

**Comment by rummens** [comment]
Can be solved using sidecars...

**Comment by viggin543** [comment]
@rummens  can you provide more info regarding the sidecars silution ? many thanks !

**Comment by rummens** [comment]
> @rummens can you provide more info regarding the sidecars silution ? many thanks !

You can find more details here, KFP runs Argo under the hood. So most Argo features are in KFP as well.

https://argoproj.github.io/argo/examples/#docker-in-docker-using-sidecars
