### ISSUE TITLE
argo UI shows blank page

### ISSUE THREAD

**Issue by hamedhsn** [argoproj/argo#1215]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Bug
**What happened**:
I deployed argo as part of kuebflow new version 0.4.1 the UI show blank page. however, I can submit jobs wout any problem.
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
I dont see any log in ui container. 
**Anything else we need to know?**:
I inspect in chrome and all 200 in network section. 
however in Console part I see ` Uncaught SyntaxError: Unexpected token <`
**Environment**:
- Argo version:
```
$ argo version
argo: v2.2.1
  BuildDate: 2018-10-11T16:25:59Z
  GitCommit: 3b52b26190163d1f72f3aef1a39f9f291378dafb
  GitTreeState: clean
  GitTag: v2.2.1
  GoVersion: go1.10.3
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :
```
$ kubectl version -o yaml
➜  ks_app git:(master) ✗ kubectl version -o yaml
clientVersion:
  buildDate: 2018-07-10T10:13:58Z
  compiler: gc
  gitCommit: 91e7b4fd31fcd3d5f436da26c980becec37ceefe
  gitTreeState: clean
  gitVersion: v1.11.0
  goVersion: go1.10.3
  major: "1"
  minor: "11"
  platform: darwin/amd64
serverVersion:
  buildDate: 2018-12-06T23:13:14Z
  compiler: gc
  gitCommit: 6bad6d9c768dc0864dab48a11653aa53b5a47043
  gitTreeState: clean
  gitVersion: v1.11.5-eks-6bad6d
  goVersion: go1.10.3
  major: "1"
  minor: 11+
  platform: linux/amd64
```

**Other debugging information (if applicable)**:
- workflow result:
```
$ argo get <workflowname>
```
- executor logs:
```
$ kubectl logs <failedpodname> -c init
$ kubectl logs <failedpodname> -c wait
```
- workflow-controller logs:
```
$ kubectl logs -n kube-system $(kubectl get pods -l app=workflow-controller -n kube-system -o name)
```

**Comment by andreyvelich** [comment]
@hamedhsn 
If you deploy Argo as a part of Kubeflow, you can access to ArgoUI only using Ambassador reverse proxy right now. 
You can have a look at this: https://github.com/argoproj/argo/issues/716#issuecomment-433213190. 

If you want to access ArgoUI without Ambassador, you need to delete this environment variable (https://github.com/kubeflow/kubeflow/blob/master/kubeflow/argo/argo.libsonnet#L161) from ArgoUI deployment in Argo Package from Kubeflow repository.

**Comment by hamedhsn** [comment]
@andreyvelich thanks for the help..all sorted. 

/close
