### ISSUE TITLE
Remove pod after Workflow finished

### ISSUE THREAD

**Issue by DaspawnW** [argoproj/argo#1230]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST

**What happened**:
When a Workflow with a PersistentVolumeClaim is finished it marks the Persistent Volume Claim as "Terminating".

**What you expected to happen**:
Persistent Volume Claims are sometimes very expensive, especially when they are large. To prevent high billing it would be nice if there is an option to automatically delete the PVC after the Workflow has finished. This would be one of the biggest advantages over Jobs in Kubernetes, they can not create a PVC or remove it when the Job has finished.
I know that the Pod then must also be deleted with the Logs, but if an Artifact repository is configured this is not such relevant, when it is an option.

**Comment by jackywu** [comment]
I have submit a PR. If you are interested in the feature，you can vote it there #1234 。

**Comment by jessesuen** [comment]
Duping to https://github.com/argoproj/argo/issues/1098
