### ISSUE TITLE
Unable to configure Minio

### ISSUE THREAD

**Issue by gaussianblurs** [argoproj/argo#1231]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Bug report

**What happened**:
When I try to run the command `minikube service --url argo-artifacts` after deploying Minio via Helm, it hangs forever. If i try to run `kubectl get service argo-artifacts` it says "Error from server (NotFound): services "argo-artifacts" not found"
Also, when I run `kubectl get svc --namespace default -l app=argo-artifacts-minio` it says "No resources found."

**What you expected to happen**:
obtain an external IP in order to access Minio's UI

**How to reproduce it (as minimally and precisely as possible)**:
Follow the Argo quickstart tutorial: https://github.com/argoproj/argo/blob/master/ARTIFACT_REPO.md

**Anything else we need to know?**:

**Environment**:
- Argo version: 
```
$ argo version
argo: v2.2.1
  BuildDate: 2018-10-11T16:26:28Z
  GitCommit: 3b52b26190163d1f72f3aef1a39f9f291378dafb
  GitTreeState: clean
  GitTag: v2.2.1
  GoVersion: go1.10.3
  Compiler: gc
  Platform: linux/amd64
```
- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: "2019-02-22T12:22:59Z"
  compiler: gc
  gitCommit: ddf47ac13c1a9483ea035a79cd7c10005ff21a6d
  gitTreeState: archive
  gitVersion: v1.13.0
  goVersion: go1.11.5
  major: "1"
  minor: "13"
  platform: linux/amd64
serverVersion:
  buildDate: "2019-02-01T20:00:57Z"
  compiler: gc
  gitCommit: 721bfa751924da8d1680787490c54b9179b1fed0
  gitTreeState: clean
  gitVersion: v1.13.3
  goVersion: go1.11.5
  major: "1"
  minor: "13"
  platform: linux/amd64
```

Any help is appreciated

**Comment by loupipalien** [comment]
I got same error, and i found  `EXTERNAL-IP`  was always `<pending>`   when i  run ` kubectl get all -l release=argo-artifacts`
```
NAME                                        READY   STATUS    RESTARTS   AGE
pod/argo-artifacts-minio-66dd6d9db8-tf92w   1/1     Running   0          12m

NAME                           TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
service/argo-artifacts-minio   LoadBalancer   10.110.109.176   <pending>     9000:30626/TCP   12m

NAME                                   READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/argo-artifacts-minio   1/1     1            1           12m

NAME                                              DESIRED   CURRENT   READY   AGE
replicaset.apps/argo-artifacts-minio-66dd6d9db8   1         1         1       12m
```
Do you solved it?

**Comment by loupipalien** [comment]
> I got same error, and i found `EXTERNAL-IP` was always `<pending>` when i run ` kubectl get all -l release=argo-artifacts`
> 
> ```
> NAME                                        READY   STATUS    RESTARTS   AGE
> pod/argo-artifacts-minio-66dd6d9db8-tf92w   1/1     Running   0          12m
> 
> NAME                           TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
> service/argo-artifacts-minio   LoadBalancer   10.110.109.176   <pending>     9000:30626/TCP   12m
> 
> NAME                                   READY   UP-TO-DATE   AVAILABLE   AGE
> deployment.apps/argo-artifacts-minio   1/1     1            1           12m
> 
> NAME                                              DESIRED   CURRENT   READY   AGE
> replicaset.apps/argo-artifacts-minio-66dd6d9db8   1         1         1       12m
> ```
> Do you solved it?

After google, i find a [question](https://stackoverflow.com/questions/44110876/kubernetes-service-external-ip-pending) on stackoverflow that  answer is minukube doesn't support  EXTERNAL-IP. 
We could set it manally, for detail see [here](https://github.com/kubernetes/kube-deploy/issues/220#issuecomment-311600192)

**Comment by DungLai** [comment]
same problem
