### ISSUE TITLE
Resource creation where template has same parameter templating

### ISSUE THREAD

**Issue by janvdvegt** [argoproj/argo#1239]
BUG REPORT / FEATURE REQUEST

I want a Workflow to create (and watch) a resource, the template for this resource uses similar templating to Argo which means I'm getting errors that say Argo cannot resolve the parameters.

@jessesuen mentioned on Slack that Argo would silently not substitute parameters that it could not resolve which would be a nice solution to this issue. Another issue would be to have some kind of escaping mechanism.

You can reproduce it by adding this to a Workflow spec:

    templates:
    - name: step
      resource:
        action: create
        manifest: |-
          spec: 
            name: {{.WorkerID}}

**Comment by janvdvegt** [comment]
@jessesuen helped me on Slack, it looks like this will fix it: https://github.com/jessesuen/argo/commit/61d36981267f46388f7ee251a0f490170f257c6a I am going to test it now

**Comment by janvdvegt** [comment]
This fix did indeed work, now it just passes unresolved variables on

**Comment by jessesuen** [comment]
https://github.com/argoproj/argo/blob/master/docs/variables.md

**Comment by jessesuen** [comment]
Resolved in https://github.com/argoproj/argo/pull/1283
