### ISSUE TITLE
mascot logo looks wrong

### ISSUE THREAD

**Issue by fiendish** [argoproj/argo#1246]
**Is this a BUG REPORT or FEATURE REQUEST?**:

Unsure. Branding?

**What happened**:

https://github.com/argoproj/argo/blob/master/argo.png Looks wrong on my screen. The helmet appears to be drawn behind the head instead of over it. That is a helmet, right? If it's a window, why is the mascot looking away from it? God, I hope it's not a dinner plate. That would be grim. Anyway, it looks like this...

![img_20190305_120556340_hdr](https://user-images.githubusercontent.com/201996/53823189-4125da00-3f3f-11e9-90ce-7810060fa3ab.jpg)

**What you expected to happen**:

Look more like it's wearing a helmet, I guess.

**Comment by alexec** [comment]
I think this is how it is.
