### ISSUE TITLE
Unable to access workflow.status from within DAG Task

### ISSUE THREAD

**Issue by eggsbenjamin** [argoproj/argo#1249]
**Is this a BUG REPORT or FEATURE REQUEST?**:

BUD REPORT

**What happened**:

Attempted to access global var `workflow.status` from within DAG task

**What you expected to happen**:

Varibale accessible

**How to reproduce it (as minimally and precisely as possible)**:

Create a dag with a `when` property e.g. `when: "{{workflow.status}} == Success"`

**Anything else we need to know?**:

workflow.name is accessible so it appears globals are meant to be accessible from here

**Environment**:
- Argo version:
```
$ argo version

argo: v2.2.1
  BuildDate: 2018-10-11T16:25:59Z
  GitCommit: 3b52b26190163d1f72f3aef1a39f9f291378dafb
  GitTreeState: clean
  GitTag: v2.2.1
  GoVersion: go1.10.3
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :
```
$ kubectl version -o yaml

clientVersion:
  buildDate: 2018-11-27T01:15:02Z
  compiler: gc
  gitCommit: 435f92c719f279a3a67808c80521ea17d5715c66
  gitTreeState: clean
  gitVersion: v1.12.3
  goVersion: go1.11.2
  major: "1"
  minor: "12"
  platform: darwin/amd64
serverVersion:
  buildDate: 2018-03-26T16:44:10Z
  compiler: gc
  gitCommit: fc32d2f3698e36b93322a3465f63a14e9f0eaead
  gitTreeState: clean
  gitVersion: v1.10.0
  goVersion: go1.9.3
  major: "1"
  minor: "10"
  platform: linux/amd64
```

**Other debugging information (if applicable)**:
- workflow result:
```
$ argo get <workflowname>
```
- executor logs:
```
$ kubectl logs <failedpodname> -c init
$ kubectl logs <failedpodname> -c wait
```
- workflow-controller logs:
```
$ kubectl logs -n kube-system $(kubectl get pods -l app=workflow-controller -n kube-system -o name)
```

**Comment by jessesuen** [comment]
`{{workflow.status}}` is only available in exitHandlers: 

https://github.com/argoproj/argo/blob/master/docs/variables.md#exit-handler

I suspect that you are trying to use it somewhere as part of the main template invocation and not from within an onExit template. Please reopen if I'm incorrect.
