### ISSUE TITLE
BUG: WorkflowStatus and related objects missing from the openapi spec

### ISSUE THREAD

**Issue by cristianpop** [argoproj/argo#1251]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT
**What happened**:
WorkflowStatus and related objects are missing in the openapi spec. As a result, complete working clients cannot be automatically generated using openapi-generator.
**What you expected to happen**:
WorkflowStatus and related objects should exist in the openapi spec.

**Comment by shimmerjs** [comment]
I would love to do this for TypeScript and give it back to the community, I can try to figure out what the definition should look like and provide a PR for it.

**Comment by strangemonad-faire** [comment]
+1 to trying to get this fixed. Would love to get the Workflow CRD loaded in the IntelliJ kubernetes plugin

**Comment by nfillot** [comment]
It seems that the openapi generation is disabled for WorkflowStatus and NodeStatus.
https://github.com/argoproj/argo/blob/88fcc70dcf6e60697e6716edc7464a403c49b27e/pkg/apis/workflow/v1alpha1/types.go#L492

Is there a specific reason for this @jessesuen ? Thank you

**Comment by dseapy** [comment]
I believe this can be closed now: https://github.com/argoproj/argo/pull/1614
