### ISSUE TITLE
serviceaccount in kube-system to Argo deployed namespace?

### ISSUE THREAD

**Issue by emichaf** [argoproj/argo#1255]
Is it possible to run argo in any namespace without adding serviceaccount to kube-system

ex)
kubectl create serviceaccount --namespace kube-system argo

to

kubectl create serviceaccount --namespace argo-namespace argo   ?

**Comment by jessesuen** [comment]
Argo's service account does not live in kube-system. It lives in the namespace wherever the controller is running in, which you decide during installation. The default install manifests, install into `argo` namespace by default:

https://github.com/argoproj/argo/blob/master/manifests/install.yaml
