### ISSUE TITLE
git checkout via ssh insecure

### ISSUE THREAD

**Issue by discordianfish** [argoproj/argo#1260]
**BUG REPORT**:
argo doesn't validate the ssh host key when checking out artifacts from git:

https://github.com/argoproj/argo/blob/master/workflow/artifacts/git/git.go#L37

This poses a huge risk given that it's not uncommon to execute the artifact. That allows a simple man in the middle attack to run code in the context of a pod. I would have disclosed this privately given how severe I consider this, if it weren't for the fact that this is intentionally setup that way.

**Comment by jessesuen** [comment]
FWIW, the reasoning behind this change is described here: https://github.com/argoproj/argo/pull/939

My mistake was taking following statement at face value:
> Even if we allow then to add a list of keys and dynamically get it it's gonna be the same level of security as InsecureIgnoreHostKey

Now that I understand the problem, I believe the proper solution is to bake in the well known provider's SSH keys into the executor, and provide an insecure option as an escape hatch for users who need this behavior.

**Comment by discordianfish** [comment]
Yes, that's true, using ssh-keyscan as before isn't more secure either. Baking in some default seems sane. In prod I'd just mount a configmap to /etc/ssh/ssh_known_hosts (in fact I'm doing that for argo-events sensors)
