### ISSUE TITLE
why spec.arguments.parameters.name cannot use underscore?

### ISSUE THREAD

**Issue by ghost** [argoproj/argo#1270]
Why set a restrict that cannot allow spec.arguments.parameters.name use underscore?

We have many config fields that use underscore, then I muse change '_' to '-' to be a parameters.name, it's a little weried 😂

**Comment by Ark-kun** [comment]
It was fixed in https://github.com/argoproj/argo/pull/1048, but there was no Argo release since October =(

**Comment by jessesuen** [comment]
v2.3 has this now.
