### ISSUE TITLE
Not possible to use Argo in several namespaces

### ISSUE THREAD

**Issue by emichaf** [argoproj/argo#1273]
Deploying Argo to several namespaces, but it's not possible to use Argo in several namespaces (isolated)!

is it possible to isolate workflow execution & GUI output for deployments in several namespaces?

using instanceid or similar ?

**Comment by sarabala1979** [comment]
are you trying to deploy more than one argo workflow and GUI in the same cluster?

**Comment by emichaf** [comment]
Yes, can deploy Argo including the GUI and Argo-events in different namespaces, but all Argo GUIs is vizualizing all workflows executed from all namespaces....

**Comment by sarabala1979** [comment]
Argo UI 2.2.1 doesn't support to watch one namespace. But the Master has the implementation. Argo UI will be released soon. 
Here the steps to configure the UI on namespace specific https://github.com/argoproj/argo/issues/1114#issuecomment-444741682

**Comment by jessesuen** [comment]
v2.3 argo UI should now support this.

**Comment by fchenTelus** [comment]
@jessesuen Supported in v2.3 based on env var FORCE_NAMESPACE_ISOLATION, or can we use something else now?
