### ISSUE TITLE
Large workflow pod state synchronization has a delay

### ISSUE THREAD

**Issue by xianlubird** [argoproj/argo#1276]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT 
**What happened**:
In a large workflow, seems have 5000 step. The real pod has Completed, but the workflow node is marked ContainerCreating, seems state a few minutes ago.

**Environment**:
- Argo version:
```
master branch build
$ argo version
```
- Kubernetes version :
```
v1.11.8
```

Anyone can give me some advice?

```
[root@master1 ~]# kubectl get pods test-xxxxxxx -n pext
NAME                          READY     STATUS      RESTARTS   AGE
test-xxxxxxx               0/2       Completed   0          24m

Workflow  State

◷ test-xxxxxxx-2221(0)       test-xxxxxxx   23m       ContainerCreating
```

**Comment by rtanner-wiley** [comment]
I'm experiencing this issue as well

**Comment by sarabala1979** [comment]
#1264 will support this large workflow
