### ISSUE TITLE
Secrets should be passed to pods using volume mounts instead of API calls

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo#1278]
Currently workflow service account pods need GET secret access to get the secret of some artifact location for archive. Instead of this, workflow controller should pass secrets to the pod using the downward API. This way, pods no longer need get secret credentials.

**Comment by jessesuen** [comment]
The work here is to replace:
https://github.com/argoproj/argo/blob/master/workflow/executor/executor.go#L571

with:
https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables

Additional notes:
Even though we've remove GET secret privileges for the service account associated with the workflow, in general the ability to simply *create* pods, means that someone can gain access to a secret by virtue of volume mounting a specific secret by name as a file in the pod. This is a kubernetes limitation:

https://github.com/kubernetes/kubernetes/issues/4957

**Comment by discordianfish** [comment]
Is this really the downward api? Guess that's what confused me when we chatted about this in slack.

**Comment by jessesuen** [comment]
You're right. It is not the downward API, it was done via volume mounts.

Fixed in https://github.com/argoproj/argo/pull/1318
