### ISSUE TITLE
Argo will support cwl(common workflow language) in the future?

### ISSUE THREAD

**Issue by xianlubird** [argoproj/argo#1284]
Airflow already support cwl, so argo will also support cwl in the future ?

**Comment by cuericlee** [comment]
CWL/WDL is used in assemble workflow for a couple of workload, especially for Genomics analysis/HPC. we might need an easy way to convert CWL to argo workflow to allow more user to migrate their workflow to argo/kubenetes workflow.

**Comment by jessesuen** [comment]
Duping to https://github.com/argoproj/argo/issues/873
