### ISSUE TITLE
CLI Does Not Honor metadata.namespace

### ISSUE THREAD

**Issue by discreet** [argoproj/argo#1288]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Bug

**What happened**:
When setting `metadata.namespace` in the workflow yaml the cli does not honor that configuration and wants to use the namespace in the current context

**What you expected to happen**:
I would expect the cli to deploy the workflow to the namespace listed in the yaml

**How to reproduce it (as minimally and precisely as possible)**:
Set `metadata.namespace` in a workflow yaml

**Environment**:
- Argo version:
argo: v2.2.1
  BuildDate: 2018-10-11T16:25:59Z
  GitCommit: 3b52b26190163d1f72f3aef1a39f9f291378dafb
  GitTreeState: clean
  GitTag: v2.2.1
  GoVersion: go1.10.3
  Compiler: gc
  Platform: darwin/amd64

- Kubernetes version :
clientVersion:
  buildDate: 2018-12-16T04:39:52Z
  compiler: gc
  gitCommit: b1d75deca493a24a2f87eb1efde1a569e52fc8d9
  gitTreeState: clean
  gitVersion: v1.11.6
  goVersion: go1.10.3
  major: "1"
  minor: "11"
  platform: darwin/amd64

serverVersion:
  buildDate: 2018-12-16T04:30:10Z
  compiler: gc
  gitCommit: b1d75deca493a24a2f87eb1efde1a569e52fc8d9
  gitTreeState: clean
  gitVersion: v1.11.6
  goVersion: go1.10.3
  major: "1"
  minor: "11"
  platform: linux/amd64

**Comment by Ark-kun** [comment]
> When setting `metadata.namespace` in the workflow yaml the cli does not honor that configuration and wants to use the namespace in the current context

I think it's OK if the CLI can override the namespace.
Does CLI ignore the workflow namespace even if there is no `--namespace` specified?
