### ISSUE TITLE
Proposal: Modify AMI search to query a regex pattern and select latest

### ISSUE THREAD

**Issue by lorengordon** [argoproj/argo#129]
Different AWS partitions (and regions) may have different AMI names/versions available. In the aws-us-gov partition, the current default AMI name, `AX_AWS_IMAGE_NAME=k8s-1.6-debian-jessie-amd64-hvm-ebs-2017-05-02`, is not available. But the AMI that *is* available there, `k8s-1.6-debian-jessie-amd64-hvm-ebs-2017-07-07`, is not available in the aws partition. 🤦‍♂️ 

To simplify the initial cluster install experience, I propose using a regex pattern to search for the AMI name, sorting the list, and selecting the latest. Something like, `^k8s-1.6-debian-jessie-amd64-hvm-ebs-[0-9]{4}-[0-9]{2}-[0-9]{2}$`.

If a user _wants_ to pin to a particular AMI name/version, they can still override the ENV.

@lcjlcj @shrinandj @abhinavdas

**Comment by zhan849** [comment]
I'm hesitated to add this regex into picture as latest does not mean its tested. We specifically hardcode an AMI name in the community version as we tested it, just as we freeze all our upstream package versions. Plus, the community did not say AMI was named according to this regex officially so theoretically we cannot find an AMI, or we might hit something ancient if naming scheme is changed.

One solution I would prefer:
for aws partition, use `k8s-1.6-debian-jessie-amd64-hvm-ebs-2017-05-02`, for us-gov partition, use `k8s-1.6-debian-jessie-amd64-hvm-ebs-2017-07-07`, once we have an GOV account and test it out.

Thoughts?

**Comment by lorengordon** [comment]
Both the partition and the region are constraints. There is no guarantee that every region in the aws partition will have an AMI named `k8s-1.6-debian-jessie-amd64-hvm-ebs-2017-05-02`.

There are also more partitions than aws and aws-us-gov, some of which are not particularly public. I don't think it is possible to hard code this value to tested AMIs that will work for every partition and every region.

**Comment by jessesuen** [comment]
Closing v1 issues.
