### ISSUE TITLE
Fish shell completions

### ISSUE THREAD

**Issue by jerr0328** [argoproj/argo#1292]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Feature request

**What happened**:
argo completions only has completions for bash and zsh.

**What you expected to happen**:
I would like to have completions as well for the fish shell.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
See: https://fishshell.com/docs/current/index.html#completion for instructions about completions

**Comment by jerr0328** [comment]
I'm closing since this hasn't had any activity, and I don't use argo anymore.

**Comment by RafalSkolasinski** [comment]
Please re-open, this are still needed and not provided to this day
```
$ argo completion fish
Invalid shell 'fish'. The supported shells are bash and zsh.
```

```
$ argo version
argo: v3.4.0
  BuildDate: 2022-09-19T17:54:12Z
  GitCommit: 97328f1ed3885663b780f43e6b553208ecba4d3c
  GitTreeState: clean
  GitTag: v3.4.0
  GoVersion: go1.18.5
  Compiler: gc
  Platform: linux/amd64
```

**Comment by RafalSkolasinski** [comment]
Seems this was just fixed through https://github.com/argoproj/argo-workflows/issues/13127 and https://github.com/argoproj/argo-workflows/pull/13128

A great day to be alive!
