### ISSUE TITLE
[Help Need] Suspend/resume workflow programmatically.

### ISSUE THREAD

**Issue by fenghejingchi** [argoproj/argo#1327]
**Is this a BUG REPORT or FEATURE REQUEST?**:

**What happened**:
Have no idea how to suspend/resume a workflow through API

**Anything else we need to know?**:
We use Rest Python API to create/get/delete the workflow, which is straight forward. However, have idea how to suspend/resume a workflow. Searched web, only find https://github.com/argoproj/argo/issues/759 , but still have no idea how to control the workflow through API.

**Comment by jessesuen** [comment]
@fenghejingchi 

Here is suspend logic:
https://github.com/argoproj/argo/blob/75b28a37b923e278fc89fd647f78a42e7a3bf029/workflow/util/util.go#L251

Here is resume logic:
https://github.com/argoproj/argo/blob/75b28a37b923e278fc89fd647f78a42e7a3bf029/workflow/util/util.go#L280

**Comment by fenghejingchi** [comment]
Thx, finished that. Thx
