### ISSUE TITLE
Allow downstream tasks to know the names of upstream pods.

### ISSUE THREAD

**Issue by Ark-kun** [argoproj/argo#1329]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST

Scenario:
Upstream tasks used `{{pod.name}}` in to generate some data storage location (e.g. a BigTable table).
Downstream component wants to know the `{{pod.name}}` of upstream.

Currently doing this requires explicitly writing the pod name to file and then telling Argo to pick it up.

This can be made simple by just allowing output parameters with explicitly set `value` (instead of `valueFrom`). AFAIK, this only requires the validator change (I need to check the placeholder resolution in the outputs though).

Template that does not output pod name:

    container:
        command: [myprog.py, arg1, arg2, arg3]

Template that outputs pod name (current workaround):

    container:
        command: [sh, -c, 'echo "{{pod.name}}" > /tmp/pod_name.txt && "$*"',
            myprog.py, arg1, arg2, arg3
        ]
    outputs:
        parameters:
        - name: pod-name
          valueFrom:
            path: /tmp/pod_name.txt

Template that outputs pod name (proposed syntax):

    container:
        command: [myprog.py, arg1, arg2, arg3]
    outputs:
        parameters:
        - name: pod-name
          value: "{{pod.name}}"

**Comment by jessesuen** [comment]
Request is reasonable, but I think we can use the existing `valueFrom.parameter` syntax:

```
container:
    command: [myprog.py, arg1, arg2, arg3]
outputs:
    parameters:
    - name: pod-name
      valueFrom:
        parameter: "{{pod.name}}"
```

**Comment by Ark-kun** [comment]
> Request is reasonable, but I think we can use the existing `valueFrom.parameter` syntax:

Unfortunately, this does not work. `valueFrom.parameter` only works for DAGs/steps.
Validator throws the following error if the container template output parameter is missing `valueFrom.Path`
https://github.com/argoproj/argo/blob/4e37a444bde2a034885d0db35f7b38684505063e/workflow/validate/validate.go#L550

I've submitted a small PR to allow output parameters with `.value`, not only `.valueFrom`: https://github.com/argoproj/argo/pull/1336
It only changes the validator, since the execution code already handles this fine.
