### ISSUE TITLE
Configuration Management does not support special character value

### ISSUE THREAD

**Issue by sytianhe** [argoproj/argo#133]
![screen shot 2017-08-31 at 4 03 17 pm](https://user-images.githubusercontent.com/605748/29948842-00421d72-8e66-11e7-8fb4-586308852b21.png)

**Comment by wokeGit** [comment]
Do we should allow all special characters?
Do we should validate anything for that value?

**Comment by sytianhe** [comment]
@wokeGit 
key: r”^[-0-9A-Za-z_]+$”
value: no restrictions

**Comment by pratulw** [comment]
@alexmt Please  port this to 1.0 branch

**Comment by alexmt** [comment]
done
