### ISSUE TITLE
Argo UI via NPM

### ISSUE THREAD

**Issue by TofuLover718** [argoproj/argo#1337]
**Is this a BUG REPORT or FEATURE REQUEST?**:
I couldn't find a way to leave a comment on the argo-ui repo at: 
https://github.com/argoproj/argo-ui

**What happened**:

I ran `npm i argo-ui` on my React project per https://www.npmjs.com/package/argo-ui

But I received an error when trying to import argo-ui `import components from 'argo-ui'`

```
Failed to compile.

./node_modules/argo-ui/bundle/app/shared/styles/main.scss (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/sass-loader/lib/loader.js??ref--6-oneOf-5-3!./node_modules/argo-ui/bundle/app/shared/styles/main.scss)
Module not found: Can't resolve './assets/fonts/argo-icon.eot?51d43a1be01e193a568d7d6a26b14f4c' in '/Users/hongcao/Projects/testArgo/my-app/node_modules/argo-ui/bundle/app/shared/styles'
```

**What you expected to happen**:

Components that can be used with my React project

**How to reproduce it (as minimally and precisely as possible)**:

`npm init react-app my-app`
`npm i argo-ui`
 
Then import components from argo-ui
`import components from 'argo-ui'`

**Anything else we need to know?**:
Node: v10.15.0
Npm: v6.9.0

**Comment by alexec** [comment]
We no longer support the Argo UI.

**Comment by githubczy** [comment]
Did you solve it ？I had the same error
