### ISSUE TITLE
Proposal: Improve YAML preview with nested display

### ISSUE THREAD

**Issue by rahuldhide** [argoproj/argo#134]
After the recent YAML changes, we are displaying all YAMLs (used for workflow steps) in the YAML preview panel. When the user highlights a step, we just highlight the step name and user has to scroll to see the template details. We can simplify this interaction by using a nested display (tree view) for the YAML code.

As shown in the attached prototype, when user selects a step, we can highlight the entire code block and also allow user to review the nested templates.

![yaml_preview1](https://user-images.githubusercontent.com/30275450/29949257-5cbfd4ac-8e68-11e7-857c-b5bad3f8069b.png)

![yaml_preview2](https://user-images.githubusercontent.com/30275450/29949261-6185368a-8e68-11e7-951c-368138a1a48a.png)

**Comment by edlee2121** [comment]
Nice!
Selecting a nested workflow node on the graphical display would expand and highlight the appropriate section of yaml?

**Comment by rahuldhide** [comment]
Yes. We will highlight the related yaml.

**Comment by jessesuen** [comment]
Closing v1 issues.
