### ISSUE TITLE
2.3.0-rc2 withParams and withItems inflation is shifted

### ISSUE THREAD

**Issue by louis-murray** [argoproj/argo#1340]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug report

**What happened**:
repeated steps/tasks using `withParams` and `withItems` have values inflated from the previous index of the loop after the first iteration. 

**What you expected to happen**:
values inflated are from the current index

**How to reproduce it (as minimally and precisely as possible)**:
for withParams: https://github.com/argoproj/argo/blob/master/examples/loops-param-result.yaml

for withItems: https://github.com/argoproj/argo/blob/master/examples/loops.yaml

**Anything else we need to know?**:
previously to the release of 2.3.0-rc2 I was using docker images I built directly off master when head was https://github.com/argoproj/argo/commit/6607dca93db6255a2abc30ae76b5f935fce5735d. Looking at the commits since then I think the issue arose in https://github.com/argoproj/argo/commit/64370a2d185db66a8d2188d986c52a3b73aaf92b#diff-799231f95f7b5d8d9fe078b2cc4ebc1dR186

**Environment**:
- Argo version: 2.3.0-rc2
- Kubernetes version : 1.13.5

**Other debugging information (if applicable)**:
- workflow result:

*withParams*
```
Name:                loops-param-result-bk67x
Namespace:           workflows
ServiceAccount:      default
Status:              Succeeded
Created:             Wed Apr 24 17:02:29 -0400 (48 seconds ago)
Started:             Wed Apr 24 17:02:29 -0400 (48 seconds ago)
Finished:            Wed Apr 24 17:03:17 -0400 (now)
Duration:            48 seconds

STEP                         PODNAME                              DURATION  MESSAGE
 ✔ loops-param-result-bk67x                                                 
 ├---✔ generate              loops-param-result-bk67x-1343984828  9s        
 └-·-✔ sleep(0:20)           loops-param-result-bk67x-826827500   24s       
   ├-✔ sleep(10:30)          loops-param-result-bk67x-2762696320  33s       
   ├-✔ sleep(1:21)           loops-param-result-bk67x-1086122870  26s       
   ├-✔ sleep(2:22)           loops-param-result-bk67x-858747572   25s       
   ├-✔ sleep(3:23)           loops-param-result-bk67x-199114722   26s       
   ├-✔ sleep(4:24)           loops-param-result-bk67x-238287044   28s       
   ├-✔ sleep(5:25)           loops-param-result-bk67x-3020122742  28s       
   ├-✔ sleep(6:26)           loops-param-result-bk67x-4192398476  30s       
   ├-✔ sleep(7:27)           loops-param-result-bk67x-3143246346  32s       
   ├-✔ sleep(8:28)           loops-param-result-bk67x-1592555596  30s       
   └-✔ sleep(9:29)           loops-param-result-bk67x-1728834166  34s 
```

logs for `sleep(2:22)`:
```
$ argo logs -n workflows loops-param-result-bk67x-858747572
sleeping for 21 seconds
done
```
*withItems*
```
Name:                loops-g66xb
Namespace:           workflows
ServiceAccount:      default
Status:              Succeeded
Created:             Wed Apr 24 17:11:25 -0400 (17 seconds ago)
Started:             Wed Apr 24 17:11:26 -0400 (16 seconds ago)
Finished:            Wed Apr 24 17:11:42 -0400 (now)
Duration:            16 seconds

STEP                                   PODNAME                 DURATION  MESSAGE
 ✔ loops-g66xb                                                           
 └-·-✔ print-message(0:hello world)    loops-g66xb-1462947920  13s       
   └-✔ print-message(1:goodbye world)  loops-g66xb-3931292484  13s
```
logs for print-message(1:goodbye world):
```
 _____________ 
< hello world >
 ------------- 
    \
     \
      \     
                    ##        .            
              ## ## ##       ==            
           ## ## ## ##      ===            
       /""""""""""""""""___/ ===        
  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~   
       \______ o          __/            
        \    \        __/             
          \____\______/   
```

**Comment by illagrenan** [comment]
I can confirm that I have the same issue with `withParams: output-list-from-previous-task` and `v2.3.0-rc2`.

**Comment by elikatsis** [comment]
I built out of 6607dca93db6255a2abc30ae76b5f935fce5735d and this bug happens as well.

Could you check once more, if it is not an inconvenience, and report back so I can keep checking on what the problem is?

**Comment by elikatsis** [comment]
Hello, thank you for reporting this bug! I had made a mistake there :sweat_smile: 

I opened #1345 which fixes this.

**Comment by louis-murray** [comment]
thanks for making a PR fixing it!

**Comment by discordianfish** [comment]
I think I might run into the same problem but merely using the same template several times (no withParams etc):

I have a step `build-experimentation-gpu` with the input parameter suffix set to `-experimentation-gpu`. the template definition that this task is using has an arg `- "--destination={{workflow.parameters.image}}{{inputs.parameters.suffix}}:{{inputs.parameters.tag}}"` but the pod for this task has `"--destination=…-experimentation:…"`
