### ISSUE TITLE
Example workflow artifact-path-placeholders.yaml fails to submit to argo

### ISSUE THREAD

**Issue by arush0** [argoproj/argo#1343]
**Is this a BUG REPORT or FEATURE REQUEST?**:

Bug Report

**What happened**:

```argo submit examples/artifact-path-placeholders.yaml```
returns
```Failed to submit workflow: templates.head-lines: failed to resolve {{inputs.artifacts.text.path}}```

**What you expected to happen**:

The workflow is submitted and outputs the artifact `text`

**How to reproduce it (as minimally and precisely as possible)**:

I am running on minikube v1.0.0 and followed the "Argo Getting Started" tutorial for set up. Submit the example `artifact-path-placeholders.yaml`

**Anything else we need to know?**:

**Environment**:
- Argo version:
```
$ argo version
argo: v2.2.1
  BuildDate: 2018-10-11T16:25:59Z
  GitCommit: 3b52b26190163d1f72f3aef1a39f9f291378dafb
  GitTreeState: clean
  GitTag: v2.2.1
  GoVersion: go1.10.3
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: "2019-04-19T22:12:47Z"
  compiler: gc
  gitCommit: b7394102d6ef778017f2ca4046abbaa23b88c290
  gitTreeState: clean
  gitVersion: v1.14.1
  goVersion: go1.12.4
  major: "1"
  minor: "14"
  platform: darwin/amd64
serverVersion:
  buildDate: "2019-03-25T15:45:25Z"
  compiler: gc
  gitCommit: 641856db18352033a0d96dbc99153fa3b27298e5
  gitTreeState: clean
  gitVersion: v1.14.0
  goVersion: go1.12.1
  major: "1"
  minor: "14"
  platform: linux/amd64
```

**Comment by Ark-kun** [comment]
This support for this feature is only added in Argo 2.4 which has not been released yet.

**Comment by arush0** [comment]
I see, my mistake. Thank you, I'll close this issue.
