### ISSUE TITLE
S3 credentials from metadata server broken in v2.3.0-rc2

### ISSUE THREAD

**Issue by jsharpe** [argoproj/argo#1355]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Bug report

**What happened**:

Upgraded to 2.3.0-rc2 from 2.2.1 and now my pod fails to create with the error message:

[spec.volumes[3].secret.secretName: Required value, spec.volumes[3].secret.items[0].key: Required value, spec.volumes[3].secret.items[0].path: Required value, spec.volumes[3].name: Required value, spec.containers[0].volumeMounts[2].name: Required value, spec.containers[0].volumeMounts[2].name: Not found: "", spec.initContainers[0].volumeMounts[1].name: Required value, spec.initContainers[0].volumeMounts[1].name: Not found: ""]

**What you expected to happen**:

I can pull a static artifact from s3 without having to specify secret access keys as these are provided to the container via the ECS metadata server via kiam / kube2iam.

**How to reproduce it (as minimally and precisely as possible)**:

Create a workflow step with an s3 repo input without specifying the secrets for accessing AWS but provide an annotation on the pod to assume the role via the metadata server.

**Anything else we need to know?**:

I suspect this is a result of PR #1302 

**Environment**:
- Argo version:
```
$ argo version
argo: v2.3.0-rc2
  BuildDate: 2019-04-21T08:17:50Z
  GitCommit: bb1bfdd9106d9b64aa2dccf8d3554bdd31513cf8
  GitTreeState: clean
  GitTag: v2.3.0-rc2
  GoVersion: go1.11.5
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: "2019-04-19T22:12:47Z"
  compiler: gc
  gitCommit: b7394102d6ef778017f2ca4046abbaa23b88c290
  gitTreeState: clean
  gitVersion: v1.14.1
  goVersion: go1.12.4
  major: "1"
  minor: "14"
  platform: darwin/amd64
serverVersion:
  buildDate: "2019-03-25T15:19:22Z"
  compiler: gc
  gitCommit: 2166946f41b36dea2c4626f90a77706f426cdea2
  gitTreeState: clean
  gitVersion: v1.13.5
  goVersion: go1.11.5
  major: "1"
  minor: "13"
  platform: linux/amd64
```

**Other debugging information (if applicable)**:
- workflow result:
```
$ argo get <workflowname>
```
- executor logs:
```
$ kubectl logs <failedpodname> -c init
$ kubectl logs <failedpodname> -c wait
```
- workflow-controller logs:
```
$ kubectl logs -n kube-system $(kubectl get pods -l app=workflow-controller -n kube-system -o name)
```

**Comment by jessesuen** [comment]
@jsharpe can you supply what the workflow template using the s3 artifacts look like?
