### ISSUE TITLE
Conditionally annotate outputs of script template only when consumed

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo#1359]
**Is this a BUG REPORT or FEATURE REQUEST?**: FEATURE REQUEST

**What happened**:

Currently, the entire output of script templates are annotated as an output of a pod, with the assumption that the output will be consumed by a later step in the workflow. Oftentimes, users are not aware of this behavior and hit the following error:

```
failed to save outputs: Pod "demo-dwb7r-3741205847" is invalid: metadata.annotations: Too long: must have at most 262144 characters
```

Script templates are useful in and of itself, just as a convenience function to run custom logic, and the output is not consumed anywhere. In this situation, a useful feature would be to conditionally annotate the pod outputs *only* when the controller detects that the script output is used in a later part of the template.

**What you expected to happen**:

Do not annotate output of script templates when the output is not consumed in a later step of the template.

**Environment**:
- Argo version: v2.3

**Comment by Ark-kun** [comment]
Sounds good.

I think there is another way to solve it though (they're not conflicting):

1. All outputs are **stored** like artifacts (stored in the artifact repository). There is no more distinction between parameter outputs and artifact outputs. Any output can be passed to any input.
1. Only those outputs that are **consumed** as parameters are added to the annotation (or passed using any other alternative implementation).

**Comment by elek** [comment]
It's a very annoying bug. I can't use any real build command from the script. Eg. in case of:

```
        source: |
              mvn clean install -DskipTests
```

The execution can be failed because the too long annotation. In case of 

```
        source: |
              mvn clean install -DskipTests > /tmp/mvn.log
```

I can't follow the progress with `kubectl logs` or `argo logs` just with `kubectl exec -it $PODNAME tail -f /tmp/mvn.log`, which is not ideal.

**Comment by wreed4** [comment]
Is there a way to turn this feature off??  I'm trying to write a controller that listens to workflows and publishes status and human readable logs (not necessarily pod logs).  I'm not sure how to capture these outputs, but my plan was to have a small template that just echoed a message, and read that output as a log and collect that.  This output is useless for the Workflow, so I don't want to reference it.  I do want a controller that watches workflows to be able to have access to some sort of string output though.  is there a good way to do this?
