### ISSUE TITLE
Unexpected behaviour when attempting to archive logs

### ISSUE THREAD

**Issue by petronius** [argoproj/argo#1361]
**Is this a BUG REPORT or FEATURE REQUEST?**:

Bug report

**What happened**:

On v2.3.0-rc2 (so with https://github.com/argoproj/argo/issues/1158 merged in), logs archived with the `archiveLogs` feature only log `stdout` and do not include `stderr`.

In addition, logs are never archived if the step being run has no artifacts specified.

**What you expected to happen**:

Archived logs should contain all of stdout and stderr output, and should be logged even if there are no other artifacts specified.

**How to reproduce it (as minimally and precisely as possible)**:

On v2.3.0-rc2 following the [Minkube setup guide with Minio](https://github.com/argoproj/argo/blob/master/demo.md):

This workflow produces no log artifact in Minio: https://gist.github.com/petronius/198b695e7f457052f1c2c18f41e2700c

This workflow products an empty log artifact in Minio: https://gist.github.com/petronius/9acd17acab92efb9467e64cf10f31e6f

**Anything else we need to know?**:

**Environment**:
- Argo configuration: https://gist.github.com/petronius/9e410e86ecaf7f48319e1b5ae46e6f48
- Argo version:
(cli version is different from the argoexec/workflow controller version running in the cluster, see gist above)
```
$ argo version
argo: v2.2.1
  BuildDate: 2018-10-11T16:25:59Z
  GitCommit: 3b52b26190163d1f72f3aef1a39f9f291378dafb
  GitTreeState: clean
  GitTag: v2.2.1
  GoVersion: go1.10.3
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: 2018-09-10T11:44:26Z
  compiler: gc
  gitCommit: a4529464e4629c21224b3d52edfe0ea91b072862
  gitTreeState: clean
  gitVersion: v1.11.3
  goVersion: go1.11
  major: "1"
  minor: "11"
  platform: darwin/amd64
serverVersion:
  buildDate: 2018-03-26T16:44:10Z
  compiler: gc
  gitCommit: fc32d2f3698e36b93322a3465f63a14e9f0eaead
  gitTreeState: clean
  gitVersion: v1.10.0
  goVersion: go1.9.3
  major: "1"
  minor: "10"
  platform: linux/amd64
```

**Comment by dfarr** [comment]
I can confirm the same behaviour for `v2.3.0-rc3`.

**Comment by Myafq** [comment]
Are there any plans to solve this?

**Comment by irlevesque** [comment]
> logs are never archived if the step being run has no artifacts specified

https://github.com/argoproj/argo/pull/1791 would fix this issue

**Comment by tcolgate** [comment]
#2136 should fix saving of stderr

**Comment by alexec** [comment]
Is this still an issue? If so - please re-open.
