### ISSUE TITLE
Add filename and line number to logs

### ISSUE THREAD

**Issue by zhujl1991** [argoproj/argo#1367]
**Is this a BUG REPORT or FEATURE REQUEST?**: FEATURE REQUEST

We should enable logging https://github.com/argoproj/argo/blob/6c18039be962996d971145be8349d2ed3e396c80/workflow/controller/operator.go#L95 with filename and line # in argo https://github.com/sirupsen/logrus/issues/63#issuecomment-433746888 with short file path https://github.com/sirupsen/logrus/issues/63#issuecomment-476486166 .

in order to do, this we have to upgrade our `logrus` pkg to `v1.2.0` or after https://github.com/sirupsen/logrus/issues/63#issuecomment-435566044

**Comment by alexec** [comment]
Would you like to submit a PR for this?
