### ISSUE TITLE
Remote debugging of python steps with PyCharm or alternative

### ISSUE THREAD

**Issue by fj-sanchez** [argoproj/argo#1368]
I am not sure if this is possible at all but my current workflow is too painful so it's worth asking. I have some python scripts inside a docker image that I call sequentially in different steps of a workflow. Locally they work and I can easily debug them, but when running in the cluster there are different sort of issues (configurations, paths, etc.) that are really hard to debug. What I would like to do is to connect using PyCharm (https://www.jetbrains.com/help/pycharm/remote-debugging-with-product.html#remote-debug-config) but I don't know if that's possible at all.

Any hints or recommendations? How do you debug your steps?

**Comment by epa095** [comment]
I use `kubectl get $podname -o yaml` to verify that things look ok, and then I start up the same code locally with those same settings, possibly using `kubectl port-forward` to get access to any services needed. But mostly the error is clear from looking at the `yaml`. Also, use python logging module, and log extensively. Use an environment variable to set the log-level of the logger so you can toggle debug mode in the workflow by an environment variable.
