### ISSUE TITLE
Is Pod securityContext fsgroup supported?

### ISSUE THREAD

**Issue by jewel77** [argoproj/argo#1373]
**Is this a BUG REPORT or FEATURE REQUEST?**: FEATURE REQUEST

**What happened**:
When submitting workflow yaml file that has securityContext fsGroup defined, argo reports: 
Failed to parse workflow: error unmarshaling JSON: while decoding JSON: json: unknown field "fsGroup"

**What you expected to happen**:
Argo supports fsGroup

**Comment by fj-sanchez** [comment]
So clearly it is not supported, I still have problems when mounting a volume and running a pod with a user different than root...

**Comment by dtaniwaki** [comment]
I think #1463 solved this issue.
