### ISSUE TITLE
[argo-ui] css loads Heebo font from the internet

### ISSUE THREAD

**Issue by devlounge** [argoproj/argo#1376]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Bug report

**What happened**:
While loading the Argo UI, the CSS tries to load Heebo from fonts.googleapis,.com.
BUT, in air-gapped environments, users workstations do NOT have any internet connection
-> It can take more than 1 to 2 minutes before the page renders (I guess CSS falls back to browser fonts instead)
-> The fallback font used in the left navbar popovers is rendered all blurred

**What you expected to happen**:
Bundle the fonts in the docker image and serve them from disk

**Environment**:
- Argo version: v2.3.0
- Kubernetes version : v1.13.4

**Comment by devlounge** [comment]
Any update on this?

**Comment by ZhengRongTan** [comment]
same issue 
access https://fonts.googleapis.com/css?family=Heebo:300,400,500,700

**Comment by devlounge** [comment]
Hi,

We need a fix for this, because this makes it annoying to use in corporate air-tight environments.

**Comment by alexec** [comment]
Would you like to submit a PR to fix this?

**Comment by alexec** [comment]
Should combine with #2760
