### ISSUE TITLE
Catalog details screen - missing breadcrumbs

### ISSUE THREAD

**Issue by wokeGit** [argoproj/argo#138]
I'm not sure if it's a bug or not, @rahuldhide please take a look.
Go to Catalog screen -> click "LERN MORE" button or any of the element on the bottom list -> you will be navigate to details screen. There is empty top bar, do we should add here breadcrumbs?
![screen shot 2017-09-01 at 12 02 25](https://user-images.githubusercontent.com/13086525/29965515-29dfc94c-8f0e-11e7-84be-1d3a7f510854.png)

**Comment by rahuldhide** [comment]
We need to change the Catalog screen as per the new patterns and visual styles.

**Comment by rahuldhide** [comment]
@wokeGit I am updating the Catalog section's design as per the Argo brand and guidelines.

**Comment by jessesuen** [comment]
Closing v1 issues.
