### ISSUE TITLE
Resume with Parameters

### ISSUE THREAD

**Issue by delwaterman** [argoproj/argo#1391]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST: Output parameters for the `suspend` template type:

```
# workflow.yml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
spec:
  # ...
  templates:
    - name: wait-for-approval
       suspend: {}
       outputs:
         parameters:
           - name: foo
```

cli:
```
$ argo resume workflow-1234 --parameter foo=bar
```

**What happened**:
For workflows that require some form of human intervention argo examples suggest using suspend/resume operations (https://github.com/argoproj/argo/blob/master/examples/suspend-template.yaml). 

Unfortunately this case only covers where the workflow should continue, or be paused indefinitely. There are cases where you would want the workflow to follow conditional paths based on a user's input. For example, my organization deploys to a special canary environment, and waits for a `go`/`no-go` command from a user. If a `go` command is executed the remaining production environments get the new build. If a `no-go` command is executed the canary environment is rolled back (As a side note, we cannot use argocd to address this problem for other reasons I will not outline here).

I've experimented with using `terminate`, `resume` and then Exit Handlers to deal with this situation, but `terminate` produces some inconsistent behavior with pods. Sometimes the exit handler pods are executed sometimes they are not. It also seems like `terminate` is really for the emergency case of shutting down a workflow, not manually setting a workflow to a failed state.

I've also experimented with the following methods for recording user input:
- Storing user's response in some external storage:
  1. The workflow reaches the suspend step
  2. A script uploads a user's input to some storage (S3 in this case), and executes a resume on the workflow
  3. Immediately following the suspend step with a step pulls the response from storage and using that as an output parameter
- Directly editing the kubernetes resource
  1. Add an argument to the workflow for the "user's response" giving it a default value
  2. Execute the workflow and wait until it reaches the suspend step
  3. Edit the workflow in kubernetes and set the value of the argument to the user's response
  4. Resume the workflow

While both of these methods works, they feel clunky. It seems like this kind of manual decision point is a feature that would be needed by various users.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Argo version:
```
$ argo version
```
- Kubernetes version :
```
$ kubectl version -o yaml
```

**Other debugging information (if applicable)**:
- workflow result:
```
$ argo get <workflowname>
```
- executor logs:
```
$ kubectl logs <failedpodname> -c init
$ kubectl logs <failedpodname> -c wait
```
- workflow-controller logs:
```
$ kubectl logs -n kube-system $(kubectl get pods -l app=workflow-controller -n kube-system -o name)
```

**Comment by Ark-kun** [comment]
Probably the best way to solve this is to just have intermediate data caching support.
With caching you do not need any special restart or resume - you can just modify the middle of the pipeline and start it again (the unmodified parts won't be re-executed).

**Comment by delwaterman** [comment]
@Ark-kun so just to be clear. You are suggesting we modify the Kubernetes Workflow resource directly, to alter the pipeline to proceed along the correct path (continue or roll-back). That is a path I tried and was able to make it work. But I have two concerns about this path:

1. I am nervous to modify a kubernetes resource in the middle of the run. It feels a little scary to modify state in the middle of a workflow run. Though I might being skiddish.

2. This can make auditing a workflow more difficult. What I like about the resume with parameters option is that within one workflow you can see all possible branches and can easily reason about the path a pipeline followed. 

Modifying the pipeline, means that anyone debugging a failed pipeline would have to know about both the workflow, and any other tools that were used to modify it. Since state is not preserved it can make tracking down errors very difficult.

**Comment by mark9white** [comment]
A workflow with a suspend/resume step can be thought of as an asynchronous version of a normal workflow step, so @delwaterman's suggestion makes sense to me - that it would support output parameters just like normal steps.

**Comment by dtaniwaki** [comment]
I got a project which requires this feature.

@alexcapras 
What do you think about this feature? If it's worth trying, I will implement it.

**Comment by mark9white** [comment]
@dtaniwaki see #3133

**Comment by dtaniwaki** [comment]
Thank you for implementing the feature!

**Comment by mark9white** [comment]
No problem! See also: https://github.com/argoproj/argo/blob/master/docs/async-pattern.md

**Comment by tszngai** [comment]
Is there a way to allow users to enter (or select) parameters when resuming a suspended workflow on the UI?
User inputs can be easily added in Jenkins. I would imagine this should be available in argo workflow too. Thanks

**Comment by basanthjenuhb** [comment]
Implemented this feature recently
https://argoproj.github.io/argo-workflows/intermediate-inputs/

**Comment by BenjaminCaffrey** [comment]
@basanthjenuhb - thank you for implementing this. Is there a way to pass these intermediate inputs in programmatically? Like I would expect that the documentation for [argo resume](https://argo-workflows.readthedocs.io/en/latest/cli/argo_resume/) would include something like `-p approve=NO`.
