### ISSUE TITLE
Invoking workflows

### ISSUE THREAD

**Issue by palade** [argoproj/argo#1395]
**Is this a BUG REPORT or FEATURE REQUEST?**:

I don't think this is either a bug report nor a feature request, but a question: 
How do I invoke/execute workflows after deploying them? 

**What happened**:

I would like to invoke a workflow as a response to some event. Or have some input and produce output from a command line. How do I trigger the execution of a workflow after has been deployed? It appears that the workflow is executed once after deployment, but I would like to use some command to trigger its execution. Is there some command that I can trigger the first node in the workflow and the dependencies of that node will also be invoked? 

**What you expected to happen**:

I expect to have some command line to invoke the workflow as I don't need to submit/re-submit the workflow. The workflow is already deployed.

**Anything else we need to know?**:

Sorry for posting the question here, but I was thinking this is the quickest way to get a response. I can delete or remove this if it should be posted somewhere else.

**Environment**:
- Argo version:
```
$ argo version
argo: v2.3.0
  BuildDate: 2019-05-20T22:11:09Z
  GitCommit: 88fcc70dcf6e60697e6716edc7464a403c49b27e
  GitTreeState: clean
  GitTag: v2.3.0
  GoVersion: go1.11.5
  Compiler: gc
  Platform: linux/amd64

```
- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:                                        
  buildDate: "2019-05-16T16:23:09Z"                   
  compiler: gc                                        
  gitCommit: 66049e3b21efe110454d67df4fa62b08ea79a19b 
  gitTreeState: clean                                 
  gitVersion: v1.14.2                                 
  goVersion: go1.12.5                                 
  major: "1"                                          
  minor: "14"                                         
  platform: linux/amd64                               
serverVersion:                                        
  buildDate: "2019-05-16T16:14:56Z"                   
  compiler: gc                                        
  gitCommit: 66049e3b21efe110454d67df4fa62b08ea79a19b 
  gitTreeState: clean                                 
  gitVersion: v1.14.2                                 
  goVersion: go1.12.5                                 
  major: "1"                                          
  minor: "14"                                         
  platform: linux/amd64                               
```

**Comment by fj-sanchez** [comment]
Have you looked already into Argo events? Also, there is an example that uses CronJob to achieve something similar (ignore the airflow part): https://github.com/argoproj/data-pipeline

**Comment by palade** [comment]
@fj-sanchez I checked the argo-events project after I posted this question. I deployed it and used it to trigger the execution execution of the workflow based on some http request. However, I noticed that the workflow is re-deployed for every request. Is this the correct flow or there is a way to invoke the workflow without re-deploying it? Please let me know if my observations are not accurate.

**Comment by sarabala1979** [comment]
Creating a new workflow object is a correct flow and it is expected behavior in argo workflow.  Each invocation input and output is different so, Argo workflow needs to keep track.

**Comment by alexec** [comment]
This is over 6 months old. Please re-open if still an issue.
