### ISSUE TITLE
Missing action options

### ISSUE THREAD

**Issue by wokeGit** [argoproj/argo#140]
@rahuldhide please take a look.
The same Fixture instance has different actions.
Go to Fixtures screen -> click "three dot menu" button, the list contains: "**Reassign**" and "**Delete**" -> open this instance to see details -> click three dot button on top, the lis contains: "**Create Instance**", "**Reassign Template**", "**Delete Class**".
![screen shot 2017-09-01 at 15 17 32](https://user-images.githubusercontent.com/13086525/29971733-a51bd82e-8f29-11e7-9d10-9408f20ef8fb.png)
![screen shot 2017-09-01 at 15 17 47](https://user-images.githubusercontent.com/13086525/29971735-a708feb4-8f29-11e7-97ee-b1f08477d726.png)

Similar issue is on the Volumes screen:
![screen shot 2017-09-01 at 15 26 12](https://user-images.githubusercontent.com/13086525/29971838-248fb968-8f2a-11e7-9645-1f24f43c8ed2.png)
![screen shot 2017-09-01 at 15 26 23](https://user-images.githubusercontent.com/13086525/29971840-25ea9c42-8f2a-11e7-9496-a7c0820f03ce.png)

**Comment by rahuldhide** [comment]
**Fixtures:**
Fixture class's interaction model is similar to the folders on file system. It's a container of fixtures. Therefore, when we are displaying a list of classes, we can't display action to add fixtures. Create Fixture should be available only when user in inside a class. Current model is correct.

We need to fix following issues for the fixture menus:
- Use consistent icons for the actions
-  Display reassign only when it's applicable. @alexmt we have discussed those usecases in the past.

**Volumes**
Volumes list items and details page should have consistent actions. Add Edit option on the list.

**Comment by alexmt** [comment]
@rahuldhide . I believe 'Reassign' should be available for all enabled classes. We are showing warning and encourage user to use 'Reassign' only if class template had been deleted but 'Reassign' button should be available any time.

**Comment by rahuldhide** [comment]
@alexmt I have updated my previous comment based on our discussion about Reassign action.
