### ISSUE TITLE
argoexec image is not statically built

### ISSUE THREAD

**Issue by schulzh** [argoproj/argo#1403]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

**What happened**: The argoexec:v2.3.0 image is not statically built, as shown by the ldd output:
```
docker run -it --rm argoproj/argoexec:v2.3.0
root@7b1fe2f3d0ee:/# ldd /usr/local/bin/argoexec
	linux-vdso.so.1 (0x00007ffe310c7000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fe46e47e000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fe46e0df000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fe46e69b000)
```

**What you expected to happen**: The binary should be statically linked as indicated by the default Makefile: https://github.com/argoproj/argo/blob/v2.3.0/Makefile#L16 and ldd should not output any shared objects

**How to reproduce it (as minimally and precisely as possible)**: `docker run -it --rm argoproj/argoexec:v2.3.0 ldd /usr/local/bin/argoexec`

**Environment**:
- Argo version: 2.3.0
- Kubernetes version: n/a

**Comment by alexec** [comment]
Can you see if this is still an issue in v2.5? Is so - please re-open.
