### ISSUE TITLE
having trouble see the k8s-job's application logs through argo & kubectl 

### ISSUE THREAD

**Issue by aime1** [argoproj/argo#1412]
I am able to see my application's log through kubectl logs command.

However, once I moved k8s-job to argo, 

both argo log and Kubectl log won't show me the log from the application.

Instead, it shows the log from argo ...

how can one see the k8s-job's app's log through argo ?

**Comment by sarabala1979** [comment]
Please try with argo logs <pod name> or kubectl logs <pod names> main,
you can find pods name using below command.
argo get <workflowname>


![image](https://user-images.githubusercontent.com/33908564/61246804-90a5bf00-a704-11e9-92ec-ecaecbf71e84.png)

**Comment by aime1** [comment]
Thanks :)
