### ISSUE TITLE
Add metrics about node status

### ISSUE THREAD

**Issue by XciD** [argoproj/argo#1415]
FEATURE REQUEST

Would be interesting to have more metrics about the inner steps of a workflow.
We are building are alerting system on our workflow based on argo and we would like to know which steps are in error for example.
Also the start time / end time etc could also be interesting.

Could I open a PR for this ?

**Comment by jessesuen** [comment]
I think more metrics would be fine. We have to be very careful about cardinality of prometheus though, so if the addition of these additional metrics would potentially result in prometheus using significantly more memory, then we need a way for this to be configurable so that users can opt-out.

**Comment by XciD** [comment]
Hello,

Could you tell me what do you think about it:

https://github.com/XciD/argo/commit/17e4d195a4b0952e3e27a62edeea589476f8d3e6 

About the a configurable way to have metrics, we could add a new field to the workflow struct or an annotation that says that we want more metrics. What do you think ?
