### ISSUE TITLE
Unable to download S3 artifact from Argo UI

### ISSUE THREAD

**Issue by harshnova** [argoproj/argo#1449]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT

**What happened**:
Tried to download an S3 artifact from Argo UI b clicking the artifact icon. The artifact did not download. Rather, got a response with status failure.

**What you expected to happen**:
Expected the artifact to get downloaded.

**How to reproduce it (as minimally and precisely as possible)**:
Start a workflow that has artifacts passing involved. Once run is complete, go to argo UI, select a component and see artifacts. click on download artifact. the error will arise.

**Anything else we need to know?**:

**Environment**:
- Argo version: 2.3.0
```
$ argo version
```
- Kubernetes version : 1.12
```
$ kubectl version -o yaml
```

**Other debugging information (if applicable)**:
- workflow result:
```
$ argo get <workflowname>
```
- executor logs:
```
$ kubectl logs <failedpodname> -c init
$ kubectl logs <failedpodname> -c wait
```
- workflow-controller logs:
```
$ kubectl logs -n kube-system $(kubectl get pods -l app=workflow-controller -n kube-system -o name)
```

![image](https://user-images.githubusercontent.com/8025623/60170126-81c69d80-9825-11e9-98c3-26b7fb592acc.png)

![image](https://user-images.githubusercontent.com/8025623/60169964-622f7500-9825-11e9-87f4-047b226c8e0f.png)

**Comment by alexec** [comment]
This issue is over 6 months old and we do not support Argo UI anymore.
