### ISSUE TITLE
failed to load artifacts: close tcp 10.60.1.248:51054->18.205.93.1:22: use of closed network connection

### ISSUE THREAD

**Issue by saward** [argoproj/argo#1457]
**Is this a BUG REPORT or FEATURE REQUEST?**:

BUG REPORT

**What happened**:

Simultaneous use of git artifact to clone same repository seems to result in an error:

"failed to load artifacts: close tcp 10.60.1.248:51054->18.205.93.1:22: use of closed network connection"

**What you expected to happen**:

Repository cloned successfully.

**How to reproduce it (as minimally and precisely as possible)**:

I'm not sure if this is the issue, but it started happening at the same time as I had added four separate simultaneous steps cloning the same repo to my workflow.  Sometimes, some of the steps succeed in cloning the repo (seems to be random).

Am I using this as intended, or is there a better way to use the git artifact so that I can clone the repo once but work with separate copies of it in later steps?  Is the git artifact unsafe to use simultaneously?

**Comment by BouweCeunen** [comment]
Any solutions to this?

**Comment by saward** [comment]
My solution was to have one step that clones repo to a volume, and another multiple steps that mount that same volume read only and each copy it to where they need.

If you think of a better work around, let me know.

**Comment by BouweCeunen** [comment]
I was only experiencing this with one of my repositories. I deleted the repo on bitbucket, removed the .git folder locally, created a new repo and pushed everything again. It is working now, no idea what caused it.

**Comment by paveq** [comment]
I'm also experiencing the same issue on medium sized (70 MB) repository from Bitbucket.

At the same time "git clone" from some other pod works just fine.. feels like this issue is in Git used in executor image.

**Comment by paveq** [comment]
Seems it might be related to this issue: https://github.com/src-d/go-git/issues/1033#issuecomment-522245481

Cloning via `https` works for me.

**Comment by alexec** [comment]
@paveq do you know if they released a fix for this? We could upgrade go-git if that is the case.

**Comment by alexec** [comment]
Is this still a problem please?

**Comment by rjdp** [comment]
@alexec its still there I got following error on 2.8.0 : failed to load artifacts: close tcp 10.244.1.251:55912->18.205.93.1:22: use of closed network connection

**Comment by saward** [comment]
I'm getting this more frequently now.  Using argo 2.11.2.

**Comment by saward** [comment]
Based on the issue linked previously (https://github.com/src-d/go-git/issues/1033#issuecomment-522245481), I tried setting "depth: 1", and that appeared to allow it to clone.  So looks like it may be an issue with go-git and ssh keys for repositories that are larger.

**Comment by dcu** [comment]
this was fixed in go-git/go-git#70
