### ISSUE TITLE
Raise (or make configurable) maxWorkflowSize 

### ISSUE THREAD

**Issue by kalugny** [argoproj/argo#1464]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Feature request, bordering on bug
**What happened**:
My workflows fail because they are "too big". What is the reason for the 1MB limit? Can this be raised or made configurable?

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Argo version:
```
$ argo version
```
- Kubernetes version :
```
$ kubectl version -o yaml
```

**Other debugging information (if applicable)**:
- workflow result:
```
$ argo get <workflowname>
```
- executor logs:
```
$ kubectl logs <failedpodname> -c init
$ kubectl logs <failedpodname> -c wait
```
- workflow-controller logs:
```
$ kubectl logs -n kube-system $(kubectl get pods -l app=workflow-controller -n kube-system -o name)
```

**Comment by sarabala1979** [comment]
#1264 and #1344 will solve the large workflow and 1MB limits on ETCD
