### ISSUE TITLE
Broken link in docs for Go API client

### ISSUE THREAD

**Issue by alexellis** [argoproj/argo#1466]
**Is this a BUG REPORT or FEATURE REQUEST?**:

I found a broken link in docs for Go API client

**What happened**:

404

**What you expected to happen**:

Get to the page.

**How to reproduce it (as minimally and precisely as possible)**:

I clicked on "See the golang code example" here -> https://argoproj.github.io/docs/argo/docs/rest-api.html

**Anything else we need to know?**:

Hopefully that's all. I'm using Safari on MacOS.

**Comment by alexec** [comment]
I think this is fixed now. Please re-open if still an issue.
