### ISSUE TITLE
Kubernetes Deployment

### ISSUE THREAD

**Issue by bobhenkel** [argoproj/argo#147]
I'd like to run Argo on my existing cluster.  From install instructions it appears Argo installer stands up a cluster and puts Argo on it.  Do you support installing Argo on an existing Kubernetes cluster? Our team is currently using kops running on aws.

Thanks
Bob

**Comment by edlee2121** [comment]
Hi Bob, we are working on this right now :-) Please stay tuned.

https://github.com/argoproj/argo/blob/master/ROADMAP.md

**Comment by jessesuen** [comment]
Argo installs as a controller now. Closing out.
