### ISSUE TITLE
Argo CLI should show warning if there is no workflow definition in file

### ISSUE THREAD

**Issue by inc0** [argoproj/argo#1486]
When calling `argo submit workflow.yaml` and there isn't any workflow defined (maybe resources with different kind), argo will not show any output or error.

It would be useful error to throw if there is no workflow defined in file.

**Comment by inc0** [comment]
Thank you!

**Comment by wdma** [comment]
Hello,  
I had been successfully using the Argo Quickstart manifest and am now trying to install the secure manifest, but am getting
this error when trying to run "argo submit..." (The workflows have worked with the QuickStart manifest.)  @inc0, your comments suggest that I have a resource issue.  Is there a test I can run to find the source of the error?

Thank you!
