### ISSUE TITLE
example to run mpi-operator jobs in worfklow

### ISSUE THREAD

**Issue by yncxcw** [argoproj/argo#1492]
**Is this a BUG REPORT or FEATURE REQUEST?**: Question

Just a question. is there an example to show how to run mpi-operator jobs (tensorflow multi-node training) in a workflow ?

**Comment by xianlubird** [comment]
you can reference kubeflow

**Comment by yncxcw** [comment]
Yeah, I got these examples from kubeflow. Thanks!

**Comment by tomdurrant** [comment]
@yncxcw did you manage to get these kubeflow examples working in argo?
