### ISSUE TITLE
Resource limits as input parameter

### ISSUE THREAD

**Issue by fj-sanchez** [argoproj/argo#1496]
I have a generic step definition that I would like to reuse but I need to parametrize things like input/output paths, arguments and specially the resource limits. Currently in the cluster that I use by default they are pretty low, so I need to specify what I want for each call. One of the input arguments to that step is actually the operation to execute (there are dozens of them and they keep growing) and each operation has very different memory consumption requirements. Is there any way to pass the memory/cpu limits using input parameters? So far I haven't been able to achieve anything like this.

**Comment by sarabala1979** [comment]
Current argo will support only parameter resolve on `args`.
