### ISSUE TITLE
Add search and gateway/sensor related filtering in argo UI

### ISSUE THREAD

**Issue by rverma-nikiai** [argoproj/argo#1509]
**Is this a BUG REPORT or FEATURE REQUEST?**:
*FEATURE REQUEST*

**What happened**:
Need to find a particular argo job faster in web console.

**What you expected to happen**:
Able to filter by Gateway/sensor first, do a nested run by prefix of job. A window selection using the calendar(line grafana) would be super awesome.

**Environment**:
- Argo version:
```
0.9.3
```
- Kubernetes version :
```
1.13.7
```

**Comment by hychrisli** [comment]
Would love this new feature to be added! From the ops perspective, I would like to know how a particular job has been doing in the past. It's difficult to do that in the UI right, since jobs are sorted in reverse chronological order with very limited filter options.
