### ISSUE TITLE
Not able to access external IPs from argo workflow step

### ISSUE THREAD

**Issue by sathyatvrcbe** [argoproj/argo#1517]
I am having a workflow in which in one of the steps I need to scp a file from a VM with public IP and export it as an artifact.

When scheduled in argo, Everything is working fine except that the scp to the public IP. I ran the same docker container using docker run in my local machine. The docker container runs as expected.

By reading kubernetes documentation, I came to know that we need to create a external load balancer to route the requests to the internet. How do I do it using argo?

**Comment by sarabala1979** [comment]
What kind of error are you getting? is it authentication error on public IP? Please share the logs

**Comment by sathyatvrcbe** [comment]
Thanks Saravanan for the response. It's a false alarm from my side. Sorry for the inconvenience.
