### ISSUE TITLE
Does Argo offer paid support?

### ISSUE THREAD

**Issue by jackmahoney** [argoproj/argo#1520]
Hi everyone. Very much appreciate your work. Does Argo team currently offer or plan to offer paid support or paid consulting? I work for a company that uses Argo heavily--enough so that they would pay a contributor a high hourly rate in order to consult on and fix issues that we encounter in our use cases.

If this is the wrong place to ask I apologize. Thanks

**Comment by sarabala1979** [comment]
Argo team is very actively supporting through slack c argoproj/argo-workflow. We do have every month argo community meeting to discuss new feature/upcoming release/supports.
We are planning to have an office hour to support community question and request.
There is one on 08/10 @10 am.
https://github.com/argoproj/argo-site/wiki/ArgoProj-Office-Hours

**Comment by saradhis** [comment]
@jackmahoney Argo is an open source project from Intuit with the intent to share some of the components we are using internally to run our SaaS services. Argo team at Intuit does not offer or currently plan to offer paid support.
