### ISSUE TITLE
Compare to Zeebe

### ISSUE THREAD

**Issue by kirgene** [argoproj/argo#1522]
I wonder how Argo is different from [Zeebe](https://zeebe.io/).
For me, the most significant one is the tasks execution approach: while Argo spawns separate worker instance (pod) per task, Zeebe acts as a message broker for already deployed worker instances.
I wonder how it would scale as Argo adds significant overhead with this approach: when using Istio service mesh, Pods will also have the sidecar running (next to the worker) so bootstrapping a single Pod can be quite time consuming and memory expensive at scale.

**Comment by shahabio** [comment]
Any thoughts?
