### ISSUE TITLE
WorkflowTemplate resolution should happen once

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo#1525]
Spawned from https://github.com/argoproj/argo/pull/1312#issuecomment-517800572

When resolving workflow templates, we should do this once when we start processing the workflow, and store the resolved templates in status. This will handle the problem of templates changing their meaning, or disappearing while workflows are running.

There's also the question about how to handle retry of workflows which are using templates. I feel behavior should be as follows:

1) `argo retry` should **_not_** re-resolve workflow templates
2) `argo resubmit` **_should_** re-resolve any workflow templates

We could consider adding flags to re-resolve templates or not during those two commands.

**Comment by jessesuen** [comment]
One corner case:

3. `argo resubmit --memoized` should probably re-use resolved workflow templates. I think we need to re-use the resolved templates because it is re-using prior node status information, and allowing templates to change meaning during resubmit may have inconsistent results.

**Comment by simster7** [comment]
Closing as resolved
