### ISSUE TITLE
can't reach http://k8s.io

### ISSUE THREAD

**Issue by xcircle** [argoproj/argo#1543]
all my dependencies under the k8s.io/ can't be reached,why?
I'v tried godep,gomodule that's not working at all.

![image](https://user-images.githubusercontent.com/5899906/62833081-5419a480-bc6b-11e9-9f64-0bb1801b4528.png)

unable to deduce repository and source type for "k8s.io/api": unable to read metadata: unable to fetch raw metadata: failed HTTP request to URL "http://k8s.io/api?go-get=1": Get http://k8s.io/api?go-get=1: dial tcp 35.201.71.162:80: i/o timeout

**Comment by BobLiu20** [comment]
Aha, Seems blocked by GFW? Using VPN or set goproxy

**Comment by xcircle** [comment]
Already fixed, thanks anyway.

**Comment by alexec** [comment]
This is over 6 months old. Please re-open if still an issue.
