### ISSUE TITLE
argoexec tag is latest in deployment manifest

### ISSUE THREAD

**Issue by tralexa** [argoproj/argo#1544]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT

**What happened**:
argoexec tag is wrong in the deployment manifest file: https://github.com/argoproj/argo/blob/release-2.3/manifests/base/workflow-controller/workflow-controller-deployment.yaml

**What you expected to happen**:
argoexec tag should be specific (e.g. v2.3.0), statically or using kustomization

**How to reproduce it (as minimally and precisely as possible)**:
see url above to workflow-controller-deployment.yaml

**Anything else we need to know?**:
no

**Environment**:
- Argo version: 2.3
```
$ argo version
```
- Kubernetes version : 1.11
```
$ kubectl version -o yaml
```

**Other debugging information (if applicable)**:
- workflow result:
```
$ argo get <workflowname>
```
- executor logs:
```
$ kubectl logs <failedpodname> -c init
$ kubectl logs <failedpodname> -c wait
```
- workflow-controller logs:
```
$ kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name)
```

**Comment by sarabala1979** [comment]
v2.3.0 manifests folder is reorganized with kustomize 2. you have to run ``` kustomize build
``` on  ```/manifests/base ``` 
or you can use ```https://github.com/argoproj/argo/blob/release-2.3/manifests/install.yaml```

**Comment by tralexa** [comment]
yes I am using kustomize, however "argoproj/argoexec:latest" is passed as args and kustomize leaves it intact. The other "latest" tags (argoproj/argoui:latest, argoproj/workflow-controller:latest) are passed as image and kustomize handles them fine.
