### ISSUE TITLE
CLI Installation documentation missing

### ISSUE THREAD

**Issue by zmunro** [argoproj/argo#1546]
Why is there no documentation on how to install the argo CLI? I need a way to kick off argo jobs on GKE but can't find any documentation on how to install the CLI.

**Comment by xianlubird** [comment]
You can download binary from release pages

**Comment by zmunro** [comment]
Or ya know, they could just put these two damn lines somewhere convenient:
```curl -sSL -o /usr/local/bin/argo https://github.com/argoproj/argo/releases/download/v2.2.1/argo-linux-amd64
chmod +x /usr/local/bin/argo
```
You have to do more than just "Download the binary", it needs to go in a place in your PATH, it needs to be made into an executable, it needs to be renamed to "argo" if you want to run it with the `argo` command. But thanks for your wonderfully insightful tip

**Comment by aviweit** [comment]
Hello,
I think it would be helpful to add to https://github.com/argoproj/argo/blob/master/demo.md which contains installation instructions - a subsection for installing the CLI similar to what @zmunro suggests (replacing to v2.3.0). I confirm this to be working in my environment.

Thanks.

**Comment by alexec** [comment]
We now list the download options in the release notes.  Please re-open if still an issue.
