### ISSUE TITLE
Issue when multiple changes are made to deployment

### ISSUE THREAD

**Issue by marcb1** [argoproj/argo#1549]
We have `HPA` added to our deployment. When the HPA scales a deployment, it also updates the `replicas` count field in the deployment.

This seems to introduce an issue if `argocd app patch` is running while the HPA is updating the`replicas` field. 

The following error is thrown:
```
local() encountered an error (return code 1) while executing '/usr/local/bin/argocd app patch test_app --patch '[{"path": "/spec/source/kustomize", "value": {"images": ["gcr.io/test_app:b2d921c80768f49089fa85a7dd3a31a25e4181c3"]}, "op": "replace"}]' --grpc-web
Unable to update test_app version; argo patch returned an error
Error deploying test_app
time="2019-08-12T16:15:37-04:00" level=fatal msg="rpc error: code = Unknown desc = Operation cannot be fulfilled on applications.argoproj.io \"test_app\": the object has been modified; please apply your changes to the latest version and try again"
```

Is it possible to retry patch operations in the argo controller if a change is being made to the deployment. Not sure what the best way to solve this would be.

**Comment by sarabala1979** [comment]
you have created in Argo Workflow project. Can you create an issue on the argo-cd project?
Here some information about HPA https://argoproj.github.io/argo-cd/user-guide/best_practices/#leaving-room-for-imperativeness

**Comment by marcb1** [comment]
@sarabala1979 will do, sorry created this by mistake here
