### ISSUE TITLE
Broken links in argo documentation

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo#155]
Argo documentation contains links to non-existing markdown files:

```
/content/user_guide/applications/applications.md:
	[Creating a Deployment as a Long Running Service](./../../yaml/ex_create_deploy_long_run_service_coretemplate_notused.md)

/content/user_guide/catalog/deploycatalogapp.md:
	[Creating a Workflow](./../../yaml/ex_create_workflow_notused.md)

/content/user_guide/configapplatixcluster/connectartifactrepo.md:
	[Managing and Monitoring Your Jobs](./../../timeline/jobs_notused.md)

/content/user_guide/timeline/create_job-viewhistory.md:
	[Monitor the progress of your job from the Timeline](./../../jobs_notused.md)

/content/yaml/ex_adding_a_private_elastic_load_balancer.md:
	[Using Load Balancers with Argo](./../user_guide/infrastructure/aboutloadbalancers.md)
	[Finding Your External ELB](../user_guide/infrastructure/aboutloadbalancers.htm#FindingExternalELB)

/content/yaml/ex_create_policy_4_workflow.md:
	[Viewing, Enabling and Disabling Policies](./../user_guide/policies/enable-disablepolicies_notused.md)


```

**Comment by rahuldhide** [comment]
@cyee88 In order to remove Install Argo and Release Notes sections from the Docs, we need to remove all hyperlinks which are pointing to Install and Release Notes.

**Comment by cyee88** [comment]
The links mentioned in this issue are all fixed now.

@rahuldhide @alexmt I've also removed all the hyperlinks that are pointing to Install and Release Notes.

So I will remove the markdown file for the "Setup and install Argo" page from my repo (docs/content/quickstart/**intro_argo_quick_start.md**).

**Comment by cyee88** [comment]
@rahuldhide and @alexmt 
To ensure there is only one install page on the Argo site, we need to do one more thing: 
At https://argoproj.github.io/argo-site/get-started/overview, we need to add a link to the first page of the tutorials. The rendered  link would be https://argoproj.github.io/argo-site/docs/yaml/using_the_yaml_dsl.html (which was rendered from the source markdown file docs\content\yaml\**using_the_yaml_dsl.md**.
