### ISSUE TITLE
liveness probe for workflow-controller Deployment

### ISSUE THREAD

**Issue by aboe026** [argoproj/argo#1575]
I'm trying to figure out how I can write a `livenessProbe` for the `workflow-controller` Deployment. I'm not sure if there is an [http endpoint](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#define-a-liveness-http-request) I can hit that will return a `200`, or if there is some [command](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#define-a-liveness-command) i can run that returns a `0`. I tried to exec into the `workflow-controller` Deployment to see what commands i could run like so:
```
kubectl exec -it workflow-controller-79c7bc56f8-kks8q sh
kubectl exec -it workflow-controller-79c7bc56f8-kks8q bash
kubectl exec -it workflow-controller-79c7bc56f8-kks8q /bin/sh
kubectl exec -it workflow-controller-79c7bc56f8-kks8q /bin/bash
```
But all of those gave an error of:
```
OCI runtime exec failed: exec failed: container_linux.go:345: starting container process caused "exec: \"sh\": executable file not found in $PATH": unknown
command terminated with exit code 126
```
So i'm kind of at a loss.

**Comment by alexec** [comment]
This was not possible last year. Today, if you expose the metrics server on port 9090 - you can also have a liveness probe on that.
