### ISSUE TITLE
Filter workflows on name prefix

### ISSUE THREAD

**Issue by samath117** [argoproj/argo#1577]
**Is this a BUG REPORT or FEATURE REQUEST?**: MINOR FEATURE REQUEST

I would like to be able to filter `argo list` by a prefix of the name. The most common use case would be filtering on runs of a given workflow (with a unique generateName).

Of course, this can also be done with `argo list -o name` and standard command line processing tools, so it's not that important, but would also probably be fairly easy.

Related (and more important): https://github.com/argoproj/argo/issues/802

**Comment by sanoojm** [comment]
I am picking this. This is my first issue in Argo. May need some help.
