### ISSUE TITLE
Permissions for files from s3 input artifact "directory" too restrictive

### ISSUE THREAD

**Issue by crobby** [argoproj/argo#1583]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Bug Report

**What happened**:
I define my input artifact and the workflow begins...at runtime, the objects/files seem to be copied into my container, but the permissions (0777) requested only apply to the root directory itself.  The files inside that directory are set to -rw-------. 1 root root and are not accessible to my user/program (runs as user "default").

    inputs:
      artifacts:
      - name: mydata
        path: /opt/app-root/src/data
        mode: 0777
        s3:
          key: <my s3 path>
          endpoint: <my s3 endpoint>
          bucket: <my bucket
          accessKeySecret:
            name: my-credentials
            key: accesskey
          secretKeySecret:
            name: my-credentials
            key: secretkey
```

**What you expected to happen**:
I'd like to be able to read/write to the files that are in my input artifact.

**How to reproduce it (as minimally and precisely as possible)**:
input artifact defined above.  Any workflow should be able to show the issue.

**Anything else we need to know?**:

**Environment**:  openshift v3.11
```
$ argo version
```
- Argo version: argo: v2.3.0-rc1
  BuildDate: 2019-04-10T15:21:12Z
  GitCommit: 40f9a87593d312a46f7fa24aaf32e125458cc701
  GitTreeState: clean
  GitTag: v2.3.0-rc1
  GoVersion: go1.11.5
  Compiler: gc
  Platform: linux/amd64

- Kubernetes version :
```
$ kubectl version -o yaml
```
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0


**Other debugging information (if applicable)**:
- workflow result:
```
$ argo get <workflowname>
```
- executor logs:
```
$ kubectl logs <failedpodname> -c init
$ kubectl logs <failedpodname> -c wait
```
- workflow-controller logs:
```
$ kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name)
```

**Comment by goern** [comment]
is this using the k8sapi executor?

**Comment by crobby** [comment]
I'm 95% sure this bug was found when we were using k8sapi executor.

**Comment by oscarrobertson** [comment]
I've hit the same problem with argo v2.3.0 and the kublet executor

**Comment by oscarrobertson** [comment]
probably just have to do a few more chmod calls and walk the dir on this line https://github.com/argoproj/argo/blob/master/workflow/executor/executor.go#L184

**Comment by alexec** [comment]
Is this still a problem please?

**Comment by ysaito1001** [comment]
Hi, I've recently run into this issue using Argo v2.8.0.  I'm curious whether there are any workarounds; running my container as `root` doesn't feel like it's a viable workaround.

**Comment by ysaito1001** [comment]
Hello. I've recently run into this issue using Argo v2.8.0. I'm curious if there are any workarounds?

**Comment by afoltzm** [comment]
I believe we're observing this issue on `v2.9.2` - the mode flag doesn't change the permissions of the directory contents. We're using the `docker` executor.
