### ISSUE TITLE
[Question] Execution Guarantees provided by Argo

### ISSUE THREAD

**Issue by sathyatvrcbe** [argoproj/argo#1588]
We are evaluating argo for our project. Can you tell us what type of execution guarantee does argo provide? At least once , At most once or exactly once?

**Comment by sarabala1979** [comment]
I am trying to understand your usecase. Can you provide more details? The Argo controller will execute a workflow that you defined in YAML.  But you can configure sequential steps to achieve the above one.

**Comment by chartinmarrel** [comment]
I specified **across workflows**, but I should have said **across workflow executions**.
We come from Luigi, where a `step` is called a `Task`, and Luigi ensures that a `Task` along with a given set of parameters is run exactly once. 
For example if an Argo workflow has some steps that write to s3, we want to ensure that two different executions of that workflow do not lead to multiple processes trying to write at the same location at the same time. Argo can solve this by ensuring that a given step with a given set of input parameters is run exactly once.
