### ISSUE TITLE
Question / issue with artifact copying between containers

### ISSUE THREAD

**Issue by jlpnetworx** [argoproj/argo#1599]
This is just a question / an issue that we have noticed and not sure how to resolve but based on comments here should be resolvable for argo 2.3.0.
We have basically standard workflows with steps in them where the init container pulls data from S3, the main container processes them and then the wait container uploads the results back to S3.
As our artifacts can be pretty large (as in several hundred GB in one step), copying the data back from the main container to the wait one takes forever due to the docker cp | gzip process.
We know that PNS should help, but we are also putting all the output artifacts in an emptyDir volume mount, which we expected the wait container can just use without the need to copy (as suggested in issue 1203).
When we look inside the init container (e.g. with df) it does not show up but with df -a it does. So not sure why this would not work and avoid the docker cp issue....

Any help would be appreciated.
Michael.

**Comment by alexec** [comment]
Could you use a PVC claim?
