### ISSUE TITLE
Policy documentation update

### ISSUE THREAD

**Issue by wanghong230** [argoproj/argo#16]
https://argoproj.github.io/argo-site/#/docs;doc=yaml%2Fpolicy_templates.md

`when:
# multiple triggers can be specified
# options: on_push, on_pull_request, on_pull_request_merge, on_cron
- event: on_push
- event: on_pull_request
- event: on_pull_request_merge
- event: on_cron
  # cron expression
  # 0 1 * * *
  #   | | | | |
  #   | | | | |
  #   | | | | +---- Run every day of the week
  #   | | | +------ Run every month of the year
  #   | +---------- Run at 1 Hour (1AM)
  #   +------------ Run at 0 Minute
  schedule: "0 * * * *"
  timezone: "US/Pacific"
`

The cron expression explaination is not aligned properly in documentation.

**Comment by edlee2121** [comment]
Fixed. Will show up when we rebuild the documents.
