### ISSUE TITLE
Argo CLI giving certificate error

### ISSUE THREAD

**Issue by mukulikak** [argoproj/argo#160]
Trying to call ./argo login CLI to login to my cluster and getting the following error

https://skynet.applatix.net/v1/auth/login: Post https://skynet.applatix.net/v1/auth/login: x509: certificate signed by unknown authority

But curl -XPOST -d '{"username": "username", "password": "my password" }' https://skynet.applatix.net/v1/auth/login  is not giving any SSL error

**Comment by pratulw** [comment]
Sandeep please look into this. See if Jesse has fixed this on master as well.

**Comment by sandeepbhojwani** [comment]
This is fixed in master and 1.0 branch. argocli shows a warning and let's you login.
