### ISSUE TITLE
Argo WF to fail if a step is failed

### ISSUE THREAD

**Issue by navinjoy** [argoproj/argo#1604]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG

**What happened**:
When an argo WF has multiple steps and if the 1st step fails, argo WF doesn't fail.

**What you expected to happen**:
Argo WF should fail if 1st step fails and should not proceed to next step or it should provide an option to the user something like failOnError = true/ false.

**How to reproduce it (as minimally and precisely as possible)**:
Run an argo WF with multiple steps and write code to fail the 1st step. It will proceed to next step instead of aborting the WF.

**Anything else we need to know?**:

**Environment**:
- Argo version:
```
2.3
$ argo version
```

- Kubernetes version :
```
1.12
$ kubectl version -o yaml
```

**Other debugging information (if applicable)**:
- workflow result:
```
$ argo get <workflowname>
```
- executor logs:
```
$ kubectl logs <failedpodname> -c init
$ kubectl logs <failedpodname> -c wait
```
- workflow-controller logs:
```
$ kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name)
```

**Comment by jlpnetworx** [comment]
that does work out of the box as well unless you specify continueOn....
