### ISSUE TITLE
docker image for ppc64le?

### ISSUE THREAD

**Issue by wzhanw** [argoproj/argo#1610]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST
**What happened**:
I cannot run argo docker image on the power platform.
**What you expected to happen**:
I want to use argo on the cloud on power platform.

We have a lot of customers using power system and they are looking for the argo on ppc64le.

**Comment by wzhanw** [comment]
I have done the code change for building the docker image for ppc64le platform, here is my thought:
1. create a separate Dockerfile named "Dockerfile.ppc64le" base on the original one.
2. modify the Makefile to use the Dockerfile.ppc64le on power, append `-ppc64le` at end of the image tag.

**Comment by wzhanw** [comment]
@jessesuen could you please help to evaluate my idea? thank you.
 I saw there was a PR https://github.com/argoproj/argo/pull/1102  for the support, but it only covered the command line.

**Comment by alexec** [comment]
We now provide `argo-linux-ppc64l`. Does this work for you?
