### ISSUE TITLE
ARGO-UI build fails due to typescript error.

### ISSUE THREAD

**Issue by abhijeet0204** [argoproj/argo#1617]
**Is this a BUG REPORT or FEATURE REQUEST?**: Bug

**What happened**: I tried to build the ARGO-UI by taking the source code and building it using NODE as mentioned in the readme.md file. "yarn build" tries to validate the typescript of the source and this step fails.

**What you expected to happen**: The build should have completed and distributable binaries must have been created.

**How to reproduce it (as minimally and precisely as possible)**: Download the latest source code (v2.3.0) and setup node 11.15.0. And try to build from source using "yarn build"

**Anything else we need to know?**:

**Environment**:
-node version: 11.15.0
```
$ argo version: v2.3.0
```
- Kubernetes version : NA
```
$ kubectl version -o yaml: NA
```

**Other debugging information (if applicable)**:
- workflow result:
```
$ argo get <workflowname>
```
- executor logs:
```
$ kubectl logs <failedpodname> -c init
$ kubectl logs <failedpodname> -c wait
```
- workflow-controller logs:
```
$ kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name)
```

**Comment by abhijeet0204** [comment]
[yarn_error.txt](https://github.com/argoproj/argo/files/3640907/yarn_error.txt)
The error log can be found in the attached file

**Comment by alexec** [comment]
Stale issue.
