### ISSUE TITLE
Mac release not built with CGO enabled, can't talk to non-public EKS

### ISSUE THREAD

**Issue by jaygorrell** [argoproj/argo#1624]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Could be argued either way, but I'd call it a bug since it affects all EKS users with a non-public cluster endpoint.

**What happened**:
Despite using `/etc/resolver/` files, using the `argo` CLI returns an error about DNS resolution after trying to resolve via normal public DNS servers.

**What you expected to happen**:
The `/etc/resolver/` entries are used to resolve the DNS of the cluster endpoint.

**Anything else we need to know?**:
There are lots of issues around this in various Go projects:
https://github.com/golang/go/issues/12524
https://github.com/kubernetes/kubernetes/issues/23130
https://github.com/kubernetes/release/issues/469

An interesting reproduction of this with kubectl is that installing via curl gives the same results as Argo, while installing through brew fixes the problem.

**Environment**:
- Argo version:
```
2.3.0
```
- Kubernetes version :
```
v1.14.6
```

**Comment by astrajohn** [comment]
I also use Argo in a network environment where this is a problem. So the fix to this is as simple as rebuilding with CGO_ENABLED=1, is that right?
