### ISSUE TITLE
Dynamic resource configuration for Argo services is cluster size dependent

### ISSUE THREAD

**Issue by shrinandj** [argoproj/argo#164]
The resource configuration for Argo services is dependent on whether the cluster is a "small", "medium", "large" cluster (which in-turn decide what type of nodes form these clusters).

This makes it hard to install these services on already existing Kubernetes clusters.

Instead of making the resource requirements always cluster size dependent, it'll be good to have these services have default resource requirements.

**Comment by abhinavdas** [comment]
I think, when we install argo on user clusters, we can "reserve" a part of the cluster by asking the user what percentage of the cluster they want us to manage. We can taint nodes to mark them as `NoSchedule` and only argo jobs will tolerate that taint. This way we can use our admission controller to make forward progress on a user provisioned cluster. 

If the user does not prefer to do this, then we should run argo services in `small` configuration without any node selectors with the obvious caveat that their mileage may vary.

**Comment by shrinandj** [comment]
There are separate configs for "argo-all" and "argo-wfe" that allow installing all Argo services or workflow only respectively. Nothing more to do here.
