### ISSUE TITLE
Feature request: Get status of previous steps

### ISSUE THREAD

**Issue by burntangel** [argoproj/argo#1663]
In the same way we can access the output parameters and artifacts of previous steps/tasks using Argo variables, it would also be useful to be able to access the status of previous steps

The format could be:

- {{steps.\<STEPNAME\>.status}}
- {{tasks.\<TASKNAME\>.status}}

This would be particularly useful for cases where you want a step to be executed if at least one of the previous steps succeeded.

**Comment by simster7** [comment]
@sarabala1979 @jessesuen I could work on this?
