### ISSUE TITLE
[RFE] Allow multiple service accounts (SA) in the workflow

### ISSUE THREAD

**Issue by CermakM** [argoproj/argo#1664]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST

As Argo user, I would like to be able to use various service accounts in the workflow so that I could use multiple service accounts (and make use of the RBAC policy they have) in the workflow.

Example use cases:
- Use an existing SA with RBAC policy to create/delete CRs
- Use an existing SA with RBAC policy to create jobs in different namespaces
- Use an existing SA which can create ImageStreams (OpenShift)

In general, I don't want to bind all the roles that are necessary for an actual execution to the single SA which actually executes the workflow, this makes it also a bit harder to maintain in the longterm. Instead, I want to use existing SAs for different workflow steps.

Any estimation of the difficulty of the implementation?

Cheers!
  Marek

**Comment by kristofarkas** [comment]
Not sure if this is the feature you’re looking for, but template level service accounts was just added in v2.4.0: https://github.com/argoproj/argo/pull/1354

**Comment by CermakM** [comment]
Wohooo, yea! That sounds exactly like the feature I was looking for. Didn't see an issue for that and I was still on 2.3.0 ... and it also looks like that it's my lucky day today since 15 hours ago was the 2.4.0 released.

Thanks for all the great work!

**Comment by habinaya28** [comment]
Can someone provide an example as to how to add multiple service account names in a workflow template?
