### ISSUE TITLE
Document best practices and limitations of running Argo on user provided Kubernetes clusters

### ISSUE THREAD

**Issue by shrinandj** [argoproj/argo#168]
Supporting user provided Kubernetes clusters will provide lots of flexibility for running Argo. However, it will also increase chances of running into some bad experiences if the clusters are not provisioned correctly or the best practices are not adhered to.

This bug will be used to track the documentation needed for supporting user provided Kubernetes clusters. The best practices as well as the limitations should be documented.

**Comment by cyee88** [comment]
This is my understanding of the Argo/Argo Lite installation choices: 

If you want "5 minute wow" (i.e., just running workflows), then install Argo Lite (either on laptop or on an existing K8S cluster on AWS)

If you're ready to do workflows and deployments, then install Argo (either on existing K8S cluster on AWS or install full Argo platform)

Please correct any errors or omissions in my understanding.

**Comment by cyee88** [comment]
After talking with Mukulika, here's the revised high-level explanation of installation choices:

If you want to run a workflow and see how the YAML files drive it, then install Argo Lite (either on laptop with minikube or on an existing K8S cluster on AWS)

If you want to run applications and deployments, then install Argo (either on existing K8S cluster on AWS or install full Argo platform)
