### ISSUE TITLE
Argo Workflow metrics

### ISSUE THREAD

**Issue by danilorsilva** [argoproj/argo#1682]
**FEATURE REQUEST**

Hello all,

I try to find something about Argo Workflow metrics without success.

Is there any work in progress to Argo workflow export metrics to prometheus or something else? To monitoring jobs status.

Thanks

**Comment by simster7** [comment]
Would this help? https://argoproj.github.io/argo-cd/operator-manual/metrics/

**Comment by saranyaeu2987** [comment]
@simster7 
I dont have argo cd installed in my EKS cluster and have only Argo workflows. 
Is there a way to scrap metrics without Argo cd?

**Comment by simster7** [comment]
Hi, yes you can see Argo Workflows metrics here:

https://argoproj.github.io/argo/metrics/

Not sure why I linked to Argo CD above

**Comment by saranyaeu2987** [comment]
@simster7 
I am interested only in default metrics. There is no url mentioned in that link (https://argoproj.github.io/argo/metrics/)

Currently, my EKS argo workflows are accessed using
**http://internal-***********.us-east-1.elb.amazonaws.com:2746/workflows/argo**

So, can the metrics be scrapped at 
**http://internal-***********.us-east-1.elb.amazonaws.com:2746/metrics/**  ?

**Comment by simster7** [comment]
Try http://internal-***********.us-east-1.elb.amazonaws.com:9090/metrics/

**Comment by simster7** [comment]
How did you install Argo? With one of our manifests?

**Comment by simster7** [comment]
Metrics are exposed out of the `workflow-controller`

**Comment by saranyaeu2987** [comment]
Thanks. Can see metrics now.

**Comment by saranyaeu2987** [comment]
@simster7 
I would recommend adding endpoint details in https://argoproj.github.io/argo/metrics/ like the one added to https://argoproj.github.io/argo-cd/operator-manual/metrics/

It will save lot of time for a newbie like me :)

**Comment by simster7** [comment]
Would you like to open a PR? @saranyaeu2987

**Comment by saranyaeu2987** [comment]
https://github.com/argoproj/argo/pull/4829

DCO and semantic checks are failing
signed with right git account along with semantics. Still failing
