### ISSUE TITLE
[Bug] `arguments: {}` is added to templates after unmarshal/marchsl

### ISSUE THREAD

**Issue by Ark-kun** [argoproj/argo#1686]
We're trying to upgrade to Argo v2.4.1

We do some workflow augmentation as part of our test. It never touches `arguments` (as it did not exist in Argo v2.3.0).

```go
	err := yaml.Unmarshal([]byte( wf), &workflow)
	assert.Nil(t, err)
	newWf, nodes, err := formulateRetryWorkflow(&workflow)
	newWfString, err := yaml.Marshal(newWf)
```

The test fails and we see `arguments: {}` being added to the representation of container and DAG templates.

I think that fields should not become non-Nil just becauls of Unmarshal+Marshal.

@dtaniwaki Can you please take a look?

**Comment by sarabala1979** [comment]
v2.4.2 has been released with few fixes on argument substitution and 
DAG retry. Can you try it on v2.4.2?

**Comment by dtaniwaki** [comment]
@Ark-kun Sorry for the late reply. I'll check and fix it soon.

**Comment by dtaniwaki** [comment]
`Arguments` is not used anymore and will be removed in the future.

https://github.com/argoproj/argo/blob/54f5be361f597d45c97469095a2e5cb5678436a8/pkg/apis/workflow/v1alpha1/workflow_types.go#L338-L340

So, I think we can close this issue unless we need to fix it now.
