### ISSUE TITLE
UI not Showing Logs When Using Workflow Templates

### ISSUE THREAD

**Issue by janhicken** [argoproj/argo#1689]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Bug Report

**What happened**:
I created a workflow using workflow templates. When running the workflow and inspecting it in the UI, the button to read the logs is not shown. Also the _Containers_ tab on the right is empty.

**What you expected to happen**:
I expect to be able to read the pod's logs.

**How to reproduce it (as minimally and precisely as possible)**:
Create any workflow referencing a workflow template. Click on the referencing step in the UI.

**Anything else we need to know?**:

**Environment**:
- Argo version: 2.4.1
```
$ argo version
argo: v2.4.1
  BuildDate: 2019-10-08T23:14:59Z
  GitCommit: d7f099992d8cf93c280df2ed38a0b9a1b2614e56
  GitTreeState: clean
  GitTag: v2.4.1
  GoVersion: go1.11.5
  Compiler: gc
  Platform: linux/amd64

```
- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: "2019-09-18T14:47:22Z"
  compiler: gc
  gitCommit: 8fca2ec50a6133511b771a11559e24191b1aa2b4
  gitTreeState: clean
  gitVersion: v1.14.7
  goVersion: go1.12.9
  major: "1"
  minor: "14"
  platform: linux/amd64
serverVersion:
  buildDate: "2019-08-12T17:49:30Z"
  compiler: gc
  gitCommit: b48a8d693e191192e27c2f807daa51b54d0b0a61
  gitTreeState: clean
  gitVersion: v1.12.9-gke.15
  goVersion: go1.10.8b4
  major: "1"
  minor: 12+
  platform: linux/amd64

```

**Other debugging information (if applicable)**:
- workflow result:
```
$ argo get <workflowname>
```
- executor logs:
```
$ kubectl logs <failedpodname> -c init
$ kubectl logs <failedpodname> -c wait
```
- workflow-controller logs:
```
$ kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name)
```

**Comment by sudermanjr** [comment]
Same issue for output parameters as well.

**Comment by dtaniwaki** [comment]
I'm working on a fix for this issue.
https://github.com/argoproj/argo-ui/pull/52

**Comment by dtaniwaki** [comment]
Please try out dtaniwaki/argoui:v2.2.1-cfca2f6 from DockerHub.

**Comment by janhicken** [comment]
It works perfectly for me, I'm able to see the corresponding logs :+1:

**Comment by steve-dtg** [comment]
When can we expect this to be shipped into a release?
