### ISSUE TITLE
git-crypt secrets are exposed in Artifacts

### ISSUE THREAD

**Issue by swapnild2111** [argoproj/argo#1705]
Hello Team,
We have different steps in Argo workflow and they pass artifacts to each other. I have git-crypt to store secrets and I de-crypt them in my first step. So they get passed via artifacts to next steps. But these artifacts are downloadale, our secrets gets leaked. Can you please help with this?

**Comment by Jude188** [comment]
This is an issue we're facing too. 

We're using a workaround which is an exit handler which uses an pod with AWS CLI to delete the artifacts that the workflow has created. This is still not ideal as the secrets are downloadable from the UI which the workflow is running.

Maybe there should be an option to not allow one or all artifacts to be downloadable through the UI?

**Comment by alexec** [comment]
Can you provide an example of the secrets shown in the UI?

**Comment by swapnild2111** [comment]
For me - click on Argo step where you unlock your secrets, download its artifacts. There you can see all your git-crypt unlocked files & the secrets will be seen in plaint text.

**Comment by alexec** [comment]
Sorry - I was not clear - can you share the workflow YAML?

**Comment by swapnild2111** [comment]
`templates:
  - name: step-name
    steps:

    # Clone and decrypt the repository
    - - name: git-crypt
        template: git
        arguments:
          parameters:
          - name: cmd
            value: |
              echo "Unlocking git-crypt files"
              git clone {{workflow.parameters.repo-https-url}} .
              git checkout {{workflow.parameters.commit-id}}
              gpg --import && git-crypt unlock`
