### ISSUE TITLE
UI fails to load workflow list

### ISSUE THREAD

**Issue by conorcurlett** [argoproj/argo#1707]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Bug report
**What happened**:
After enabling the UI, and exposing it using the AWS ALB Ingress Controller and External DNS, I can browse to the URL and the outer react app loads. The call to /api/workflows gets a 502 (error) message however. Making a cURL request to /api/workflows/live returns a LOT of data. 
We run a very large number of workflows, and have had issues scaling etcd to handle the amount of traffic and data transfer occurring due to Argo. Because the API doesn't paginate from what I can tell from the source, is it possible its just failing to get the workflow list because it's too large?
**What you expected to happen**:
UI to load
**How to reproduce it (as minimally and precisely as possible)**:
Install to a k8s cluster
Run a large number of workflows
Attempt to load the UI
**Anything else we need to know?**:
Cluster is EKS, we have had AWS scale up the API Server and etcd multiple times reflecting the scale of our use of Argo
We use a large number of Spot instances managed by the cluster autoscaler, scaling up and down aggressively. The UI is running on a dedicated node through a nodeselector.
**Environment**:
- Argo version:
```
$ argo version
argo: v2.2.1
  BuildDate: 2018-10-11T16:26:28Z
  GitCommit: 3b52b26190163d1f72f3aef1a39f9f291378dafb
  GitTreeState: clean
  GitTag: v2.2.1
  GoVersion: go1.10.3
  Compiler: gc
  Platform: linux/amd64
```
Note that the version of the workflow controller running in the cluster is `v2.4.0-rc1`
- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: "2019-08-19T11:13:54Z"
  compiler: gc
  gitCommit: 2d3c76f9091b6bec110a5e63777c332469e0cba2
  gitTreeState: clean
  gitVersion: v1.15.3
  goVersion: go1.12.9
  major: "1"
  minor: "15"
  platform: linux/amd64
serverVersion:
  buildDate: "2019-09-24T20:54:25Z"
  compiler: gc
  gitCommit: 5876d6b7429820450950ade17fe7b4bf5ccada7f
  gitTreeState: clean
  gitVersion: v1.13.11-eks-5876d6
  goVersion: go1.11.13
  major: "1"
  minor: 13+
  platform: linux/amd64
```

**Other debugging information (if applicable)**:

- workflow-controller logs:
```
$ kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name)

time="2019-10-23T00:18:23Z" level=warning msg="ConfigMap 'workflow-controller-configmap' does not have key 'config'"
time="2019-10-23T00:18:23Z" level=warning msg="ConfigMap 'workflow-controller-configmap' does not have key 'config'"
time="2019-10-23T00:18:26Z" level=error msg="Failed to delete pod prod/a19-107-pesaresi-namnat-run1-1-brcbt-2163452909 for gc: pods \"a19-107-pesaresi-namnat-run1-1-brcbt-2163452909\" not found"
time="2019-10-23T00:23:10Z" level=error msg="Failed to delete pod prod/ripk1-xhit-enum-run3-1-jlvkn-523670041 for gc: pods \"ripk1-xhit-enum-run3-1-jlvkn-523670041\" not found"
time="2019-10-23T00:23:15Z" level=error msg="Failed to delete pod prod/ripk1-xhit-enum-run3-1-jlvkn-1862876324 for gc: pods \"ripk1-xhit-enum-run3-1-jlvkn-1862876324\" not found"
time="2019-10-23T00:23:21Z" level=error msg="Failed to delete pod prod/ripk1-xhit-enum-run3-1-jlvkn-3553185763 for gc: pods \"ripk1-xhit-enum-run3-1-jlvkn-3553185763\" not found"
time="2019-10-23T00:23:43Z" level=error msg="Failed to delete pod prod/ripk1-xhit-enum-run3-1-jlvkn-366732646 for gc: pods \"ripk1-xhit-enum-run3-1-jlvkn-366732646\" not found"
time="2019-10-23T00:23:50Z" level=error msg="Failed to delete pod prod/ripk1-xhit-enum-run3-1-jlvkn-3126145587 for gc: pods \"ripk1-xhit-enum-run3-1-jlvkn-3126145587\" not found"
time="2019-10-23T00:37:32Z" level=error msg="Failed to delete pod prod/a19-107-pesaresi-namnat-run1-1-brcbt-3883820033 for gc: pods \"a19-107-pesaresi-namnat-run1-1-brcbt-3883820033\" not found"
time="2019-10-23T00:42:47Z" level=error msg="Failed to delete pod prod/a19-106-pesaresi-namnat-run1-2-t2sv7-3441809399 for gc: pods \"a19-106-pesaresi-namnat-run1-2-t2sv7-3441809399\" not found"
time="2019-10-23T00:44:08Z" level=error msg="Failed to delete pod prod/aims4-akker-slt70-run1-2-24jsc-476602409 for gc: pods \"aims4-akker-slt70-run1-2-24jsc-476602409\" not found"
```

**Comment by alexec** [comment]
Is this still a problem please?

**Comment by ericandrewmeadows** [comment]
I get this problem when I have multiple tabs open to Argo Workflows UI on my laptop.  It can serve across many users, just not many tabs on the same machine.

**Comment by alexec** [comment]
Stale issue.

**Comment by tooptoop4** [comment]
did u solve @conorcurlett ?
