### ISSUE TITLE
[FEATURE REQUEST] specify automatic resume on timer

### ISSUE THREAD

**Issue by sudermanjr** [argoproj/argo#1709]
It would be really nice if we could specify a timer on suspend.

Example/Use-Case:

I have a workflow that spins up a bunch of infrastructure and then suspends so that it can be utilized or tested. Once the workflow is resumed, the infra is cleaned up along with all of the resources created by the workflow.

It would be really cool to put a timer on that so that if someone forgets to delete, it can be automatically cleaned up after x hours.

**Comment by simster7** [comment]
Not a bad idea, I'll look into this

**Comment by simster7** [comment]
FYI: We currently have https://github.com/argoproj/argo/pull/1704 that is similar to this and will allow a suspended workflow to stop execution after a set amount of time. However, this feature request would allow a suspended workflow to continue gracefully after a set amount of time and is therefore different.
