### ISSUE TITLE
Allow changing between "all", "partial" and "none" spot-instance-config.

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo#171]
Currently, the cluster UI shows a simple button that allows "enable" and "disable" of the spot-instance feature. This should be changed to show all the three possible options "All", "Partial" and "None" and the user should be allowed to choose any of these. Whatever the option is selected, it should be sent via json to axops (which forwards the request to axmon). The option that is chosen should be sent as the value of the "asgs" json field in the http request.

The request should be like this if the user chooses "all".

```
 curl -H "Content-Type: application/json" -X PUT -d '{"asgs":"all"}' http://localhost:8901/v1/axmon/cluster/spot_instance_config
```

Earlier, the only key value pair sent was "enabled" : "True" or "False".

Please use buttons group to represent selected state:

![1](https://user-images.githubusercontent.com/426437/30089475-f48307a8-9261-11e7-813b-88e19eb82aef.png)

**Comment by wokeGit** [comment]
PR: https://github.com/argoproj/argo/pull/173
