### ISSUE TITLE
for a specific workflow, how to set max parallel running limit

### ISSUE THREAD

**Issue by guohenghaha** [argoproj/argo#1711]
**Is this a BUG REPORT or FEATURE REQUEST?**:

FEATURE REQUEST

**What happened**:

I have a workflow template, and i want the max parallel running workflow is 2 even if i submit 200 workflows at once, what should i do?

I used `spec.parallelism` , but it's not works.

**Environment**:
- Argo version: 2.3.0
- Kubernetes version : 1.12

**Comment by sarabala1979** [comment]
For workflow level parallelism, you need to config in  `workflow-controller-configmap`.
Set your parallel requirement in `Parallelism`

**Comment by guohenghaha** [comment]
really thanksl, i will try
