### ISSUE TITLE
Argo is truncating pod logs

### ISSUE THREAD

**Issue by thundergolfer** [argoproj/argo#1717]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT 🐛 

**What happened**:

Running the following:

`argo -n argo logs -f ds-dev template-stats-pipeline-lk6vx-1796972213`

produces truncated logs, as evidenced by the output of this:

`kubectl -n argo logs  template-stats-pipeline-lk6vx-1796972213 -c main`

being many many lines longer. 

`wf.sh logs -f ds-dev --follow --workflow template-stats-pipeline-lk6vx` 

Has the same problem. It stops spitting out logs at precisely the same point that the logs become truncated. 

**What you expected to happen**:

Argo's CLI should return the same results as `kubectl`, and the `--follow --workflow` functionality should not stall.

**How to reproduce it (as minimally and precisely as possible)**:

working on it....

I'm not able to share the code that's affected by this in my company. It's Python code though so I'll find time to try reproduce with an open-source Python container. 

**Anything else we need to know?**:

**Environment**:
- Argo version: `2.4.1` (we're using Nix)
- Kubernetes version : 
```
$ kubectl version -o yaml

clientVersion:
  buildDate: "1970-01-01T00:00:01Z"
  compiler: gc
  gitCommit: 5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0
  gitTreeState: archive
  gitVersion: v1.14.3
  goVersion: go1.12.7
  major: "1"
  minor: "14"
  platform: darwin/amd64
serverVersion:
  buildDate: "2019-09-21T08:33:01Z"
  compiler: gc
  gitCommit: e9b1d0551216e1e8ace5ee4ca50161df34325ec2
  gitTreeState: clean
  gitVersion: v1.14.7-eks-e9b1d0
  goVersion: go1.12.9
  major: "1"
  minor: 14+
  platform: linux/amd64
```

---- 

**Precedents:** https://github.com/argoproj/argo/issues/819, 
**Related:** https://github.com/argoproj/argo/issues/1259

**Comment by thundergolfer** [comment]
I'm pretty sure this has been an issue since at least #1259 in March 2019, but likely #819. So it's worth trying to reproduce.

**Comment by thundergolfer** [comment]
_Update:_ I've begun working on an open-source reproduction of this bug here -> https://github.com/thundergolfer-playground/argo-logs-truncation-bug-repro

I'll update the "How to reproduce it" section once I've confirmed that the above actually does reproduce the bug. 

👍

**Comment by mehtadeepen** [comment]
@thundergolfer I have also faced this issue intermittently.

**Comment by thundergolfer** [comment]
@mehtadeepen It would be great to get details so I can narrow down what's causing this. 

My attempted reproduction above is targeting the context that we had when we saw this problem. Unfortunately running it didn't trigger the issue.
