### ISSUE TITLE
Approval Container Integration with UI

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo#172]
Allow approve workflows with approval step from job details page.

- [ ] Job details page should list all pending approvals from all approval steps
- [ ] If current user is one of approvers when 'Approve' button should be rendered on step panel

<img width="1392" alt="screen shot 2017-09-06 at 5 55 21 pm" src="https://user-images.githubusercontent.com/426437/30140943-ecf4ee90-932c-11e7-8ce9-84522f2168cd.png">

**Comment by sytianhe** [comment]
I need to check this as approval is a step just like any other user-defined steps. From the image above, I can see it tries to show a status for the workflow. However, this is not accurate as if there are multiple approval steps in the workflow and they are in parallel steps, how would the UI shows the status correctly...

I was thinking more of a UI status for each individual approval step (showing in the small box), which will require the UI to recognize the approval step. I can provide an api to check whether a workflow_id/step_id is an approval step and the approval details for this step. Is this something we  can start with?

**Comment by roofi07** [comment]
I think that we need details about approval step in exists api. Details I mean: who is assigned to approve and who approved.

**Comment by jessesuen** [comment]
Closing v1 issues.
