### ISSUE TITLE
Adding Pod Disruption budget for each workflow run by argo controller so that Pod/Step does not gets deleted during autoscaling event

### ISSUE THREAD

**Issue by mehtadeepen** [argoproj/argo#1728]
**Is this a BUG REPORT or FEATURE REQUEST?**: Feature

**What you expected to happen**:

Adding Pod Disruption budget for each workflow run by argo controller so that Pod/Step does not gets deleted during autoscaling event

**Comment by frozeNinK** [comment]
@simster7 

Hi, I may have some spare time to work on this feature.
Could you plz point out which part (logic) should be modified? (I am new to Argo)

Thanks

**Comment by alexec** [comment]
@sarabala1979 close?
