### ISSUE TITLE
Bug: Setting value of global output parameter even if worklfow fails

### ISSUE THREAD

**Issue by mehtadeepen** [argoproj/argo#1730]
**Is this a BUG REPORT or FEATURE REQUEST?**: Bug

**What happened**:
Argo controller not setting value of  global output parameter even if step fails

**What you expected to happen**:
It should set it even if it fails. It should be independent of step execution.

**How to reproduce it (as minimally and precisely as possible)**:

Working on it

**Comment by alexec** [comment]
@mehtadeepen is this a duplicate of #1759?

**Comment by mehtadeepen** [comment]
@alexec Yes. Should I close this?

**Comment by mehtadeepen** [comment]
Closing issue as it duplicate of #1759
