### ISSUE TITLE
Argo Java SDK for developers

### ISSUE THREAD

**Issue by mehtadeepen** [argoproj/argo#1731]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 Feature

If we have argo java sdk for developers then it would be really helpful to integrate with other application in my company.

**Comment by harry0123** [comment]
This would be helpful for integrating with applications in my company too! 😉

**Comment by naiduasn** [comment]
would n't any existing kubernetes java client work? like this https://github.com/kubernetes-client/java

**Comment by sarabala1979** [comment]
Are you looking Java ask for Argo workflow? Kubernetes Java SDk can be used for all basic kubectl operation for workflow

**Comment by sarabala1979** [comment]
We are working Argo API server with grpc support. Once this is done, we can easy create all language SDK with full functionality

**Comment by alexec** [comment]
See 
* https://github.com/argoproj-labs/argo-java-client
* https://github.com/argoproj-labs/argo-java-client/issues/8

**Comment by alexec** [comment]
Pending happiness.

**Comment by mehtadeepen** [comment]
@alexec We are yet to check sdk. We are still use argo cli.
