### ISSUE TITLE
Typo in rest-api.md

### ISSUE THREAD

**Issue by aviweit** [argoproj/argo#1740]
Hi,

There is a typo in https://github.com/argoproj/argo/blob/master/docs/rest-api.md 2nd line:
argorproj.io/v1alpha1 should be argoproj.io/v1alpha1

It caused errors in my REST client until I noticed this typo.

Thanks.

**Comment by simster7** [comment]
Feel free to submit a PR with the fix.

**Comment by aviweit** [comment]
I created PR at: https://github.com/argoproj/argo/pull/1745

Thanks.

**Comment by simster7** [comment]
Closed by #1745
