### ISSUE TITLE
Argo input artifacts with files > 6 GB cause The node was low on resource Error

### ISSUE THREAD

**Issue by lorenz-99** [argoproj/argo#1742]
BUG REPORT  

when using an artifact with input of a file > 6 GB the workflow errors with the message: The node was low on resource: ephemeral-storage"

Success is expected as with smaller files

loading a large file (6 GB) into an S3 bucket, then starting the workflow. 

kubectl descrieb nodes show 0% for ephemeral storage while running the workflow

**Environment**:
- Argo version:
```
argo: v2.2.1
  BuildDate: 2018-10-11T16:26:28Z
  GitCommit: 3b52b26190163d1f72f3aef1a39f9f291378dafb
  GitTreeState: clean
  GitTag: v2.2.1
  GoVersion: go1.10.3
  Compiler: gc
  Platform: linux/amd64

```
- Kubernetes version : EKS 1.14
```
$ kubectl version -o yaml
clientVersion:
  buildDate: "2019-07-23T03:14:24Z"
  compiler: gc
  gitCommit: fa4c703fa1706fac99d00d7f1f2080e9d4cc7eed
  gitTreeState: clean
  gitVersion: v1.13.7-eks-fa4c70
  goVersion: go1.11.5
  major: "1"
  minor: 13+
  platform: linux/amd64
serverVersion:
  buildDate: "2019-08-21T22:32:40Z"
  compiler: gc
  gitCommit: 5047edce664593832e9b889e447ac75ab104f527
  gitTreeState: clean
  gitVersion: v1.14.6-eks-5047ed
  goVersion: go1.12.9
  major: "1"
  minor: 14+
  platform: linux/amd64


**Other debugging information (if applicable)**:
- workflow result: The node was low on resource: ephemeral-storage. Container wait was using 12Ki, which exceeds its request of 0.
```
$ argo get <workflowname>
Name:                proteomics-pipeline-diann-out-l6qmk
Namespace:           argo
ServiceAccount:      default
Status:              Running
Created:             Wed Nov 06 16:23:18 +0100 (13 minutes ago)
Started:             Wed Nov 06 16:23:18 +0100 (13 minutes ago)
Duration:            13 minutes 52 seconds

STEP                                    PODNAME                              DURATION  MESSAGE
 ◷ proteomics-pipeline-diann-out-l6qmk  proteomics-pipeline-diann-out-l6qmk  13m       Unschedulable: 0/3 nodes are available: 3 Insufficient cpu.

- executor logs:
```
$ kubectl logs <failedpodname> -c init
$ kubectl logs <failedpodname> -c wait
```
- workflow-controller logs:
```
$ kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name)

time="2019-11-06T15:32:58Z" level=info msg="Alloc=5354 TotalAlloc=92194 Sys=70078 NumGC=169 Goroutines=69"
time="2019-11-06T15:37:58Z" level=info msg="Alloc=5357 TotalAlloc=92248 Sys=70078 NumGC=171 Goroutines=69"
W1106 15:39:03.960592       1 reflector.go:289] github.com/argoproj/argo/workflow/controller/config_controller.go:116: watch of *v1.ConfigMap ended with: too old resource version: 4052723 (4053560)
time="2019-11-06T15:42:58Z" level=info msg="Alloc=5323 TotalAlloc=92333 Sys=70078 NumGC=174 Goroutines=69"

```

**Comment by salanki** [comment]
Sounds like you are running out of local storage on your node.

**Comment by lorenz-99** [comment]
Thanks, Peter - yes, I've increased storage and I'm requesting ephemeral storage in the workflow, as well. Do you think it's going to work with 200 GB files?

**Comment by alexec** [comment]
Can I please ask if this is still a problem with v2.8?

**Comment by alexec** [comment]
No reply. Closing.

**Comment by sachinlionel** [comment]
How can we get large input artifacts working? I see same error as in description.

**Comment by tczhao** [comment]
@sachinlionel 
You can try use pvc and mount it to the same path to your artifact download path.
This way, the artifacts are downloading directly to the PVC instead of using node volume
