### ISSUE TITLE
Support session token to access S3

### ISSUE THREAD

**Issue by duyngle** [argoproj/argo#1749]
**Is this a BUG REPORT or FEATURE REQUEST?**:

Feature request

**What happened**:
One more option to add Session Token along with Access Key ID & Secret Access Key.
When I try to run workflow locally,I cannot be able to call metadata server (http://169.254.169.254) to assume role. Need to have a way to directly provide aws temp credential in the workflow to make connection.

**Screenshot**
<img width="453" alt="Screen Shot 2019-11-07 at 2 13 32 PM" src="https://user-images.githubusercontent.com/4967217/68432243-ed702e00-0168-11ea-90a9-87e848cea662.png">

**Comment by simster7** [comment]
Would something like this work? https://github.com/argoproj/argo/issues/1668#issuecomment-544664510

**Comment by agilgur5** [comment]
This was superseded by #5446
