### ISSUE TITLE
DNS config example not working

### ISSUE THREAD

**Issue by vdinesh1990** [argoproj/argo#1751]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG

**What happened**: dnsConfig in https://github.com/argoproj/argo/blob/master/examples/dns-config.yaml not working

**What you expected to happen**: container dns config should be changed

**How to reproduce it (as minimally and precisely as possible)**: kubectl -n default create -f dns-config.yaml

kubectl get pod <pod_name> -o yaml

check the dnsConfig

**Anything else we need to know?**:

**Environment**:
- Argo version: v2.2.0
```
$ argo version
```
- Kubernetes version : 1.12
```
$ kubectl version -o yaml
```

**Other debugging information (if applicable)**:
- workflow result:
```
$ argo get <workflowname>
```
- executor logs:
```
$ kubectl logs <failedpodname> -c init
$ kubectl logs <failedpodname> -c wait
```
- workflow-controller logs:
```
$ kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name)
```

**Comment by sarabala1979** [comment]
Not reproducible.
