### ISSUE TITLE
Setting default value for output parameters with globalName, the workflow fails to report "failed to save outputs: exit status 2"

### ISSUE THREAD

**Issue by cccdy** [argoproj/argo#1755]
Similar to issue 954(https://github.com/argoproj/argo/issues/954), i set default empty string for output parameters,but i make it global output by globalName,but the workflow fail to report "failed to save outputs: exit status 2". i have some try, but fail. Wish for some help, thanks!

**Environment**:
- Argo version:
argo: v2.2.1
  BuildDate: 2018-10-11T16:26:28Z
  GitCommit: 3b52b26190163d1f72f3aef1a39f9f291378dafb
  GitTreeState: clean
  GitTag: v2.2.1
  GoVersion: go1.10.3
  Compiler: gc
  Platform: linux/amd64
- Kubernetes version :
clientVersion:
  buildDate: 2018-10-05T16:46:06Z
  compiler: gc
  gitCommit: 4ed3216f3ec431b140b1d899130a69fc671678f4
  gitTreeState: clean
  gitVersion: v1.12.1
  goVersion: go1.10.4
  major: "1"
  minor: "12"
  platform: linux/amd64
serverVersion:
  buildDate: 2018-06-27T20:08:34Z
  compiler: gc
  gitCommit: 91e7b4fd31fcd3d5f436da26c980becec37ceefe
  gitTreeState: clean
  gitVersion: v1.11.0
  goVersion: go1.10.2
  major: "1"
  minor: "11"
  platform: linux/amd64

**Other debugging information (if applicable)**:
- workflow result:
failed to save outputs: exit status 2

- executor logs:
time="2019-11-12T05:46:55Z" level=error msg="`[sh -c docker cp -a 7216740ce5d4a0512f54fc248a20194e191134e8a499c529cb0009df5e1afc2f:/tmp/recommend_error.txt - | tar -ax -O]` stderr:\nError: No such container:path: 7216740ce5d4a0512f54fc248a20194e191134e8a499c529cb0009df5e1afc2f:/tmp/recommend_error.txt\ntar: This does not look like a tar archive\ntar: Exiting with failure status due to previous errors\n"

**Comment by sarabala1979** [comment]
Can you upgrade to the latest version or v2.3 and try the same scenario?
