### ISSUE TITLE
Add audit logging for Workflow resources

### ISSUE THREAD

**Issue by simster7** [argoproj/argo#1769]
Currently `kubectl describe wf [...]` does not display anything under `Events`:

```
$ kubectl describe wf
Name:         cron-hw-5skx4
...
Events:  <none>
```

It would be useful to log significant events during the Workflow's execution

**Comment by amarrella** [comment]
I agree this would be great! It would also make it easier to watch on these events to trigger alerts/etc

**Comment by amarrella** [comment]
I can try to help with this but I have never written Go. Any pointers would be appreciated :)
