### ISSUE TITLE
Retries with artifacts in DAG is not working

### ISSUE THREAD

**Issue by jangojam** [argoproj/argo#1770]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT
**What happened**:
my yaml 
```apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: artifact-passing-
spec:
  entrypoint: artifact-example
  templates:
  - name: artifact-example
    dag:
      tasks:
      - name: generate-artifact
        template: whalesay
      - name: consume-artifact
        template: print-message
        dependencies: [generate-artifact]
        arguments:
          artifacts:
          - name: message
            from: "{{tasks.generate-artifact.outputs.artifacts.hello-art}}"
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [sh, -c]
      args: ["sleep 1; cowsay hello world | tee /tmp/hello_world.txt"]
    outputs:
      artifacts:
      - name: hello-art
        path: /tmp/hello_world.txt
    retryStrategy:
      limit: 3
  - name: print-message
    retryStrategy:
      limit: 3
    inputs:
      artifacts:
      - name: message
        path: /tmp/message
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["cat /tmp/message"]
```
and the workflow status is Error
STEP                                          PODNAME                            DURATION  MESSAGE
 ⚠ artifact-passing-v7vbf (artifact-example)
 ├-✔ generate-artifact(0) (whalesay)          artifact-passing-v7vbf-1512299620  47s
 └-✔ consume-artifact(0) (print-message)      artifact-passing-v7vbf-570011547   23s

when I remove the retryStrategy parameter, it can work.

**Environment**:
- Argo version: 
```
$ argo version
v2.4.1
```
- Kubernetes version :
```
$ kubectl version -o yaml
v1.12.6
```

**Comment by ptemmer** [comment]
I'm seeing something similar. The DAG itself is marked as "ERROR", while it's tasks have the green check and finished fine.
Interesting to mention is that the workflow stops at that point as if it finished, although there are much more tasks after the DAG.
Without "retryStrategy", the all tasks get executed as expected.
