### ISSUE TITLE
Argo not executing a next step in a dag even though previous step is successful

### ISSUE THREAD

**Issue by tyagi-prashant** [argoproj/argo#1772]
**Is this a BUG REPORT or FEATURE REQUEST?**:

**What happened**: I have a certain tasks in my DAG where in my first step i'm  creating some artifacts which will be consume by all other tasks down the tree. but after executing 2 steps next step is not being created in the argo.

**What you expected to happen**:I expect  that next step should be run.

**How to reproduce it (as minimally and precisely as possible)**: 

**Anything else we need to know?**: No

**Environment**:  Ubuntu/Linux
- Argo version:argo: v2.3.0
```
$ argo version 
```
- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: "2019-09-18T14:36:53Z"
  compiler: gc
  gitCommit: 2bd9643cee5b3b3a5ecbd3af49d09018f0773c77
  gitTreeState: clean
  gitVersion: v1.16.0
  goVersion: go1.12.9
  major: "1"
  minor: "16"
  platform: linux/amd64
serverVersion:
  buildDate: "2019-08-19T10:44:49Z"
  compiler: gc
  gitCommit: 37d169313237cb4ceb2cc4bef300f2ae3053c1a2
  gitTreeState: clean
  gitVersion: v1.13.10
  goVersion: go1.11.13
  major: "1"
  minor: "13"
  platform: linux/amd64

```

**Other debugging information (if applicable)**:
- workflow result:
```
$ argo get <workflowname>
Name:                osvalidation

-4sq8q
Namespace:           default
ServiceAccount:      default
Status:              Running
Created:             Fri Nov 15 09:07:02 +0000 (10 minutes ago)
Started:             Fri Nov 15 09:07:02 +0000 (10 minutes ago)
Duration:            10 minutes 34 seconds

STEP                                    PODNAME                        DURATION  MESSAGE
 ● osvalidation-4sq8q
 ├-✔ createMainValidationInputFile(0)  osvalidation-4sq8q-3821993795  6s
 └-✔ mainCleanup(0)                    osvalidation-4sq8q-1557476242  11s

```
- executor logs:
```
$ kubectl logs <failedpodname> -c init
$ kubectl logs <failedpodname> -c wait
```
- workflow-controller logs:
```
$ kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name)
```
Here is my yaml that i'm using for workflow 
`apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: osvalidation-
spec:
  entrypoint: main
  imagePullSecrets:
    - name: regcred 
  templates:
  - name: main
    dag:
      tasks:
      - name: createMainValidationInputFile
        template: createMainValidationInputFile
      - name: mainCleanup
        dependencies: [createMainValidationInputFile]
        template: mainCleanup
        arguments:
          artifacts:
          - name: mainValidationInputFile
            from: "{{tasks.createMainValidationInputFile.outputs.artifacts.mainValidationInputFile}}"
      - name: processMainConfigAndCopyFilesOnRemoteHost
        dependencies: [mainCleanup]
        template: processMainConfigAndCopyFilesOnRemoteHost
        arguments:
          artifacts:
          - name: mainValidationInputFile
            from: "{{tasks.createMainValidationInputFile.outputs.artifacts.mainValidationInputFile}}"
      - name: extractBinariesAndRunMain
        dependencies: [processMainConfigAndCopyFilesOnRemoteHost]
        template: extractBinariesAndRunMain
        arguments:
          artifacts:
          - name: mainValidationInputFile
            from: "{{tasks.createMainValidationInputFile.outputs.artifacts.mainValidationInputFile}}"
      - name: pollForMainCompletion
        dependencies: [extractBinariesAndRunMain]
        template: pollForMainCompletion
        arguments:
          artifacts:
          - name: mainValidationInputFile
            from: "{{tasks.createMainValidationInputFile.outputs.artifacts.mainValidationInputFile}}"
  - name: createMainValidationInputFile
    retryStrategy:
      limit: 3
    container:
      image: osvalidationacr.azurecr.io/mainValidation/osvalidator:latest
      command: [/inputdir/createMainValidationInputFile.sh]
    outputs:
      artifacts:
      - name: mainValidationInputFile
        path: /inputdir/main_validation_input.json
  - name: mainCleanup
    inputs:
      artifacts:
      - name: mainValidationInputFile
        path: /inputdir/main_validation_input.json
    retryStrategy:
      limit: 3
    container:
      image: osvalidationacr.azurecr.io/mainValidation/osvalidator:latest
      command: [/inputdir/osvalidator]
      args: ["--input-dir=/inputdir", "--input-config=main_validation_input.json", "--validation-step=Cleanup"]
  - name: processMainConfigAndCopyFilesOnRemoteHost
    inputs:
      artifacts:
      - name: mainValidationInputFile
        path: /inputdir/main_validation_input.json
    retryStrategy:
      limit: 3
    container:
      image: osvalidationacr.azurecr.io/mainValidation/osvalidator:latest
      command: [/inputdir/osvalidator]
      args: ["--input-dir=/inputdir", "--input-config=main_validation_input.json", "--validation-step=ProcessMainConfigAndCopyFilesOnRemoteHost"]
  - name: extractBinariesAndRunMain
    inputs:
      artifacts:
      - name: mainValidationInputFile
        path: /inputdir/main_validation_input.json
    retryStrategy:
      limit: 3
    container:
      image: osvalidationacr.azurecr.io/mainValidation/osvalidator:latest
      command: [/inputdir/osvalidator]
      args: ["--input-dir=/inputdir", "--input-config=main_validation_input.json", "--validation-step=ExtractBinariesAndRunMain"]
  - name: pollForMainCompletion
    inputs:
      artifacts:
      - name: mainValidationInputFile
        path: /inputdir/main_validation_input.json
    container:
      image: osvalidationacr.azurecr.io/mainValidation/osvalidator:latest
      command: [/inputdir/waitForMainCompletion.sh]`

**Comment by simster7** [comment]
Could you please add a Workflow that is able to reproduce this?

**Comment by tyagi-prashant** [comment]
Hi @simster7 
You can reproduce this by running a below workflow.All the containers used are fetched from docker hub so you just have to run this as it,is, no change needed from your side to run this workflow.
`apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: osvalidation-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: createMainValidationInputFile
        template: createMainValidationInputFile
      - name: mainCleanup
        dependencies: [createMainValidationInputFile]
        template: mainCleanup
        arguments:
          artifacts:
          - name: mainValidationInputFile
            from: "{{tasks.createMainValidationInputFile.outputs.artifacts.mainValidationInputFile}}"
      - name: processMainConfigAndCopyFilesOnRemoteHost
        dependencies: [mainCleanup]
        template: processMainConfigAndCopyFilesOnRemoteHost
        arguments:
          artifacts:
          - name: mainValidationInputFile
            from: "{{tasks.createMainValidationInputFile.outputs.artifacts.mainValidationInputFile}}"
      - name: extractBinariesAndRunMain
        dependencies: [processMainConfigAndCopyFilesOnRemoteHost]
        template: extractBinariesAndRunMain
        arguments:
          artifacts:
          - name: mainValidationInputFile
            from: "{{tasks.createMainValidationInputFile.outputs.artifacts.mainValidationInputFile}}"
      - name: pollForMainCompletion
        dependencies: [extractBinariesAndRunMain]
        template: pollForMainCompletion
        arguments:
          artifacts:
          - name: mainValidationInputFile
            from: "{{tasks.createMainValidationInputFile.outputs.artifacts.mainValidationInputFile}}"
  - name: createMainValidationInputFile
    retryStrategy:
      limit: 3
    container:
      image: prashant221295/osvalidator:latest
      command: [/inputdir/createMainValidationFile.sh]
    outputs:
      artifacts:
      - name: mainValidationInputFile
        path: /inputdir/main_validation_input.json
  - name: mainCleanup
    inputs:
      artifacts:
      - name: mainValidationInputFile
        path: /inputdir/main_validation_input.json
    retryStrategy:
      limit: 3
    container:
      image: prashant221295/osvalidator:latest
      command: [/inputdir/osvalidator.sh]
      args: ["--input-config=main_validation_input.json"]
  - name: processMainConfigAndCopyFilesOnRemoteHost
    inputs:
      artifacts:
      - name: mainValidationInputFile
        path: /inputdir/main_validation_input.json
    retryStrategy:
      limit: 3
    container:
      image: prashant221295/osvalidator:latest
      command: [/inputdir/osvalidator.sh]
      args: ["--validation-step=ProcessMainConfigAndCopyFilesOnRemoteHost"]
  - name: extractBinariesAndRunMain
    inputs:
      artifacts:
      - name: mainValidationInputFile
        path: /inputdir/main_validation_input.json
    retryStrategy:
      limit: 3
    container:
      image: prashant221295/osvalidator:latest
      command: [/inputdir/osvalidator.sh]
      args: ["--validation-step=ExtractBinariesAndRunMain"]
  - name: pollForMainCompletion
    inputs:
      artifacts:
      - name: mainValidationInputFile
        path: /inputdir/main_validation_input.json
    container:
      image: prashant221295/osvalidator:latest
      command: [/inputdir/waitForMainCompletion.sh]`
