### ISSUE TITLE
Expose exit code in as output parameter

### ISSUE THREAD

**Issue by epa095** [argoproj/argo#1773]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Feature request

When doing `argo get ...` I can see the exit code for failed workflows. It would be reasonable if the exit code for steps could be exposed as an output parameter and used for other parts in the workflow. E.g. to [not retry](https://github.com/argoproj/argo/issues/1150) a step for certain exit codes, or to use the exit code in conditionals.

**Comment by simster7** [comment]
Seems reasonable. Have you thought about contributing a fix?

**Comment by epa095** [comment]
> Seems reasonable. Have you thought about contributing a fix?

Unfortunately I dont know go:-/

**Comment by cloud-on-prem** [comment]
@epa095 - Thanks for using Argo and for the awesome suggestion.

@simster7 - I'm looking to pick this one. Quick clarification - Would this apply only for `script` type `templates`? Or do you see this working for a `container` type as well? if so, how do we handle multiple `exitCodes` in a `Pod` - say a template that has a `sidecar`?

**Comment by sarabala1979** [comment]
Exitcode should be expose for script and container template types. Exitcode should be from main container.

**Comment by cloud-on-prem** [comment]
@sarabala1979 roger that.

**Comment by rdigiorgio** [comment]
@cloud-on-prem are you still working on it ?

**Comment by cloud-on-prem** [comment]
@rdigiorgio - sorry this fell off my radar. I did some initial digging around but haven't been to find time to get it work properly. Are you planning on picking this up? Feel free to do so.

**Comment by rdigiorgio** [comment]
I think this requires some more reflexion.

Do we really want the exit code to be exposed as an **output** ?
AFAIK, whenever a script / container template fails, there are no output and the whole template is marked as failed, so it does not feel right for me.
Also, any step that would come after a failed step (possibly using a script / container template with an exit code) will not be executed.

**Comment by simster7** [comment]
@rdigiorgio I think this is meant to add the exit code as an [output _variable_](https://github.com/argoproj/argo/blob/master/docs/variables.md#steps-templates). Something like `steps.<STEPNAME>.outputs.exitcode` and `tasks.<TASKNAME>.outputs.exitcode`.

> AFAIK, whenever a script / container template fails, there are no output and the whole template is marked as failed, so it does not feel right for me.

Some output variables such as `result` still get filled after a step fails.

> Also, any step that would come after a failed step (possibly using a script / container template with an exit code) will not be executed.

Not always true, a step or DAG task could have `continueOn: failed: true`. See [example](https://github.com/argoproj/argo/blob/master/examples/continue-on-fail.yaml).

> Should this exit code be only available to use with retry strategies ?

It should be available regardless of retryStrategy

**Comment by simster7** [comment]
Let me know if you want to take on this change and I can assign the issue to you

**Comment by rdigiorgio** [comment]
Thanks for clarifying, I just have had a newborn so I am trying to work on it when I have spare time (do I really have some ? lol) because I might need this at work

**Comment by rdigiorgio** [comment]
@simster7 I created a pull request for this #2111

**Comment by simster7** [comment]
>  I just have had a newborn

Congratulations! 🎊 🎉
