### ISSUE TITLE
What's a good way to manage and search workflow & job info

### ISSUE THREAD

**Issue by yujingz** [argoproj/argo#1783]
Is there any recommended way to manage the information of a workflow/job, it's related parameters and job status. So users are able to search by let's say parameters, dates, job status etc. Or this is totally a different topic we should build our own record/job tracking system to do this.

Thanks!

**Comment by sarabala1979** [comment]
The current v2.4.2 version supports secondary persistence to store the workflow objects.  The next v2.5 will support API Server with persistence. So, the user can query the workflow with all filters.

**Comment by yujingz** [comment]
> The current v2.4.2 version supports secondary persistence to store the workflow objects. The next v2.5 will support API Server with persistence. So, the user can query the workflow with all filters.

Awesome, thanks for the info and quick reply.
