### ISSUE TITLE
Argo Executor Error message is misleading if service account doesn't have permission

### ISSUE THREAD

**Issue by sarabala1979** [argoproj/argo#1792]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG

**What happened**:
The controller is executing the next step if the previous step didn;t capture the output because of the permission issue and an error message is misleading.
`Invalid 'when' expression '{{steps.flip-coin.outputs.result}} == heads': Invalid token: '{{'`

**What you expected to happen**:
The step should fail with the correct error message

**Comment by simster7** [comment]
https://stackoverflow.com/questions/58834064/can-not-execute-argo-workflow-due-to-invalid-when-expression-in-workflow-file

**Comment by simster7** [comment]
Related issue from actual user: https://stackoverflow.com/questions/58834064/can-not-execute-argo-workflow-due-to-invalid-when-expression-in-workflow-file

**Comment by simster7** [comment]
This will be fixed by https://github.com/argoproj/argo/pull/1776

**Comment by simster7** [comment]
Closed by #1776
