### ISSUE TITLE
Start a workflow without the yaml definition

### ISSUE THREAD

**Issue by jomach** [argoproj/argo#1794]
FEATURE REQUEST:

**What happened**:
I would like to expose the argo workflow to users and just tell the users: 
"Your workflow is the one with name template1" Now they can start the workflow when they want by just calling template1.

**What you expected to happen**:
We should have a place were we can define and store workflows that then can be started by others.

**Environment**:

```
argo: v2.4.2
  BuildDate: 2019-10-21T18:39:52Z
  GitCommit: 675c66267f0c916de0f233d8101aa0646acb46d4
  GitTreeState: clean
  GitTag: v2.4.2
  GoVersion: go1.11.5
  Compiler: gc
  Platform: darwin/amd64
```
> $ minikube start
😄  minikube v1.5.2 on Darwin 10.15.1
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🔄  Starting existing hyperkit VM for "minikube" ...
⌛  Waiting for the host to be provisioned ...
🐳  Preparing Kubernetes v1.16.2 on Docker '18.09.9' ...
🔄  Relaunching Kubernetes using kubeadm ...
⌛  Waiting for: apiserver
🏄  Done! kubectl is now configured to use "minikube"

**Comment by sarabala1979** [comment]
you can try the `resubmit` option in argocli. This will create a new workflow from the already created workflow.

'argo resubmit <workflowname>`

**Comment by jomach** [comment]
what would be the api for it? Is the workflowname the one generated from K8 ? If yes this will not work because: 
* Image I re-setup my argo people will still call re-submit on a old "thing"

**Comment by simster7** [comment]
Hi @jomach. You can always use the `name` field (instead of `generateName`) to run your worklfows. This will use the same name to run it every time. For example:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: hello-world
spec:
  entrypoint: whalesay
  templates:
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["hello world"]
```
For the first run, you would submit just like normal:
```
$ argo submit --watch examples/hello-world.yaml
Name:                hello-world
Namespace:           argo
ServiceAccount:      default
Status:              Pending
Created:             Tue Nov 26 08:46:57 -0800 (1 second ago)
```
And then from then on you would use `resubmit` like @sarabala1979 mentioned:
```
$ argo resubmit --watch hello-world
Name:                hello-world-888w7
Namespace:           argo
ServiceAccount:      default
Status:              Pending
Created:             Tue Nov 26 08:47:16 -0800 (1 second ago)
```

**Comment by jomach** [comment]
Hmm that would work ... thanks a lot.

**Comment by antoniomo** [comment]
How does this work when you want to resubmit with different parameters? Templates doesn't help either, as they aren't directly submittable: https://github.com/argoproj/argo/issues/2007
