### ISSUE TITLE
Argo suspend template example does not work.

### ISSUE THREAD

**Issue by jimbeck** [argoproj/argo#1795]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 BUG REPORT 

**What happened**:
 Example in documentation does not work for suspending a template using duration as defined by this example: https://github.com/argoproj/argo/blob/master/examples/suspend-template.yaml
This error was thrown `Failed to parse workflow: error unmarshaling JSON: while decoding JSON: json: unknown field "duration"` The workflow never even gets created.

**What you expected to happen**:
I expected the sample code to work.

**How to reproduce it (as minimally and precisely as possible)**:
Run argo submit on this file `https://github.com/argoproj/argo/blob/master/examples/suspend-template.yaml`

**Anything else we need to know?**:

**Environment**:
- Argo version: 
```
$ argo version
argo: v2.4.2
  BuildDate: 2019-10-21T18:39:29Z
  GitCommit: 675c66267f0c916de0f233d8101aa0646acb46d4
  GitTreeState: clean
  GitTag: v2.4.2
  GoVersion: go1.11.5
  Compiler: gc
  Platform: linux/amd64
```
- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: "2019-07-31T00:59:16Z"
  compiler: gc
  gitCommit: cd3eb06a896644a770b14acf6b3123b417fa50e9
  gitTreeState: clean
  gitVersion: v1.13.8-eks-cd3eb0
  goVersion: go1.11.5
  major: "1"
  minor: 13+
  platform: linux/amd64
serverVersion:
  buildDate: "2019-09-21T08:33:01Z"
  compiler: gc
  gitCommit: e9b1d0551216e1e8ace5ee4ca50161df34325ec2
  gitTreeState: clean
  gitVersion: v1.14.7-eks-e9b1d0
  goVersion: go1.12.9
  major: "1"
  minor: 14+
  platform: linux/amd64
```

**Other debugging information (if applicable)**:
- workflow result:
```
$ argo get <workflowname>
```
- executor logs:
```
$ kubectl logs <failedpodname> -c init
$ kubectl logs <failedpodname> -c wait
```
- workflow-controller logs:
```
$ kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name)
```

**Comment by jimbeck** [comment]
After further inspection. It looks like the code associated with duration has not been released yet. Any word on when the next release will be cut?

**Comment by cloud-on-prem** [comment]
Hi @jimbeck 

Great investigative work! You are right on the money.
`duration` is not part of the [`SuspendTemplate struct`](https://github.com/argoproj/argo/blob/release-2.4/pkg/apis/workflow/v1alpha1/workflow_types.go#L1181) in the version you are running - `2.4.2`.

And the `master` does have it today which can be confusing to some new users.
I'll let the maintainers comment on the release date - but looks like it should be part of the next minor release.

**Comment by simster7** [comment]
Correct -- this feature is aimed for next release, which should be early next week. Happy to see that folks are already looking to use this feature!

**Comment by jimbeck** [comment]
Awesome. Thanks so much for the quick responses.
I'm going to close this ticket.
