### ISSUE TITLE
Question: how to restart workflow/step in the case of preemption

### ISSUE THREAD

**Issue by hnykda** [argoproj/argo#1796]
**Is this a BUG REPORT or FEATURE REQUEST?**: Question

**What happened**: When a k8s Job's pod is preempted, it gets restarted no matter `backoffLimit` value and restart doesn't count against that. In the case of Argo's Workflow, it does count against `retryPolicy`.

**What you expected to happen**: In the case of preemption, it wouldn't count against retryPolicy. 

**How to reproduce it (as minimally and precisely as possible)**: Spawn a job/flow, kill it, check `backoffLimit`/`retryPolicy`

**Anything else we need to know?**: The reason why we want this: it enables as not to retry a job which fails with a **deterministic** error after, say, 10 hours, but it's still being restarted in the case of (non-deterministic) preemption. Not so with workflow's retryPolicy. Is there some way to achieve this?

**Environment**:
- Argo version: 2.4.2
```
$ argo version
argo: v2.4.0-rc1
  BuildDate: 2019-08-08T22:59:15Z
  GitCommit: 6131721f43545196399d7ffe3a72c1b9dc04df87
  GitTreeState: clean
  GitTag: v2.4.0-rc1
  GoVersion: go1.11.5
  Compiler: gc
  Platform: linux/amd64
```
- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: "2019-11-13T11:23:11Z"
  compiler: gc
  gitCommit: b3cbbae08ec52a7fc73d334838e18d17e8512749
  gitTreeState: clean
  gitVersion: v1.16.3
  goVersion: go1.12.12
  major: "1"
  minor: "16"
  platform: linux/amd64
serverVersion:
  buildDate: "2019-11-07T19:23:23Z"
  compiler: gc
  gitCommit: 81c87c699557fed991e292cd328b2129c2f242a2
  gitTreeState: clean
  gitVersion: v1.14.7-gke.23
  goVersion: go1.12.11b4
  major: "1"
  minor: 14+
  platform: linux/amd64
```

**Comment by alexec** [comment]
https://adrianhesketh.com/2017/03/18/getting-line-and-character-positions-from-gos-json-unmarshal-errors/
