### ISSUE TITLE
Restart failed DAG step

### ISSUE THREAD

**Issue by mckjhd** [argoproj/argo#1803]
Suppose we have a complex DAG, and one step fails.
Is there a way to manually retry the failed step only and let it to continue execution?

I tried to resubmit with memoize, but it fails with: `volume 'work' not found in workflow spec`,
and automatic retry fails because of messed arguments.

**Comment by simster7** [comment]
Sorry if I misunderstood your question, but have you tried `retryOn`?

https://github.com/argoproj/argo/blob/master/examples/retry-container-to-completion.yaml
https://github.com/argoproj/argo/blob/master/examples/retry-container.yaml

**Comment by mckjhd** [comment]
@simster7, yes, it's fails because on retry it messes with step arguments. My question is more about api/cli feature, e.g. you have a workflow, and one of dag step fails -- is it possible/would it make sense to manually restart the failing step? I'd expect the workflow to continue in that case, tbh.

**Comment by simster7** [comment]
We currently have an open issue/bug with step arguments (#1744). So the issue with your workflow might be unrelated to the `retryOn` behavior.

Could you include the version of argo that you're using and a sample workflow that demonstrates this behavior please?

**Comment by mckjhd** [comment]
@simster7
```
argo: v2.4.2
  BuildDate: 2019-10-21T18:39:52Z
  GitCommit: 675c66267f0c916de0f233d8101aa0646acb46d4
  GitTreeState: clean
  GitTag: v2.4.2
  GoVersion: go1.11.5
  Compiler: gc
  Platform: darwin/amd64
```
wrt the workflow, it's a dag with dependencies, e.g. steps `a`, `b`, `c` and `c` depends on `a` and `b`, so if `b` fails, the workflow fails too. The things is that `b` might succeed on retry, and retry doesn't work due to known issue #1744 (I hope it's resolved in the latest master, but still), so I've been thinking about a way to manually retry `b`,  e.g. `argo retry workflow step`, so the workflow could continue to `c`.

**Comment by lueenavarro** [comment]
i'm looking for this feature as well, it would be nice to have this because sometimes the step must not be retried automatically because of some other issues that must be fixed first.
