### ISSUE TITLE
Argo 'lint' tolerates redundant dependencies

### ISSUE THREAD

**Issue by thundergolfer** [argoproj/argo#1806]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

**What happened**:

Created a workflow DAG of this structure: 

```
+-----+                +-----+               +-----+
|     |                |     |               |     |
|  A  +--------------->+  B  +-------------->+  C  |
+--+--+                +-----+               +--+--+
   |                                            ^
   |                                            |
   |                                            |
   |                                            |
   +--------------------------------------------+


X ---> Y = "X is a dependency of Y"
```

where `C` unnecessarily declares a dependency on `A`, as it depends on `A` already via depending on `B`. 

**What you expected to happen**:

As I can't think of a reason why you would ever want to redundantly declare a dependency and I don't think that doing so will actually affect workflow execution, I think this should just be a lint violation. 

**How to reproduce it (as minimally and precisely as possible)**:

Create any workflow of equivalent structure to what's described by my above diagram and run it through `argo lint`. 

**Environment**:
- Argo version: `2.4.2`

----

👋  If you agree with me, I'm happy to put up a PR introducing a lint-check for this.

**Comment by simster7** [comment]
Maybe a (somewhat trivial) reason to allow redundant dependencies is because it makes `B` more modular?

For example, if a user redundantly declares that `A` depends on `C` from the get go and then decides to remove `B` from the workflow, it is less likely that they will run into a user issue after the removal.

No strong opinions here, just throwing ideas around.

**Comment by alexec** [comment]
This is over 6 months old. Please re-open if still an issue.
