### ISSUE TITLE
[Question] S3 Artifact: Handling Multiple Accounts & Multiple Buckets

### ISSUE THREAD

**Issue by naiduasn** [argoproj/argo#1816]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Question
**What happened**:
I want to manage below use cases via workflow controller config
1) All output artifacts will be available in one bucket
2) All logs will be available in one bucket
3) All temp artifacts like git will be in one bucket with expiration policy set to auto delete

How can i configure these at a global argo level?

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Argo version:
```
$ argo version
```
- Kubernetes version :
```
$ kubectl version -o yaml
```

**Other debugging information (if applicable)**:
- workflow result:
```
$ argo get <workflowname>
```
- executor logs:
```
$ kubectl logs <failedpodname> -c init
$ kubectl logs <failedpodname> -c wait
```
- workflow-controller logs:
```
$ kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name)
```

**Comment by naiduasn** [comment]
any way i can achieve this? @simster7 @sarabala1979

**Comment by sarabala1979** [comment]
if you want to achieve the above use-case on workflow-controller-configmap(centralized), currently there is no support for multi S3 buckets in config.  we can enhance to support multiple ArtifactRepositories config in `configmap` and it will be referred in workflow input and output.

**Comment by naiduasn** [comment]
@sarabala1979 Yes, Multiple Artifact repositories can allow me to create a workaround.

**Comment by alexec** [comment]
See #2157
