### ISSUE TITLE
Argo UI and Workflow container pods running as root users

### ISSUE THREAD

**Issue by idristarwala** [argoproj/argo#1824]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST :- Set the user in the argo container pods to be nonRoot.
**What happened**:
We are evaluating Argo tools for our use-case, our kubernetes clusters are built with pod-securities enabled. Which means no pod can run as root. The argo tool container images are by default running as root. As a result we are unable to directly use the image out of the box.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Argo version:
```
$ argo version
```
- Kubernetes version :
```
$ kubectl version -o yaml
```

**Other debugging information (if applicable)**:
- workflow result:
```
$ argo get <workflowname>
```
- executor logs:
```
$ kubectl logs <failedpodname> -c init
$ kubectl logs <failedpodname> -c wait
```
- workflow-controller logs:
```
$ kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name)
```

**Comment by idristarwala** [comment]
we would be happy to submit PRs enhancing the docker files to use a nonRoot user instead of the default root user.

**Comment by sarabala1979** [comment]
l will leave @jessesuen to comment on this enhancement.
