### ISSUE TITLE
Question on building and versioning

### ISSUE THREAD

**Issue by tonyyang-svail** [argoproj/argo#1826]
Hi Argo team,

Thanks for open sourcing this workflow engine. I am trying to integrate it into our system and find the following problem.

First, I am confused about the version names. It looks like Argo is on version 2.4.3, however, [the example](https://github.com/argoproj/argo/blob/master/docs/example-golang/main.go) is using `v1alpha1`. Are `v1` and `v2` compatible? What is the relationship between `v1` and `v2`?

Second, Argo is using Gopkg as its dependency management tool. Does that mean I need to install https://github.com/golang/dep to build Argo. Is there any related documents?

Third, is there any plan to migrate to `go.mod` which is the official dependency management tool supported by the Go team.

**Comment by simster7** [comment]
> First, I am confused about the version names. It looks like Argo is on version 2.4.3, however, the example is using v1alpha1. Are v1 and v2 compatible? What is the relationship between v1 and v2?

The version you see on the examples (v1) is the [API version](https://kubernetes.io/docs/concepts/overview/kubernetes-api/#api-groups) for the Custom Resource Definitions in Kubernetes, and the Argo version (v2) is the version of the Workflow controller. They refer to separate things and are compatible with each other.

> Second, Argo is using Gopkg as its dependency management tool. Does that mean I need to install https://github.com/golang/dep to build Argo. Is there any related documents?

Yes. Documentation is not great currently, unfortunately, but take a look at the Makefile. Everything you need to build is there.

> Third, is there any plan to migrate to go.mod which is the official dependency management tool supported by the Go team.

[Yes](https://github.com/argoproj/argo/pull/1815), but not in the short term.

**Comment by tonyyang-svail** [comment]
@simster7 Thanks for the explanation. The effort of migrating to `go.mod` is greatly appreciated. :)
