### ISSUE TITLE
current date in global variable

### ISSUE THREAD

**Issue by timnon** [argoproj/argo#1833]
for etl-processes, i often need the current date. In order not to have to grep the date in every step of the workflow (which might also lead to a non-synchronized date), i usually get the date in a tiny first workflow step and write it to `workflow.outputs.parameters.date`.

To avoid this, it would be handy to have the date when the workflow was started already as a default global variable.

**Comment by Ark-kun** [comment]
There is the `workflow.creationTimestamp` placeholder https://github.com/argoproj/argo/blob/master/docs/variables.md

**Comment by timnon** [comment]
thanks a lot, this is perfect, did a lot of googleing, but this one didnt pop up!
