### ISSUE TITLE
Allow navigate to jobs from metics page

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo#185]
Metrics page displays charts which represents jobs breakdown by status grouped by templates.

UI should provide easy way to find jobs in particular status for required template. User should be able to click on red section for required template and UI should redirect user to global search with appropriate filter set.

Example:

- User is seeing chart for template 'Argo CI'
- 30% of jobs failed, so chart should has 30% of chart rendered in red.
- User should be able to click on red section and UI should redirect user to jobs global search with following filters: Template name = Argo CI, Status = Failed

**Comment by wokeGit** [comment]
Working on it.

**Comment by wokeGit** [comment]
If we use only "template name" and "status" filter. Global search returns the same results no matter which repo we select.
![screen shot 2017-09-11 at 13 43 28](https://user-images.githubusercontent.com/13086525/30273150-05db6988-96f8-11e7-82ae-70c96519c1f0.png)
I added "repo" filter to allow display only the results that we are looking for.
