### ISSUE TITLE
Does Argo assume Docker the container runtime used by Kubernetes

### ISSUE THREAD

**Issue by wangkuiyi** [argoproj/argo#1888]
We are the SQLFlow.org team. We are trying to refactorize SQLFlow.org to convert a SQL program into a workflow. For that purpose, a team member https://github.com/Yancey1989 tried to deploy Argo on a customized implementation of Kubernetes, which doesn't use Docker as the default container runtime.

The trial failed with error messages indicating that Argo expected to mount `/var/run/docker.sock` to some step containers. However, this customized Kubernetes doesn't use Docker, so there is no `/var/run/docker.sock`.

After git-grep the source code, it seems that the following snippet is suspicious to me.  Could Argo authors please confirm? If so, may we have suggestions from Argo authors please? Thanks!

https://github.com/argoproj/argo/blob/54f44909a0e68bc24209e9e83999421b814e80c9/workflow/controller/workflowpod.go#L54-L82

**Comment by dcherman** [comment]
(Not a maintainer, just a drive by suggestion):

The default executor for Argo is the docker executor which is why it's trying to mount `docker.sock`.  There are multiple others executors available which should avoid the need to do that:

https://github.com/argoproj/argo/blob/master/docs/workflow-executors.md
https://github.com/argoproj/argo/blob/59a190697286bf19ee4a5c398c1af590a2419003/docs/workflow-controller-configmap.yaml#L78-L80

**Comment by alexec** [comment]
@dcherman is correct, you can change the container runtime. What runtime do you need to use? `containerd`?

**Comment by wangkuiyi** [comment]
Thanks, @dcherman for pointing me to the container runtimes available to Argo and how to choose one.

Hi @alexec, I was trying to deploy [SQLFlow](http://sqlflow.org/sqlflow) on an Alibaba internal customized Kubernetes cluster running Pouch https://github.com/alibaba/pouch when I noticed the problem. In other deployments to vanilla Kubernetes, including the one at DiDi https://en.wikipedia.org/wiki/DiDi, everything thing works fine.

Still a little bit of confusion in my mind - It looks to me that Kubernetes is customizable to work with multiple container runtimes, as explained in https://kubernetes.io/docs/setup/production-environment/container-runtimes/. Does that mean Argo should work with any container runtime that the Kubernetes cluster uses? Why would Argo users need to configure and choose the container runtime?

**Comment by alexec** [comment]
@jessesuen ?

**Comment by jessesuen** [comment]
> Does that mean Argo should work with any container runtime that the Kubernetes cluster uses? 

Argo started out with only the Docker runtime, and subsequently added kubelet, K8s, and finally PNS to address the security concerns with the mounting of docker.sock on the host. The kubelet, k8s, and PNS executor should work with any container runtime including containerd.

> Why would Argo users need to configure and choose the container runtime?

There are tradeoffs to using each runtime as explained in the docs. Often, the choice is made for you such as if you are *not* running docker runtime, or if you have an admission controller that blocks `docker.sock` from mounting. In your case, PNS is probably your best option.
