### ISSUE TITLE
Mark suspended nodes as suspended with a unique symbol in the CLI

### ISSUE THREAD

**Issue by simster7** [argoproj/argo#1896]
Currently, suspended nodes are marked with the `running` symbol even when they are suspended. The CLI ux should be changed to reflect that they are in fact suspended.

From this:
```
Name:                test-dgrc2
Namespace:           argo
ServiceAccount:      default
Status:              Running (Suspended)
Created:             Mon Dec 30 08:20:03 -0800 (6 seconds ago)
Started:             Mon Dec 30 08:20:03 -0800 (6 seconds ago)
Duration:            6 seconds

STEP                          PODNAME  DURATION  MESSAGE
 ● test-dgrc2 (sensorAction)
 └-● suspend (fail)
```
To maybe this:
```
Name:                test-dgrc2
Namespace:           argo
ServiceAccount:      default
Status:              Running (Suspended)
Created:             Mon Dec 30 08:20:03 -0800 (6 seconds ago)
Started:             Mon Dec 30 08:20:03 -0800 (6 seconds ago)
Duration:            6 seconds

STEP                          PODNAME  DURATION  MESSAGE
 ● test-dgrc2 (sensorAction)
 └- || suspend (fail)
```

**Comment by changhc** [comment]
Hello @simster7 , may I take this issue?

I'd like to know why you chose the symbol `||` as well. Is it the pause symbol?

I think maybe we can use the empty set symbol `∅` or circle with left half black `◐`.  Suspended nodes are still in the running state, so I think we can keep using circles for consistency.

**Comment by simster7** [comment]
Hi @changhc, feel free to take over this issue! I was in fact trying to make a "pause" symbol. I think the pause symbol would be better -- it universally understood. While the `◒` symbol could be seen as more consistent, its meaning is also not as ubiquitous as the pause symbol.

If for some reason the pause symbol doesn't work out, we can explore other options.
