### ISSUE TITLE
GetTaskAncestry loop through steps that are already visited and cause performance issue

### ISSUE THREAD

**Issue by StoneRelax** [argoproj/argo#1907]
Checklist:

 * [ ] I've included the version.
 * [ ] I've included reproduction steps.
 * [ ] I've included the workflow YAML.
 * [ ] I've included the logs.
 
**What happened**:
When testing complicated DAG workflow (10*10 matrix with Cartesian product like dependencies) the workflow controller stuck at GetTaskAncestry, as it try to process every node even through they are already visited and take extremely long time  

**What you expected to happen**:
The visited ancestry node should not be processed again during the same GetTaskAncestry cycle for better performance 

**How to reproduce it (as minimally and precisely as possible)**:
workflow spec to reproduce 
https://github.com/StoneRelax/ArgoBenchmark/blob/master/argo-10by10.yaml

**Anything else we need to know?**:

**Environment**:
- Argo version:
```
$ argo version
```
- Kubernetes version :
```
$ kubectl version -o yaml
```

**Other debugging information (if applicable)**:
- workflow result:
```
argo get <workflowname>
```
- executor logs:
```
kubectl logs <failedpodname> -c init
kubectl logs <failedpodname> -c wait
```
- workflow-controller logs:
```
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name)
```

**Logs**

```
argo get <workflowname>
kubectl logs <failedpodname> -c init
kubectl logs <failedpodname> -c wait
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name)
```

**Comment by alexec** [comment]
Thank you @StoneRelax. You seem to have a good handle on this issue - would you be interested in submitting a PR to fix it please?

**Comment by StoneRelax** [comment]
Sure https://github.com/argoproj/argo/pull/1908 opened for review
