### ISSUE TITLE
Support GCS natively

### ISSUE THREAD

**Issue by nikolay** [argoproj/argo#1911]
# Summary

In addition to Artifactory, native support for GCS would be great.

# Motivation

Enabling S3-compatible API to GCS is not specific to the bucket Argo would use, so, it has more side effects that it should.

# Proposal

Just like Artifactory is supported natively, Google Cloud Storage should be as well. Ideally, Azure Storage, too.

**Comment by alexec** [comment]
This would be a useful feature. Would you be Interested in submitting a PR?

**Comment by whynowy** [comment]
@nikolay - GCS is already supported as artifact storage, let me know if you have a different opinion.

https://github.com/argoproj/argo/blob/master/docs/configure-artifact-repository.md#configuring-gcs-google-cloud-storage

**Comment by nikolay** [comment]
@whynowy Did you read what I wrote?

**Comment by whynowy** [comment]
@nikolay - Thanks. @decarboxy will get it implemented in his PR https://github.com/argoproj/argo/pull/1067.

**Comment by nikolay** [comment]
Thank you, @whynowy!
