### ISSUE TITLE
Incomplete node offload feature - should it be removed from config?

### ISSUE THREAD

**Issue by mark9white** [argoproj/argo#1918]
Taking a look at the node status offload feature in the code, there seem to be a couple of potential issues:

- not supported by CLI commands (/API server, at least in https://github.com/argoproj/argo/pull/1882). For example retry and resume workflow functions fetch the workflow directly from K8s API and assume that wf.Status.Nodes are present. I believe this also breaks compressed workflows.

- if there are conflicts when persisting workflow updates, the reapplyUpdate function is completely unaware of the Nodes object

- in addition the persistence code doesn't do anything to avoid race conditions between the two stores (eg we 1. update K8s API, 2. someone else updates K8s API, 3. someone else updates DB, 4. we update DB)

I would suggest that availability of the feature should be removed from the config file for now?

**Comment by alexec** [comment]
@sarabala1979 @jessesuen

**Comment by sarabala1979** [comment]
not supported by CLI commands (/API server, at least in #1882). For example retry and resume workflow functions fetch the workflow directly from K8s API and assume that wf.Status.Nodes are present. I believe this also breaks compressed workflows.
**[Bala]:** Thanks for finding. It was missed.  we can add it v2.5

if there are conflicts when persisting workflow updates, the reapplyUpdate function is completely unaware of the Nodes object
**[Bala]:** It is a bug. We will fix it 

in addition the persistence code doesn't do anything to avoid race conditions between the two stores (eg we 1. update K8s API, 2. someone else updates K8s API, 3. someone else updates DB, 4. we update DB)
**[Bala]:**  I think code will handle 1 and 2 if any change happened in etcd, Workflow controller will receive change and update to the DB. 3 and 4 will be the case for all DB applications if anybody updated the back door. It will affect the data consistency.  This needs to be handled with DB permissions.

I would suggest that availability of the feature should be removed from the config file for now?
It is an optional feature. it will be disabled by default.  Do you think this feature needs to remove from config after we fix the missing one and bug?

**Comment by mark9white** [comment]
I agree that if the issues are fixed then the feature should be kept,
however I didn't describe the race condition clearly.

What I meant is that if two instances of the persistUpdates function in
operator.go are operating at the same time against a single workflow, then
you could end up with the database and the k8s API getting out of sync with
each other. Imagine the following steps:
1) in goroutine A, operator.go:368 performs an update to the workflow using
the K8s API
2) in goroutine B, operator.go:368 attempts to perform a different update
to the same workflow using the K8s API. It sees there is a conflct, and
performs reapplyUpdate, but this doesn't resolve conflicts within
wf.Status.Nodes.

Then either:
3a) in goroutine B, operator.go:389 saves the wf.Status.Nodes to the
database
4a) in goroutine A, operator.go:389 saves the wf.Status.Nodes to the
database

In which case you would end up with the K8s API containing the merged data
from goroutines A and B, but the database containing just the updated data
from goroutine A.

Or:
Then either:
3b) in goroutine A, operator.go:389 saves the wf.Status.Nodes to the
database
4b) in goroutine B, operator.go:389 saves the wf.Status.Nodes to the
database

In which case you would end up with the K8s API containing the merged data
from goroutines A and B, but the database containing just the updated data
from goroutine B.

There is also a race condition where one goroutine is loading the workflow
whilst another goroutine is saving the same workflow, and the goroutine
loading the workflow could ends up loading non-matching versions from the
database and the K8s API.

A potential resolution to this issue could be to do the following two items:
- update the reapplyUpdate function so it correctly handles merging
wf.Status.Nodes when offload nodes is enabled.
- and also add a column in the database containing the Kubernetes
'metadata.resourceVersion'. Make sure when loading from the database that
this is equivalent to the resourceVersion received from the k8s API, and
make sure when saving to the database that the value in the database is not
higher than the version being saved.

**Comment by mark9white** [comment]
@alexec FYI I tried running a large workflow with offload enabled and got consistency issues, I'm pretty sure related to this. Note that there were simultaneous updates happening in workflow-controller and from the apiserver.

Describing the issue with the current version of the code:

1) goroutine A loads the workflow + nodes
2) goroutine B (which may be in a different process) loads the same workflow + nodes

3) they both make changes which mutate the nodes

4) goroutine A persists its modified nodes to offload (operator.go:468), let's assume this results in version 'fnv:12', then persists the rest of the workflow metadata to etcd with offload pointing to 'fnv:12'
5) goroutine B persists its modified nodes to offload (operator.go:468), let's assume this results in version 'fnv:943', then attempts to persist the workflow to etcd with offload pointing to 'fnv:943'. This fails and it does a merge of the workflow metadata (but not the nodes) in reapplyUpdate, it then tries again and this succeeds.

At no point are the updates to the two sets of nodes merged and therefore the updates to the nodes made by goroutine A which are contained in 'fnv:12' are lost and replaced by the updates in goroutine B.

**Comment by alexec** [comment]
> This fails and it does a merge of the workflow metadata (but not the nodes) in reapplyUpdate, it then tries again and this succeeds.

So there's a bug in `reapplyUpdate`?

**Comment by mark9white** [comment]
I'd say it's the whole handling of offloaded nodes in the `persistUpdates()` function when `apierr.IsConflict(..)` returns true.

**Comment by alexec** [comment]
>  it needs to make sure that changes to the nodes in the offload storage are merged with the changes we're trying to save.

It needs to read it back. I get it.

Could I please ask you to raise a bug for this?

**Comment by mark9white** [comment]
I've created #2856
