### ISSUE TITLE
Cashboard enhancements

### ISSUE THREAD

**Issue by rahuldhide** [argoproj/argo#192]
As a user, I should be able understand the value (savings) of Argo.
- Cashboard should display the total savings with argo for the selected time period.

UI issues-
- Navigation bar is inconsistent
- Grapah display issues and label overlapping
- All second level pages (Spend by Service, Apps, Users) are incomplete
- Style updates

Working on a design proposal to address these issues.

**Comment by jessesuen** [comment]
Closing v1 issues.
