### ISSUE TITLE
Add timezone support to CronWorkflows

### ISSUE THREAD

**Issue by simster7** [argoproj/argo#1931]
Users have requested timezone support to CronWorkflows

> **Use Case**: Being able to schedule something periodically during, say business hours M-F using simple cron ranges when your business hours stradle UTC midnight.  The patterns would be much simpler if you could evaluate them in the context of a specific timezone
> That said, it's pretty straightforward schedule a workflow to run every period, but start with a step workflow whose sole job can checks if the time is in a local timezone window and whose result is a conditional for continuing the workflow.
> It's not as efficient as being able to evaluate cron expressions in the context of a timezone, and results in a lot of noop workflows, but it works, as a workaround.

_Originally posted by @evaneaston in https://github.com/argoproj/argo/pull/1758#issuecomment-573045485_

> Indeed, we can find plenty of workarounds, but it seems to be cumbersome and moreover, playing with infrastructure that can scale from 0 to X, it is sad to say "Ok let's run the workflow, wait for a node to span (GKE autoscale feature), the first step says that we should not go forward and abort the workflow, wait for the cluster to scale down" = pay extra bucks because CRON does not support timezones.
> By the way, I am nowhere near to know how "hard" it would be to implement on CronWorkflows, but I really thought this new feature would come bundled with timezones support and I would be able to drop all those K8S CronJobs

_Originally posted by @rdigiorgio in https://github.com/argoproj/argo/pull/1758#issuecomment-573055151_

**Comment by simster7** [comment]
Update: I've come up with a design to add timezone support and will implement it after the upcoming API Server release

**Comment by rdigiorgio** [comment]
Hey @simster7 , am I right thinking this is quite easy to implement ? Being more and more involved into K8S stuff, I am willing to get my hands dirty with some work using Golang, and why not this feature implementation. What do you think about it ?

If you agree, I would be glad to hear about the design you came up with.

**Comment by simster7** [comment]
Sure! New contributors are always welcome. The design is simple:

The library we use to dispatch `cron` events already has in-line timezone support by prepending a `CRON_TZ` env variable before the schedule, e.g. `"CRON_TZ=Asia/Tokyo 0 6 * * *"`. This technically means that timezone support is actually available now if users would just prepend their schedule string with `CRON_TZ`. However, since we want to abstract away the library in case the library changes, or we want to use our own mechanism, I suggest we add a `timezone` field to the `CronWorkflow.spec` that accepts strings. Then, at the `CronWorkflow` creation point we could simply prepend the `CRON_TZ` to the schedule if necessary.

Docs: https://godoc.org/github.com/robfig/cron#hdr-Time_zones

P.S. I suggest starting this after #1882 is merged in, since that also contains some changes to `cron` (unless you are comfortable dealing with merge conflicts)

**Comment by simster7** [comment]
@rdigiorgio Sorry, I had to take over this PR since I realized that more involved changes would be needed (such as adding timezone binaries to our images). If you're still interested in contributing feel free to checkout our [help wanted](https://github.com/argoproj/argo/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) and [good first issue](https://github.com/argoproj/argo/issues?q=is%3Aopen+is%3Aissue+label%3A"good+first+issue") tags! I'll be adding more items to these soon

**Comment by rdigiorgio** [comment]
Ok @simster7 , I started working on it, but I do not think it will help you much making a PR for you to see the changes as it really was simple
