### ISSUE TITLE
Proposal: Enhance settings for namespace mode installation

### ISSUE THREAD

**Issue by whynowy** [argoproj/argo#1938]
# Summary

- Deprecate `namespace` setting in configmap
- Add optional `--namespace-mode` in `workflow-controller` start args
- Add optional `--namespace` in `workflow-controller` start args to support specifying a namespace for `workflow-controller` to listen to

# Motivation

For most of the cases of namespace mode installation, it's redundant to set up the namespace in the configmap, unless people want to make `workflow-controller` to listen to a different namespace.

It also make it possible to run `workflow-controller` on the local to test namespace only mode without configmap dependency.

# Proposal

**Comment by simster7** [comment]
#1939 Merged
