### ISSUE TITLE
Failed to parse workflow: error unmarshaling JSON: while decoding JSON: json: unknown field "backoff"

### ISSUE THREAD

**Issue by rahuly1516** [argoproj/argo#1940]
Hi, 

I am trying a restart strategy wherein I am trying to rerun(retry) my workflow at an interval of 5 mins for couple of time.  When I submit my argo workflow I get error :
Failed to parse workflow: error unmarshaling JSON: while decoding JSON: json: unknown field "backoff"

On the slack couple of people have asked to check format as when code is copied to the editor they can see tab. So I re-create my YAML file without tab but still getting the same error. 

Find below my agro version, kubectl version and Yaml file:

argo version
argo: v2.4.2
  BuildDate: 2019-10-21T18:39:29Z
  GitCommit: 675c66267f0c916de0f233d8101aa0646acb46d4
  GitTreeState: clean
  GitTag: v2.4.2
  GoVersion: go1.11.5
  Compiler: gc
  Platform: linux/amd64

kubectl version -o yaml
clientVersion:
  buildDate: "2019-09-24T22:12:08Z"
  compiler: gc
  gitCommit: 1861c597586f84f1498a9f2151c78d8a6bf47814
  gitTreeState: clean
  gitVersion: v1.14.7-eks-1861c5
  goVersion: go1.12.9
  major: "1"
  minor: 14+
  platform: linux/amd64
serverVersion:
  buildDate: "2019-12-22T23:14:11Z"
  compiler: gc
  gitCommit: c0eccca51d7500bb03b2f163dd8d534ffeb2f7a2
  gitTreeState: clean
  gitVersion: v1.14.9-eks-c0eccc
  goVersion: go1.12.12
  major: "1"
  minor: 14+
  platform: linux/amd64

Yaml file:
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: exec-sp
spec:
  entrypoint: exec-sp
  templates:
  - name: exec-sp
    retryStrategy:
      limit: 10
      backoff:
        duration: 1
        factor: 2
        maxDuration: "1m"
    container:
      image: XXXXXXX.dkr.ecr.us-east-2.amazonaws.com/exec-sp
	  
I am using AWS EC2 instance for development. 

Thanks,
Rahul

**Comment by simster7** [comment]
Hi @rahuly1516, `backoff` has not been released yet, it is expected to be released this Wednesday the 15th with the `v2.5` pre-release. Keep an eye out!

**Comment by rahuly1516** [comment]
> Hi @rahuly1516, `backoff` has not been released yet, it is expected to be released this Wednesday the 15th with the `v2.5` pre-release. Keep an eye out!

Thanks @simster7 ... I was looking to contact you to get this information. Good to see your reply

**Comment by simster7** [comment]
Closing this, feel free to reopen if necessary
