### ISSUE TITLE
archiveLogs not saving stack-trace when pod fails

### ISSUE THREAD

**Issue by Arkanayan** [argoproj/argo#1941]
Checklist:

 * [ ] I've included the version.
 * [ ] I've included reproduction steps.
 * [ ] I've included the workflow YAML.
 * [ ] I've included the logs.
 
**What happened**:
When archieveLogs is set, argo saves the logs of the pod as "main-logs" in artifact store. But in cases where the pod is exiting with non-zero status. The logs doesn't contain the stack-trace.

**What you expected to happen**:
It should save whatever the pod logs to stdout.
`kubectl logs <pod_name> -c main` displays the whole log including the stack-trace.

**Anything else we need to know?**: For simple hello-world argo is not saving any logs.

**Environment**:
- Argo version: v2.4.3
- Kubernetes version : v1.15.6

**Comment by tcolgate** [comment]
This may be due to stderr not being saved, and may be fixed by #2136

**Comment by alexec** [comment]
Is this still an issue in v2.5.0? If so - please re-open.
