### ISSUE TITLE
Test the various different K8S providers

### ISSUE THREAD

**Issue by alexec** [argoproj/argo#1957]
Install and test bearer token with:

* Minikbue
* Docker Desktop
* GCP
* IKS

**Comment by sarabala1979** [comment]
Approach :
1. Create an environment  
2. Run `make start`
3. Run ` make test`
4. Run ` make test-e2e`

**Comment by sarabala1979** [comment]
Tested v0,v1,v2 tokens with below k8s
1. GCP
2. Minikube
3. K3S
4 Docker on Desktop
