### ISSUE TITLE
Add CLI command to run a CronWorkflow on demand

### ISSUE THREAD

**Issue by simster7** [argoproj/argo#1963]
E.g. `argo cron run cron-wf-1`. This will allow users to run CronWorkflows on demand and out of schedule.

Note: Since the `cron` CLI currently only manipulates `CronWorkflow` resources, we may not want to use it to submit a Workflow directly.

Options to implement this:

1. Use `argo cron run cron-wf-1`. Implement by `Get`ing the CronWorkflow resource, converting it to a Workflow object and calling `util.SubmitWorkflow(...)` directly from the CLI.
1. Use `argo cron run cron-wf-1`. Implement by setting a flag in the CronWorkflow resource intended to instruct the cron controller to run the CronWorkflow immediately, after which the flag is reset to its resting state.
1. Use `argo submit --from=CronWorkflow/cron-wf-1`. Implement by `Get`ing the CronWorkflow resource, converting it to a Workflow object and calling `util.SubmitWorkflow(...)`. Probably least desirable option because it would require adding the `CronWorkflowInterface` to the root command.

**Comment by alexec** [comment]
@simster7 I'm putting this in v2.6 so we can prioritize it alongside other issues.
