### ISSUE TITLE
Add Suspend and Resume for  Cronworkflow in UI

### ISSUE THREAD

**Issue by sarabala1979** [argoproj/argo#1975]
Provide the Suspend and Resume functionality in Cronworkflow UI

**Comment by simster7** [comment]
Is there an API endpoint for these already?

**Comment by alexec** [comment]
No endpoints as of today.

**Comment by alexec** [comment]
Can be done as UI only change.

**Comment by changhc** [comment]
Could you please provide more details on this? Can we suspend or resume a cronworkflow?

**Comment by sarabala1979** [comment]
you use Argo CLI to suspend and resume the Cronworkflow.
`argo cron suspend <cronwf>
argo cron resume <cronwf>
`

```
Usage:
  argo cron [flags]
  argo cron [command]

Available Commands:
  create      create a cron workflow
  delete      delete a cron workflow
  get         display details about a cron workflow
  lint        validate files or directories of cron workflow manifests
  list        list cron workflows
  resume      resume zero or more cron workflows
  suspend     suspend zero or more cron workflows

```

**Comment by simster7** [comment]
> Could you please provide more details on this? Can we suspend or resume a cronworkflow?

The goal with this issue is to add this functionality to the UI

**Comment by changhc** [comment]
I see. I missed out the explanation in the document. Thanks!
