### ISSUE TITLE
All proto requests should use name and not resourceNameName

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo#1982]
Checklist:

 * [ ] I've included the version.
 * [ ] I've included reproduction steps.
 * [ ] I've included the workflow YAML.
 * [ ] I've included the logs.
 
**What happened**:

See the following proto messge:

```proto
message GetCronWorkflowRequest {
    string cronWorkflowName = 1;
    string namespace = 2;
    k8s.io.apimachinery.pkg.apis.meta.v1.GetOptions getOptions = 3;
}
```

In the above example request, we have `cronWorkflowName` and `namespace`. It really should be `name` and `namespace`, since the resource type is implied by the message type, `GetCronWorkflowRequest`.

Another way to say this is: why was `cronWorkflowName` chosen to have `cronWorkflow` in the prefix, but not `cronWorkflowNamespace`?

**Comment by alexec** [comment]
This is across all proto files, so probably just copy-and-paste. Should be easy to change.
