### ISSUE TITLE
Make is broken

### ISSUE THREAD

**Issue by dtaniwaki** [argoproj/argo#2010]
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [ ] I've included the workflow YAML.
 * [ ] I've included the logs.
 
**What happened**:

I can't build a controller by make command. I can't execute make commands with other targets either.

```bash
$ make controller
Makefile:83: *** target pattern contains no `%'.  Stop.
```

I investigated the issue and the following code of `Makefile` is problematic.

```Makefile
...
$(GOPATH)/bin/staticfiles:
   # Install the "staticfiles" tool
   go get bou.ke/staticfiles
 
 cmd/server/static/files.go: ui/dist/app $(GOPATH)/bin/staticfiles
   # Pack UI into a Go file.
   staticfiles -o cmd/server/static/files.go ui/dist/app
...
```

Because my `GOPATH` is `/Users/dtaniwaki/pfidev:/Users/dtaniwaki/go`, it makes the Makefile invalid.

**What you expected to happen**:

It should build a controller.

**How to reproduce it (as minimally and precisely as possible)**:

Set multiple paths on `GOPATH`.

**Anything else we need to know?**:

**Environment**:
- Argo version:
```
$ argo version
argo: v2.3.0
  BuildDate: 2019-05-20T22:11:23Z
  GitCommit: 88fcc70dcf6e60697e6716edc7464a403c49b27e
  GitTreeState: clean
  GitTag: v2.3.0
  GoVersion: go1.11.5
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: "2019-10-15T23:41:55Z"
  compiler: gc
  gitCommit: c97fe5036ef3df2967d086711e6c0c405941e14b
  gitTreeState: clean
  gitVersion: v1.16.2
  goVersion: go1.12.10
  major: "1"
  minor: "16"
  platform: darwin/amd64
serverVersion:
  buildDate: "2019-12-22T23:14:11Z"
  compiler: gc
  gitCommit: c0eccca51d7500bb03b2f163dd8d534ffeb2f7a2
  gitTreeState: clean
  gitVersion: v1.14.9-eks-c0eccc
  goVersion: go1.12.12
  major: "1"
  minor: 14+
  platform: linux/amd64
```

**Other debugging information (if applicable)**:
- workflow result:
```
argo get <workflowname>
```
- executor logs:
```
kubectl logs <failedpodname> -c init
kubectl logs <failedpodname> -c wait
```
- workflow-controller logs:
```
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name)
```

**Logs**

```
argo get <workflowname>
kubectl logs <failedpodname> -c init
kubectl logs <failedpodname> -c wait
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name)
```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by alexec** [comment]
Any thoughts on how to fix this please?
