### ISSUE TITLE
Private github enterprise with git artifact

### ISSUE THREAD

**Issue by devlounge** [argoproj/argo#2011]
# Summary
How to prove a private CA cert to talk to self hosted GitHub enterprise?

# Motivation

I need to be able to clone repos hosted in a private github enterprise, but how to mount the CA cert to communicate with it when using the gut artifact feature?

**Comment by devlounge** [comment]
It looks to me that what is cloning the git repo is the argoexec init container.
I have no way to mount the volume containing the CA cert as the container is injected dynamically by argo.
What do you suggest.

**Comment by devlounge** [comment]
I solved the issue by injecting the ssl certs via PodPreset

**Comment by devlounge** [comment]
Any other solution?

**Comment by Mohjive** [comment]
@devlounge I'd love if you could share your workaround. I have a similar issue, and have a hard time matching pod presets against Argo pods.

**Comment by tszngai** [comment]
Any updates on this from Argo? What is the official way to fetch content from self-hosted github (github enterprise) to the workflow?

**Comment by tszngai** [comment]
Found a workaround:
Set `insecureIgnoreHostKey: true`
