### ISSUE TITLE
Our Makefile is dangerous

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo#2016]
**What happened**:

Our Makefile does some pretty intrusive things such as installing manifests, scaling up and down services, and deleting untracked files in the git repo, with the assumption that the current kubeconfig is pointing to a cluster which is safe for development purposes.

This is *not* always a safe assumption, **especially** when the development namespace we are manipulating is the `argo` namespace (where we install by default)

It's okay to have convenience make targets, so long as if it were accidentally run against a prod kubeconfig, it would fail with no affect.

Let's not default to the `argo` namespace, and/or allow a *different* namespace to be used.

**Comment by alexec** [comment]
Short-term - what about adding a check to make sure you cluster is localhost?
Mid-term - we could use a different namespace (e.g. `argo-dev`).

**Comment by alexec** [comment]
`KUBERNETES_NAMESPACE` now supported
