### ISSUE TITLE
Argo Workflow setup on windows

### ISSUE THREAD

**Issue by kabilan6** [argoproj/argo#2031]
can someone please share the setup steps to install Argo workflow on local windows machine ?

**Comment by simster7** [comment]
How are you running Kubernetes on your windows machine? Our Argo CLI binaries are currently unix-only, but you could still communicate with Argo using the new API server, or running the CLI in a docker container

**Comment by kabilan6** [comment]
installed kubernetes in local machine with steps mentioned here(using Minikube) - https://kubernetes.io/docs/setup/learning-environment/minikube/.

**Comment by alexec** [comment]
Please read `docs/running-locally.md`.
