### ISSUE TITLE
Is it possible to use a different nodeSelector at retryStrategy attempts failure?

### ISSUE THREAD

**Issue by fabio-rigato** [argoproj/argo#2039]
# Summary

First of all thanks a lot for this awesome project.

# Motivation

I'm wondering if is possible to use a different node after all failure retries defined in the retryStrategy field.
Basically I used to try N times with a preemptible node (defined in nodeSelector) and I would love to run the same steps in a not-preemptible node if all the N attempts will fail.

Thanks so much for your effort.

**Comment by simster7** [comment]
Currently not supported... as a workaround you could have two distinct steps -- one for each node selector -- and only have a conditional `when` on the second step to only run if the first step failed. You can look at the examples folder to see how to create a `when` and how to get the status of a previous step.

**Comment by fabio-rigato** [comment]
Thanks a lot for your fast reply, I'll try to manage this with this workaround for the moment. @simster7 do you think is possible to add this feature request in Argo roadmap? If yes when do you think will be released? =)

Have a nice day

Best
Fabio

**Comment by simster7** [comment]
Feel free to open a separate issue proposing an enhancement and the team will take a look! Closing this...
