### ISSUE TITLE
Running multiple parallel pods per step

### ISSUE THREAD

**Issue by dobrerazvan** [argoproj/argo#2043]
Our usecase requires to run multiple parallel containers per workflow step. We've searched in examples and in CRD and parallel operations are used for lists (withItems) or in dags where makes sense.

Is the feature available (did we miss it from the docs)? 

We got inspiration from https://github.com/argoproj/argo/blob/master/examples/README.md#steps and wanted to run multiple containers/pods per step by keeping the same container image (no need for sidecars).

Thanks

**Comment by simster7** [comment]
You mean run multiple pods/containers at once? If so the example that you posted should do the trick. `hello2a` and `hello2b` run at the same time and use the same container image `docker/whalesay`

**Comment by dobrerazvan** [comment]
Thanks for the reply. I was more interested about how I can run 10 hello2b at the same time.

**Comment by simster7** [comment]
Ah, if I'm understanding this correctly now, I think you would have to either expand it into 10 `hello2b` steps, or use `withItems` with dummy variables.

**Comment by oliverdain** [comment]
I'd like to second this.

Example use case: we have hundreds and hundreds of videos that all need to be re-encoded. Some are short and some are long so time to re-encode varies quite a bit. One nice way to handle this is to have a job that publishes all the videos to be converted to a PubSub topic (or Kafka queue or whatevever) and then launch `n` tasks that can cooperate, via the PubSub topic, to pull videos and re-encode them. This ensures fair distribution of the work and it ensures that each video is eventually re-encoded.

I can create an input parameter that is just a list of `n` arbitrary items that are ignored so I can use `withParams` to launch my `n` jobs but that feels pretty hacky. I'd love to see a `replicas` field in addition to `withItems` and `withParams`. k8's jobs support the `n` replicas in a job natively so it seems like it shouldn't be too hard to implement.

**Comment by dkwgit** [comment]
@oliverdain @dobrerazvan Looks like one can achieve this via withParam.  A prior step can generate a list of dynamic length, and this can serve as an input to the next step, which can process the list in parallel, with the list's length thus setting the "replica count".  It's a bit hacky for the use case, but looks like it would work. I am going to try it.
See [`withParam example from another step in the workflow` in https://github.com/argoproj/argo-workflows/blob/main/docs/walk-through/loops.md](https://github.com/argoproj/argo-workflows/blob/main/docs/walk-through/loops.md#withparam-example-from-another-step-in-the-workflow).

**Comment by oliverdain** [comment]
> Looks like one can achieve this via withParam.

Yup. From my original comment:

> I can create an input parameter that is just a list of `n` arbitrary items that are ignored so I can use `withParams` to launch my `n` jobs but that feels pretty hacky. I'd love to see a `replicas` field in addition to `withItems` and `withParams`

**Comment by Joibel** [comment]
You can use withSequence if all you are about is a number of things.

https://argo-workflows.readthedocs.io/en/release-3.5/walk-through/loops/

**Comment by dkwgit** [comment]
> You can use withSequence if all you are about is a number of things.
> 
> https://argo-workflows.readthedocs.io/en/release-3.5/walk-through/loops/

Thank you!  Will withSequence run things in parallel?

**Comment by oliverdain** [comment]
> You can use withSequence if all you are about is a number of things.
> 
> https://argo-workflows.readthedocs.io/en/release-3.5/walk-through/loops/

`withSequence` looks like what I want. Note that the link you sent is for version 3.5. In the latest stable docs (3.5.6) `withSequence` isn't documented: https://argo-workflows.readthedocs.io/en/stable/walk-through/loops/. Has it been removed or are the docs just missing it?

**Comment by dkwgit** [comment]
> Yes, by default it will.

Many thanks!
