### ISSUE TITLE
Normalize the way git URLs are stored

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo#207]
A user encountered an issue where the git repo was added to the cluster and missing the .git extension in the git URL (e.g. https://github.com/argoproj/argo instead of https://github.com/argoproj/argo.git). But the way that the repo was cloned locally to his workstation, included the .git extension. So there was a discrepancy between the URLs. This caused problems for the CLI, which tried to find the name of a template using the repo URL (including the .git extension), but was unable to find the repo using an exact match. 

This issue is to normalize the way git URLs are stored (or queried) such that we can always find the repo matching the local clone.

**Comment by sytianhe** [comment]
I also find this is annoying. For git integrations, we let users to type the url. The backend does some basic checking like protocol checking of "http" or "https", but it's error prone when parsing things like this.

**Comment by sytianhe** [comment]
The whole generic git integration is something I don't understand. User can still put a github url there but calls it generic. This creates bug like https://github.com/argoproj/argo/issues/224
