### ISSUE TITLE
Cost estimate for workflow

### ISSUE THREAD

**Issue by ddseapy** [argoproj/argo#2082]
# Summary

Does argo have any way to report cost of worfklows?  On this page (https://blog.argoproj.io/argo-workflow-demo-at-the-kubernetes-community-meeting-c428c3c93f9d), we noticed that there is a screenshot (https://miro.medium.com/max/1592/1*ZzGoOFnIDhkLZlEmEvG4Ng.png) with the cost listed.

@jessesuen Is this at all related?: https://github.com/Applatix/claudia

# Motivation

We are looking for a way to track costs for workflows being run by argo.  Specifically on AWS.

**Comment by alexec** [comment]
I think this is a dup of #1066?

**Comment by ddseapy** [comment]
Indeed, I missed that.  Guess feature doesn't exist yet.

Im guessing that screenshot was from an older version, where maybe cost calculation existed?  That other project looked like it might not be maintained anymore.

I'll close this and subscribe to the other issue
