### ISSUE TITLE
How many Pods will be created for a workflow ?

### ISSUE THREAD

**Issue by kabilan6** [argoproj/argo#2086]
# Summary

if i have workflow with 30 tasks (includes DAG) , how many pods will be created ? is it going to be 30?                     

Does Argo creates a pod executes a step and delete the pod? is that how it works ?

Am planning to create one docker container and use that for 30 tasks to execute different operations of our ETL process.

**Comment by TekTimmy** [comment]
Yes Argo will create 30 Pods, one pod for every task, that's why you can specify a different container image for every task. Depending on your DAG they'll be started parallel or sequentially.

**Comment by simster7** [comment]
@TekTimmy is correct. Closing this, feel free to reopen if necessary

**Comment by kabilan6** [comment]
based on the response, for etl processing use case, if i have more jobs running on same cluster in parallel then we need to reserve enough IP address as the IP address aren't shred by POD . is my understanding correct ? 

Another question -  i have two uses cases with complex workflows

1. I need to run a 10 workflows in parallel on daily basis. Each workflow will have roughly about 20 -30 task . all the 10 workflow will be same. is there any benefits in creating different containers for each task? because all it does is run some db interaction, executing heavy lifting queries and capture logs

2. i may need to run anywhere between 10 -100 workflow on daily basis. each workflow will have around 10 -15 task. this also have lot of file processing

any suggestion on what would be best approach for better resource usage .
