### ISSUE TITLE
on_pull_request policy triggered jobs should use template from incoming branch instead of destination

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo#21]
The following scenario happened where a developer made change to both the build scripts, and the argo build template which invoked the corresponding changes to the build script. Both changes need to execute in tandem.

Currently our policy trigger will correctly use the source code of the incoming commit during checkout, but it will not use the templates from the incoming commit. In the above scenario, the job immediately fails because of the mismatch.

This issue is to improve policy execution to use the templates from the incoming commit. This may not be possible to do if the repo is not attached to the cluster, but should be possible if it is. The policy trigger should understand to use the policy ID of the incoming repo/branch when submitting the job.

**Comment by sytianhe** [comment]
As discussed, this is a known issue and requires fix. 
The potential fix includes:
- Use template from incoming commit
- Send alert if template is not valid

#20 provides another improvement on this, which is to have on_pull_request successfully triggered, user has to add both the base and compare repo into the system.
