### ISSUE TITLE
Deep links to workflows, and reload, no longer work

### ISSUE THREAD

**Issue by tcolgate** [argoproj/argo#2103]
**What happened**:

**What you expected to happen**:
I can no longer directly link from another ui to the workflow URL. Also, if I am viewing a workflow, and ctrl-r reload, it doesn't work. Both workflows get a 404

**How to reproduce it (as minimally and precisely as possible)**:

visit /workflows
click on a workflow
hit ctlr-r

similarly, copy the URL for a specific workflow, and open in a new tab, this gives a 404

**Anything else we need to know?**:

**Environment**:
- Argo version: v2.5.0-rc5
- Kubernetes version : 1.15

**Comment by simster7** [comment]
I am so far unable to reproduce this. I tried both with webpack and with the server on both master and the release branch. Could you provide more details? Browser? How are you running the server? Screen cap?

**Comment by alexec** [comment]
I'll take a quick look.

**Comment by tcolgate** [comment]
My ui is behind a reverse proxy (technically two, an oauth2 proxy and a traefik instance), but I really don't think that is the issue. If you open the debugger and browse around, the ui never actually loads /workflows/[ID], it only loads /workflows and then calls out to /api/v1/workfloes/[ID]. When you hit reload on a workload view , the browser actually tries to visit that URL, and then I get the 404.

**Comment by tcolgate** [comment]
Browser is `Chrome Version 79.0.3945.88 (Official Build) (64-bit)`
I tried just port-forward'ing to the server pod and browsing localhost:2746, and I get exactly the same behaviour.

**Comment by tcolgate** [comment]
![image](https://user-images.githubusercontent.com/76019/73523290-76ae9e00-4402-11ea-8bd3-9006fbe1467f.png)

**Comment by tcolgate** [comment]
That shows the flow of requests that I see. The xhr for the /api/v1/.... work just fine, but the initial browsing two the workflows view never uses /workflows/argo/... .
I get the same error if I go to /workdlows, then right click on one of the listed workflows and copy link, then paste that into another tab.
It could be that you are viewing the by starting it directly from node, rather than serving out of the go process maybe?

**Comment by simster7** [comment]
Aha! I found the issue here (thanks to your screen cap). Seems like it is the same issue that came up in Argo CD: https://github.com/argoproj/argo-cd/issues/2114. I.e., WebPack doesn't like when it has to route URLs with periods in them. Luckily, this has a very simple fix: https://github.com/argoproj/argo-cd/pull/2162

Thanks for providing such good debugging information! Will submit a PR shortly.
