### ISSUE TITLE
Error while using rc6

### ISSUE THREAD

**Issue by amoldharamshi** [argoproj/argo#2107]
Warning: You tried to redirect to the same route you're currently on: "workflows"
(anonymous) @ main.9263c6e00044a0788ca2.js:12
r @ main.9263c6e00044a0788ca2.js:12
t.componentDidUpdate @ main.9263c6e00044a0788ca2.js:17
Im @ main.9263c6e00044a0788ca2.js:111
P_ @ main.9263c6e00044a0788ca2.js:111
e @ main.9263c6e00044a0788ca2.js:98
c @ main.9263c6e00044a0788ca2.js:98
y @ main.9263c6e00044a0788ca2.js:98
F_ @ main.9263c6e00044a0788ca2.js:111
(anonymous) @ main.9263c6e00044a0788ca2.js:111
t.unstable_runWithPriority @ main.9263c6e00044a0788ca2.js:111
Yy @ main.9263c6e00044a0788ca2.js:111
Dy @ main.9263c6e00044a0788ca2.js:111
Sy @ main.9263c6e00044a0788ca2.js:111
Ly @ main.9263c6e00044a0788ca2.js:111
wy @ main.9263c6e00044a0788ca2.js:111
K_ @ main.9263c6e00044a0788ca2.js:111
(anonymous) @ main.9263c6e00044a0788ca2.js:111
Fy @ main.9263c6e00044a0788ca2.js:111
Ny @ main.9263c6e00044a0788ca2.js:111
Ky.render @ main.9263c6e00044a0788ca2.js:111
(anonymous) @ main.9263c6e00044a0788ca2.js:111
Cy @ main.9263c6e00044a0788ca2.js:111
tb @ main.9263c6e00044a0788ca2.js:111
render @ main.9263c6e00044a0788ca2.js:111
(anonymous) @ main.9263c6e00044a0788ca2.js:82
(anonymous) @ main.9263c6e00044a0788ca2.js:82
n @ main.9263c6e00044a0788ca2.js:1
(anonymous) @ main.9263c6e00044a0788ca2.js:1
(anonymous) @ main.9263c6e00044a0788ca2.js:1

Warning: You tried to redirect to the same route you're currently on: "workflows"
(anonymous) @ main.9263c6e00044a0788ca2.js:12
r @ main.9263c6e00044a0788ca2.js:12
t.componentDidUpdate @ main.9263c6e00044a0788ca2.js:17
Im @ main.9263c6e00044a0788ca2.js:111
P_ @ main.9263c6e00044a0788ca2.js:111
e @ main.9263c6e00044a0788ca2.js:98
c @ main.9263c6e00044a0788ca2.js:98
y @ main.9263c6e00044a0788ca2.js:98
F_ @ main.9263c6e00044a0788ca2.js:111
(anonymous) @ main.9263c6e00044a0788ca2.js:111
t.unstable_runWithPriority @ main.9263c6e00044a0788ca2.js:111
Yy @ main.9263c6e00044a0788ca2.js:111
Dy @ main.9263c6e00044a0788ca2.js:111
Sy @ main.9263c6e00044a0788ca2.js:111
Ly @ main.9263c6e00044a0788ca2.js:111
wy @ main.9263c6e00044a0788ca2.js:111
K_ @ main.9263c6e00044a0788ca2.js:111
(anonymous) @ main.9263c6e00044a0788ca2.js:111
Fy @ main.9263c6e00044a0788ca2.js:111
Ny @ main.9263c6e00044a0788ca2.js:111
Ky.render @ main.9263c6e00044a0788ca2.js:111
(anonymous) @ main.9263c6e00044a0788ca2.js:111
Cy @ main.9263c6e00044a0788ca2.js:111
tb @ main.9263c6e00044a0788ca2.js:111
render @ main.9263c6e00044a0788ca2.js:111
(anonymous) @ main.9263c6e00044a0788ca2.js:82
(anonymous) @ main.9263c6e00044a0788ca2.js:82
n @ main.9263c6e00044a0788ca2.js:1
(anonymous) @ main.9263c6e00044a0788ca2.js:1
(anonymous) @ main.9263c6e00044a0788ca2.js:1

**Comment by sarabala1979** [comment]
He is using v2.5.0-rc6

**Comment by alexec** [comment]
I'll own this. Already have a fix.

**Comment by alexec** [comment]
Fixed by #2048
