### ISSUE TITLE
Navigation errors in new UI

### ISSUE THREAD

**Issue by fsiegmund** [argoproj/argo#2113]
**What happened**:

When using argo server with --basehref, navigation is broken in several places:

Bug in app.tsx:
```
export const history = createBrowserHistory({basename: base});
```
the correct statement should be as in old UI 
```
export const history = createBrowserHistory();
```
The baseulr is already included where history is updated. By adding the basename parameter, the location in the browser contains duplicated baseulrs.

There are also a few places in the UI source code with a missing _uiUrl()_ conversion, which causes navigation to fail:

assignments to _document.location.href_  [some are correct]
calls to _ctx.navigation.goto_   [goto('/ has to be replaced with goto(uiUrl(']

I also noticed that changing the phase filter does not refresh the UI, nor is it possible to clear the filter by deselecting all phases.

**How to reproduce it (as minimally and precisely as possible)**:

Run argo server and nginx together:

```
argo server --basehref /test/
cat <<EOF > nginx.conf
events {
    worker_connections  1024;
}

http {
    server {
      location /test/ {
        proxy_pass http://host.docker.internal:2746/;
      }
    }
}
EOF
docker run -p 8001:80 -v  $(pwd)/nginx.conf:/etc/nginx/nginx.conf:ro nginx
```

Open http://localhost:8001/test/

**Anything else we need to know?**:

**Environment**:
- Argo version: 2.5.0-rc6

**Other debugging information (if applicable)**:
- workflow result:
```
---
<!-- Issue Author: Don't delete this message to ecourage other users to support your issue! -->
**Message from the maintainers**:

If you are impacted by this bug please add a ?? reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by alexec** [comment]
Thank you for this @fsiegmund - would you be interested in contributing a fix?

**Comment by fsiegmund** [comment]
Sure. I will create a pull request.
________________________________

**Comment by alexec** [comment]
Thank you!

**Comment by alexec** [comment]
Welcome to the team :)
