### ISSUE TITLE
Archived workflow `workflow` column should be json

### ISSUE THREAD

**Issue by ddseapy** [argoproj/argo#2133]
# Summary

The `workflow` column in the `argo_archived_workflows` is of type `text` and should be of type `json`.

# Motivation

Making it `json` type would make it much easier to query in postgresql.

I ran this after installation, which works but would be nice if defaulted to json:
```sql
alter table argo_archived_workflows ALTER COLUMN workflow TYPE JSON USING workflow::json;
```

# Proposal

How do you think this should be implemented?

Set the type to `json`.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by alexec** [comment]
Nice idea, would you like to submit a PR please? Should be just a case of adding a line to `migrate.go`.

**Comment by alexec** [comment]
Probably should do https://dev.mysql.com/doc/refman/8.0/en/json.html too

**Comment by alexec** [comment]
This is easy!

References: 

* https://www.slideshare.net/billkarwin/how-to-use-json-in-mysql-wrong

**Comment by mark9white** [comment]
Great idea. What about doing the same for the argo_workflows_table? Also using jsonb rather than json in Postgres would save space.

**Comment by alexec** [comment]
@mark9white `argo_workflows_table` is an internal table and you should not read from this table as you can predict what data it will contain.

**Comment by ddseapy** [comment]
@mark9white For whatever reason we have been using plain json on 2.4, but jsonb likely would make more sense.
