### ISSUE TITLE
ui: Logs link does not fall back to archive

### ISSUE THREAD

**Issue by tcolgate** [argoproj/argo#2137]
**What happened**:
* start a workflow that archives logs
* when it completes, delete the pods
* go to the ui, click the node, and click "logs"
* we don't see the logs
* console.logs shows a 404
* network logs does not show any requests for artifacts
* main-log can be retrieved from the artifacts tab

**What you expected to happen**:
Logs should pull logs from stopped pods from the archive

**Anything else we need to know?**:

https://github.com/argoproj/argo/blob/master/ui/src/app/shared/services/workflows-service.ts#L76

may be to blame, the catch does not seem to fire and may need to be elsewhere.

**Environment**:
- Argo version: 2.5-rc7
- Kubernetes version : 1.15

**Comment by tcolgate** [comment]
I think this is because the ready state on the error event that gets fired is "connecting" (0)

**Comment by simster7** [comment]
@tcolgate Seems like you have a good handle on this, would you like to submit a PR? If not I can take it over

**Comment by tcolgate** [comment]
https://github.com/argoproj/argo/pull/2139 attempt to fix, but  needs someone that understand what is happening

**Comment by alexec** [comment]
Merged. Will come in rc8.
