### ISSUE TITLE
Unable to download artifacts from Argo UI

### ISSUE THREAD

**Issue by ddseapy** [argoproj/argo#2142]
Checklist:

 * [X ] I've included the version.
 * [X ] I've included reproduction steps.
 * [ ] I've included the workflow YAML.
 * [ ] I've included the logs.
 
**What happened**:
When trying to download artifacts through the UI, when setting `insecure: true` under the `s3:` configuration, was presented with `http: named cookie not present`

**EDIT - @haghabozorgi discovered this happens regardless of insecure true/false**

**What you expected to happen**:

Artifacts should be downloaded.

**How to reproduce it (as minimally and precisely as possible)**:
Set `insecure: true` and try to download an artifact.

**Anything else we need to know?**:

**Environment**:
- Argo version: 2.5.0-rc7
- Kubernetes version : 1.16.4

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by ddseapy** [comment]
Discussed more in https://github.com/argoproj/argo/issues/2129, however that ticket is tracking the missing CA certificates for `insecure: false`.  This seems to be unrelated.

**Comment by haghabozorgi** [comment]
this seems to happen whether you set insecure to true or false.

**Comment by ddseapy** [comment]
thanks @haghabozorgi! i'll update the description.  i don't currently have a good way to test with inscure: false.

**Comment by haghabozorgi** [comment]
@ddseapy  https://github.com/argoproj/argo/pull/2129 was closed based on https://github.com/argoproj/argo/pull/2147 being merged. Using install.yaml from master branch and adding the volume and volume mounts from tcolgate's comment (til https://github.com/argoproj/argo/pull/2143 is merged)  still leads to http named cookie not present. Not sure if that is expected, given your last comment in https://github.com/argoproj/argo/pull/2129?

**Comment by alexec** [comment]
Fixed by https://github.com/argoproj/argo/pull/2147

**Comment by alexec** [comment]
Please re-open if not :)
