### ISSUE TITLE
New Argo-Server UI user authentication and Authorization 

### ISSUE THREAD

**Issue by kabilan6** [argoproj/argo#2154]
how do we achieve the user authentication and authorization in the New improved UI. We are planning to develop a ETL orchestration process using the Argo workflow and argo events. We want only give few users with access to submit/suspend/resume/terminate a workflow. some user should only have read-only access to UI. some user should n't have access to UI. Any suggestions on how to achieve this ? 

Argo Version - v2.5.0-rc7

**Comment by sarabala1979** [comment]
new Argo server has three types of Authentication mode
**1. Server** 
    Argo server will run a server-side service account full RBAC. All user can do without token 
**2. Client**
    Argo Server will run with minimum or nil RBAC. All requests will be executed with the user/client token.
**3. Hybrid**
   Argo Server will run with RBAC which all user can access it. User can use their token to perform privileged operations (create/delete)

**Comment by simster7** [comment]
Perhaps we should add some documentation to the docs @sarabala1979?

**Comment by alexec** [comment]
Tada! https://github.com/argoproj/argo/blob/master/docs/argo-server.md

**Comment by kabilan6** [comment]
if we setup the argo-server with "Hybrid" then every operation from UI will use the Token entered by the user from the UI ? is the user token being persisted somewhere ? user should submit the token only once ?

**Comment by sarabala1979** [comment]
yes, UI will cache the last used token.

**Comment by kabilan6** [comment]
@sarabala1979 @alexec how to setup the argo-server with client mode ?

**Comment by wajdi-datalvo** [comment]
you need simply to do: kubectl -n argo exec argo-server-7d7dbb9db8-6mzsd -- argo auth token
And copy all the output which looks like:

`Bearer blablablablabla4EQViURBI-0lARFSeoZqsjKTzudazC83h54tNBwaAH6ESC0c8UKnn3dGLHIkTw4FNfBGQtQ4S1QMtlkAAfVAk4pD0VgmiKl6ef-bjm9iWUePv6Yk4AoA_EmW7c1wgeXhg1NRS_ik5xGmNeDqKcYILaIE_D2JCto_j4Oz79Y4mL-_03lLzcTAbVDSdk89FOA63I8_G2Yje_tjD3rWQh2tGJOHw9yPowRx5uA8FZtaEuFf2xR2iwblablabla`

**Comment by ig0rsky** [comment]
@wajdi-datalvo thanks, @alexec maybe this should be documented when using the default auth mode, to clarify that we need the auth token from the server pod? 

> you need simply to do: kubectl -n argo exec argo-server-7d7dbb9db8-6mzsd -- argo auth token
> And copy all the output which looks like:
> 
> `Bearer blablablablabla4EQViURBI-0lARFSeoZqsjKTzudazC83h54tNBwaAH6ESC0c8UKnn3dGLHIkTw4FNfBGQtQ4S1QMtlkAAfVAk4pD0VgmiKl6ef-bjm9iWUePv6Yk4AoA_EmW7c1wgeXhg1NRS_ik5xGmNeDqKcYILaIE_D2JCto_j4Oz79Y4mL-_03lLzcTAbVDSdk89FOA63I8_G2Yje_tjD3rWQh2tGJOHw9yPowRx5uA8FZtaEuFf2xR2iwblablabla`

**Comment by spkane** [comment]
@alexec Did this get documented anywhere that is easily discoverable? `kubectl -n argo exec argo-server-${POD_ID} -- argo auth token`

This is not super obvious and has taken a bit of time to figure out.

It might actually be a good thing to the `argo` CLI, so that if people run `argo auth token` on their local machines, if it produces and error, maybe then it cane say something like `If you are looking for the auth token for your server, you probably need to run this command inside the argo-server pod via kubectl.`

**Comment by grid-dev** [comment]
It's already made it into a Stackoverflow question https://stackoverflow.com/questions/68334643/enable-anonymous-read-only-access-to-users-in-argo-workflows-similar-to-argocd

**Comment by maguowei** [comment]
with one command

`kubectl -n argo exec $(kubectl get pod -n argo -l 'app=argo-server' -o jsonpath='{.items[0].metadata.name}') -- argo auth token`
