### ISSUE TITLE
Can I schedule CronWorkflow for time of next year?

### ISSUE THREAD

**Issue by TrevorNodeJS** [argoproj/argo#2155]
# Summary

What do you want to know about this project?
The cron pattern does not contain year.

```bash

    /**
      * standard cron
        * * * * * *
        | | | | | | 
        | | | | | +-- Year              (range: 1900-3000)
        | | | | +---- Day of the Week   (range: 1-7, 1 standing for Monday)
        | | | +------ Month of the Year (range: 1-12)
        | | +-------- Day of the Month  (range: 1-31)
        | +---------- Hour              (range: 0-23)
        +------------ Minute            (range: 0-59) 
    */

    /**
      * k8s cronjob & argo cronworkflow
        * * * * * 
        | | | | | 
        | | | | | 
        | | | | +---- Day of the Week   (range: 1-7, 1 standing for Monday)
        | | | +------ Month of the Year (range: 1-12)
        | | +-------- Day of the Month  (range: 1-31)
        | +---------- Hour              (range: 0-23)
        +------------ Minute            (range: 0-59) 
    */
```

# Motivation

Why do you need to know this, any examples or use cases you could include?
How to schedule cron-workflow for next year?

**Comment by simster7** [comment]
The cron spec we use does not include a year field. Curious where you see that the "standard cron" has a year field? I have never seen that before. It is [not on the `crontab` man](http://man7.org/linux/man-pages/man5/crontab.5.html), and [stackoverflow](https://stackoverflow.com/questions/7724316/how-can-i-specify-time-in-cron-considering-year) agrees.

Perhaps someone extended the definition for a specific use case?

**Comment by TrevorNodeJS** [comment]
@simster7 
I may copy that **standard cron** from [nncron](http://www.nncron.ru/help/EN/working/cron-format.htm)
