### ISSUE TITLE
unclear documentation comments for persistence in workflow-controller-configmap.yaml

### ISSUE THREAD

**Issue by eug48** [argoproj/argo#2156]
Currently workflow-controller-configmap.yaml has

```
      # save the entire workflow into etcd and DB
      nodeStatusOffLoad: false
      # save completed workloads to the archived, even if disabled, you'll be able to
      # read from the archive
      archive: false
```

Perhaps more clearer would be "nodeStatusOffLoad if false saves the entire workflow into both etcd and the persistence DB, if true node status is only saved to the persistence DB to avoid the 1MB limit in etcd".

For archive the wording appears to have a typo and is unclear about what can be read from the archive.

Thanks very much for all the great work!

**Comment by alexec** [comment]
You statement is incorrect - or at least - should be.

Nodes should only be offloaded if `nodeStatusOffload: true`. Is this not the behavior you're seeing please?

**Comment by alexec** [comment]
See  #2170

**Comment by eug48** [comment]
@alexec the linked PR does improve the comment for `nodeStatusOffLoad`, but not for `archive`

**Comment by alexec** [comment]
> @alexec the linked PR does improve the comment for `nodeStatusOffLoad`, but not for `archive`

better now?

**Comment by eug48** [comment]
a bit better but what I still don't clearly understand is that if `archive` is false what gets stored in the persistence DB if `nodeStatusOffLoad` is false and if `nodeStatusOffLoad` true?

**Comment by alexec** [comment]
the two features are independent - the whole workflow is store in the archive, including any data that was offloaded (or not)

**Comment by eug48** [comment]
So if both `nodeStatusOffLoad: false` and `archive: false` then nothing is written to the persistence DB?
 
And if `nodeStatusOffLoad: true` and `archive: false` just the nodeStatus is temporarily written to the DB but then deleted?

**Comment by alexec** [comment]
correct - the node status is deleted when the workflow is deleted
