### ISSUE TITLE
argo server configmap fatal 2.5.0RC7+

### ISSUE THREAD

**Issue by seddonm1** [argoproj/argo#2158]
**What happened**:
`argo server` throws a FATAL error when running with Argo 2.5.0RC7+ which I believe is due to this change:
https://github.com/argoproj/argo/pull/2092/files#diff-1afb956681cbe494a0d07d8092bf8dd0R116

```
INFO[0000]                                               authMode=server baseHRef=/ managedNamespace= namespace=default
FATA[0000] configmaps "workflow-controller-configmap" not found
```

**What you expected to happen**:
Argo 2.5.0RC6 and lower threw an error but not fatal and so still allowed Argo UI to work:

```
INFO[0000]                                               authMode=server baseHRef= managedNamespace= namespace=default
ERRO[0000] Error marshalling config map: configmaps "workflow-controller-configmap" not found 
INFO[0000] Argo Server started successfully on address :2746 
```

This issue occurs with example [install.yaml](https://github.com/argoproj/argo/blob/release-2.5/manifests/install.yaml) manifest so the configmap has the default `workflow-controller-configmap` name.

**Comment by alexec** [comment]
I believe this was fixed in rc8 yesterday. Please re-open if that is not the case.

**Comment by seddonm1** [comment]
Problem persists with RC8

```
INFO[0000]                                               authMode=server baseHRef=/ managedNamespace= namespace=default
FATA[0000] configmaps "workflow-controller-configmap" not found 
```

**Comment by seddonm1** [comment]
@alexec Sorry I am unable to re-open but can raise a new issue if you want?
