### ISSUE TITLE
Artifacts download as `.gz` through UI when they are `.tgz`

### ISSUE THREAD

**Issue by ddseapy** [argoproj/argo#2163]
Checklist:

 * [X ] I've included the version.
 * [X ] I've included reproduction steps.
 * [ ] I've included the workflow YAML.
 * [ ] I've included the logs.
 
**What happened**:

Downloading output artifacts through the UI results in a `.gz` file extension.

**What you expected to happen**:

The output artifacts are of type `.tgz`, and therefore require renaming before you can open them.

**How to reproduce it (as minimally and precisely as possible)**:

Create a workflow with an output artifact and try to download it through the UI (server mode).

**Anything else we need to know?**:

**Environment**:
- Argo version: 2.5.0-rc8
- Kubernetes version : 1.16.4

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by alexec** [comment]
Can I ask if this is different in v2.4.3 (i.e. is it a regression)?

**Comment by ddseapy** [comment]
> Can I ask if this is different in v2.4.3 (i.e. is it a regression)?

Yes.  It works for us on 2.4.2 at least.  I haven't checked 2.4.3.

**Comment by alexec** [comment]
I'm pondering this. How are you impacted? Just usability?

**Comment by ddseapy** [comment]
> I'm pondering this. How are you impacted? Just usability?

Correct, developers run workflows with output artifacts and it is nice to be able to simply click in the browser and open them.  Nothing too critical.

**Comment by ddseapy** [comment]
Thanks @simster7!
