### ISSUE TITLE
Improved OTS helm chart support

### ISSUE THREAD

**Issue by omerlh** [argoproj/argo#2183]
# Summary

Today, support for OTS helm charts is not ideal - you have to define 3 files for each chart:
 - requirements.yaml
 - Chart.yaml
 - values.yaml (optional)

This makes the process a bit cumbersome to use.

# Motivation

We have a lot of OTS charts we're using and creating those files for each chart is a very tedious process. 

# Proposal

Something similar to Flux's helm operator [CRD](https://github.com/fluxcd/helm-operator/blob/master/docs/references/helmrelease-custom-resource.md) - the ability to define the repo and chart name as part of the CRD. This would eliminate the need for the 2 additional files (Chart.yaml and requirements.yaml).
---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by alexec** [comment]
Are you referrer to the Argo Helm charts please?

**Comment by omerlh** [comment]
I'm referring to Argo CD helm chart support - the ability to install OTS helm charts with Argo.

**Comment by alexec** [comment]
Are you raising this in the correct repository? If this meant for Argo CD?

**Comment by omerlh** [comment]
Should be on ArgoCd, sorry...
