### ISSUE TITLE
Add support for GitHub app authentication for repositories access

### ISSUE THREAD

**Issue by omerlh** [argoproj/argo#2200]
# Summary

Adding the ability to clone private repos from GitHub using GitHub app authentication.

# Motivation

When working with a lot of private repos, one challenge is scaling auth. Deploy is not feasible, as it is unique per repo. So the current alternative is either creating a user for argo and using personal access token (cost a seat in the organization) or creating an app and using the [private key](https://developer.github.com/apps/building-github-apps/authenticating-with-github-apps/#http-based-git-access-by-an-installation) of the app to authenticate to the repo.

# Proposal

How do you think this should be implemented?

Adding a new field for repo credentials:
  repositories: |
    # this has it's own credentials
    - url: <>
     installationId: <>
      appPrivateKey:
        name: <>
        key: <>

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by alexec** [comment]
Is this about Argo CD OR Argo Workflows?

**Comment by omerlh** [comment]
Sorry, wrong repository - it should be on argo cd.
