### ISSUE TITLE
Labels and annotations cannot be deleted in the UI

### ISSUE THREAD

**Issue by bitfactory-henno-schooljan** [argoproj/argo#2209]
**What happened**:
When deleting labels or annotations of an application in the UI, they stay put.

**What you expected to happen**:
Labels and annotations are deleted.

**How to reproduce it (as minimally and precisely as possible)**:

1. Go to app
2. Hit App Details
3. Remove a label or annotation by hitting the X
4. Save.

**Anything else we need to know?**:
Tested with Safari, Firefox and Chrome, using port forward access via 127.0.0.1:8080

**Environment**:
- Argo version:
```
$ argocd version
argocd: v1.4.2+48cced9
  BuildDate: 2020-01-24T01:07:43Z
  GitCommit: 48cced9d925b5bc94f6aa9fa4a8a19b2a59e128a
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.4.2+48cced9
  BuildDate: 2020-01-24T01:07:03Z
  GitCommit: 48cced9d925b5bc94f6aa9fa4a8a19b2a59e128a
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: Version: {Version:kustomize/v3.2.1 GitCommit:d89b448c745937f0cf1936162f26a5aac688f840 BuildDate:2019-09-27T00:10:52Z GoOs:linux GoArch:amd64}
  Helm Version: v2.15.2
  Kubectl Version: v1.14.0
```
- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: "2019-06-19T16:40:16Z"
  compiler: gc
  gitCommit: e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529
  gitTreeState: clean
  gitVersion: v1.15.0
  goVersion: go1.12.5
  major: "1"
  minor: "15"
  platform: darwin/amd64
serverVersion:
  buildDate: "2020-01-29T19:27:22Z"
  compiler: gc
  gitCommit: 2ccf2c797713077f4a3d0f87c4b4bae725362326
  gitTreeState: clean
  gitVersion: v1.15.8-gke.3
  goVersion: go1.12.12b4
  major: "1"
  minor: 15+
  platform: linux/amd64
```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by alexec** [comment]
@bitfactory-henno-schooljan this is an Argo CD issue, but you have raised it in the Argo Workflows repository. I will close it as "invalid". @alexmt 

You can raise Argo CD issues here: https://github.com/argoproj/argo-cd/issues/new/choose
