### ISSUE TITLE
Support creating/reading/updating archived arbitrary workflow metadata

### ISSUE THREAD

**Issue by mac9416** [argoproj/argo#2211]
# Summary

It would be helpful if the CRD and Argo Server supported creating/reading/updating metadata. 

I'd like to see this metadata archived rather than solely stored with the workflow objects.

For our purposes, a simple string:string key/value pair store would do the trick.

# Motivation

There's metadata we'd like to associate with a workflow. That metadata should:
1. persist - i.e. not disappear when workflow objects are deleted
1. be mutable at runtime via the Argo Server

And ideally:
1. initialize-able via yaml - so default/initial values can be set for all workflows

Right now we're maintaining a parallel table. We could eliminate a lot of code and potential bugs by incorporating the feature into Argo.

# Proposal

I'm thinking metadata could be persisted in a `json` or `hbase` column, but I'm not sure of their relative merits.

**Comment by alexec** [comment]
Conventionally, as a workflow is a custom resource, meta-data is  the contents of the `/metadata` field in the resource. Same part are mutable and it always disappears when the resource is deleted, so it cannot be used for what you are asking.

I wonder if you could give some specific examples of the use cases please?

**Comment by mac9416** [comment]
After thinking about it some more, I think our main use case for mutable metadata (workflow progress) is in the works as a first-class feature. The existing immutable metadata should take care of our other needs.
