### ISSUE TITLE
Add default TTLStrategy

### ISSUE THREAD

**Issue by zhujl1991** [argoproj/argo#2217]
When there's no `TTLStrategy` in workflow, we'd like to add a default `TTLStrategy`, which can be configured in `ConfigMap`. I'm thinking about adding this right after we get the structured workflow https://github.com/argoproj/argo/blob/master/workflow/controller/controller.go#L349 in a function called something like `func (wfc *WorkflowController) addingWorkflowDefaultValueIfValueNotExist(wf *wfv1.Workflow)`, in which we can add more workflow-level default values (e.g, deaultActiveDeadlineSeconds) configured in ConfigMap in the future.

Any ideas?

**Comment by simster7** [comment]
#2044 is already open for this. Please see my comment https://github.com/argoproj/argo/pull/2044#pullrequestreview-352420169 regarding adding a generic way to do this. Perhaps talk with @NikeNano who is also interested in this and has already opened a PR

**Comment by NikeNano** [comment]
I believe this could be closed @simster7
