### ISSUE TITLE
Terminate does not seem to work when container fails to start

### ISSUE THREAD

**Issue by Ark-kun** [argoproj/argo#2223]
Terminate does not seem to work when container fails to start. For example this can happen when the image is missing or wrong and the pod is in the `ImagePullBackOff` state.

**Comment by sarabala1979** [comment]
Can you provide more details? what kind of error are you getting? Share the logs

**Comment by Ark-kun** [comment]
> Can you provide more details? what kind of error are you getting? Share the logs

Thanks. I'll try to get the details.
