### ISSUE TITLE
Slack invite link is no longer active [regression]

### ISSUE THREAD

**Issue by alexlatchford** [argoproj/argo#2224]
Checklist:

 * [] I've included the version.
 * [ ] I've included reproduction steps.
 * [ ] I've included the workflow YAML.
 * [ ] I've included the logs.
 
**What happened**:

Same problem as https://github.com/argoproj/argo/issues/1789 & https://github.com/argoproj/argo/issues/1706

Seeing the same "This invite link is no longer active" when clicking on: https://argoproj.github.io/community/join-slack

**What you expected to happen**:

I can join the community Slack.

**How to reproduce it (as minimally and precisely as possible)**:

Click on the link at the bottom of the `README.md`.

**Anything else we need to know?**:

**Environment**:
- Argo version:
```
$ argo version
```
- Kubernetes version :
```
$ kubectl version -o yaml
```

**Other debugging information (if applicable)**:
- workflow result:
```
argo get <workflowname>
```
- executor logs:
```
kubectl logs <failedpodname> -c init
kubectl logs <failedpodname> -c wait
```
- workflow-controller logs:
```
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name)
```

**Logs**

```
argo get <workflowname>
kubectl logs <failedpodname> -c init
kubectl logs <failedpodname> -c wait
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name)
```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by cdenneen** [comment]
@alexlatchford thanks for opening this. I was just about to do so since I couldn't get the invite to work myself.

**Comment by jessesuen** [comment]
Here is the working link until we fix the shortlink:

https://join.slack.com/t/argoproj/shared_invite/enQtODMxNTg3OTA3Nzk0LTg5NDQ3YjRhYzNkMGZkMTEzN2IyZDQ2ZDI3ZTc1NmYxYzIyOGVlNjFmMjA3MDI2YWZlNTdlNzNmMjBhM2VlMDU

**Comment by jessesuen** [comment]
Shortlink updated
