### ISSUE TITLE
Server-side recursion when watching workflows with Offload Nodes Enabled

### ISSUE THREAD

**Issue by simster7** [argoproj/argo#2230]
When watching workflows with offload nodes enabled, the server will start to return

```json
{
    "error": {
        "grpc_code": 2,
        "http_code": 500,
        "message": "upper: no more rows in this result set",
        "http_status": "Internal Server Error"
    }
}
```

after some time. This will cause the UI to keep retrying to watch infinitely. This error seems to be related to the DB. More details to follow.

**Comment by simster7** [comment]
This was perhaps because my local instance of minikube was out of space. Closing for now.

**Comment by alexec** [comment]
dup of #2233 now.
