### ISSUE TITLE
Support upgrade to image in different registry

### ISSUE THREAD

**Issue by zhan849** [argoproj/argo#225]
Currently we abort upgrading cross docker registry. The major blocker is that we need to revise the part that we create registry secrets for short running services such as AM and workflow. We need to revise it and support it.

Cases:
1. Upgrade from a registry without a secret to a registry with a secret
    - We need to make sure we create a registry secret in all Application namespaces
    - registry secret in axsys, kube-system and axuser namespaces are handled by platform-bootstrap.cfg
    - Existing workflows are fine as the jobs does not have a registry secret, even if WFE job failed and needs restart, WFE image will be pulled successfully

2. Upgrade from a registry with a secret to a registry without a secret
    - We need to remove registry secret in all Application namespace (We have too as we don't want unnecessary things to accumulate)
    - We need to delete all registry secret in axsys, kube-system and axuser namespaces (i.e. change `CreateOnce` policy to `CreateMany`, so they will be deleted during platform down. Need to be backward compatible to 1.0 and 1.1)
    - Existing workflows will be affected, as if WFE job failed and needs restart, the WFT job object does have a registry secret, but we already removed it.

**Comment by abhinavdas** [comment]
I don't see a need to support this. @pratulw Thoughts?
