### ISSUE TITLE
argo lint on multiple files should list all files with failures

### ISSUE THREAD

**Issue by samath117** [argoproj/argo#2266]
# Summary

`argo lint` can run on either a list of files or an entire directory to verify multiple workflows. However, it doesn't give a complete report of the passing and failing workflows, but simply outputs the first failure it finds. It would be more useful if it gave a complete listing of whether the linter passes on each workflow file provided.

# Motivation

I frequently develop sets of multiple related workflows want to check all of them. But while I'm writing them, they might not all be fixed up yet. I want to easily be able to tell which ones have errors without having to run `argo lint` on each file individually in separate lines.

# Proposal

When running on either a directory or multiple files, `argo lint` should just continue after failure to the next file, echoing its error messages as they come in. As a bonus, it could print something after each file which passes to show that it checked that file.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by NikeNano** [comment]
I would be happy to work on this. Could you assign me @simster7 ?

**Comment by NikeNano** [comment]
Based upon: https://github.com/argoproj/argo/pull/2552 I think this can be closed.
