### ISSUE TITLE
Emit events to event bus

### ISSUE THREAD

**Issue by alexec** [argoproj/argo#2274]
# Summary

We would like to be able to inform other systems when things happen (e.g. workflow completion).

# Motivation

Sending emails on Slack messages or Kafka.

# Proposal

We should emit Kubernetes events. These can then be consumed by the following:

* https://github.com/heptiolabs/eventrouter - ★405 - but does not seem active
* https://github.com/opsgenie/kubernetes-event-exporter ★107 new, active

## Why not Argo Events?

Argo Events...

>  is mostly useful for getting events in cluster and triggering workflows/serverless functions as the actions.
> ...
> You can set up Resource gateway that listens to k8s events and trigger a openfaas function or some lightweight workflow that can publish message to kafka.

I.e. you both need to install Argo Events, and write the plumbing - it is not "first-class" or "out-of-the-box".

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by alexec** [comment]
One option:

* https://github.com/heptiolabs/eventrouter - but does not seem active

**Comment by alexec** [comment]
OK. When should we emit an event?

* Workflow completion.

Any other time?

**Comment by AntoineDao** [comment]
Emitting an event when a step or task is completed would also be really useful. Our use case is to have argo workflow under the hood and update a separate table with workflow updates in a different format (where we scrub certain artifact paths or secret names and the like).

**Comment by Mohjive** [comment]
I have a similar use case as the above, and step/task start and completion would help.

**Comment by alexec** [comment]
it looks to me that we already emit events on workflow completion

**Comment by alexec** [comment]
Nodes are run as pods. Any reason that listening to pods would not be good enough?

```
0s          Normal    WorkflowRunning     workflow/success-event-7nmj2                Workflow Running
<unknown>   Normal    Scheduled           pod/success-event-7nmj2                     Successfully assigned argo/success-event-7nmj2 to k3d-k3s-default-server
0s          Normal    Pulled              pod/success-event-7nmj2                     Container image "argoproj/argoexec:latest" already present on machine
0s          Normal    Created             pod/success-event-7nmj2                     Created container wait
0s          Normal    Started             pod/success-event-7nmj2                     Started container wait
0s          Normal    Pulled              pod/success-event-7nmj2                     Container image "cowsay:v1" already present on machine
0s          Normal    Created             pod/success-event-7nmj2                     Created container main
0s          Normal    Started             pod/success-event-7nmj2                     Started container main
0s          Normal    WorkflowSucceeded   workflow/success-event-7nmj2                Workflow completed
```

**Comment by alexec** [comment]
@AntoineDao @Mohjive thoughts on just using normal pod events?

**Comment by AntoineDao** [comment]
I have considered using events from pods and was dissuaded from doing so mostly because of having to build a custom resolver between pods and the workflow step they correspond to.

It feels like this resolution service between pod events and workflows is something that would fit nicely within the Argo codebase.

**Comment by AntoineDao** [comment]
Awesome thanks for addressing this!
