### ISSUE TITLE
clusterName is not properly quoted in SQL migrations

### ISSUE THREAD

**Issue by danxmoran** [argoproj/argo#2278]
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [ ] I've included the workflow YAML.
 * [x] I've included the logs.
 
**What happened**:
Using v2.5.1 with persistence enabled and a `clusterName` set, the controller enters a crash loop. The logs always end with:
```
time="2020-02-20T21:29:16Z" level=info msg="applying database change" change="update argo_archived_workflows set clustername = core where clustername is null" changeSchemaVersion=18
Error: pq: column "core" does not exist
```

My guess is that it's because the cluster name isn't quoted in the SQL. The migration line is [here](https://github.com/argoproj/argo/blob/63858eaa919c430bf0683dc33d81c94d4237b45b/persist/sqldb/migrate.go#L160). There's another line [here](https://github.com/argoproj/argo/blob/63858eaa919c430bf0683dc33d81c94d4237b45b/persist/sqldb/migrate.go#L160) which looks like it'd hit the same problem.

**What you expected to happen**:
The controller starts successfully when a `clusterName` is set

**How to reproduce it (as minimally and precisely as possible)**:
Edit the postgres quick-start manifests to include a `clusterName` under the `persistence` config, and run it.

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by alexec** [comment]
Fascinating. How did this ever work? Who knows.
