### ISSUE TITLE
service accout namespace issue

### ISSUE THREAD

**Issue by veera2019** [argoproj/argo#2287]
Hi , I have installed my application on kubernetes and i tried to integrate some tools with application, Starting  it was creating my tool integration pod and with in minute pod was deleting automatically  and i have seen logs it was showing below error.
 **is forbidden: User "system:serviceaccount:default:argo" cannot get resource "pods/log" in API group "" in the namespace "default"**

Please give me some suggestions on this issue ASAP .

Thanks

**Comment by sarabala1979** [comment]
can you check your role and rolebinding for `argo` service account? whether it has the right permissions

**Comment by veera2019** [comment]
Can you give me guidance how to check argo service account and permissions

**Comment by sarabala1979** [comment]
can you check the `role` argo-role?

**Comment by veera2019** [comment]
This is the my role yaml file
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/exec
  - pods/logs
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  - workflows/finalizers
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete


I think everything fine here , please check once this yaml fiel

**Comment by salanki** [comment]
You need to update the Argo role and add pods/log. This should probably be classified as a bug, happens to me in namespace I stalls too.

**Comment by veera2019** [comment]
Can you tell me where i need to add pods/logs in argo role, i have shared above my argo role yaml file 

Thanks

**Comment by veera2019** [comment]
Thank you, issue was resolved after adding pods/log in argo role.
