### ISSUE TITLE
Argo Qs

### ISSUE THREAD

**Issue by emichaf** [argoproj/argo#2289]
Is it possible:
   
- to remove workflows (removing terminated pods, but still workflows visiblw in GUI.. any function to clear etcd or similar for workflows?)

- Re run failed workflow (CLI / GUI) 

- Stop workflow execution (CLI / GUI)

- Remove terminated pods (any clean up handling ?)

**Comment by sarabala1979** [comment]
to remove workflows (removing terminated pods, but still workflows visiblw in GUI.. any function to clear etcd or similar for workflows?)
1. PodGC strategy : it will delete workflow pods once it completed https://github.com/argoproj/argo/blob/master/examples/pod-gc-strategy.yaml

Re run failed workflow (CLI / GUI)
1. v2.5 UI has retry functionality for failed workflow
2. Argo CLI has retry functionality

Stop workflow execution (CLI / GUI)
v2.5 UI and CLI support workflow `terminate` for delete permanently and ` suspend` will start stop temporarily until `resume` 

Remove terminated pods (any clean up handling ?)
1. PodGC strategy : it will delete workflow pods once it completed

**Comment by alexec** [comment]
I think your questions are answered.  Please re-open if still an issue.
