### ISSUE TITLE
Workflow status API

### ISSUE THREAD

**Issue by obiwen** [argoproj/argo#2294]
# Summary

Within our workflow orchestration code we would like to be able to use a lightweight API to query the current state of a workflow, given the name of the workflow and the namespace it is running in. 

# Motivation

Currently we are using the “get workflow” API to get the complete workflow details and search for the status. The returned data in from this API can get quite large depending on the workflow, up to several MBs. Since our orchestration calls for statuses of workflows quite often this can put a strain on the network as well as compute in order to parse the full response. 

# Proposal

Add a getWorkflowStatus API to return just the status of the given workflow. 

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
@obiwen - With the new feature, what you need to do is when you call the APIs of `GetWorkflow` or `ListWorkflows`, you can add a new query parameter `fields` to achieve it. 

For example, for `GetWorkflow`, add `fields=spec,status.phase` to let the response only contain `spec` and `status.phase`, or add `fields=-status.nodes`, which means excluding `status.nodes` from the response.

Please note this feature is only available when you use `ARGO_SERVER`, not k8s api server.
