### ISSUE TITLE
Logs does not automatically fail over to artifact in v2.5.1

### ISSUE THREAD

**Issue by alexec** [argoproj/argo#2300]
I'm not sure if this is quite fixed. On v2.5.1, I'm getting:

```
 Waiting for data...
```

When the underlying pod does not exist anymore.

_Originally posted by @MrSaints in https://github.com/argoproj/argo/pull/2139#issuecomment-590456761_

**Comment by MrSaints** [comment]
Woah that was fast. Thanks!
