### ISSUE TITLE
Logging in JSON

### ISSUE THREAD

**Issue by hnykda** [argoproj/argo#2307]
# Summary
Hi. Argo's machinery logs in go plain logs, e.g. something like this:
![image](https://user-images.githubusercontent.com/2741256/75252483-116d8300-57dd-11ea-9940-6af3ca4a8536.png)

which pollutes stderr and doesn't allow much filtering. Is there a way how it could log in JSON or somehow control the logging? Additionally, if the logging was structured (that is in JSON), one can much easily search in it.

# Motivation
Cluster monitoring often have something like "if count(error_log) > 0, raise alert". E.g. GCP logging enables ingesting JSON and recognizing severity based on the `severity` field and also search via structured log records. The current design doesn't allow it.

**Comment by simster7** [comment]
We've had internal discussions about this too. Tracking this in #2308

**Comment by hnykda** [comment]
Great.

And I was looking for logs and `JSON` and didn't find the issue, sorry
