### ISSUE TITLE
argo ui does not store filter preferences

### ISSUE THREAD

**Issue by abhinavdas** [argoproj/argo#231]
Selected filters are lost when I click out of the page and then come back to the page (e.g. Applications page)

![screen shot 2017-09-19 at 2 37 03 pm](https://user-images.githubusercontent.com/12264511/30616747-244b16ce-9d48-11e7-9d03-bc1d86dba0ee.png)

**Comment by wokeGit** [comment]
@rahuldhide Please take a look.
Do we should save last selected filter in view preferences? Some time ago we dropped it (I can't find that task to mention it here) and decided to just select default values each time we navigate to particular page.

**Comment by rahuldhide** [comment]
Clearing the filters on page refresh (when the user is navigating to a different view) is not a good experience. UI should persist the filter selection until it's changed again by the user.
