### ISSUE TITLE
Logs are only showing last 19 lines of long output on completed steps

### ISSUE THREAD

**Issue by sudermanjr** [argoproj/argo#2318]
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [ ] I've included the workflow YAML.
 * [x] I've included the logs.
 
**What happened**:
Logs only showed 19 lines in the argo server UI

**What you expected to happen**:
I expected to be able to scroll the log output

**How to reproduce it (as minimally and precisely as possible)**:
Run a workflow with more than 19 lines of log output in a step. Mine was a DAG step. Then view the logs in the server UI

**Anything else we need to know?**:
<img width="606" alt="Screen Shot 2020-02-26 at 5 17 06 PM" src="https://user-images.githubusercontent.com/7624765/75400293-0fc6bc80-58bc-11ea-9502-544465595389.png">

**Environment**:
- Argo version: 2.5.2
- Kubernetes version : 1.5.7

**Other debugging information (if applicable)**:
Server Logs:

```
argo-server-5bb46b9fb4-tsz26 server time="2020-02-27T00:20:22Z" level=info msg="finished streaming call with code OK" grpc.code=OK grpc.method=PodLogs grpc.service=workflow.WorkflowService grpc.start_time="2020-02-27T00:20:22Z" grpc.time_ms=16.302 span.kind=server system=grpc
```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by sudermanjr** [comment]
I should also note that live log-tailing works great. I just can't scroll back.

**Comment by alexec** [comment]
(1) To narrow this down, when the container is running a different process is used to when it is not. Is your container running or finished?

(2) If you open the network console, you should be able to find the request that gets the logs, it'll look like:

`/api/v1/workflows/argo/delightful-dragon/delightful-dragon/log?logOptions.container=main&logOptions.tailLines=20&logOptions.follow=true`

Can you open this up in a new tab, then change the `tailLines` to other values, such as "100, "-1", "0" or delete it entirely? This might provide a workaround for today, but also help diagnose this problem.

**Comment by sudermanjr** [comment]
The container is finished.

If I set tailLines to `100`, it works fine
if I remove that option entirely it shows me all the logs 
`-1` results in a 500 error 
`0` returns a blank page.

**Comment by simster7** [comment]
Fixed in https://github.com/argoproj/argo/pull/2330
