### ISSUE TITLE
Difference between "resubmit" and "retry" commands

### ISSUE THREAD

**Issue by danxmoran** [argoproj/argo#2320]
# Summary

I see "retry" and "resubmit" commands in the CLI / buttons in the server UI. It's not clear what the differences are between the two options, and I can't find any documentation about it. The only difference I can see in the CLI args is the `--memoized` flag on `resubmit`, which is marked as experimental.

# Motivation

My team uses volumes to pass large files between workflow steps. When a downstream step fails for a reason external to the workflow (i.e. some service is down), we want to be able to "poke" the workflow and have it pick up from the last successful step, without losing track of any volumes. It's not clear which of the two options support that behavior.

**Comment by simster7** [comment]
`resubmit`: A Workflow execution has been completed, and you would like to submit it again. Essentially an alias for running `argo submit` again.

`retry`: Rerun a failed Workflow. The same Workflow object is re-run and all of the steps that failed or errored are marked as pending and then executed as normal. No new Workflows are created.

From your motivation, you should use `retry`.

**Comment by bklaubos** [comment]
@simster7 A few questions:
My context is as follows: I run a workflow, went for lunch and comes back and found the workflow failed but the workflow has been deleted(with all its pods) but I still have the whole workflow plus its state metadata(NodePhases) and artifacts saved to a database which I can retrieved and rehydrate back to the argo workflow
1. Would "resubmit --memoized" automatically reuse the outputs from successful tasks when it  commences executing from the failed step/task?
2. In similar vein, would "retry" work ?

Please enlighten.
Thanks

**Comment by simster7** [comment]
Neither would work, both `resubmit` and `retry` depend on a live Workflow object on K8s. What you could do is create the failed Workflow object back to K8s. Since it is already marked as Failed it will not run. Then you can use `retry` or `resubmit` as needed

**Comment by bklaubos** [comment]
@simster7 Thanks. Your answer makes sense.

**Comment by bklaubos** [comment]
@simster7  One more question:
**argo resubmit workflowname --memoized** - will this reuse artifact outputs(from S3) from previous workflow run?
