### ISSUE TITLE
Trigger/Invoke Argo Workflow

### ISSUE THREAD

**Issue by kabilan6** [argoproj/argo#2322]
Are there any option to invoke Argo workflow, without going using Argo events ? like API call or any other option

**Comment by MrSaints** [comment]
Several options:-

- Trigger via CLI
- Trigger via Argo Events (e.g. using webhook)
- Argo 2.5.x, there appears to be a POST endpoint: `/api/v1/workflows/argo`

**Comment by alexec** [comment]
Answered.
