### ISSUE TITLE
Panic on workflow controller if DB connection timeout.

### ISSUE THREAD

**Issue by sarabala1979** [argoproj/argo#2348]
**What happened**:

Argo version 2.5.3

/usr/local/go/src/runtime/asm_amd64.s:1333
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1323065]

goroutine 167 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x108
panic(0x14f6b00, 0x25627b0)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/argoproj/argo/workflow/persist/sqldb.(*WorkflowDBContext).IsNodeStatusOffload(0x0, 0x0)
	/go/src/github.com/argoproj/argo/workflow/persist/sqldb/workflow_repository.go:61 +0x5
github.com/argoproj/argo/workflow/controller.(*WorkflowController).processNextItem(0xc0001a2400, 0xc000358500)
	/go/src/github.com/argoproj/argo/workflow/controller/controller.go:283 +0xae2
github.com/argoproj/argo/workflow/controller.(*WorkflowController).runWorker(0xc0001a2400)
	/go/src/github.com/argoproj/argo/workflow/controller/controller.go:230 +0x2b
github.com/argoproj/argo/workflow/controller.(*WorkflowController).runWorker-fm()
	/go/src/github.com/argoproj/argo/workflow/controller/controller.go:171 +0x2a
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000841a60)
	/go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x54
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000841a60, 0x3b9aca00, 0x0, 0x1791301, 0xc000094960)
	/go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xbe
k8s.io/apimachinery/pkg/util/wait.Until(0xc000841a60, 0x3b9aca00, 0xc000094960)
	/go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by github.com/argoproj/argo/workflow/controller.(*WorkflowController).Run
	/go/src/github.com/argoproj/argo/workflow/controller/controller.go:171 +0x75f

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Argo version:
```
$ argo version
```
- Kubernetes version :
```
$ kubectl version -o yaml
```

**Other debugging information (if applicable)**:
- workflow result:
```
argo get <workflowname>
```
- executor logs:
```
kubectl logs <failedpodname> -c init
kubectl logs <failedpodname> -c wait
```
- workflow-controller logs:
```
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name)
```

**Logs**

```
argo get <workflowname>
kubectl logs <failedpodname> -c init
kubectl logs <failedpodname> -c wait
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name)
```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by alexec** [comment]
Unsupported version.
