### ISSUE TITLE
Make stdout from non-script steps available as an output

### ISSUE THREAD

**Issue by mac9416** [argoproj/argo#2370]
# Summary

There have been a [couple](https://argoproj.slack.com/archives/C8J6SGN12/p1583329753253900?thread_ts=1583326195.250100&cid=C8J6SGN12) [requests](https://argoproj.slack.com/archives/C8J6SGN12/p1583423785269100) for making stdout available as an output for non-script steps.

Wrapping the container to pipe stdout to a file or refactoring to use a script step both feel hacky.

# Motivation

When I don't have control of or don't want to modify an image to access stdout as an output.

The hacks/workarounds are simple enough. But adding this feature would reduce some (apparently common) onboarding friction, since people seem to expect stdout to be available on `outputs.result`.

# Proposal

I think `outputs.result` should contain the stdout.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by alexec** [comment]
How do we deal with large amounts of output?

**Comment by alexec** [comment]
@simster7 to close if done

**Comment by simster7** [comment]
Closed by https://github.com/argoproj/argo/pull/2584
