### ISSUE TITLE
Use a monospace font family for yaml editors in UI

### ISSUE THREAD

**Issue by changhc** [argoproj/argo#2378]
# Summary

Use a monospace font family for yaml editors in UI.

# Motivation

Monospace font families are commonly used for code editors. They look nicer and can help reduce errors.

# Proposal

Just a minor change in the css file.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by simster7** [comment]
Great suggestion. Want to own this change?

**Comment by changhc** [comment]
Em I think I'll just take it unless anyone else is interested in this as well
