### ISSUE TITLE
CLI commands in the Tutorials are not displaying properly

### ISSUE THREAD

**Issue by cyee88** [argoproj/argo#238]
The Argo CLI commands in the Tutorials are not displaying properly after last "build-publish" of the Argo site. For example, in Tutorial 1, the markdown from *argo_tutorial_1_create_ci_workflow.md* looks like this: 

Run the CI workflow:

```$ argo job submit example-workflow-approval --argument "parameters.REQUIRED_APPROVALS=<your_email_address>" --repo https://github.com/argoproj/ci-workflow.git```

Get the job ID of the running job:

```$ argo job list```

Get the status of a job:

```$ argo job show <job_ID>```

However, if you look at the attached screenshot, the code snippet shows a fragment from Tutorial 2 (Docker-in-Docker example.)

<img width="1212" alt="screen shot 2017-09-20 at 8 49 32 am" src="https://user-images.githubusercontent.com/17263318/30654063-b3d71eca-9de1-11e7-842e-f70087232953.png">

All 7 of the tutorials are displaying the same issue.

**Comment by roofi07** [comment]
I think that Markdown has wrong syntax.
If you want make code block you need to add new line after starting marks and before ending marks. For example:

> \`\`\`
> asdasd
> \`\`\`

**Comment by cyee88** [comment]
Fixed the Markdown syntax. Had to add new lines both before the starting the marks and also after the ending marks.
