### ISSUE TITLE
Make Argo UI not indexed

### ISSUE THREAD

**Issue by mac9416** [argoproj/argo#2381]
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [ ] I've included the workflow YAML.
 * [ ] I've included the logs.
 
**What happened**:

I noticed Argo UI doesn't prevent search engine indexing.

**What you expected to happen**:

I expected Argo UI to prevent search engine indexing. If someone leaves an Argo UI public-facing accidentally, we probably want it to be not super discoverable.

**How to reproduce it (as minimally and precisely as possible)**:

Inspect the source code of the Argo UI. Search for `noindex`, and you won't find any results.

**Anything else we need to know?**:

**Environment**:
- Argo version: 2.6.0
---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by simster7** [comment]
Care to submit a PR? :)

**Comment by simster7** [comment]
Closed with #2383
