### ISSUE TITLE
Don't show retries in UI if first try succeeds

### ISSUE THREAD

**Issue by foobarbecue** [argoproj/argo#2384]
# Summary

Right now, if a template has a retryStrategy, the UI will always show a node mytemplate but also one called mytemplate(0) . This is unnecessary clutter. (0) and (1) should show up if (0) fails. I don't think any of the (0) nodes are necessary here:

![image](https://user-images.githubusercontent.com/854789/76132986-a9801f00-5fca-11ea-8160-19463668bbc6.png)

# Proposal

I don't know the architecture well enough yet to know how to make this happen.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by simster7** [comment]
Thanks for the bug report @foobarbecue!
