### ISSUE TITLE
Delete the CHANGELOG.md

### ISSUE THREAD

**Issue by alexec** [argoproj/argo#2397]
# Summary

Delete this file.

# Motivation

This file in 2 release out of date. We're clearly not updating it. It's costly and with little benefit.

# Proposal

Delete the file.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by alexec** [comment]
@jessesuen @sarabala1979 thoughts?

**Comment by simster7** [comment]
Why not add to the top something like: `This file is deprecated and no longer supported. For latest release information please see our [releases page](https://github.com/argoproj/argo/releases)`?
