### ISSUE TITLE
Workflow Archive RBAC doesn't agree with Workflow / Timeline RBAC

### ISSUE THREAD

**Issue by danxmoran** [argoproj/argo#2399]
Checklist:

 * [x] I've included the version.
 * [ ] I've included reproduction steps.
 * [ ] I've included the workflow YAML.
 * [x] I've included the logs.
 
**What happened**:
For context, I'm running the Argo Server in hosted mode, with the "client" auth mode enabled. The SA running the server has minimal RBAC (get/watch/list on configmaps and get on secrets).

Workflows are being written to the `argo_archived_workflows` table by my controller, but the Archived Workflows page in the UI claims there are none in the DB. Looking in the logs I found:
```
time="2020-03-09T13:32:52Z" level=debug msg=CanI allowed=false name=clinvar-ingest-pwnpk namespace=clinvar resource=workflows verb=get
```
Emphasis on `allowed=false`. This was confusing because the Timeline page makes the same call to decide what should be shown, and workflows have been appearing there without problems.

**What you expected to happen**:
All workflows in the archive table appear in the UI when using client-mode auth as a user with sufficient permissions.

**Anything else we need to know?**:
I found that the server is filtering archived workflows returned by the DB using a `can-i` call [here](https://github.com/argoproj/argo/blob/master/server/workflowarchive/archived_workflow_server.go#L73). When I run the command locally, it works:
```
$ kubectl -n clinvar auth can-i get workflow/clinvar-ingest-pwnpk
yes
```
Could the workflow archive API be dropping / ignoring the auth-mode config, always using the equivalent of server mode?

**Environment**:
- Argo version:
```
$ argo version
argo: v2.6.0
  BuildDate: 2020-02-28T23:32:45Z
  GitCommit: 5d3bdd56607eea962183a9e45009e3d08fafdf9b
  GitTreeState: clean
  GitTag: v2.6.0
  GoVersion: go1.13.4
  Compiler: gc
  Platform: darwin/amd64
```
I'm running 2.6.1 for the server / controller.
- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: "2020-01-18T23:33:14Z"
  compiler: gc
  gitCommit: 2e808b7cb054ee242b68e62455323aa783991f03
  gitTreeState: clean
  gitVersion: v1.15.9
  goVersion: go1.12.12
  major: "1"
  minor: "15"
  platform: darwin/amd64
serverVersion:
  buildDate: "2020-01-29T19:27:22Z"
  compiler: gc
  gitCommit: 2ccf2c797713077f4a3d0f87c4b4bae725362326
  gitTreeState: clean
  gitVersion: v1.15.8-gke.3
  goVersion: go1.12.12b4
  major: "1"
  minor: 15+
  platform: linux/amd64
```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by simster7** [comment]
@alexec Would you take this one?

**Comment by alexec** [comment]
@danxmoran you are quite correct - the RBAC should be exactly the same rules.

**Comment by alexec** [comment]
The code is different for getting a single archive and listing all of them. I'd like to understand which is the problem. Are you listing? Or are you trying to view a single one? Could you share the URL?

**Comment by danxmoran** [comment]
I'm seeing the difference on the list view (/archived-workflows)

**Comment by danxmoran** [comment]
What would the URL be for a workflow named "clinvar-ingest-4bv6t"? I can try going to it directly and see if that works.

**Comment by alexec** [comment]
you need the UID. I think it is either

* /archived-workflows/${uid}
* /archived-workflows/${namespace}/${uid}

**Comment by danxmoran** [comment]
Direct access to the workflow (/archived-workflows/${namespace}/${uid}) works.

**Comment by alexec** [comment]
So it is list that is broken. Can you tell what RBAC provider you are using.

**Comment by alexec** [comment]
I'd also like to find out what K8S is returning. We use a request called SelfSubjectAccessReview:

https://docs.openshift.com/container-platform/3.7/rest_api/apis-authorization.k8s.io/v1.SelfSubjectAccessReview.html

Do you think you could do this? This is advanced.

**Comment by danxmoran** [comment]
I'm running on GKE, so the RBAC comes from whatever mechanism it uses under-the-hood (not sure of the details myself).

Is `kubectl auth can-i` the CLI way to run the SelfSubjectAccessReview? If so:
```
$ kubectl -n clinvar auth can-i get workflow/clinvar-ingest-pwnpk
yes
$ kubectl -n clinvar auth can-i get workflows
yes
$ kubectl -n clinvar auth can-i get workflow --all-namespaces
yes
```

Also, if it helps, here's the role assigned to the SA running the Argo server:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-role
rules:
- apiGroups:
  - policy
  resourceNames:
  - argo-pod-running-policy
  resources:
  - podsecuritypolicies
  verbs:
  - use
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
```
So I'd expect any `can-i` calls about workflows that run as this SA to fail.

**Comment by danxmoran** [comment]
The main difference I see between list and get's auth calls are that the list method creates a new authorizer [each time](https://github.com/argoproj/argo/blob/master/server/workflowarchive/archived_workflow_server.go#L60), while the get method seems to use some [global instance](https://github.com/argoproj/argo/blob/master/server/workflowarchive/archived_workflow_server.go#L103).

Is there an easy command I could run locally to build the `argocli` Docker image? I can push to my team's GCR and deploy into my environment for a first pass at testing.
