### ISSUE TITLE
Fix flakey tests in operator_template_scope_test.go

### ISSUE THREAD

**Issue by alexec** [argoproj/argo#2432]
These are marked with SkipNow

**Comment by alexec** [comment]
@dtaniwaki do you want to own this?

**Comment by dtaniwaki** [comment]
I have fixed something about the informer. Does it solve the issue?
https://github.com/argoproj/argo/commit/563b5b9bf6a30e2a81365b1a226b5423c6968508

**Comment by alexec** [comment]
These tests are still skipped.

**Comment by dtaniwaki** [comment]
It seems a fakeclient may have a race condition with its informer.
https://github.com/kubernetes/kubernetes/issues/87472
