### ISSUE TITLE
Argo Workflow Pod Logs seem to be truncated

### ISSUE THREAD

**Issue by jbmcfarlin31** [argoproj/argo#2440]
Hello,

Running Argo Workflows `v2.6.0`. When looking at steps within a workflow, you have the ability to view logs. Prior to this release, you used to see all log output however as of now it appears the log output is truncated to the last 20 lines.

If you look at the logs using the CLI however, it shows all log output with no truncation.

Is there a configuration setting for the workflow server or within the UI to be able to set the log line limit or disable it entirely? We would prefer to see all log output through the UI as it is convenient and useful.

Thank you!

**Comment by simster7** [comment]
Fixed in: https://github.com/argoproj/argo/pull/2330

Should be in the next release
