### ISSUE TITLE
Bad URL for project URL

### ISSUE THREAD

**Issue by whyvez** [argoproj/argo#2462]
The URL used for the project website is broken.

<img width="767" alt="Screen Shot 2020-03-17 at 7 55 14 AM" src="https://user-images.githubusercontent.com/1593907/76863132-b13e8f80-6824-11ea-9ccc-5e9f25f884de.png">

<img width="449" alt="Screen Shot 2020-03-17 at 7 54 00 AM" src="https://user-images.githubusercontent.com/1593907/76863027-8b18ef80-6824-11ea-9213-16db3e9bcac5.png">

**Comment by alexec** [comment]
Thank you. Fixed!
