### ISSUE TITLE
Slow linting performance

### ISSUE THREAD

**Issue by tomdurrant** [argoproj/argo#2474]
# Summary

I am attempting to use argo to submit large workflows.  The problem is that argo appears to have significant performance issues with large workflows. 

These first present in the submit.  `argo submit <workflow>` cannot process large workflows, sitting at 100% cpu indefinitely
[example.yaml.txt](https://github.com/argoproj/argo/files/4351962/example.yaml.txt)

. `argo lint <workflow> produces the same behavior, so it seems likely that it is the linting that is causing the issue. I can submit the workflow without the argo cli (i.e.  kubectl create -f <workflow>), and the workflow appears in the UI, but the status remains pending, and no task begins. Examining the container cpu in the pods on the cluster, the cpu of the workflow-controller is also at 100%, suggesting it is stuck with the same issue. 

Attached is an example, relatively simple workflow. The workflow is less than 3k lines, yet linting of this workflow on my local i7 machine takes over half an hour. 

` time argo lint example.yaml`

2283.80s user 
2.35s system 99% 
cpu 38:06.55 total

Since argo is specifically designed to handle large workflows, and there is recent features such as persistence to overcome the etcd limitations which these workflows are not coming anywhere near approaching, I may be missing something here... Any help would be appreciated. 

# Motivation

Would like to run large workflows in argo

**Comment by tomdurrant** [comment]
[example.yaml.txt](https://github.com/argoproj/argo/files/4351968/example.yaml.txt)

**Comment by tomdurrant** [comment]
Thanks @alexec. I have done some more digging, it looks like its actually and spending most of its time in GetTaskAncestry. 

```(pprof)  
(pprof) top10 -cum
Showing nodes accounting for 161.16s, 87.36% of 184.48s total
Dropped 202 nodes (cum <= 0.92s)
Showing top 10 nodes out of 30
      flat  flat%   sum%        cum   cum%
    22.57s 12.23% 12.23%    179.03s 97.05%  github.com/argoproj/argo/workflow/common.GetTaskAncestry.func1
    38.70s 20.98% 33.21%     91.03s 49.34%  runtime.mapaccess1
    27.89s 15.12% 48.33%     46.64s 25.28%  runtime.mapaccess2_faststr
     8.15s  4.42% 52.75%     30.33s 16.44%  runtime.strequal
    27.28s 14.79% 67.54%     27.28s 14.79%  aeshashbody
    24.25s 13.15% 80.68%     24.25s 13.15%  memeqbody
    12.32s  6.68% 87.36%     12.32s  6.68%  runtime.duffcopy
         0     0% 87.36%      6.56s  3.56%  github.com/argoproj/argo/workflow/validate.(*templateValidationCtx).validateTemplateHolder
         0     0% 87.36%      6.54s  3.55%  github.com/argoproj/argo/workflow/validate.(*templateValidationCtx).validateTemplate
         0     0% 87.36%      6.52s  3.53%  github.com/argoproj/argo/workflow/validate.ValidateWorkflow```

In which case, it looks likely symptomatic of #1907, and hopefully addressed by #1908. Let me know if I can be of any help confirming that.

**Comment by tomdurrant** [comment]
Looks much better!

```
(pprof) top10 -cum
Showing nodes accounting for 0, 0% of 9.70s total
Dropped 189 nodes (cum <= 0.05s)
Showing top 10 nodes out of 119
      flat  flat%   sum%        cum   cum%
         0     0%     0%      8.71s 89.79%  github.com/argoproj/argo/cmd/argo/commands.NewLintCommand.func1
         0     0%     0%      8.71s 89.79%  github.com/argoproj/argo/cmd/argo/commands.NewLintCommand.func1.1
         0     0%     0%      8.71s 89.79%  github.com/spf13/cobra.(*Command).ExecuteC
         0     0%     0%      8.71s 89.79%  github.com/spf13/cobra.(*Command).execute
         0     0%     0%      8.69s 89.59%  github.com/spf13/cobra.(*Command).Execute (inline)
         0     0%     0%      8.69s 89.59%  main.main
         0     0%     0%      8.69s 89.59%  runtime.main
         0     0%     0%      8.55s 88.14%  github.com/argoproj/argo/workflow/validate.(*templateValidationCtx).validateTemplateHolder
         0     0%     0%      8.54s 88.04%  github.com/argoproj/argo/pkg/apiclient.argoKubeWorkflowServiceClient.LintWorkflow
         0     0%     0%      8.54s 88.04%  github.com/argoproj/argo/server/workflow.(*workflowServer).LintWorkflow
```

**Comment by simster7** [comment]
Thanks for the detective work, @tomdurrant! Hopefully this issue is fixed
