### ISSUE TITLE
How to pass artifacts to other workflowtemple

### ISSUE THREAD

**Issue by JulianZhang** [argoproj/argo#2503]
I want to split my workflows to defferent  workflowtemples. 
Such as build, install, test, uninstall.

So I need pass artifacts from a workflowtemple to an other workflowtemple.

But I didn't find a example for this case.
Can someone provide a example ?

Thanks very much.

**Comment by hayato1121** [comment]
@JulianZhang 

Hi! 
`templateRef`, which is kind of CRD would help you.

https://github.com/argoproj/argo/pull/1312


In addition here is how to write with Argo after v2.5. The difference between before v2.7 and after will occur some errors.

https://github.com/argoproj/argo/blob/master/docs/workflow-templates.md

**Comment by JulianZhang** [comment]
@hayato1121 
Thanks you reply, I had already use workflowtemplate in main workflow with templateRef.

I point is  don't know how to pass artifacts to other workflowtemplate.

Let me explain with a details:

I had write two workflowtemplate such as :
1,  build-template: build install package, last step have an output artifactory name as package );
2,  install-template(first step need an input artifactory).

In daily-CD worklow,  I had one step build (ref form build-template) and the next step is install (ref form install-temple). 

But I don't konw how to pass the package from build to install.

Where I can find any example or document for this case.

**Comment by alexec** [comment]
It'd be great to see an example, but have you looked in the examples directory yet? artifact-passing.yaml maybe?

**Comment by JulianZhang** [comment]
Dear @alexec 
I had look in the examples directory. And I can pass artifact in build-template from step1 to step2.

But when I use same syntax to try to pass  artifact from build-template to install-template, it didn't work.

**Comment by JulianZhang** [comment]
I had try again with the artifact-passing.yaml, and I know how to change it to template now. 
So so I close this issue, Thanks.
