### ISSUE TITLE
Submit submittable WorkflowTemplate through the rest api

### ISSUE THREAD

**Issue by jpambrun** [argoproj/argo#2527]
# Summary

Workflow are re-submitable from the [rest api](https://github.com/argoproj/argo/blob/master/api/openapi-spec/swagger.json#L1043), I think it would be reasonable to be able to submit  submittable WorkflowTemplate with something like PUT /api/v1/workflow-templates/{namespace}/{name}/submit.

# Motivation

I want to be able to submit WorkflowTemplates from a web service running in the cluster with a simple PUT request. 

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by sarabala1979** [comment]
It is good enhancement. I would enhance the workflow API `CreateFromResource` API will have resourcekind and resource name rather enhancing in `workflow-template` , `cron-workflow` and `clusterworkflowtemplate` APIs
`CreateFromResource` API can  submit the workflow from `workflowtemplate`,`cronworkflow` and `ClustetWorkflowTemplate`

**Comment by shanleyHe** [comment]
I have same problem.I'm looking forward you can resolve this issue

**Comment by sarabala1979** [comment]
I am working on it

**Comment by shanleyHe** [comment]
> I am working on it

[thumb up]👍👍

**Comment by clemensvonschwerin** [comment]
Hey guys, I can no longer find "/api/v1/workflows/{namespace}/submit-from" in the swagger documentation. Has it been removed? I am using argo-workflow-server v2.12.9 and the endpoint returns 501 for me.

**Comment by sarabala1979** [comment]
It is renamed to `submit` #2778.
try `/api/v1/workflows/{namespace}/submit`

**Comment by clemensvonschwerin** [comment]
Ah, thank you, found it. If I may ask, what is the format for `submitOptions.parameters`? So lets imagine I have a parameter named "message" that I would like to set to the value "hello".

**Comment by sarabala1979** [comment]
> Ah, thank you, found it. If I may ask, what is the format for `submitOptions.parameters`? So lets imagine I have a parameter named "message" that I would like to set to the value "hello".

submitOptions.parameters="param1=val1, param2-val2"

**Comment by clemensvonschwerin** [comment]
Perfect, is works 👍 thanks a lot!
