### ISSUE TITLE
Add Kubernetes node name to workflow node detail in Web UI and CLI output

### ISSUE THREAD

**Issue by salanki** [argoproj/argo#2540]
# Summary

Add information about which Kubernetes node a workflow step is executing on to Web UI and CLI.

# Motivation

For people operating bare metal clusters knowing which instance a Workflow step is executing on is valuable for troubleshooting and monitoring.

# Proposal

How do you think this should be implemented?
**Proposed WebUI Placement**
<img width="557" alt="Screen Shot 2020-03-29 at 00 45 43" src="https://user-images.githubusercontent.com/192223/77840539-b968ca00-7156-11ea-8453-68d44eec0ea7.png">

**Possibly show on the workflow summary when workflow only has one step that is executed in a Pod**
<img width="1843" alt="Screen Shot 2020-03-29 at 00 44 23" src="https://user-images.githubusercontent.com/192223/77840541-c08fd800-7156-11ea-81e2-7e1d6d5f7a0b.png">

**Proposed CLI Placement**
As with `kubectl get pods` node name could be shown only in the `wide` output.
```
# argo get -o wide uncompress-7kd82
Name:                uncompress-7kd82
Namespace:           test
ServiceAccount:      default
Status:              Succeeded
Created:             Sat Mar 28 22:15:22 -0400 (2 hours ago)
Started:             Sat Mar 28 22:15:21 -0400 (2 hours ago)
Finished:            Sat Mar 28 22:15:29 -0400 (2 hours ago)
Duration:            8 seconds
Parameters:
  source_file:       uploads///2020-03-28_22_12_38_28x_untitled.zip


STEP                          PODNAME                      DURATION  ARTIFACTS  NODE                                   MESSAGE
 ✔ uncompress-7kd82 (unpack)
 └-·-○ rar (unrar)                                                                                                     when ''uploads///2.zip' =~ '\.rar$'' evaluated false
   └-✔ zip (unzip)            uncompress-7kd82-3309228194  7s                   gke-test-default-pool-b11f5e68-2hlf
```

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by simster7** [comment]
Interested in contributing submitting a PR for this?

**Comment by aistein** [comment]
@simster7 I'm interested in giving this a try!

**Comment by changhc** [comment]
@simster7 would you please close this issue as it's implemented?
