### ISSUE TITLE
New 'Argo-Server' dashboard should have the option to display workflow creation timestamps

### ISSUE THREAD

**Issue by encigem** [argoproj/argo#2564]
# Summary

Previously I was using Argo v2.4.2, including the 'argo-ui' dashboard that showed timestamps of workflows, which for my needs was very useful.
See screenshot:
![argo-ui-old](https://user-images.githubusercontent.com/38977030/78232663-7e56f580-74cc-11ea-9fda-419f6d101775.jpg)

However, since upgrading to v2.6.1 and with it the 'argo-ui' into the 'argo-server' dashboard, all workflows in the list give a less accurate "[x time] ago" value for workflow age.
See screenshot:
![argo-ui-new](https://user-images.githubusercontent.com/38977030/78232972-fa513d80-74cc-11ea-8057-7e03ef2d6233.png)

This, in my case, makes finding a particular workflow more difficult.
I would like to have the option of seeing workflow timestamps, as was the case in older versions of the dashboard.

# Motivation

Where workflows run periodically over a number of days and i want to see the logs of a workflow run at a specific time in the past, then timestamps would be of much greater value to me

# Proposal

I wouldn't mind if this was some option that could be set in the Argo helm charts values.yaml, but I think it would be pretty good to have a button/dropdown directly on the frontend to chose preferred 'created' time format.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by simster7** [comment]
Hey @encigem. You can hover over the "short" date and see the full date. Example:

https://cl.ly/ec2e6433e1da

Does this work for you?

**Comment by encigem** [comment]
Ahh, excellent! 
Yes, this is workable, in my case. Thanks for the help!
