### ISSUE TITLE
Link broken on doc page - Workflow Executors

### ISSUE THREAD

**Issue by huikang** [argoproj/argo#2567]
On this page (https://argoproj.github.io/docs/argo/workflow-executors.html), the link to  `the configmap` (https://argoproj.github.io/docs/argo/workflow-controller-configmap.yaml) seems broken.

**Comment by alexec** [comment]
Would you like to submit a PR to fix?

**Comment by simster7** [comment]
@alexec The link on the page in this repo is correct. It seems like the website hasn't been refreshed.

**Comment by alexec** [comment]
@alexmt can you help please?

**Comment by jgoldfar** [comment]
Seeing a possibly related issue on https://argoproj.github.io/docs/argo/getting-started.html; the link to  "Argo Workflows by Example", 
![image](https://user-images.githubusercontent.com/5564569/79764559-84820a00-82f3-11ea-9214-32f919073fc2.png)
is broken.
I would submit a PR, but the corresponding link in the docs here, https://github.com/argoproj/argo/blame/master/docs/getting-started.md#L73 seems to be correct (and it works on github)

**Comment by alexec** [comment]
@alexmt could you please look into this?

**Comment by alexec** [comment]
See #3186 and see #3203

**Comment by alexec** [comment]
Fixed.
