### ISSUE TITLE
Make log viewer compatible with output in color

### ISSUE THREAD

**Issue by sebastien-prudhomme** [argoproj/argo#2569]
# Summary

Container log viewer is not compatible with containers that use terminal escape code to display text in color.

# Proposal

Argo CD has this feature and is using the LogsViewer component from  argo-ui package.

**Comment by alexec** [comment]
Would you like to submit a PR?

**Comment by sebastien-prudhomme** [comment]
@alexec Unfortunately i have zero knowledge in Go and React...

**Comment by dtaniwaki** [comment]
I want the feature too. I’ll take care of it.
