### ISSUE TITLE
CLI/API doesn't properly support workflow compression or node offload

### ISSUE THREAD

**Issue by mark9white** [argoproj/argo#2592]
Checklist:

 * [X] I've included the version.
 * [ ] I've included reproduction steps.
 * [ ] I've included the workflow YAML.
 * [ ] I've included the logs.
 
**What happened**:

Argo CLI/API doesn't properly support workflow compression or node offload, for example:
- workflow retry in RetryWorkflow in workflow_server.go doesn't support either of these
- workflow resume supports decompression but not recompression or node offload

**What you expected to happen**:

All API (and therefore CLI) commands to support both

**Environment**:
- Argo version: 2.7

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by alexec** [comment]
By default, the CLI does not support node offload status or archiving. You must have `ARGO_SERVER` set to use these. However, it seems you're suggesting that the `retry` and `resume` commands do not support it?

**Comment by alexec** [comment]
@sarabala1979 looking at the code, I can see this is probably in `workflow/util/util.go`. Who's best to look at this do you think?

**Comment by simster7** [comment]
I'll take a look at this.
