### ISSUE TITLE
Add CII Badge (CNCF Requirement)

### ISSUE THREAD

**Issue by caniszczyk** [argoproj/argo#2614]
Please fill this out and add a badge to the README

https://bestpractices.coreinfrastructure.org/en

**Comment by alexec** [comment]
@edlee2121 we'll need you input on the security aspects.
![Screen Shot 2020-04-07 at 10 15 21 AM](https://user-images.githubusercontent.com/1142830/78699451-c7d28680-78b8-11ea-9a06-633d73160be5.png)
