### ISSUE TITLE
Allow user to resubmit jobs with historical versions

### ISSUE THREAD

**Issue by rahuldhide** [argoproj/argo#262]
@sytianhe @edlee2121 Do we need an option to select a different version while resubmitting a job or should we always default to the version that was used originally?

**Comment by edlee2121** [comment]
For resubmits, I think it is OK to always use the original version. If they want to choose a different version, they can always create a new commit (that may be the preferred way to do it).

**Comment by sytianhe** [comment]
Agreed with ed that resubmit should always use the same context as the original submitted job.
