### ISSUE TITLE
Add commit selection step in the job creation wizard

### ISSUE THREAD

**Issue by rahuldhide** [argoproj/argo#264]
When the user is creating a job using a template (from the Templates view), UI should allow user to select the source code (commit).

InVision prototype: https://invis.io/U2DFGVC4N#/255156717_a11

**Comment by wokeGit** [comment]
@rahuldhide What I have to do to achieve the state of branch selector? 
![screen shot 2017-10-13 at 14 36 49](https://user-images.githubusercontent.com/13086525/31546550-12369de8-b024-11e7-832a-18dad9c54849.png)

I understand that if I open Service Launch panel the default view is: 
![screen shot 2017-10-13 at 14 38 47](https://user-images.githubusercontent.com/13086525/31546650-7c6c3cea-b024-11e7-95f4-c0cb22539dfd.png)
then I can click "Browse" and select: repo, branch, commit, template and if I'll click 'X' icon I'll close template selector and I'll be back to default screen. So I don't know how to achieve branch selector state from first screenshot.
