### ISSUE TITLE
Can't list workflow with `workflows.argoproj.io/controller-instanceid` label using argo native client

### ISSUE THREAD

**Issue by sjc960115** [argoproj/argo#2650]
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [ ] I've included the workflow YAML.
 * [ ] I've included the logs.
 
**What happened**:
use `argo list -n argo-manager` to retrieve workflow in `argo-manager` namespace
**What you expected to happen**:
```
NAME                                                             STATUS      AGE   DURATION   PRIORITY
retry-with-steps-template-9b8a1a21-9fad-45ae-8465-cdbcc04a8d4e   Succeeded   14h   8m         0
hello-world-template-b6aa1e09-3d34-4791-b38f-4d194211db61        Succeeded   1d    1m         0
hello-world-template-ca2a5fe2-ef8e-4503-ad6a-2d8c07c79872        Succeeded   1d    8s         0
```
But show nothing
```
NAME                                                             STATUS      AGE   DURATION   PRIORITY
```
**How to reproduce it (as minimally and precisely as possible)**:
create workflow with `workflows.argoproj.io/controller-instanceid` label.
**Anything else we need to know?**:
I found the way to list workflow in code.
By https://github.com/argoproj/argo/blob/master/pkg/apiclient/argo-kube-client.go#L52 creating workflowServer without instanceID.
By https://github.com/argoproj/argo/blob/master/server/workflow/workflow_server.go#L123, https://github.com/argoproj/argo/blob/master/server/workflow/workflow_server.go#L357 to list workflow.
Because workflowServer without instanceID, it cann't get any workflow with `workflows.argoproj.io/controller-instanceid` label.
Anyway to list workflow with `workflows.argoproj.io/controller-instanceid` label using argo native client instead of `kubelet`.

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by sjc960115** [comment]
@alexec Is there a way to list wf with `workflows.argoproj.io/controller-instanceid` label using `argo`?

**Comment by alexec** [comment]
See #2780
