### ISSUE TITLE
How to use JSON format parameters？

### ISSUE THREAD

**Issue by chengchaoyin** [argoproj/argo#2651]
# Summary

I want to know how to use json format parameters for input parameters

argo version:2.5.3

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: test
  namespace: argo
spec:
  # invoke the whalesay template with
  # "hello world" as the argument
  # to the message parameter
  entrypoint: whalesay
  arguments:
    parameters:
    - name: message
      value: json param
  templates:
  - name: whalesay
    inputs:
      parameters:
      - name: message       # parameter declaration
    serviceAccountName: argo
    container:
      # run cowsay with that message input parameter as args
      image: docker/whalesay
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]
    metrics:
      prometheus:
        - gauge:
            value: '{{duration}}'
          help: Duration of the template in seconds
          labels:
            - key: message
              value: "{{inputs.parameters.message}}"
          name: whalesay

# Motivation
Business needs to pass JSON parameters

**Comment by sjc960115** [comment]
You can marshal json to string and pass it as parameters, then unmarshal parameters to json.
