### ISSUE TITLE
Why i can't terminate job with API ?

### ISSUE THREAD

**Issue by sunzhenyucn** [argoproj/argo#2658]
I tried terminate workflow job with API like this:

```go
// JobInfo.JobId is job name
func TerminateWorkflow(wfClient argoprojv1alpha1.WorkflowInterface, job *api.JobInfo) error {
	patchObj := map[string]interface{}{
		"spec": map[string]interface{}{
			"shutdown": ShutdownStrategyTerminate,
		},
	}

	patchJSON, err := json.Marshal(patchObj)
	if err != nil {
		return err
	}

	_ = wait.ExponentialBackoff(retry.DefaultRetry, func() (done bool, err error) {
		_, err = wfClient.Patch(job.JobId, types.MergePatchType, patchJSON)
		if err != nil {
			if !k8serrors.IsConflict(err) {
				return false, err
			}
			return false, nil
		}
		return true, nil
	})

	return err
}
```

The Argo version information is:
```bash
argo: v2.4.0-rc1
  BuildDate: 2019-08-08T22:59:15Z
  GitCommit: 6131721f43545196399d7ffe3a72c1b9dc04df87
  GitTreeState: clean
  GitTag: v2.4.0-rc1
  GoVersion: go1.11.5
  Compiler: gc
  Platform: linux/amd64
```

The API has no error respond, i tried query jobs with `argo -n <namespace> list`, the job terminated with API is still running, why?

**Comment by simster7** [comment]
> `argo: v2.4.0-rc1`

This method of stopping workflows (`using spec.Shutdown`) was introduced after v2.7.

For v2.4 you can set `activeDeadlineSeconds` to `0` to terminate a job.

**Comment by sunzhenyucn** [comment]
> > `argo: v2.4.0-rc1`
> 
> This method of stopping workflows (`using spec.Shutdown`) was introduced after v2.7.
> 
> For v2.4 you can set `activeDeadlineSeconds` to `0` to terminate a job.

Thanks for your help!!!
