### ISSUE TITLE
Massive scale

### ISSUE THREAD

**Issue by alexec** [argoproj/argo#2663]
# Summary

Test Argo Workflows at massive scale

# Motivation

Discover issues at scale.

# Proposal

See ticket with "scalability" on "performance" labels.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by salanki** [comment]
I am posting this here in lieu for creating a separate ticket:

```
 time curl http://10.135.205.252:8080/metrics
# HELP argo_workflows_count Number of Workflows currently accessible by the controller by status
# TYPE argo_workflows_count gauge
argo_workflows_count{status="Error"} 0
argo_workflows_count{status="Failed"} 5
argo_workflows_count{status="Pending"} 0
argo_workflows_count{status="Running"} 1
argo_workflows_count{status="Skipped"} 0
argo_workflows_count{status="Succeeded"} 12349
curl http://10.135.205.252:8080/metrics  0.01s user 0.01s system 0% cpu 7.173 total
```

workflow controller is running unbounded in a latest generation AMD Epyc CPU. A response time <10s is often expected for a Prometheus metric, which means that this will top out at a couple of thousand more workflows.

**Comment by alexec** [comment]
> workflow controller is running unbounded in a latest generation AMD Epyc CPU. A response time <10s is often expected for a Prometheus metric, which means that this will top out at a couple of thousand more workflows.

Thank you @salanki - this ticket is meant to be an umbrella ticket for scalability issues. I think I'd like to ask you to create a separate ticket for Prometheus problems?
