### ISSUE TITLE
Failed to list the ClusterWorkflowTemplate on Namespaced installation

### ISSUE THREAD

**Issue by sarabala1979** [argoproj/argo#2664]
E0409 04:46:32.888632       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20191225075139-73fd2ddc9180/tools/cache/reflector.go:98: Failed to list *v1alpha1.ClusterWorkflowTemplate: clusterworkflowtemplates.argoproj.io is forbidden: User "system:serviceaccount:ecosecdev:argo" cannot list resource "clusterworkflowtemplates" in API group "argoproj.io" at the cluster scope

**Comment by alexec** [comment]
does this stop start-up?

**Comment by jfb74** [comment]
@alexec I am trying to deploy the namespaced install.yaml and too am experiencing this problem. I am using argo v2.7.6 with the argoexec, workflow-controller, and argocli images all being hosted in our enterprise artifact repository.

**Comment by sarabala1979** [comment]
@jfb74 Can you try v2.8.0-rc3?

**Comment by jfb74** [comment]
@sarabala1979 Yeah, applying that as a namespaced install for v2.8.0-rc3 has stopped the errors and allows me to `argo submit` workflows as long as they are in the same namespace that I installed it in.

**Comment by chenbodeng719** [comment]
hi, still get the issue from workflow v3.6.6 on Namespaced installation？ Anyone has the problem?

**Comment by arkpoah** [comment]
Same here, I just upgraded 3.2.11 to 3.3.9 and I get this error with a namespaced installation.

**Comment by emirot** [comment]
Is there a workaround ?

**Comment by jakovidulic** [comment]
Same error for 3.5.0 version namespaced installation

**Comment by araji-collibra** [comment]
I am getting a similar error related on a namespaced deployment (running  3.5.5) but strangely enough only when I on EKS/Fargate:
`
W0401 16:23:22.877725       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.24.3/tools/cache/reflector.go:167: failed to list *unstructured.Unstructured: the server could not find the requested resource                                                                   │
│ E0401 16:23:22.877750       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.24.3/tools/cache/reflector.go:167: Failed to watch *unstructured.Unstructured: failed to list *unstructured.Unstructured: the server could not find the requested resource                       │
│ I0401 16:24:11.294644       1 reflector.go:255] Listing and watching *unstructured.Unstructured from pkg/mod/k8s.io/client-go@v0.24.3/tools/cache/reflector.go:167                                                                                                           │
│ I0401 16:24:11.294821       1 round_trippers.go:466] curl -v -XGET  -H "Accept: application/json" -H "User-Agent: workflow-controller/v0.0.0 (linux/amd64) kubernetes/$Format/argo-workflows/v3.5.5 argo-controller" -H "Authorization: Bearer <masked>" 'https://10.100.0.1/ │
│ time="2024-04-01T16:24:11.297Z" level=debug msg="List clusterworkflowtemplates 404"                                                                                                                                                                                          │
│ I0401 16:24:11.297135       1 round_trippers.go:553] GET [https://10.100.0.1:443/apis/argoproj.io/v1alpha1/clusterworkflowtemplates?limit=500](https://10.100.0.1/apis/argoproj.io/v1alpha1/clusterworkflowtemplates?limit=500) 404 Not Found in 2 milliseconds
`
The problem goes away as soon as I add the CRD.
