### ISSUE TITLE
Trigger workflows from webhook

### ISSUE THREAD

**Issue by alexec** [argoproj/argo#2667]
# Summary

Allow automated scripts to trigger workflows from a webhook.

# Motivation

Simplify trigger or workflows.

# Proposal

TBD

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by nHurD** [comment]
I'm curious how this would differ from Argo Events?

**Comment by sarabala1979** [comment]
This is mainly to support simple use-case like just user wants to trigger the workflow/workflows based on webhook invoke.  Argo Event is a sophisticated application to support many usecases with multiple event sources, condition-based trigger, and complex event trigger logics.

**Comment by salanki** [comment]
Triggering Workflows via the new REST API is already pretty simple, however it requires a Workflow body even when triggering a WorkflowTemplate.

Is the idea here to support triggering a WorfklowTemplate by simply including parameters in the query? Ie `/api/submit/workflowtemplate/my-template?param1=cow&param2=say`? I can see that being very useful.

**Comment by alexec** [comment]
The biggest difference for this would be the use of a token (like GITHUB_TOKEN) to escalate an anonymous user to one that is able to submit workflows as the system user. This makes it much easier and safer to use.

**Comment by salanki** [comment]
Yup, that makes a lot of sense.

**Comment by sarabala1979** [comment]
> Triggering Workflows via the new REST API is already pretty simple, however it requires a Workflow body even when triggering a WorkflowTemplate.
> 
> Is the idea here to support triggering a WorfklowTemplate by simply including parameters in the query? Ie `/api/submit/workflowtemplate/my-template?param1=cow&param2=say`? I can see that being very useful, I've built my own proxy for this for my own usage.
In V2.7, Argo workflow has a `Submittable workflowtemplate `. User can submit the workflowtemplate as workflow.   Webhook should have a generalized Authentication mechanism to authenticate the call.

**Comment by nHurD** [comment]
Wow, this sounds pretty awesome! Would the result of this return the generated name of the new workflow?

**Comment by alexec** [comment]
@whynowy has an example of how to do this, but the big challenge is that the payload of different systems varies. E.g. https://developer.github.com/webhooks/

Argo Events would be able to do this:

https://argoproj.github.io/argo-events/tutorials/03-trigger-sources/#git

**Comment by whynowy** [comment]
@alexec - The link your gave is an example about how to trigger a git action not a github notification, check following links for a right example.

https://github.com/argoproj/argo-events/blob/master/examples/event-sources/github.yaml
https://github.com/argoproj/argo-events/blob/master/examples/gateways/github.yaml
https://github.com/argoproj/argo-events/blob/master/examples/sensors/github.yaml

**Comment by alexec** [comment]
@whynowy do you want to add your Google do to /docs?

**Comment by alexec** [comment]
Please review the proposal:

https://github.com/alexec/argo/blob/cloudevents/docs/events.md

**Comment by alexec** [comment]
@nHurD, @deepk2u, @kmarquardsen, @juanchristensen, @kabilan6, @samath117, @shrimank, @maguowei, @oleg-borodai, @nikopen please can your review the proposal:

https://github.com/alexec/argo/blob/cloudevents/docs/events.md

**Comment by alexec** [comment]
Please remember to 👍 #3344 if you want to be able to resume suspended workflows.

**Comment by alexec** [comment]
@nHurD, @deepk2u, @kmarquardsen, @juanchristensen, @kabilan6, @samath117, @shrimank, @maguowei, @oleg-borodai, @nikopen request for comment:
https://docs.google.com/document/d/1f2z6W0pI86z28T_GI-jgchlJ1twFmV37qla-Lm3egYk/edit

**Comment by alexec** [comment]
Available for testing in [v2.10.0-rc1](https://github.com/argoproj/argo/releases/tag/v2.11.0-rc1).
