### ISSUE TITLE
Make it easier to write complete tests for the controller code

### ISSUE THREAD

**Issue by alexec** [argoproj/argo#2674]
# Summary

Make it easier to write tests.

# Motivation

Currently, if you want to write a sophisticated test for the operator, you must write an e2e test, e.g. `functional_test.go`. These are hard to write, and flakey. Lets shift-left the tests.

We could also capture test coverage if they could be run as standard unit tests.

# Proposal

It should be possible to write these as standard unit tests, so we can get test coverage, and they should be fast.

I envisage you'd specify the workflow YAML and then a series of Kubernetes fakes that execute in response to those API requests. E.g. creating a workflow pod should create a fake pod that then runs to completion (or not, depending on how we prime the test system)

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by simster7** [comment]
This should not be difficult. We just need to make use of mocks as we do elsewhere in the code base.

**Comment by alexec** [comment]
I don't feel this is a problem today.
