### ISSUE TITLE
Configuration using Kubernetes secrets

### ISSUE THREAD

**Issue by sytianhe** [argoproj/argo#268]
As discussed @rahuldhide, there should be a check box to indicate whether user wants the config as Kubernetes secrets.

For UI, there are following change (once pull request: https://github.com/argoproj/argo/pull/267 is merged)
1. Configurations POST and PUT apis are changed. Please check the swagger.
2. Indicating whether a configuration is a Kubernetes secrets from the UI
3. The checkbox only allows in the creation time but the modification time, which means if configured as Kubernetes secrets, user cannot change it back to normal configuration
 
Let me know if questions.

**Comment by rahuldhide** [comment]
Here is the UI prototype for this requirement.
When the user is adding a new Config, UI would allow user to save the Config as K8 Secret-  by using checkboxes. Currently we don't allow user to edit the saved configs.

![k8secret](https://user-images.githubusercontent.com/30275450/30937158-d5d05330-a38a-11e7-807c-de8893be720f.png)

**Comment by jessesuen** [comment]
@rahuldhide, @alexmt - I was incorrect about individual keys being secrets. Actually, the entire configuration is a secret, or not at all. We don't allow secrets at individual keys. In other words, the checkmark should be at the top pane, and not the individual keys.

**Comment by rahuldhide** [comment]
This would simplify the interaction!
1. Add two choices on the Config screen [+] - 
- Add New Config as Kubernetes Secret
- Add New Public Config

2. Add Config Type column to the Config list and display 'Encrypted as Kubernetes Secret' and 'Public'.
