### ISSUE TITLE
Why can't I run workflow directly from template page

### ISSUE THREAD

**Issue by vrodomista** [argoproj/argo#2688]
I didn't think this deserved a bug sticker, so I posted as a question. The issue I am having after having freshly setup argo on my cluster is that I am unable to run templates in the UI. I can go to the template, but when I click submit and then submit on the modal that pops up - nothing happens. The submit button gets greyed out but that's about it. Is this a work-in-progress issue or is this unique to me?

https://pasteboard.co/J3QHoT4.png

# Motivation

I need to figure this out to meaningfully implement Argo Workflows.

**Comment by alexec** [comment]
Can you try click on some white space after you enter the YAML to see if the submit becomes enabled please?

**Comment by simster7** [comment]
Also removing focus from the textarea should trigger validation to run again

**Comment by vrodomista** [comment]
@alexec Tried that, no luck, @simster7 I have tried about everything

**Comment by vrodomista** [comment]
even closing the modal and reopening it will still have a greyed out submit

**Comment by simster7** [comment]
Perhaps this is the same solution to your problem here: https://github.com/argoproj/argo/issues/2693#issuecomment-614182828?

**Comment by vrodomista** [comment]
duplicate of #2693
