### ISSUE TITLE
Automatic workflow duration prediction

### ISSUE THREAD

**Issue by alexec** [argoproj/argo#2717]
# Summary

Users would like to be able to understand the how long similar workflows took to see if they start to take longer.

# Motivation

When I'm using workflow templates, is this template taking longer to run?

# Proposal

![Image from iOS](https://user-images.githubusercontent.com/1142830/93688214-f31cec80-fa78-11ea-95bb-ce8e220b4efc.jpg)

Add summary data of recent runs of the template status?

Related to #1658, #3557

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by alexec** [comment]
@dtaniwaki @sarabala1979 would it be possible do you think?

**Comment by alexec** [comment]
could we solve by just adding duration to list view?

**Comment by dtaniwaki** [comment]
I think we can have stats of workflow templates in RDB or somewhere and calculate the average, median and etc. and show it in the list view.

But it may affect the performance of the controller. We may need to has an option to disable the feature.

**Comment by dtaniwaki** [comment]
Actually, we want to use these stats in the scheduler and optimize the scheduling algorithm. For example, there is few resources available and a pod is waiting with high priority, now, a low priority pod came. If we can predict how long the pod runs, we can let it run before the high priority waiting pod.

**Comment by alexec** [comment]
This specific use case I want to solve - seeing historical durations is shown in the UI already.

**Comment by alexec** [comment]
There might be other things we want to aggregate, so I'll leave this open.

**Comment by alexec** [comment]
#3558 produces a way to determine likely execution time and to dig into problems.

**Comment by alexec** [comment]
Duplicate.

**Comment by tszngai** [comment]
How do I enable this feature to see the estimation time on my UI?

**Comment by alexec** [comment]
It is automatically enabled. It estimates based on the most recently completed workflow that used the same workflow template or cron workflow.

**Comment by tszngai** [comment]
Thanks for the quick reply. I'm using v2.12.5 and I don't see the estimation time on it:
![image](https://user-images.githubusercontent.com/41026708/112033613-d2eaea80-8afa-11eb-9c18-37c9c694c817.png)

**Comment by tobisinghania** [comment]
Is it also possible to retrieve those metrics via the prometheus metrics endpoint?

**Comment by alexec** [comment]
Short answer - no.
Long answer - there are metrics related to workflow execution that might help you.

**Comment by tobisinghania** [comment]
Thx for your answer....although it's not the one I was hoping for ;)
Unfortunately I have not been able to create a similar diagram as you have in the UI with using the duration workflow metric together with a gauge in grafana (this might be only because a lack of skill on my end, though).

Maybe I will create the metric via a workaround which is using your api and pushes to prometheus...

Thank you

**Comment by Ybbbbbbbbbbb** [comment]
hi, in our  case, due to the large number of workflows that have been archived,  execute SQL queries 
like this can lead to excessive data retrieval, causes a sudden increase in machine IO. That is an issue that needs to be solved.
```
err = r.session.
		Select("name", "namespace", "uid", "phase", "startedat", "finishedat").
		From(archiveTableName).
		Where(r.clusterManagedNamespaceAndInstanceID()).
		And(namespaceEqual(namespace)).
		And(nameEqual(name)).
		And(namePrefixClause(namePrefix)).
		And(startedAtClause(minStartedAt, maxStartedAt)).
		And(clause).
		OrderBy("-startedat").
		Limit(limit).
		Offset(offset).
		All(&archivedWfs)
```

**Comment by agilgur5** [comment]
> hi, in our case, due to the large number of workflows that have been archived, execute SQL queries
> like this

This did not change any SQL queries so I'm not sure what you're referring to. If you have found some bug, please properly report it as a bug. This is a couple years old issue, so commenting here is not really helpful.
