### ISSUE TITLE
Workflows depending on other workflows

### ISSUE THREAD

**Issue by alexec** [argoproj/argo#2718]
# Summary

Make it possible/easy for one workflow to depend on the completion of another.

# Motivation

Tidal parity.

# Proposal

Not sure. Can we do this with artifacts today? 

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by sarabala1979** [comment]
Can we achieve this through  `WorkflowtTemplate`? Master workflow can have a step template and each step can refer to different WorkflwoTemplates(technically workflow definition).   This way user can have more flexibility of `When` condition, skip the step using`continueOn`

**Comment by mukulikak** [comment]
Workflows need to depend on completion of all or any of the workflows it is dependent on. so need to support DAG of workflows

**Comment by sarabala1979** [comment]
#3295
