### ISSUE TITLE
UI Crash on Containers or Yaml button

### ISSUE THREAD

**Issue by pbecotte** [argoproj/argo#2726]
Checklist:

v2.7.4

**What happened**:

New install of argo a couple days ago. Added a cronworkflow. It runs them, but in the UI clicking on "containers" for any particular run crashes the React app.

> TypeError: Cannot read property 'local/backup-grafana-xp4lt/backup-grafana' of undefined

Tried updating to the lastest version just now (2.7.4), no change. Happens with every workflow, and on both the "containers" link and the "yaml" link.

Deployed running kustomize directly against the 'base install' folder in this repo.

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by pbecotte** [comment]
I did. Just the TypeError listed above followed by many lines of minified JavaScript.

**Comment by alexec** [comment]
Can you please provide your YAML so we can repro?

**Comment by pbecotte** [comment]
`
resources:
  - http://<ourmirror>/argo/manifests/cluster-install?ref=v2.7.4
  - ./ingress.yaml

images:
  - name: argoproj/argocli
    newName: <ourmirror>/argoproj/argocli
    newTag: v2.7.4
  - name: argoproj/workflow-controller
    newName: <ourmirror>/argoproj/workflow-controller
    newTag: v2.7.4

patchesJson6902:
  - target:
      name: workflow-controller
      kind: Deployment
      group: apps
      version: v1
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/args
        value:
          - --configmap
          - workflow-controller-configmap
          - --executor-image
          - <ourmirror>/argoproj/argoexec:v2.7.4
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: argo
spec:
  rules:
    - host: 'arogo.<our hostname>'
      http:
        paths:
          - backend:
              serviceName: argo-server
              servicePort: 2746
`

**Comment by brunomptorres** [comment]
I'm adding a GIF with the behavior on our project
![2020-04-17 12 02 19](https://user-images.githubusercontent.com/7015243/79562741-6c1bb080-80a3-11ea-95c6-efcf0a3e987c.gif)

**Comment by simster7** [comment]
I think there are a couple of things happening here.

> New install of argo a couple days ago. Added a cronworkflow. It runs them, but in the UI clicking on "containers" for any particular run crashes the React app.
>
> >   TypeError: Cannot read property 'local/backup-grafana-xp4lt/backup-grafana' of undefined

This behavior is part of a commit (https://github.com/argoproj/argo/pull/2573) that has not been released yet, so it's not ready for use.

> Deployed running kustomize directly against the 'base install' folder in this repo.

You're most likely getting changes that haven't been released because you're using Kustomize to deploy. See https://github.com/argoproj/argo/issues/2715. We're currently working on making changes so that deployments from Kustomize don't behave this way: https://github.com/argoproj/argo/pull/2724

> I'm adding a GIF with the behavior on our project

Unsure if this is part of the same team, but the UI shown in this GIF is and old and deprecated version of the UI (from `2.4` and before). See https://github.com/argoproj/argo/blob/master/docs/getting-started.md#8-access-the-argo-ui on how to access the new UI.

**Comment by brunomptorres** [comment]
> Unsure if this is part of the same team, but the UI shown in this GIF is and old and deprecated version of the UI (from 2.4 and before). See https://github.com/argoproj/argo/blob/master/docs/getting-started.md#8-access-the-argo-ui on how to access the new UI.

Different teams. But I'll try to see if updating to the new UI fixes it on my end

**Comment by alexec** [comment]
This attached GIF shows the v2.4 UI which is defunct and not compatible with v2.7.4. Please make sure you're using the latest UI. We should display UI version as an aside.

**Comment by sarabala1979** [comment]
Are you using a v2.7.2 persistence feature with `NodeStatusOffload` enabled?

**Comment by brunomptorres** [comment]
> This attached GIF shows the v2.4 UI which is defunct and not compatible with v2.7.4. Please make sure you're using the latest UI. We should display UI version as an aside.

Like I said on my update on https://github.com/argoproj/argo/issues/2726#issuecomment-615289112 with the new UI some of the issues go away but others remain, new GIF to illustrate:
![2020-04-17 19 28 25](https://user-images.githubusercontent.com/7015243/79602179-ecf99d00-80e1-11ea-8f26-f9690518f45b.gif)

But appears that this new issue is going to be tracked on #2736

**Comment by pbecotte** [comment]
> This behavior is part of a commit (#2573) that has not been released yet, so it's not ready for use.

Which behavior? the containers or yaml buttons? (the second gif from brunomptorres illustrates what we are seeing as well).

> You're most likely getting changes that haven't been released because you're using Kustomize to deploy. See #2715. We're currently working on making changes so that deployments from Kustomize don't behave this way: #2724 

Yes, I saw #2715- you'll notice that I used a patch to pin the various container versions (our cluster runs inside a firewall anyway, that would have been necessary even without the "latest" tags). I can't imagine that there is anything specific about the deployment method in this case causing this though- the javascript app isn't even making a network request there, just failing immediately. It's possible that version 2.7 wasn't ready for release? Usually you would hide non-functional buttons in the UI though :)

**Comment by simster7** [comment]
I opened #2726 to investigate the UI crash

**Comment by simster7** [comment]
> It's possible that version 2.7 wasn't ready for release?

I don't think so. Tagging templates with strings like 'local/backup-grafana-xp4lt/backup-grafana' haven't been released yet, so the fact that you're getting them tells me that either kustomize is pulling manifests or docker is pulling images that are not ready for release.

Nevertheless, there was actually a related but different UI issue: opened https://github.com/argoproj/argo/pull/2754 to fix it.

**Comment by pbecotte** [comment]
I am just running the image from dockerhub- I haven't looked at the code to see your build/release/feature flag setup, but if that behavior isn't supposed to be released, it probably needs to be looked at :)

**Comment by simster7** [comment]
Closing with https://github.com/argoproj/argo/pull/2724
