### ISSUE TITLE
Fetching the executor image with an imagePullSecret

### ISSUE THREAD

**Issue by twiechert** [argoproj/argo#2734]
We are currently setting up Argo using the k8sapi executor but Workfows don't get picked up by the controller.

Our current suspicion is that the spawning process is dying silently while trying to fetch the executor image.  Could that be a potential issue or are secrets propagated through the Workflow resource when fetching the executor?

Other than that, we are unsure which exact role the executor-image plays when using different execution types. 

I used argo workflow almost two years ago. I remember that workflows had been spawned as pods and workflow statuses been reported back through sidecars. I don't remember having dealt with an executor config back then. Or am I confusing something?

**Comment by alexec** [comment]
Could you please provide more diagnostic information? I recommend you re-raise this as a bug to see what information is needed.
