### ISSUE TITLE
Create a workflow to build deploy and test kubernetes

### ISSUE THREAD

**Issue by abhinavdas** [argoproj/argo#276]
This is a workflow that creates a kubernetes on kubernetes deployment https://github.com/abhinavdas/kink/blob/master/.argo/kubernetes.yml. Currently the binaries that it installs are kubernetes release binaries (1.7.6). The goal of this issue is to compile the latest binaries, install them as a kubernetes on kubernetes deployment and run e2e tests. 
The steps needed are:
1. Create a docker container that has dependencies needed to compile kubernetes master
2. Run make to build binaries
3. Copy binaries out as artifacts and start kubernetes deployment for master and minion
4. Once master and minion are ready, use the src and built binaries to run e2e tests

For step 4: 
```
export KUBECONFIG=/path/to/kubeconfig
kubetest -v -test -provider=local -test_args="--host=https://IPOFMASTER"
```

**Comment by pratulw** [comment]
@francis-ax can you please take this on and get status next week.
