### ISSUE TITLE
Add TLS support to Argo Server

### ISSUE THREAD

**Issue by alexec** [argoproj/argo#2764]
# Summary

Argo Server needs a HTTPS endpoint.

# Motivation

This is so we can encrypt all communication.

# Proposal

Same as Argo CD?

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by alexec** [comment]
@edlee2121 we can used self-signed certs because the requirement is only encryption?

**Comment by edlee2121** [comment]
Yes, self-signed certs are fine.

**Comment by alexec** [comment]
@jessesuen , @edlee2121 requested we sync on this.

**Comment by alexec** [comment]
The workflows controller metrics server exposes metrics on 9090. This is pre-existing.
