### ISSUE TITLE
Missing Information in Argo CLI Cluster Management Help 

### ISSUE THREAD

**Issue by cyee88** [argoproj/argo#277]
The CLI help text is missing some important information. 

For the 23 optional arguments, about 15 of the arguments are missing crucial configuration information.

For example, the CLI Help text for these optional arguments are missing the following infromation:

--cluster-name    Does not mention the min/max length (2 - 64 characters)
--cluster-id          Does not mention that the id must be a UUID for an AWS cluster nor does it mention the "default" profile

We should add the missing information to the CLI help text.

**Comment by jessesuen** [comment]
Closing V1 issues
