### ISSUE TITLE
DOCKER_BUILD_OPTS does not work as intended

### ISSUE THREAD

**Issue by simster7** [argoproj/argo#2770]
https://github.com/argoproj/argo/blob/af9f61ea7ce53f629a284a44f0106b9ed73f24e2/Makefile#L16

When running `make build` in a release branch, `--no-cache` is not added for some reason.

**Comment by alexec** [comment]
I can tell you why `DOCKER_BUILDS_OPTS` != `DOCKER_BUILD_OPTS` (extra "S").

**Comment by alexec** [comment]
`make --warn-undefined-variables` does not actually help.

**Comment by simster7** [comment]
That seems to be the error on the file as well

**Comment by alexec** [comment]
AFAIK, you cannot fail a `Makefile`, best you can do:

alias make=make --warn-undefined-variables

**Comment by alexec** [comment]
Just a thought. Instead of fixing, in the `make clean` target can you bust the Docker cache?
