### ISSUE TITLE
Workflow Labels - Annotations on Rows

### ISSUE THREAD

**Issue by ericmeadows** [argoproj/argo#2782]
# Summary

Add labels to each workflow row for custom Workflow labels.

# Motivation

We have some developers that want to be able to have a quick look at the workflows, and not all understand the way to filter through the massive list of values in the list.  
# Proposal

How do you think this should be implemented?

Add random, or `configMap` specifiable labels to each row, giving simple visual representation of what labels are present for a given build.  When a label is clicked on, this should then filter the list down to only include those whose values are equal to the given label.

See **EXP1** below.
![](https://user-images.githubusercontent.com/40736765/43573401-efbb5a38-9641-11e8-943a-72df97504bda.png)

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by alexec** [comment]
This is a great idea! But, what is the app in the screenshot? It is not Argo Workflows AFAIK?

**Comment by ericmeadows** [comment]
@alexec - it is not.  It was a React app that I figured would be an example.  Another one would be GitHub's labels...

**Comment by rbreeze** [comment]
I can work on this one

**Comment by ericmeadows** [comment]
Awesome - let me know if you have questions.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by rbreeze** [comment]
@ericmeadows Was something like this what you were envisioning? I haven't added the tooltip on hover yet but will update you when I do.

<img width="760" alt="Screen Shot 2020-06-01 at 10 19 04 AM" src="https://user-images.githubusercontent.com/6250584/83435618-67138600-a3f1-11ea-8809-e61337ad4099.png">

**Comment by sarabala1979** [comment]
@rbreeze  thanks for taking more issues. I would recommend having multiline text or scrollable label. So it can display all labels/annotations in one place with scroll and we can save some realestate

![image](https://user-images.githubusercontent.com/33908564/83436904-9d520500-a3f3-11ea-8bed-708ffeb876be.png)

**Comment by rbreeze** [comment]
@sarabala1979 good idea, thanks! As I have it, the labels are multiline, just not demonstrated in the screenshot. But some sort of scroll interface would probably help for workflows with dozens of labels.
