### ISSUE TITLE
Create Dropdowns per Label in Workflows Views

### ISSUE THREAD

**Issue by ericmeadows** [argoproj/argo#2783]
# Summary

Group labels into sortable drop-down lists to ease searching.

# Motivation

We are adding labels to make them sortable - we have hundreds of builds a day, and sometimes you want to look at the builds for yourself to trace down a bug instead of having to go between GitHub for the given commit's build, etc.  By allowing me to select just my builds on a given branch (these are already labels), it would be easier.  The problem is that these labels are in a single list, and are very cumbersome to navigate.

# Proposal

How do you think this should be implemented?

In `configMap`, you can specify labels that will have a dropdown, otherwise they will be in a massive other list, `Other Labels`.  For instance, I would like to have the GitHub committer be a filter, and I would also like to be able to filter based upon time of Workflow Initialization, along with instance types used by tasks (are they all GPU/CPU, etc)

List could shrink or grow, or list of labels could be static based upon all groups.
![](https://i.ytimg.com/vi/c7-HkztGahM/maxresdefault.jpg)

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

![](https://i.ytimg.com/vi/c7-HkztGahM/maxresdefault.jpg)

**Comment by rbreeze** [comment]
I'll take this one

**Comment by rbreeze** [comment]
@ericmeadows In `configMap`, what format do you envision for specifying which labels go in which dropdown?

**Comment by simster7** [comment]
Hey @ericmeadows, we discussed this issue and decided that adding the ability to specify label dropdowns is too specific of a use case and would not want to support it for now.

Is there a reason as to why being able to filter labels by search is not sufficient for you?
<img width="290" alt="image" src="https://user-images.githubusercontent.com/614838/83552707-0e122380-a4bf-11ea-9780-70c58516b04b.png">

Let me know if I'm not understanding your use case correctly.
