### ISSUE TITLE
`withItems` isn't accurately described in swagger.json

### ISSUE THREAD

**Issue by mac9416** [argoproj/argo#2790]
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [x] I've included the workflow YAML.
 * [ ] I've included the logs.
 
**What happened**:

swagger.json didn't match API output for `spec.templates[0].dag.tasks[1].withItems`. The swagger spec [describes](https://github.com/argoproj/argo/blob/8de572813ee9f028cf8e06834f45a3592bc73f14/api/openapi-spec/swagger.json#L2082) `withItems` as an array of `Item`, but instead the array items can be numbers, booleans, strings, arbitrary objects, or arrays of these same types (except the nested arrays may contain any values, including nulls, if I'm reading the code correctly).

Aside: Downstream, this causes issues for _at least_ the Java client. I've written [an issue for argo-client-gen](https://github.com/argoproj-labs/argo-client-gen/issues/7). Unfortunately, I _don't_ think fixing swagger.json will fix the client (at least not if the fix relies on Swagger's `oneOf` feature, which I think it probably will).

**How to reproduce it (as minimally and precisely as possible)**:

`argo submit https://raw.githubusercontent.com/argoproj/argo/master/examples/loops-dag.yaml -n argo`

Then hit `/api/v1/workflows/argo` on your Argo server.

Search for "withItems", and you'll find that the array contains strings.

**Anything else we need to know?**:

`Item` has a [custom marshaller/unmarshaller](https://github.com/argoproj/argo/blob/8de572813ee9f028cf8e06834f45a3592bc73f14/pkg/apis/workflow/v1alpha1/item.go#L84), which is why swagger.json doesn't match the API output.

`Item`, when expressed as an array, may contain elements of type `ItemValue`. That type [also has a custom marshaller/unmarshaller](https://github.com/argoproj/argo/blob/8de572813ee9f028cf8e06834f45a3592bc73f14/pkg/apis/workflow/v1alpha1/item.go#L114), so it should probably be modified in swagger.json as well.

I think `withItems` should be overridden in _primary.swagger.json to use Swagger's `oneOf` to express the possible types. One of the `oneOf` types would probably be "array of `ItemValue`s", so `ItemValue` should probably also be overridden. I suspect `Item` will simply be orphaned.

If the argo-client-gen solution involves simply overriding `withItem`'s type in the openapi-generator arguments, the type info should probably be in a synthetic, named type rather than directly in the `withItem` block. 

**Environment**:
- Argo version:
```
$ argo version
argo: v2.8.0-rc1+4a73f45.dirty
  BuildDate: 2020-04-21T05:30:01Z
  GitCommit: 4a73f45c38a07e9e517c39ed5611d386bcf518bd
  GitTreeState: dirty
  GitTag: v2.8.0-rc1
  GoVersion: go1.13.4
  Compiler: gc
  Platform: linux/amd64
```
- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: "2019-12-11T12:47:40Z"
  compiler: gc
  gitCommit: 224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba
  gitTreeState: clean
  gitVersion: v1.16.4
  goVersion: go1.12.12
  major: "1"
  minor: "16"
  platform: linux/amd64
serverVersion:
  buildDate: "2020-01-27T18:09:26Z"
  compiler: gc
  gitCommit: cdab19b09a84389ffbf57bebd33871c60b1d6b28
  gitTreeState: clean
  gitVersion: v1.17.2+k3s1
  goVersion: go1.13.6
  major: "1"
  minor: "17"
  platform: linux/amd64
```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by alexec** [comment]
Recently we changed the swagger. `Item` is arbitrary JSON, and swagger should reflect that.
