### ISSUE TITLE
How to submit Workflowtemplate

### ISSUE THREAD

**Issue by alex-lipkin-create** [argoproj/argo#2792]
In 2.7 release was added a feature to to submit Workflowtemplate. I can not find any documentation how exactly can workflow template be submitted through argo cli.

Could you please describe exact command and add it to documantation.

**Comment by simster7** [comment]
`argo submit --from=wftmpl/<template_name>`

**Comment by simster7** [comment]
```
$ argo submit --help
submit a workflow

Usage:
  argo submit [FILE... | --from `kind/name] [flags]

Examples:

...

# Submit a single workflow from an existing resource

  argo submit --from cronwf/my-cron-wf


Flags:
...
      --from kind/name          Submit from an existing kind/name E.g., --from=cronwf/hello-world-cwf
...
```

**Comment by alex-lipkin-create** [comment]
Thanks a lot for a quick response. One working example with all steps wrere really helpfull.
I am pretty new in using argo. So I do following steps.

For instance  workflow  hello-word

----
apiVersion: argoproj.io/v1alpha1
kind: Workflow                  # new type of k8s spec
metadata:
  generateName: hello-world-    # name of the workflow spec
spec:
  entrypoint: whalesay          # invoke the whalesay template
  templates:
  - name: whalesay              # name of the template
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["hello world"]
      resources:                # limit the resources
        limits:
          memory: 32Mi
          cpu: 100m
---

Step1: I am changing kind from Workflow to WorkflowTemplate.
Then run  argo template create hello-word-template.yaml
That runs successfull:
-----
Name:                hello-world-ds9tm
Namespace:           argo
Created:             Thu Apr 23 08:51:55 +0200 (now)
-------

Now trying to execute workflow template

argo submit --watch --from hello-world-/whalesay
and get an error message
2020/04/23 08:53:25 Failed to submit workflow: Resource kind 'hello-world-' is not supported for submitting

Where I do an error?

Thanks
Alex

**Comment by alex-lipkin-create** [comment]
OK, found the problem. It schould be executed as:

 argo submit --watch --from=wftmpl/workflow-template-submittable

Thanks for support
