### ISSUE TITLE
Metrics Endpoint slow with large number of Workflows

### ISSUE THREAD

**Issue by salanki** [argoproj/argo#2815]
**What happened**:
With a large number of workflows, the `/metrics` endpoint is slow to respond. This with legacy metrics disabled and no custom metrics.

```bash
$ time curl http://10.135.205.252:8080/metrics
# HELP argo_workflows_count Number of Workflows currently accessible by the controller by status
# TYPE argo_workflows_count gauge
argo_workflows_count{status="Error"} 0
argo_workflows_count{status="Failed"} 5
argo_workflows_count{status="Pending"} 0
argo_workflows_count{status="Running"} 1
argo_workflows_count{status="Skipped"} 0
argo_workflows_count{status="Succeeded"} 12349

0.01s user 0.01s system 0% cpu 7.173 total
```

The `workflow-controller` is running unbounded on a latest generation AMD Epyc CPU, much faster than you'd find in your typical AWS or GCP instance, however I assume that much of the delay is due to querying Kubernetes objects. A response time of less than 10s is often expected for a Prometheus metric, which means that this will top out at a couple of thousand more workflows.

**What you expected to happen**:
This is not necessarily a bug, but it is a scalability concern, and should be noted in scalability documentation.

**How to reproduce it (as minimally and precisely as possible)**:
Create a lot of workflows. Query `/metrics`.

**Environment**:
On prem.

```
argo: v2.7.3
  BuildDate: 2020-04-15T22:52:59Z
  GitCommit: 66bd0425280c801c06f21cf9a4bed46ee6f1e660
  GitTreeState: clean
  GitTag: v2.7.3
  GoVersion: go1.13.4
  Compiler: gc
  Platform: darwin/amd64
```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by simster7** [comment]
Thanks for this @salanki, I have a fair idea of what the issue is here

**Comment by alexec** [comment]
@simster7 I have a solution to this I'd like to discus than would design-on scalability problems.

**Comment by simster7** [comment]
Sure, let's discuss

**Comment by alexec** [comment]
ping me whenever

**Comment by alexec** [comment]
@simster7 do you want to own this?
