### ISSUE TITLE
Augment `argo list --chunk-size` with `--continue` and `--limit`

### ISSUE THREAD

**Issue by alexec** [argoproj/argo#2820]
# Summary

There is no way to get the next chunk.

# Motivation

* So that we can get the next chunk.
* So we know that there is another chunk.
* Use server side list options.
* Do not default to 500, should be all by default - I think this was a breaking change. 
* Not consistent with `kubectl get`

# Proposal

Edit `cmd/argo/commands/list.go` keep the option like `kubectl get`:

```
kubectl get --help
...
      --chunk-size=500: Return large lists in chunks rather than all at once. Pass 0 to disable. This flag is beta and
may change in the future.
```

We should also support two new options that we can pass directly to `metav1.ListOptions`:

```
--continue string
--limit limit
```

See https://github.com/kubernetes/apimachinery/blob/master/pkg/apis/meta/v1/types.go#L80

```
if(results == limit) print(“There are additional suppressed results, show them by increasing --continue string”)
```

See #2420 and #2485
---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by alexec** [comment]
@changhc FYI

**Comment by salanki** [comment]
As currently implemented, it seems as the pagination is done client side, without any performance benefit except for less console output: https://github.com/argoproj/argo/blob/96c80e3e2c6eb6867e360dde3dea97047b963c2f/cmd/argo/commands/list.go#L120. For this to be useful, the chunking has to happen server side, otherwise it is fairly pointless from a performance perspective.

**Comment by changhc** [comment]
I agree. So it means that we need to implement some cursors as well for this right?

**Comment by alexec** [comment]
The Kubernetes APIs already support limit and continue, so it is a case of just passing the values down and back.

**Comment by salanki** [comment]
It would be super awesome if this was implemented in a way so that it can be used by the web UI in the future as well. Doing server side pagination would make the UI actually useful for > 400 workflows.

**Comment by changhc** [comment]
Do we really want to remove the default 500? I'm wondering if it's problematic if a user has lots of workflows. Or we still keep it but set limit to 500 at the same time and show `There are additional suppressed results, show them by increasing --continue string` if there are more records?

**Comment by salanki** [comment]
I think either or is good, as long as the message is there.

**Comment by tooptoop4** [comment]
maybe https://github.com/argoproj/argo-workflows/issues/9656 is related
