### ISSUE TITLE
Compatibily issues when using WorkflowTemplates as a "template" library

### ISSUE THREAD

**Issue by simster7** [argoproj/argo#2831]
Currently a `WorkflowTemplate` is guaranteed to behave exactly as a `Workflow` when it is used as a “Submittable WorkflowTempalte” – i.e. when creating the WorkflowTemplate on the cluster and then submitting it as a whole via `argo submit --from`.

The same guarantee is not afforded when using them as a “template” (note lower-case template) library. I.e. when you there is an existing `WorkflowTemplate` in the cluster, and the only interaction with it is to reference it with `templateRef`.

This had led rise to some issues, such as #2777 and some over Slack:

> Workflow parameters. As of v2.7, you simply can't use these in a `WorkflowTemplate`. In v2.8, it seems like they will be allowed, but since the `WorkflowTemplate` isn't at the highest level anymore, it won't be able to define them. So you'll have to convert any usages into input parameters passed throughout the tree of template calls.
> Exit handlers. As a Workflow, the `onExit` field defines another step that always runs after the `entrypoint` template runs. But as a `WorkflowTemplate`, that logic now resides in the main workflow that is invoking that template. My understanding is that if you want to port over the exit handler logic, too, then you need to separately define a new template within the calling workflow that references the exit handler, and pass that template under the `onExit` field. Alternatively, you can abandon the exit handler entirely in favor of manually defining the main workflow and the cleanup step running serially, using `continueOn` logic.

We should make a decision as to how much we want to support this "template library" use case by adding support for behaviors such as those described above.

**Comment by sarabala1979** [comment]
https://github.com/argoproj/argo/issues/2777#issuecomment-619486554
#2556

**Comment by automagic** [comment]
A use-case we have is being able to use the global outputs of a workflow template (by `globalName:`) just as if we were referencing the outputs of a local template in a workflow.  That is, our workflow has a step that references a WorkflowTemplate by `templateRef` and we would like to reference its outputs in a dag or step workflow, e.g. `{{ tasks.my-templated-task.outputs.parmeters.my-template-global-output-param }}`

**Comment by samath117** [comment]
For volumes and global parameters, I like the solution @sarabala1979 linked in of merging all of the global (workflow) parameters, with the caller getting priority over the template library if they conflict (as with default input parameters).

I'm not sure there's a good solution to the exit handler issue, though, and maybe that should be forked for another time. On the project I'm working on right now, I've decided to just get rid of exit handlers, replacing them with an explicit higher-level steps template with the exit handler as the second step and the continueOn: {failed: true} option on the first step. This was also necessary because they used global outputs, which is another issue with passing information to exit handlers.

(I was the author of the above quoted discussion on Slack. Thanks for making an issue for me!)

**Comment by samath117** [comment]
@automagic There shouldn't be any issue using regular (non-global) outputs of a WorkflowTemplate exactly the same way as you would a template (e.g. `{{tasks.TASK.outputs.parameters.NAME}}`). Global output variables (`{{workflow.outputs.parameters.NAME}}`) just have a bug (#2590) whose fix appears to be in the works

**Comment by automagic** [comment]
@samath117 tasks.TASK refers to a WorkflowTemplate (entrypoint), but i want the output of a (sub) task within that WorkflowTempate to use in the caller.  How do I specify the output parameter name on the WorkflowTemplate?

**Comment by samath117** [comment]
@automagic No, tasks.TASK refers to a particular invocation of the template in a dependent task within the same DAG as where it is called. If the dependent task is itself an invocation of a DAG (or steps) template, you can't extract any of its own tasks' output artifacts or parameters unless those are "exported" by making them output artifacts or parameters of the parent task. All of this holds whether we're talking about templates defined in the same file or WorkflowTemplates.

Anyways, this is getting a bit farther afield; let's take further discussion of this to Slack.

**Comment by salanki** [comment]
As I understand it, currently, global parameters in a `WorkflowTemplate` are not usable when used as a `templateRef`? There was some discussion around it here: https://github.com/argoproj/argo/issues/2559#issuecomment-611042520. It would be really useful to be able to use global parameters in WFTs when used as `templateRef`. This will make them more reusable (as they can be treated both as WFs and WFTs) and globals allow for less prop-passing inside the template.

**Comment by alexec** [comment]
@simster7 to respond.

**Comment by simster7** [comment]
@salanki Could you provide a short example? Sorry I can't seem to understand what you mean. Do you mean that global parameters in a Workflow are not accessible within templates referenced using `templateRef` or that global parameters in a `WorkflowTemplate` are not carried over when calling templates referenced using `templateRef`?
