### ISSUE TITLE
Argo Server doesn't release memory when Workflows are deleted

### ISSUE THREAD

**Issue by salanki** [argoproj/argo#2846]
**What happened**:
When passing through thousands of workflows through Argo, Argo Server seems to hold on to some resources in memory even efter the workflow has been deleted by `argo delete`.

![Screen Shot 2020-04-26 at 11 28 42](https://user-images.githubusercontent.com/192223/80315349-ee535580-87c4-11ea-9a83-8f2a620df911.png)
Between each run (noted by the large uptick), all workflows were deleted.

When restarting `argo-server` memory usage returns to 0, and starts building up again with new workflows submitted:
![Screen Shot 2020-04-26 at 13 28 20](https://user-images.githubusercontent.com/192223/80315650-0035f800-87c7-11ea-9737-4182d3d70d8b.png)

`legacyMetrics` are disabled. No custom metrics. No SQL workflow persistence. `resourcesDuration` is enabled.

The increase seems to be a step function, it could possibly be some internal buffers that get re-allocated as demand grows? Kind of like JVM heap.

**What you expected to happen**:
Memory usage should go down as workflows are deleted, or document in scalability docs that a spike in workflows will lead to persistent memory growth in argo-server. 

**How to reproduce it (as minimally and precisely as possible)**:
Run 2,000 short workflows after each other.

**Anything else we need to know?**:
If logs can be of help let me know, they are quite massive so I will have to wrangle to get them exported, unless there is something specific I should look for.

**Environment**:
- Argo version:
```
argo: v2.7.3
  BuildDate: 2020-04-15T22:52:59Z
  GitCommit: 66bd0425280c801c06f21cf9a4bed46ee6f1e660
  GitTreeState: clean
  GitTag: v2.7.3
  GoVersion: go1.13.4
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :
```
$ kubectl version -o yaml
```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by alexec** [comment]
Thank you for this report. The argo-server (not the workflow controller) is stateless and so memory usage should not increase. To control memory usage in the short term you can set pod resource requests and limits for the container (we probably should by default - so if you do come up with limits - do let us know what they are).

Can I please ask for additional information:

* What auth-mode are you using?
* What APIs are you using -  `CreateWorkflow`,  are you invoking `PodLogs` or `WatchWorkflow`?

**Comment by alexec** [comment]
argo-server:
```
    resources:
      requests:
        cpu: 0.1
       # we need a minimum of 16m
        memory: 64Mi 
      limits:
        cpu: 0.5
        memory: 128Mi
```

You need only to create some workflows to repro this and you can see memory usage slowly increase from 16m .

**Comment by alexec** [comment]
![profile001](https://user-images.githubusercontent.com/1142830/80321920-0aabbe00-87d6-11ea-9d19-7aaf93aa81ce.png)

**Comment by alexec** [comment]
@salanki are you please able to provide more information?

**Comment by salanki** [comment]
Thanks for the reminder, will get back to you asap.

**Comment by alexec** [comment]
No reply. Closing.
