### ISSUE TITLE
Workflow archive installation is incomplete

### ISSUE THREAD

**Issue by inc0** [argoproj/argo#2859]
Checklist:

 * [x] I've included the version. - 2.7.5
 * [x] I've included reproduction steps.
 
**What happened**:

When installing Argo from guide, we enabled workflow archive. We've created database. Now after checking Argo UI in archive, we got error. 

```
{
  "error": "Error 1146: Table 'virga.argo_archived_workflows' doesn't exist",
  "code": 2,
  "message": "Error 1146: Table 'virga.argo_archived_workflows' doesn't exist"
}
```

https://github.com/argoproj/argo/blob/master/docs/workflow-archive.md doesn't show any notion of create table needed or which schema should it use

**Comment by alexec** [comment]
Tables are created by the workflow controller. Can you please attach its logs?

**Comment by inc0** [comment]
I figured it out, problem was that user that workflow controller had was unable to create tables. I also had small typo in config. Problem was, as usual, between chair and keyboard. Thank you!
