### ISSUE TITLE
Need documentation on "nodeFieldSelector"

### ISSUE THREAD

**Issue by simster7** [argoproj/argo#2860]
We need to add some documentation regarding `nodeFieldSelector`s in CLI commands. Ideally, it would be a doc under `docs/` something like `node-field-selector.md` following the same template of other docs. The docs should contain a list of all available "node selector fields" in it.

I think the closest example for this would be something like https://github.com/argoproj/argo/blob/master/docs/default-workflow-specs.md

**Comment by simster7** [comment]
@mark9white Could I ask that you own this since you implemented the feature? If not possible I can take care of it.

**Comment by mark9white** [comment]
No problem
