### ISSUE TITLE
Create a cmd/common package for methods used accross the CLI

### ISSUE THREAD

**Issue by simster7** [argoproj/argo#2864]
For example, the `printWorkflow` method is used in different parts of the CLI. `cmd/argo/get.go` and `cmd/argo/archive/get.go`.

Currently, the method is duplicated in the two files, which is undesirable. Furthermore, importing the method from the `commands` package would create a circular dependency.

We should extract these functions under a common package so that they can be imported across the CLI.

**Comment by agilgur5** [comment]
> For example, the `printWorkflow` method is used in different parts of the CLI. `cmd/argo/get.go` and `cmd/argo/archive/get.go`

This was completed as part of https://github.com/argoproj/argo-workflows/pull/8166#discussion_r829542134
