### ISSUE TITLE
Add controller mode where only WFs from WFTemplates can be submitted

### ISSUE THREAD

**Issue by simster7** [argoproj/argo#2867]
# Summary

Add a "restricted" mode to the `workflow-controller` where only `Workflows` that submit `WorkflowTempaltes` can be executed. Depends on the top-level `WorkflowTemplate` reference PR #2556 

# Motivation

After #2556 is completed, users will be able to submit Workflows that are simply a reference to a `WorkflowTemplate`.

Some users might want to take advantage of this feature to add a "restricted" controller, in which users of said controller may only submit `Workflows` that already exist in the cluster as `WorkflowTemplates` and may not submit any user-defined `Workflows`. These `WorkflowTemplates` would be maintained by the "cluster owner".

# Proposal

Allow the `workflow-controller` to start with a flag setting it as restricted, then only accept `Workflows` that contain a workflow reference as defined in #2556 

Feature idea by @jessesuen 

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by stefansedich** [comment]
I like this idea, lets us manage the templates in our normal GitOps process and not allow arbitary workflow execution.
