### ISSUE TITLE
Preempted nodes are treated as Fails but should be Errors

### ISSUE THREAD

**Issue by hnykda** [argoproj/argo#2881]
**What happened**: When a kubernetes node is preempted (killed), the workflow nodes get into `phase: Failed`, but it should be `phase: Error`.

**What you expected to happen**: A node would get `phase: Error`

**How to reproduce it (as minimally and precisely as possible)**: Run jobs on cloud (we use GCP) and wait until your node is preempted.

**Anything else we need to know?**: The reason why we want this is that we want the jobs to retry on preemption but not on program failure (which is deterministic therefore it doesn't make sense to retry). We hoped that this will be fixed by adding `retryPolicy`, where `Error` is for preempted nodes and `Failed` is for actual failures, so we could use `retryPolicy: OnError`. But given the workflow nodes don't end up in `Error` in these cases, it's not possible to distinguish between these. 

Running workflows on preemptible nodes would mean huge savings.

**Environment**: GKE in GCP

- Argo version:
```
$ argo version
argo: v2.6.3
  BuildDate: 2020-03-16T17:55:34Z
  GitCommit: 2e8ac609cba1ad3d69c765dea19bc58ea4b8a8c3
  GitTreeState: clean
  GitTag: v2.6.3
  GoVersion: go1.13.4
  Compiler: gc
  Platform: linux/amd64
```
- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: "2020-03-25T14:58:59Z"
  compiler: gc
  gitCommit: 9e991415386e4cf155a24b1da15becaa390438d8
  gitTreeState: clean
  gitVersion: v1.18.0
  goVersion: go1.13.8
  major: "1"
  minor: "18"
  platform: linux/amd64
serverVersion:
  buildDate: "2020-02-21T18:01:40Z"
  compiler: gc
  gitCommit: 145f9e21a4515947d6fb10819e5a336aff1b6959
  gitTreeState: clean
  gitVersion: v1.14.10-gke.27
  goVersion: go1.12.12b4
  major: "1"
  minor: 14+
  platform: linux/amd64
```

**Other debugging information (if applicable)**:
* [Gist with the result workflow](https://gist.github.com/hnykda/47b25c1944c848df3067ec253c9553f1#file-workflow-result)
* [workflow-controller logs](https://gist.github.com/hnykda/47b25c1944c848df3067ec253c9553f1#file-controller-logs-descending)
* [preemption log](https://gist.github.com/hnykda/47b25c1944c848df3067ec253c9553f1#file-log-preemption-via-gcp)

It seems that the pods get `message: pod termination`, which sounds quite generic. But I haven't found any other case when this message would occur but this case, so IMO it _should_ be possible to either create a new state or set it to `Error`. I believe that `Failed` should be reserved for program failures, not for generic errors.

Related:
* https://github.com/argoproj/argo/issues/1796

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by alexec** [comment]
You've raised a bug, are you able to provide repro steps?

Also, can you try in v2.8.0-rc3?

**Comment by simster7** [comment]
The node is set to `Failed` in this line (per your posted logs):

https://github.com/argoproj/argo/blob/a0035dd58609d744a6fa304e51d61474f25c817d/workflow/controller/operator.go#L957-L960

Which leads me to assume that when a Node is preempted, it deletes all of its pods gracefully (hence setting `DeletionTimestamp`). This behavior would be similar to a user deleting a pod manually while a Workflow is running.

I am starting to think that when this happens the resulting phase should indeed be `Errored`: if a Pod is deleted under a Workflow's feet, it should not be a node-internal "failure".

However I don't know why that's not the case right now. I'll bring this up internally and update.

**Comment by hnykda** [comment]
Yes, you are probably right. When I `delete` a running pod (managed by workflow) manually, it does get `phase: Failed`:
![image](https://user-images.githubusercontent.com/2741256/80643541-8f156f80-8a68-11ea-8dfa-ad5cb4c61467.png)

**Comment by hnykda** [comment]
Awesome, thank you!
