### ISSUE TITLE
Allow to open workflow logs in new tab

### ISSUE THREAD

**Issue by dguendisch** [argoproj/argo#2887]
The new logging facility option is really great and super useful (https://github.com/argoproj/argo/pull/2443)
While the pod log link allows to be opened in a new tab (or directly cmd+click), the same doesn't work for the workflow link on the top.
Is it possible to enable this for the top workflow log link as well?

![image](https://user-images.githubusercontent.com/30311254/80612176-e4875780-8a3b-11ea-99c8-98ca14f2cebf.png)

**Comment by alexec** [comment]
Would you like to submit a PR to fix this?

**Comment by dguendisch** [comment]
I'm sorry but having never done any html/javascript/typescript/react and judging from a quick look (seeing that the buttons in the pod links are directly styleable and seeing that the buttons from the workflow links come from some more generic page/toolbar and given your comment here https://github.com/argoproj/argo/pull/2443/files#diff-a19f113f6e39d3f31c1d1e776cdf84b3R388) I fear that I'm not capable of changing the code with reasonable efforts.
