### ISSUE TITLE
Mention AWS CLI in 'Prerequisites for Argo to Run on AWS'

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo#289]
In order to install ARGO user have to install AWS CLI and configure at least one AWS profile. Please add this step into https://argoproj.github.io/argo-site/docs/a_introduction_topics/Min_Req_AWS_Resources_4_Argo.html

**Comment by cyee88** [comment]
Have requested Alex and Ed to review the proposed content:

FAQ

Q. I'm trying to reinstall Argo with different configuration settings but the re-installation fails to take my latest settings. How do I get Argo to take my changes to the configuration settings?

A.  When you rerun the Argo installer with the same cluster name without first uninstalling the cluster, Argo assumes you are trying to resume the failed install from where it left off. This is done to ensure that the installation is idempotent and can be retried multiple times. The Argo installer persists the installation settings and reuses them in subsequent installations of the cluster with the same name. (The settings are stored by cluster name in a S3 bucket.)

To reinstall Argo with new configuration settings, you must first uninstall Argo and then install it again with the new settings. Here's an example of the Argo Dev CLI commands to do this:

argocluster uninstall --cluster-name <yourArgoName> --cloud-provider aws --cloud-profile default

argocluster install --cluster-name argo-cluster \
--cloud-provider aws \
--cloud-profile default \
--cluster-size small \
--cluster-type standard \
--cloud-region us-east-1 \
--cloud-placement us-east-1a \
--vpc-cidr-base 172.20 \
--subnet-mask-size 22 \
--trusted-cidrs 0.0.0.0/0 \
--user-on-demand-nodes 2 \
--spot-instances-option all \
--vpc-id <my-vpc-id>
