### ISSUE TITLE
Swagger docs not getting updated after #2837

### ISSUE THREAD

**Issue by simster7** [argoproj/argo#2892]
**What happened**:

`api/openapi-spec/swagger.json` is not getting updated after #2837. To test this, I reverted the commit and ran `make swagger` again and the docs were updated successfully.

**What you expected to happen**:

When I update `workflow_types.go` and run `make codegen` or even `make swagger`, I expect `api/openapi-spec/swagger.json` to be updated.

**How to reproduce it (as minimally and precisely as possible)**:

1. Modify `workflow_types.go`
2. Run `make codegen`. `api/openapi-spec/swagger.json` won't be updated.
3. Run `make swagger` and get "make: Nothing to be done for `swagger'."

**Anything else we need to know?**:

It could be that `make swagger` works correctly after running `make clean`, but that should be unnecessary.

**Comment by simster7** [comment]
FYI @alexec

**Comment by alexec** [comment]
`api/openapi-spec/swagger.json` is based on `$(SWAGGER_FILES)`, which is based on `codegen` - so we could create an alias target.

**Comment by simster7** [comment]
I thought `make swagger` was a target on `api/openapi-spec/swagger.json`:

```
.PHONY: swagger
swagger: api/openapi-spec/swagger.json
```
?

**Comment by alexec** [comment]
Should be fixed
