### ISSUE TITLE
Do not sleep for 1s each time we reconcile

### ISSUE THREAD

**Issue by alexec** [argoproj/argo#2908]
# Summary

We sleep for 1s in the reconciliation loop. Can we avoid this?

# Motivation

Please give examples of your use case, e.g. when would you use this.

# Proposal

@jessesuen ...

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by simster7** [comment]
I'm sure you've seen the explanation as to why we do this, but good to have on the issue.

https://github.com/argoproj/argo/blob/3afa7b2f1b4ecb9e64b2c9dee1e91dcf548f82c3/workflow/controller/operator.go#L510-L516
