### ISSUE TITLE
Remove old secret v1 from UI

### ISSUE THREAD

**Issue by sytianhe** [argoproj/argo#291]
As we have the Kubernetes secrets as part of configuration management, we should remove the secret v1 from argo.

![screen shot 2017-10-03 at 2 02 39 pm](https://user-images.githubusercontent.com/605748/31149068-903425d2-a843-11e7-9137-bfcd02c77227.png)

![screen shot 2017-10-03 at 2 02 25 pm](https://user-images.githubusercontent.com/605748/31149065-8bdd897e-a843-11e7-8850-fce163ccf06d.png)

**Comment by alexmt** [comment]
done
