### ISSUE TITLE
Some E2E Tests fails in Argo 2.6.1

### ISSUE THREAD

**Issue by Naveenlbg** [argoproj/argo#2916]
Hi Team,

I am using Argo 2.6.1 as part of this there were some security vulnerabilities in Argo Exec image so I tried fixing the issue by changing the base image.
For testing the images are working fine or not I tried executing the Argo E2E tests. I can see some of the tests are failing is it expected or am I missing some configuration.

Any help in this regard will be appreciated

Attached is the Report of the execution for reference
[e2e-test-report.txt](https://github.com/argoproj/argo/files/4563069/e2e-test-report.txt)

**Comment by alexec** [comment]
Thank you for attaching this. We no longer support v2.6, so I'll close this for now.
