### ISSUE TITLE
Testing Argo Workflow pipelines

### ISSUE THREAD

**Issue by yauhen-sobaleu** [argoproj/argo#2931]
# Summary

Hello!
Is there a way to test Argo Workflow pipelines? Are there already any best practices on how to test the contents of an Argo Workflow manifest?

# Motivation

I use Argo Workflows for Spark jobs orchestrations and part of my pipeline is a Python `script` step that does all data dependency checks (if input data is there and output data is not still there -> launch a spark job).

These custom Python script steps can be buggy and I don't see the way how I can cover them with tests in an automated manner.

**Comment by metasim** [comment]
Good question @yauhen-sobaleu

**Comment by bmaggi** [comment]
Hi,

I think it's an excellent question.
I had a look in the [doc](https://argoproj.github.io/argo-workflows/) but did't found the answer 

At this day, is there a recommendation ?

**Comment by ncjones** [comment]
Maybe running K3D or Minikube would work for local integration testing. 

https://argoproj.github.io/argo-workflows/running-locally/

**Comment by DimKanoute** [comment]
If you want to test the script, you can always dockerize it push it to a registry and use this image on the argo workflow.
That way you can have tests and a CI running when you push changes related to the python script.
