### ISSUE TITLE
Some E2E Tests fails in Argo 2.7.6

### ISSUE THREAD

**Issue by Naveenlbg** [argoproj/argo#2940]
Hi Team,

I am using Argo 2.7.6 as part of this there were some security vulnerabilities in Argo Exec image so I tried fixing the issue by changing the base image.
For testing the images are working fine or not I tried executing the below cmd. 

make test               //(output in test.txt)
make test-e2e       //(output in e2e-test.txt)

I also ran the same e2e test connecting to Kubernetes cluster in GCP

make test-e2e      //(output in e2e-test-cluster.txt)

Error : TestWorkflowTemplateSuite: e2e_suite.go:83: No Auth Provider found for name "gcp"

I can see some of the tests are failing 
is it expected ? or am I missing some configuration?

Attached is the Report of the execution for reference

[test.txt](https://github.com/argoproj/argo/files/4575453/test.txt)
[e2e-test.txt](https://github.com/argoproj/argo/files/4575454/e2e-test.txt)
[e2e-test-cluster.txt](https://github.com/argoproj/argo/files/4575457/e2e-test-cluster.txt)

Could you please let me know if I am missing any steps or guide me to any page on how to run the tests. Any help in this regard will be appreciated.

Thanks & Regards,
Naveen

**Comment by alexec** [comment]
We should be fixing security vulnerabilities on master. Can you please provide more info?

**Comment by Naveenlbg** [comment]
Hi Alex,

Thanks for replying.
No, I have already fixed the security vulnerabilities as per my company standards but for testing the cleaned image is working fine or not i am using Argo E2E Test suite.

I tried executing E2E Tests which is there in the make file as a cmd.

I followed the below steps to execute E2E Test

- cloned https://github.com/argoproj/argo Repo

- I installed below packages

         1. home brew go
         2. home brew dep
         3. home brew kustomize
         4. home brew yarn
         5. brew install protobuf

- I executed the cmd
     make test-e2e

But I was unable to execute the whole e2e Test suite as it fails with below step 

FAIL	github.com/argoproj/argo/test/e2e	900.209s
?   	github.com/argoproj/argo/test/e2e/fixtures	[no test files]
FAIL

Is there any step I am missing in running the Test?
If there any reference/ guide me to any page on how to run the E2E Tests will be very helpful.

[e2e-test.txt](https://github.com/argoproj/argo/files/4593871/e2e-test.txt)

Thanks & Regards,
Naveen

**Comment by alexec** [comment]
run `make test-e2e`

**Comment by Naveenlbg** [comment]
But I was unable to execute the whole e2e Test suite as it fails with below step

FAIL github.com/argoproj/argo/test/e2e 900.209s
? github.com/argoproj/argo/test/e2e/fixtures [no test files]
FAIL

Below is the log 
[e2e-test.txt](https://github.com/argoproj/argo/files/4593979/e2e-test.txt)

**Comment by alexec** [comment]
v2.7 is end of life now.
