### ISSUE TITLE
Logs UI is very CPU heavy

### ISSUE THREAD

**Issue by logicfox** [argoproj/argo#2946]
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [ ] I've included the workflow YAML.
 * [ ] I've included the logs.
 
**What happened**:
The logs view in the UI appears to be CPU heavy. When I view the logs view open to keep track of logs for a long running step, I can feel my laptop get noticably warm and the fans spin up. Chrome's task manager indicates that the CPU usage is spiking up to 100%. Apologies for the poor screenshot. 
<img width="674" alt="Argo logs UI CPU usage" src="https://user-images.githubusercontent.com/2287019/81008033-86e77680-8e52-11ea-981f-34fedce45fc8.png">

**What you expected to happen**:
Logs view should not hog CPU usage

**How to reproduce it (as minimally and precisely as possible)**:
Navigate to the logs view of a workflow, leave it open and observe the CPU usage for the tab in Chrome's task manager. Also notice the machine exhibit typical high CPU usage behaviour.

**Environment**:

- Argo version: 2.7.5

- Kubernetes version : 1.14.8/AKS

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by sorenvind** [comment]
This happens consistently for me. It may take a couple of minutes before it reaches 100%, but already initially it hovers around 25% cpu usage.

**Comment by alexec** [comment]
@dtaniwaki we merged your change to master in the last couple of days, ie. after v2.7.5? Could that help do you think?

**Comment by dtaniwaki** [comment]
I believe [the logs viewer improvement](https://github.com/argoproj/argo/pull/2825) has not been deployed as of v2.7.6. I'm not sure what caused this problem, but I'll take a look. 👍

**Comment by dtaniwaki** [comment]
I compared `v2.7.6` and the master at `e3ed686e13eacf0174b3e1088fe3cf2eb7706b39` of the CLI and run the following manifest.

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: colored-logs-
spec:
  entrypoint: whalesay
  templates:
  - name: whalesay
    script:
      image: python:3.7
      command: ["python"]
      source: |
        import time
        import random

        messages = [
            'No Color',
            '\x1b[30m%s\x1b[0m' % 'FG Black',
            '\x1b[32m%s\x1b[0m' % 'FG Green',
            '\x1b[34m%s\x1b[0m' % 'FG Blue',
            '\x1b[36m%s\x1b[0m' % 'FG Cyan',
            '\x1b[41m%s\x1b[0m' % 'BG Red',
            '\x1b[43m%s\x1b[0m' % 'BG Yellow',
            '\x1b[45m%s\x1b[0m' % 'BG Magenta',
        ]
        for i in range(1, 100000):
          print(random.choice(messages))
          time.sleep(0.1)
      env:
      - name: PYTHONUNBUFFERED
        value: '1'
```

After 30 seconds, I checked the task manager of Chrome and found CPU usage increases differ as below.

<img width="765" alt="Screen Shot 2020-05-05 at 2 38 24 PM" src="https://user-images.githubusercontent.com/1162120/81037552-184ffa80-8ede-11ea-88c6-aede8a35b06d.png">

The first row is the master and the second is `v2.7.6`.

I also checked the old viewer was rendering all the tailed logs even if most of them are not visible. I think this problem will be solved in the new logs viewer. Could you try newer versions once they get available?

**Comment by alexec** [comment]
Fixed by the sound of it.

**Comment by logicfox** [comment]
@alexec Has this been released? I noticed that the colored logs example @dtaniwaki mentioed above is only in the master.
