### ISSUE TITLE
Workflow UI params dont work when params are part of a workflow template

### ISSUE THREAD

**Issue by samirmajen** [argoproj/argo#2948]
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [x] I've included the workflow YAML.
 * [ ] I've included the logs.
 
**What happened**:

https://github.com/argoproj/argo/pull/2030 introduced new functionality to provide a UI to enter parameters. This UI works fine if the workflow arguments are defined as part of the workflow but fails to work if the arguments are part of a template inside templateRef. 

**What you expected to happen**:

Selecting a parameter defined under templateRef should provide the same functionality as selecting a parameter for a workflow.

**How to reproduce it (as minimally and precisely as possible)**:

Working: https://github.com/argoproj/argo/blob/master/examples/parallelism-nested-workflow.yaml

Not working: https://github.com/argoproj/argo/blob/master/examples/workflow-template/hello-world.yaml

**Anything else we need to know?**:

**Environment**:

- Argo version: v.2.7.4
```
$ argo version
```
- Kubernetes version : 1.18
```
$ kubectl version -o yaml
```

**Other debugging information (if applicable)**:

- workflow result:

```
argo --loglevel DEBUG get <workflowname>
```

- executor logs:

```
kubectl logs <failedpodname> -c init
kubectl logs <failedpodname> -c wait
```

- workflow-controller logs:

```
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name)
```

**Logs**

```
argo get <workflowname>
kubectl logs <failedpodname> -c init
kubectl logs <failedpodname> -c wait
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name)
```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by simster7** [comment]
This feature is only for Workflow-level parameters. I.e. parameters under `Workflow.spec.parameters`. It currently does not support template-level parameters (`Workflow.spec.templates.parameters`).

The idea is that only these top-level parameters should be specified by the user and all of the parameters within the Workflow should be set at runtime.

What is the use case that caused you to want this feature? You should be able to simply specify a Workflow-level parameter to pass in to whatever value you wanted to change originally.

**Comment by samirmajen** [comment]
passing the worklow level parameter works, thanks
