### ISSUE TITLE
[UI] Use production build instead dev

### ISSUE THREAD

**Issue by MaksimKiselev** [argoproj/argo#2953]
**What happened**:
UI was built for dev environment

**What you expected to happen**:
Build UI for production environment

**How to reproduce it (as minimally and precisely as possible)**:
Deploy UI somewhere and open console

**Anything else we need to know?**:
![image](https://user-images.githubusercontent.com/4495801/81091480-01be9900-8f08-11ea-8438-8ab9dd4bb4ef.png)

To fix it just add: `ENV NODE_ENV=production` to `Dockerfile` before run build command https://github.com/argoproj/argo/blob/master/Dockerfile#L76

https://github.com/argoproj/argo/blob/master/ui/src/app/webpack.config.js#L8

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by alexec** [comment]
This should be fixed in recent versions - what version are you using please?

**Comment by MaksimKiselev** [comment]
@alexec 2.7.2

**Comment by alexec** [comment]
Can you please try v2.7.7 and v2.8.0-rc4?

**Comment by MaksimKiselev** [comment]
**v2.7.7 still**
![image](https://user-images.githubusercontent.com/4495801/81319821-ea62e580-9098-11ea-8982-d5d8e297d237.png)

**v2.8.0-rc4 OK**
![image](https://user-images.githubusercontent.com/4495801/81320221-81c83880-9099-11ea-9c95-18e3500f54a0.png)

As I see it is already fixed here: https://github.com/argoproj/argo/commit/65d413e5d68b2f1667ef09f3c5938a07c3442fe8#diff-6559f21ee61b77fb6e0ed91c2df87162R9

@alexec thx
