### ISSUE TITLE
Support large parameters

### ISSUE THREAD

**Issue by youngjoonso1** [argoproj/argo#2969]
# Summary

We can pass [parameters](https://github.com/argoproj/argo/blob/master/examples/README.md#parameters) to workflows.
And, we usually use those parameters to set environment variables of each stage.

But, if the parameter is too large, we will get the following error:
```
Pod "xxxx-b7tfb-422045195" is invalid: metadata.annotations: Too long: must have at most 262144 characters
```

I would like to propose the way to pass big files as artifacts.

# Motivation

If I set the large parameters, when I trigger the workflow via Argo HTTP API,
it seems the global parameter is passed well:
```
$ argo get xxxx-b7tfb

Parameters:
  id-list: 12532532463,321532654326,253265326235, ....
```
But, when Argo tries to run the stage in the step, it gets the error.
```
Pod "xxxx-b7tfb-422045195" is invalid: metadata.annotations: Too long: must have at most 262144 characters
```

I've also tried to use the [global artifact](https://github.com/argoproj/argo/blob/master/examples/arguments-artifacts.yaml) feature with the [raw input data](https://github.com/argoproj/argo/blob/master/examples/input-artifact-raw.yaml), but it was caused the same error: `Too long: must have at most 262144 characters`.

# Proposal

I would like to propose the way to pass big files as artifacts.
```
argo submit my.yaml \
  -p param1=value1 \
  -a artifact1=/tmp/big.csv
```
For that, I guess Argo CLI should be able to upload files to the artifact storage.
Also, Argo HTTP API should get files via multiparts, and uploads them to the artifacts storage.

Then, each stage can access the global artifact like below:
```yaml
- name: my-workflow
  steps:
  - - name: my-stage
      template: my-stage-tmpl
      arguments:
        artifacts:
        - name: my-big-file
          from: "{{workflow.artifacts.artifact1}}"
```

I'm also willing to make a PR for this proposal, if it's feasible.
Thank you for reading my proposal.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by simster7** [comment]
To clarify, the only functionality you're requesting is that we enable artifact passing from the CLI?

**Comment by youngjoonso1** [comment]
> To clarify, the only functionality you're requesting is that we enable artifact passing from the CLI?

I hope Argo HTTP API also can have the artifact passing feature, because many users trigger Argo workflow via HTTP API.
