### ISSUE TITLE
Could you show me an example of CronWorkflow together with DAG?

### ISSUE THREAD

**Issue by AndreiBrajnicov** [argoproj/argo#2970]
Hello. I would like to setup a cronworkflow together with DAG conditions.
Could you tell me if it is supported?

Unfortunately you don't have such examples, and I wasn't able to create a working one.

**Comment by simster7** [comment]
You can convert any `Workflow` into a `CronWorkflow`, including those that use DAGs. Take a look at the instructions in: https://github.com/argoproj/argo/blob/master/docs/cron-workflows.md
