### ISSUE TITLE
OpenAPI definition for io.argoproj.workflow.v1alpha1.ScriptTemplate missing "metadata" field

### ISSUE THREAD

**Issue by jbehling** [argoproj/argo#2996]
Checklist:

 * [x] I've included the version. master
 * [x] I've included reproduction steps.
 * [x] I've included the workflow YAML.
 * [x] I've included the logs.
 
**What happened**:
The definition for  io.argoproj.workflow.v1alpha1.ScriptTemplate is missing the "metadata" field. This means that https://github.com/CermakM/argo-client-python (which uses the apispec to generate the models) cannot create script templates that add pod metadata like in this example https://github.com/argoproj/argo/blob/master/examples/pod-metadata.yaml

**What you expected to happen**:
I would expect the definition to include all valid fields

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Argo version:
master
- Kubernetes version :

**Other debugging information (if applicable)**:

- workflow result:

```
argo --loglevel DEBUG get <workflowname>
```

- executor logs:

```
kubectl logs <failedpodname> -c init
kubectl logs <failedpodname> -c wait
```

- workflow-controller logs:

```
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name)
```

**Logs**

```
argo get <workflowname>
kubectl logs <failedpodname> -c init
kubectl logs <failedpodname> -c wait
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name)
```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by simster7** [comment]
@alexec Seems like another `inline` issue

**Comment by alexec** [comment]
I don't think `io.argoproj.workflow.v1alpha1.ScriptTemplate` has meta-data.
