### ISSUE TITLE
IDE tooling?

### ISSUE THREAD

**Issue by brabster** [argoproj/argo#3022]
# Summary

This is probably the wrong project, but it's a place to start!

It would be great to get some IDE tooling in place for workflow authoring. See https://argoproj.slack.com/archives/C8J6SGN12/p1589298816385200 for context.

# Motivation

It's hard to keep track of what's going on in a non-trivial Argo workflow without some tool support. Current feedback loop for me is typically mistyping -> lint -> error -> search through files -> correct typo
From Sam Elder: "The number of times I've typed `{{inputs.paraemters.X}}`..."

# Proposal

I would like VSCode tooling. Maybe start to collect up a list of useful features (like autocomplete string expressions involving `inputs.parameters`) and see if someone/we can figure out how to implement.

I'm not exactly sure what's involved but I suspect a good approach would be to write a language server, that could perhaps be written in Go and use some of the existing code.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by mac9416** [comment]
#859 would help with this for Intellij. It might also help for VSCode, but I'm not sure. https://github.com/Azure/vscode-kubernetes-tools/pull/583
