### ISSUE TITLE
Define entrypoint as a dag step

### ISSUE THREAD

**Issue by alex-lipkin-create** [argoproj/argo#3028]
Hi,

is it possible to define an entrypoint as a step in a dag?
Let assume I have following workflow

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dag-test-
spec:
  entrypoint: dag
  templates:
  - name: echo
    inputs:
      parameters:
      - name: message
    container:
      image: alpine:3.7
      command: [echo, "{{inputs.parameters.message}}"]
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [sh, -c]
      args: ["cowsay hello"]
  - name: dag
    dag:
      tasks:
      - name: A
        template: echo
        arguments:
          parameters: [{name: message, value: A}]
      - name: B
        dependencies: [A]
        template: echo
        arguments:
          parameters: [{name: message, value: B}]
      - name: C
        dependencies: [B]
        template: echo
        arguments:
          parameters: [{name: message, value: C}]
      - name: D
        dependencies: [C]
        template: echo
        arguments:
          parameters: [{name: message, value: D}]

Is it possible during submission to define that I would like to start from step C?

Thanks
Alex

**Comment by simster7** [comment]
Yes. You can do so in two ways:

1. Any task without a dependency is automatically considered an entrypoint and will be run as soon as the DAG begins.

2. You can use the `dag.target` field to set this

**Comment by alex-lipkin-create** [comment]
Hi Simon,

thanks a lot for a quick response.

If understand correctly with target parameter I can define till which step dag should be executed.
I would like to define with which step it should start.

So in my examle modified example
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dag-test-
spec:
  entrypoint: dag
  arguments:
    parameters:
    - name: target
      value:  B
  templates:
  - name: echo
    inputs:
      parameters:
      - name: message
    container:
      image: alpine:3.7
      command: [echo, "{{inputs.parameters.message}}"]
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [sh, -c]
      args: ["cowsay hello"]
  - name: dag
    dag:
      target: "{{workflow.parameters.target}}"
      tasks:
      - name: A
        template: echo
        arguments:
          parameters: [{name: message, value: A}]
      - name: B
        dependencies: [A]
        template: echo
        arguments:
          parameters: [{name: message, value: B}]
      - name: C
        dependencies: [B]
        template: echo
        arguments:
          parameters: [{name: message, value: C}]
      - name: D
        dependencies: [C]
        template: echo
        arguments:
          parameters: [{name: message, value: D}]

I can provide with target parameter for instance , that A and B shold be executed like this.
argo submit --watch dag_entrypoint.yaml -p target="B"

So workflow will stop on B.

But how I can define that B C D should be executed and A skipped?

Thanks,
Alex

**Comment by alex-lipkin-create** [comment]
There is no feature for defining start step in the dag. But condionals may be used to skip stepts that are not required.

For instance like following:

apiVersion: argoproj.io/v1alpha1
kind: Workflow
 metadata:
 generateName: dag-test-
 spec:
 entrypoint: dag
 arguments:
 parameters:
 - name: target
 value: B
 templates:
•name: echo
 inputs:
 parameters: ◦name: message
 container:
 image: alpine:3.7
 command: [echo, "{{inputs.parameters.message}}"]

•name: whalesay
 container:
 image: docker/whalesay:latest
 command: [sh, -c]
 args: ["cowsay hello"]
•name: dag
 dag:
 target: "{{workflow.parameters.target}}"
 tasks: ◦name: A
 template: echo
 arguments:
 parameters: [{name: message, value: A}]
◦name: B
 dependencies: [A]
 template: echo
 arguments:
 parameters: [{name: message, value: B}]
◦name: C
 dependencies: [B]
 template: echo
 arguments:
 parameters: [{name: message, value: C}]
◦name: D
 dependencies: [C]
 template: echo
 arguments:
 parameters: [{name: message, value: D}]


depending on the start parameter for instance argo submit --watch dag_entrypoint.yaml -p start-point=3 we can choose the entrypoint.
