### ISSUE TITLE
Metrics should display controller error counts by type

### ISSUE THREAD

**Issue by Syps** [argoproj/argo#3034]
# Summary

Workflow Controller should be able to emit a Prometheus metric when an error occurs when trying to execute a CronWorkflow.

# Motivation

Currently, when a workflow controller encounters an error when resolving parameters for executing a cron workflow, the error will be logged to stdout but otherwise there is no way to be made aware of this failure.

If the workflow controller was able to emit a Prometheus event when this occurs, users could better handle this case (such as creating an alert).

# Proposal

How do you think this should be implemented?
Assuming metrics can be emitted from the controller, then emit an additional metric in the error case when executing CWF (not sure of more specific implementation details)

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by simster7** [comment]
There are two issues within this issue.

1. There is currently no way to see the status of a `CronWorkflow` except looking at the logs. This should be fixed independently of any metrics being emitted. I have opened https://github.com/argoproj/argo/issues/3036 to track this issue.

2. We should emit metrics when the controller has certain errors, including but not limited to an error when operating on a `CronWorkflow`. I have edited this issue to track this problem.

**Comment by Syps** [comment]
Implementation-wise, how do you think the controller should add these new metrics? Should it upsert a custom metric to Metrics Collector, or should the Metrics type be expanded to hold an additional Counter for workflow-controller errors?

**Comment by simster7** [comment]
Hey @Syps, sorry for the delay. Opened https://github.com/argoproj/argo/pull/3144 to fix

**Comment by Syps** [comment]
Awesome, thanks @simster7 !
