### ISSUE TITLE
Set int64 Fields with Parameters

### ISSUE THREAD

**Issue by dtaniwaki** [argoproj/argo#3041]
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [x] I've included the workflow YAML.
 * [ ] I've included the logs.
 
**What happened**:

I wanted to set `runAsUser` and `runAsGroup` with parameters in a workflow, but they're not possible because parameters are string while those fields are int64.

```
$ argo lint workflow.yaml
WARN[0000] hoge.yaml failed to parse: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go struct field PodSecurityContext.spec.templates.securityContext.runAsGroup of type int64
FATA[0000] Invalid workflow/workflows found
```

**What you expected to happen**:

Convert non-string values to match the field types.

**How to reproduce it (as minimally and precisely as possible)**:

```
$ cat workflow.yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: int-parameter-
spec:
  entrypoint: main
  arguments:
    parameters:
    - name: uid
  templates:
  - name: main
    container:
      name: main
      image: ubuntu:18.04
    securityContext:
      runAsUser: "{{workflow.parameters.uid}}"
      runAsGroup: "{{workflow.parameters.uid}}"
```

**Anything else we need to know?**:

N/A

**Environment**:

- Argo version:
```
$ argo version
argo: v2.7.6+70facdb.dirty
  BuildDate: 2020-04-28T17:09:06Z
  GitCommit: 70facdb67207dbe115a9029e365f8e974e6156bc
  GitTreeState: dirty
  GitTag: v2.7.6
  GoVersion: go1.13.4
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :

N/A

**Other debugging information (if applicable)**:

- workflow result:

N/A

- executor logs:

N/A

- workflow-controller logs:

N/A

**Logs**

N/A

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by dtaniwaki** [comment]
I realized the error occurred on the client-side when it's unmarshalled to a `Workflow` object. As we use `RunAsUser` of `PodSecurityContext` in my example, it is not possible to keep placeholders in a manifest.

Here're my 2 ideas to solve this problem and pros and cons.
1. Use a custom structure instead of `PodSecurityContext`.

Pros:
No change in the user-side operations.

Cons:
Hard to track corresponded structure changes to Kubernetes upstream.

2. Client-side parameters (like [envsubst](https://linux.die.net/man/1/envsubst))

Pros:
We can use parameters on any field without caring for the field type.

Cons:
We need another flag over `--parameter` maybe, something like `--client-parameter`.

**Comment by dtaniwaki** [comment]
I found it can be solved by adding `podSpecPatch: '{"securityContext": {"runAsUser": {{workflow.parameters.uid}}, "runAsGroup": {{workflow.parameters.uid}}}}'`.

**Comment by iven** [comment]
I think this issue should be reopened, as there's no solution right now, only workarounds.
I'm trying to set `activeDeadlineSeconds` in Argo Workflow, and also meet this problem. It's too complicated to represent the entire structure as JSON, as the workaround said above.

**Comment by alexec** [comment]
@iven I think a new issue is in order - one to support templating for non-strig fields. Could you like to open it?

**Comment by iven** [comment]
Added #4571.
