### ISSUE TITLE
bug: `argoexec` sometimes panics when waiting for a docker:dind sidecar to exit

### ISSUE THREAD

**Issue by justenwalker** [argoproj/argo#3053]
**What happened**:

There appears to be a Go panic in `argoexec` when the `wait` container terminates a heavily-used `docker:dind` side-car. It happens a lot to me, but not **every** time.

**What you expected to happen**:

`argoexec` should ideally not panic; but at least it should log it.

**How to reproduce it (as minimally and precisely as possible)**:

Still trying to get a minimal test-case I can share, but see below for the use-case.
Reproducing this is difficult, since it requires a special setup and it happens somewhat reliably but it doesn't reproduce 100% of the time.

Here is an example of the workflow template with identifying information removed.

[workflow.yaml](https://github.com/argoproj/argo/files/4645894/example-workflow.yaml.txt)

**Anything else we need to know?**:

For some background — I’m using `docker:dind` and [KinD](https://kind.sigs.k8s.io/) to spin up a k8s cluster to perform integration tests on our custom k8s controllers. After the tests run, my otherwise successful workflow will often-times get marked as an Error with `failed to save outputs: verify serviceaccount argo:default has necessary privileges`. However, the job has no outputs to save, and the `argo:default` service account has a rolebinding `ClusterRole/admin`.

Looking a bit further into the issue, when it happens; the `wait` container terminates with `"exitCode": 2`:

```json
    {
      "containerID": "docker://4dbbbe3e7431a4fa53c109cd9e197fb7ac25aa17978c32b2619ee85edda9bf30",
      "image": "argoproj/argoexec:v2.8.0",
      "imageID": "docker-pullable://argoproj/argoexec@sha256:9eb71f2dae8405d8c053d5beccce15ecf179448ad0809d9f55f1333bf1d71a01",
      "lastState": {},
      "name": "wait",
      "ready": false,
      "restartCount": 0,
      "state": {
        "terminated": {
          "containerID": "docker://4dbbbe3e7431a4fa53c109cd9e197fb7ac25aa17978c32b2619ee85edda9bf30",
          "exitCode": 2,
          "finishedAt": "2020-05-18T17:49:17Z",
          "reason": "Error",
          "startedAt": "2020-05-18T17:31:52Z"
        }
      }
    }
```

As far as I can tell, there is no code in Argo that explicitly exits with this code; however, there is documentation in the [Go runtime Package](https://golang.org/pkg/runtime/):

> By default, a failure prints a stack trace for the current goroutine, eliding functions internal to the run-time system, and then exits with exit code 2.

Unfortunately, there is no stacktrace to be found in the wait log, so something seems to be hiding it; but it seems to happen after `[docker wait {ID}]`

In the rare cases where the issue does not reproduce, the `wait` container yields some additional logs past the `[docker wait {ID}]` message, indicating that it successfully ran the docker wait command:

```plain_text
time="2020-05-16T00:33:18Z" level=info msg="Main container completed"
time="2020-05-16T00:33:18Z" level=info msg="No output parameters"
time="2020-05-16T00:33:18Z" level=info msg="No output artifacts"
time="2020-05-16T00:33:18Z" level=info msg="No Script output reference in workflow. Capturing script output ignored"
time="2020-05-16T00:33:18Z" level=info msg="Capturing script exit code"
time="2020-05-16T00:33:18Z" level=info msg="[docker inspect 2f929e8444e9f9405b3e05b8fb484f769c2abf227dd24667e980c04829b89dc1 --format='{{.State.ExitCode}}']"
time="2020-05-16T00:33:18Z" level=info msg="Containers [2f929e8444e9f9405b3e05b8fb484f769c2abf227dd24667e980c04829b89dc1] killed successfully"
time="2020-05-16T00:33:18Z" level=info msg="Annotating pod with output"
time="2020-05-16T00:33:18Z" level=info msg="Killing sidecars"
time="2020-05-16T00:33:18Z" level=info msg="Killing sidecar docker-daemon (a390618204fa2f59352e1ebf896652824617b8e8a5c4bc2450c98a764cc880dc)"
time="2020-05-16T00:33:18Z" level=info msg="docker kill --signal TERM a390618204fa2f59352e1ebf896652824617b8e8a5c4bc2450c98a764cc880dc"
time="2020-05-16T00:33:18Z" level=info msg="[docker wait a390618204fa2f59352e1ebf896652824617b8e8a5c4bc2450c98a764cc880dc]"
------------- This is where the logging would stop in the "Error" case -------------
time="2020-05-16T00:33:20Z" level=info msg="Containers [a390618204fa2f59352e1ebf896652824617b8e8a5c4bc2450c98a764cc880dc] killed successfully"
time="2020-05-16T00:33:20Z" level=info msg="Alloc=5968 TotalAlloc=12210 Sys=71104 NumGC=4 Goroutines=9"
```

I was able to work around this issue by running 

```shell
docker ps --format="{{ .ID }}" | xargs docker kill
docker ps -a --format="{{ .ID }}" | xargs docker rm
```

In my main container before exiting. I suspect only the `docker kill` one is necessary though.

**Environment**:

* Argo version:

    ```shell
    $ argo version
    argo: v2.8.0
    BuildDate: 2020-05-11T22:55:16Z
    GitCommit: 8f696174746ed01b9bf1941ad03da62d312df641
    GitTreeState: clean
    GitTag: v2.8.0
    GoVersion: go1.13.4
    Compiler: gc
    Platform: linux/amd64
    ```

* Kubernetes version :

    ```shell
    $ kubectl version -o yaml
    clientVersion:
    buildDate: "2019-12-07T21:20:10Z"
    compiler: gc
    gitCommit: 70132b0f130acc0bed193d9ba59dd186f0e634cf
    gitTreeState: clean
    gitVersion: v1.17.0
    goVersion: go1.13.4
    major: "1"
    minor: "17"
    platform: linux/amd64
    ```

**Other debugging information (if applicable)**:

* workflow result:

    ```shell
    $ argo --loglevel DEBUG get docker-kind-tester-2nvpp
    Name:                docker-kind-tester-2nvpp
    Namespace:           argo
    ServiceAccount:      default
    Status:              Error
    Message:             failed to save outputs: verify serviceaccount argo:default has necessary privileges
    Created:             Mon May 18 17:31:47 +0000 (17 minutes ago)
    Started:             Mon May 18 17:31:47 +0000 (17 minutes ago)
    Finished:            Mon May 18 17:49:29 +0000 (12 seconds ago)
    Duration:            17 minutes 42 seconds

    STEP                          TEMPLATE  PODNAME                    DURATION  MESSAGE
    ⚠ docker-kind-tester-2nvpp  tester    docker-kind-tester-2nvpp  17m       failed to save outputs: verify serviceaccount argo:default has necessary privileges
    ```

**Logs**

* [workflow-controller.log](https://github.com/argoproj/argo/files/4645886/workflow-controller.log)
* [wait.log](https://github.com/argoproj/argo/files/4645887/wait.log)
* [init.log](https://github.com/argoproj/argo/files/4645889/init.log)
---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by alexec** [comment]
We have two facts here:

* `argoexec` panicked - inferred from exit code 2
* It failed a permission check at the some time.

Correct?

**Comment by justenwalker** [comment]
Fact 1 is correct. I'm not sure if fact 2 is correct. The service account has has admin permissions so it would be unlikely that it would fail a permission check; But the error message does say:

```failed to save outputs: verify serviceaccount argo:default has necessary privileges```

So it's difficult to tell. I saw a previous issue say that this message is somewhat confusing/generic (See #982)

**Comment by sarabala1979** [comment]
I didn't see any error on wait.log. is it the right one?

**Comment by justenwalker** [comment]
I have a hunch it is a race with the timer func; although I don't really have hard evidence. I say this because there does appear to be a race to set the `err` var.
-  https://github.com/argoproj/argo/blob/e0ad7de97a82b2e509bb4bc8bb5fcf5b9c26dea3/workflow/executor/docker/docker.go#L209
-  https://github.com/argoproj/argo/blob/e0ad7de97a82b2e509bb4bc8bb5fcf5b9c26dea3/workflow/executor/docker/docker.go#L214

This would explain why killing all the docker containers helped, since it alters the timing.

Maybe if there was an Argo build with race-detector enabled we could know for sure.

**Comment by alexec** [comment]
This should be investigated.

**Comment by justenwalker** [comment]
See #4097 for a possible fix for the race condition. Not 100% sure if this will fix this issue, but I'm pretty confident it will - worst case it eliminates a known data race.
