### ISSUE TITLE
Cannot see logs in argo UI

### ISSUE THREAD

**Issue by yeya24** [argoproj/argo#3065]
Checklist:

 * [X] I've included the version.
 * [ ] I've included reproduction steps.
 * [x] I've included the workflow YAML.
 * [X] I've included the logs.
 
**What happened**:

Unable to view the workflow logs in the argo UI.

![image](https://user-images.githubusercontent.com/25150124/82509438-e477f600-9ad5-11ea-8287-fc0e96ad6c4f.png)

![image](https://user-images.githubusercontent.com/25150124/82509450-ed68c780-9ad5-11ea-927b-3e177ef9a1fb.png)

**What you expected to happen**:

I am not sure whether this is expected or not. But when I check the logs of `argo-server` I find some error messages.

```
time="2020-05-21T00:08:00Z" level=error msg="finished streaming call with code Unknown" error="context canceled" grpc.code=Unknown grpc.method=WatchWorkflows grpc.service=workflow.WorkflowService grpc.start_time="2020-05-21T00:07:46Z" grpc.time_ms=14261.373 span.kind=server system=grpc
time="2020-05-21T00:08:00Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=GetInfo grpc.service=info.InfoService grpc.start_time="2020-05-21T00:08:00Z" grpc.time_ms=0.045 span.kind=server system=grpc
2020/05/21 00:08:05 proto: tag has too few fields: "-"
time="2020-05-21T00:08:05Z" level=error msg="parsing time \"unable\" as \"2006-01-02T15:04:05Z07:00\": cannot parse \"unable\" as \"2006\"" namespace=argo podName=tipocket-bank-replica-read-4tr4h-2269954769 workflow=tipocket-bank-replica-read-4tr4h
time="2020-05-21T00:08:05Z" level=info msg="finished streaming call with code OK" grpc.code=OK grpc.method=PodLogs grpc.service=workflow.WorkflowService grpc.start_time="2020-05-21T00:08:05Z" grpc.time_ms=27.859 span.kind=server system=grpc
time="2020-05-21T00:10:10Z" level=error msg="parsing time \"unable\" as \"2006-01-02T15:04:05Z07:00\": cannot parse \"unable\" as \"2006\"" namespace=argo podName=tipocket-bank-replica-read-4tr4h-2269954769 workflow=tipocket-bank-replica-read-4tr4h
time="2020-05-21T00:10:10Z" level=info msg="finished streaming call with code OK" grpc.code=OK grpc.method=PodLogs grpc.service=workflow.WorkflowService grpc.start_time="2020-05-21T00:10:10Z" grpc.time_ms=19.054 span.kind=server system=grpc
```

Also I can see the logs of my workflow pod in the minio.

![image](https://user-images.githubusercontent.com/25150124/82509713-ad561480-9ad6-11ea-9fb1-065d9e2dd1ea.png)

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Argo version:
```
2.8.0
```
- Kubernetes version :
```
1.17.0
```

**Other debugging information (if applicable)**:

- workflow result:

```
 └---⚠ call-tipocket-scbank          tipocket-scbank/tipocket-scbank  tipocket-bank-replica-read-4tr4h-2269954769  1d        failed to save outputs: path /var/run/tipocket-logs does not exist in archive /tmp/argo/outputs/artifacts/tidb-logs.tgz
```

- workflow yaml:

This is the example workflow template I use. I configured an output artifact `tidb-logs` here.

```
name: tipocket-scbank
arguments: {}
inputs:
    parameters:
      xxx: xxx
outputs:
    artifacts:
        - name: tidb-logs
            path: /var/run/tipocket-logs
            archiveLogs: true
```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by yeya24** [comment]
I just tested this with another workflow again, seems even the workflow is succeded, this problem is still reproducible.

![image](https://user-images.githubusercontent.com/25150124/82510367-55b8a880-9ad8-11ea-8ab0-005ce9bf7e21.png)

![image](https://user-images.githubusercontent.com/25150124/82510380-5ea97a00-9ad8-11ea-8675-cf979723261a.png)

![image](https://user-images.githubusercontent.com/25150124/82510403-679a4b80-9ad8-11ea-99d6-3620d2be69ce.png)

But I can see the artifacts when I click `ARTIFACTS`

![image](https://user-images.githubusercontent.com/25150124/82510440-87ca0a80-9ad8-11ea-97fe-4afb8fad0dae.png)

**Comment by simster7** [comment]
Will take a look. Thanks for the detailed bug report!

**Comment by alexec** [comment]
Do you have PodGC enabled?

**Comment by yeya24** [comment]
I don't set `PodGC`.

**Comment by simster7** [comment]
Could you include a minimal Workflow to reproduce?

**Comment by simster7** [comment]
@alexec I see this may be your area of expertise, so feel free to take this over if you'd like. Just let me know.

**Comment by simster7** [comment]
These lines look to be the problem:

https://github.com/argoproj/argo/blob/5b5bae9a6e46a82f5830f68f87598ee0c7dc2ff7/util/logs/workflow-logger.go#L97-L101

We might need better error handling here

**Comment by simster7** [comment]
Opened #3071 to fix

**Comment by simster7** [comment]
While #3071 fixes our strict error handling, the root cause of the issue seems to come from the decoding stage of the watch (these are the only errors that begin with "unable" in this scope).

https://github.com/kubernetes/client-go/blob/7ab8430bef2c3a2dac4002a48f714b0557379cd7/rest/watch/decoder.go#L47-L67

@yeya24 Do your log outputs contain unusual character formatting? If you could provide the logs that your pod outputs it might make this easier to reproduce.

**Comment by yeya24** [comment]
Thanks for the help ❤️. I am not sure whether I have time to investigate this today. I will try to reproduce this again and give you more information.

**Comment by alexec** [comment]
@simster7 good work - please own.
