### ISSUE TITLE
Where is the implementation of the ServerHttp and Hash methods in the static.go file?

### ISSUE THREAD

**Issue by tincopper** [argoproj/argo#3070]
# Summary
What do you want to know about this project?
First of all, I'm sorry to ask such a basic question. When I was debugging the source code, I found that ServerHttp and Hash were reporting errors on my ide in the file `github.com/argoproj/argo/server/static/static.go`, I found that the implementation of ServerHttp and Hash methods could not be found. Where is the implementation?

```
func (s *FilesServer) ServerFiles(w http.ResponseWriter, r *http.Request) {
	// If there is no stored static file, we'll redirect to the js app
	if Hash(strings.TrimLeft(r.URL.Path, "/")) == "" {
		r.URL.Path = "index.html"
	}
	if r.URL.Path == "index.html" {
		// hack to prevent ServerHTTP from giving us gzipped content which we can do our search-and-replace on
		r.Header.Del("Accept-Encoding")
		w = &responseRewriter{ResponseWriter: w, old: []byte(`<base href="/">`), new: []byte(fmt.Sprintf(`<base href="%s">`, s.baseHRef))}
	}
	// in my IDE (IntelliJ) the next line is red for some reason - but this is fine
	ServeHTTP(w, r)
}
```
# Motivation
I want to know more about this framework.

**Comment by alexec** [comment]
This code is generated using `staticfiles`. This tool creates a `staticifiles.go`. Look at the `Makefile` for details.

**Comment by tincopper** [comment]
Thank you for your answer!
