### ISSUE TITLE
PVC GC Policy

### ISSUE THREAD

**Issue by dcherman** [argoproj/argo#3095]
# Summary

Similar to `PodGC`, can we consider implementing `VolumeGC` which would allow users to customize whether or not PVCs are retained on failed / errored workflows?  Right now, volumes are never deleted when a Workflow fails or errors.

# Motivation

There are a lot of scenarios where if a given workflow fails, you may choose to never retry or re-submit it, or retrying the workflow would require recreation of the contents of the volume anyway.  In those scenarios, it doesn't make sense to continue paying the cost for the volumes if they're provisioned using something like EBS which charges per GB/mo.

# Proposal

How do you think this should be implemented?

New proposed workflow field:

```yaml
  volumeGC: OnWorkflowCompletion | OnWorkflowSuccess
```

In order to make this a non-breaking change, the default value for `volumeGC` would be `OnWorkflowSuccess` which matches the behavior that exists today.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by alexec** [comment]
See #2771

**Comment by dcherman** [comment]
Cool, I'll keep an eye on that PR.  If it stalls for any reason, I'd be happy to make this contribution.

**Comment by dcherman** [comment]
Copying a thread from slack:

Daniel Herman Aug 1st at 1:05 PM
@jesse When you're around, any chance you could take a look at https://github.com/argoproj/argo/issues/1819 to give your opinion?  I'm working on a PR for https://github.com/argoproj/argo/issues/3095 and am running into that

#3095 PVC GC Policy
<https://github.com/argoproj/argo|argoproj/argo>argoproj/argo | May 23rd | Added by GitHub
4 replies

Daniel Herman  2 days ago
Basically, what's happening is that the PVC has the pvc-protection finalizer applied to it by the PVCProtectionController in k8s - that finalizer is only removed when no pods are referencing the PVC

Daniel Herman  2 days ago
A pod being completed does not fulfill that requirement - only a pod that has the DeletionTimestamp set (i.e. it's being deleted) does (or no pods exist that reference the PVC of course)

Daniel Herman  2 days ago
That would mean that a VolumeGC feature would only be valid if we either documented that you had to combine it with PodGC, or we removed the finalizer ourselves since the workflow does own the PVC

Daniel Herman  2 days ago
Could also argue that the PVC Protection Controller should consider Completed pods as ones that should fulfill their requirement, though I don't know what implications that might have

**Comment by dcherman** [comment]
Definitely will need some input on how you'd like to proceed here.  The options as I see them are:

1.  Document that VolumeGC will need to be used in combination with PodGC
2.  Remove the `kubernetes.io/pvc-protection` finalizer ourselves when we intend to GC a volume, even if the pod still exists in a `Completed` or `Error` state.
3.  Try to make a case that the `PVCProtectionController` should consider `Error/Completed` pods as having released their claim on the PVC.  I don't know what implications that might have.
    * https://github.com/kubernetes/kubernetes/blob/ec560b9737537be8c688776461bc700e8ddedb9d/pkg/controller/volume/pvcprotection/pvc_protection_controller.go#L313-L346
    * https://github.com/kubernetes/kubernetes/blob/ec560b9737537be8c688776461bc700e8ddedb9d/pkg/controller/volume/pvcprotection/pvc_protection_controller.go#L266-L270

**Comment by dcherman** [comment]
@alexec @jessesuen Any opinions on the approach you'd like to take here given the previous couple of comments?

**Comment by tiwarisanjay** [comment]
Solution : https://argoproj.github.io/argo-workflows/environment-variables/#:~:text=ARGO_REMOVE_PVC_PROTECTION_FINALIZER
