### ISSUE TITLE
Inputs and outputs should be labelled in UI

### ISSUE THREAD

**Issue by foobarbecue** [argoproj/argo#3098]
# Summary

It should be obvious which items on the node details panel are inputs, and which are outputs.

# Motivation

In the attached image, there are two headers labelled "Artifacts". One refers to input artifacts, the other to output. Although an experienced user can tell the difference from context, this is unclear to a new user and makes the UI confusing.

![image](https://user-images.githubusercontent.com/854789/82769901-68d6bb80-9deb-11ea-9f17-8df568b39156.png)

# Proposal

A good start would be adding an "Inputs" label to the box that contains inputs.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by simster7** [comment]
@rbreeze

**Comment by rbreeze** [comment]
I'll take this one
