### ISSUE TITLE
Retain layout changes after page reloads in UI

### ISSUE THREAD

**Issue by theStrayPointer** [argoproj/argo#3120]
# Summary

Argo UI currently provides a few neat ways to modify the visual layout of the workflow(s) and filter steps/tasks. But changes are not retained following a page reload.

# Motivation

Especially for very large and complex workflows, UI customization actions become quite repetitive.

# Proposal

A simple save/load process using local storage may be sufficient.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by simster7** [comment]
I figured this would come up at some point. I'll take a look at this

**Comment by alexec** [comment]
This sounds specifically like the DAG display. 

This needs some polish. It'd be good to fix with #3092 and 3091.

**Comment by theStrayPointer** [comment]
Thank you.

**Comment by alexec** [comment]
> This needs some polish. It'd be good to fix with #3092 and #3091.

I'll fix #3091.
