### ISSUE TITLE
Filter by label with CLI

### ISSUE THREAD

**Issue by rbreeze** [argoproj/argo#3139]
# Summary

Allow filtering by label on the CLI.

# Motivation

On the UI, it's really easy to filter workflows by label. I couldn't find an equivalent with the CLI and I think it would be useful to have. 

# Proposal

A `--label` flag for `argo list`. 

Example: 
`argo list --label "workflows.argoproj.io/completed=true"`

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by sarabala1979** [comment]
this feature implemented in #3088 

`argo list -l `
