### ISSUE TITLE
Passing arguments to workflow inside a cronworkflow

### ISSUE THREAD

**Issue by manpreet1994** [argoproj/argo#3154]
# Summary

How can I pass arguments/parameters to a workflow running in a cronworkflow?

# Motivation
I'm working on a scenario where, a workflow which requires input parameters from env file, needs to be scheduled also.

**Comment by samath117** [comment]
My usual approach is to have the workflow load the input parameters from a file in my artifact repository, which I update when necessary.

**Comment by alexec** [comment]
@simster7 FYI
@samath117 do you have an example we could add to docs?

**Comment by samath117** [comment]
Nah, it's really just the same as the standard input artifact importing examples, like [this one](https://github.com/argoproj/argo/blob/master/examples/input-artifact-s3.yaml). You have to write a processing step to unpack those variables, and decide what process you want to write to that file (another CronWorkflow, manually-submitted Workflows, uploading directly, etc).

**Comment by manpreet1994** [comment]
@samath117 
Thanks for input. I'm using azure blob storage, however, it seems azure blob storage artifact is not supported yet. Any workarounds?

**Comment by samath117** [comment]
I'm not aware of any if S3 artifacts don't work for you. Others probably are better suited to answer that question, though.

**Comment by simster7** [comment]
FYI: Opened #3173 to add Azure Blob Storage

**Comment by manpreet1994** [comment]
@simster7 @samath117 
I used kubernetes secrets to achieve what i was looking for. (https://kubernetes.io/docs/concepts/configuration/secret/)

I created a secret from env file and referred this newly created secret from cronworkflow. 

It will be helpful if this can be added in the argo documentation

**Comment by omarzouk** [comment]
@alexec is there a design reason behind this not being supported in the CronWorkflow spec? Being able to pass parameters to a WorkflowTemplateRef sounds like a very reasonable way to use a template

**Comment by simster7** [comment]
@omarzouk It is possible to pass in parameters to a `WorkflowTemplateRef`. See this example: https://github.com/argoproj/argo/blob/master/examples/workflow-template/workflow-template-ref-with-entrypoint-arg-passing.yaml

**Comment by samath117** [comment]
Yes, but you can't set those parameters from the CLI in `argo cron create`. This seems like a reasonable suggestion to me, similar to #3194.

**Comment by simster7** [comment]
Ah I see. Yes, that is a reasonable request. Is this what you meant @omarzouk?

**Comment by omarzouk** [comment]
@simster7 I was actually referring to something like this: https://github.com/argoproj/argo/issues/2556#issuecomment-607452619

```
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: hello-world
spec:
  schedule: "* * * * *"
  workflowSpec:
    workflowTemplateRef:
      name: workflow-template-name
    arguments:
      parameters:
        - name: message
          value: "Hello, world"
```
but I guess this is coming out in 2.9 right?

however being able to pass them in the command line would be a good thing too!
