### ISSUE TITLE
Spark operator integration

### ISSUE THREAD

**Issue by surajrajan-maf** [argoproj/argo#3168]
From workflow, how do I invoke spark operator? (https://github.com/GoogleCloudPlatform/spark-on-k8s-operator)

currently, spark application is created via 
kubectl apply -f spark app.yaml

**Comment by duongnt** [comment]
We are just using the resource op to create the SparkApplication CRD. It's still a challenge to pass spark outputs back to argo though. I think spark operator isn't giving us much information about the spark job in the SparkApplication CRD itself, other than the job status (like failed or succeeded).

**Comment by alexec** [comment]
https://github.com/argoproj/argo/blob/master/docs/fields.md#resourcetemplate ?

**Comment by MuhammadZeeshan34** [comment]
Did anyone found a way to pass the outputs from spark operator to argo workflow?
