### ISSUE TITLE
protoc-gen-go/generator is deprecated

### ISSUE THREAD

**Issue by simster7** [argoproj/argo#3172]
`protoc-gen-go/generator` is part of the codegen process and is deprecated. 

```
WARNING: Package "github.com/golang/protobuf/protoc-gen-go/generator" is deprecated.
	A future release of golang/protobuf will delete this package,
	which has long been excluded from the compatibility promise.
```
https://github.com/golang/protobuf/blob/d04d7b157bb510b1e0c10132224b616ac0e26b17/protoc-gen-go/generator/generator.go#L5-L11

We should migrate to google.golang.org/protobuf/compiler/protogen as advised

**Comment by wreed4** [comment]
just ran into this issue today.. is there a reason this was closed?
