### ISSUE TITLE
Log during wk submit

### ISSUE THREAD

**Issue by hadim** [argoproj/argo#3183]
My current workflow to debug/develop an Argo workflow is to submit it, get its name, and execute `argo logs -f` to check the logs.

I do that very often during the early phases of the dev. It would be nice to have an option in `argo submit` to directly execute `argo logs -f` upon submission.

**Comment by hadim** [comment]
That feature would be similar as `docker-compose up` while the current default is similar to `docker-compose up -d`.

Note: I am looking for logs and not the `--watch` argument.

**Comment by simster7** [comment]
We're considering a related change in https://github.com/argoproj/argo/pull/3179. What do you think of

```
$ argo submit wf.yaml
$ argo logs -f --latest
```

or

```
$ argo submit wf.yaml && argo logs -f --latest
```
@rbreeze Please make sure `argo logs` is covered in #3179

**Comment by hadim** [comment]
`--latest` would be super useful indeed. A flag to `submit` for `argo logs -f --latest` would also a good addition but I guess it's more complicated.

**Comment by rbreeze** [comment]
@simster7 will do!

**Comment by iMoses** [comment]
Personally I'd like a flag on the submit command as well. especially when using `watch` it'd be nice to get the logs there as well :)

```
$ argo submit --watch --show-logs workflow.yaml
```

**Comment by alexec** [comment]
I think you'll be able to do this in low traffic installations v2.9:

```
argo submit my-wf.yaml
argo logs --follow @latest
```

This won't work in high traffic situations.
