### ISSUE TITLE
Docs link to 404

### ISSUE THREAD

**Issue by max-sixty** [argoproj/argo#3186]
Checklist:

 * [x] I've included reproduction steps.
 
**What happened**:
The link `Argo Workflows: Documentation by Example` below links to https://argoproj.github.io/docs/examples/README.html, which is a 404
<img width="939" alt="image" src="https://user-images.githubusercontent.com/5635139/83987412-04d8ea80-a8f5-11ea-9638-be7586b645b2.png">

---
<img width="645" alt="image" src="https://user-images.githubusercontent.com/5635139/83987464-2934c700-a8f5-11ea-9b6b-83cf83f1fad5.png">

---

**Comment by alexec** [comment]
@alexmt could you please fix this?

**Comment by alexec** [comment]
Dup of #3203?

**Comment by alexec** [comment]
Fixed.
