### ISSUE TITLE
optimization log

### ISSUE THREAD

**Issue by wangzhipeng** [argoproj/argo#3189]
# Summary

Modify log save method to stream

# Motivation

Modify the log saving mode to streaming mode to prepare for the next real-time log saving

# Proposal
Save(path string, outputArtifact *wfv1.Artifact) error [link](https://github.com/argoproj/argo/blob/04c77f490b00ffc05f74a941f1c9ccf76a5bf789/workflow/artifacts/artifacts.go#L25)    to
 Save(stream Stream, outputArtifact *wfv1.Artifact) error 

current  :    docker  --->  local file(Disk) ----> Artifact
want :  docker----> local (RAM) ---->Artifact

**Comment by alexec** [comment]
@wangzhipeng are you able to give examples of when this would have been useful to you please?

**Comment by wangzhipeng** [comment]
@alexec  We do cicd based on Argo and display log in real time in each pod

**Comment by alexec** [comment]
You can stream logs using the Argo Server API: "/api/v1/workflows/{namespace}/{name}/{podName}/log"

**Comment by alexec** [comment]
Or "/api/v1/workflows/{namespace}/{name}/log" on v2.12.2

**Comment by wangzhipeng** [comment]
thank
