### ISSUE TITLE
`go get github.com/argoproj/argo` > v.2.5.2

### ISSUE THREAD

**Issue by dcherman** [argoproj/argo#3192]
# Summary

I'm not sure whether or not this is a bug or me doing something wrong, so I'm reporting this as a question first.  Looking at https://pkg.go.dev/github.com/argoproj/argo, there are no versions newer than v2.5.2 listed versions listed.  Trying to force it by using curl against https://sum.golang.org results in invalid version: +incompatible suffix not allowed: module contains a go.mod file, so semantic import versioning is required.  Go modules were introduced in v2.6.0 , so that suggests that something might not be set up quite right.  Is that a fair assessment (an actual bug), or am I doing something incorrect when trying to run go get for a newer version of argo?

# Motivation

Using newer versions of Argo programatically with Golang.

**Comment by alexec** [comment]
This does not work because we move to Gomodules as of v2.6.0. Unfortunately, the way that Gomodules works (which is frankly bizarre) requires you either create a branch or a subdirectory for v2. So we cannot fix this. You should be able to use @master or similar.

**Comment by dcherman** [comment]
Should we re-label this with a v3.0 tag since you mentioned that it would be considered during the meeting yesterday?

**Comment by blkperl** [comment]
@dcherman The current workaround is described here:

https://github.com/argoproj/argo/issues/2602#issuecomment-636097428
