### ISSUE TITLE
Custom Metric: Race Conditions?

### ISSUE THREAD

**Issue by dcherman** [argoproj/argo#3193]
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [x] I've included the workflow YAML.
 * [x] I've included the logs.
 
**What happened**:

Running the example workflow for custom metrics with multiple concurrent workflows results in errors like 

```
An error has occurred while serving metrics:

2 error(s) occurred:
* collected metric "argo_workflows_result_counter" { label:<name:"name" value:"flakey" > label:<name:"status" value:"Succeeded" > counter:<value:9 > } was collected before with the same name and label values
* collected metric "argo_workflows_result_counter" { label:<name:"name" value:"flakey" > label:<name:"status" value:"Failed" > counter:<value:11 > } was collected before with the same name and label values
```

**What you expected to happen**:

Workflow metrics should be successfully collected.

**How to reproduce it (as minimally and precisely as possible)**:

Install the latest version of Argo (v2.8.1) in whatever environment you'd like (I git cloned argo @ the latest release), enable metrics config so you can inspect the metrics page, and run the following:

```bash
for i in {1..40}; do (argo submit -n argo --serviceaccount argo examples/custom-metrics.yaml &); done
```

**Anything else we need to know?**:

No.

**Environment**:

- Argo version:
```
$ argo version

argo: v2.7.3
  BuildDate: 2020-04-15T22:52:59Z
  GitCommit: 66bd0425280c801c06f21cf9a4bed46ee6f1e660
  GitTreeState: clean
  GitTag: v2.7.3
  GoVersion: go1.13.4
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :
```
$ kubectl version -o yaml

clientVersion:
  buildDate: "2020-04-16T23:35:15Z"
  compiler: gc
  gitCommit: 52c56ce7a8272c798dbc29846288d7cd9fbae032
  gitTreeState: clean
  gitVersion: v1.18.2
  goVersion: go1.14.2
  major: "1"
  minor: "18"
  platform: darwin/amd64
serverVersion:
  buildDate: "2020-04-30T20:19:45Z"
  compiler: gc
  gitCommit: 52c56ce7a8272c798dbc29846288d7cd9fbae032
  gitTreeState: clean
  gitVersion: v1.18.2
  goVersion: go1.13.9
  major: "1"
  minor: "18"
  platform: linux/amd64

```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by simster7** [comment]
Was able to reproduce... looking into this

**Comment by simster7** [comment]
Found the bug, fix incoming
