### ISSUE TITLE
Links to examples on the documentation are broken

### ISSUE THREAD

**Issue by carlosjgp** [argoproj/argo#3203]
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [x] I've included the workflow YAML.
 * [x] I've included the logs.
 
**What happened**:

I checked the docs but I can't see the examples

**What you expected to happen**:

Link to examples work

**How to reproduce it (as minimally and precisely as possible)**:
Go to
https://argoproj.github.io/docs/argo/fields.html#localobjectreference

![screenshot-argoproj github io-2020 06 10-15_32_06](https://user-images.githubusercontent.com/1277613/84281106-14904300-ab30-11ea-9f05-ed5e80535e1a.png)

![screenshot-argoproj github io-2020 06 10-15_32_39](https://user-images.githubusercontent.com/1277613/84281304-53be9400-ab30-11ea-9b9e-16e01eaeae0c.png)

**Anything else we need to know?**:

**Environment**:

**Other debugging information (if applicable)**:

**Logs**

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by alexec** [comment]
Fixed.
