### ISSUE TITLE
How to stop/terminate a workflow via HTTP?

### ISSUE THREAD

**Issue by mecampbellsoup** [argoproj/argo#3221]
# Summary

Hello guys - 

I am trying to use the k8s HTTP API to stop an Argo workflow.

Our project began prior to the existence of Argo server and so I'd rather just port the semantics of "Argo, stop this workflow" into a "Kubernetes, patch this workflow resource so as to terminate/stop it". Hopefully this distinction I'm making makes sense to you.

I'm struggling to figure out how to issue an "Argo, stop that workflow" command as a k8s patch HTTP request - here are some of the parameters I've tried so far:

```shell
➜  concierge-backend git:(matt-brian-argo-render) ✗ KUBECONFIG=./kubeconfig k patch workflow render-fgjxd -p '{"shutdown": "Terminate"}'

Error from server (UnsupportedMediaType): the body of the request was in an unknown format - accepted media types include: application/json-patch+json, application/merge-patch+json, application/apply-patch+yaml
➜  concierge-backend git:(matt-brian-argo-render) ✗ KUBECONFIG=./kubeconfig k patch workflow render-fgjxd --type='json' -p '{"shutdown": "Terminate"}'

Error from server (BadRequest): json: cannot unmarshal object into Go value of type jsonpatch.Patch
➜  concierge-backend git:(matt-brian-argo-render) ✗ KUBECONFIG=./kubeconfig k patch workflow render-fgjxd --type='json' -p '{"spec": {"shutdown": "Terminate"}}'

Error from server (BadRequest): json: cannot unmarshal object into Go value of type jsonpatch.Patch
➜  concierge-backend git:(matt-brian-argo-render) ✗ KUBECONFIG=./kubeconfig k patch workflow render-fgjxd --type='json' -p '[{"spec": {"shutdown": "Terminate"}}]'

The request is invalid
➜  concierge-backend git:(matt-brian-argo-render) ✗ KUBECONFIG=./kubeconfig k patch workflow render-fgjxd --type='json' -p '[{"spec": {"shutdown": "Terminate"}}]'

The request is invalid
➜  concierge-backend git:(matt-brian-argo-render) ✗ KUBECONFIG=./kubeconfig k patch workflow render-fgjxd --type='json' -p '[{"shutdown": "Terminate"}]'

The request is invalid
```
However as you can see, the requests are invalid.

Can you offer any suggestions on how I might go about reverse engineering the appropriate patch payload to shutdown/stop the desired workflow? Thank you kindly, I am very stuck so very much appreciate your comments!

**Comment by mecampbellsoup** [comment]
I found the Argo "terminate a workflow" patch definition here: https://github.com/argoproj/argo/blob/591f649a306edf826b667d0069ee04cb345dcd26/workflow/util/util.go#L722-L726

**Comment by simster7** [comment]
This worked for me:

```
$ kubectl patch wf steps-4bnx4 --type merge --patch '{"spec": {"shutdown": "Terminate"}}'
workflow.argoproj.io/steps-4bnx4 patched
```

**Comment by mecampbellsoup** [comment]
Wow, you are the MAN @simster7 - thank you!

**Comment by simster7** [comment]
Glad to help
