### ISSUE TITLE
Support remote manifest in the ResourceTemplate.

### ISSUE THREAD

**Issue by youngsofun** [argoproj/argo#3231]
# Summary

Support an option to fetch the manifest in ResourceTemplate from a URL. 

# Motivation

1. I  want to generalize [examples/k8s-waitwf.yaml](https://github.com/argoproj/argo/blob/master/examples/k8s-wait-wf.yaml#L23) into a WorkflowTemplates, and just pass it a URL of a manifest in the workflow.
2. Some manifest, like sparkapp in SparkOperator, is too complicated to be embedded in a workflow template field.  
3. Need git version management of the manifest alone.  A path on a distributed filesystem is also helpful for testing.
4. I can alternatively create resource With ContainerTemplate and kubectl,  but cannot use jsonPath to retrieve output parameters.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by simster7** [comment]
You could potentially have a Workflow step that downloads the manifest, outputs it, and passes it to the resource template as an Argo variable?

**Comment by alexec** [comment]
This is kind of GitOpts - maybe Argo CD could help?

**Comment by youngsofun** [comment]
@simster7   Thanks, It surely meets our requirements.  But current implementation is saving manifest to  "/tmp/manifest.yaml" and calling `kubectl ... -o json`. And kubectl naturally supports URL.  So I took it for granted that ResourceTemplate should accept URL too.

**Comment by youngsofun** [comment]
@alexec Thanks, I am new to Argo, I will look into argo-cd.
