### ISSUE TITLE
New Release (v2.9.0-rc1) erased old workflow metrics

### ISSUE THREAD

**Issue by prateekkhera** [argoproj/argo#3232]
Checklist:

 [x] I've included the version.
 [x] I've included reproduction steps.
 
**What happened**:

installing v2.9.0-rc1 in anticipation of using new metrics from this: [PR#3144](https://github.com/argoproj/argo/pull/3144) removed the old metrics. However, I can see the new metrics

**What you expected to happen**:
Old metrics (argo_workflow_info, argo_workflow_status_phase etc) persisted along with new metrics (argo_workflows_error_count etc) added

**How to reproduce it (as minimally and precisely as possible)**:
Re-installed argo from this: `kubectl apply -n argo -f https://raw.githubusercontent.com/argoproj/argo/v2.9.0-rc1/manifests/install.yaml`

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by simster7** [comment]
We have intentionally removed the old metrics, as they are not proper Prometheus metrics and are susceptible to issues such as cardinality explosion.

Here is an example of how you would define a workflow_info metric with custom metrics:

https://github.com/argoproj/argo/issues/2199#issuecomment-641569086

You cal also make use of the workflow list API endpoint or query the workflow archive.

**Comment by prateekkhera** [comment]
Thanks, looks good!
