### ISSUE TITLE
Provide a folder from local system as an input artifact to a template.

### ISSUE THREAD

**Issue by sahil-sawhney** [argoproj/argo#3235]
**Summary**  

Is there a provision in Argo workflow, using which we can provide a folder from our local file system as an input artifact to a template?  
Like we have s3, Http, git as some of the hardwired artifacts. I know about raw, but it requires an inline file, what I want is to provide a path to a folder from my local filesystem.  

**Motivation**  
This would be very helpful as I would be able to check my workflow with my code configs that contain secrets, locally. Will also relax me from pushing the (secret less version of) code every time to GitHub to test things.

**Comment by simster7** [comment]
By "local filesystem" do you mean the machine in which K8s is running on? If so, no... this seems like a bit of an anti-pattern.

What you can definitely do is store data on K8s objects, such as a `ConfigMap` or a `Secret`, then use Argo to retrieve them. These objects would not have to leave the K8s cluster.

Take a look at this example: https://github.com/argoproj/argo/issues/3212#issuecomment-642824124

**Comment by sahil-sawhney** [comment]
Hey, @simster7 by local filesystem I mean my laptops file system that has kubectl configured and has the Argo CLI from which I am triggering the command to submit a workflow and not node on which k8 is running.

**Comment by simster7** [comment]
Ah I see. In that case you should be able to do `argo submit <wf_name> --parameter-file <path>`. Take a look at the example in https://github.com/argoproj/argo/blob/master/examples/README.md#parameters

**Comment by sahil-sawhney** [comment]
Hey @simster7 the --parametr-file will just provide an input yaml. So what I am looking for is something that makes a local folder containing let's say my source code available to workflow. So instead of using git as hardwired artifact to fetch my sorce code from GitHub, I can provide a path on my laptop to my source code folder.

**Comment by sahil-sawhney** [comment]
@simster7 please let me know if I should explain my use case better.
A dummy example of what I am looking at is:
`
inputs:
  artifacts:
  - name: argo-source
    path: /src	# Path where folder would be monted in POD
    local:
      path: /my/local-systems/folder	# my local systems (laptops) folders path
`

**Comment by simster7** [comment]
Ah I see. This is not supported right now and I'm not sure it would even be possible. The only code that we control that would have access to your filesystem is the `argo` CLI binary. However, we designed Argo to be able to run workflows entirely without it (ie., talking directly to K8s, GitOps, API endpoints, etc.), so not sure if a feature like this would fit our design.

**Comment by sahil-sawhney** [comment]
Thanks a lot for confirming @simster7 . This was very helpful 😊
