### ISSUE TITLE
[UI] Better YAML editor

### ISSUE THREAD

**Issue by hadim** [argoproj/argo#3236]
The current YAML editor is simple HTML text area. It can be convenient for certain people to launch workflows from the UI. Maybe a more feature-rich YAML editor could be useful.

A one I found powerful is https://microsoft.github.io/monaco-editor/index.html

Another very long-time popular one is https://codemirror.net/

What do you think?

**Comment by simster7** [comment]
One step ahead of you :) https://github.com/argoproj/argo/pull/3075

**Comment by agilgur5** [comment]
This seemed to have been a duplicate of #3027
