### ISSUE TITLE
Restrict client mode access to only specific service account

### ISSUE THREAD

**Issue by hadim** [argoproj/argo#3243]
Is that possible to restrict access when using the `client` auth mode to only a specific Bearer token that is associated to a specific service account?

Maybe this is already possible and I missed it?

**Comment by alexec** [comment]
It uses the `argo-server` service account. Could you configure that?

**Comment by hadim** [comment]
So you mean the token used can only be the one linked to the service account that executes the argo server? I don't think this is what I observe (will confirm soon).

**Comment by hadim** [comment]
I confirm that as long as a token is associated with the correct permissions, it can access the UI. So it's not possible at the moment to restrict argo server to a specific serviceaccount/token.
