### ISSUE TITLE
Proposal: Eliminate dependency on Load balancer for external routes for deployments

### ISSUE THREAD

**Issue by abhinavdas** [argoproj/argo#325]
Currently, external routes are configured by having the cloud load balancer forward to ingress controller (via nodeport). However, this does require a load balancer and it must be configured for every cloud provider. This make argo install cloud dependent. In an effort to reduce cloud dependency, I propose the following change:

Use an awesome tunneled reverse proxy tool called pagekite (https://github.com/pagekite/PyPagekite). This tool works by running a front end server on the public internet and various backends that connect to this front end for exposing localhost services.
In our case, we can run pagekite front end on a VM tied to our domain name and every cluster that is created will automatically be assigned `*.CLUSTERNAME.CUSTOMERID.argoproj.io`. The backend will be running on the ingress controller pod as a sidecar and will be exposing localhost:80 and localhost:443 to `*.CLUSTERNAME.CUSTOMERID.argoproj.io`.

As a bonus this should work for every kind of cluster including minikube :)

**Comment by abhinavdas** [comment]
@edlee2121 : Comments?

**Comment by abhinavdas** [comment]
I have tested some of the basics out on my dast2 cluster. 
Main question is whether I can create wildcard sub-kites...

**Comment by edlee2121** [comment]
Nice, in addition to making a separate load balancer unnecessary, this would also allow us access to Kubernetes clusters in private subnets.

Wildcards will work with DNS resolution (Route53) for sub, sub-sub, sub-sub-sub, etc. domains. But wildcard certs will not work with sub-sub domains.

**Comment by abhinavdas** [comment]
I can run pagekite in frontend and backend mode. 
TODO:
1. Need to enable TLS tunnels between front end and back end
2. Modify pagekit to support wildcard kites (does not seem to have support for this)

**Comment by abhinavdas** [comment]
Not needed as we are not deploying an LB for user provided clusters.
