### ISSUE TITLE
Is it possible to test substring in conditionals.

### ISSUE THREAD

**Issue by lueenavarro** [argoproj/argo#3250]
For example the output of one step are the following. "JOB1, JOB2, JOB3, JOB5"

How can i use conditionals to check if "JOB4" is in the output of that step or not. I could only see == by reading the documents.

If test for substring is not available, what would be a great alternative?

**Comment by yauhen-sobaleu** [comment]
Hi, it is possible
https://github.com/argoproj/argo/issues/860#issuecomment-410987112
