### ISSUE TITLE
argo list and argo get work, but argo logs does not

### ISSUE THREAD

**Issue by orcaman** [argoproj/argo#3275]
# Summary

I'm using argo and the commands for `argo get` and `argo list` work. `argo get` returns a pod X-Y, yet the `argo logs X-Y` command seems to fail with the error message "]FATA[0000] workflows.argoproj.io "data-X-Y" not found".

Changing `argo logs X-Y` to `kubectl logs X-Y main` actually works. Any idea?

**Comment by simster7** [comment]
What version are you running? Can you post some screenshots and logs? Would need more info to debug this

**Comment by orcaman** [comment]
Here are the logs that might be helpful:

## version
`argo version`
Output:
```
argo: v2.7.0
  BuildDate: 2020-03-31T23:35:43Z
  GitCommit: 4d1175eb68f6578ed5d599f877be9b4855d33ce9
  GitTreeState: clean
  GitTag: v2.7.0
  GoVersion: go1.13.4
  Compiler: gc
  Platform: darwin/amd64
```

## running argo logs command:
`argo logs  data-hntn6-3489222862`

Output is:
`FATA[0003] workflows.argoproj.io "data-hntn6-3489222862" not found 
`

## running kubectl logs command for the same pod:
`kubectl logs data-hntn6-3489222862 main`
Output:
`some logs from the pod`

**Comment by simster7** [comment]
A couple of fixes to `argo logs` have been made since 2.7.0 (https://github.com/argoproj/argo/pull/2595 and https://github.com/argoproj/argo/pull/2639). Can you update to 2.8.2 and see if this issue is fixed for you?

**Comment by orcaman** [comment]
I tried upgrading to 2.9.0-rc3, same issue:

➜  curl -sLO https://github.com/argoproj/argo/releases/download/v2.9.0-rc3/argo-darwin-amd64

➜  chmod +x argo-darwin-amd64

➜  mv ./argo-darwin-amd64 /usr/local/bin/argo

➜  argo version

argo: v2.9.0-rc3
  BuildDate: 2020-06-23T18:46:18Z
  GitCommit: 2e95ff4843080e7fd673cf0a551a862e3e39d326
  GitTreeState: clean
  GitTag: v2.9.0-rc3
  GoVersion: go1.13.4
  Compiler: gc
  Platform: darwin/amd64

➜  argo logs  data-hntn6-3489222862        
FATA[0000] workflows.argoproj.io "data-hntn6-3489222862" not found 

➜  kubectl logs data-hntn6-3489222862  main
some logs from the pod

**Comment by alexec** [comment]
This command has changed. The first argument is the name of the workflow, not the name of the pod.
```
argo logs --help
view logs of a pod or workflow

Usage:
  argo logs WORKFLOW [POD] [flags]

Examples:
# Print the logs of a workflow:

  argo logs my-wf

# Follow the logs of a workflows:

  argo logs my-wf --follow

# Print the logs of single container in a pod

  argo logs my-wf my-pod -c my-container

# Print the logs of a workflow's pods:

  argo logs my-wf my-pod

# Print the logs of a pods:

  argo logs --since=1h my-pod

# Print the logs of the latest workflow:
  argo logs @latest


```

**Comment by orcaman** [comment]
Thank you very much my friend!
