### ISSUE TITLE
{tasks,steps}.*.outputs.results capture

### ISSUE THREAD

**Issue by gmahomarf** [argoproj/argo#3289]
# Summary

`{tasks,steps}.*.outputs.results` seems to capture both STDIN and STDERR. Is this the expected behavior? The docs are unclear about this

# Motivation

Noticed this behavior, and was wondering if it was expected. Asked on Slack, and got no response

**Comment by simster7** [comment]
Depends on which executor you are using. Some executors don't support non-combined output. Do you know which one you're using?

**Comment by gmahomarf** [comment]
Thanks for the response.

It seems we're using `k8sapi`. Is there alist of which executors support non-combined output? I searched the docs, but it seems I missed it.

**Comment by simster7** [comment]
Only the `Docker` executor supports it

**Comment by gmahomarf** [comment]
Noted. Thanks for the info!
