### ISSUE TITLE
Document the "workflow of workflows" pattern

### ISSUE THREAD

**Issue by alexec** [argoproj/argo#3295]
# Summary

Now we have templates, you can compose a workflow from other workflows. We should document this.

# Motivation

This is because we do not promote this solution much

# Proposal

Write docs!

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by alexec** [comment]
FYI @jessesuen 
@sarabala1979 would you like to own?

**Comment by sarabala1979** [comment]
yes
