### ISSUE TITLE
Error in Swagger.json

### ISSUE THREAD

**Issue by mtiller** [argoproj/argo#3318]
**What happened**:

As part of issue #3309, I looked into generating types directly from the `swagger.json` file.  I was successful in generating the types, but immediately ran into type errors.  Specifically, when creating a `container` in a `spec`, I get an error if I don't provide a value for `name`.  This can be traced to [the following line](https://github.com/argoproj/argo/blob/master/api/openapi-spec/swagger.json#L4776) in `swagger.json` (commit a0062adfe895ee39572db3aa6f259913279c6db3).

**What you expected to happen**:

I expect `name` to be optional.  I say this because looking at the code [here](https://godoc.org/k8s.io/api/core/v1#Container), we can see it conflicts with what is in `swagger.json`.

**How to reproduce it (as minimally and precisely as possible)**:

This is strictly an issue with the code in the repo.  Nothing needs to be run to see it.

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by alexec** [comment]
I think this was being fixed, but I guess not. The correct value for name is always `main`.

**Comment by mtiller** [comment]
I see.  So the point is that the argo runtime will add the name automatically.  So it really shouldn't reference the Kubernetes type there, right?

**Comment by mtiller** [comment]
I found what I consider another error [here](https://github.com/argoproj/argo/blob/master/api/openapi-spec/swagger.json#L3680).  It indicates that `status` is required.  But it isn't.  It may very well always be present in *responses*, but it is also the argument when you create a `Workflow` and it definitely isn't required there.

Is it worth reporting these issues?  It seems like perhaps nobody is actually using the `swagger.json` file.

**Comment by alexec** [comment]
We should fix these, so please leave open.

**Comment by mtiller** [comment]
Should I create separate issues?  Seems easier to track that way.

**Comment by alexec** [comment]
@mtiller what would better that creating an issue :)

Do you want to get your hands dirty and fix them as you find them...?

**Comment by mtiller** [comment]
Possibly.  I'd just have to see whether I can get the necessary dev environment setup.  But a key issue is tests.  Clearly, these have slipped through so far.  What kind of tests would be required for a PR on this?

**Comment by alexec** [comment]
Should be fixed on master.
