### ISSUE TITLE
How to "exec" (/bin/bash) into an Argo pod/container for debugging?

### ISSUE THREAD

**Issue by mecampbellsoup** [argoproj/argo#3324]
# Summary

I want to know how I can debug an Argo k8s pod that is running or already ran in order to poke around the OS, run commands, etc. (normal debugging)

# Motivation

I have a failing workflow step and I'm struggling to uncover what is going on with the failing process.

**Comment by mecampbellsoup** [comment]
OK, I realized I was using the wrong pod ID (i.e. `render-4hfgl` instead of `render-4hfgl-2742724330` in this example), but now I'm unable to exec into a completed pod...

```
➜  concierge-backend git:(eevee-mount-display-servers) kubectl exec --stdin --tty render-4hfgl-2742724330 -- /bin/bash
error: cannot exec into a container in a completed pod; current phase is Succeeded
```

**Comment by simster7** [comment]
If the Pod is completed, there's nothing running you can exec into. If you want to `sh` into a container, you can just have it sleep to keep it running. Then you should be able to exec into it

**Comment by mecampbellsoup** [comment]
I ended up adding a `time.sleep` to my Argo workflow script (it's a Python script, FWIW) so I could exec while running.

I didn't see any of the things I was expecting to see in the host OS, e.g.:

```sh
root@gdfc128:/# file /var/run/
docker.sock  lock/        secrets/     utmp
root@gdfc128:/# file /var/run/lightdm
/var/run/lightdm: cannot open `/var/run/lightdm' (No such file or directory)
```

I mount in this socket as a volume in my workflow definition (a `WorkflowTemplate` to be specific):

```yaml
      volumeMounts:
        - name: light-dm
          mountPath: /var/run/lightdm
```

When I look at `ps aux` results, it leads me to think Argo is doing a docker-in-docker workflow of its own - is that correct?

```sh
root@gdfc128:/# ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0 145816 34048 ?        Ssl  17:37   0:00 argoexec wait
root        25  0.0  0.0  46988 29564 ?        Sl   17:38   0:00 docker wait e3cd79ec0ef87102e10eb09e070e7d7d8537186a9dc493ac7b4084b1c6f0e714
root        40  0.0  0.0   4012  3244 pts/0    Ss   17:38   0:00 /bin/bash
root        58  0.0  0.0   7640  2676 pts/0    R+   17:40   0:00 ps aux
```
So my question is whether looking into this running Argo pod is the correct way to introspect the actual workflow execution I'm debugging - does my Q make sense to you?
