### ISSUE TITLE
How argo convert workflow made by UI to the YAML file ?

### ISSUE THREAD

**Issue by NKcqx** [argoproj/argo#3333]
# Summary
How argo convert workflow made by UI to the YAML file ?

# Motivation
We're working on something like this: deploy a workflow on cluster. The workflow is a data structure stored in memory, and we wanna convert it to a YAML file so that we can deploy it. We're planning use some tools like template engine, but I'm not sure whether it is a good solution, so here I am~

**Comment by alexec** [comment]
`argo get workflow-name -o yaml`

**Comment by NKcqx** [comment]
Thank you at first~!
Actually I know what command can do that convertion, instead what I wanna know is "how argo can technically do that", I'm hoping for some more implementation details if this is allowed ~

**Comment by alexec** [comment]
Ok.  Workflows are custom resources, as such their definitions is stored in etcd along with the definitions of pods etc. 

This is why you can do `kubectl get workflow workflow-name`.

Alex

**Comment by NKcqx** [comment]
Oh OK, I get it, I was completely thinking in an opposite way, thank u for ur time !
