### ISSUE TITLE
Possible bad code block in quick start

### ISSUE THREAD

**Issue by whyvez** [argoproj/argo#3346]
Nice work on new docs!

Looks like there might be a bad code block in the quickstart here: https://argoproj.github.io/argo/quick-start/#install-argo-workflows

The `kubectl apply` link is:

`kubectl apply -n argo -f https://raw.githubusercontent.com/argoproj/argo/stable/manifests/quick-start-postgress.yaml`

but should be:

`kubectl apply -n argo -f https://raw.githubusercontent.com/argoproj/argo/stable/manifests/install.yaml`

**Comment by alexec** [comment]
You're correct. This doc is new and wrong only on "s" is "postgres":

```
kubectl apply -n argo -f https://raw.githubusercontent.com/argoproj/argo/stable/manifests/quick-start-postgres.yaml
```

**Comment by alexec** [comment]
Fixed.
