### ISSUE TITLE
Argo cli does not honor --repo if local directory is a git repo

### ISSUE THREAD

**Issue by shrinandj** [argoproj/argo#337]
Argo cli ignores the --repo command line option if the local directory from which it is running is a git repo.

```
$ pwd
/src/argo
$ argo --branch master --repo https://github.com/argoproj/ci-workflow.git job submit "example-workflow"
Could not find template 'example-workflow' in repo: https://github.com/argoproj/argo.git, branch: master
```

In the above example, I wanted to run a workflow from the "ci-workflow" git repo. However, since the local directory was the local clone of the argo git repo, it kept on failing.

**Comment by jessesuen** [comment]
Fixed. cli should honor repo command line flag.
