### ISSUE TITLE
generate-artifact failed to save outputs:

### ISSUE THREAD

**Issue by zhujiangyou** [argoproj/argo#3394]
`     ├-⚠ generate-artifact(2) (docker-task)  offline-docker-task-nl9vb-1772027110  22s  failed to save outputs: Pod "offline-docker-task-nl9vb-1772027110" is invalid: spec: Forbidden: pod updates may not change fields other than `spec.containers[*].image`, `spec.initContainers[*].image`, `spec.activeDeadlineSeconds` or `spec.tolerations` (only additions to existing tolerations)
  core.PodSpec{
    Volumes:        []core.Volume{{Name: "podmetadata", VolumeSource: core.VolumeSource{DownwardAPI: &core.DownwardAPIVolumeSource{Items: []core.DownwardAPIVolumeFile{{Path: "annotations", FieldRef: &core.ObjectFieldSelector{APIVersion: "v1", FieldPath: "metadata.annotations"}}}, DefaultMode: &420}}}, {Name: "docker-sock", VolumeSource: core.VolumeSource{HostPath: &core.HostPathVolumeSource{Path: "/var/run/docker.sock", Type: &"Socket"}}}, {Name: "4e918144-c00d-11ea-af9e-f28f9f23c562", VolumeSource: core.VolumeSource{HostPath: &core.HostPathVolumeSource{Path: "/data/dataset-002", Type: &"Directory"}}}, {Name: "minio-secret", VolumeSource: core.VolumeSource{Secret: &core.SecretVolumeSource{SecretName: "minio-secret", Items: []core.KeyToPath{{Key: "accesskey", Path: "accesskey"}, {Key: "secretkey", Path: "secretkey"}}, DefaultMode: &420}}}, {Name: "workflow-sa-token-6shbj", VolumeSource: core.VolumeSource{Secret: &core.SecretVolumeSource{SecretName: "workflow-sa-token-6shbj", DefaultMode: &420}}}},
    InitContainers: nil,
    Containers: []core.Container{
      {
        ... // 15 identical fields
        TerminationMessagePath:   "/dev/termination-log",
        TerminationMessagePolicy: "File",
-       ImagePullPolicy:          "Always",
+       ImagePullPolicy:          "IfNotPresent",
        SecurityContext:          nil,
        Stdin:                    false,
        ... // 2 identical fields
      },
      {
        ... // 15 identical fields
        TerminationMessagePath:   "/dev/termination-log",
        TerminationMessagePolicy: "File",
-       ImagePullPolicy:          "Always",
+       ImagePullPolicy:          "IfNotPresent",
        SecurityContext:          nil,
        Stdin:                    false,
        ... // 2 identical fields
      },
    },
    EphemeralContainers: nil,
    RestartPolicy:       "Never",
    ... // 24 identical fields
  }`
# Summary

The phenomenon is: sometimes it fails and reports the above error, but when I submit the workflow again, it succeeds.
Does anyone know about this？

**Comment by zhujiangyou** [comment]
I've solved this problem.

**Comment by akshaybhatt14495** [comment]
@zhujiangyou  Can you tell me what was the RCA for this issue? We are facing it as well.

**Comment by madhuresh04** [comment]
Facing the similar issue. Can you help us !

**Comment by zhujiangyou** [comment]
> Facing the similar issue. Can you help us !

It may be due to the Argo version. Check whether the versions of Argo server and workflow controller are consistent。
