### ISSUE TITLE
Argo does not work when iframe

### ISSUE THREAD

**Issue by smolaon** [argoproj/argo#3397]
Checklist:

 * [ x] I've included the version.
 * [ ] I've included reproduction steps.
 * [ ] I've included the workflow YAML.
 * [ ] I've included the logs.
 
**What happened**:
When accessing argo server via iframe we got message 
```Refused to display 'https://xxx/workflows/' in a frame because it set 'X-Frame-Options' to 'deny'.```

**What you expected to happen**:
I would like to have option to change value of `X-Frame-Options`.

**Environment**:

- Argo version:
```
$ argo version
argo: v2.9.1
  BuildDate: 2020-07-03T15:11:20Z
  GitCommit: 6b967d08c0a142aaa278538f2407c28de467262e
  GitTreeState: clean
  GitTag: v2.9.1
  GoVersion: go1.13.4
  Compiler: gc
  Platform: linux/amd64
```
---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by alexec** [comment]
This is intentional. You cannot embed for security reasons.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options

**Comment by simster7** [comment]
Perhaps we should make this configurable? I know @ericmeadows also wants to embed

**Comment by alexec** [comment]
I'm happy for someone to submit a PR to make this configurable.

**Comment by ericandrewmeadows** [comment]
I would love to - I'm currently waiting on internal approval to contribute to OSS.  :/.
