### ISSUE TITLE
(SSO) OIDC request asks for non-standard groups scope

### ISSUE THREAD

**Issue by Azolo** [argoproj/argo#3412]
With SSO enabled and argo-server 9.2.1, authentication with AzureAD returns an error that the scope `groups` doesn't exist on the resource.

I think you're trying to get the `groups` claim to be able to map it to some form of RBAC in the future. However, the `groups` scope is probably an implementation detail for some provider(s) to include the `groups` claim in the JWT and isn't standard.

The `groups` claim isn't included in any of the [specification scopes][0] because it's not a [specification claim][1] nor is it [registered by the IANA][2]. Which means it's completely up in the air on how exactly to implement it.

There is a way to request individual claims, but I've never seem it actually used. Most of the time, it's either built into the request or part of a custom scope.

This is one of those situations where, besides the required `openid` scope, it's probably a better to allow users to specify the request scopes and which claim, if any, to map the groups from.

[0]: https://openid.net/specs/openid-connect-core-1_0.html#ScopeClaims
[1]: https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims
[2]: https://www.iana.org/assignments/jwt/jwt.xhtml

**Comment by alexec** [comment]
Hi @Azolo we request the `groups` in `sso.go`. I'm pretty sure we don't need them, as we do not support RBAC yet.

We've very busy at the moment - but if you like to submit a PR to fix this, we could  get this into v2.9.3 or .4.

**Comment by alexec** [comment]
Fix in v2.9.2

**Comment by Azolo** [comment]
@alexec Awesome, thanks. Working great.
