### ISSUE TITLE
Error syncing pod "argo/my-pod": generic::unavailable: pod "argo/my-pod" not found after refresh

### ISSUE THREAD

**Issue by aviklai** [argoproj/argo#3416]
Hi,

I have tried to run a stress test on my argo v2.9.1 cluster which included running 1000 workflows.
3 of them are stuck on running after almost 24 hours.
I checked the logs and this is the error that I get:
Error syncing pod "argo/my-pod": generic::unavailable: pod "argo/my-pod" not found after refresh

Pod "argo/my-pod" found in snapshot: podfinder.entry{sandboxUID:"0dca60508027ee92b5ecb2fac4aa196e32018ff03f4aee472617e7ed48258ef3", podUID:"34cd8db2-6274-4620-8922-1272f38ad56d"}

I am running argo on a kubernetes cluster on Google Cloud and I am using preemptible nodes with an auto scale feature enabled.
I have an assumption that this happens when an scale down event occurs which deletes the pod (because the node was terminated) and it never recovers.
If this is the issue - is there any way to restart this step of the workflow on such event?
and if not - what else might cause the issue?

**Comment by alexec** [comment]
Can you confirm if your workflows work with v2.8.2 so we can determine if this is a regression?

**Comment by aviklai** [comment]
I am not sure but I don't think it's a regression.
I upgraded from version 2.7.6 and saw there something similar - I saw a case where the phase was an error and the pod was in status Deleted.

**Comment by aviklai** [comment]
I update the retryStrategy and now it looks o.k - a new pod is created when a pod is deleted by an autoscale event.
