### ISSUE TITLE
Panic on CLI Watch command 

### ISSUE THREAD

**Issue by sarabala1979** [argoproj/argo#3422]
[msaasfmea4-ppd-usw2.cluster.k8s.local] \W$ argo watch perf-infra-ln6d8
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x318 pc=0x26d44e8]
goroutine 1 [running]:
k8s.io/apimachinery/pkg/apis/meta/v1.(*Time).IsZero(...)
	/Users/acollins8/go/pkg/mod/k8s.io/apimachinery@v0.16.7-beta.0/pkg/apis/meta/v1/time.go:65
github.com/argoproj/argo/cmd/argo/commands.watchWorkflow(0x7ffeefbffc7b, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/acollins8/go/src/github.com/argoproj/argo/cmd/argo/commands/watch.go:96 +0x458
github.com/argoproj/argo/cmd/argo/commands.NewWatchCommand.func1(0xc000605900, 0xc0003f0860, 0x1, 0x1)
	/Users/acollins8/go/src/github.com/argoproj/argo/cmd/argo/commands/watch.go:43 +0x91
github.com/spf13/cobra.(*Command).execute(0xc000605900, 0xc0003f0820, 0x1, 0x1, 0xc000605900, 0xc0003f0820)
	/Users/acollins8/go/pkg/mod/github.com/spf13/cobra@v0.0.4-0.20181021141114-fe5e611709b0/command.go:766 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0xc0005a2f00, 0xc00008a750, 0xc00085df50, 0x100545f)
	/Users/acollins8/go/pkg/mod/github.com/spf13/cobra@v0.0.4-0.20181021141114-fe5e611709b0/command.go:852 +0x2ea
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/acollins8/go/pkg/mod/github.com/spf13/cobra@v0.0.4-0.20181021141114-fe5e611709b0/command.go:800
main.main()
	/Users/acollins8/go/src/github.com/argoproj/argo/cmd/argo/main.go:17 +0x2b
[msaasfmea4-ppd-usw2.cluster.k8s.local] \W$ argo watch perf-infra-ln6d8
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x318 pc=0x26d44e8]
goroutine 1 [running]:
k8s.io/apimachinery/pkg/apis/meta/v1.(*Time).IsZero(...)
	/Users/acollins8/go/pkg/mod/k8s.io/apimachinery@v0.16.7-beta.0/pkg/apis/meta/v1/time.go:65
github.com/argoproj/argo/cmd/argo/commands.watchWorkflow(0x7ffeefbffc7b, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/acollins8/go/src/github.com/argoproj/argo/cmd/argo/commands/watch.go:96 +0x458
github.com/argoproj/argo/cmd/argo/commands.NewWatchCommand.func1(0xc000719b80, 0xc0004a9860, 0x1, 0x1)
	/Users/acollins8/go/src/github.com/argoproj/argo/cmd/argo/commands/watch.go:43 +0x91
github.com/spf13/cobra.(*Command).execute(0xc000719b80, 0xc0004a9820, 0x1, 0x1, 0xc000719b80, 0xc0004a9820)
	/Users/acollins8/go/pkg/mod/github.com/spf13/cobra@v0.0.4-0.20181021141114-fe5e611709b0/command.go:766 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0xc0006f9180, 0xc00008a750, 0xc000819f50, 0x100545f)
	/Users/acollins8/go/pkg/mod/github.com/spf13/cobra@v0.0.4-0.20181021141114-fe5e611709b0/command.go:852 +0x2ea
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/acollins8/go/pkg/mod/github.com/spf13/cobra@v0.0.4-0.20181021141114-fe5e611709b0/command.go:800
main.main()
	/Users/acollins8/go/src/github.com/argoproj/argo/cmd/argo/main.go:17 +0x2b

**Comment by alexec** [comment]
maybe
```
	if !wf.Status.FinishedAt.IsZero() {
			return
		}
```
?

**Comment by jamesgunnfiveai** [comment]
I'm still experiencing this issue with the 2.9.3 CLI. As far as I can tell it should be resolved in 2.9.3 as the fix was backported to 2.9 ahead of the 2.9.3 cut.

Would you prefer a separate ticket?

```
argo version
argo: v2.9.3
  BuildDate: 2020-07-15T01:15:50Z
  GitCommit: 9407e19b3a1c61ad4043e382484fd0b6b15574f2
  GitTreeState: clean
  GitTag: v2.9.3
  GoVersion: go1.13.4
  Compiler: gc
  Platform: linux/amd64
```

```
argo watch <<REDACTED>>
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x318 pc=0x1ad39e8]

goroutine 1 [running]:
k8s.io/apimachinery/pkg/apis/meta/v1.(*Time).IsZero(...)
	/Users/acollins8/go/pkg/mod/k8s.io/apimachinery@v0.16.7-beta.0/pkg/apis/meta/v1/time.go:65
github.com/argoproj/argo/cmd/argo/commands.watchWorkflow(0x7ffd111c2bac, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/acollins8/go/src/github.com/argoproj/argo/cmd/argo/commands/watch.go:100 +0x458
github.com/argoproj/argo/cmd/argo/commands.NewWatchCommand.func1(0xc00056c000, 0xc0001bd910, 0x1, 0x1)
	/Users/acollins8/go/src/github.com/argoproj/argo/cmd/argo/commands/watch.go:43 +0x91
github.com/spf13/cobra.(*Command).execute(0xc00056c000, 0xc0001bd7e0, 0x1, 0x1, 0xc00056c000, 0xc0001bd7e0)
	/Users/acollins8/go/pkg/mod/github.com/spf13/cobra@v0.0.4-0.20181021141114-fe5e611709b0/command.go:766 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0xc00054f400, 0xc000088750, 0xc0008eff50, 0x40576f)
	/Users/acollins8/go/pkg/mod/github.com/spf13/cobra@v0.0.4-0.20181021141114-fe5e611709b0/command.go:852 +0x2ea
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/acollins8/go/pkg/mod/github.com/spf13/cobra@v0.0.4-0.20181021141114-fe5e611709b0/command.go:800
main.main()
	/Users/acollins8/go/src/github.com/argoproj/argo/cmd/argo/main.go:17 +0x2b
```

**Comment by alexec** [comment]
```golang
	var wf *wfv1.Workflow
	ticker := time.NewTicker(time.Second)
	for {
		select {
		case newWf := <-wfChan:
			// If we get a new event, update our workflow
			if newWf == nil {
				return
			}
			wf = newWf
		case <-ticker.C:
			// If we don't, refresh the workflow screen every second
		}

		printWorkflowStatus(wf, getArgs)
		if !wf.Status.FinishedAt.IsZero() {
			return
		}
	}
```

Something - wrong in this loop maybe with ticket. Needs investigation.

**Comment by sarabala1979** [comment]
[msaasfmea4-ppd-usw2.cluster.k8s.local] \W$ argo list | grep argowf
argowf-chaos-8g6cn          Failed                10m   1m         0
argowf-chaos-574f8          Failed                16m   1m         0
argowf-chaos-x5zng          Failed                25m   1m         0
argowf-chaos-8dvxt          Failed                57m   1m         0
argowf-chaos-bv24p          Failed                2h    1m         0
[msaasfmea4-ppd-usw2.cluster.k8s.local] \W$ argo watch argowf-chaos-8g6cn 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x318 pc=0x26d44e8]
goroutine 1 [running]:
k8s.io/apimachinery/pkg/apis/meta/v1.(*Time).IsZero(...)
	/Users/acollins8/go/pkg/mod/k8s.io/apimachinery@v0.16.7-beta.0/pkg/apis/meta/v1/time.go:65
github.com/argoproj/argo/cmd/argo/commands.watchWorkflow(0x7ffeefbffc93, 0x12, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/acollins8/go/src/github.com/argoproj/argo/cmd/argo/commands/watch.go:96 +0x458
github.com/argoproj/argo/cmd/argo/commands.NewWatchCommand.func1(0xc00076e000, 0xc0004b5740, 0x1, 0x1)
	/Users/acollins8/go/src/github.com/argoproj/argo/cmd/argo/commands/watch.go:43 +0x91
github.com/spf13/cobra.(*Command).execute(0xc00076e000, 0xc0004b5700, 0x1, 0x1, 0xc00076e000, 0xc0004b5700)
	/Users/acollins8/go/pkg/mod/github.com/spf13/cobra@v0.0.4-0.20181021141114-fe5e611709b0/command.go:766 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0xc000751400, 0xc00008a750, 0xc00081bf50, 0x100545f)
	/Users/acollins8/go/pkg/mod/github.com/spf13/cobra@v0.0.4-0.20181021141114-fe5e611709b0/command.go:852 +0x2ea
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/acollins8/go/pkg/mod/github.com/spf13/cobra@v0.0.4-0.20181021141114-fe5e611709b0/command.go:800
main.main()
