### ISSUE TITLE
Artifact mode is not recursive

### ISSUE THREAD

**Issue by ValdasK** [argoproj/argo#3444]
Argo version: 2.9.2

Artifact directory items in  do not get their mode set recursively. By setting a mode I'd expect every children to receive same permissions, but now if directory contains nested items, and container does not run as root, they are unable to access them.
 
Can be reproduced by uploading some files to bucket:

```
touch test.txt
gsutil cp test.txt gs://[BUCKET]/parent/test.txt
gsutil cp test.txt gs://[BUCKET]/parent/child/test.txt
```

Then starting a workflow:

```
metadata:
  generateName: not-working-
spec:
  entrypoint: work
  templates:
    - name: work
      container:
        name: main
        image: alpine
        command:
          - ls
          - -la
          - /home/data
          - "&&"
          - ls
          - -la
          - /home/data/child
      inputs:
        artifacts:
          - name: data
            path: /home/data
            mode: 0777
            gcs:
              bucket: [BUCKET]
              key: parent
              serviceAccountKeySecret:
                name: my-gcs-credentials
                key: serviceAccountKey
```

Container output looks like:

```
2020-07-10T09:07:40.353777421Z /home/data:
2020-07-10T09:07:40.35414018Z total 12
2020-07-10T09:07:40.354155704Z drwxrwxrwx    3 root     root          4096 Jul 10 09:07 .
2020-07-10T09:07:40.354183878Z drwxr-xr-x    1 root     root          4096 Jul 10 09:07 ..
2020-07-10T09:07:40.354201555Z drwx------    2 root     root          4096 Jul 10 09:07 child
2020-07-10T09:07:40.354206473Z -rw-r--r--    1 root     root             0 Jul 10 09:07 test.txt
2020-07-10T09:07:40.354211338Z
2020-07-10T09:07:40.354215825Z /home/data/child:
2020-07-10T09:07:40.354220523Z total 8
2020-07-10T09:07:40.354225122Z drwx------    2 root     root          4096 Jul 10 09:07 .
2020-07-10T09:07:40.354229791Z drwxrwxrwx    3 root     root          4096 Jul 10 09:07 ..
2020-07-10T09:07:40.354234687Z -rw-r--r--    1 root     root             0 Jul 10 09:07 test.txt
```

We can observe that /home/data got expected 777, but both parent "test.txt" or nested directories are using other permissions.

I think that this could also be similar to https://github.com/argoproj/argo/issues/1583

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by alexec** [comment]
Can you confirm if this worked in v2.8.2 please?

**Comment by ValdasK** [comment]
> 
> 
> Can you confirm if this worked in v2.8.2 please?

Will try to get back to you on this on monday

**Comment by alexec** [comment]
@alexec to write how to do this.

**Comment by ValdasK** [comment]
Installed using 

```
https://raw.githubusercontent.com/argoproj/argo/v2.8.2/manifests/namespace-install.yaml
```

And behavior seems to be identical, folders are readable only by root, and files only get read access.

**Comment by alexec** [comment]
If your archive does not have the permissions you need when unpacked, because it was packed without the permissions you want,  use the `script` template and chmod to fix this. E.g.

```
find /home/data -type d | xargs chmod 0777 
find /home/data -type f | xargs chmod 0644
```

Note that you typically want different permissions for files and directories.

**Comment by ValdasK** [comment]
Could you post an example yml for how to use this script template together with image?

As if my container is not root, it won't be able to chmod root owned items, and if I move script to another part, it will receive copies of those inputs?

Or do you say I have to:
1. download from storage
2. run script to chmod using root
3. pass chmoded artifacts to my image?

**Comment by AntoineDao** [comment]
I am proposing a PR to resolve this at the `executor` level as it has `root` privilege when using the `docker` executor. This means that both when the executor is root or when it is non-root (ie: PNS executor) it should perform as expected for `main` containers that do not have `root` access.
