### ISSUE TITLE
Support `resubmit` with memoization from the UI

### ISSUE THREAD

**Issue by alexec** [argoproj/argo#3453]
# Summary

This is not possible in the UI.

# Motivation

Make `argo resubmit --memoized` available as a UI feature.

# Proposal

React!

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by alexec** [comment]
See #3214

**Comment by alexec** [comment]
@ashrafgt, @raphelemmanuvel, @terrytangyuan would you like to submit a PR for this? It would be good to support resubmit with different parameters too.

**Comment by alexec** [comment]
This would be really useful for ML, where user want to re-submit the same workflow with different parameters each time.

**Comment by alexec** [comment]
See #4662

**Comment by simster7** [comment]
Will be fixed with https://github.com/argoproj/argo/issues/4662
