### ISSUE TITLE
Don't force a reload on UI error

### ISSUE THREAD

**Issue by alexec** [argoproj/argo#3454]
# Summary

When the UI reports an error, it bubbles up to a special error page, this page blocks the UI and we can't use it anymore.

# Motivation

Is there a better. way to do this?

# Proposal

How do you think this should be implemented?

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by alexec** [comment]
Closing as duplicate.

**Comment by agilgur5** [comment]
Duplicate of #3666 to be specific (though this issue was first)
