### ISSUE TITLE
Windows CLI is gone

### ISSUE THREAD

**Issue by saosebastiao** [argoproj/argo#3463]
# Summary

What do you want to know about this project?

What happened to the Windows CLI app? 

# Motivation

Why do you need to know this, any examples or use cases you could include?

I have been going through some due diligence to test/adopt this project at T-Mobile, but right before we were about to deploy, the Windows CLI downloads seemed to disappear.  This could potentially be a dealbreaker. If support for testing a Windows CLI is necessary, we may be able to assist.

**Comment by simster7** [comment]
The windows CLI is available in our latest release page: 

https://github.com/argoproj/argo/releases/tag/v2.9.2

https://github.com/argoproj/argo/releases/download/v2.9.2/argo-windows-amd64

Am I missing something?

**Comment by saosebastiao** [comment]
Sorry, forgive me, I'm not sure what I was thinking.
