### ISSUE TITLE
Panic on releaseAllWorkflowLocks if Object is not Unstructured type

### ISSUE THREAD

**Issue by sarabala1979** [argoproj/argo#3503]
panic: runtime error: invalid memory address or nil pointer dereference 
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x155d0c7] 
goroutine 174 [running]: 
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0) /go/pkg/mod/k8s.io/apimachinery@v0.17.5/pkg/util/runtime/runtime.go:55 +0x105 panic(0x17aeaa0, 0x2931830) 
/usr/local/go/src/runtime/panic.go:679 +0x1b2 github.com/argoproj/argo/workflow/util.FromUnstructured(0x0, 0xffffffff00000003, 0x19f7f9a, 0x28)
/go/src/github.com/argoproj/argo/workflow/util/util.go:128 +0x47
github.com/argoproj/argo/workflow/controller.(*WorkflowController).releaseAllWorkflowLocks(0xc00047bc00, 0x182c000, 0xc000a084c0) 
/go/src/github.com/argoproj/argo/workflow/controller/controller.go:842 +0x50 github.com/argoproj/argo/workflow/controller.(*WorkflowController).addWorkflowInformerHandlers.func4(0x182c000, 0xc000a084c0) 
/go/src/github.com/argoproj/argo/workflow/controller/controller.go:660 +0x8a 
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnDelete(...) /go/pkg/mod/k8s.io/client-go@v0.17.5/tools/cache/controller.go:212 
k8s.io/client-go/tools/cache.FilteringResourceEventHandler.OnDelete(0x1a873a0, 0x1c6f6c0, 0xc0006aeea0, 0x182c000, 0xc000a084c0) 
/go/pkg/mod/k8s.io/client-go@v0.17.5/tools/cache/controller.go:254 +0x69 
k8s.io/client-go/tools/cache.(*processorListener).run.func1.1(0x203000, 0x0, 0x0) 
/go/pkg/mod/k8s.io/client-go@v0.17.5/tools/cache/shared_informer.go:660 +0x1d6 
k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff(0x989680, 0x3ff0000000000000, 0x3fb999999999999a, 0x5, 0x0, 0xc000ab7dd8, 0x194f460, 0x0) 
/go/pkg/mod/k8s.io/apimachinery@v0.17.5/pkg/util/wait/wait.go:292 +0x51 
k8s.io/client-go/tools/cache.(*processorListener).run.func1() 
/go/pkg/mod/k8s.io/client-go@v0.17.5/tools/cache/shared_informer.go:652 +0x79 
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00054df40) 
/go/pkg/mod/k8s.io/apimachinery@v0.17.5/pkg/util/wait/wait.go:152 +0x5e 
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000ab7f40, 0xdf8475800, 0x0, 0x42db01, 0xc0000adb00) 
/go/pkg/mod/k8s.io/apimachinery@v0.17.5/pkg/util/wait/wait.go:153 +0xf8 
k8s.io/apimachinery/pkg/util/wait.Until(...) 
/go/pkg/mod/k8s.io/apimachinery@v0.17.5/pkg/util/wait/wait.go:88 
k8s.io/client-go/tools/cache.(*processorListener).run(0xc000394880) 
/go/pkg/mod/k8s.io/client-go@v0.17.5/tools/cache/shared_informer.go:650 +0x9b 
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc0002c54f0, 0xc0005d1fd0) 
/go/pkg/mod/k8s.io/apimachinery@v0.17.5/pkg/util/wait/wait.go:71 +0x59 created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start 
/go/pkg/mod/k8s.io/apimachinery@v0.17.5/pkg/util/wait/wait.go:69 +0x62****

**Comment by sarabala1979** [comment]
@duongnt I am trying to understand the scenario when the informer will get nil obj. can you provide me more information about what you are trying to do?

**Comment by alexec** [comment]
@sarabala1979 I think we can get nil on error, so we need to cater for them. I think we typically just ignore them.

**Comment by alexec** [comment]
@sarabala1979 does this make master non-viable?

**Comment by sarabala1979** [comment]
yes

**Comment by duongnt** [comment]
@alexec I'm not sure if `stable` is also non-viable or is it just me, but I'm getting 

```
runtime error: invalid memory address or nil pointer dereference" stack="goroutine 343 [running]:
runtime/debug.Stack(0xc05fda1f51, 0x173d180, 0x28720d0)
  /usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).operate.func2(0xc0023d40b0)
  /go/src/github.com/argoproj/argo/workflow/controller/operator.go:164 +0xc4
panic(0x173d180, 0x28720d0)
  /usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).addOutputsToLocalScope(0xc0023d40b0, 0xc002a460a0, 0x15, 0xc0024fa540, 0xc002071a90)
  /go/src/github.com/argoproj/argo/workflow/controller/operator.go:2072 +0x493
github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).buildLocalScope(0xc0023d40b0, 0xc002071a90, 0xc002a460a0, 0x15, 0xc0023ddb80)
 /go/src/github.com/argoproj/argo/workflow/controller/operator.go:2050 +0xaa
github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).buildLocalScopeFromTask(0xc0023d40b0, 0xc0018ddea0, 0xc001001ce0, 0x0, 0x0, 0x0)
  /go/src/github.com/argoproj/argo/workflow/controller/dag.go:475 +0x24c
github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).resolveDependencyReferences(0xc0023d40b0, 0xc0018ddea0, 0xc001001ce0, 0xf, 0x0, 0x0)
  /go/src/github.com/argoproj/argo/workflow/controller/dag.go:485 +0x5d
github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).executeDAGTask(0xc0023d40b0, 0xc0018ddea0, 0xc003465870, 0xf)
  /go/src/github.com/argoproj/argo/workflow/controller/dag.go:372 +0x7e6
github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).executeDAG(0xc0023d40b0, 0xc002520160, 0x1f, 0xc0024faa00, 0xc0005167b0, 0x25, 0xc0048778c0, 0x1bba5a0, 0xc0023d4160, 0xc00243def0, ...)
  /go/src/github.com/argoproj/argo/workflow/controller/dag.go:231 +0x2d6
github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).executeTemplate(0xc0023d40b0, 0xc002520160, 0x1f, 0x1bba5a0, 0xc0023d4160, 0xc0024fa980, 0x0, 0x0, 0x0, 0x0, ...)
  /go/src/github.com/argoproj/argo/workflow/controller/operator.go:1517 +0x1de4
github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).operate(0xc0023d40b0)
  /go/src/github.com/argoproj/argo/workflow/controller/operator.go:290 +0x125d
github.com/argoproj/argo/workflow/controller.(*WorkflowController).processNextItem(0xc000097c00, 0x0)
 /go/src/github.com/argoproj/argo/workflow/controller/controller.go:433 +0x8c2
github.com/argoproj/argo/workflow/controller.(*WorkflowController).runWorker(0xc000097c00)
 /go/src/github.com/argoproj/argo/workflow/controller/controller.go:359 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc002e4f020)
  /go/pkg/mod/k8s.io/apimachinery@v0.16.7-beta.0/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc002e4f020, 0x3b9aca00, 0x0, 0x1, 0xc0000abc80)
  /go/pkg/mod/k8s.io/apimachinery@v0.16.7-beta.0/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc002e4f020, 0x3b9aca00, 0xc0000abc80)
  /go/pkg/mod/k8s.io/apimachinery@v0.16.7-beta.0/pkg/util/wait/wait.go:88 +0x4d
created by github.com/argoproj/argo/workflow/controller.(*WorkflowController).Run
 /go/src/github.com/argoproj/argo/workflow/controller/controller.go:172 +0x975```

with the stable build as well.

**Comment by sarabala1979** [comment]
@duongnt I think this is a different panic. Can you create new bug issue?

**Comment by duongnt** [comment]
@sarabala1979 Yes, i just created https://github.com/argoproj/argo/issues/3505

**Comment by sarabala1979** [comment]
@duongnt thanks
