### ISSUE TITLE
Does argo support IAM Roles via service accounts using OIDC?

### ISSUE THREAD

**Issue by pc-mreeves** [argoproj/argo#3531]
# Summary

I'd like to know if argo supports pod level iam via service account IAM role annotations
References:
https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/
https://docs.aws.amazon.com/eks/latest/userguide/specify-service-account-role.html

# Motivation

Currently the argo IAM privileges to access S3, etc. come from the EKS Worker's Instance Profile and Role (or AWS creds via env vars). Ideally they could be limited to only the access Argo needs via this process.

From the link above:
```
$ kubectl get sa my-serviceaccount -o yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/eksctl-irptest-addon-iamsa-default-my-serviceaccount-Role1-UCGG6NDYZ3UE
  name: my-serviceaccount
  namespace: default
```

It looks like you access AWS using the aws-sdk-go and IIRC this is fully supported by default.
https://github.com/aws/aws-sdk-go/blob/master/CHANGELOG.md#release-v11928-2019-05-10
```
Release v1.19.28 (2019-05-10)
Service Client Updates
aws/endpoints: Updated Regions and Endpoints metadata.
service/glue: Updates service API and documentation
AWS Glue now supports specifying existing catalog tables for a crawler to examine as a data source. A new parameter CatalogTargets is added to the CrawlerTargets data type.
service/sts: Updates service API, documentation, and examples
AWS Security Token Service (STS) now supports passing IAM Managed Policy ARNs as session policies when you programmatically create temporary sessions for a role or federated user. The Managed Policy ARNs can be passed via the PolicyArns parameter, which is now available in the AssumeRole, AssumeRoleWithWebIdentity, AssumeRoleWithSAML, and GetFederationToken APIs. The session policies referenced by the PolicyArn parameter will only further restrict the existing permissions of an IAM User or Role for individual sessions.
```

**Comment by sarabala1979** [comment]
S3 will support IAM assume role based access. you can specify the RoleARN which it needs to be assume.

```
      artifacts:
      - name: message
        path: /tmp
        s3:
          endpoint: s3.amazonaws.com
          bucket: my-bucket
          key: path/in/bucket/hello_world.txt.tgz
          // RoleARN is the Amazon Resource Name (ARN) of the role to assume.
	  roleARN: arn:aws:iam::123456789012:role/eksctl-irptest-addon-iamsa-default-my-serviceaccount-Role1-UCGG6NDYZ3UE

**Comment by jessesuen** [comment]
We support this by specifying the ARN in the S3 artifact itself, but in order to support based on pod annotation, we need to upgrade the minio client. Duping this to https://github.com/argoproj/argo/issues/2748
