### ISSUE TITLE
Argo Server Support TTL

### ISSUE THREAD

**Issue by bpayt2** [argoproj/argo#3538]
# Summary

Add a TTL setting for Argo Server

# Motivation

Our company has a requirement of a 15 minute TTL for any web application. I would like to know if the Argo Server can support a TTL setting. 

# Proposal

Add a TTL option to the Argo Server YAML

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by simster7** [comment]
Can you clarify? TTL for what? There is already a field to set TTL for Workflows, but I don't seem to understand what "TTL for any web application" means in this context

**Comment by bpayt2** [comment]
@simster7  My apologies - TTL for session timeout. User authenticate via bearer token; but are really never logged off the server. I would like to have a session timeout on the server.

**Comment by simster7** [comment]
Gotcha, I will bring this up with the team and get back to you

**Comment by simster7** [comment]
Hey @bpayt2 the bearer token is actually managed by K8s, we are just a pass through service and don't control its life cycle. If you want more control over auth, you can set up and use SSO with whatever preferences you'd desire.
