### ISSUE TITLE
New UI editor should default to YAML

### ISSUE THREAD

**Issue by foobarbecue** [argoproj/argo#3543]
# Summary

It's nice that we can now edit in both JSON and YAML in the UI, but strange that it comes up JSON-first, since Argo and Kubernetes are generally thought of as YAML-based and the user expects to interact with YAML. YAML is also more succinct than JSON.

# Proposal

All editors should display in YAML by default.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by mac9416** [comment]
If I recall correctly, JSON is default because the YAML version does not support autocomplete. (feature demo: https://www.youtube.com/watch?v=IVDhZuo_cv4)

**Comment by foobarbecue** [comment]
Ok... does somebody think that's a good reason? You kinda gotta pick a lane here. Can't have all the docs in YAML and the interface in JSON.

**Comment by simster7** [comment]
Perhaps we can simply store a user's preference in local storage? That way a user who prefers YAML won't have to switch every time

**Comment by alexec** [comment]
I think it would be fine to start in YAML, as long as the text states something like "YAML supports basic completion, full auto-completion is available when switching to JSON"

**Comment by alexec** [comment]
This is a small UI only change anyone could do.

**Comment by rbreeze** [comment]
Addressed in [#3560](https://github.com/argoproj/argo/pull/3560)

**Comment by alexec** [comment]
Available for testing in [v2.10.0-rc1](https://github.com/argoproj/argo/releases/tag/v2.11.0-rc1).
