### ISSUE TITLE
[bug] localhost not point to 127.0.0.1

### ISSUE THREAD

**Issue by lonsdale8734** [argoproj/argo#3564]
https://github.com/argoproj/argo/blob/13b1d3c19e94047ae97a071e4468b1050b8e292b/server/apiserver/argoserver.go#L232

`endpoint` should be explicit set as `127.0.0.1` but `localhost`. There are cases `localhost` is not resolved to 127.0.0.1

**Comment by alexec** [comment]
Would you like to submit a PR to fix?

**Comment by lonsdale8734** [comment]
Finally, maybe It's a bug of go net. https://github.com/golang/go/issues/22846 .
In my environment, this can be fixed with `GODEBUG=netdns=cgo` or add `echo "hosts: files dns" > /etc/nsswitch.conf` to docker image.

**Comment by alexec** [comment]
@lonsdale8734 would you like to submit a PR to fix?
