### ISSUE TITLE
Add ability to automatically decompress zipped artifacts

### ISSUE THREAD

**Issue by alexcapras** [argoproj/argo#3585]
# Summary

Currently, the executer has the ability to automatically unpack tar-balled artifacts (.tar.gz). It might be nice to add the ability to do the same for zip files (.zip).

# Motivation

Sometimes artifacts need to be zipped instead of tarred, but it's nice to still have the auto-unpack functionality.

# Proposal

In executor.go, we check if an artifact is a tarball, using function `isTarball` and the artifact is untarred using `untar`. I propose we add similar functions for `isZip` and `unzip` to handle the zip usecase.

https://github.com/argoproj/argo/blob/cdc935ae76b3d7cc50a486695b40ff2f647b49bc/workflow/executor/executor.go#L184

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by alexec** [comment]
Would you like to submit a PR for this feature?

**Comment by alexcapras** [comment]
just raised a PR: https://github.com/argoproj/argo/pull/4068/files
