### ISSUE TITLE
Create default S3 bucket if not present

### ISSUE THREAD

**Issue by alexcapras** [argoproj/argo#3586]
# Summary

When writing output S3 artifacts to a bucket (e.g. default bucket), if the specified bucket doesn't exist, the execution fails. A message is shown in the Argo UI saying: `failed to save outputs: timed out waiting for the condition`.

I propose we add the option to enable the auto-creation of the required S3 bucket if it does not exist.

# Motivation

In a newly bootstrapped environment, the S3 bucket might not exist initially.

# Proposal

In the Save method in s3.go, check if the bucket exists and create it if it doesn't. (Could make it configurable via Config Map).

https://github.com/argoproj/argo/blob/cdc935ae76b3d7cc50a486695b40ff2f647b49bc/workflow/artifacts/s3/s3.go#L84

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by alexec** [comment]
This is a great idea. Would you like to submit a PR?

**Comment by alexcapras** [comment]
I'm looking into it atm

**Comment by alexcapras** [comment]
I've raised 2 PRs for this:
- (pkg) https://github.com/argoproj/pkg/pull/29
- (argo) https://github.com/argoproj/argo/pull/4098

The argo PR depends on pkg being merged first
