### ISSUE TITLE
Kubectl pods aren't running argo

### ISSUE THREAD

**Issue by jonmun93** [argoproj/argo#3601]
Hi, 

I'm really new to Kubernetes and especially Argo. I'm just following the instructions on "https://argoproj.github.io/argo/quick-start/" but perhaps I've done something wrong.

I'm using WSL 2.0 (Ubuntu) on Windows 10.
My Kubernetes cluster is from Docker for desktop.
Kubectl version: 1.16
Docker version: 19.03.8
Argo version: 2.10

I tried to run:

`kubectl -n argo port-forward deployment/argo-server 2746:2746`

but I get the error message "_error: unable to forward port because pod is not running. Current status=Pending_"

so I check the status of my pods:

NAME                                  READY   STATUS    RESTARTS   AGE
argo-server-779cc5bb79-h27zl          0/1     Pending   0          11m
minio                                 0/1     Pending   0          11m
postgres-67658b9b5b-gbwtn             0/1     Pending   0          11m
workflow-controller-8dd6bff96-pmzwc   0/1     Pending   0          11m

None of my pods are running and the namespace has existed for 11 minutes.

These are the only two commands I have done:

```
kubectl create ns argo
kubectl apply -n argo -f https://raw.githubusercontent.com/argoproj/argo/stable/manifests/quick-start-postgres.yaml
```

I skipped `kubectl create clusterrolebinding...` since I'm running this locally. Anyone know what I've skipped?

**Comment by simster7** [comment]
You can run `kubectl describe pod <POD_NAME>` to see why the Pod hasn't been started. In your example `<POD_NAME>` would be `workflow-controller-8dd6bff96-pmzwc`

**Comment by jonmun93** [comment]
Thanks!

This was the error message I got:

```
Type     Reason            Age        From               Message
  ----     ------            ----       ----               -------
  Warning  FailedScheduling  <unknown>  default-scheduler  0/1 nodes are available: 1 node(s) were unschedulable.
```

So I do a `kubectl get nodes`

```
NAME             STATUS                     ROLES    AGE     VERSION
docker-desktop   Ready,SchedulingDisabled   master   6d19h   v1.16.6-beta.0`
```

So, I'm guessing I need to enable scheduling for docker-desktop? I didn't even disable it. I've been Googling how to enable the scheduling and I can't seem to find the answer.

Does anyone know what I'm supposed to do here?

**Comment by jonmun93** [comment]
Okay, so I thought I had it but it still isn't working.

I ran 

`kubectl describe nodes`

and got
```
Name:               docker-desktop
Roles:              master
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/os=linux
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=docker-desktop
                    kubernetes.io/os=linux
                    node-role.kubernetes.io/master=
Annotations:        kubeadm.alpha.kubernetes.io/cri-socket: /var/run/dockershim.sock
                    node.alpha.kubernetes.io/ttl: 0
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Tue, 21 Jul 2020 12:52:23 +1000
**Taints:             node.kubernetes.io/unschedulable:NoSchedule**
```

So I did some Googling and used this command to try and remove the taint.

 `kubectl taint nodes --all node.kubernetes.io/unschedulable:NoSchedule-`

Which got me the following output.
`node/docker-desktop untainted`

So I check the node again and it's still disabled.

`kubectl get nodes`

NAME             STATUS                     ROLES    AGE     VERSION
docker-desktop   Ready,SchedulingDisabled   master   6d19h   v1.16.6-beta.0

When I describe the node, nothing has changed.

**Comment by jonmun93** [comment]
Okay, so I wasn't able to resolve it by running commands so I just clicked on "Reset Kubernetes Cluster" in the Docker for desktop settings which is disappointing and now I can get my Argo server running just fine.

Funnily enough, I tried doing the exact same thing yesterday and it didn't work...

Something about the definition of insanity...
