### ISSUE TITLE
Using argo to build and push docker image, parameter issues

### ISSUE THREAD

**Issue by LazyBrush** [argoproj/argo#3619]
# Summary

I am trying to use argo to build a docker image and push to a docker repo.
This is using config from various examples 'steps', 'docker in docker sidecar', etc.

However, I cannot seem to pass parameters or to use them.

In my spec section I have

<pre> 
  arguments:
    parameters:
    - name: dockerrepo
      value: some.machine:5000/home
</pre>

In my steps section I have
<pre>
    - - name: docker-build
        template: build-img         
        arguments:
          parameters:
          - name: myrepo
            value: myrepo-name:5000/home
            #value: "{{workflow.parameters.dockerrepo}}"
</pre>

In the 'build-img' section I have
<pre>
  - name: build-img
    inputs:
      parameters:
      - name: myrepo
      artifacts:
      - name: django-src
        path: /src
    container:
      image: docker:17.10
      command: [sh, -c]
      args: ["
        until docker ps; do sleep 3; done &&
        echo {{inputs.parameters}} 
      "]
      env:
      - name: DOCKER_HOST
        value: 127.0.0.1
      workingDir: /src 
    sidecars:
    - name: dind
      image: docker:18.09.4-dind
      securityContext:
        privileged: true
      mirrorVolumeMounts: true
</pre>

With this and running with 
<pre>
argo submit -n argo --watch -p dockerrepo="myrepo-cmdline:5000/home"  build.yaml -s 127.0.0.1:9000
</pre>
It runs and the output of the echo is (see the strange characters prepended to the value)
<pre>
2020-07-28T16:11:01.084673816Z [{name:myrepo,value:\u0008\u0001\u0010\u0000\u001a\u0015myrepo-name:5000/home}]
</pre>
and I also see from the argo command (again something in front of the repo name)
<pre>
Parameters:          
  dockerrepo:        {1 0 myrepo-cmdline:5000/home}
</pre>

If I try with 'echo {{inputs.parameters.myrepo}}' argo fails to run and I get
<pre>
2020/07/28 16:19:52 Failed to submit workflow: rpc error: code = Unknown desc = templates.clone-and-do-stuff.steps[2].docker-build templates.build-img invalid character 'x' in string escape code
</pre>
If I try with the commented out 'value: "{{workflow.parameters.dockerrepo}}"' argo fails to run and I get
<pre>
2020/07/28 16:22:22 Failed to submit workflow: rpc error: code = Unknown desc = templates.clone-and-do-stuff invalid character 'x' in string escape code
</pre>

I am not sure what I am doing wrong.  Can I have some help please?

thanks!

<pre>
argo: v2.10.0-rc1
  BuildDate: 2020-07-17T19:39:25Z
  GitCommit: 616c79df09c435fa7659bf7e5194529d948ee93b
  GitTreeState: clean
  GitTag: v2.10.0-rc1
  GoVersion: go1.13.4
  Compiler: gc
  Platform: linux/amd64
argo-server: v2.9.3
  BuildDate: 2020-07-18T19:09:09Z
  GitCommit: 9407e19b3a1c61ad4043e382484fd0b6b15574f2
  GitTreeState: clean
  GitTag: v2.9.3
  GoVersion: go1.13.4
  Compiler: gc
  Platform: linux/amd64
</pre>

**Comment by LazyBrush** [comment]
Trying to narrow this down.   The example argo/examples/global-parameters.yaml also does not work for me and I get the same error with:

<pre>
argo -n argo submit hello2.yaml -p message="darn gosh"  -s 127.0.0.1:9000
</pre>

But it works if I change 

<pre>
args: ["{{workflow.parameters.message}}"]
</pre>

For a fixed string

<pre>
args: ["boom"]
</pre>

**Comment by LazyBrush** [comment]
FIXED

Changing argo cli from v2.10.0-rc1  to v2.10.0-rc4 fixed this issue.

**Comment by thedewpoint** [comment]
hey @LazyBrush did you ever get your docker image build and push workflow working? I'm trying to do the same but struggling to find a working example. Thank you!

**Comment by alexec** [comment]
https://raw.githubusercontent.com/argoproj-labs/argo-workflows-catalog/master/templates/buildkit/manifests.yaml

**Comment by thedewpoint** [comment]
@alexec thank you!

**Comment by sanzenwin** [comment]
> https://raw.githubusercontent.com/argoproj-labs/argo-workflows-catalog/master/templates/buildkit/manifests.yaml

Thanks 💯
