### ISSUE TITLE
Re-submitted workflows do not carry over labels

### ISSUE THREAD

**Issue by alexec** [argoproj/argo#3622]
When you re-submit a workflow, labels for templates should remain?

workflows.argoproj.io/resubmitted-from-workflow

**Comment by jessesuen** [comment]
I agree we should carry forward existing labels (aside from the ones used functionally e.g. completed=true)

**Comment by alexec** [comment]
Available in [v2.10.0-rc7](https://github.com/argoproj/argo/releases/tag/v2.10.0-rc7).

**Comment by alexec** [comment]
Available for testing in [v2.10.0-rc1](https://github.com/argoproj/argo/releases/tag/v2.11.0-rc1).
