### ISSUE TITLE
Unable to use SSO with redirect URL pointing to a Ingress https URL 

### ISSUE THREAD

**Issue by sudarshntn** [argoproj/argo#3626]
ArgoWorkflow version 2.9.4

**Issue:**
when we try to access the argo workflow url and try to login we are getting below error:
failed to verify token: failed to verify signature: fetching keys oidc: failed to decode keys: expected Content-Type = application/json, got "application/jwk-set+json": illegal base64 data at input byte 43 {
```
  "keys": [
    {
      "kty": "RSA",
      "alg": "RS256",
      "e": "AQAB",
      "kid": "kdMGsVSWsregfrtgrtggHbs8vy",
      "use": "sig",
      "n": "2lndfggggdxrKs836yrbdIWOCWzQ4P0ieNr0HEyYC8zfc2HfatPJkjQtbZBua9ylq6NoP-wAql8JgItwAcPUJLztD5LQ2BET-TWgV5xrRMgrAhU6MbVRi4E8JertregregjqrLu-U2kCHKeK5ouBloinvQyTAdGzfFUc8afefserfjYOXRxsl5CxpQGUQrFQfmtgIhlr1Z-dsqyc6n9l94lzpdfgf8OOK8b1LeFxIC7nrO2oidQ",
      "x5t#S256": "duWB_-0jRqu_mxx4pH4cgffrgr4t4q1i6X5GA="
    }
  ]
}
```
**Steps followed:**
When deploying Argo Workflow we have updated the configmap with the SSO credentials / details like
```
 config: "containerRuntimeExecutor: kubelet  \nartifactRepository:\n  archiveLogs:
    true\n  s3:\n    accessKeySecret:\n      key: accesskey\n      name: argo-s3-creds\n
    \   secretKeySecret:\n      key: secretkey\n      name: argo-s3-creds\n    bucket:
    \"argo-workflow-bucket-15987261\"\n    endpoint: \"s3.us-staage.appdomain.cloud\"\n
    \   insecure: true\nsso:\n  clientId:\n    key: client.ID\n    name: argo-oidc-creds\n
    \ clientSecret:\n    key: client.Secret\n    name: argo-oidc-creds\n  issuer:
    \"https://test1.xyz.com\"\n  redirectUrl: \"https://devops-argoworkflow.xyz.com/oauth2/callback\"\n"
```
Also we have updated the deployment YAML file if argo-server to below details so that it is by default enabled to SSO auth-mode.
```
containers:
      - args:
        - server
        - --auth-mode
        - sso
        image: argoproj/argocli:v2.9.3
        imagePullPolicy: IfNotPresent
        name: argo-server
```
At the deployment time we are setting the Ingress with TLS certificate for this instance and use this as the redirect URL in the SSO configuration configmap as above.

**Comment by alexec** [comment]
It is unclear when this error is happening. Can I ask:

* Are you using an ingress? Are you using `BASE_HREF` or and reverse proxy? 
* Which actual request fails? Can you provide the HTTP request logs from you browser network console?

**Comment by nvenkatapavan** [comment]
@alexec
Thanks for the reply. 

Yes we are using ingress and here is the ingress yaml file
`
apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    labels:
      chart: argo-0.9.9
      heritage: Tiller
      release: argo
    name: argo-server
    namespace: argo
  spec:
    rules:
    - host: devops-argoworkflow.xyz.com
      http:
        paths:
        - backend:
            serviceName: argo-server
            servicePort: 2746
    tls:
    - hosts:
      - devops-argoworkflow.xyz.com
      secretName: mysecrets-tls
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
`

Logs from Network console:

**Request:**

`
Request URL: https://devops-argoworkflow.xyz.com/oauth2/callback?code=5f21a40da950c39343877a1aba&state=IXLcjas224Ft&nonce=&redirect_uri=https://devops-argoworkflow.xyz.com/oauth2/callback
Request Method: GET
Status Code: 401 Unauthorized
Remote Address: 162.33.128.112:443
Referrer Policy: no-referrer-when-downgrade
`
**Response:**

`
failed to verify token: failed to verify signature: fetching keys oidc: failed to decode keys: expected Content-Type = application/json, got "application/jwk-set+json": illegal base64 data at input byte 43 {
 "keys": [
    {
      "kty": "RSA",
      "alg": "RS256",
      "e": "AQAB",
      "kid": "kdMGsVSWsregfrtgrtggHbs8vy",
      "use": "sig",
      "n": "2lndfggggdxrKs836yrbdIWOCWzQ4P0ieNr0HEyYC8zfc2HfatPJkjQtbZBua9ylq6NoP-wAql8JgItwAcPUJLztD5LQ2BET-TWgV5xrRMgrAhU6MbVRi4E8JertregregjqrLu-U2kCHKeK5ouBloinvQyTAdGzfFUc8afefserfjYOXRxsl5CxpQGUQrFQfmtgIhlr1Z-dsqyc6n9l94lzpdfgf8OOK8b1LeFxIC7nrO2oidQ",
      "x5t#S256": "duWB_-0jRqu_mxx4pH4cgffrgr4t4q1i6X5GA="
    }
  ]
}
`

**Comment by alexec** [comment]
There is a lot of moving parts here. The "failed to verify token" error comes because the `id_token` cannot be verified, specifically because the content-type is "application/jwk-set+json" and must be "application/json". 

https://github.com/coreos/go-oidc/blob/v2/oidc.go#L415

Can you contact your OIDC provider (are you using Auth0?) and determine why they are sending this content type please?

**Comment by sudarshntn** [comment]
@alexec our OIDC provider supports the JWK-set+json following these standards - https://tools.ietf.org/html/rfc7517
Does Argo workflow also follow the same.
