### ISSUE TITLE
Does upgrading Argo affect workflows that are currently running? 

### ISSUE THREAD

**Issue by chriswwalz** [argoproj/argo#3633]
# Summary

What do you want to know about this project?

I know how to write workflows, submit workflows and interact with the web api 

# Motivation

Why do you need to know this, any examples or use cases you could include?

We run many workflows in Argo and there is no window to upgrade

**Comment by simster7** [comment]
Yes, the new controller will pick up workflows exactly where they were left off by the old controller. We almost always (99%+) ensure that new versions are backwards compatible, but we don't guarantee it. Because of this, for best results upgrade Argo when there are no Workflows running.

**Comment by chriswwalz** [comment]
Okay thanks!
