### ISSUE TITLE
How to get generateName inside workflow

### ISSUE THREAD

**Issue by sh-tatsuno** [argoproj/argo#3641]
# Summary

I want to get generateName hash inside workflow. But how can I do?

# Motivation

Our team posts workflow results to slack channels so that we could notice them immediately.
So, I want to attach a direct link to the results of workflows to the posts.

In this case, I assume that it is necessary to know generateName in the job.
e.g ) https://job-domain/workflows/{prefix-}{generatedName}

**Comment by simster7** [comment]
You can use `{{workflow.name}}`

**Comment by sh-tatsuno** [comment]
Thank you. quite appreciated!
