### ISSUE TITLE
[Argo API] get a list of workflows from a list of names

### ISSUE THREAD

**Issue by hadim** [argoproj/argo#3642]
Is that possible to get a list of workflows (from one single HTTP call) from a list of workflow's names?

I tried something similar to:

```python
params["listOptions.fieldSelector"] = f"items.metadata.name in {workflow_names}"
```

With `workflow_names` being a list of names but it API returns a not supported error.

**Comment by alexec** [comment]
Try `listOptions.fieldSelector=metadata.name in (...)` (Ii.e. remove `items`) - if that does not work, I'm not sure what would.

**Comment by hadim** [comment]
I tried without `items` too but the same error. That being said the issue could in the way I format the list with `[]` instead of `()`. I will report here.

**Comment by simster7** [comment]
[`fieldSelector` does not support the `in` operation, unfortunately.](https://kubernetes.io/docs/concepts/overview/working-with-objects/field-selectors/)

**Comment by jessesuen** [comment]
This doesn't look possible with K8s APIs.

**Comment by hadim** [comment]
Isn't that possible to have this logic on the argo server side? That would save an external clients multiple calls.
