### ISSUE TITLE
Argo CLI - argo delete --older no longer works

### ISSUE THREAD

**Issue by prateekkhera** [argoproj/argo#3695]
## Summary 

--older flag in `argo delete` no longer works. It used to work with previous versions of argo CLI/ argo controller

## Diagnostics

Argo v2.9.2
Argo CLI - v2.9.2

Please refer below:

![image](https://user-images.githubusercontent.com/22524153/89616137-76a5c400-d8a5-11ea-9dd6-4c374017f386.png)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by simster7** [comment]
Will take a look

**Comment by prateekkhera** [comment]
Thanks @simster7 , also one issue(unrelated, because of which we resorted to a cron workflow that does cleanup with argo delete --older).

The `successfulJobsHistoryLimit`, `failedJobsHistoryLimit` with cron workflow is not working for us. I tested with simple cron workflows and works fine. But, in our cron, we are calling workflow templates using `templateRef` which in turn calls for another workflow template using `templateRef` that has the container definition. Could this nesting be causing the issue? Here's the snippet for cron:



![image](https://user-images.githubusercontent.com/22524153/89704647-36ad1280-d973-11ea-806f-74733b0592de.png)

**Comment by alexec** [comment]
I said I would look into this as I thought these was a test in places is because the test `TestWorkflowDeleteOlder` runs `argo delete --older 0s -l argo-e2e` and therefore has a label flag.

This hints at a workaround for this:

```bash
argo delete --older 0s -l '!foo`
```

i.e. run the command with `l` and a label that does not exist

**Comment by simster7** [comment]
> I said I would look into this as I thought these was a test in places is because the test TestWorkflowDeleteOlder runs argo delete --older 0s -l argo-e2e and therefore has a label flag.

This happens because the presence of a label flag passes this if condition and applies the delete opts.

https://github.com/argoproj/argo/blob/6134a56540e9bbb744fe06ce5be69eca99e95b32/cmd/argo/commands/delete.go#L48-L49

**Comment by simster7** [comment]
> The successfulJobsHistoryLimit, failedJobsHistoryLimit with cron workflow is not working for us. I tested with simple cron workflows and works fine. But, in our cron, we are calling workflow templates using templateRef which in turn calls for another workflow template using templateRef that has the container definition

Looking into this

>  Could this nesting be causing the issue? 

I don't think so. Can you open a new issue and provide a sample workflow to reproduce?
