### ISSUE TITLE
Run Steps on Remote Cluster

### ISSUE THREAD

**Issue by hyorigo** [argoproj/argo#3696]
# Summary

We want to figure out best/simplest practice to run steps on remote cluster.

Already read through and tried the [admiraltyio/multicluster-scheduler](https://github.com/admiraltyio/multicluster-scheduler) solution, however it's kinda complicated and overwhelming for our scenarios:

* https://admiralty.io/blog/running-argo-workflows-across-multiple-kubernetes-clusters/
* https://itnext.io/multicluster-scheduler-argo-workflows-across-kubernetes-clusters-ea98016499ca

Working with only Argo itself, is there any possible or solution to let `argo-server` of Argo on one cluster, and `workflow-controller` of Argo to create/watch step pods on the other cluster?

# Motivation

We're building a specific CI/CD based on Argo, for some performance testing or test cases involving GPU nodes scenarios, the step pods should be running on the same remote cluster with the testbed pods. And we want to minimize the changes upon the remote clusters.

**Comment by alexec** [comment]
Argo Workflows is designed to be install into the cluster it is needed for. We do not currently support multi-cluster. See #3523

**Comment by hyorigo** [comment]
@alexec  Thanks for your reply! So it's kinda design problem.

Is it hard/complicated to adjust Argo Workflow Controller for this purpose? Or it's nearly impossible to make such a change since it's the root of Argo and its design.

**Comment by CaramelMario** [comment]
The same. @alexec  Is it a big big change, or maybe possible the fork and make a quick fix for this?
