### ISSUE TITLE
Argo is losing connectivity to K8 pods intermittently

### ISSUE THREAD

**Issue by csandiri11** [argoproj/argo#3698]
Hi,

We deployed argo 2.6.2 and its working fine. But recently we are observing Argo is losing connectivity to its workflows and our inter dependent workflow schema is getting failed with the below errors. is this know issue with this version of Argo or any work around available to get it fixed. 

Error:

**[inf] [01:45:06.689] [00.1GB] [00.0%] [T01] Execution status: Running [Root] 

[err] [01:46:59.373] [00.1GB] [00.0%] [T319] Exit code [1] [Root] 

Unhandled exception. System.AggregateException: One or more errors occurred. (One or more errors occurred. (time="2020-08-06T19:02:22Z" level=fatal msg="the server was unable to return a response in the time allotted, but may still be processing the request (get workflows.argoproj.io model-gbhjq)"))

 ---> System.AggregateException: One or more errors occurred. (time="2020-08-06T19:02:22Z" level=fatal msg="the server was unable to return a response in the time allotted, but may still be processing the request (get workflows.argoproj.io model-gbhjq)")**

```
argo: v2.6.2
BuildDate: 2020-03-12T16:04:25Z
GitCommit: be0a0bb
GitTreeState: clean
GitTag: v2.6.2
GoVersion: go1.13.4
Compiler: gc
Platform: linux/amd64

Kubernetes Version:

Client Version: v1.17.2
Server Version: v1.17.2

Host OS:
Centos 7.7

CNI:
Weave
```
Thank you and appreciate any help or inputs with this issue?

Regards,
CS

**Comment by sarabala1979** [comment]
looks like your k8s API server is not responding argo request.  It might be a network delay or K8s API server is under load. Is this issue happening consistently or intermittently?

**Comment by csandiri11** [comment]
Thank you for reply.

this is happening intermittently. but when I check GRID load and NW activity, its not super busy. seeing the below errors

Unhandled exception. System.AggregateException: One or more errors occurred. (One or more errors occurred. (time="2020-08-06T19:02:22Z" level=fatal msg="the server was unable to return a response in the time allotted, but may still be processing the request (get workflows.argoproj.io model-z69nq)"))
 ---> System.AggregateException: One or more errors occurred. (time="2020-08-06T19:02:22Z" level=fatal msg="the server was unable to return a response in the time allotted, but may still be processing the request (get workflows.argoproj.io model-z69nq)")
 ---> System.Exception: time="2020-08-06T19:02:22Z" level=fatal msg="the server was unable to return a response in the time allotted, but may still be processing the request (get workflows.argoproj.io model-z69nq)"
Unhandled exception. System.AggregateException: One or more errors occurred. (One or more errors occurred. (time="2020-08-06T19:02:22Z" level=fatal msg="the server was unable to return a response in the time allotted, but may still be processing the request (get workflows.argoproj.io model-gbhjq)"))
 ---> System.AggregateException: One or more errors occurred. (time="2020-08-06T19:02:22Z" level=fatal msg="the server was unable to return a response in the time allotted, but may still be processing the request (get workflows.argoproj.io model-gbhjq)")
 ---> System.Exception: time="2020-08-06T19:02:22Z" level=fatal msg="the server was unable to return a response in the time allotted, but may still be processing the request (get workflows.argoproj.io model-gbhjq)"
Unhandled exception. System.AggregateException: One or more errors occurred. (One or more errors occurred. (time="2020-08-07T07:41:23Z" level=fatal msg="etcdserver: request timed out"))
 ---> System.AggregateException: One or more errors occurred. (time="2020-08-07T07:41:23Z" level=fatal msg="etcdserver: request timed out")
 ---> System.Exception: time="2020-08-07T07:41:23Z" level=fatal msg="etcdserver: request timed out"
Unhandled exception. System.AggregateException: One or more errors occurred. (One or more errors occurred. (time="2020-08-07T08:08:46Z" level=fatal msg="etcdserver: request timed out"))
 ---> System.AggregateException: One or more errors occurred. (time="2020-08-07T08:08:46Z" level=fatal msg="etcdserver: request timed out")
 ---> System.Exception: time="2020-08-07T08:08:46Z" level=fatal msg="etcdserver: request timed out"
Unhandled exception. System.AggregateException: One or more errors occurred. (One or more errors occurred. (time="2020-07-30T19:55:44Z" level=fatal msg="Get https://10.96.0.1:443/apis/argoproj.io/v1alpha1/namespaces/default/workflows/model-bssk2: net/http: TLS handshake timeout"))
 ---> System.AggregateException: One or more errors occurred. (time="2020-07-30T19:55:44Z" level=fatal msg="Get https://10.96.0.1:443/apis/argoproj.io/v1alpha1/namespaces/default/workflows/model-bssk2: net/http: TLS handshake timeout")
 ---> System.Exception: time="2020-07-30T19:55:44Z" level=fatal msg="Get https://10.96.0.1:443/apis/argoproj.io/v1alpha1/namespaces/default/workflows/model-bssk2: net/http: TLS handshake timeout"

Thanks,
CS
