### ISSUE TITLE
workflow must be Failed/Error to retry

### ISSUE THREAD

**Issue by lueenavarro** [argoproj/argo#3709]
## Summary 

What happened/what you expected to happen?
I am able to retry a workflow only once, when it fails again, a pop up from the UI says Unable to Retry Workflow. When I checked the logs from argo server, the error says `workflow must be Failed/Error to retry`. 

![image](https://user-images.githubusercontent.com/47080916/89759031-da392700-db1b-11ea-9eb6-85c6cd5a23fa.png)

I have an On Exit pod that saves the status of the workflow to db. When I checked the db, it says that my workflow's status on exit is In Progress

![image](https://user-images.githubusercontent.com/47080916/89759098-fd63d680-db1b-11ea-8b1b-20962dd77190.png)

## Diagnostics

Argo version:
`2.9.5`

Logs from Argo Server
```
time="2020-08-10T06:58:21Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=RetryWorkflow grpc.service=workflow.WorkflowService grpc.start_time="2020-08-10T06:58:20Z" grpc.time_ms=235.086 span.kind=server system=grpc
time="2020-08-10T06:58:21Z" level=error msg="finished unary call with code Unknown" error="workflow must be Failed/Error to retry" grpc.code=Unknown grpc.method=RetryWorkflow grpc.service=workflow.WorkflowService grpc.start_time="2020-08-10T06:58:21Z" grpc.time_ms=23.82 span.kind=server system=grpc
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by simster7** [comment]
Based on your screenshot, it looks like your Workflow actually succeeded, but the `onExit` handler of the Workflow failed. We currently don't consider the `onExit` handler as part of the workflows for retry purposes, but I can see how you would want it to be. I'll discuss with the team and work on a fix if that's our desired behavior

**Comment by sarabala1979** [comment]
Here the workaround, if you think `onExit` template will fail and want to retry, you can add it as a normal step/task end of your DAG/Step instead of `onExit` handler.  Retry works for this case.

**Comment by lueenavarro** [comment]
> 
> 
> Based on your screenshot, it looks like your Workflow actually succeeded, but the `onExit` handler of the Workflow failed. We currently don't consider the `onExit` handler as part of the workflows for retry purposes, but I can see how you would want it to be. I'll discuss with the team and work on a fix if that's our desired behavior

Based from my screenshot, the onExit handler succeeded. Its the step ON-START which failed, ON-START is part of the main workflow, it is not under the onExit.

**Comment by lueenavarro** [comment]
> 
> 
> Here the workaround, if you think `onExit` template will fail and want to retry, you can add it as a normal step/task end of your DAG/Step instead of `onExit` handler. Retry works for this case.

I want to send an email at the end of each workflow regardless of the workflow's status. I'm guessing an on exit handler is the only way to do that?

**Comment by nojvek** [comment]
Regarding retry, I wish the logic was simpler "find the first failed/error node and run everything after it".

Our scenario is that we have check steps the behave more like warnings than failures. The stage-deploy step has `depends: "check-ci || check-ci.Failed"`. We want user to have the ability to retry check-ci if it failed, however don't stop if it failed. 

![image](https://user-images.githubusercontent.com/1018196/98778703-974f4f80-23a7-11eb-9309-9e85653e3b37.png)

However the issue is if one uses `task.Failed` then retry is disabled and doesn't work.
