### ISSUE TITLE
Downloading artifacts from the "Workflow" page fails on minikube

### ISSUE THREAD

**Issue by shrinandj** [argoproj/argo#371]
Artifact download from the "Workflow" page (where each step of the workflow shows up as a circle) fails on minikube. Looks like the browser is given a url by axops which is something like  http://axartifactmanager.axsys:9892/.... which doesn't resolve.

On AWS, the browser gets a url for the S3 bucket, something like: 
https://ax-shri-test-us-west-2.s3.amazonaws.com/shri.test.eng.applatix.net/...

However, the "Artifacts" tab works just fine on minikube as well as AWS.

It seems that axops has two different endpoints for getting artifacts. Only one of them might have been updated recently.

**Comment by sandeepbhojwani** [comment]
@alexmt this may be a UI issue
