### ISSUE TITLE
Slack invite link is no longer active

### ISSUE THREAD

**Issue by laymain** [argoproj/argo#3711]
## Summary 

The slack invitation has expired: https://argoproj.github.io/community/join-slack

Same as #2224, #1789 and #1706

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by simster7** [comment]
I pinged our webmaster to update our link. Will close this when it's working again. Thanks!

**Comment by simster7** [comment]
Link should work now!

**Comment by laymain** [comment]
I can confirm it works, thank you
