### ISSUE TITLE
browser spams /api/v1/workflow-events if 'Timeline' page does not completely load

### ISSUE THREAD

**Issue by bryanisgreat** [argoproj/argo#3718]
## Summary 
Using the web UI, if you leave the 'Timeline' page before it completely loads it will spam requests to `/api/v1/workflow-events/?listOptions.resourceVersion=250320295&fields=result.object.metadata.name,result.object.metadata.namespace,result.object.metadata.resourceVersion,result.object.metadata.uid,result.object.status.finishedAt,result.object.status.phase,result.object.status.startedAt,result.type,result.object.metadata.labels`

The easiest way to reproduce is to load the UI, and click between 'Timeline' and another page like 'Workflow Templates' and back. The more times you do this, ever more requests are sent to the server.   
This can cause very high cpu usage on the argo-server.

Once it gets in this state, the only way to stop the requests is refreshing the page.

![image](https://user-images.githubusercontent.com/49660961/89806953-aabef600-daec-11ea-8eaf-d67c7b1b6f8a.png)

## Diagnostics

Argo version: 2.9.5

argo-server logs are full of messages like this when it is in the failure mode:
```
time="2020-08-10T16:31:37Z" level=error msg="finished streaming call with code Unknown" error="context canceled" grpc.code=Unknown grpc.method=WatchWorkflows grpc.service=workflow.WorkflowService grpc.start_time="2020-08-10T16:31:37Z" grpc.time_ms=405.321 span.kind=server system=grpc
```
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by simster7** [comment]
`/api/v1/workflow-events` is a stream which updates for every new workflow event that the server sees. It seems that the calls on your screenshot are the stream getting opened and closed with the `time` showing how much time the stream was open. From your screenshot it seems that only one stream is open at a time.

For the "context canceled" issue, I recall @alexec working on it recently; perhaps https://github.com/argoproj/argo/pull/3652?

**Comment by bryanisgreat** [comment]
It's hard to capture in a screenshot, but those requests are flooding at about 10/second and have not settled down to a single open request as it may appear (and as you would expect for normal working behavior).

**Comment by alexec** [comment]
The `context cancelled` error occurs (< v2.10) when the client disconnects. I have changed the re-connection code on master.

@bryanisgreat could I ask you to try running `argoproj/argocli:latest` and see if solves your problem?

**Comment by bryanisgreat** [comment]
Hi, I was finally able to revisit this issue and was not able to reproduce with v2.11.1!
