### ISSUE TITLE
Broken link in argo docs

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo#374]
https://dev.applatix.net/app/timeline/jobs/5fb8364a-a79f-11e7-8636-0a58c0a88106;tab=workflow

```
Invalid links found in markdown files:

/src/content/user_guide/timeline/create_job-viewhistory.md:
        [](../../../images/Timeline_Branching_icon_2
  .png)
```

**Comment by alexmt** [comment]
@cyee88 please take a look

**Comment by cyee88** [comment]
Fixed in this commit: 

commit db5f6cb978d5d29a10776eca3402a5e7e42cfb62 (HEAD -> master, origin/master, origin/HEAD)
Author: Calvin Yee <calvin@applatix.com>
Date:   Thu Oct 19 14:49:06 2017 -0700

    Added a period and copied again the path to the missing image
