### ISSUE TITLE
CronWorkflow jobs status history

### ISSUE THREAD

**Issue by xinbinhuang** [argoproj/argo#3742]
# Summary

I am evaluating Argo Workflow for scheduling ETL jobs for my team, and I am trying to find a way to retrieve the job status history for a certain (Cron)Workflow. Is that a way to I can inspect this metadata information?

# Motivation

Why do you need to know this, any examples or use cases you could include?

It's common to retrieve and monitor the history of ETL pipelines, so that we can retrigger failed jobs.

**Comment by simster7** [comment]
Currently the most reliable way to do this is to set up the [workflow archive](https://github.com/argoproj/argo/blob/master/docs/workflow-archive.md). There you'll be able to see every workflow that has completed

**Comment by alexec** [comment]
@simster7 +1

**Comment by xinbinhuang** [comment]
@simster7 @alexec Thanks for the recommendations! I was not aware of this feature before, and I will try it out!
