### ISSUE TITLE
Allow for Parameter usage in Resource Requests/Limits

### ISSUE THREAD

**Issue by nfickas** [argoproj/argo#3755]
**Is your feature request related to a problem? Please describe.**

We are trying to use a parameter from an SQS notification in the resource request/limits field in a template. Since we are able to use parameters in environment variables, we should be able to use them also in the resource request fields.

**Describe the solution you'd like**

I should be able to insert a parameter as a value for a memory limit like so:
```container:
                    image: alpine:latest
                    imagePullPolicy: Always
                    resources:
                      limits:
                        memory: "{{inputs.parameters.object-size}}"
```

**Describe alternatives you've considered**

**Additional context**

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by sarabala1979** [comment]
you can parameterize all `podspec` using podspecpath.
https://github.com/argoproj/argo/blob/master/examples/pod-spec-patch-wf-tmpl.yaml
https://github.com/argoproj/argo/blob/master/examples/pod-spec-patch.yaml
https://github.com/argoproj/argo/blob/master/examples/pod-spec-from-previous-step.yaml

**Comment by alexec** [comment]
We just keep seeing this problem.

**Comment by nfickas** [comment]
Yeah the pod spec patch could be used but is there a good reason to why we shouldn't be able to do it as I described above?

**Comment by elocke** [comment]
agreed, it would be great if my events could tell the workflow how much resources it will need

**Comment by alexec** [comment]
It is technically very hard to fix because the `corev1.Container` must match a resource limit regexp.
