### ISSUE TITLE
How do we auto sync workflow templates from Git to Argo Workflow automatically if there is any change

### ISSUE THREAD

**Issue by sudarshntn** [argoproj/argo#3760]
We want to auto sync the workflow templates that are in Git which is our source of truth to Argo Workflow similar to ArgoCD.

We are using Argo Workflow version 2.9.4

I have a predefined set of workflows which are loaded using the Argo API into the Work and runs perfectly fine when ever there is an event that gets triggered which in turn calls the workflow to execute. Also the sensor (this has definition of workflow steps) templates are committed to git as source of truth.

Question: If I make any changes to the existing sensor (this has definition of workflow steps) templates that are in git, how do I automatically sync the updated templated into ArgoWorkflow?

(Is there some concept similar to AppOfApp that help in auto sync if enabled in ArgoCD)

**Comment by simster7** [comment]
Try [Argo CD](https://github.com/argoproj/argo-cd)?

**Comment by sudarshntn** [comment]
We are already using ArgoCD for our CD flow and there we have enabled the auto sync so any change that we commit in git to the argo application templates it gets sync automatically (using AppOfApp)

Can we use the same for workflow templates to be loaded into Argo Workflow?
@simster7

**Comment by nvenkatapavan** [comment]
@simster7 @alexec We tried ArgoCD to sync argo workflows templates. When we choose ArgoCD helm deploy, helm variables getting conflict argo workflow variables. 

example:
"{{workflow.parameters.appName}}"

**Comment by nvenkatapavan** [comment]
Found one alternative to fix above issue. Using below example we are able to deploy workflows using ArgoCD. Now Helm is not throwing any error. 

{{ printf "{{workflow.parameters.appName}}" }}
