### ISSUE TITLE
Document "emptyDir pattern"

### ISSUE THREAD

**Issue by alexec** [argoproj/argo#3768]
# Summary

When using k8s/kubelet/pns executors, users often need to mount an emptyDir to capture output artifacts.

# Use Cases

We get a lot of questions, so we should document this pattern and link from the executors page:

https://argoproj.github.io/argo/workflow-executors/

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Related to #4059, #3933, #3678, #3252, #2679, #2239, #1667

**Comment by terrytangyuan** [comment]
Looks like this document has been added already. We can close this now? @alexec
