### ISSUE TITLE
Argo web ui crash.

### ISSUE THREAD

**Issue by arnoldcui** [argoproj/argo#3781]
## Summary 

Argo web ui crash.

## Diagnostics

What version of Argo Workflows are you running?

2.8.2+8a

![image](https://user-images.githubusercontent.com/40977489/90217831-d74c7800-de34-11ea-864b-13de7c704a87.png)
![image](https://user-images.githubusercontent.com/40977489/90217845-dadfff00-de34-11ea-9db7-81745a2b4d72.png)

When the templates is null,the argo ui will crash.

I don't know what cause the problem. 
After I delete the workflow from argo cli.The web work normal.

This seems to be a bug of web ui.

**Comment by sarabala1979** [comment]
what CLI version are you using? have you submitted workflow from workflowtemplate using `argo submit --from`?

**Comment by arnoldcui** [comment]
> what CLI version are you using? have you submitted workflow from workflowtemplate using `argo submit --from`?
> It looks like version incompatibility.

The CLI version 
```
➜  ~ argo version
argo: v2.10.0-rc6+cb3536f.dirty
  BuildDate: 2020-08-06T22:47:49Z
  GitCommit: cb3536f9d1dd64258c1c3d737bb115bdab923e58
  GitTreeState: dirty
  GitTag: v2.10.0-rc6
  GoVersion: go1.13.4
  Compiler: gc
  Platform: darwin/amd64
➜  ~
```
It is happend after using `argo submit --from WorkflowTemplate/myTpl`

**Comment by alexec** [comment]
Can you please try with v2.11.5?

**Comment by arnoldcui** [comment]
We have tried v2.10,The crash problem seems fixed.
