### ISSUE TITLE
Fail fast

### ISSUE THREAD

**Issue by alexec** [argoproj/argo#3784]
# Summary

There are uses cases where there is a large DAG (or steps) which are intended to run in sequence, but should fail as soon as any task fails.

# Use Cases

This can be worked around by having sequential steps, but the challenge is that you probably don't want to wait for a large number of tasks to complete before failing, i.e. you explicitly want to run tasks in parallel and then terminate them all when one fails.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by ppapasani1** [comment]
@alexec This is something we are looking for many days. I have long-running tasks, and if anyone of the tasks fail, I want the workflow to exit immediately. Attached a clip from one of my workflows, it has ~700 tasks and ~380th task failed and I don't want the rest of the tasks to be scheduled and complete and then fail. 
![image](https://user-images.githubusercontent.com/37124509/90275490-3ef3ca80-de17-11ea-941e-caee2f3773f6.png)

**Comment by alexec** [comment]
This duplicates #3644
