### ISSUE TITLE
Argo Workflows Training 101

### ISSUE THREAD

**Issue by alexec** [argoproj/argo#3789]
2 hours of virtual training including intended to cover the core competencies when working with Argo Workflows. 

You should be familiar with basics of Kubernetes, such as creating pods.

* Fundamentals of creating workflows - Hello Argo!
* Anatomy of a workflow 
* The service account.
* Artifacts
* Exit Handlers
* Workflow Templates
* Cron Workflows
* Hands-on exercises

To sign-up please give a thumbs-up.

![image](https://user-images.githubusercontent.com/1142830/90285042-f2fd5180-de27-11ea-820c-e392818ebfd1.png)
![image](https://user-images.githubusercontent.com/1142830/90285053-f7c20580-de27-11ea-9c7a-fc80de05b62b.png)
![image](https://user-images.githubusercontent.com/1142830/90285066-fdb7e680-de27-11ea-9335-326f14b24db8.png)

**Comment by alexec** [comment]
https://docs.google.com/presentation/d/1ZEZuxznc-Bx3STjoyS5Vd-zrjvlNaSbgKBn0Qlaidl0/edit?usp=sharing

**Comment by jorik** [comment]
Hey! This sounds very interesting and I'd like join. Will this be a live training session, and if so, in what timezone will it be held?

**Comment by alexec** [comment]
It will be virtual. Likely be at 10am PST/5pm GMT next week.

**Comment by dcherman** [comment]
Other than knowledge of creating Pods, what other pre-reqs would there be?  I'm going to try to do a crash course in Kubernetes basics for some people at my company that are interested in attending, so I'm thinking about what I should plan to cover

Things like:

* Creating and accessing a Kubernetes cluster.  Presumably, `kind` would be sufficient for this training?
* Basic knowledge of a few Kubernetes primitives (Pods, Services, Deployments, how to create them)
* Knowledge of how to port-forward to the cluster to get access to the Argo UI
* Will it be expected that attendees have a working Argo installation, or will they need that ahead of time?

**Comment by alexec** [comment]
[Slides](https://drive.google.com/file/d/1xKFYG0VO4prqvCmLO2wSmnjoX4nZU7Y5/view?usp=sharing)

**Comment by alexec** [comment]
This will be on the 22nd September at 10am-12am PST

**Comment by alexec** [comment]
https://calendar.google.com/event?action=TEMPLATE&tmeid=MjMxMXBmMTU4M2M0dWVoMjc4MThrNm9mbmwgYXJnb3Byb2pAbQ&tmsrc=argoproj%40gmail.com

**Comment by spkane** [comment]
@alexec Will this be recorded for those of us with hard conflicts?

**Comment by alexec** [comment]
Yes.

**Comment by alexec** [comment]
[Slides](https://drive.google.com/file/d/1xKFYG0VO4prqvCmLO2wSmnjoX4nZU7Y5/view?usp=sharing)

**Comment by alexec** [comment]
Done. I will now close the most popular Argo issue ever.
