### ISSUE TITLE
How to handle Argo as an dependency for Kubeflow pipelines. 

### ISSUE THREAD

**Issue by NikeNano** [argoproj/argo#3803]
# Summary

For Kubeflow pipelines Argo Workflows are used. During attempts to do validation of Argo Workflows in the backend of Kubeflow pipelines there are some issues with dependencies on com_github_colinmarc_hdfs that comes from having argo as a dependency. 

For Kubeflow pipelines Bazel is used. To reproduce pull the branch from here: https://github.com/kubeflow/pipelines/pull/3965

Then execute: ``` bazel run //:gazelle -- update-repos --from_file=go.mod & bazel build --action_env=PATH --define=grpc_no_ares=true //backend/...```

The received error message is: 

``` 
Analysis of target '//backend/src/apiserver:apiserver' failed; build aborted: no such package '@com_github_colinmarc_hdfs//': failed to fetch com_github_colinmarc_hdfs: # cd /private/var/tmp/_bazel_niklashansson/b0db32648c4d9475e405b778807c3054/external/com_github_colinmarc_hdfs; git checkout v1.1.4-0.20180805212432-9746310a4d31
error: pathspec 'v1.1.4-0.20180805212432-9746310a4d31' did not match any file(s) known to git
2020/08/18 16:32:04 exit status 1
```

How could this dependency be handle correctly? I am rather new to both golang and Bazel so sorry if I am missing something obviously. 

Thank you!

# Motivation

Why do you need to know this, any examples or use cases you could include?

**Comment by alexec** [comment]
The validate library transitively imports this HDFS dependency:

```
	github.com/colinmarc/hdfs v1.1.4-0.20180805212432-9746310a4d31
```

**Comment by alexec** [comment]
That tag does not exist, try pinning to v1.13:

go get github.com/colinmarc/hdfs@v1.1.3

**Comment by NikeNano** [comment]
Thanks @alexec. When i pin to 1.13 I get the following issues when I run the test for the validation argo workflows in the Kubeflow backend.  

```
 ../../../../../../../../pkg/mod/github.com/argoproj/argo@v2.3.0+incompatible/workflow/artifacts/hdfs/util.go:21:10: options.KerberosClient undefined (type hdfs.ClientOptions has no field or method KerberosClient)
../../../../../../../../pkg/mod/github.com/argoproj/argo@v2.3.0+incompatible/workflow/artifacts/hdfs/util.go:22:10: options.KerberosServicePrincipleName undefined (type hdfs.ClientOptions has no field or method KerberosServicePrincipleName)
```

[Link](https://github.com/kubeflow/pipelines/blob/6ec60a1fcfdff92f990b6855c9d66b86e62ee8f2/backend/src/common/util/template_util_test.go)  to test.

**Comment by NikeNano** [comment]
Get the same error as https://github.com/argoproj/argo/issues/1983 if i pin to v1.1.3 issues discuss but don't get it to work with their solution either.

**Comment by NikeNano** [comment]
Do you know more about the issue @alexec, thanks for your help!

**Comment by alexec** [comment]
hi @NikeNano I'm afraid I don't know how to fix this issue. The is Go modules issue rather than an Argo issue. You'll know if you've tried to import the Kubernetes dependencies Go modules is not the seamless experience of Maven.

**Comment by NikeNano** [comment]
Thanks for the help :)  

> You'll know if you've tried to import the Kubernetes dependencies Go modules is not the seamless experience of Maven.

I am starting to learn that now .... :(

**Comment by dtzar** [comment]
I believe #3991 would help the overall situation.  
Also @NikeNano per https://github.com/kubeflow/pipelines/pull/4477 you shouldn't be using Bazel which also can cause problems.
