### ISSUE TITLE
Re-submitted workflows do not carry over ownerReferences

### ISSUE THREAD

**Issue by yoichiwo7** [argoproj/argo#3818]
## Summary 

When you re-submit workflows with ownerReferences set, the re-submitted workflows do not carry over the ownerReferences.

When you manage Argo Workflow resources in your own CRD, you usually add the CRD resource into ownerReferences of the created Argo Workflow. This enable to cleanup Argo Workflow resources when the owner CRD resource is removed. However, because re-submitted workflows do not carry over ownerReferences, the re-submitted workflows won't be cleaned up.

By carrying over the ownerReferences to re-submitted workflows, you can also cleanup these re-submitted workflows.

**Related Issues:**
- #1736 
- #3622 

**Note:**
I'm not sure this is a bug. Please update to appropriate issue type if necessary.

## Diagnostics

What version of Argo Workflows are you running?

v2.9

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Available for testing in [v2.10.0-rc1](https://github.com/argoproj/argo/releases/tag/v2.11.0-rc1).
