### ISSUE TITLE
Workflow step taking time to start

### ISSUE THREAD

**Issue by mukulikak** [argoproj/argo#382]
Sometimes for dind steps, the container step gets stuck. It is before container is initialized and we can see the log. eventually it starts successfully. if i run the same workflow again it is fine. Attached logs from one such workflow

---------

[SCAN.aqua-docker-image-scan-workflowscan.bd3eb3fab50e914511393e8d67de9766dffb0f3b2b0ecf0ee33673f69e13be7b.log](https://github.com/argoproj/argo/files/1389674/SCAN.aqua-docker-image-scan-workflowscan.bd3eb3fab50e914511393e8d67de9766dffb0f3b2b0ecf0ee33673f69e13be7b.log)

**Comment by pratulw** [comment]
Abhinav can you please triage this

**Comment by abhinavdas** [comment]
As we had discussed earlier, since the step is stuck in stage where it is not even created as a Pod, the step is waiting inside WFE/ADC. @sytianhe Can you repro and verify?

@mukulikak: Can you add steps to repro in the bug?

**Comment by teddybuy** [comment]
Do we have logs that show the step is waiting inside WFE/ADC?

**Comment by sytianhe** [comment]
Cannot reproduce
