### ISSUE TITLE
 argoproj/argoexec no matching manifest for linux/amd64 in the manifest list entries

### ISSUE THREAD

**Issue by alexec** [argoproj/argo#3866]
## Summary 

Latest build should work just fine. Instead, this error:

```bash
docker pull argoproj/argoexec:latest 
latest: Pulling from argoproj/argoexec
no matching manifest for linux/amd64 in the manifest list entries
```

Caused by #3854 ?

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
@dgiebert could this be related?

**Comment by dgiebert** [comment]
Yes fixing this right now, the manifests are still an experimental feature, will create a MR for it

If you are affected by this using the tag latest-linux should work for you

**Comment by alexec** [comment]
I've temporarily built this locally:
```
$ docker run argoproj/argoexec:latest version
argoexec: v2.3.0-rc3
  BuildDate: 2020-08-26T16:33:10Z
  GitCommit: c6b51362eb91f042c63ce64e5c6996fef13c90a7
  GitTreeState: clean
  GitTag: v2.3.0-rc3
  GoVersion: go1.13.4
  Compiler: gc
  Platform: linux/amd64
```

Ignore the version and note the GitCommit.

**Comment by alexec** [comment]
```
020-08-26T20:26:49.9001080Z #36 [argo-build 13/13] RUN . hack/image_arch.sh && ./dist/argo-linux-${IMAGE...
2020-08-26T20:26:50.9508624Z #36 1.042 time="2020-08-26T20:26:50Z" level=fatal msg="invalid configuration: no configuration has been provided"
```

**Comment by dgiebert** [comment]
Seems a bit odd tbh, because it is exactly the same Dockerfile / configuration as linux/amd64 whhich passed right before it.

Also locally it worked, can you maybe retrigger the build. I can check again when I am at home ?

**Comment by alexec** [comment]
The error often occurs when Kubernetes is not installed. You can often reproduce it by running `export KUBECONFIG=/dev/null`. I think this error occurs because there is a call to `argoexec version` to check that it prints "clean" (not "dirty"). I think it would be acceptable to remove this check.

**Comment by dgiebert** [comment]
I can remove the check, but I still think it is a bit odd that it did not happen on the amd64 build.

Any other clues maybe ?

**Comment by alexec** [comment]
https://github.com/argoproj/argo/actions?query=branch%3Amaster+workflow%3A%22Docker+Image+CI%22

As a short term fix, let's just remove it. Priority should be getting builds to work.

**Comment by dgiebert** [comment]
I will try to fix the issue without removing the check, if this won't work I will remove it !
