### ISSUE TITLE
Pass S3 backed artifacts from one dag to another in one workflow.

### ISSUE THREAD

**Issue by sahil-sawhney** [argoproj/argo#3875]
# Summary

I have a workflow that has 1 main dag and then that dag calls templates which are dag in themselves. Now I am having trouble accessing an artifact generated by the main dag into the sub dag. Could you please tell me how should I correctly access the dag. When I try following workflow, it gives error:

> templates:
>   - name: main-template
>     dag:
>       tasks:
>       - name: A			# Task A Generates output artifact named "my-artifact"
>         template: template-A
>       - name: sub-dag
>         template: sub-template
>   - name: sub-template
>     dag:
>       tasks:
>       - name: B
>         template: template-B
>         arguments:
>           artifacts:
>           - name: source-repo
>             from: "{{templates.main-template.tasks.A.outputs.artifacts.my-artifact}}"

The error message I get when workflow runs is as follows:

> Unable to resolve: {{templates.main-template.tasks.A.outputs.artifacts.my-artifact}}

# Motivation

The use case is simple I want to pass the output artifact generated in the main dag to 1 or more sub dags.

## Note

The formatting of the configuration under block quote is changing here, please consider the bullets to be '-'

**Comment by sarabala1979** [comment]
you can use the global artifacts
https://github.com/argoproj/argo/blob/master/examples/global-outputs.yaml

**Comment by sarabala1979** [comment]
@sahil-sawhney

**Comment by sahil-sawhney** [comment]
Thanks a lot @sarabala1979
