### ISSUE TITLE
Some workflows not appearing in workflow archive.

### ISSUE THREAD

**Issue by janschauta** [argoproj/argo#3880]
## Summary 

When workflow ends, it is stored to workflow archive table. However when this save action is not successful, for whatever reason (e.g. temporary db unavailability), it does not show the workflow in the archive at all. Is there any possibility workflow-controller or some related container/process would repair these?

## Diagnostics

Argo version 2.6.3

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
Fixes https://github.com/argoproj/argo/pull/3862

**Comment by sarabala1979** [comment]
duplicate #3837

**Comment by alexec** [comment]
This is a know issue (identified by FMEA testing) and should be fixed in v2.11
