### ISSUE TITLE
Does argo keep data after upgrade?

### ISSUE THREAD

**Issue by arnoldcui** [argoproj/argo#3885]
Hi, I am looking for upgrade experience. 
The argo we deployed is version 2.8, and we plan to upgrade to version 2.10. 
But I found thers is no PVC set in the argo pod. 
I am a little worried about whether the data(templates,cron workflow) will be lost after the upgrade.

**Comment by sarabala1979** [comment]
It is safe to upgrade argo controller. Argo will keep all resources (workflow/cronworkflow/workflowtemplate) and configuration(configmap) in k8s etcd.

**Comment by arnoldcui** [comment]
Thanks you so much.
