### ISSUE TITLE
Workflow auto-completes to wrong URL

### ISSUE THREAD

**Issue by alexec** [argoproj/argo#3903]
## Summary 

Using the autocomplete box on the workflow page sends you to the wrong. Has this ever worked? If not, lets remove it.

![autocomplete-bug](https://user-images.githubusercontent.com/1142830/91666677-82a33100-eab3-11ea-987c-09280261799c.png)

## Diagnostics

master

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by nirav24** [comment]
@alexec I think, the problem is, when selecting workflow, it doesn't care about where we are at that time and just append workflow URL (`ns/workflowId`) to the URL. It can be solved by using an absolute URL when redirecting.

**Comment by alexec** [comment]
Available for testing in [v2.10.0-rc1](https://github.com/argoproj/argo/releases/tag/v2.11.0-rc1).
