### ISSUE TITLE
`Cannot read property 'children' of undefined` error in workflow DAG  

### ISSUE THREAD

**Issue by alexec** [argoproj/argo#3904]
## Summary 

![children-bug](https://user-images.githubusercontent.com/1142830/91666686-98b0f180-eab3-11ea-9b2e-c41e862d336c.png)

## Diagnostics

master

Git blame: #3669

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by nirav24** [comment]
@alexcapras I'd like to work on it if possible. Would you be able to share the workflow you used? I am trying to re-create it on master `v2.10.0-rc1` but not able to reproduce it.

**Comment by alexec** [comment]
I'm not sure how to repro this either, I see it sporadically. I'm actually on the `inf-wb` branch and running `many-massive-workflows.yaml`

**Comment by nirav24** [comment]
> I'm not sure how to repro this either, I see it sporadically. I'm actually on the `inf-wb` branch and running `many-massive-workflows.yaml`

I will give it a try then. thanks

**Comment by alexec** [comment]
@nirav24 can you hold off please? @simster7 will look into this (he wrote the code).

**Comment by nirav24** [comment]
> @nirav24 can you hold off please? @simster7 will look into this (he wrote the code).

definitely
