### ISSUE TITLE
DAGs may not abort on `ErrDeadlineExceeded`

### ISSUE THREAD

**Issue by alexec** [argoproj/argo#3905]
## Summary 

When the deadline is exceeded, the DAG should abort and return. Instead, ""Deadline exceeded" is printed as many times as the number of items.

dag.go:

![image](https://user-images.githubusercontent.com/1142830/91667224-b7b18280-eab7-11ea-98e9-03912d4576d8.png)

## Diagnostics

master

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
This deadline is a workflow processing deadline (10s). The workflow will be re-queued after 10s of process time.

**Comment by alexec** [comment]
Workflows with DAG will not honor deadline exceeded.

After investigating, I'm not sure this is fixable.

**Comment by sarabala1979** [comment]
you right, In DAG flow, the code is ignoring the err
https://github.com/argoproj/argo/blob/712c77f5c46cdbb6f03ec2b020fbca9de08d6894/workflow/controller/dag.go#L435
But in step flow, err is handled
https://github.com/argoproj/argo/blob/712c77f5c46cdbb6f03ec2b020fbca9de08d6894/workflow/controller/steps.go#L233

I think we need to do the same thing in DAG
