### ISSUE TITLE
Retry on  K8s API request timeout 

### ISSUE THREAD

**Issue by sarabala1979** [argoproj/argo#3939]
## Summary 
workflow failed on  intermittent K8s API timeout

What happened/what you expected to happen?

## Diagnostics

What version of Argo Workflows are you running?

```yaml
Paste the workflow here, including status:
kubectl get wf -o yaml ${workflow} 
```

```
Paste the logs from the workflow controller:
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name) | grep ${workflow}
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Maybe fixed by  #3217 (#3853)?
