### ISSUE TITLE
How to dynamically generate output directory in cron workflow

### ISSUE THREAD

**Issue by zyxue** [argoproj/argo#3944]
I'm trying to convert a multi-step ML model training pipeline into an Arg cron workflow.

Each step in the pipeline has some inputs and outputs, and these steps form a DAG.

If I run them in a cron workflow,  I need to send all the outputs to a different location each time the workflow is run, e.g. to `gs://some-bucket/YYYYMMDD`.

But I'm not sure how to dynamically generate the output path since it's hard-coded in the YAML. What's the common practice for such use case, please?

Currently, I'm generating the YAML with [kuberflow pipelines](https://github.com/kubeflow/pipelines)

**Comment by simster7** [comment]
Hi @zyxue,

You can use [Argo variables](https://github.com/argoproj/argo/blob/master/docs/variables.md) to do this, particularly the `{{workflow.creationTimestamp}}`. Argo will resolve it to its actual value during runtime.

Let me know if you need more help with this.

**Comment by zyxue** [comment]
thanks @simster7 , what if I need the date of yesterday wrt. current?

**Comment by simster7** [comment]
In that case you will need to run a container (such as a simple bash or python script) to do the math for you. You can then use the result through an output paramter.
