### ISSUE TITLE
Argo CI Workflow stuck when running fixturemanager-test.  

### ISSUE THREAD

**Issue by francis-ax** [argoproj/argo#397]
I installed argo(latest master 1.1.0-5361e90 ) on existing kubernetes cluster and started Argo CI stress test over the weekend. 

Most of the Argo CI Workflow stuck when running fixturemanager-test.  I tested the same argo CI workflow on dev cluster and it passed.  Tested cluster is running in sb3 account.

```
Francis-Macbook-Pro:argoKube francis$ kpassword
ClusterID: sb3-c2.francis.applatix.net
Access info in ~/.argo
```

![image](https://user-images.githubusercontent.com/29876185/31896735-19082bac-b847-11e7-86b6-869c2853e48a.png)

**Comment by shrinandj** [comment]
If this was a problem seen during stress tests, it could be related to lack of resources. Can you test this workflow in isolation?

**Comment by francis-ax** [comment]
I have GKE argo cluster and "argo CI" workflow  also stuck at the same point, I only have 4 CI workflow running at the moment and cluster is not running out of resource. I think this is not stress test related and we need to investigate this.

**Comment by sytianhe** [comment]
I tested on dev, it seems work fine

**Comment by sytianhe** [comment]
Let me know if still seeing this. Closing now.
