### ISSUE TITLE
Server UI shows "undefined" for environment variable populated from a secret

### ISSUE THREAD

**Issue by ebr** [argoproj/argo#3973]
# Summary

When an environment variable is populated from a secret, the server UI shows `undefined` for its value. This is highly confusing because the user's first reaction is that the secret value isn't being correctly passed. This messaging could be improved by showing `secret` or `hidden` or something to that effect, to indicate that the value does exist, but is not displayed.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Thank you for the bug report. Would you like to submit a PR to fix this?

**Comment by ebr** [comment]
I would like to, if I can get to it in the next couple of weeks!

**Comment by alexec** [comment]
You probably don't need to know Go to do this. I _think_ you need to change: ui/src/app/workflows/components/workflow-node-info/workflow-node-info.tsx

**Comment by aletepe** [comment]
I'm working on this bug for Hacktoberfest. @alexec I'd like to not only fix the bug but maybe tweak it a bit to differentiate not available values from secrets. I was thinking having the value show as _`[redacted]`_ (or something similar) when the value is a secret, and showing `not available` for other reasons. Where would you say is the best place to put that logic?

**Comment by alexec** [comment]
@aletepe I don't think the actual value will be returned by the API call. So I don't think you'll need to redact it. What will be useful is showing it is from a secret (e.g. using an FontAwesome icon, e.g. `<i className='fa fa-key'/>`), the name of the secret and key within it. This allows the user to then go and look it up themselves if they need to.

**Comment by aletepe** [comment]
@alexec I meant writing literally `redacted`, so as to make users understand there was actually a value behind it and not simply that there is no value available, and thus avoiding the confusion which led to raising this bug.
I like the idea of showing a more details about the secret, like the icon you mention 👍 

PS: could you please assign this issue to me? Thanks before hand!

**Comment by alexec** [comment]
sure or maybe "secret"?

**Comment by aletepe** [comment]
@ebr could you please add to the Issue description a screenshot of the UI showing `undefined`? And maybe steps to reproduce it (an example yaml file or similar)?

**Comment by aletepe** [comment]
I've used the example in the docs here: https://github.com/argoproj/argo/blob/master/examples/secrets.yaml

Without changes the behaviour is the following:
<img width="350" alt="image" src="https://user-images.githubusercontent.com/47940494/97584242-b9cc8a80-19ef-11eb-9334-fa1dad305029.png">

With my proposed changed it would look something like this (injected two secrets to show multiline behaviour):
<img width="350" alt="image" src="https://user-images.githubusercontent.com/47940494/97586383-19c43080-19f2-11eb-949f-d82a0aa90df4.png">

It would still show `undefined` like in the first screenshot for undefined values not coming from secrets.

@alexec @ebr how is this looking?

**Comment by alexec** [comment]
Looks great!
Can I ask that when you hover your mouse of the key icon you get some explanatory text?

**Comment by aletepe** [comment]
Something like this?
>The value of this environment variable has been hidden for security reasons because it comes from a kubernetes secret.

**Comment by alexec** [comment]
perfect

**Comment by alextsakpinis** [comment]
Hello, 
I am using argo with the following version

argo: v3.2.6
BuildDate: 2021-12-17T20:59:31Z
GitCommit: db7d90a1f609685cfda73644155854b06fa5d28b
GitTreeState: clean
GitTag: v3.2.6
GoVersion: go1.16.12
Compiler: gc
Platform: darwin/amd64

When running a workflow on argo, I am still getting the label undefined for the environment variables within the container. Why is that still happening? I thought this was resolved from [v.3.0.0](https://github.com/argoproj/argo-workflows/releases/tag/v3.0.0).

<img width="568" alt="Bildschirmfoto 2022-01-17 um 10 30 32" src="https://user-images.githubusercontent.com/23211992/149743844-ea861ed2-1e75-4c45-b457-9d92cc916459.png">

Thanks a lot for your help!
