### ISSUE TITLE
CRDs have incomplete schema

### ISSUE THREAD

**Issue by kevinhwang** [argoproj/argo#3974]
As of [402fc0b](https://github.com/argoproj/argo/commit/402fc0bf65c11fa2c6bee3b407d6696089a3387e), the generated CRDs at [argo/manifests/base/crds/full](https://github.com/argoproj/argo/tree/402fc0bf65c11fa2c6bee3b407d6696089a3387e/manifests/base/crds/full) have an incomplete schema, which makes them difficult to an IDE for validation / autocompletion:

![image](https://user-images.githubusercontent.com/11861195/92560812-dafecf00-f227-11ea-8f28-bd62da1ba489.png)

The example pictured above from https://argoproj.github.io/argo/examples/#steps fails validation because the generated schema at https://github.com/argoproj/argo/blob/402fc0bf65c11fa2c6bee3b407d6696089a3387e/manifests/base/crds/full/argoproj.io_workflows.yaml#L12647-L12650

expects `steps` to be an array of array of scalars. The same error is present in the other CRDs.

The actual [Argo field reference](https://argoproj.github.io/argo/fields/#template) specifies that `steps` to have type `Array<Array<`[`WorkflowStep`](https://argoproj.github.io/argo/fields/#workflowstep)`>>`.

The CRDs look like they're auto-generated, so maybe there's a bug with how they're generated?

**Comment by alexec** [comment]
I'm not sure what's happening here. The schema looks correct to me - steps are an array of arrays. However, IntelliJ is complaining that it "expects a scalar value". I.e. IntelliJ does not seem to interpret the schema correctly.

Do you have a suggestion for the correct schema? If not, I'll raise a big with IntelliJ.

**Comment by alexec** [comment]
https://youtrack.jetbrains.com/issue/IDEA-250448

**Comment by kevinhwang** [comment]
I guess the issue is that the schema isn't specific enough—an array of arrays vs an array of array of workflow steps.
