### ISSUE TITLE
Broken connection during streaming request for logs using API

### ISSUE THREAD

**Issue by ivancili** [argoproj/argo#4017]
## Summary 

What happened/what you expected to happen?

I'm using API server to fetch logs and display them in real time in terminal using Python. The request breaks after some time with the following message:

```python
Traceback (most recent call last):
  File "/Users/ivancili/blabla/.venv/lib/python3.7/site-packages/urllib3/response.py", line 696, in _update_chunk_length
    self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ivancili/blabla/.venv/lib/python3.7/site-packages/urllib3/response.py", line 436, in _error_catcher
    yield
  File "/Users/ivancili/blabla/.venv/lib/python3.7/site-packages/urllib3/response.py", line 763, in read_chunked
    self._update_chunk_length()
  File "/Users/ivancili/blabla/.venv/lib/python3.7/site-packages/urllib3/response.py", line 700, in _update_chunk_length
    raise httplib.IncompleteRead(line)
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ivancili/blabla/.venv/lib/python3.7/site-packages/requests/models.py", line 751, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/Users/ivancili/blabla/.venv/lib/python3.7/site-packages/urllib3/response.py", line 571, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/Users/ivancili/blabla/.venv/lib/python3.7/site-packages/urllib3/response.py", line 792, in read_chunked
    self._original_response.close()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/ivancili/blabla/.venv/lib/python3.7/site-packages/urllib3/response.py", line 454, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
```

This is the code I use:

```python
import requests
endpoint = 'https://argo.local/api/v1/workflows/argo/my-workflow-n8crq/my-workflow-n8crq-2252535549/log'
params = {
    'logOptions.container': 'main',
    'logOptions.follow': True
}
with requests.get(url=endpoint, params=params, stream=True) as resp:
    for _line in response.iter_lines():
        print(_line)
```

The (pretty much) same thing happens when using cURL:

```bash
curl -X GET 'https://argo.local/api/v1/workflows/argo/my-workflow-n8crq/my-workflow-n8crq-2252535549/log'
```

And the error message appears after some time of working correctly:

```bash
curl: (92) HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)
```

It seems there is something wrong with the API server. Im using the latest version of Argo Workflows deployed using [this manifest file](https://github.com/argoproj/argo/blob/stable/manifests/quick-start-postgres.yaml).

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
This can happen unfortunately (due to many reasons). It is up to the client to re-establish connection.

**Comment by alexec** [comment]
Removed `bug` label as this is not a bug.

**Comment by ivancili** [comment]
@alexec thanks for your response, I did a bit of debugging and reading. The connection itself is OK, the issue occurs when the server responds with a chunk of length zero (0 bytes). This gets misinterpreted by libs/tools such as `urllib3` and `curl` as the end of chunked transfer. The server should respond with zero-sized chunk only at the end of the transfer, not when the main process inside a container is not providing logs for some time.

Please see this [RFC](https://tools.ietf.org/html/rfc7230#section-4.1) for clarification:

```
The chunked transfer coding is complete
when a chunk with a chunk-size of zero is received, possibly followed
by a trailer, and finally terminated by an empty line.
```

In my case, the main process inside the container is an ML train process which produces logs after every epoch. The epoch can last for some time, and this is probably the reason why the empty chunk appears (this is just a guess).

**Comment by ivancili** [comment]
The same thing happens when I watch logs through the browser UI. The message displayed by the UI is:
```
 Failed to load logs: Unsuccessful HTTP response
```
Stack trace is visible in the console and failed request is visible under Network tab in Developer tools.

**Comment by alexec** [comment]
Are you fronting Argo with any kind of ingress or reverse proxy? Can it handle HTTP2 connections?

**Comment by ivancili** [comment]
@alexec Hi, yes, there's an nginx ingress controller in front of Argo (in combination with Metal LB, its a private cluster). And yes, it handles http2 connections. 
On the other hand, the http library that I use in my code sends uses http1.1 requests. So that could possibly be the issue? But that doesn't explain why the same thing happens when watching logs through browser (which sends http2 requests). I'll look into it.

**Comment by alexec** [comment]
It's a bit hard to draw any conclusion. We have found that Nginx (for example) needs extra configuration for HTTP 2 (I think it is something to do with keep-alives). I would check to see if the issue persists with a direct connection. If not, then ask on the Slack channel? You wont' be the only person to have had this problem

**Comment by ivancili** [comment]
@alexec That seems like a good starting point, I'll try to search through slack for similar issues. Thanks.

**Comment by ivancili** [comment]
I forgot to put it here earlier, but if anyone encounters the same problem, I added the following annotation to the ingress rule config for Argo UI:
```
nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
```
This is just a workaround actually, assuming you won't be watching the pod logs for more than an hour at a time.

**Comment by Dhaval08** [comment]
@ivancili  Hello, I am facing the exact same issue. If the pod does not register any new logs (which can happen in case of long running epochs), the connection is closed assuming all logs have been streamed.
Have you figured out a solution to keep the connection alive?
Thank you.

**Comment by ivancili** [comment]
@Dhaval08 Unfortunately no, I haven't invested any further time in solving this issue. In my case the problem is clearly the nginx ingress controller, which terminates the proxy connection to the Argo server if no data has been transmitted for some period of time. I send requests from outside the cluster, which are then proxied by the nginx ingress.

I used an annotation inside the ingress rule which allowed me to increase the timeout, and it was a good enough solution for my use case. See [this link](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_read_timeout) for more info.

Out of curiosity, by looking at your code, you wrote a server which is talking to the Argo server and requesting the logs? And the problem happens when you talk (from outside the cluster?) to your server? Or did I get something wrong?

**Comment by Dhaval08** [comment]
@ivancili 
I am trying to implement a streaming API in golang that would talk to the Argo server and stream the logs from the pod that's running the Argo workflow.
