### ISSUE TITLE
Problem with artifact access after upgrade to GKE 1.16.13-gke.401

### ISSUE THREAD

**Issue by jnmclarty** [argoproj/argo#4030]
## Summary 

What happened/what you expected to happen?

I upgraded my GKE cluster to the latest patch for 1.16 (1.16.13-gke.401 from 1.16.13-gke.1).  

Pipelines immediately stopped working, displaying the following error in the UI:

`failed to save outputs: timed out waiting for the condition`

Pipelines that ran in the past can no longer display their output artifacts

Highly possible, this is a knowledge gap on my side and unrelated to this project.  But, this was the first place I came to check for a solution.  So, maybe, when I/we find a solution, it'll help somebody else.

From the logs in GCP, I find:

```
Failed get file: Get http://minio:9000/my-bucket/?location=: dial tcp 10.16.5.120:9000: connect: connection refused
```

## Diagnostics

What version of Argo Workflows are you running?

v2.9.3

Other helpful snippets from the workflow controller log:

```
Paste the logs from the workflow controller:
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name)

time="2020-09-15T02:51:42Z" level=error msg="failed to update CronWorkflow" error="Put https://10.16.0.1:443/apis/argoproj.io/v1alpha1/namespaces/argo/cronworkflows/process-dailyjob: dial tcp 10.16.0.1:443: connect: connection refused" namespace=argo workflow=process-dailyjob
```

I'll try redeploying a fresh cluster with a fresh install of Argo within 18h of this post, and I'll report back shortly after. 

Any tips or pointers, are welcome.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
looks like you have artifactory is enabled on your `workflow-controller-configmap` or in your workflow step. it is trying to download or upload the artifact to `dial tcp 10.16.5.120:9000` and getting `connect: connection refused`.
Can you check whether you can access this artifactory from new cluster?

**Comment by jnmclarty** [comment]
Thanks so much @sarabala1979 ; I ended up tearing everything down, and rebuilding the cluster on the latest patch.  Everything is workign smooth.  Likely my config or something naive/dumb I did on my side.
