### ISSUE TITLE
Tooltips should also be supplied for ellipsized text

### ISSUE THREAD

**Issue by jsoref** [argoproj/argo#4039]
# Summary

Tooltips (introduced in #767) should extend to the text below icons

# Use Cases

Visit a workflow and see:
![image](https://user-images.githubusercontent.com/2119212/93249570-81cef800-f75f-11ea-8d8c-ec03ffa11458.png)

If you hover over the ✅ , you'll get a tooltip.
If you hover over the ellipsized text below, you don't

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
@jsoref would you like to submit a PR to add this?

**Comment by jsoref** [comment]
I don't think I'll have time anytime soon.

**Comment by alexec** [comment]
Ok. Maybe some else picks this up.
