### ISSUE TITLE
Pod container hostname

### ISSUE THREAD

**Issue by tse77** [argoproj/argo#4047]
I am new to Argo and looking in to how we can make use of Argo to create more complex workflows than what is possible from K8s batch job. In the K8s Job spec I can specify a hostname but I cant find out how to do that in Argo.

Is there any way to specify hostname for the containers in a workflow?

**Comment by alexec** [comment]
Node selector?
https://argoproj.github.io/argo/fields/#nodeselector

**Comment by tse77** [comment]
I have a legacy application im migrating to run in a container and the application reads different files depending on the hostname. It requires that the container have a specific name while it doesnt matter on which node it runs. So I need to set the hostname of the container. Is that possible? In a batch job yaml file I just specify "hostname: dean" for example.

**Comment by alexec** [comment]
Can you set this based on this:

https://stackoverflow.com/questions/34609572/is-it-possible-to-set-a-hostname-in-a-kubernetes-replication-controller

You can set this probably set using `podSpecPatch`?

**Comment by tse77** [comment]
I got it to work now byt adding:

`podSpecPatch: '{"hostname":"dean"}'`

Thank you for the help =)
