### ISSUE TITLE
Argo Workflow is not displaying correct pod status on UI after installing kubeflow v1.1

### ISSUE THREAD

**Issue by JasonPad19** [argoproj/argo#4056]
## Summary 

What happened/what you expected to happen?
I installed Argo workflow (v2.10.2)  with namespace "argo" , and then installed kubeflow (v.1.1).
Then, argo workflow can't display correct pod status on UI. However, Kubeflow pipeline displayed the pipeline execution runs.

I might encounter  a similar issue to this Closed issue. 
https://github.com/argoproj/argo/issues/4036

And i tried to update argo namespace configmap with instanceID.
![image](https://user-images.githubusercontent.com/52347372/93404568-a56c7c80-f8de-11ea-84cd-b4a06b48587e.png)

and tried to follow the step to bind workflow with instanceID
![image](https://user-images.githubusercontent.com/52347372/93404657-e6fd2780-f8de-11ea-93d5-7b6049e7faa9.png)

Yet, from UI, it still can't display correct pod status. btw, i can see pod status as "complete" on kubernetes.

Could you please help to guide me to make it work please?

## Diagnostics

What version of Argo Workflows are you running?
v2.10.2

```yaml
Paste the workflow here, including status:
kubectl get wf -o yaml ${workflow} 
```

```
Paste the logs from the workflow controller:
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name) | grep ${workflow}
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by simster7** [comment]
How are you running the UI? You also need to start the UI with the correct instanceId:

```
$ argo server --instanceid hello
```

**Comment by JasonPad19** [comment]
After installation, I have enabled the load balancer.
kubectl patch svc argo-server -n argo -p '{"spec": {"type": "LoadBalancer"}}'

and then access the ui using ip address directly.
e.g. http://x.x.x.x:2746

![image](https://user-images.githubusercontent.com/52347372/93524858-3f88ff00-f989-11ea-98fa-a0dc5b428e07.png)
