### ISSUE TITLE
Argo not offloading large workflow to postgres

### ISSUE THREAD

**Issue by punjabdhaputar** [argoproj/argo#4065]
## Summary 

When running large workflows via the http rest api or the CLI, I have been unable to submit jobs with the following error 

```
ERRO[0170] Create request is failed. Error: Request entity too large: limit is 3145728 
ERRO[0170] finished unary call with code Unknown         error="Request entity too large: limit is 3145728" grpc.code=Unknown grpc.method=CreateWorkflow grpc.service=workflow.WorkflowService grpc.start_time="2020-09-17T12:27:16-07:00" grpc.time_ms=63461.7 span.kind=server system=grpc
```

I have also received this error

```
ERRO[1991] Create request is failed. Error: etcdserver: request is too large 
ERRO[1991] finished unary call with code Unknown         error="etcdserver: request is too large" grpc.code=Unknown grpc.method=CreateWorkflow grpc.service=workflow.WorkflowService grpc.start_time="2020-09-17T16:59:42-07:00" grpc.time_ms=16243.304 span.kind=server system=grpc
```

An large example workflow that causes this error is attached

[test_workflow.yaml.zip](https://github.com/argoproj/argo/files/5242514/test_workflow.yaml.zip)

Based upon this link: https://argoproj.github.io/argo/offloading-large-workflows/, I set  `nodeStatusOffLoad: true` within my config map. 

A few questions: 
1) Are we able to use the nodeStatusOffLoad feature via the rest api?
2) Is there a way we can package the example workflow more efficiently?
Thanks for the help!
## Diagnostics

What version of Argo Workflows are you running?

```
bash-3.2$ argo version
argo: latest+ed79a54.dirty
  BuildDate: 2020-09-14T17:46:17Z
  GitCommit: ed79a5401162db7a3060111aff1b0fae5e8c2117
  GitTreeState: dirty
  GitTag: v2.10.2
  GoVersion: go1.15.2
  Compiler: gc
  Platform: darwin/amd64
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Node offload status is not an API feature. Instead it is a configuration item that requires SQL database to connect to. 

As we have had very few issues with this feature, I suspect this is set-up related.

Can you please check the workflow controller logs for errors?

**Comment by alexec** [comment]
Submission of large workflows should be done using `env ARGO_SERVER=your-server argo submit`

**Comment by punjabdhaputar** [comment]
Workflow Controller Logs and Argo Server Logs copied below. It seems that after the workflow is rejected from Argo-server, nothing is logged in the workflow controller.

```
bash-3.2$ tail argo_server.logs 
time="2020-09-18T16:15:32Z" level=info msg="Alloc=7795 TotalAlloc=1185383 Sys=70592 NumGC=399 Goroutines=65"
time="2020-09-18T16:20:32Z" level=info msg="Alloc=9093 TotalAlloc=1192491 Sys=70592 NumGC=401 Goroutines=65"
time="2020-09-18T16:25:32Z" level=info msg="Alloc=7577 TotalAlloc=1199624 Sys=70592 NumGC=404 Goroutines=65"
time="2020-09-18T16:30:32Z" level=info msg="Alloc=8887 TotalAlloc=1206775 Sys=70592 NumGC=406 Goroutines=65"
time="2020-09-18T16:35:32Z" level=info msg="Alloc=7388 TotalAlloc=1213959 Sys=70592 NumGC=409 Goroutines=65"
time="2020-09-18T16:37:41Z" level=error msg="Create request is failed. Error: etcdserver: request is too large"
time="2020-09-18T16:37:41Z" level=error msg="finished unary call with code Unknown" error="etcdserver: request is too large" grpc.code=Unknown grpc.method=CreateWorkflow grpc.service=workflow.WorkflowService grpc.start_time="2020-09-18T16:37:26Z" grpc.time_ms=15324.664 span.kind=server system=grpc
time="2020-09-18T16:40:32Z" level=info msg="Alloc=10901 TotalAlloc=8336429 Sys=139682 NumGC=650 Goroutines=65"
time="2020-09-18T16:43:54Z" level=error msg="Create request is failed. Error: etcdserver: request is too large"
time="2020-09-18T16:43:54Z" level=error msg="finished unary call with code Unknown" error="etcdserver: request is too large" grpc.code=Unknown grpc.method=CreateWorkflow grpc.service=workflow.WorkflowService grpc.start_time="2020-09-18T16:43:39Z" grpc.time_ms=15027.986 span.kind=server system=grpc
bash-3.2$ tail workflow_controller.logs 
time="2020-09-18T16:28:11Z" level=info msg="Zero old offloads, nothing to do"
time="2020-09-18T16:33:11Z" level=info msg="Alloc=85477 TotalAlloc=8687190 Sys=894974 NumGC=428 Goroutines=156"
time="2020-09-18T16:33:11Z" level=info msg="Performing periodic workflow GC"
time="2020-09-18T16:33:11Z" level=info msg="Zero old offloads, nothing to do"
time="2020-09-18T16:38:11Z" level=info msg="Alloc=691959 TotalAlloc=9469131 Sys=894974 NumGC=432 Goroutines=156"
time="2020-09-18T16:38:11Z" level=info msg="Performing periodic workflow GC"
time="2020-09-18T16:38:11Z" level=info msg="Zero old offloads, nothing to do"
time="2020-09-18T16:43:11Z" level=info msg="Alloc=85525 TotalAlloc=9469295 Sys=894974 NumGC=435 Goroutines=156"
time="2020-09-18T16:43:11Z" level=info msg="Performing periodic workflow GC"
time="2020-09-18T16:43:11Z" level=info msg="Zero old offloads, nothing to do"
```

**Comment by punjabdhaputar** [comment]
My current setup uses the Argo installation from the setup-guide with a built in postgres database: https://raw.githubusercontent.com/argoproj/argo/stable/manifests/quick-start-postgres.yaml. To automate my workflows, I have a separate service that calls the argo-server api endpoint to automate job-submission. 

So if I understand correctly, with this setup there is no option to use the node offload status since it is only available on the CLI?  Do you have a recommendation on how to workflow with large workflows (~10,000+ Nodes) via the API?

Thanks for the help!

**Comment by alexec** [comment]
How big is your workflow spec?

Can we check the size of your workflow before it is submitted? Can you `kubectl apply` it?

**Comment by punjabdhaputar** [comment]
One of the workflows I am running has a size YAML file size of 2.7MB. 

I get the following error when submitting through kubectl 
```
bash-3.2$ kubectl -n dev create -f workflow.yaml 
Error from server: error when creating "workflow.yaml": etcdserver: request is too large
```

**Comment by jessesuen** [comment]
> One of the workflows I am running has a size YAML file size of 2.7MB.

This is a fundamental limitation of etcd resource objects. The limit is 1MB. Unfortunately, your only recourse is to split your workflow into multiple workflows.

**Comment by punjabdhaputar** [comment]
> > One of the workflows I am running has a size YAML file size of 2.7MB.
> 
> This is a fundamental limitation of etcd resource objects. The limit is 1MB. Unfortunately, your only recourse is to split your workflow into multiple workflows.

To split the workflow into multiple workflows, would something like this https://argoproj.github.io/argo/workflow-of-workflows/ work  (as was referenced in this other issue https://github.com/argoproj/argo/issues/3738)?


Is there any existing tooling that can take a large workflow and dynamically generate a workflow of workflows? Can this be built into Argo? I believe that would allow Argo to run arbitrarily large workflows?

**Comment by alexec** [comment]
> To split the workflow into multiple workflows, 

Correct.

> Is there any existing tooling that can take a large workflow and dynamically generate a workflow of workflows

No, sorry.

**Comment by agilgur5** [comment]
#7121 is a feature request for supporting even larger Workflows and there is a suggestion for tooling to auto-split a large Workflow into multiple Workflows-of-Workflows
