### ISSUE TITLE
https://argoproj.io/ won't redirect to the right page

### ISSUE THREAD

**Issue by francis-ax** [argoproj/argo#407]
In the latest argo cluster, the docs tab's documentation link to https://argoproj.io/ which will refuse the connection.  maybe It should link to http://argoproj.io/ instead and this link will redirect to https://applatix.com/open-source/argo/

![image](https://user-images.githubusercontent.com/29876185/32073525-f6b7305a-bac8-11e7-98b4-006f843ac2c4.png)

**Comment by pratulw** [comment]
This is the behaviour we want
