### ISSUE TITLE
Allow to limit the number of concurrent running workflow

### ISSUE THREAD

**Issue by ErezAlster** [argoproj/argo#4078]
# Summary
Common case scenario is to have a queue based mechanism that limits that number of jobs that running at the same time.
I would like to apply multiple workflows at once and to limit the number of workflows of **specific** workflow template that running at the same time.

At the moment the parallelism parameters is applying for steps only inside a specific workflow.

# Use Cases
1. Event based systems
2. Batch processing
3. recurring job that creates workflows dynamically
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Read this page https://argoproj.github.io/argo/synchronization/

**Comment by dshiryaev-plesk** [comment]
The page has been moved to https://argoproj.github.io/argo-workflows/synchronization/ .
