### ISSUE TITLE
Unable to parse 1d as a duration

### ISSUE THREAD

**Issue by samath117** [argoproj/argo#4088]
## Summary 

The documentation around retry loops explains that it is possible to specify both the `duration` and the `maxDuration` as "durations", specifically
> e.g.: "2m", "6h", "1d"

However, specifying the duration as "1d" leads to an error: "unable to parse 1d as a duration". In any case, a full accounting of the allowed duration specifications in the docs would be much appreciated.

To reproduce this error, I simply submitted the [retry-backoff.yaml](https://github.com/argoproj/argo/blob/master/examples/retry-backoff.yaml) workflow, modifying the maxDuration to "1d" instead of its default of "1m". Note that since this is a stochastic workflow, you might need to run it multiple times to produce a failure on the first attempt and trigger the retry loop.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
This document in incorrect. Days are not supported. Would you like to submit a PR to fix the docs?

Otherwise, you could use `24h` or `48h` for `1d` or `2d` etc etc

**Comment by jessesuen** [comment]
Relevant: https://github.com/golang/go/issues/17767
