### ISSUE TITLE
Workflow failed because its unable to load logs

### ISSUE THREAD

**Issue by saranyaeu2987** [argoproj/argo#4092]
# Workflow failed because its unable to load logs 

Argo version: 2.11.0

Preface:
Workflow  has failed because it was unable to load the logs.
Out of 2 steps, one step is able to pull logs but not the other one

Below are 2 API to made to get logs

http://internal-23e.us-east-1.elb.amazonaws.com:2746/artifacts/argo/output-parameters-wt294/output-parameters-wt294-3630452401/main-logs
(step : consume-parameter) Unsuccessful
Response: Artifact no found

http://internal-23e.us-east-1.elb.amazonaws.com:2746/artifacts/argo/output-parameters-wt294/output-parameters-wt294-2743065841/main-logs
(step : generate-parameter) Successful

![image](https://user-images.githubusercontent.com/19850718/93942322-cb868800-fcf5-11ea-8c65-042563bf49a9.png)

Questions:
1. Which artifacts logs available for one step but not other one?

**Comment by saranyaeu2987** [comment]
@simster7 @alexec 
Can you please guide me on this issue. ?
P.S - both https://github.com/argoproj/argo/issues/4079  and this uses same workflow

**Comment by chaserogers** [comment]
Ever figure this out?

**Comment by saranyaeu2987** [comment]
@chaserogers 
This issue happened due to mutating webhooks admission control in my EKS cluster.
More description in https://github.com/argoproj/argo/issues/4107
