### ISSUE TITLE
v2.11: Workflows do not load in the UI

### ISSUE THREAD

**Issue by chris-durbin** [argoproj/argo#4123]
## Summary 

What happened/what you expected to happen?

I navigated to the main workflows page http://localhost:2746/workflows/argo and received an error with a stacktrace. I expected to see my workflows listed.

## Diagnostics

What version of Argo Workflows are you running?
2.11.0

At some point the main argo workflows page started throwing an error in my Chrome browser. I haven't been able to figure out exactly what triggers the problem, but I did select multiple workflows from the main page and click terminate at one point shortly before the page stopped loading.

When I opened a new browser in Firefox and a new incognito window in Chrome the workflows page loads fine. But when I attempt to reload it in my original browser it continues to fail.

The stacktrace is:
```
Cannot read property 'forEach' of undefined
 Reload this page to try again.

Stack Trace
TypeError: Cannot read property 'forEach' of undefined
    at t.get (http://localhost:2746/main.a56dcbe022dfd2a79d67.js:89:265536)
    at t.saveHistory (http://localhost:2746/main.a56dcbe022dfd2a79d67.js:89:265749)
    at oa (http://localhost:2746/main.a56dcbe022dfd2a79d67.js:396:72729)
    at ra (http://localhost:2746/main.a56dcbe022dfd2a79d67.js:396:72479)
    at Ha (http://localhost:2746/main.a56dcbe022dfd2a79d67.js:396:82493)
    at Va (http://localhost:2746/main.a56dcbe022dfd2a79d67.js:396:84967)
    at http://localhost:2746/main.a56dcbe022dfd2a79d67.js:396:98147
    at Object.t.unstable_runWithPriority (http://localhost:2746/main.a56dcbe022dfd2a79d67.js:405:3194)
    at Ts (http://localhost:2746/main.a56dcbe022dfd2a79d67.js:396:98082)
    at Es (http://localhost:2746/main.a56dcbe022dfd2a79d67.js:396:97858)
Component Stack

    in t
    in t
    in t
    in Unknown
    in t
    in t
    in t
    in div
    in Unknown
    in t
    in n
```

The only clue I've found from a working browser (incognito in Chrome) vs the broken browser is that in the working browser I see the following in local storage ListOptions:
`{selectedPhases: [], selectedLabels: []}`

and in the broken browser I only see:
`{selectedPhases: []}`

I suspect forEach is being called on ListOptions.selectedLabels which is undefined. 

---
**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by chris-durbin** [comment]
I've confirmed that clearing the LocalStorage from Developer Tools -> Application fixes the issue.

**Comment by alexec** [comment]
Thank you for the work-around. We should be able to tolerant corrupted local storage. 

Would you be interested in contributing a fix?

**Comment by kushthedude** [comment]
Hi @alexec , we are still experiencing this. Is it fixed?

**Comment by alexec** [comment]
@kushthedude please open new issue.
