### ISSUE TITLE
Documentation: Examples edit link is wrong

### ISSUE THREAD

**Issue by secretlifeof** [argoproj/argo#4124]
Hello lovely creators of this great tool!

Just getting started, but already half in love.

I wanted to edit the examples page, but the link seems to be wrong (returns 404):
https://github.com/argoproj/argo/edit/master/docs/examples/README.md

It looks like `-w` is removed and the second line gets all steps, is that correct?

```
argo logs -w hello-world-xxx    # get logs from all steps in a workflow
argo logs hello-world-xxx-yyy   # get logs from a specific step in a workflow
```

**Comment by alexec** [comment]
Good point. Would you like to submit a PR to fix?

**Comment by secretlifeof** [comment]
Yes. PR is submitted. Where can I edit the link?
