### ISSUE TITLE
Argo REST API Status

### ISSUE THREAD

**Issue by punjabdhaputar** [argoproj/argo#4134]
# Summary

When using the rest api to query for a workflow status: /api/v1/workflows/{namespace}/{name} I am looking to get only the phase of all of the nodes, something akin to: fields=status.nodes.*.phase. Since the children of "nodes" is the names of all of the pods, is there a way to have a "wildcard" to get all of the phases of each key under nodes?

# Motivation

We are working with extremely large and verbose workflows and the responses for the get-workflows api call are getting prohibitively large. Therefore, we would like to filter the requests for only the fields we require to minimize network traffic.

Thanks!

**Comment by sarabala1979** [comment]
Get and list API call supports `fields` parameter you can pass jsonpath to query the fields

curl http://localhost:2746/api/v1/workflows/argo/loops-param-result-jpflg?fields="status.nodes"

**Comment by punjabdhaputar** [comment]
> Get and list API call supports `fields` parameter you can pass jsonpath to query the fields
> 
> curl [http://localhost:2746/api/v1/workflows/argo/loops-param-result-jpflg?fields="status.nodes](http://localhost:2746/api/v1/workflows/argo/loops-param-result-jpflg?fields=%22status.nodes)"

So in my workflow, the value under nodes represents all of the pod names within a workflow. 
I want to be able to query the phase of every node without all of the other metadata.

Like curl http://localhost:2746/api/v1/workflows/argo/loops-param-result-jpflg?fields="status.nodes.*.phase"

Note how in my argument to fields I am using a wildcard. Does the fields parameters support anything like that?

**Comment by sarabala1979** [comment]
I think wildcard is not supported in fields. Nodesstatus is not an array. you can get all nodestatus using `curl http://localhost:2746/api/v1/workflows/argo/loops-param-result-jpflg?fields="status.nodes` and process it in the client side

**Comment by punjabdhaputar** [comment]
> I think wildcard is not supported in fields. Nodesstatus is not an array. you can get all nodestatus using `curl http://localhost:2746/api/v1/workflows/argo/loops-param-result-jpflg?fields="status.nodes` and process it in the client side

So I was finding that the size of the request for large workflows (1000+ nodes) was causing the Argo server to crash and become unstable (the responses were 10MB+). Therefore, I was trying to find a method to conduct filtering on the server-side to reduce back the network response but it sounds like that is not possible since wildcards are not supported.

**Comment by alexec** [comment]
Would you like to submit a PR?

**Comment by punjabdhaputar** [comment]
> Would you like to submit a PR?

I would love to give it a try! I tried to poke around the Argo code-base and I could not find the section of code where the fields parameter was being utilized. Could you provide me a link to the part of the code that contains this logic?
