### ISSUE TITLE
Parameterized onExit handler for templates

### ISSUE THREAD

**Issue by punjabdhaputar** [argoproj/argo#4138]
# Summary

Hello! I am trying to use exit-handlers within a template and was wondering how to pass parameters to the exit-container.

Given an exit-template as follows:

```
   "name": "send-template-update"
    "inputs":
      "parameters":
      - "name": "podName"
      - "name": "podStatus"
    "container":
      "image": "ubuntu"
      "command":
      - "/bin/bash"
      - "-c"
      "args":
      - "echo \"{{inputs.parameters.podName}}{{inputs.parameters.podStatus}}\""
```

And a task-template as follows
```
name: example-template
onExit: send-template-update
...
```

And an instantiation of that template within a DAG

```
name: example-task
template: example-template
...
```

how would I pass the arguments of podName and podStatus to the exit-container.

# Motivation

I am trying to automate collection of per-node statuses.

**Comment by sarabala1979** [comment]
Exithandler doesn't support passing input parameters.  you can use global parameters and here the list of global variables
https://github.com/argoproj/argo/blob/f8053ae379a8244b53a8da6787fe6d9769158cbe/docs/variables.md
