### ISSUE TITLE
What is the expiry time of access tokens?

### ISSUE THREAD

**Issue by AnjanaAK** [argoproj/argo#4143]
# Summary

There are 3 auth modes supported by Argo workflows as mentioned here : https://argoproj.github.io/argo/argo-server-auth-mode/

"client" auth mode requires clients to provide their Kubernetes bearer token and use that.

Running the following command provides an access token:
`argo auth token`

But it seems that the tokens are expiring so fast. 
What is the expiry time of an access token?
Is there any option or argument to configure it manually?

# Motivation

The fast expiration of tokens becomes a problem in cases where the application just adds a token in the request to argo instead of doing the auth itself.

**Comment by alexec** [comment]
There are several types of token. You've asked about "client auth" so I will answer that.

* `argo auth token`: It depends on your Kubernetes provider. Expiry time for tokens might be set low for them. 
* [access token](https://argoproj.github.io/argo/access-token/): it depends. I would expect them to last indefinately.
