### ISSUE TITLE
Workflows UI step links bug

### ISSUE THREAD

**Issue by mecampbellsoup** [argoproj/argo#4160]
## Summary 

When executing a workflow that has conditional steps/branches therein, the UI misrepresents the link between steps in certain cases.

![image](https://user-images.githubusercontent.com/2043821/94592525-08530180-0257-11eb-98f0-c9e494e33bcd.png)

## Diagnostics

* Running Arog 2.11.0

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Missing reproduction steps. Please add them.
