### ISSUE TITLE
Why there is no yaml tag in golang struct definition such as argoproj.argo.pkg.apis.workflow.v1alpha1.Workflow

### ISSUE THREAD

**Issue by gtarcoder** [argoproj/argo#4167]
There is no yaml tag in golang struct definition such as argoproj.argo.pkg.apis.workflow.v1alpha1.Workflow, so it is hard to decode from yaml to golang struct

This should be useful in some cases, i.e. given a yaml file, submit it to argo using argo's golang sdk.

**Comment by simster7** [comment]
Not sure what you mean, we unmarshal/decode from YAML almost ubiquitously in the code base. Here is an example of a function that does it:

```
func unmarshalWF(yamlStr string) *wfv1.Workflow {
	var wf wfv1.Workflow
	err := yaml.Unmarshal([]byte(yamlStr), &wf)
	if err != nil {
		panic(err)
	}
	return &wf
}
```
Does this help?

**Comment by gtarcoder** [comment]
> Not sure what you mean, we unmarshal/decode from YAML almost ubiquitously in the code base. Here is an example of a function that does it:
> 
> ```
> func unmarshalWF(yamlStr string) *wfv1.Workflow {
> 	var wf wfv1.Workflow
> 	err := yaml.Unmarshal([]byte(yamlStr), &wf)
> 	if err != nil {
> 		panic(err)
> 	}
> 	return &wf
> }
> ```
> 
> Does this help?

Sometimes yaml.unmarshal can not decode all fields defined in wfv1.Workflow, for example, we can not decode Workflow.Spec.OnExit from "onExit" or "on_exit", and it can only be decoded successfully from "onexit".
