### ISSUE TITLE
unmarshal to workflow struct failed,if outputs.parameters.value is a number

### ISSUE THREAD

**Issue by gosoon** [argoproj/argo#4169]
## Summary 

What happened/what you expected to happen?

The conversion of Workflow YAML to Argo Workflow Struct failed，error is： 
```
json: cannot unmarshal number into Go struct field Parameter.status.nodes.outputs.parameters.value of type string
```

Below is the Workflow I specified for the output，the outputs.parameters.value is displayed as a number in YAML
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: "2020-09-29T03:54:31Z"
  generateName: test-client-
  generation: 5
  labels:
    workflows.argoproj.io/completed: "true"
    workflows.argoproj.io/phase: Succeeded
  name: test-client-pdzbm
  namespace: default
  resourceVersion: "72569130"
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/default/workflows/test-client-pdzbm
  uid: ef76c688-71ed-4683-a43c-35e6706784f5
spec:
    ......
status:
  conditions:
  - status: "True"
    type: Completed
  finishedAt: "2020-09-29T03:55:12Z"
  nodes:
    test-client-pdzbm-3099866031:
      boundaryID: test-client-pdzbm
      displayName: create-appstack
      finishedAt: "2020-09-29T03:55:10Z"
      hostNodeName: bjrz-rs2569.lf
      id: test-client-pdzbm-3099866031
      inputs:
        parameters:
        - name: body
          value: '{"isCreateService":false}'
      name: test-client-pdzbm.create-appstack
      outputs:
        exitCode: "0"
        parameters:
        - globalName: service-A-Id
          name: serviceId
          value: 1017125                                 // output is a number 
          valueFrom:
            path: /result/serviceId
      phase: Succeeded
      resourcesDuration:
        cpu: 70
        memory: 70
      startedAt: "2020-09-29T03:54:31Z"
      templateName: create-service-A
      templateScope: local/test-client-pdzbm
      type: Pod
  outputs:
    parameters:
    - name: service-A-Id
      value: 1017125                      // output is a number 
  phase: Succeeded
  resourcesDuration:
    cpu: 70
    memory: 70
  startedAt: "2020-09-29T03:54:31Z"
``` 

but in workflow struct，output type is *string.

```github.com/argoproj/argo/pkg/apis/workflow/v1alpha1/workflow_types.go
// Parameter indicate a passed string parameter to a service template with an optional default value
type Parameter struct {
    ......

    // Value is the literal value to use for the parameter.
    // If specified in the context of an input parameter, the value takes precedence over any passed values
    Value *string `json:"value,omitempty" protobuf:"bytes,3,opt,name=value"`

    ......
}
```

The failure because wait container to save the output value without escaping it.

## Diagnostics

What version of Argo Workflows are you running?

```yaml
# argo version
argo: v2.10.1
  BuildDate: 2020-09-02T22:53:49Z
  GitCommit: 854444e47ac00d146cb83d174049bfbb2066bfb2
  GitTreeState: clean
  GitTag: v2.10.1
  GoVersion: go1.13.4
  Compiler: gc
  Platform: linux/amd64
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by simster7** [comment]
Can you add a sample workflow to reproduce this issue please? I would also try upgrading to 2.11.1 and seeing if that fixes the issue

**Comment by alexec** [comment]
Parameters must be string - maybe quote them?

**Comment by alexec** [comment]
@simster7 I'm seeing too many parameters must be a string. Maybe we should change them to `item`? Thoughts?

**Comment by simster7** [comment]
Is there a chance this workflow that there is a mismatch between the controller and CLI versions?

**Comment by alexec** [comment]
This is impacting too many people so I will take action to fix it.

**Comment by alexec** [comment]
Relates to #3960

**Comment by alexec** [comment]
No longer planning to fix this.

**Comment by AvasDream** [comment]
Since this is the first thing that comes up when googling the error I add my solution. 

My script template looked like this: 

```
  - name: task-template
    inputs: 
      parameters: 
        name: text
    script:
      image: python:3.8
      command: [python]
      source: |
        print("{{inputs.parameters.text}}")
```

And should have been:

```
  - name: task-template
    inputs: 
      parameters: 
        - name: text
    script:
      image: python:3.8
      command: [python]
      source: |
        print("{{inputs.parameters.text}}")
```

The parameters name key was not a list. `  name: text` vs `  - name: text`

**Comment by swafa** [comment]
> No longer planning to fix this.

@alexec For  a particular node, we need to supply/set an outputParameter that is not a String (but rather a number or an object consisting of multiple fields). Is this currently still not possible?

I'm getting this error message when supplying an object for example to the outputParameters field in the body of the **/set** endpoint:

"unable to parse output parameter set request: json: cannot unmarshal **object** into Go value of type string"

and this one when attempting to provide a number:

"unable to parse output parameter set request: json: cannot unmarshal **number** into Go value of type string"

Is there no way of defining the type of the output parameter? Kindly, advice on what's the best approach to tackle this.

**Comment by alexec** [comment]
Try quoting the number?

**Comment by swafa** [comment]
> Try quoting the number?

@alexec  Quoting the number would work of course but it's a workaround that I was trying to avoid having to apply since we're calling this programmatically after serializing a POJO object to JSON.

Also, there are more complex cases when the output parameter is a JSON object (and not just a string). That JSON object could also have encapsulated objects which adds more to the complexity. Are there no plans to support such use cases? Only String OutputParameters will be supported then? Any other ideas?

**Comment by swafa** [comment]
@alexec I also noticed that the issue boils down to the fact that escaped double quotes are not allowed within the **outputParameters** String.

Currently (v 3.3.0), providing **outputParameters** like this:

"outputParameters": "{\"result\": \"{\"foo\": \"bar\", \"foo1\": \"bar1\"}\"}"

Results in an error:

{
    "code": 2,
    "message": "unable to parse output parameter set request: invalid character 'f' after object key:value pair"
}

Because the escaped double quotes inside the output parameter's ("result") value get treated just like the ones wrapping the whole value.

Is there any way that I am missing to supply/escape double quotes **within** the outputParameters String?
