### ISSUE TITLE
Kubectl deployment example

### ISSUE THREAD

**Issue by mukulikak** [argoproj/argo#417]
Hi,
1. Can we redo the microservices demo with kubectl commands https://github.com/argoproj/microservices-demo/tree/master/.argo. I created a workflow in the same folder and Abhinav created the kubectl image to use kubectl deploy but at that time the services were giving error.

2.Write a workflow to do rolling upgrade and blue green deployment of one service from the above

3.Write a workflow to deploy in 2 kubernetes clusters in different AWS or GKE regions

4. See how to monitor these deployments

**Comment by pratulw** [comment]
Francis please work on this
