### ISSUE TITLE
default page limits in argo server

### ISSUE THREAD

**Issue by sh-tatsuno** [argoproj/argo#4179]
# Summary

Can I set default page limits in argo server? (e.g. limit: 100)
When colleagues first access to web UI, it takes time to load all jobs.
I know that we can set page limit at the bottom of the top page, but I want to know the way to set the limit in advance 

# Use Cases

like this in main configmap or in argo-server manifest.

```
data:
--
  | config: \|
  |    # enable persistence using postgres
  |    persistence:
  |       connectionPool:
  |         maxIdleConns: 100
  |         maxOpenConns: 0
  |   pageDefaultLimit: 100 <- like this
```

When new members use argo, 

of course, it can be OK

```
https://{argo-domain}?limit=100
```

But, if possible, I want to set the limit as default value for avoiding all job scanning

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Can I please ask for more information?

* How long does it take to load?
* You you go into the webconsole and see what's actually taking a long time? It might not be due to the number of workflows.
