### ISSUE TITLE
Update `Dockerfile` with USER (if possible)

### ISSUE THREAD

**Issue by alexec** [argoproj/argo#4182]
# Summary

https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#user

# Use Cases

When would you use this?

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by whynowy** [comment]
https://github.com/argoproj/argo-rollouts/pull/498

**Comment by jessesuen** [comment]
https://github.com/argoproj/argo-cd/pull/3108

**Comment by alexec** [comment]
Duplicate of #1824
