### ISSUE TITLE
Makefile seems to have deprecated k3d commands

### ISSUE THREAD

**Issue by kpr6** [argoproj/argo#4206]
## Summary 

What happened/what you expected to happen?

After starting k3d cluster locally, if I run `make start` I get an error
```
➜  argo git:(learning) ✗ make start
# GIT_TAG=v2.10.0-rc1, GIT_BRANCH=learning, GIT_TREE_STATE=dirty, VERSION=latest, DEV_IMAGE=true, K3D=true
killall argo workflow-controller kubectl || true
No matching processes belonging to you were found
k3d start
Error: unknown command "start" for "k3d"
Run 'k3d --help' for usage.
FATA[0000] unknown command "start" for "k3d"            
make: *** [install] Error 1
➜  argo git:(learning) ✗ kubectl cluster-info
Kubernetes master is running at https://0.0.0.0:61662
CoreDNS is running at https://0.0.0.0:61662/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
Metrics-server is running at https://0.0.0.0:61662/api/v1/namespaces/kube-system/services/https:metrics-server:/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
```

## Diagnostics

What Kubernetes provider are you using? 
`K3d`
What version of Argo Workflows are you running? 
```
argo: latest+9319c07.dirty
  BuildDate: 2020-10-03T06:45:57Z
  GitCommit: 9319c074e742c5d9cb97d6c5bbbf076afe886f76
  GitTreeState: dirty
  GitTag: v2.10.0-rc1
  GoVersion: go1.14.3
  Compiler: gc
  Platform: darwin/amd64
```
This line here for ref: https://github.com/argoproj/argo/blob/300634af42a3017a5354468a2779ef1fa5e37931/Makefile#L326
```yaml
Paste a workflow that reproduces the bug, including status:
kubectl get wf -o yaml ${workflow} 
```

```
Paste the logs from the workflow controller:
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name) | grep ${workflow}
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexcapras** [comment]
I'm experiencing an issue that i think might be related. Specifically, using the Makefile for local development doesn't seem to pick up the locally built executor image. The image gets built fine, but k3d isn't able to access the local image registry, so it always ends up pulling it from docker hub.

(As a workaround for local dev on the executor image, I am just building the image and using it in a regular deployment, following the quickstart guide)

**Comment by alexec** [comment]
@kpr6 would you like to submit a PR to fix? You'll need to change `github/workflow/ci-build.yaml` too.
