### ISSUE TITLE
Golang example outdated.

### ISSUE THREAD

**Issue by nityanandagohain** [argoproj/argo#4214]
## Summary 

The example https://github.com/argoproj/argo/blob/master/examples/example-golang/main.go doesn't work it throws
```
 Error: workflows must use workflowTemplateRef to be executed when the controller is in reference mode
```

Argo version is v2.11.0

I have the example modified to work where I have created WorkflowTemplate and submitted a workflow referencing the WorkflowTemplate, should we update the same example or add as a different example?

**Comment by simster7** [comment]
Whoever set up your Argo controller turned on a setting to only allow workflows that use `workflowTemplateRef` to run. This isn't an issue with the example itself, but instead your controller is not configured to work with that example.

**Comment by simster7** [comment]
See: https://github.com/argoproj/argo/blob/master/docs/workflow-requirements.md

**Comment by nityanandagohain** [comment]
Thanks @simster7
