### ISSUE TITLE
Argo lint command that validates any argo object?

### ISSUE THREAD

**Issue by max-sixty** [argoproj/argo#4221]
# Summary

Any thoughts on an `argo lint`-like command to lint any argo object? 

# Use Cases

Currently I have a path with a mix of `WorkflowTemplate`, `CronWorkflow`, and a couple `Workflow`s.

`argo lint` fails because there are some files without a `Workflow`, and same for each of `argo cron lint` and `argo workflow lint`. 

Other options include:
- Letting each command pass if there is no matching object in a file, such that someone can run all three commands over all their files, and each would pick up its respective objects
- On balance saying people should organize their workflow files by tipe

Thanks as ever!

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Related to #3728

**Comment by alexec** [comment]
@max-sixty I started work on fixing this in #3734, but I have had to re-prioritise. Would you like to take over?

**Comment by max-sixty** [comment]
Ah, sorry I missed the duplicate.

I would be keen to contribute at some point given great I think argo is. But it won't be that soon unfortunately, since I'm a go newbie, and have a understanding with my firm to limit my OSS contributions to xarray while they work out a more general policy.

**Comment by agilgur5** [comment]
This may have been fixed by #10059

**Comment by agilgur5** [comment]
> `argo lint` fails because there are some files without a `Workflow`, and same for each of `argo cron lint` and `argo workflow lint`.

Woops I misread and missed this initially. This was completed in #5224
