### ISSUE TITLE
 v2.11.2: Unsuccessful HTTP response

### ISSUE THREAD

**Issue by meurig** [argoproj/argo#4231]
## Summary 

Upon upgrading from v2.10 to v2.11 I'm faced with the following error:

![image](https://user-images.githubusercontent.com/507747/95350330-f35e1a00-08b7-11eb-9332-47e339158990.png)

The link address is:
https://argo-dev/api/v1/workflows/argo?fields=metadata,items.metadata.uid,items.metadata.name,items.metadata.namespace,items.metadata.labels,items.status.phase,items.status.finishedAt,items.status.startedAt,items.spec.suspend

Hitting that address directly gives me:
{"code":2,"message":"v1alpha1.WorkflowList.Items: v1alpha1.Workflows: v1alpha1.Workflow.Spec: v1alpha1.WorkflowSpec.Templates: []v1alpha1.Template: v1alpha1.Template.DAG: v1alpha1.DAGTemplate.Tasks: []v1alpha1.DAGTask: v1alpha1.DAGTask.v1alpha1.DAGTask.Template: Name: Arguments: v1alpha1.Arguments.Parameters: []v1alpha1.Parameter: v1alpha1.Parameter.Value: ReadString: expects \" or n, but found 1, error found in #10 byte of ...|,\"value\":1}]},\"name\"|..., bigger context ...|uments\":{\"parameters\":[{\"name\":\"seconds\",\"value\":1}]},\"name\":\"start\",\"template\":\"sleep-n-sec\"},{\"arg|..."}

Downgrading to v2.10.2 solves the issue. I've also tried with v2.11.0 and the issue returns.

I've not tried with a fresh install of argo yet.

## Diagnostics

What Kubernetes provider are you using? 
v1.19.2 (running on hyper-v)

What version of Argo Workflows are you running? 
v2.11.2 (installed with help chart v0.12.2)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by meurig** [comment]
I'm not sure if this is related to this issue:
https://github.com/argoproj/argo-helm/issues/462

**Comment by meurig** [comment]
Looking more closely at the response from that address I can see:
ReadString: expects " or n, but found 1, error found in #10 byte of ...|,"value":1}]},"name"|..., bigger context ...|uments":{"parameters":[{"name":"seconds","value":1}]},"name":"start","template":"sleep-n-sec"},{"arg|..."}

This led me to suspect the issue is in one of my workflows. Running the following seems to have fixed it:
argo -n argo delete --all

Sorry for the false alarm!

**Comment by alexec** [comment]
You have a malformed workflow in your system. This is typically because there is a number where there must be a string. This workflow will not execute. 

In your case, you have a number in your input parameters.

Options: 

* Find and delete the malformed workflow.
* Find and fix the malformed workflow.
* Wait for v2.11.2 which will tolerate this problem.

**Comment by meurig** [comment]
Thanks @alexec !

I'll try and remove the workflows that are causing the problem, but I'll also look forward to your fix in the next version (I think it will be v2.11.3). 

Thanks for all the options! 👍
