### ISSUE TITLE
Argo UI:  Cannot read property 'x' of undefined when viewing workflow (v2.11.0)

### ISSUE THREAD

**Issue by kevinhwang** [argoproj/argo#4232]
## Summary 

When viewing a workflow in the Argo UI, we get the following error:

![image](https://user-images.githubusercontent.com/11861195/95362005-53d26480-0882-11eb-919a-af5338de8bc8.png)

## Diagnostics

What Kubernetes provider are you using: IKS v1.29.1

What version of Argo Workflows are you running: v2.11.0

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
@kevinhwang can you please provide the workflow YAML? You can DM me if secret.

**Comment by alexec** [comment]
@kevinhwang please can you send me the problem workflow.

**Comment by kevinhwang** [comment]
> @kevinhwang can you please provide the workflow YAML? You can DM me if secret.

DMed you.

**Comment by alexec** [comment]
Loaded on `master` and works-for-me. Maybe bug just on v2.11.3 branch.

**Comment by alexec** [comment]
something to do with omitted node

wf-template-dce-update-lsltx-824903303
