### ISSUE TITLE
argo on GKE: https://[cluster ip]/app/hosts is broken

### ISSUE THREAD

**Issue by francis-ax** [argoproj/argo#424]
installed latest argo on GKE and find that cluster page always show empty page. 

https://[cluster ip]/app/hosts

![image](https://user-images.githubusercontent.com/29876185/32446067-ad67d990-c342-11e7-9f78-9a9708cec45b.png)

**Comment by sandeepbhojwani** [comment]
axstats is not installed for GKE and Minikube. Please hide hosts if not "full" or "aws" install

**Comment by alexmt** [comment]
Fixed
