### ISSUE TITLE
argo fixture page

### ISSUE THREAD

**Issue by francis-ax** [argoproj/argo#425]
argo fixture tab is not working in argo GKE/minikube installation, we should probably hide this page. 

https://[cluster_ip]/app/fixtures

![image](https://user-images.githubusercontent.com/29876185/32455018-f20f173e-c35b-11e7-9c82-214c4f78d82a.png)

**Comment by sandeepbhojwani** [comment]
fixture manager is not installed in GKE and Minikube scenario. Please hide if install is not "full" or "aws"

**Comment by alexmt** [comment]
Fixed
