### ISSUE TITLE
Master/workers controller architecture

### ISSUE THREAD

**Issue by naor2013** [argoproj/argo#4257]
# Summary

I want to set up Argo in a master/workers architecture. I want to manage the controller myself in my own namespace and have my users run their workflows in their own namespaces, using my "master" controller.
Is this kind of architecture possible? If not, will it be implemented in the future?

# Use Cases

My use case for this setup is that I want to manage the Argo usage: update the version for everyone, manage workflow, etc.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
Yes, It is a very well supported feature. You can install Controller as a cluster scope using `https://raw.githubusercontent.com/argoproj/argo/v2.11.2/manifests/install.yaml`. The controller will watch all namespaces in that cluster. The controller will act as a central orchestrator to execute the workflow on their namespace.

**Comment by naor2013** [comment]
> Yes, It is a very well supported feature. You can install Controller as a cluster scope using `https://raw.githubusercontent.com/argoproj/argo/v2.11.2/manifests/install.yaml`. The controller will watch all namespaces in that cluster. The controller will act as a central orchestrator to execute the workflow on their namespace.

How does that work in regards of UI? Do I set up one UI per namespace or one central UI where people can see only their namespace based on a token?

**Comment by sarabala1979** [comment]
I think it should handled by the token.

**Comment by jskrzypek** [comment]
Using the cluster install setup, there is just one instance of the argo server for the whole cluster. You don't need separate uis for each namespace

**Comment by naor2013** [comment]
I know it's unrelated but does Argo supports horizontal scaling? For the cases where the controller pod fails for whatever reason?

**Comment by jskrzypek** [comment]
looks like no: https://argoproj.github.io/argo/scaling/#horizontally-scaling

**Comment by jskrzypek** [comment]
if the pods fail in a way that is obvious to k8s, though they ought to be kicked and replaced the same as in any other deployment
