### ISSUE TITLE
Need to hide global search navigation items and hints if start typing.

### ISSUE THREAD

**Issue by wokeGit** [argoproj/argo#426]
For argo-lite we should hide most of global search elements.
<img width="1438" alt="screen shot 2017-11-06 at 19 17 29" src="https://user-images.githubusercontent.com/13086525/32457561-df7e36ea-c329-11e7-9726-eb938d94ccc0.png">
<img width="1439" alt="screen shot 2017-11-06 at 19 34 11" src="https://user-images.githubusercontent.com/13086525/32457565-e175f834-c329-11e7-8f9d-9bc204f00138.png">

**Comment by alexmt** [comment]
Fixed
