### ISSUE TITLE
Missing "chmod +x argo" in documentation files

### ISSUE THREAD

**Issue by wokeGit** [argoproj/argo#427]
https://github.com/argoproj/docs/blob/master/content/user_guide/install_argo_custom_k8s_cluster/install_argo_k8s_cluster_GKE.md, https://github.com/argoproj/docs/blob/master/content/user_guide/install_argo_custom_k8s_cluster/install_argo_k8s_cluster_Minikube.md
Installing Argo -> For Mac -> missing "chmod +x argo"

**Comment by cyee88** [comment]
It's fixed in the documentation and pushed to Git. On next docs release, the "chmod +x argo" will display in the Minikube and GKE install instructions.
