### ISSUE TITLE
Can't deploy example odoo app

### ISSUE THREAD

**Issue by wokeGit** [argoproj/argo#428]
I'm running example deploy odoo and I have strange issue:

ERR_CREATING_DEPLOYMENT
An error occurred (LoadBalancerNotFound) when calling the DescribeLoadBalancers operation: There is no ACTIVE Load Balancer named 'mwoyeqoddwdyrcmrrjqypgvdwnfyxrpl'

<img width="1420" alt="screen shot 2017-11-06 at 19 46 31" src="https://user-images.githubusercontent.com/13086525/32458113-94990748-c32b-11e7-9fc9-cbaf68a7b1fc.png">

My template parameters:
<img width="1439" alt="screen shot 2017-11-06 at 19 49 56" src="https://user-images.githubusercontent.com/13086525/32458159-c6ee6d96-c32b-11e7-981c-187062ff58e1.png">

**Comment by edlee2121** [comment]
This looks like it may be caused by #358.
@wokeGit Did you try to create a cluster with the same name before this failure?

**Comment by wokeGit** [comment]
@edlee2121  I don't remember but for 99% I didn't create a cluster with the same name before.
But once when our UI stopped work on this cluster, I suspend it for some time by the portal, maybe it can be a reason?

**Comment by edlee2121** [comment]
@wokeGit Before you suspended the cluster, deployments used to work? But afterwards, it does not?

**Comment by wokeGit** [comment]
@edlee2121 No, I don't know if it was working or not. I didn't try it earlier.

**Comment by edlee2121** [comment]
Most likely, the loadbalancer was never successfully created.
@sandeepbhojwani Please take a look when you get the chance.

**Comment by wokeGit** [comment]
Thank you @edlee2121 
I reinstalled cluster and everything works correct.

**Comment by edlee2121** [comment]
Looks like no longer a problem.
