### ISSUE TITLE
Support getting nominal datetime information into workflow

### ISSUE THREAD

**Issue by saranyaeu2987** [argoproj/argo#4281]
# Summary
Is there a way to get nominal date time (planned date time for a scheduled sample) for a run in cron workflow

# Use Cases

nominal date time  information will be used in workflow to retrieve file(s) created during that nominal date. 
nominal date time is not equivalent current datetime. Nominal date time will not change on failure retry or workflow rerun. 

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Is this the same as #3649?

**Comment by saranyaeu2987** [comment]
> Is this the same as #3649?

Yes. we can close this as duplicate.
