### ISSUE TITLE
Allow whitespace in templates

### ISSUE THREAD

**Issue by idsvandermolen** [argoproj/argo#4286]
# Summary

Currently Argo does not allow white space in templating, rendering of `{{workflow.parameters.variable}}` does correctly work, however `{{ workflow.parameters.variable }}` doesn't render the variable. Also `argo lint` did not issue any warning or error.

# Use Cases

I often find it more readable when you can add whitespace to separate markers like `{{` and `}}` from variable names.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Good idea. Would you like to investigate how to fix this?

**Comment by idsvandermolen** [comment]
I'm not that proficient in Go, but looks like in function `Replace` this https://github.com/argoproj/argo/blob/8facaceeb3515d804c3fd276b1802dbd6cf773e8/workflow/common/util.go#L375 
could probably be replaced with:
```golang
  replacement, ok := replaceMap[strings.TrimSpace(tag)]
```

**Comment by alexec** [comment]
Want to submit a PR?

**Comment by idsvandermolen** [comment]
👍 let me have a look

**Comment by idsvandermolen** [comment]
There you go, PR #4310

**Comment by idsvandermolen** [comment]
btw I had to make a few `Makefile` adjustments to be able to build (see PR #4311)
