### ISSUE TITLE
Install argo on minikube doesn't work

### ISSUE THREAD

**Issue by wokeGit** [argoproj/argo#431]
I'm using this documentation to get and run argo:
https://github.com/argoproj/docs/blob/master/content/user_guide/install_argo_custom_k8s_cluster/install_argo_k8s_cluster_AWS_GKE_Minikube.md
```
curl -sSL -O https://s3-us-west-1.amazonaws.com/ax-public/argocli/stable/darwin_amd64/argo
chmod +x argo
```
Then I'm trying to install:
```
$ argo cluster
argo cluster ops> argocluster install-argo-only --cloud-provider minikube --cluster-name <name_of_kubernetes_cluster> --kubeconfig /tmp/ax_kube/<name_of_kubeconfig_file>
```
And I receive this error:
![screen shot 2017-11-06 at 15 17 24](https://user-images.githubusercontent.com/13086525/32484334-b382573a-c39f-11e7-8f5b-b219d6ac1da1.png)

**Comment by pratulw** [comment]
Will close this as you are not using the correct branch for this release install. It should be master

**Comment by francis-ax** [comment]
please get the latest argo CLI from https://s3-us-west-1.amazonaws.com/ax-public/argocli/latest/darwin_amd64/argo
