### ISSUE TITLE
argo cron list  *NEXT RUN* report wrong if timezone is not set

### ISSUE THREAD

**Issue by monsterxx03** [argoproj/argo#4325]
## Summary 

What happened/what you expected to happen?

Submit a daily cronjob without timezone.

From the doc, I know the timezone should be set as machine's timezone. My workflow controller is running in UTC.

If I run `argo cron list` in UTC timezone, get correct value:

    NAME                         AGE   LAST RUN   NEXT RUN   SCHEDULE         SUSPENDED
    test-cron-wf                 2m    N/A        21h        1 1 * * *        false

Run `argo cron list` in UTC+8 local machine, get:

    NAME                         AGE   LAST RUN   NEXT RUN   SCHEDULE         SUSPENDED
    test-cron-wf                 3m    N/A        13h        1 1 * * *        false

I know the cron workflow is running in my expected schedule, just a client showing issue: https://github.com/argoproj/argo/blob/v2.11.6/pkg/apis/workflow/v1alpha1/cron_workflow_types.go#L32

It's using local time to calculate next schedule time, really confusing. I think argo should return NEXT RUN time on server side and return in api.

## Diagnostics

What version of Argo Workflows are you running? 

v2.11.4

```yaml
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  creationTimestamp: "2020-10-20T03:02:05Z"
  generation: 1
  labels:
    workflows.argoproj.io/controller-instanceid: argo-workflow
  name: test-cron-wf
  namespace: glow
  resourceVersion: "262639983"
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/glow/cronworkflows/test-cron-wf
  uid: c76b114b-7324-44a3-b0a1-d22fa043c5b3
spec:
  concurrencyPolicy: Replace
  schedule: 1 1 * * *
  startingDeadlineSeconds: 0
  workflowSpec:
    arguments: {}
    entrypoint: whalesay
    templates:
    - arguments: {}
      container:
        args:
        - date; sleep 90
        command:
        - sh
        - -c
        image: alpine:3.6
        name: ""
        resources: {}
      inputs: {}
      metadata: {}
      name: whalesay
      outputs: {}
status: {}

```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
I can see the problem. It is taking local timezone in both places because `timezone` is not defined in workflow.  I would recommend  to try the following workaround to specify the `timezone` in cronworkflow.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  creationTimestamp: "2020-10-20T03:02:05Z"
  generation: 1
  labels:
    workflows.argoproj.io/controller-instanceid: argo-workflow
  name: test-cron-wf
  namespace: glow
  resourceVersion: "262639983"
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/glow/cronworkflows/test-cron-wf
  uid: c76b114b-7324-44a3-b0a1-d22fa043c5b3
spec:
  concurrencyPolicy: Replace
  timezone: "America/Los_Angeles"
  schedule: 1 1 * * *
  startingDeadlineSeconds: 0
  workflowSpec:
    arguments: {}
    entrypoint: whalesay
    templates:
    - arguments: {}
      container:
        args:
        - date; sleep 90
        command:
        - sh
        - -c
        image: alpine:3.6
        name: ""
        resources: {}
      inputs: {}
      metadata: {}
      name: whalesay
      outputs: {}
status: {}
```
