### ISSUE TITLE
Weird space in parameter view

### ISSUE THREAD

**Issue by simonfrey** [argoproj/argo#4337]
# Summary

If a parameter is too long it gets broken into the next line. This next line is super far away from the first one. 

It would be great if the space is removed

![Screenshot](https://user-images.githubusercontent.com/24354822/96725324-0f31e780-13b1-11eb-812d-a2b87e2f1e62.png)

# Use Cases

When I check the parameters of a workflow step

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Ok. Would you like to submit a PR to fix?

**Comment by simonfrey** [comment]
Could do that. Would you mind adding the Hacktoberfest label, so it would count into the tshirt thingy? :D
