### ISSUE TITLE
import argo release-2.11 and client-go v0.17.8 in my project is Incompatible

### ISSUE THREAD

**Issue by jackywu** [argoproj/argo#4343]
## Summary 

What happened/what you expected to happen?
> my project depend on argo and kubernetes client-go, I wanna use the most recent version of argo which is release-2.11, and I know from [go.mod](https://github.com/argoproj/argo/blob/master/go.mod) that argo is depend on` k8s.io/client-go v0.17.8 `,  but I can not lock version argo release-2.11 and client-go v0.17.8 at the same time, after run 'go get github.com/argoproj/argo@release-2.11', the go command will update client-go to version v0.18.2, and it is incompatible with  argo release-2.11.

## Diagnostics

```
cd {path to your project}
go get k8s.io/client-go@v0.17.8 
go get github.com/argoproj/argo@release-2.11
```
and look at go.mod in your project directory. 

```
grep 'client-go' go.mod
```
that is v0.18.2 instead of v0.17.8 .

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
use go.mod `replace` directive?

**Comment by jackywu** [comment]
thanks @alexec ，I guess it works , and go further more ,  any other elegant way？

**Comment by alexec** [comment]
Not AFAIK - welcome to the world of Gomodules!
