### ISSUE TITLE
Manifest file `install.yaml` has incorrect ClusterRoleBindings.

### ISSUE THREAD

**Issue by cthulhu666** [argoproj/argo#4345]
## Summary 

What happened/what you expected to happen?

> Installation using `install.yaml` manifest fails (pods stuck in Error state)

## Diagnostics

What Kubernetes provider are you using? 

> GKE

What version of Argo Workflows are you running? 

> v2.11.6 

```yaml
wget https://raw.githubusercontent.com/argoproj/argo/stable/manifests/install.yaml
kubectl apply -f install.yaml
```

```
 ± k logs workflow-controller-56b9896b99-pkwwp
time="2020-10-22T11:14:50Z" level=info msg="config map" name=workflow-controller-configmap
time="2020-10-22T11:14:50Z" level=fatal msg="Failed to register watch for controller config map: configmaps \"workflow-controller-configmap\" is forbidden: User \"system:serviceaccount:default:argo\" cannot get resource \"configmaps\" in API group \"\" in the namespace \"default\""
```

I believe a fix is to change `namespace: argo` to `namespace: default` in `argo-binding` and `argo-server-binding` ClusterRoleBindings. At least it works for me.
I would submit a PR, but this manifest file is auto-generated and I have no idea based on what source files. Any hints?

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
you must install into the `argo` namespace

**Comment by alexec** [comment]
or use a tool to patch the manifests

**Comment by cthulhu666** [comment]
I see. 
I'm not sure if installation manual is clear on that regard.

**Comment by alexec** [comment]
Might be good to update it. Would you like to submit a PR?
