### ISSUE TITLE
'Internal error occurred: failed calling webhook "mutating.pod-env-webhook.svc"

### ISSUE THREAD

**Issue by perlinger** [argoproj/argo#4385]
After running command below to install argo-workflows on EKS cluster
kubectl apply -n argo -f https://raw.githubusercontent.com/argoproj/argo/stable/manifests/install.yaml

I ran this command to check on the health of the deployment
kubectl get deployment argo-server -n argo -0 yaml
And, in the status response was a message with an internal error.
How do I fix the error?

kubectl get deployment argo-server -n argo -o yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
annotations:
deployment.kubernetes.io/revision: "2"
kubectl.kubernetes.io/last-applied-configuration: |
{"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"argo-server","namespace":"argo"},"spec":{"selector":{"matchLabels":{"app":"argo-server"}},"template":{"metadata":{"labels":{"app":"argo-server"}},"spec":{"containers":[{"args":["server"],"image":"argoproj/argocli:v2.11.6","name":"argo-server","ports":[{"containerPort":2746,"name":"web"}],"readinessProbe":{"httpGet":{"path":"/","port":2746,"scheme":"HTTP"},"initialDelaySeconds":10,"periodSeconds":20}}],"nodeSelector":{"kubernetes.io/os":"linux"},"serviceAccountName":"argo-server"}}}}
creationTimestamp: "2020-10-26T21:34:00Z"
generation: 2
name: argo-server
namespace: argo
resourceVersion: "276522180"
selfLink: /apis/extensions/v1beta1/namespaces/argo/deployments/argo-server
uid: e6c55fe2-157e-4a53-a77a-6b070f368cd1
spec:
progressDeadlineSeconds: 600
replicas: 1
revisionHistoryLimit: 10
selector:
matchLabels:
app: argo-server
strategy:
rollingUpdate:
maxSurge: 25%
maxUnavailable: 25%
type: RollingUpdate
template:
metadata:
creationTimestamp: null
labels:
app: argo-server
spec:
containers:
- args:
- server
image: argoproj/argocli:v2.11.6
imagePullPolicy: IfNotPresent
name: argo-server
ports:
- containerPort: 2746
name: web
protocol: TCP
readinessProbe:
failureThreshold: 3
httpGet:
path: /
port: 2746
scheme: HTTP
initialDelaySeconds: 10
periodSeconds: 20
successThreshold: 1
timeoutSeconds: 1
resources: {}
terminationMessagePath: /dev/termination-log
terminationMessagePolicy: File
dnsPolicy: ClusterFirst
nodeSelector:
kubernetes.io/os: linux
restartPolicy: Always
schedulerName: default-scheduler
securityContext: {}
serviceAccount: argo-server
serviceAccountName: argo-server
terminationGracePeriodSeconds: 30
status:
conditions:

lastTransitionTime: "2020-10-26T21:34:01Z"
lastUpdateTime: "2020-10-26T21:34:01Z"
message: Deployment does not have minimum availability.
reason: MinimumReplicasUnavailable
status: "False"
type: Available
lastTransitionTime: "2020-10-26T21:34:01Z"
lastUpdateTime: "2020-10-26T21:34:01Z"
message: 'Internal error occurred: failed calling webhook "mutating.pod-env-webhook.svc":
an error on the server ("\n<title>500
Internal Server Error</title>\n
Internal Server Error
\n
The server
encountered an internal error and was unable to complete your request. Either
the server is overloaded or there is an error in the application.

") has
prevented the request from succeeding'
reason: FailedCreate
status: "True"
type: ReplicaFailure
lastTransitionTime: "2020-10-26T21:57:16Z"
lastUpdateTime: "2020-10-26T21:57:16Z"
message: Created new replica set "argo-server-55c988b69d"
reason: NewReplicaSetCreated
status: "True"
type: Progressing
observedGeneration: 2
unavailableReplicas: 2

**Comment by alexec** [comment]
This is a Kubernetes error. Not an Argo error. Please speak to you Kubernetes admin or provider.
