### ISSUE TITLE
v2.12: log viewer only showing first log line

### ISSUE THREAD

**Issue by alexec** [argoproj/argo#4388]
## Summary 

Should see all lines of logs, but only see first line.

## Diagnostics

Network shows all lines:

![image](https://user-images.githubusercontent.com/1142830/97246159-e72ff300-17b9-11eb-86e4-1e2f52928299.png)

UI states correct number of lines, but only first appears:

![image](https://user-images.githubusercontent.com/1142830/97246175-edbe6a80-17b9-11eb-8041-e643d634e3b9.png)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
@dcherman I think you worked on this recently?

**Comment by dcherman** [comment]
Huh, interesting; I'm not sure how my original PR actually worked.  Essentially what's happening is the lines array contains all of the expected content, however the way that we pass the observable to the logs viewer doesn't make sense - we're emitting the lines array as a value, however that will never get re-emitted as more lines get pushed (and that wouldn't make a ton of sense).

It should be relatively straightforward to fix by using a multicast observable - PR incoming.
