### ISSUE TITLE
Image processing workflow

### ISSUE THREAD

**Issue by mukulikak** [argoproj/argo#439]
Alex,

We need an image processing working

Upload an image on Google storage -> trigger Argo workflow on GKE (might need a google function to get the event 

Have 2-3 steps in the workflow to do different processing. The rest I am sure you will do cooler stuff than me :)

This is for a demo next Thursday which Ed will do so has the highest priority...

**Comment by edlee2121** [comment]
Initially, we can skip the google function integration and just run the workflow from CLI.

**Comment by alexmt** [comment]
Version for argo 1.x had been implemented: https://github.com/argoproj/image-processing-demo . Working on version for argo 2.x

**Comment by edlee2121** [comment]
Looks like this is done.
