### ISSUE TITLE
CD workflow

### ISSUE THREAD

**Issue by mukulikak** [argoproj/argo#440]
We need a CD workflow with kubernetes commands

1. Deploy sock shop using k8s yamls ( today it uses deployments)
2. Deploy sock shop using Helm charts ( available today, need to test it)
3. Deploy sock shop with statefulsets and PVs (GKE and AWS) - convert any of the mongodb based service from Deployment to statefulset using volumes
4.  Show Blue green deployment and rolling upgrade modifying the front end service  (GKE and AWS)
5. Show that deployment was successful by adding steps to check some logs/monitors - ELK and some open source monitor
6. Using Istio in the control plane to manage the services

**Comment by mukulikak** [comment]
1. Namespace based deployment workflow - directory of specs (2-3 directories). input parameter is git url of yamls and namespace name

2. Namespace healthchecker workflow - availability/ resource usage/ error

3. Helm deploy

4.Helm healthchecker

5. Blue green deployment (using label group)

6. fluentd + ELK (generic)

7.prometheus + grafana 

8.7.istio - manually inject to sock shop and collect telemetry

**Comment by edlee2121** [comment]
Done for now.
