### ISSUE TITLE
AWS IAM Role Access

### ISSUE THREAD

**Issue by bobhenkel** [argoproj/argo#443]
Does the role found here: https://github.com/argoproj/docs/blob/master/content/a_introduction_topics/AWS_IAM_Minion_role.md

Really need to have access to all that stuff? I understand the S3 access, but why does it want to have access to auto scaling, Route53, EC2, etc? I'm assuming most of these are for when you're running full blown Argo Cluster. My use case is to install this on my existing cluster. I have to hold off on the install until I understand why I need to allow my nodes all this access.

Can someone show a role that only contains the bare minimum access needed to run Argo on an existing K8s cluster? 

Thanks!

**Comment by mukulikak** [comment]
You are correct. We don't need those IAM permissions for installing only Argo workflow engine. Updated install docs.
