### ISSUE TITLE
globalname not working when Argo has no default archive location

### ISSUE THREAD

**Issue by sebastien-prudhomme** [argoproj/argo#4438]
## Summary 

Executing https://github.com/argoproj/argo/blob/master/examples/global-outputs.yaml on an Argo instance without default archive location

The workflow `generate` step fails with this error:

```
controller is not configured with a default archive location
```

I think it's a bug as if I've understood the usecase for globalname, an external artifact location is not needed when using such a config field.

## Diagnostics

What Kubernetes provider are you using? 

1.19

What version of Argo Workflows are you running? 

2.11.3

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Interesting. This workflow cannot work without a default location - where would it save the output?

**Comment by sebastien-prudhomme** [comment]
I misunderstood the feature. I close the issue.
