### ISSUE TITLE
Cannot set SSL certificate

### ISSUE THREAD

**Issue by AdamNowaczyk** [argoproj/argo#444]
I'm trying to assign wildcard SSL certificate in System Settings page. I'm getting "Success" message, but after navigating back to the page, old (self-signed) certificate is displayed. 
I'd like to be able to have proper SSL certificate for applications running on Argo platform.

**Comment by alexmt** [comment]
@AdamNowaczyk can you please check certificate using Firefox, Safari, Chrome and let me know if you can reproduce in all browsers?

**Comment by wokeGit** [comment]
It's done
