### ISSUE TITLE
WorkflowStatus check is flawed

### ISSUE THREAD

**Issue by jackywu** [argoproj/argo#4444]
## Summary 

in `github.com/argoproj/argo/pkg/apis/workflow/v1alpha1/workflow_types.go` of argo 2.11

```
// Failed return whether or not the workflow has failed
func (ws *WorkflowStatus) Failed() bool {
	return ws.Phase == NodeFailed
}
```

## Diagnostics

argo 2.11. I think it should be 

```go
// Failed return whether or not the workflow has failed
func (ws *WorkflowStatus) Failed() bool {
	return ws.Phase == NodeFailed || ws.Phase == NodeError
}
```

Is it necessary? @alexec 

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
There are already supporting functions in `Nodephase`.    `func (ws *WorkflowStatus) Failed() bool ` is a convenient function.
 Do you have any requirements to have FailedOrError()? 
https://github.com/argoproj/argo/blob/6016ebdd94115ae3fb13cadbecd27cf2bc390657/pkg/apis/workflow/v1alpha1/workflow_types.go#L1436-L1463

**Comment by jackywu** [comment]
oh, thanks @sarabala1979 , I'll close this issue.
