### ISSUE TITLE
Web UI Help Leads to Broken Link at https://argoproj.io/

### ISSUE THREAD

**Issue by bobhenkel** [argoproj/argo#445]
What did you do? (how to reproduce)
When clicking the link Argo Project under documentation it sends you to a broken link.
![screencapture at sun nov 12 17 28 29 cst 2017](https://user-images.githubusercontent.com/22456457/32704708-f5298f72-c7ce-11e7-8c76-fa89c26d4fc8.png)

What did you see? (include logs and screenshots as appropriate)
![screencapture at sun nov 12 17 30 49 cst 2017](https://user-images.githubusercontent.com/22456457/32704723-40acceb4-c7cf-11e7-99ed-72cae67a17c4.png)

What did you expect?
To be taken to the online documentation, most likely here https://applatix.com/open-source/argo/docs.

**Comment by alexmt** [comment]
Thank you for catching it @bobhenkel !

**Comment by wokeGit** [comment]
This is argo v1, in argo v2 this issue is fixed.

**Comment by alexmt** [comment]
Fixed

**Comment by andahme** [comment]
This is broken in `master` and tags `v2.1.0-alpha1`, `v2.2.0`.  `http://argoproj.io/` does not appear to be active and should probably link to the README at the deeper path https://argoproj.github.io/docs/argo/readme.html.
