### ISSUE TITLE
Transient database errors with offload enabled cause workflow to fail

### ISSUE THREAD

**Issue by markterm** [argoproj/argo#4464]
## Summary 

If there is a transient database connection error with offload enabled, then active workflows are marked as failed. I would at least expect some kind of retry.

## Diagnostics

What Kubernetes provider are you using? 
GKE

What version of Argo Workflows are you running? 
2.11.0-rc1

```
Paste the logs from the workflow controller:
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name) | grep ${workflow}
```

```
 time="2020-11-02T13:32:42Z" level=error msg="hydration failed: dial tcp 10.X.X.X:5432: connect: connection refused" namespace=default workflow=XXXX
 time="2020-11-02T13:32:42Z" level=error msg="Failed to archive workflow" err="dial tcp 10.X.X.X:5432: connect: connection refused" namespace=default workflow=XXXX
```

Seems to be caused by controller.go:517 which marks any workflows as 'error' if hydration fails.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
This should be fixed. I think we should create a `RetryingOffloadNodeStatusRepo` that delegates to another `OffloadNodeStatusRepo` - but adds retry using `wait.ExponentialBackoff`. Would you be interested in submitting a PR?

**Comment by markterm** [comment]
Thanks - I’m afraid I don’t have capacity to work on this in the immediate
future.

**Comment by alexec** [comment]
https://github.com/argoproj/argo/commit/ee848921348676718a8ab4cef8e8c2f52b86d124

**Comment by alexec** [comment]
Can you try with `v2.11.7`?

**Comment by markterm** [comment]
I tried turning off incoming connections for the DB for a few seconds while a workflow was running, and got this, which looks like a hard fail on dehydration:

```
workflow-controller-59d5969b9d-9j568 workflow-controller time="2020-11-09T16:37:01Z" level=warning msg="Failed to dehydrate: pq: database \"staging_codec\" is not currently accepting connections" namespace=staging workflow= XXXX-7ldnh
workflow-controller-59d5969b9d-9j568 workflow-controller time="2020-11-09T16:37:01Z" level=info msg="Updated phase Running -> Error" namespace=staging workflow= XXXX-7ldnh
workflow-controller-59d5969b9d-9j568 workflow-controller time="2020-11-09T16:37:01Z" level=info msg="Updated message  -> pq: database \"staging_codec\" is not currently accepting connections" namespace=staging workflow=XXXX-7ldnh
```

**Comment by alexec** [comment]
How long was your database offline for?

**Comment by markterm** [comment]
Ah - about a minute and I can see that the maximum retry is under a second.

How about having more retries for DB connection issues? eg single-AZ
database deployments with Amazon RDS can have outages of several minutes
during maintenance.

**Comment by alexec** [comment]
Maybe a transient error should not fail the workflow, instead, it should leave it running?

**Comment by markterm** [comment]
Yes - I think if there's an error accessing the database on hydration then we should leave it running and try again later. However if the error is on dehydration then we could end up with a set of workflow updates that we can't persist, I don't see a good way out of that so failing the workflow seems reasonable.

**Comment by alexec** [comment]
@jessesuen interesting point - SQL database could be offline for minutes.

* For hydration, was can just re-queue the workflow and try again.
* For dehydration data might be lost. 

What should we do - keep retrying for minutes?

**Comment by alexec** [comment]
@markterm I've created an engineering build for you to test:

```
docker pull argoproj/workflow-controller:nr
```

**Comment by markterm** [comment]
It looked like this worked :)

**Comment by markterm** [comment]
Just checking if this is going to be merged?

**Comment by alexec** [comment]
I've just re-implemented this is a simpler version. It's targetted for v2.12 which is rc-3 today.

**Comment by markterm** [comment]
great - thanks!

**Comment by alexec** [comment]
Merged into https://github.com/argoproj/argo/releases/tag/v2.12.0-rc4
