### ISSUE TITLE
All Argo Workflows logs are marked as error on stackdriver

### ISSUE THREAD

**Issue by pbonito** [argoproj/argo#4471]
Hi,
we are using Argo Workflows on GCP. All logs are currently captured in stackdriver but we observe a strange behaviour: all entries are marked as error regardless of log level. 
severity: "ERROR"  
 textPayload: "time="2020-11-05T17:25:18.576Z" level=info msg="Main container completed"

Same happens if we try to use python logging module. Only way to have log entries correctly marked as Info in stackdriver is to use print("message"), but that is really poor  implementation for logging.

Thanks in advance for your help.

**Comment by alexec** [comment]
@whynowy can you please share the fix?

**Comment by alexec** [comment]
```
// Output to stdout instead of the default stderr   // Can be any io.Writer, see below for File example   log.SetOutput(os.Stdout) https://github.com/sirupsen/logrus 
```

**Comment by alexec** [comment]
It appears that Golang apps typically logs to stderr by default. 

For me this is counter-intuitive, but @jessesuen suggests this is common for Golang and Python.

**Comment by afoltzm** [comment]
@whynowy I have opened a discussion about potentially overriding this default behavior in Logrus here: https://github.com/argoproj/argo-workflows/discussions/5871. Perhaps you'd like to describe your use case in that discussion?
