### ISSUE TITLE
"View Deployment" links points to wrong place.

### ISSUE THREAD

**Issue by wokeGit** [argoproj/argo#448]
If you deploy any app by argo. There are couple ways to navigate to deployed app.
The links points to timeline screen instead to corresponding app details screen.
![screen shot 2017-11-14 at 13 33 45](https://user-images.githubusercontent.com/13086525/32780243-dd166fa4-c940-11e7-8805-c7dd20e7363b.png)
![screen shot 2017-11-14 at 13 33 59](https://user-images.githubusercontent.com/13086525/32780244-dd2e4390-c940-11e7-9b5e-ac21f833876b.png)

**Comment by jessesuen** [comment]
Closing V1 issues
