### ISSUE TITLE
Update banner on argoproj.io

### ISSUE THREAD

**Issue by mukulikak** [argoproj/argo#449]
Please update banner saying

"Argo 2.0 coming soon as Custom Resource Definition to be up and running in less than a min and able to create workflows as custom kubernetes resources" Please reach out to Google group (https://groups.google.com/forum/#!forum/argoproj) for early access...

**Comment by rahuldhide** [comment]
Implement the banner as per the attached design.
![v2banner](https://user-images.githubusercontent.com/30275450/32874852-88ff7618-ca49-11e7-91a5-b07a4135445a.png)
