### ISSUE TITLE
docker image tag v2.12.0-rc1 is no manifest containing all architectures

### ISSUE THREAD

**Issue by mweibel** [argoproj/argo#4499]
## Summary 

https://hub.docker.com/layers/argoproj/argoexec/v2.12.0-rc1/images/sha256-c2489151857efca3073cf7ad90e955ce38d765c580d4d1906197a179f9cd2b30?context=explore

This tag seems to be a single tag of linux/amd64 and is not a manifest containing arm and windows builds (see [`latest`](https://hub.docker.com/layers/argoproj/argoexec/latest/images/sha256-a7ecbb53c0220d88c066e57a6add17aa74e8e66f8d212b7bfb110b6212192387?context=explore) for the difference). 

Unfortunately this prevents us from testing v2.12.0-rc1 on windows nodes. 

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
@argoproj/argo-windows can anyone please investigate?

**Comment by lippertmarkus** [comment]
Push for Windows Image failed: https://github.com/argoproj/argo/runs/1365261588?check_suite_focus=true

@alexec Don't you receive emails about such failures?

**Comment by mweibel** [comment]
FYI rc2 works now - I'm closing this issue therefore 👍
