### ISSUE TITLE
"TestWFDefaultWithWFTAndWf" is flakey

### ISSUE THREAD

**Issue by simster7** [argoproj/argo#4501]
Failed runs:

https://github.com/argoproj/argo/runs/1379089047

https://github.com/argoproj/argo/runs/1380263090

https://github.com/argoproj/argo/runs/1376428332

**Comment by sarabala1979** [comment]
I will take a look

**Comment by alexec** [comment]
This test is still flakey. I think it should create a new controller for each of the three tests.

**Comment by sarabala1979** [comment]
I will take a look.
