### ISSUE TITLE
prometheus names prefixed with argo_*

### ISSUE THREAD

**Issue by rosscdh** [argoproj/argo#4522]
# Summary
When running argo with potentially tens if not hundreds of other services all with prometheus scrapers
It is difficult to find the argo labels.

Ideally grouping of the prometheus labels should be together
currently they are scattered and not central to find without the docs

https://github.com/argoproj/argo/blob/25f12441f94dfb8e8b7ade5f20c79687e4ac1471/docs/metrics.md

# Use Cases

when searching for argo stats they are clearly grouped

instead of:

```
workflows_processed_count
count
operation_duration_seconds
error_count
queue_depth_count
queue_adds_count
queue_latency
```

they present and group as

```
argo_workflows_processed_count
argo_count
argo_operation_duration_seconds
argo_error_count
argo_queue_depth_count
argo_queue_adds_count
argo_queue_latency
```

especially with regards to things like "count"
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by simster7** [comment]
I'm sorry, I'm not sure I understand what the request is. Currently all Argo Workflows metrics are indeed grouped:

<img width="826" alt="image" src="https://user-images.githubusercontent.com/614838/98954906-edb1b080-24c3-11eb-8139-743611e51a86.png">

Are you asking that they do not be grouped?

**Comment by rosscdh** [comment]
apologies if this is the case! Thanks for the prompt response..
