### ISSUE TITLE
Tolerate large workflows in GRPC calls

### ISSUE THREAD

**Issue by simster7** [argoproj/argo#4529]
## Summary 

What happened/what you expected to happen?

## Diagnostics

What Kubernetes provider are you using? 

What version of Argo Workflows are you running? 

```yaml
Paste a workflow that reproduces the bug, including status:
kubectl get wf -o yaml ${workflow} 
```

```
Paste the logs from the workflow controller:
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name) | grep ${workflow}
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
https://godoc.org/google.golang.org/grpc#MaxCallSendMsgSize

**Comment by sarabala1979** [comment]
https://github.com/argoproj/argo/blob/d0082e8fb87fb731c7247f28da0c1b29b6fa3f02/server/apiserver/argoserver.go#L55
