### ISSUE TITLE
Add filter all cronWorkflow/templateWorkflow to UI Workflow labels filter

### ISSUE THREAD

**Issue by tczhao** [argoproj/argo#4532]
# Summary

What change needs making?

Add `workflows.argoproj.io/cron-workflow`, `workflows.argoproj.io/workflow-template` to the UI Labels autocomplete

For example,
![tempsnip](https://user-images.githubusercontent.com/20961507/99181798-0a304000-2785-11eb-80a8-70dbb85f1d10.png)

# Use Cases

When would you use this?

This will enable us to quickly filter all cronWorkflows or templateWorkflows.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by simster7** [comment]
Would you like to submit a PR for this?

**Comment by alexec** [comment]
This should be automatic - maybe you don't have any cron workflows?

**Comment by alexec** [comment]
It might be nice to have pre-populated lists of cron workflows and workflow templates to filter on, like the reports page.

![image](https://user-images.githubusercontent.com/1142830/99300718-ccbdc800-2801-11eb-84d5-f56d90c4082e.png)

**Comment by tczhao** [comment]
that sounds like a good idea, I will do PR for that,

regarding the "This should be automatic - maybe you don't have any cron workflows?"
I was in the line of 

if there exist any cron/template jobs,
we will add a 
`workflows.argoproj.io/cron-workflow`/`workflows.argoproj.io/workflow-template`
at the beginning of list of labels, to enable us filter all cron/template jobs
