### ISSUE TITLE
Capture container logs as part of artifacts

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo#454]
We currently do not upload container logs as artifacts, so access to logs are kept as long as kubernetes decides to keeplogs. For users who want more permanent storage of logs, a feature we can support is to upload container logs into the archive location of the template. Note that this must be optional because it is possible to configure controllers without an artifact repository.

**Comment by jessesuen** [comment]
Although most production k8s clusters will have some form of centralized logging, to clarify the motivation of this: we are imagining a class of applications built on-top of the workflow-controller, which do not want to assume things about the kubernetes environment. For example, the argo-ci project eventually wants to archive all aspects of a job (artifacts, logs, workflow result) in a single place in S3 so that it has zero dependency on the Kube API server and CI jobs are shown as static html.

**Comment by joshes** [comment]
@jessesuen what do you think for implementation strategy for this? api-level (behind the scenes) log capture and storage or something more like a pattern ala https://github.com/argoproj/argo/blob/master/examples/output-artifact-s3.yaml - kind of curious about picking at this, just need some direction to get started.

**Comment by joshes** [comment]
@jessesuen actually, after reading #745 ref'd above, it looks like it'd be done within the controller, which seems reasonable. will have a look at that as time permits.

**Comment by jessesuen** [comment]
Working on this now
