### ISSUE TITLE
Is `podReconciliation` upside down?

### ISSUE THREAD

**Issue by alexec** [argoproj/argo#4563]
# Summary

`podReconciliation` iterates over every pod returned for the workflow.  This could be thousands of pods. Could somehow iterating over nodes be faster?

# Use Cases

Contra: 
I believe that most of the reconciliation time is JSON marshaling.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by simster7** [comment]
Closed per Alex's request
