### ISSUE TITLE
argo ui  build  

### ISSUE THREAD

**Issue by EricYqd** [argoproj/argo#4591]
# Summary

I want to deploy the latest version of UI. I encounter various problems during the build process. Can I provide argoui dockerfile or image.

Thanks very  much！👍

**Comment by alexec** [comment]
You can pull the latest from Docker:

```
docker pull argoproj/argocil:latest
```

If you want to test the v3 UI:

```
docker pull argoproj/argocil:ui-v3
``

**Comment by simster7** [comment]
There is a typo above. The correct image name is `argoproj/argocli:...`

**Comment by EricYqd** [comment]
> You can pull the latest from Docker:
> 
> ```
> docker pull argoproj/argocli:latest
> ```
> 
> If you want to test the v3 UI:
> 
> ```
> docker pull argoproj/argoclil:ui-v3
> ``
> ```

First of all, thank you for your reply ，I have try   docker pull   argoproj/argoui:latest   ，but  is not the latest version of argo UI， Because it can only be used to read, not to update， I just tried your way, but it can not start  running ，Some startup parameters are required； I  pulled image “argoproj/argoclil:ui-v3 ”  but error message：”Error response from daemon: pull access denied for argoproj/argoclil, repository does not exist or may require 'docker login': denied: requested access to the resource is denied”
