### ISSUE TITLE
Quickstart "namespace" manifest causes lots of errors in workflow controller log

### ISSUE THREAD

**Issue by tomqwpl** [argoproj/argo#4593]
## Summary 

I installed the namespaced-install manifest : https://github.com/argoproj/argo/blob/master/manifests/namespace-install.yaml
In the log for the workflow controller, I then get 1 message every second saying:

     E1124 14:17:29.471963       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.8/tools/cache/reflector.go:105: Failed to list *unstructured.Unstructured: clusterworkflowtemplates.argoproj.io is forbidden: User "system:serviceaccount:tomq:argo" cannot list resource "clusterworkflowtemplates" in API group "argoproj.io" at the cluster scope

Full log is:
```
time="2020-11-24T14:07:31Z" level=info msg="config map" name=workflow-controller-configmap
time="2020-11-24T14:07:31Z" level=info msg="Configuration:
artifactRepository: {}
instanceID: tomq
metricsConfig: {}
nodeEvents: {}
podSpecLogStrategy: {}
sso:
  clientId:
    key: ""
  clientSecret:
    key: ""
  issuer: ""
  redirectUrl: ""
telemetryConfig: {}
"
time="2020-11-24T14:07:31Z" level=info msg="Persistence configuration disabled"
time="2020-11-24T14:07:31Z" level=info msg="Starting Workflow Controller" version=v2.11.8
time="2020-11-24T14:07:31Z" level=info msg="Workers: workflow: 32, pod: 32"
time="2020-11-24T14:07:31Z" level=info msg="Performing periodic GC every 5m0s"
time="2020-11-24T14:07:31Z" level=info msg="Persistence disabled - so archived workflow GC disabled - you must restart the controller if you enable this"
time="2020-11-24T14:07:31Z" level=info msg="Starting workflow TTL controller (resync 20m0s)"
time="2020-11-24T14:07:31Z" level=info msg="Starting CronWorkflow controller"
time="2020-11-24T14:07:31Z" level=info msg="...with InstanceID: tomq"
time="2020-11-24T14:07:31Z" level=info msg="Starting prometheus metrics server at localhost:9090/metrics"
time="2020-11-24T14:07:31Z" level=info msg="Started workflow TTL worker"
time="2020-11-24T14:07:31Z" level=info msg="Manager initialized successfully"
E1124 14:07:31.815988       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.8/tools/cache/reflector.go:105: Failed to list *unstructured.Unstructured: clusterworkflowtemplates.argoproj.io is forbidden: User "system:serviceaccount:tomq:argo" cannot list resource "clusterworkflowtemplates" in API group "argoproj.io" at the cluster scope
```

It's unclear whether the resulting controller works, indications are not, since it's not apparently choosing to run my workflow.

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by tomqwpl** [comment]
That's interesting. I have removed the "instanceID" configuration and it now works. I don't get the log messages, and it runs my workflow.
I was expecting to have to specify an instanceID, as well. We have a "globally installed" argo, that's watching all namespaces, and doesn't have an instanceID, so picks up anything anywhere without an instanceid annotation. So I specified instanceID on my installation to make sure that the workflows I created were processed by my own argo. It seems that combination doesn't work, or isn't intended to work.

**Comment by tomqwpl** [comment]
Very strange.
I've been through the process again, and now my symptoms have changed. Having put the instanceID back, I now just get:

    time="2020-11-24T16:15:57Z" level=warning msg="Controller doesn't have RBAC access for ClusterWorkflowTemplates"

once, and the result works.

**Comment by alexec** [comment]
You're not applying the master version of these manifests because the controller is logging the version as `v2.11.8` not `9ee4d446c1908f59240ca4b814ba565bb1acbc1f` (i.e. `latest`). 

I would expect `Controller doesn't have RBAC access for ClusterWorkflowTemplates` to be logged for a namespace install.  However, instance ID configuration should not have any impact on this, as we ignore this value for these.

**Comment by tomqwpl** [comment]
OK. Thanks.
I think I know what I probably did. I started out by just following the instructions to install the normal manifest, and then probably later tried to delete everything and install the namespaced one. One was probably the released one and one was master, and I probably didn't delete everything I needed to in between.
Good news is that it's working as expected now.
Thanks
