### ISSUE TITLE
`argo watch` can fail with `too old resource version`

### ISSUE THREAD

**Issue by alexec** [argoproj/argo#4596]
## Summary 

`argo watch` can return `too old resource version` after a long time and we could be tolerant of this.

## Diagnostics

This will be a challenge to fix. It only happens after a long time and the action you need to take will vary. 

See #4580

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by lueenavarro** [comment]
I'm getting this error as well
![image](https://user-images.githubusercontent.com/47080916/101334174-7d276500-38b2-11eb-8fc0-70fa1544c7e5.png)

**Comment by alexec** [comment]
@lueenavarro  I think you see #4580

**Comment by alexec** [comment]
Can anyone provide reliablee repro steps?
