### ISSUE TITLE
Workflow executor waitMainContainerStart returns while main container is in waiting state

### ISSUE THREAD

**Issue by fsiegmund** [argoproj/argo#4599]
## Summary 

WorkflowExecutor.waitMainContainerStart returns while main container is in waiting state, which causes premature detection of main container completion. Pod sidecars get killed and pod fails.

## Diagnostics

What Kubernetes provider are you using? 

GKE

What version of Argo Workflows are you running? 

master

Paste a workflow that reproduces the bug, including status:

Random error. Occurs when main container state looks like this:

{
   "containerID":"docker://eb6c6450564d1e43b99f05feacb975412d09108003d10ab675c1e857a3c95d2a",
   "image":"...",
   "imageID":"docker-pullable://...@sha256:795734650e78511ef194121e1e09552ad817b36bba8b815ced86de5fe739624f",
   "name":"main",
   "ready":false,
   "restartCount":0,
   "started":false,
   "state":{
      "waiting":{
         "message":"context deadline exceeded",
         "reason":"CreateContainerError"
      }
   }
}

```

---
<!-- Issue Author: Don't delete this message to encourage other users to support your issue! -->
**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Merged into https://github.com/argoproj/argo/releases/tag/v2.12.0-rc4
