### ISSUE TITLE
UI - The cron refresh of the "Timeline" view throw an error

### ISSUE THREAD

**Issue by sylock** [argoproj/argo#4609]
## Summary 

- From the UI, go to /workflows/
- First you get the list of your last workflows
- Do nothing and wait
- After some time instead of the list of workflows you get `Unknown error. Open your browser error console for more information.`

## Diagnostics

- From the UI, go to /workflows/
- First you get the list of your last workflows
![2020-11-27_13h53_12](https://user-images.githubusercontent.com/2362405/100451688-1fc43480-30b8-11eb-9800-a470485bb726.png)
- After some time, you can see the error in the UI and in the console
![2020-11-27_13h49_50](https://user-images.githubusercontent.com/2362405/100451415-aaf0fa80-30b7-11eb-9f39-2d510330cbd8.png)

The exact URL that throw the failure is:
```
http://<OBFUSCATED>:2746/api/v1/workflow-events/?listOptions.resourceVersion=30176595&fields=result.object.metadata.name,result.object.metadata.namespace,result.object.metadata.resourceVersion,result.object.metadata.uid,result.object.status.finishedAt,result.object.status.phase,result.object.status.startedAt,result.type,result.object.metadata.labels,result.object.spec.suspend
```
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by simster7** [comment]
Possibly related tohttps://github.com/argoproj/argo/issues/4529. The same endpoint is implicated

**Comment by sylock** [comment]
You can close this ticket. It was a mistake from my side.

**Comment by sylock** [comment]
You can close this ticket. It was a mistake from my side.
