### ISSUE TITLE
Kustomize install cluster argo error

### ISSUE THREAD

**Issue by FogDong** [argoproj/argo#4613]
## Summary 

Kustomize install cluster argo error

```
 kubectl kustomize cluster-install
Error: rawResources failed to read Resources: Load from path ../base failed: '../base' must be a file (got d='/argo/manifests/base')
```
kustomize version: v3.8.7

## Diagnostics

What Kubernetes provider are you using? 

What version of Argo Workflows are you running? 
master branch

```yaml
Paste a workflow that reproduces the bug, including status:
kubectl get wf -o yaml ${workflow} 
```

```
Paste the logs from the workflow controller:
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name) | grep ${workflow}
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
What version of Kustomize are you using? The latest v3?

**Comment by FogDong** [comment]
> What version of Kustomize are you using? The latest v3?

yes the version of kustomize is  v3.8.7

**Comment by alexec** [comment]
I don't think this is an Argo issue, because we use Kustomize 3 to create our manifest. Could you share your files?
