### ISSUE TITLE
Example memoize-simple.yaml is not valid

### ISSUE THREAD

**Issue by brabster** [argoproj/argo#4626]
## Summary 

Examples should validate by the JSON schema.

![image](https://user-images.githubusercontent.com/38702/100892381-2f75bb80-34b2-11eb-8113-3724d590fe01.png)

![image](https://user-images.githubusercontent.com/38702/100892648-72379380-34b2-11eb-8609-33329cf24d08.png)

Schema or example is wrong. This example will be ignored in the validation test until fixed (see `examples/validation_test.go`)

## Diagnostics

What Kubernetes provider are you using? N/A

What version of Argo Workflows are you running? N/A

```
Paste the logs from the workflow controller:
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name) | grep ${workflow}
N/A
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by whynowy** [comment]
@brabster - would you like to submit a PR to fix it?

**Comment by brabster** [comment]
@whynowy no, I'm not sure whether the schema or the example is right and I don't know the feature
