### ISSUE TITLE
Daemoned flag not removed and workflow not completed when daemon pod deleted.

### ISSUE THREAD

**Issue by lonsdale8734** [argoproj/argo#4652]
## Summary 

What happened/what you expected to happen?

Daemoned flag in `NodeStatus` not removed and workflow not completed when daemon pod deleted.

When daemon pod deleted, code blow may be unreachable.

https://github.com/argoproj/argo/blob/v2.11.8/workflow/controller/operator.go#L1089

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
@lonsdale8734 have you seen this in the wild? Do you have steps to reproduce please?
