### ISSUE TITLE
Workflow operation error when daemon pod failed

### ISSUE THREAD

**Issue by lonsdale8734** [argoproj/argo#4665]
## Summary 

What happened/what you expected to happen?

When daemon pod failed but its children are still running, workflow will be marked `Workflow operation error`.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Please provide reproduction steps, e.g. a workflow that produces this issue.
