### ISSUE TITLE
Header changes for V2

### ISSUE THREAD

**Issue by rahuldhide** [argoproj/argo#468]
- Remove notifications icon and notifications panel.
- Move Help on left nav
- Remove branch breadcrumb and branch selection panel
- Move date selection and job filter to left (use left align)
- Remove tabs- Overview, Commits and Jobs. Since we are just going to display a job list, these tabs are not required in V2

**Comment by wokeGit** [comment]
Done
https://github.com/argoproj/argo/pull/491
