### ISSUE TITLE
[UI] Unknown error. Open your browser error console for more information.

### ISSUE THREAD

**Issue by zen-xu** [argoproj/argo#4710]
## Summary 

I upgrade argo to 2.12.0-rc5, and I will meet error when workflow complete

![image](https://user-images.githubusercontent.com/38552291/101870065-d4cc1600-3bbb-11eb-9dc3-2652ddd0dde3.png)

## Diagnostics

What Kubernetes provider are you using?
v1.18.2 

What version of Argo Workflows are you running? 
v2.12.0-rc5

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Is your workflow GCed please?

**Comment by zen-xu** [comment]
> Is your workflow GCed please?

No, self hosted

**Comment by alexec** [comment]
I'm afraid the screenshot does not show either the HTTP status code or response body. Could you please attach them?

**Comment by zen-xu** [comment]
![image](https://user-images.githubusercontent.com/38552291/102161201-d3536400-3ec1-11eb-9555-ac6882b0f5e9.png)

**Comment by zen-xu** [comment]
ref  #4017 
I added the following annotation to the ingress rule config for Argo server will fix it 
```yaml
nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
```
