### ISSUE TITLE
For multiple step workflow, Recv() of WorkflowService_PodLogsClient for each single stage will block until all stages is done.

### ISSUE THREAD

**Issue by hyorigo** [argoproj/argo#4753]
## Summary 

What happened/what you expected to happen?

Recv() of WorkflowService_PodLogsClient returns io.EOF error right after the pod is completed.

## Diagnostics

What Kubernetes provider are you using? 

```
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

What version of Argo Workflows are you running? 

```
argo: v2.11.7
  BuildDate: 2020-11-02T20:59:01Z
  GitCommit: bf3fec176cf6bdf3e23b2cb73ec7d4e3d051ca40
  GitTreeState: clean
  GitTag: v2.11.7
  GoVersion: go1.13.15
  Compiler: gc
  Platform: linux/amd64
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Could you perhaps add some detail of why this is a problem and reproduction steps?
