### ISSUE TITLE
v2.12.1 manifests use v2.12.0-rc6 image

### ISSUE THREAD

**Issue by max-sixty** [argoproj/argo#4771]
## Summary 

Currently the most recent tag — v2.12.1 — has manifests which use v2.12.0-rc6 images: 
https://github.com/argoproj/argo/blob/v2.12.1/manifests/base/argo-server/argo-server-deployment.yaml#L17

Not sure what the process is for updating these — is it manual? I guess a PR isn't that helpful as the tag is unlikely to change?

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
> Not sure what the process is for updating these

It is meant to be automatic with a manual verification step.

**Comment by alexec** [comment]
This is broken

**Comment by max-sixty** [comment]
Fixed based on https://github.com/argoproj/argo/blob/v2.12.2/manifests/base/argo-server/argo-server-deployment.yaml#L17

Thank you very much for this feature — it makes upgrading trivial!
