### ISSUE TITLE
Change Go modules version to v3

### ISSUE THREAD

**Issue by alexec** [argoproj/argo#4786]
This is needed to fix/complete out Gomodules support.

Relates to #4197
Relates to #4331
Relates to #2602

**Comment by alexec** [comment]
@peterbourgon would you be interested in leading this?

**Comment by peterbourgon** [comment]
No :) But I'm happy to answer questions.

**Comment by alexec** [comment]
@tcolgate this will have a lot of impact - would you like to lead it?

**Comment by peterbourgon** [comment]
The PR does not resolve this issue. [See comments here](https://github.com/argoproj/argo/pull/4916#discussion_r561214858).

**Comment by simster7** [comment]
Fixed in https://github.com/argoproj/argo/pull/4959
