### ISSUE TITLE
Broken import when using Argo go client

### ISSUE THREAD

**Issue by JPZ13** [argoproj/argo#4791]
## Summary 

When building a service that invokes Argo using the go client, I frequently run into the [gnostic openapiv2 error](https://github.com/kubernetes/client-go/issues/741). [Newer kube dependencies](https://github.com/kubernetes/kube-openapi/pull/189) seem to have fixed this, but [existing versions](https://github.com/kubernetes/client-go/issues/741#issuecomment-606883355) will not be fixed 😞. 

I'd propose bumping the K8s dependencies to a newer version. I'm happy to own the issue and make the changes.
 
## Diagnostics

Here are my relevant go dependencies in go.mod:
```
require (
	github.com/argoproj/argo v0.0.0-20200724211756-20d2ace3d534
	k8s.io/api v0.17.8
	k8s.io/apimachinery v0.17.8
	k8s.io/client-go v0.17.8
	k8s.io/kubectl v0.17.5
)
```
Note: I use the scheme package in kubectl to interact with secrets.

Here's the error I get when running a build:
```
cannot load github.com/googleapis/gnostic/OpenAPIv2: module github.com/googleapis/gnostic@latest found (v0.5.3), but does not contain package github.com/googleapis/gnostic/OpenAPIv2
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Will this be fixed by #4425 ?

**Comment by JPZ13** [comment]
Yes. @NikeNano, would you mind if I started on #4425? I'm currently blocked by it

**Comment by NikeNano** [comment]
Sure @JPZ13 go for it, feel free to take what ever you want from my rough first stab at it, https://github.com/argoproj/argo/pull/4426

**Comment by JPZ13** [comment]
Thanks @NikeNano!

**Comment by JPZ13** [comment]
@alexec @NikeNano What's the command to update the client set? I ran `make codegen` a couple times and didn't get an update. I should be ready to put up a PR once I get client-gen to run properly.

**Comment by NikeNano** [comment]
Great @JPZ13, I am not aware of anything else than ``` make codegen```

**Comment by JPZ13** [comment]
You are the man @NikeNano. I had to run `chmod +x` on `$GOPATH/pkg/mod/k8s.io/code-generator@v0.20.1/generate-groups.sh` and then was able to generate the client set. Thanks for pointing that out! I'll get it all cleaned up and put out a PR.

**Comment by NikeNano** [comment]
Let me know when you have an PR @JPZ13, look forward to see this merged.

**Comment by JPZ13** [comment]
Will do! I'll tag you as a reviewer when I put up the PR @NikeNano
