### ISSUE TITLE
v2.12: `EstimatorFactory` can result in >1Gi memory usage

### ISSUE THREAD

**Issue by alexec** [argoproj/argo#4801]
## Summary 

`util.FromUnstructured` does a lot of memory allocations, especially in loops. If we have access to an `unstructured.Unstructured` and only need some of the information (any metadata, one or two fields) then we do not need to invoke it. 

Over time this type will start doing very large allocs resulting in rampant memory usage.

Fix: https://github.com/argoproj/argo/pull/4795/files#diff-c5ce6b47371bfd1984ffff5b3c51c4a92ac0af836a74b079d25bb79774cdc84aR49

**Comment by simster7** [comment]
Fix for this is out on https://github.com/argoproj/argo/releases/tag/v2.12.3
