### ISSUE TITLE
Unable to view workflow logs: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by r2sd** [argoproj/argo#4816]
## Summary 

I'm trying to view the logs of my workflow, it works fine when I do `argo logs -n argo 'custom-cdm-item-lfh6z'`.
But attempting to get the logs using the python client fails:
```
config = Configuration(host="http://localhost:2746")
client = ApiClient(configuration=config)
service = WorkflowServiceApi(api_client=client)
print(service.workflow_logs('argo', 'custom-cdm-item-lfh6z'))
```

I get the following stack trace:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/shridharshanrr/sdmain/lab/bodega/.venv/lib/python3.8/site-packages/argo/workflows/client/api/workflow_service_api.py", line 2310, in workflow_logs
    return self.workflow_logs_with_http_info(namespace, name, **kwargs)  # noqa: E501
  File "/Users/shridharshanrr/sdmain/lab/bodega/.venv/lib/python3.8/site-packages/argo/workflows/client/api/workflow_service_api.py", line 2436, in workflow_logs_with_http_info
    return self.api_client.call_api(
  File "/Users/shridharshanrr/sdmain/lab/bodega/.venv/lib/python3.8/site-packages/argo/workflows/client/api_client.py", line 364, in call_api
    return self.__call_api(resource_path, method,
  File "/Users/shridharshanrr/sdmain/lab/bodega/.venv/lib/python3.8/site-packages/argo/workflows/client/api_client.py", line 188, in __call_api
    raise e
  File "/Users/shridharshanrr/sdmain/lab/bodega/.venv/lib/python3.8/site-packages/argo/workflows/client/api_client.py", line 181, in __call_api
    response_data = self.request(
  File "/Users/shridharshanrr/sdmain/lab/bodega/.venv/lib/python3.8/site-packages/argo/workflows/client/api_client.py", line 389, in request
    return self.rest_client.GET(url,
  File "/Users/shridharshanrr/sdmain/lab/bodega/.venv/lib/python3.8/site-packages/argo/workflows/client/rest.py", line 230, in GET
    return self.request("GET", url,
  File "/Users/shridharshanrr/sdmain/lab/bodega/.venv/lib/python3.8/site-packages/argo/workflows/client/rest.py", line 224, in request
    raise ApiException(http_resp=r)
argo.workflows.client.exceptions.ApiException: (500)
Reason: Internal Server Error
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'Date': 'Thu, 31 Dec 2020 10:56:40 GMT', 'Transfer-Encoding': 'chunked'})
HTTP response body: {"error":{"grpc_code":13,"http_code":500,"message":"runtime error: invalid memory address or nil pointer dereference","http_status":"Internal Server Error"}}
```

## Diagnostics

What Kubernetes provider are you using?  minikube

What version of Argo Workflows are you running? argo v2.12.2

```yaml
Paste a workflow that reproduces the bug, including status:
kubectl get wf -o yaml ${workflow} 

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: "2020-12-31T10:36:40Z"
  generateName: custom-cdm-item-
  generation: 6
  labels:
    workflows.argoproj.io/completed: "true"
    workflows.argoproj.io/creator: system-serviceaccount-argo-argo-server
    workflows.argoproj.io/phase: Succeeded
    workflows.argoproj.io/workflow-archiving-status: Archived
  managedFields:
  - apiVersion: argoproj.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:generateName: {}
        f:labels:
          .: {}
          f:workflows.argoproj.io/creator: {}
      f:spec:
        .: {}
        f:arguments:
          .: {}
          f:parameters: {}
        f:entrypoint: {}
        f:templates: {}
      f:status: {}
    manager: argo
    operation: Update
    time: "2020-12-31T10:36:40Z"
  - apiVersion: argoproj.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          f:workflows.argoproj.io/completed: {}
          f:workflows.argoproj.io/phase: {}
          f:workflows.argoproj.io/workflow-archiving-status: {}
      f:status:
        f:conditions: {}
        f:finishedAt: {}
        f:nodes:
          .: {}
          f:custom-cdm-item-lfh6z:
            .: {}
            f:displayName: {}
            f:finishedAt: {}
            f:hostNodeName: {}
            f:id: {}
            f:name: {}
            f:outputs:
              .: {}
              f:artifacts: {}
              f:exitCode: {}
            f:phase: {}
            f:progress: {}
            f:resourcesDuration:
              .: {}
              f:cpu: {}
              f:memory: {}
            f:startedAt: {}
            f:templateName: {}
            f:templateScope: {}
            f:type: {}
        f:phase: {}
        f:progress: {}
        f:resourcesDuration:
          .: {}
          f:cpu: {}
          f:memory: {}
        f:startedAt: {}
    manager: workflow-controller
    operation: Update
    time: "2020-12-31T10:36:44Z"
  name: custom-cdm-item-lfh6z
  namespace: argo
  resourceVersion: "21409"
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/argo/workflows/custom-cdm-item-lfh6z
  uid: 216cd39f-d673-4f3e-b5c7-abbc84db878a
spec:
  arguments:
    parameters:
    - name: message
      value: good day!
  entrypoint: workflow
  templates:
  - arguments: {}
    container:
      args:
      - run_workflow.py
      - validate_and_get_ingredients
      - '{"node_count":2}'
      command:
      - python
      image: localhost:5000/shridharshan/custom-cdm-item
      name: ""
      resources: {}
    inputs: {}
    metadata: {}
    name: workflow
    outputs: {}
status:
  conditions:
  - status: "True"
    type: Completed
  finishedAt: "2020-12-31T10:36:44Z"
  nodes:
    custom-cdm-item-lfh6z:
      displayName: custom-cdm-item-lfh6z
      finishedAt: "2020-12-31T10:36:42Z"
      hostNodeName: minikube
      id: custom-cdm-item-lfh6z
      name: custom-cdm-item-lfh6z
      outputs:
        artifacts:
        - archiveLogs: true
          name: main-logs
          s3:
            accessKeySecret:
              key: accesskey
              name: my-minio-cred
            bucket: my-bucket
            endpoint: minio:9000
            insecure: true
            key: custom-cdm-item-lfh6z/custom-cdm-item-lfh6z/main.log
            secretKeySecret:
              key: secretkey
              name: my-minio-cred
        exitCode: "0"
      phase: Succeeded
      progress: 1/1
      resourcesDuration:
        cpu: 1
        memory: 1
      startedAt: "2020-12-31T10:36:40Z"
      templateName: workflow
      templateScope: local/custom-cdm-item-lfh6z
      type: Pod
  phase: Succeeded
  progress: 1/1
  resourcesDuration:
    cpu: 1
    memory: 1
  startedAt: "2020-12-31T10:36:40Z"

```

```
Paste the logs from the workflow controller:
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name) | grep ${workflow}

time="2020-12-31T10:36:40.547Z" level=info msg="Processing workflow" namespace=argo workflow=custom-cdm-item-lfh6z
time="2020-12-31T10:36:40.547Z" level=info msg="Updated phase  -> Running" namespace=argo workflow=custom-cdm-item-lfh6z
time="2020-12-31T10:36:40.547Z" level=info msg="Pod node custom-cdm-item-lfh6z initialized Pending" namespace=argo workflow=custom-cdm-item-lfh6z
time="2020-12-31T10:36:40.556Z" level=info msg="Created pod: custom-cdm-item-lfh6z (custom-cdm-item-lfh6z)" namespace=argo workflow=custom-cdm-item-lfh6z
time="2020-12-31T10:36:40.564Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=21386 workflow=custom-cdm-item-lfh6z
time="2020-12-31T10:36:40.565Z" level=info msg="Processing workflow" namespace=argo workflow=custom-cdm-item-lfh6z
time="2020-12-31T10:36:40.566Z" level=info msg="Skipped pod custom-cdm-item-lfh6z (custom-cdm-item-lfh6z) creation: already exists" namespace=argo podPhase=Pending workflow=custom-cdm-item-lfh6z
time="2020-12-31T10:36:40.578Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=21389 workflow=custom-cdm-item-lfh6z
time="2020-12-31T10:36:40.579Z" level=info msg="Processing workflow" namespace=argo workflow=custom-cdm-item-lfh6z
time="2020-12-31T10:36:40.579Z" level=info msg="Updating node custom-cdm-item-lfh6z message: ContainerCreating"
time="2020-12-31T10:36:40.579Z" level=info msg="Skipped pod custom-cdm-item-lfh6z (custom-cdm-item-lfh6z) creation: already exists" namespace=argo podPhase=Pending workflow=custom-cdm-item-lfh6z
time="2020-12-31T10:36:40.584Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=21390 workflow=custom-cdm-item-lfh6z
time="2020-12-31T10:36:41.556Z" level=info msg="Processing workflow" namespace=argo workflow=custom-cdm-item-lfh6z
time="2020-12-31T10:36:41.557Z" level=info msg="Skipped pod custom-cdm-item-lfh6z (custom-cdm-item-lfh6z) creation: already exists" namespace=argo podPhase=Pending workflow=custom-cdm-item-lfh6z
time="2020-12-31T10:36:43.529Z" level=info msg="Processing workflow" namespace=argo workflow=custom-cdm-item-lfh6z
time="2020-12-31T10:36:43.530Z" level=info msg="Setting node custom-cdm-item-lfh6z outputs"
time="2020-12-31T10:36:43.530Z" level=info msg="Updating node custom-cdm-item-lfh6z status Pending -> Running"
time="2020-12-31T10:36:43.530Z" level=info msg="Skipped pod custom-cdm-item-lfh6z (custom-cdm-item-lfh6z) creation: already exists" namespace=argo podPhase=Running workflow=custom-cdm-item-lfh6z
time="2020-12-31T10:36:43.536Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=21403 workflow=custom-cdm-item-lfh6z
time="2020-12-31T10:36:43.538Z" level=info msg="Processing workflow" namespace=argo workflow=custom-cdm-item-lfh6z
time="2020-12-31T10:36:43.538Z" level=info msg="Skipped pod custom-cdm-item-lfh6z (custom-cdm-item-lfh6z) creation: already exists" namespace=argo podPhase=Running workflow=custom-cdm-item-lfh6z
time="2020-12-31T10:36:44.559Z" level=info msg="Processing workflow" namespace=argo workflow=custom-cdm-item-lfh6z
time="2020-12-31T10:36:44.560Z" level=info msg="Updating node custom-cdm-item-lfh6z status Running -> Succeeded"
time="2020-12-31T10:36:44.560Z" level=info msg="Updated phase Running -> Succeeded" namespace=argo workflow=custom-cdm-item-lfh6z
time="2020-12-31T10:36:44.560Z" level=info msg="Marking workflow completed" namespace=argo workflow=custom-cdm-item-lfh6z
time="2020-12-31T10:36:44.560Z" level=info msg="Marking workflow as pending archiving" namespace=argo workflow=custom-cdm-item-lfh6z
time="2020-12-31T10:36:44.561Z" level=info msg="Checking daemoned children of " namespace=argo workflow=custom-cdm-item-lfh6z
time="2020-12-31T10:36:44.572Z" level=info msg="Workflow update successful" namespace=argo phase=Succeeded resourceVersion=21406 workflow=custom-cdm-item-lfh6z
time="2020-12-31T10:36:44.573Z" level=info msg="archiving workflow" namespace=argo uid=216cd39f-d673-4f3e-b5c7-abbc84db878a workflow=custom-cdm-item-lfh6z
time="2020-12-31T10:36:44.579Z" level=info msg="Labeled pod completed" namespace=argo pod=custom-cdm-item-lfh6z
time="2020-12-31T10:36:44.590Z" level=info msg="archiving workflow" namespace=argo uid=216cd39f-d673-4f3e-b5c7-abbc84db878a workflow=custom-cdm-item-lfh6z

```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Please attach the stack trace from `kubectl logs deploy/argo-server`

**Comment by r2sd** [comment]
Hi @alexec 
Here is the output of running `kubectl logs deploy/argo-server -n argo`:

`time="2021-01-04T05:21:51.946Z" level=info msg="Alloc=8947 TotalAlloc=236732 Sys=71616 NumGC=384 Goroutines=88"
time="2021-01-04T05:27:31.828Z" level=info msg="Alloc=8947 TotalAlloc=236736 Sys=71616 NumGC=387 Goroutines=88"
time="2021-01-04T05:32:31.825Z" level=info msg="Alloc=8947 TotalAlloc=236741 Sys=71616 NumGC=389 Goroutines=88"
time="2021-01-04T05:37:31.828Z" level=info msg="Alloc=8947 TotalAlloc=236745 Sys=71616 NumGC=392 Goroutines=88"
time="2021-01-04T05:42:31.833Z" level=info msg="Alloc=8947 TotalAlloc=236750 Sys=71616 NumGC=394 Goroutines=88"
time="2021-01-04T05:47:31.825Z" level=info msg="Alloc=8947 TotalAlloc=236754 Sys=71616 NumGC=396 Goroutines=88"
time="2021-01-04T06:11:32.585Z" level=info msg="Alloc=8947 TotalAlloc=236759 Sys=71616 NumGC=399 Goroutines=88"
time="2021-01-04T06:16:32.584Z" level=info msg="Alloc=8947 TotalAlloc=236763 Sys=71616 NumGC=401 Goroutines=88"
time="2021-01-04T06:21:32.588Z" level=info msg="Alloc=8947 TotalAlloc=236768 Sys=71616 NumGC=404 Goroutines=88"
time="2021-01-04T06:26:32.585Z" level=info msg="Alloc=8947 TotalAlloc=236772 Sys=71616 NumGC=406 Goroutines=88"
time="2021-01-04T06:29:51.150Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=GetInfo grpc.service=info.InfoService grpc.start_time="2021-01-04T06:29:51Z" grpc.time_ms=0.531 span.kind=server system=grpc
time="2021-01-04T06:29:51.151Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=GetVersion grpc.service=info.InfoService grpc.start_time="2021-01-04T06:29:51Z" grpc.time_ms=0.141 span.kind=server system=grpc
time="2021-01-04T06:29:51.232Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=GetInfo grpc.service=info.InfoService grpc.start_time="2021-01-04T06:29:51Z" grpc.time_ms=0.044 span.kind=server system=grpc
time="2021-01-04T06:29:53.795Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=ListCronWorkflows grpc.service=cronworkflow.CronWorkflowService grpc.start_time="2021-01-04T06:29:53Z" grpc.time_ms=4.569 span.kind=server system=grpc
time="2021-01-04T06:29:53.801Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=ListWorkflowTemplates grpc.service=workflowtemplate.WorkflowTemplateService grpc.start_time="2021-01-04T06:29:53Z" grpc.time_ms=17.235 span.kind=server system=grpc
time="2021-01-04T06:29:53.904Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=ListWorkflows grpc.service=workflow.WorkflowService grpc.start_time="2021-01-04T06:29:53Z" grpc.time_ms=29.463 span.kind=server system=grpc
time="2021-01-04T06:29:53.925Z" level=info msg="finished streaming call with code OK" grpc.code=OK grpc.method=WatchWorkflows grpc.service=workflow.WorkflowService grpc.start_time="2021-01-04T06:29:51Z" grpc.time_ms=2729.834 span.kind=server system=grpc
time="2021-01-04T06:30:21.828Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=CreateWorkflow grpc.service=workflow.WorkflowService grpc.start_time="2021-01-04T06:30:21Z" grpc.time_ms=9.983 span.kind=server system=grpc
time="2021-01-04T06:30:49.646Z" level=error msg="Recovered from panic: runtime error: invalid memory address or nil pointer dereference\ngoroutine 6793 [running]:\nruntime/debug.Stack(0xc00124a830, 0x1ee90a0, 0x4103530)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9d\ngithub.com/argoproj/argo/util/grpc.PanicLoggerStreamServerInterceptor.func1.1(0xc000184380, 0xc00124b930)\n\t/go/src/github.com/argoproj/argo/util/grpc/interceptor.go:31 +0x6e\npanic(0x1ee90a0, 0x4103530)\n\t/usr/local/go/src/runtime/panic.go:679 +0x1b2\ngithub.com/argoproj/argo/util/logs.WorkflowLogs(0x2fdb160, 0xc000d49830, 0x2f95120, 0xc00017d0a0, 0x3039200, 0xc0000e9ce0, 0x2fdb8e0, 0xc0009b19e0, 0x7fedae9a0360, 0xc000e10360, ...)\n\t/go/src/github.com/argoproj/argo/util/logs/workflow-logger.go:150 +0xccd\ngithub.com/argoproj/argo/server/workflow.(*workflowServer).PodLogs(0xc000671a40, 0xc0009b19e0, 0x7fedae9a0310, 0xc000e10360, 0xc000e10360, 0xc000e10360)\n\t/go/src/github.com/argoproj/argo/server/workflow/workflow_server.go:512 +0x2e2\ngithub.com/argoproj/argo/server/workflow.(*workflowServer).WorkflowLogs(0xc000671a40, 0xc0009b19e0, 0x2ff7d00, 0xc000e10360, 0xc000671a40, 0x414e960)\n\t/go/src/github.com/argoproj/argo/server/workflow/workflow_server.go:516 +0x6d\ngithub.com/argoproj/argo/pkg/apiclient/workflow._WorkflowService_WorkflowLogs_Handler(0x21491c0, 0xc000671a40, 0x2ff0bc0, 0xc000c42540, 0xc000d49830, 0x0)\n\t/go/src/github.com/argoproj/argo/pkg/apiclient/workflow/workflow.pb.go:2009 +0x10c\ngithub.com/argoproj/argo/server/auth.(*gatekeeper).StreamServerInterceptor.func1(0x21491c0, 0xc000671a40, 0x2ff0bc0, 0xc000c42540, 0xc000c42460, 0x2bb50b0, 0x0, 0x0)\n\t/go/src/github.com/argoproj/argo/server/auth/gatekeeper.go:86 +0xcc\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1.1(0x21491c0, 0xc000671a40, 0x2ff0bc0, 0xc000c42540, 0x0, 0x203000)\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.1.0/chain.go:49 +0x5f\ngithub.com/argoproj/argo/util/grpc.glob..func2(0x21491c0, 0xc000671a40, 0x2ff0bc0, 0xc000c42540, 0xc000c42460, 0xc000c424a0, 0xc, 0x2217a35)\n\t/go/src/github.com/argoproj/argo/util/grpc/interceptor.go:45 +0x4e\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1.1(0x21491c0, 0xc000671a40, 0x2ff0bc0, 0xc000c42540, 0x0, 0x0)\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.1.0/chain.go:49 +0x5f\ngithub.com/argoproj/argo/util/grpc.PanicLoggerStreamServerInterceptor.func1(0x21491c0, 0xc000671a40, 0x2ff0bc0, 0xc000c42540, 0xc000c42460, 0xc000c424c0, 0x0, 0x0)\n\t/go/src/github.com/argoproj/argo/util/grpc/interceptor.go:35 +0xa8\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1.1(0x21491c0, 0xc000671a40, 0x2ff0bc0, 0xc000c42540, 0x26, 0xbff4cb6664f02c5b)\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.1.0/chain.go:49 +0x5f\ngithub.com/grpc-ecosystem/go-grpc-middleware/logging/logrus.StreamServerInterceptor.func1(0x21491c0, 0xc000671a40, 0x2ff0da0, 0xc0011f6240, 0xc000c42460, 0xc000c424e0, 0xc000c42500, 0xc000c42460)\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.1.0/logging/logrus/server_interceptors.go:66 +0x176\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1.1(0x21491c0, 0xc000671a40, 0x2ff0da0, 0xc0011f6240, 0xc000ad4c20, 0x40c698)\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.1.0/chain.go:49 +0x5f\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1(0x21491c0, 0xc000671a40, 0x2ff0da0, 0xc0011f6240, 0xc000c42460, 0x2bb50b0, 0x2fdb160, 0xc000d49680)\n\t/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.1.0/chain.go:58 +0xcf\ngoogle.golang.org/grpc.(*Server).processStreamingRPC(0xc000403040, 0x3004660, 0xc0007d0300, 0xc00107a500, 0xc000671b00, 0x41129a0, 0x0, 0x0, 0x0)\n\t/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1336 +0x486\ngoogle.golang.org/grpc.(*Server).handleStream(0xc000403040, 0x3004660, 0xc0007d0300, 0xc00107a500, 0x0)\n\t/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1409 +0xcc0\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0000587b0, 0xc000403040, 0x3004660, 0xc0007d0300, 0xc00107a500)\n\t/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:746 +0xbb\ncreated by google.golang.org/grpc.(*Server).serveStreams.func1\n\t/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:744 +0xa1\n"
time="2021-01-04T06:30:49.647Z" level=error msg="finished streaming call with code Internal" error="rpc error: code = Internal desc = runtime error: invalid memory address or nil pointer dereference" grpc.code=Internal grpc.method=WorkflowLogs grpc.service=workflow.WorkflowService grpc.start_time="2021-01-04T06:30:49Z" grpc.time_ms=27.392 span.kind=server system=grpc
time="2021-01-04T06:30:49.651Z" level=error msg="a container name must be specified for pod custom-cdm-item-jgx4s, choose one of: [wait main]" namespace=argo podName=custom-cdm-item-jgx4s workflow=custom-cdm-item-jgx4s
`
