### ISSUE TITLE
make db migration optional

### ISSUE THREAD

**Issue by book987** [argoproj/argo#4822]
# Summary

Hi.

We use argo internally with our own db platform, which disable all DDL operation for security reason, means we can only do DDL operation at db platform.

Currently we remove lines [workflow/controller/config.go:49-52](https://github.com/argoproj/argo/blob/master/workflow/controller/config.go#L49) as workaround.

Can we provide a `--ignore-db-migration` flag or a relative filed in configmap for ignoring db migration?
Or can we check schema before DDL operation instead of `create xxx if not exist`?

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Good idea. Would you like to submit a PR?

**Comment by book987** [comment]
> Good idea. Would you like to submit a PR?

Love to. I'll try my best.

**Comment by book987** [comment]
Hi @alexec 
I've just submit a PR, add an option `SkipDBMigration` in persistence configuration. Need review.

Plus, I think hardcoded SQL is not friendly for maintaining migration, also user should track SQL changes from commits. But I didn't find a good way (or popular way) managing db migration from other projects. And there's a [`ternary`](https://github.com/argoproj/argo/blob/master/persist/sqldb/migrate.go#L28) in argo which make things more complex. Maybe further discussion is needed, including whether current way is just fine.
