### ISSUE TITLE
useful to have an argo command that get the workflow controller logs

### ISSUE THREAD

**Issue by edlee2121** [argoproj/argo#483]
To debug problems that occur after submitting a workflow, would be useful to have an argo command that returns log messages related to a particular workflow.

**Comment by jessesuen** [comment]
The issue with this request, is that for argo to get the controller logs, argo CLI would have to make assumptions of how the controller was deployed (i.e. the namespace it was created in, as well as the deployment name). I'm not convinced argo cli can make those assumptions.

For the record, you could still get logs from the controller using the following one-liner:
```
$ kubectl logs -n kube-system -l app=workflow-controller
```

I think this should be sufficient for most users.

**Comment by edlee2121** [comment]
Could we have an argo command that basically runs that. Today, to debug certain workflow problems, one needs to look at the log for the controller, but a new user will not know how to access the controller logs.

**Comment by jessesuen** [comment]
As I mentioned in https://github.com/argoproj/argo/issues/483#issuecomment-347365402. The one-liner that I gave is making two assumptions that is not necessarily true:
1. the workflow-controller was installed in `kube-system`. It is possible to install it somewhere else.
2. the name of the deployment is `workflow-controller`. It is possible to use a different name for the deployment.

Both of these assumptions are unable to be determined by the CLI, specifically in the case when we support multiple controllers in a single cluster.

For debugging failed workflows, we should concentrate on improving the status information in workflow resources. The controller is not the right place for debugging workflows. Its for debugging the controller. Recent commits have addressed the issue of not providing sufficient error information about failed workflows.

**Comment by edlee2121** [comment]
I agree that users shouldn't need controller logs to debug workflows.
