### ISSUE TITLE
Flakey tests in TestWorkflowTemplateSuite

### ISSUE THREAD

**Issue by simster7** [argoproj/argo#4833]
`TestWorkflowTemplateSuite/TestSubmitWorkflowTemplate`
`TestWorkflowTemplateSuite/TestNestedWorkflowTemplate`
`TestWorkflowTemplateSuite/TestSubmitWorkflowTemplateWithEnum`

Example runs:
https://github.com/argoproj/argo/pull/4823/checks?check_run_id=1651690361

https://github.com/argoproj/argo/pull/4427/checks?check_run_id=1532851026

**Comment by sarabala1979** [comment]
It might be a k3d issue. Workflow didn't start on time. Currently, it is not happening.  We will keep eye on it.
