### ISSUE TITLE
Controller side workflow validation

### ISSUE THREAD

**Issue by gaganapplatix** [argoproj/argo#486]
```
time="2017-11-21T01:13:49Z" level=info msg="Step group node logging-workflow-lkxxp[0] (logging-workflow-lkxxp-1189724776) already marked completed" namespace=default workflow=logging-workflow-lkxxp
time="2017-11-21T01:13:49Z" level=info msg="Evaluating node logging-workflow-lkxxp[1].get-kibana-ip: template: kibana-svc-ip" namespace=default workflow=logging-workflow-lkxxp
time="2017-11-21T01:13:49Z" level=info msg="Creating Pod: logging-workflow-lkxxp[1].get-kibana-ip" namespace=default workflow=logging-workflow-lkxxp
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc0 pc=0xec56a8]
goroutine 21 [running]:
github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).addInputArtifactsVolumes(0xc42059cb40, 0xc42043d180, 0xc4201b0ea0, 0x0, 0x0)
	/root/go/src/github.com/argoproj/argo/workflow/controller/workflowpod.go:344 +0x2f8
github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).createWorkflowPod(0xc42059cb40, 0xc420173500, 0x27, 0xc4201b0ea0, 0xc4202a35e8, 0x0)
	/root/go/src/github.com/argoproj/argo/workflow/controller/workflowpod.go:177 +0x842
github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).executeScript(0xc42059cb40, 0xc420173500, 0x27, 0xc4201b0c30, 0x0, 0x0)
	/root/go/src/github.com/argoproj/argo/workflow/controller/operator.go:589 +0x4d
github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).executeTemplate(0xc42059cb40, 0xc4202a3540, 0xd, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc420173500, ...)
	/root/go/src/github.com/argoproj/argo/workflow/controller/operator.go:219 +0x788
github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).executeStepGroup(0xc42059cb40, 0xc420458780, 0x1, 0x4, 0xc4202c31c0, 0x19, 0xc42061f2e8, 0x0, 0x0)
	/root/go/src/github.com/argoproj/argo/workflow/controller/operator.go:412 +0x672
github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).executeSteps(0xc42059cb40, 0xc4202c3c80, 0x16, 0xc4201b09c0, 0x0, 0x0)
	/root/go/src/github.com/argoproj/argo/workflow/controller/operator.go:315 +0xca2
github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).executeTemplate(0xc42059cb40, 0xc4202c3d00, 0x11, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc4202c3c80, ...)
	/root/go/src/github.com/argoproj/argo/workflow/controller/operator.go:212 +0x450
github.com/argoproj/argo/workflow/controller.(*WorkflowController).operateWorkflow(0xc4200faaf0, 0xc4202918c0)
	/root/go/src/github.com/argoproj/argo/workflow/controller/operator.go:82 +0x491
github.com/argoproj/argo/workflow/controller.(*WorkflowController).Run(0xc4200faaf0, 0x1813600, 0xc4202f1700, 0xc4204a5cf0, 0xc420083ef0)
	/root/go/src/github.com/argoproj/argo/workflow/controller/controller.go:103 +0x355
created by main.Run
```

**Comment by gaganapplatix** [comment]
apiVersion: argoproj.io/v1
kind: Workflow
metadata:
  generateName: logging-workflow-
spec:
  entrypoint: sock-shop-logging

  templates:
  - name: sock-shop-logging
    steps:
    - - name: deploy
        template: logging-deploy
    - - name: get-kibana-ip
        template: kibana-svc-ip
    - - name: kibana-running
        template: kbiana-svc-check
        arguments:
          parameters:
          - name: kibana-ip
            value: "{{steps.generate.outputs.result}}"

  - name: logging-deploy
    inputs:
      artifacts:
      - name: logging-manifests
        path: /src
        git:
          repo: https://github.com/argoproj/example-cd.git
          revision: "master"
      - name: kubectl
        path: /usr/local/bin/kubectl
        http:
          url: https://storage.googleapis.com/kubernetes-release/release/v1.8.3/bin/linux/amd64/kubectl
        mode: 755
    container:
      image: docker.io/debian:9.2
      command: ["/bin/sh", "-c"]
      args: ['kubectl create -f "/src/example-cd/logging"']

  - name: kibana-svc-ip
    inputs:
      artifacts:
      - name: kubectl
        path: /usr/local/bin/kubectl
        http:
          url: https://storage.googleapis.com/kubernetes-release/release/v1.8.3/bin/linux/amd64/kubectl
        mode: 755
    script:
      image: docker.io/debian:9.2
      command: [bash]
      source: |
        which jq
        SECONDS=0
        LIMIT=300
        while (( SECONDS < LIMIT )); do
          IP=$(kubectl get services kibana --namespace kube-system -o json | jq ".status.loadBalancer.ingress[0].ip")
          if [ "${IP}" != "null" ]; then
            temp="${IP%\"}"
            temp="${temp#\"}"
            echo "${temp}"
            exit 0
          fi
          sleep 5
        done
        exit 1

  - name: kibana-svc-check
    inputs:
      parameters:
      - name: kibana-ip
    script:
      image: docker.io/debian:9.2
      command: [bash]
      source: |
        URL="http://{{inputs.parameters.kibana-ip}}:5601/"
        SECONDS=0
        LIMIT=120
        while (( SECONDS < LIMIT )); do
          status=$(curl -s --head -w %{http_code} "${URL}" -o /dev/null)
          if [ "${status}" == "200" ]; then
            exit 0
          fi
          sleep 3
        done
        exit 1

**Comment by gaganapplatix** [comment]
The above is the yaml I submitted that caused the crash

**Comment by jessesuen** [comment]
The third step in the YAML `kibana-running` is referencing `steps.generate.outputs.result` but there is no step named `generate`. So the YAML itself has problems. However, the linter should be improved to detect this so will fix the validation.

```
apiVersion: argoproj.io/v1
kind: Workflow
metadata:
  generateName: logging-workflow-
spec:
  entrypoint: sock-shop-logging

  templates:
  - name: sock-shop-logging
    steps:
    - - name: deploy
        template: logging-deploy
    - - name: get-kibana-ip
        template: kibana-svc-ip
    - - name: kibana-running
        template: kbiana-svc-check
        arguments:
          parameters:
          - name: kibana-ip
            value: "{{steps.generate.outputs.result}}"
```

**Comment by jessesuen** [comment]
Actually, it appears that the linter will indeed catch this error. Which means this was likely submitted using `kubectl create` which performs no validation. I plan on adding controller side validation before accepting a workflow.
```
$ argo lint issue486.yaml
[ERR_BAD_REQUEST] issue486.yaml: template 'sock-shop-logging' steps[2].kibana-running failed to resolve {{steps.generate.outputs.result}}
```

**Comment by jessesuen** [comment]
Commit bfa62af adds controller side YAML validation and will fail the workflow immediately.
