### ISSUE TITLE
Workflow resource view

### ISSUE THREAD

**Issue by alexec** [argoproj/argo#4873]
# Summary

Some workflows create resources. It might be nice to have a view similar to Argo CD to view the workflow's resources.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by simster7** [comment]
Great idea!

**Comment by alexec** [comment]
This is what I did in my Whitespace day on Wednesday. I seemed like a neat idea - but once implemented I did not think it would be useful.

**Comment by agilgur5** [comment]
This seems to have been re-opened in / superseded by #10822.
See also #6922 for Workflows of Workflows specifically
