### ISSUE TITLE
Customize logging for ResourceOp

### ISSUE THREAD

**Issue by duongnt** [argoproj/argo#4878]
# Summary

A pattern we're using (we guess it's a common pattern) to support launching Spark clusters through Argo is to use ResourceOp to create a SparkApplication CRD, which is then handled by the spark operator which spawns driver and executor pods.

One issue we're running into is the logs from the ResourceOp are not very readable (essentially it logs the resource yaml, and the status). Our users need to get the driver pod name, and then retrieve the logs themselves.

It would be nice if the ResourceOp can forward the logs from the driver pod as well, or at least we can customize it to provide a link to the correct logs. 

# Use Cases

To support launching Spark/Flink clusters through ResourceOp.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Are your logs in Splunk? Have you considered setting up a UI link for them?

https://argoproj.github.io/argo/links/
