### ISSUE TITLE
[Firefox] Tabs doesn't work

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo#49]
Firefox - Open any screen with tabs and try to change tab. Javascript exception happens:

![29070779-ff09cec8-7c40-11e7-8f6c-035203cffdfd](https://user-images.githubusercontent.com/426437/29753674-97faad0c-8b2b-11e7-9a40-498e1d0eb0a3.png)

**Comment by alexmt** [comment]
@roofi07 as I remember you were working on it. Can you share your changes please?

**Comment by wokeGit** [comment]
@alexmt The changes are available on the ui-lib (https://github.com/argoproj/ui-lib/commit/123ec71f0d7eac5f100fc0a057b855410ff20a25)
We need to update Gui to latest version of ui-lib

**Comment by alexmt** [comment]
Done
