### ISSUE TITLE
Installation error on existing kubernetes cluster API Not reachable

### ISSUE THREAD

**Issue by vaibhavjain882** [argoproj/argo#490]
I tried installing argo on my existing Kubernetes cluster with command but installation failed:

argocluster install-argo-only --cloud-provider aws --cluster-name ops-k8s --cloud-profile default --cloud-region ap-south-1 --cluster-bucket argo-test-bucket --kubeconfig kubeconfig

[root@mastercontroller-k8s-v1-16722 vaibhav2.jain]# kubectl get namespaces
NAME          STATUS    AGE
axsys         Active    1h
axuser        Active    1h
default       Active    10d
kube-public   Active    10d
kube-system   Active    10d

[root@mastercontroller-k8s-v1-16722 vaibhav2.jain]# kubectl get pods --namespace axuser
No resources found.

[root@mastercontroller-k8s-v1-16722 vaibhav2.jain]# kubectl get pods --namespace axsys
NAME                                                 READY     STATUS             RESTARTS   AGE
applet-2sszq                                         1/1       Running            0          1h
applet-mh30h                                         1/1       Running            0          1h
applet-s4cz0                                         1/1       Running            0          1h
axamm-deployment-2278361794-klnv1                    1/1       Running            0          1h
axartifactmanager-deployment-980136800-6qgxg         1/1       Running            0          1h
axdb-0                                               1/1       Running            0          1h
axdb-1                                               1/1       Running            0          1h
axdb-2                                               1/1       Running            1          1h
axmon-deployment-3868867852-m4917                    2/2       Running            0          1h
axops-deployment-2664451870-ptthg                    2/2       Running            0          1h
axscheduler-deployment-1687455719-7nbpc              1/1       Running            0          1h
axstats-deployment-1997717291-b8j4h                  2/2       Running            0          1h
axworkflowadc-deployment-2042875441-qhrzt            0/1       CrashLoopBackOff   21         1h
default-http-backend-1695166865-hkwgm                1/1       Running            0          1h
fixturemanager-deployment-1731100267-wdqj9           1/1       Running            0          1h
gateway-deployment-3712948279-ql50p                  1/1       Running            8          1h
ingress-controller-deployment-3282936498-8l28g       1/1       Running            0          1h
ingress-controller-int-deployment-4225476020-tqmvb   1/1       Running            0          1h
kafka-zk-1-1346873852-tjfv9                          2/2       Running            0          1h
kafka-zk-2-1273604618-wv650                          2/2       Running            0          1h
kafka-zk-3-1200335384-zhgb0                          2/2       Running            0          1h
redis-deployment-2992430959-1ddng                    1/1       Running            0          1h

One pod is failing here "**axworkflowadc-deployment**"

When I describe the pod:

[root@mastercontroller-k8s-v1-16722 vaibhav2.jain]# kubectl describe pod axworkflowadc-deployment-2042875441-qhrzt --namespace axsys
Name:		axworkflowadc-deployment-2042875441-qhrzt
Namespace:	axsys
Node:		ip-172-26-168-173.ap-south-1.compute.internal/172.26.168.173
Start Time:	Wed, 22 Nov 2017 15:20:21 +0530
Labels:		app=axworkflowadc-deployment
		pod-template-hash=2042875441
		role=axcritical
		tier=platform
Annotations:	kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"axsys","name":"axworkflowadc-deployment-2042875441","uid":"8d3639b8-cf6a-11e7-a9d...
Status:		Running
IP:		10.200.220.4
Controllers:	ReplicaSet/axworkflowadc-deployment-2042875441
Init Containers:
  pre:
    Container ID:	docker://f05b6a728780c205a673803d9e865b2316e3286057e1b44f462ca57c00d8c863
    Image:		docker.io/argoproj/kube-init:1.1.0
    Image ID:		docker-pullable://argoproj/kube-init@sha256:661f47d994b8720f53ce03ce74fd4dfc18fce9a0c17c79b2e2ef8fe8c588314d
    Port:		
    Command:
      timeout
      1200
      sh
      -c
      wait_http http://axdb:8083/v1/axdb/status
    State:		Terminated
      Reason:		Completed
      Exit Code:	0
      Started:		Mon, 01 Jan 0001 00:00:00 +0000
      Finished:		Wed, 22 Nov 2017 15:20:30 +0530
    Ready:		True
    Restart Count:	0
    Environment:	<none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-fxg0r (ro)
Containers:
  axworkflowadc:
    Container ID:	docker://5fbb194a97b201110b855358d4b7197ef7bd2a4e5e3eb82e074d64aeb27ba44e
    Image:		docker.io/argoproj/workflow:1.1.0
    Image ID:		docker-pullable://argoproj/workflow@sha256:906920232d00162ed7a07ece9f02bf601b125af331db0894480aedcf15b4e461
    Port:		8911/TCP
    Command:
      /ax/src/ax/devops/workflow/adc
      --image-registry
      docker.io
      --image-namespace
      argoproj
      --image-version
      1.1.0
    State:		Waiting
      Reason:		CrashLoopBackOff
    Last State:		Terminated
      Reason:		Error
      Exit Code:	1
      Started:		Mon, 01 Jan 0001 00:00:00 +0000
      Finished:		Wed, 22 Nov 2017 16:47:42 +0530
    Ready:		False
    Restart Count:	21
    Limits:
      cpu:	200m
      memory:	200Mi
    Requests:
      cpu:	75m
      memory:	100Mi
    Environment:
      ARGO_DATA_BUCKET_NAME:	paytmmall-argo
      AX_NODE_NAME:		 (v1:spec.nodeName)
      AX_POD_NAME:		axworkflowadc-deployment-2042875441-qhrzt (v1:metadata.name)
      AX_POD_NAMESPACE:		axsys (v1:metadata.namespace)
      AX_POD_IP:		 (v1:status.podIP)
      DISK_MULT:		1
      AX_TARGET_CLOUD:		aws
      AX_CLUSTER_NAME_ID:	ops-k8s-ffd09aea-cf69-11e7-bde5-0a98059d0a1e
      AX_CUSTOMER_ID:		user-customer-id
      AX_AWS_REGION:		ap-south-1
      CPU_MULT:			1
      MEM_MULT:			1
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-fxg0r (ro)
Conditions:
  Type		Status
  Initialized 	True 
  Ready 	False 
  PodScheduled 	True 
Volumes:
  default-token-fxg0r:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-fxg0r
    Optional:	false
QoS Class:	Burstable
Node-Selectors:	<none>
Tolerations:	<none>
Events:
  FirstSeen	LastSeen	Count	From							SubObjectPath			Type		Reason		Message
  ---------	--------	-----	----							-------------			--------	------		-------
  1h		2m		21	kubelet, ip-172-26-168-173.ap-south-1.compute.internal	spec.containers{axworkflowadc}	Normal		Pulled		Container image "docker.io/argoproj/workflow:1.1.0" already present on machine
  1h		2m		14	kubelet, ip-172-26-168-173.ap-south-1.compute.internal	spec.containers{axworkflowadc}	Normal		Created		(events with common reason combined)
  1h		2m		14	kubelet, ip-172-26-168-173.ap-south-1.compute.internal	spec.containers{axworkflowadc}	Normal		Started		(events with common reason combined)
  1h		5s		385	kubelet, ip-172-26-168-173.ap-south-1.compute.internal	spec.containers{axworkflowadc}	Warning		BackOff		Back-off restarting failed container
  1h		5s		359	kubelet, ip-172-26-168-173.ap-south-1.compute.internal					Warning		FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "axworkflowadc" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=axworkflowadc pod=axworkflowadc-deployment-2042875441-qhrzt_axsys(8d37b2de-cf6a-11e7-a9dd-0a8dcc6a57be)"

Then i logged in to the node on which this pod is scheduled and tried Debugging:

[root@workernode-k8s-v1-168173 vaibhav2.jain]# docker ps -a | grep -i axworkflowadc5fbb194a97b2        argoproj/workflow                          "/ax/src/ax/devops..."   4 minutes ago       Exited (1) 4 minutes ago                             k8s_axworkflowadc_axworkflowadc-deployment-2042875441-qhrzt_axsys_8d37b2de-cf6a-11e7-a9dd-0a8dcc6a57be_21
f05b6a728780        argoproj/kube-init                         "timeout 1200 sh -..."   2 hours ago         Exited (0) 2 hours ago                               k8s_pre_axworkflowadc-deployment-2042875441-qhrzt_axsys_8d37b2de-cf6a-11e7-a9dd-0a8dcc6a57be_0
4a573f78ba46        gcr.io/google_containers/pause-amd64:3.0   "/pause"                 2 hours ago         Up 2 hours                                           k8s_POD_axworkflowadc-deployment-2042875441-qhrzt_axsys_8d37b2de-cf6a-11e7-a9dd-0a8dcc6a57be_0

When I check the logs for the exited containers:
**1. argoproj/kube-init**
[root@workernode-k8s-v1-168173 vaibhav2.jain]# docker logs f05b6a728780
Wed Nov 22 09:50:21 UTC 2017
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
[{"status":"OK"}]
100    18  100    18    0     0      2      0  0:00:09  0:00:08  0:00:01     4
http://axdb:8083/v1/axdb/status is OK
All URLs are OK

**2. argoproj/workflow**  
[root@workernode-k8s-v1-168173 vaibhav2.jain]# docker logs fd68bed3aeb2
2017-11-22 11:22:53,500 INFO ax.devops.workflow.adc_main 198 MainThread: [adc]: starting...
2017-11-22 11:22:53,501 DEBUG ax.devops.axrequests 80 MainThread: GET http://axdb.axsys:8083/v1/axdb/version
2017-11-22 11:22:53,694 DEBUG ax.devops.axrequests 86 MainThread: Response status: 200 (GET http://axdb.axsys:8083/v1/axdb/version)
2017-11-22 11:22:53,694 INFO ax.devops.workflow.adc_main 199 MainThread: [adc]: AXDB version: v1
2017-11-22 11:22:53,699 INFO ax.devops.redis.redis_client 58 MainThread: Successfully connected to Redis server
2017-11-22 11:22:53,700 INFO ax.devops.workflow.adc_main 201 MainThread: [adc]: redis is available
2017-11-22 11:22:53,700 DEBUG ax.devops.axsys.axsys_client 158 MainThread: AXSYSClient for cluster_config with metadata None
2017-11-22 11:22:53,700 DEBUG ax.devops.axrequests 80 MainThread: GET http://axmon.axsys:8901/v1/axmon/cluster/nodes
2017-11-22 11:22:59,893 DEBUG ax.devops.axrequests 86 MainThread: Response status: 400 (GET http://axmon.axsys:8901/v1/axmon/cluster/nodes)
2017-11-22 11:23:00,486 ERROR ax.devops.axrequests 94 MainThread: Request failed (status: 400, reason: {
  "backtrace": "Traceback (most recent call last):\n  File \"/usr/lib/python2.7/site-packages/flask/app.py\", line 1475, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/usr/lib/python2.7/site-packages/flask/app.py\", line 1461, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \"/ax/python/ax/platform/rest.py\", line 190, in cluster_node_config\n    return jsonify(AXClusterConfig().get_node_config())\n  File \"/ax/python/ax/platform/cluster_config/cluster_config.py\", line 145, in get_node_config\n    self._load_config()\n  File \"/ax/python/ax/platform/cluster_config/cluster_config.py\", line 39, in _load_config\n    data = self._bucket.get_object(self._cluster_config_key)\n  File \"/ax/python/ax/cloud/aws/aws_s3.py\", line 365, in get_object\n    if not self.exists():\n  File \"/ax/python/ax/cloud/aws/aws_s3.py\", line 285, in exists\n    return self._exists()\n  File \"/usr/lib/python2.7/site-packages/retrying.py\", line 49, in wrapped_f\n    return Retrying(*dargs, **dkw).call(f, *args, **kw)\n  File \"/usr/lib/python2.7/site-packages/retrying.py\", line 212, in call\n    raise attempt.get()\n  File \"/usr/lib/python2.7/site-packages/retrying.py\", line 247, in get\n    six.reraise(self.value[0], self.value[1], self.value[2])\n  File \"/usr/lib/python2.7/site-packages/retrying.py\", line 200, in call\n    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)\n  File \"/ax/python/ax/cloud/aws/aws_s3.py\", line 565, in _exists\n    raise ce\nClientError: An error occurred (403) when calling the HeadBucket operation: Forbidden\n", 
  "message": "An error occurred (403) when calling the HeadBucket operation: Forbidden"
})
Traceback (most recent call last):
  File "/ax/src/ax/devops/workflow/adc", line 11, in <module>
    main()
  File "/ax/src/ax/devops/workflow/adc_entry.py", line 39, in main
    ADC().set_param(wfe_registry=args.image_registry, wfe_namespace=args.image_namespace, wfe_version=args.image_version)
  File "/ax/src/ax/util/singleton.py", line 15, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
  File "/ax/src/ax/devops/workflow/adc_main.py", line 72, in __init__
    cluster_config = axsys_client.get_cluster_config()
  File "/ax/src/ax/devops/axsys/axsys_client.py", line 318, in get_cluster_config
    response = self._run_service(action=CLUSTER_CONFIG, metadata=None, retry_on_500=True)
  File "/ax/src/ax/devops/axsys/axsys_client.py", line 210, in _run_service
    response = _run()
  File "/ax/src/ax/devops/axsys/axsys_client.py", line 188, in _run
    resp = self.axmon_client.get(path, headers=default_headers, raise_exception=True)
  File "/ax/src/ax/devops/axrequests/axrequests.py", line 122, in get
    return self._run_requests(REQUESTS_GET, path, params=params, **kwargs)
  File "/ax/src/ax/devops/axrequests/axrequests.py", line 96, in _run_requests
    response.raise_for_status()
  File "/usr/local/lib/python3.4/dist-packages/requests/models.py", line 844, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: BAD REQUEST for url: http://axmon.axsys:8901/v1/axmon/cluster/nodes

**Here is the actual problem but not sure what was that**

My Services looks like:

[root@mastercontroller-k8s-v1-16722 vaibhav2.jain]# kubectl get svc --namespace axsys
NAME                   CLUSTER-IP    EXTERNAL-IP        PORT(S)                               AGE
applatix               10.32.0.45    <none>             80/TCP                                1h
axamm                  10.32.0.133   <none>             8966/TCP                              1h
axartifactmanager      10.32.0.7     <none>             9892/TCP                              1h
axdb                   10.32.0.115   <none>             8083/TCP                              1h
axmon                  10.32.0.202   <none>             8901/TCP                              1h
axops                  10.32.0.104   a0576c5aecf6a...   80:30683/TCP,443:31763/TCP            1h
axops-internal         10.32.0.129   <none>             8085/TCP                              1h
axscheduler            10.32.0.74    <none>             9890/TCP                              1h
axworkflowadc          10.32.0.43    <none>             8911/TCP                              1h
default-http-backend   10.32.0.194   <none>             80/TCP                                1h
fixturemanager         10.32.0.77    <none>             8912/TCP                              1h
gateway                10.32.0.210   <none>             8889/TCP                              1h
kafka-zk               10.32.0.57    <none>             9092/TCP,2181/TCP                     1h
kafka-zk-1             10.32.0.80    <none>             9092/TCP,2181/TCP,2888/TCP,3888/TCP   1h
kafka-zk-2             10.32.0.155   <none>             9092/TCP,2181/TCP,2888/TCP,3888/TCP   1h
kafka-zk-3             10.32.0.132   <none>             9092/TCP,2181/TCP,2888/TCP,3888/TCP   1h
redis                  10.32.0.56    <none>             6379/TCP                              1h

**Then for debugging**
[root@mastercontroller-k8s-v1-16722 vaibhav2.jain]# kubectl describe pod axmon-deployment-3868867852-m4917 --namespace axsys
Name:		axmon-deployment-3868867852-m4917
Namespace:	axsys
Node:		ip-172-26-168-173.ap-south-1.compute.internal/172.26.168.173
Start Time:	Wed, 22 Nov 2017 15:19:02 +0530
Labels:		app=axmon-deployment
		pod-template-hash=3868867852
		role=axcritical
		tier=platform
Annotations:	kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"axsys","name":"axmon-deployment-3868867852","uid":"5e354ac8-cf6a-11e7-a9dd-0a8dcc...
		prometheus.io/port=8902
		prometheus.io/scrape=true
Status:		Running
IP:		10.200.220.3
Controllers:	ReplicaSet/axmon-deployment-3868867852
Init Containers:
  pre:
    Container ID:	docker://7f4ad1a8dd529d6fe71866fd982e531dd3ffea3eeb774d5b9ce5841a97988a59
    Image:		docker.io/argoproj/kube-init:1.1.0
    Image ID:		docker-pullable://argoproj/kube-init@sha256:661f47d994b8720f53ce03ce74fd4dfc18fce9a0c17c79b2e2ef8fe8c588314d
    Port:		
    Command:
      timeout
      1200
      sh
      -c
      wait_http http://axdb:8083/v1/axdb/status
    State:		Terminated
      Reason:		Completed
      Exit Code:	0
      Started:		Mon, 01 Jan 0001 00:00:00 +0000
      Finished:		Wed, 22 Nov 2017 15:19:45 +0530
    Ready:		True
    Restart Count:	0
    Environment:	<none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-fxg0r (ro)
Containers:
  axmon:
    Container ID:	docker://18e0c5971e468010392d7279020475020dc53e46758b74428f4bdb0641285064
    Image:		docker.io/argoproj/axmon:1.1.0
    Image ID:		docker-pullable://argoproj/axmon@sha256:5f912d4b0ec4dc189d23f54be4c2d8dde328df916687031ba76f5f26a6f1e818
    Port:		8901/TCP
    Command:
      /ax/bin/axmon
    State:		Running
      Started:		Wed, 22 Nov 2017 15:20:10 +0530
    Ready:		True
    Restart Count:	0
    Limits:
      memory:	600Mi
    Requests:
      cpu:	50m
      memory:	150Mi
    Liveness:	http-get http://:8901/v1/axmon/ping delay=120s timeout=1s period=60s #success=1 #failure=3
    Environment:
      ARGO_DATA_BUCKET_NAME:		paytmmall-argo
      ARGO_DIST_REGISTRY:		docker.io
      ARGO_DIST_REGISTRY_SECRETS:	
      AX_NAMESPACE:			argoproj
      AX_VERSION:			1.1.0
      AX_CLUSTER_META_URL_V1:		https://s3-ap-south-1.amazonaws.com/paytmmall-argo/ops-k8s/ffd09aea-cf69-11e7-bde5-0a98059d0a1e/metadata/v1/metadata.yaml
      ARGO_LOG_BUCKET_NAME:		paytmmall-argo
      AX_NODE_NAME:			 (v1:spec.nodeName)
      AX_POD_NAME:			axmon-deployment-3868867852-m4917 (v1:metadata.name)
      AX_POD_NAMESPACE:			axsys (v1:metadata.namespace)
      AX_POD_IP:			 (v1:status.podIP)
      DISK_MULT:			1
      AX_TARGET_CLOUD:			aws
      AX_CLUSTER_NAME_ID:		ops-k8s-ffd09aea-cf69-11e7-bde5-0a98059d0a1e
      AX_CUSTOMER_ID:			user-customer-id
      AX_AWS_REGION:			ap-south-1
      CPU_MULT:				1
      MEM_MULT:				1
    Mounts:
      /var/run from docker-socket-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-fxg0r (ro)
  kubectl-proxy:
    Container ID:	docker://b5cea25e696adf2287b69f016917090a4b22fb85da0fd440ae775ab8c858850a
    Image:		argoproj/kubectl:v1.6.7
    Image ID:		docker-pullable://argoproj/kubectl@sha256:0db59ee14f27a58a48854e268d1fc292f63bdf479d0aaef0e5b1d63311a5e820
    Port:		
    Args:
      proxy
      -p
      8001
    State:		Running
      Started:		Wed, 22 Nov 2017 15:20:14 +0530
    Ready:		True
    Restart Count:	0
    Limits:
      memory:	80Mi
    Requests:
      cpu:	25m
      memory:	20Mi
    Environment:
      AX_NODE_NAME:		 (v1:spec.nodeName)
      AX_POD_NAME:		axmon-deployment-3868867852-m4917 (v1:metadata.name)
      AX_POD_NAMESPACE:		axsys (v1:metadata.namespace)
      AX_POD_IP:		 (v1:status.podIP)
      DISK_MULT:		1
      AX_TARGET_CLOUD:		aws
      AX_CLUSTER_NAME_ID:	ops-k8s-ffd09aea-cf69-11e7-bde5-0a98059d0a1e
      AX_CUSTOMER_ID:		user-customer-id
      AX_AWS_REGION:		ap-south-1
      CPU_MULT:			1
      MEM_MULT:			1
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-fxg0r (ro)
Conditions:
  Type		Status
  Initialized 	True 
  Ready 	True 
  PodScheduled 	True 
Volumes:
  docker-socket-dir:
    Type:	HostPath (bare host directory volume)
    Path:	/var/run/
  default-token-fxg0r:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-fxg0r
    Optional:	false
QoS Class:	Burstable
Node-Selectors:	<none>
Tolerations:	<none>
Events:		<none>
I describe the axmon pod and attach a bash to the axmon container and try to cULR on the API:
[root@workernode-k8s-v1-168173 vaibhav2.jain]# docker exec -it 18e0c5971e468010392d7279020475020dc53e46758b74428f4bdb0641285064 /bin/bash
bash-4.3# ls
ax     bin    dev    etc    home   lib    media  mnt    proc   root   run    sbin   srv    sys    tmp    usr    var
bash-4.3# vim /etc/host
bash-4.3# vim /etc/hosts
bash-4.3# curl localhost:8091/v1/axmon/ping
curl: (7) Failed to connect to localhost port 8091: Connection refused
bash-4.3# curl http://:8901/v1/axmon/ping
curl: (6) Couldn't resolve host ''
bash-4.3# curl http://localhost:8901/v1/axmon/ping
{
  "status": "OK"
bash-4.3# curl http://localhost:8901/v1/axmon/cluster/nodes
{
  "backtrace": "Traceback (most recent call last):\n  File \"/usr/lib/python2.7/site-packages/flask/app.py\", line 1475, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/usr/lib/python2.7/site-packages/flask/app.py\", line 1461, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \"/ax/python/ax/platform/rest.py\", line 190, in cluster_node_config\n    return jsonify(AXClusterConfig().get_node_config())\n  File \"/ax/python/ax/platform/cluster_config/cluster_config.py\", line 145, in get_node_config\n    self._load_config()\n  File \"/ax/python/ax/platform/cluster_config/cluster_config.py\", line 39, in _load_config\n    data = self._bucket.get_object(self._cluster_config_key)\n  File \"/ax/python/ax/cloud/aws/aws_s3.py\", line 365, in get_object\n    if not self.exists():\n  File \"/ax/python/ax/cloud/aws/aws_s3.py\", line 285, in exists\n    return self._exists()\n  File \"/usr/lib/python2.7/site-packages/retrying.py\", line 49, in wrapped_f\n    return Retrying(*dargs, **dkw).call(f, *args, **kw)\n  File \"/usr/lib/python2.7/site-packages/retrying.py\", line 212, in call\n    raise attempt.get()\n  File \"/usr/lib/python2.7/site-packages/retrying.py\", line 247, in get\n    six.reraise(self.value[0], self.value[1], self.value[2])\n  File \"/usr/lib/python2.7/site-packages/retrying.py\", line 200, in call\n    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)\n  File \"/ax/python/ax/cloud/aws/aws_s3.py\", line 565, in _exists\n    raise ce\nClientError: An error occurred (403) when calling the HeadBucket operation: Forbidden\n", 
  "message": "An error occurred (403) when calling the HeadBucket operation: Forbidden"

Ping is health(Return 200) but http://localhost:8901/v1/axmon/cluster/nodes

returns forbidden not sure what is the reason and on the same API my workflowengine is trying to hit.

**Need help on this**

**Comment by vaibhavjain882** [comment]
I am using Weave as my networking on my K8s cluster.

**Comment by vaibhavjain882** [comment]
I more thing if anyone else face this: When I install argo on existing cluster it attach multiple volumes to my worker node instance(/dev/xvdf, /dev/xvdbl, /dev/xvdbp, /dev/xvdbt, /dev/xvdbu) of multiple sizes which is totally unethical because this hampers my Terraform state and my terrafrom no more able to handel the nodes. Is there a way to control this?

**Comment by bobhenkel** [comment]
@vaibhavjain882  Are those created via Kubernetes Persistence Volumes?

**Comment by vaibhavjain882** [comment]
@bobhenkel Those were AWS EBS SSD with the tag "ops-k8s-dynamic-pvc-043acb89-cf6a-11e7-a9dd-0a8dcc6a57be"  and are attached to my K8s worker nodes. Size of volumes varies from 1 GB to 30 GB

**Comment by vaibhavjain882** [comment]
As soon as I did "argocluster uninstall-argo-only --kubeconfig /tmp/ax_kube/kubeconfig" boom they all were  gone.

**Comment by vaibhavjain882** [comment]
Fixed all the issues now(by running clusterinstallargo command multiple times). The only concern I have now is the Disk mounting issues. How can i restrict that?

**Comment by shrinandj** [comment]
Hey Vaibhav,

Looks like you had at least 2 problems:
* S3 Bucket ACLS because of which the Head Bucket was failing with a Forbidden error.
* Varying EBS volume sizes.

If I understand it right, you were able to fix the Bucket acls issue. Now, the only question remaining is why Argo uses EBS volume of varying sizes, right?

Argo uses several microservices for the functionality to run workflows. Some of these services use persistent storage. The sizes of the EBS volumes are decided depending on how much data these services are going to store. These are Kubernetes' PVCs.

Can you share some details about what disk mounting issues you're seeing?

**Comment by jessesuen** [comment]
Closing out v1 issues.
