### ISSUE TITLE
Correct misconceptions about Argo Workflows+ Python

### ISSUE THREAD

**Issue by alexec** [argoproj/argo#4923]
# Summary

Example: https://www.datarevenue.com/en-blog/airflow-vs-luigi-vs-argo-vs-mlflow-vs-kubeflow

We should document or blog about this with help from @terrytangyuan .

See https://github.com/kubeflow/pipelines/issues/3253 too.

# Use Cases

When would you use this?

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
WIP: https://docs.google.com/document/d/1gtQ-Vd0BkO_wep3QtBtpzzYmdpOYsTtt6yisnSfxDW0/edit#

**Comment by alexec** [comment]
@liorshk  @terrytangyuan would you like to feedback on the doc above?

**Comment by alexec** [comment]
@binarycrayo would you be able to help with this blog post? I'd like to include an example of coin flip using https://github.com/argoproj-labs/argo-client-python/issues.

**Comment by terrytangyuan** [comment]
Yes, I'll comment on the doc directly.
