### ISSUE TITLE
Add selected ServiceAccount into user-info.tsx when enable RBAC

### ISSUE THREAD

**Issue by krrrr38** [argoproj/argo#4936]
# Summary

Please add selected ServiceAccount into `user-info.tsx` to check which SA is used on WebUI?

https://github.com/argoproj/argo/blob/9d4edaef47c2674861d5352e2ae6ecb10bcbb8f1/server/auth/gatekeeper.go#L232

https://github.com/argoproj/argo/blob/9d4edaef47c2674861d5352e2ae6ecb10bcbb8f1/ui/src/app/userinfo/components/user-info.tsx#L38-L46

# Use Cases

When enable RBAC, sometimes user groups match multiple ServiceAccount. At that time ServiceAccount is selected by `workflows.argoproj.io/rbac-rule-precedence`. If selected SA is shown on Web UI, it helps us to investigate RBAC features.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Great idea! Would you like to raise a PR to add this feature?

**Comment by krrrr38** [comment]
Thanks. Unfortunately I changed my pc to M1 mac, which doesn't work docker-for-mac preview. Anyone can try this feature.
