### ISSUE TITLE
SSO with RBAC fails when using email addresses (works on latest)

### ISSUE THREAD

**Issue by covidium** [argoproj/argo#4942]
## Summary 

What happened/what you expected to happen?
- After enabling SSO the next step was to enable Google Auth and with it authorization based on the email address. This feature already had a PR #4644 already merged into master. The issue is that the feature works properly using the latest tag, but doesn't work with the latest release.
- Any plans to include the PR #4644 in the next release?

## Diagnostics

What Kubernetes provider are you using? 
- AWS EKS 1.16

What version of Argo Workflows are you running? 
- 2.12.5

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
I’ve had at least 3 requests to back port this feature to 2.12.

Hopefully this will happen, maybe even this week @simster7

**Comment by simster7** [comment]
This is out on https://github.com/argoproj/argo/releases/tag/v2.12.6
