### ISSUE TITLE
Cross Origin Requests

### ISSUE THREAD

**Issue by joyciep** [argoproj/argo#4984]
# Summary

Allow CORS by adding a way to set the "Access-Control-Allow-Origin" headers

What change needs making?

Something like 

```
argo-server --access-control-allow-origin="http://localhost:8080"
```

# Use Cases

When would you use this?

For making requests from my web application to Argo under the origin of `http://localhost:8080` for example.
I can issue a PR for this since this is just setting an HTTP header.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
would you like to submit a PR to add this?

**Comment by alexec** [comment]
actually, this might be in v3.0?

**Comment by joyciep** [comment]
> would you like to submit a PR to add this?

Submitted a PR for this #4990. Thanks!
