### ISSUE TITLE
CI examples don't work

### ISSUE THREAD

**Issue by sestegra** [argoproj/argo#5038]
## Summary 

When submitting `examples/ci.yaml` or `examples/ci-output-artifact.yaml`, the workflow fails on `build` step.

## Diagnostics

What Kubernetes provider are you using? 
Kind

What version of Argo Workflows are you running? 
v2.12.7

Following workflows are impacted
`examples/ci.yaml`
`examples/ci-output-artifact.yaml`

See following logs from `build` step
```
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
hello.go:22:2: cannot find package "golang.org/x/example/stringutil" in any of:
        /usr/local/go/src/golang.org/x/example/stringutil (from $GOROOT)
        /go/src/golang.org/x/example/stringutil (from $GOPATH)
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by simster7** [comment]
Closed by https://github.com/argoproj/argo/pull/5039
