### ISSUE TITLE
global/session/workflow level parameter and artifacts

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo#516]
It can be irritating to pass parameters/artifacts around templates as arguments. One way to make this easier in our YAMLs is to provide the notion of global/session/workflow level parameters and artifacts. For example, one idea is that all top level parameters/artifacts at the `workflow.spec.arguments` level could be referred to via a special variable (e.g. `{{workflow.parameters.revision}}`). This would ease the burden of passing these around to templates who all want the same information.

**Comment by gaganapplatix** [comment]
This is merged with https://github.com/argoproj/argo/pull/571
