### ISSUE TITLE
Document RBAC requirements for workflow pods

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo#530]
Testing on GKE with legacy auth disabled. Although the controller installs and runs with correct service account, the pods which it schedules, are still using the default service account (in their respective namespace) and are unable to update the pod metadata of itself and add the outputs to the pod annotation.

```
time="2017-12-04T02:19:31Z" level=info msg="Capturing script output"
time="2017-12-04T02:19:31Z" level=fatal msg="Error capturing script output, pods \"pod-limits-dds8d-1859251742\" is forbidden: User \"system:serviceaccount:default:default\" cannot get pods in the namespace \"default\": Unknown user \"system:serviceaccount:default:default\"
github.com/argoproj/argo/errors.Wrap
	/root/go/src/github.com/argoproj/argo/errors/errors.go:86
github.com/argoproj/argo/errors.InternalWrapError
	/root/go/src/github.com/argoproj/argo/errors/errors.go:69
github.com/argoproj/argo/workflow/executor.(*WorkflowExecutor).GetMainContainerStatus
	/root/go/src/github.com/argoproj/argo/workflow/executor/executor.go:265
github.com/argoproj/argo/workflow/executor.(*WorkflowExecutor).GetMainContainerID
	/root/go/src/github.com/argoproj/argo/workflow/executor/executor.go:280
github.com/argoproj/argo/workflow/executor.(*WorkflowExecutor).CaptureScriptResult
	/root/go/src/github.com/argoproj/argo/workflow/executor/executor.go:306
github.com/argoproj/argo/cmd/argoexec/commands.waitContainer
	/root/go/src/github.com/argoproj/argo/cmd/argoexec/commands/wait.go:41
github.com/argoproj/argo/vendor/github.com/spf13/cobra.(*Command).execute
	/root/go/src/github.com/argoproj/argo/vendor/github.com/spf13/cobra/command.go:702
github.com/argoproj/argo/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/root/go/src/github.com/argoproj/argo/vendor/github.com/spf13/cobra/command.go:783
github.com/argoproj/argo/vendor/github.com/spf13/cobra.(*Command).Execute
	/root/go/src/github.com/argoproj/argo/vendor/github.com/spf13/cobra/command.go:736
main.main
	/root/go/src/github.com/argoproj/argo/cmd/argoexec/main.go:11
runtime.main
	/usr/local/go/src/runtime/proc.go:185
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:2337"
```

**Comment by jessesuen** [comment]
Docs now explain how to create a rolebinding for submitting workfows as

**Comment by discordianfish** [comment]
Just trying to get started with argo and while these notes are a good start, I don't think that giving the default user admin permissions is a good idea. Correct me if I'm wrong, but that means that all my pods get full access, right?

As I understand it, I can use `submit --as` to provide a different account, but I struggle creating one that has the right permissions. I've installed argo in a new `argo` namespace (with install --install-namespace`), then tried:

```
kubectl create sa argo
kubectl create rolebinding argo --clusterrole admin --serviceaccount default:argo
```

But when trying to submit a job in the default namespace, I get:
```
argo submit --as argo https://raw.githubusercontent.com/argoproj/argo/master/examples/coinflip.yaml 
2018/02/05 13:23:59 Workflow manifest https://raw.githubusercontent.com/argoproj/argo/master/examples/coinflip.yaml failed submission: workflows.argoproj.io is forbidden: User "argo" cannot create workflows.argoproj.io in the namespace "default"
```

Do I somehow need to explicitly give it permissions on the workflow CRDs?

**Comment by discordianfish** [comment]
Okay I figured this out: I needed to build from source and use the recently added `--serviceaccount` flag. Not sure what the difference is though. I'd suggest to improve the help strings for the flags too. I don't know what it means by 'impersonating'. Would also help to group the flags somehow to avoid confusion. E.g --user could become --kubeconfig.user or something like that.

In general though, I'd like to be able to run workflows in any namespace, so giving the default user in each namespace *some* permissions seems to be the way to go. But not the admin permissions. Are the required permissions documented somewhere? IMO there should be a role that can be bound to default, allowing only the necessary actions (annotating the pods AFAIK?)

**Comment by jessesuen** [comment]
> Correct me if I'm wrong, but that means that all my pods get full access, right?

That is correct, but this is an admin and not cluster-admin, so it will be limited to what is in that namespace. So if you are worried workflows accessing things that it shouldn't, you should run workflows in an isolated namespace.

> Not sure what the difference is though. I'd suggest to improve the help strings for the flags too. I don't know what it means by 'impersonating'

Actually these are all kubernetes flags that we inherit from the k8s CLI tooling so we don't have control over this

> Okay I figured this out: I needed to build from source and use the recently added --serviceaccount flag

Both v2.0.0-beta1 and v2.0.0-alpha3 have this feature so no need to rebuild from source.

>  Are the required permissions documented somewhere? IMO there should be a role that can be bound to default, allowing only the necessary actions (annotating the pods AFAIK?)

The bare minimum for normal workflows is that the executor sidecar needs to get/update/patch pods so that it can read metadata about itself, and annotate outputs.

That said, the privileges that the pod needs depends on what the workflow is doing. For example, if the workflow also needs to upload/download artifacts to S3, it should also be able to read secrets in the namespace. If the workflow needs to orchestrate (create/delete) other kubernetes resources, it will need create/delete permissions on those types of resources.

**Comment by discordianfish** [comment]
> That is correct, but this is an admin and not cluster-admin, so it will be limited to what is in that namespace. So if you are worried workflows accessing things that it shouldn't, you should run workflows in an isolated namespace.

Ah thanks for clarifying.

> Both v2.0.0-beta1 and v2.0.0-alpha3 have this feature so no need to rebuild from source.
Uhmm.. you're right, not sure how I missed that.

> The bare minimum for normal workflows is that the executor sidecar needs to get/update/patch pods so that it can read metadata about itself, and annotate outputs.

Is there a reason why the controller isn't doing these things instead? Except maybe the S3, it sounds to me (but I might miss something) like it's something the controller should do. That could ensure that it's only modifying the pods that belong to the workflow.

**Comment by nelsonfassis** [comment]
I'm still having issues with RBAC, granting the same access to my developers group I can only execute argo commands if using an admin account. Using a developer account, I have this problem:

argo submit --serviceaccount argo --namespace argo https://raw.githubusercontent.com/argoproj/argo/master/examples/artifact-passing.yaml

2018/02/08 15:47:05 Workflow manifest https://raw.githubusercontent.com/argoproj/argo/master/examples/artifact-passing.yaml failed submission: workflows.argoproj.io is forbidden: User "developers-staging" cannot create workflows.argoproj.io in the namespace "argo"

Couldn't find what kind of permissions I need to grant to my developers group. They can create/patch/update/get pods on the argo namespace. Tried a buch of different rules and still the same issue.
