### ISSUE TITLE
Improve date range picker

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo#54]
Date range picker should be improved according to attached mockups:

1. When date range picker is expanded user is seeing menu with several predefined items and 'Custom Date Range' menu item
2. If user click 'Custom Date Range' menu item when menu expand into calendar view with ability to select required date range.

![1](https://user-images.githubusercontent.com/426437/29753942-70337560-8b30-11e7-8476-25f5e7dea294.png)
![2](https://user-images.githubusercontent.com/426437/29753943-71d00fbe-8b30-11e7-88f2-de5986297a56.png)

**Comment by roofi07** [comment]
Done
