### ISSUE TITLE
Support notification events push delivery

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo#56]
Currently UI has to periodically pull user events using `v1/notification_center/events?recipient=` API. This should switch to push model to improve performance. Following changes are required:

- [ ] Implement `/v1/notification_center/events_stream` API which should implement SSE protocol. API should support recipient query parameter to apply filter by recipient. 
- [ ] Update UI to use `/v1/notification_center/events_stream` API instead of periodical pulling.

**Comment by jessesuen** [comment]
Closing v1 issues.
