### ISSUE TITLE
Feature Request Argo V2 Workflow Triggers/Dependencies on other Workflows

### ISSUE THREAD

**Issue by bobhenkel** [argoproj/argo#581]
Often time large systems have many workflows. And often you want to have downstream workflows kick off when an upstream workflow completes either success or failure depending on the user's needs.

For example three workflows A, B, and C(Each one in this case belongs to a different git repo):
A->B->C

- (Scenario 1) B has declared a dependency to A. If A completes to success or failure(user picks) B is triggered to started. C has declared a dependency to B. If B completes to success or failure(user picks) C is triggered to started.
- (Scenario 2)C has declared a dependency to B. If B completes to success or failure(user picks) C is triggered to started.
- (Scenario 3)C is kicked off. No other workflow are started because nothing has declared C an upstream workflow.

**Comment by jessesuen** [comment]
I think this use case can be addressed with the implementation of workflow finalizers (#495). Workflow finalizers are a list of templates that would be executed at the end of a workflow, regardless of the success/fail status of the core workflow. Finalizer containers will be provided understanding of the overall status of the workflow (e.g. success/failed), of which it can base decisions off of.

The way I see your use case being solved is:
1. core workflow fails (or passes)
2. finalizer step executes with some logic like:
```
if [ "$WORKFLOW_STATUS" = "Success" ]; then
  argo submit http://some-url.com/workflow-b.yaml
fi
```
Alternatively, it could use a git input artifact to load the repository of workflows and run `argo submit` against a file local in the container.

**Comment by afoninsky** [comment]
What if I want to redeploy all the services in case of internal library update? How will the pipeline look like?

**Comment by bobhenkel** [comment]
@jessesuen That sounds like that covers the functionality I was asking for.  

Being particular... the issue with this is the workflow that shouldn't even know about workflow B needs to have logic linking it to B. Ideally B should be fired off based on an event of A succeeding or failing.  Granted I'm being picky, just wanted to capture the thought.

**Comment by jessesuen** [comment]
Establishing relationships between workflows is something that I feel is out of the scope of the workflow spec definition. The fact that workflow B has a dependency on A, implies some higher level context that spans multiple workflow manifest files. The current design is such that workflows are independent of each other and adding understanding context in the manifest itself will make the logic much more complicated.

That said, if the requirement is that workflow A has no knowledge of workflow B, *and* should still somehow trigger a submission of workflow B upon completion, I think are other avenues to explore:

One approach (which would require more effort) is to use kuberentes watches to listen for workflow events (i.e. `kubectl get wf -w`).  The idea is to establish a watch on workflows (filtered by metadata identifying workflows of type A). When a completion event happens for workflow A on the watch, it would programmatically trigger a submit of workflow B. This would keep the workflows independent of each other, but still achieve the event-based triggering that you are looking for.

**Comment by jessesuen** [comment]
> What if I want to redeploy all the services in case of internal library update? How will services pipelines look like? In case then the library also in argo and I do not want to describe all services in library's pipeline.

@afoninsky can you elaborate on your use case a little more and how it relates to workflow relationships/dependencies? I would like to understand how establishing relationships between independent workflows could solve your problem.

**Comment by jessesuen** [comment]
@bobhenkel - I forgot to ask, is there a specific reason that you would like workflow A and B to be kept independent from each other as separate manifests, instead of making A and B just nested workflows in the same manifest?

https://github.com/argoproj/argo/blob/master/examples/nested-workflow.yaml

**Comment by jessesuen** [comment]
Nevermind, I forgot about your comment, "For example three workflows A, B, and C (Each one in this case belongs to a different git repo)". This would be a reason why you need to keep the workflows independent from each other.

**Comment by jessesuen** [comment]
Duplicating this to issue #495, which has been implemented and merged into master.
