### ISSUE TITLE
Create a ClusterIP  service for argo UI during install

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo#582]
It is not apparent to end users that a UI is available after installation. They also have to run a `kubectl` step manually to create a service object for the UI. Instead, this service should be created automatically for them with a ClusterIP.

**Comment by ricoms** [comment]
Following [quickstart documentation](https://argoproj.github.io/argo/quick-start/) it says "If you're using running Argo Workflows on a remote cluster (e.g. on EKS or GKE) then [follow these instructions](https://argoproj.github.io/argo/argo-server/#access-the-argo-workflows-ui)."

On those instructions it says "Update the argo-ui service to be of type LoadBalancer." `kubectl patch svc argo-ui -n argo -p '{"spec": {"type": "LoadBalancer"}}'` after running this command the response is `Error from server (NotFound): services "argo-ui" not found`.

This seems a dead-end for me. I also cannot find anything else in this subject searching with that error message. And that is how I found this issue, that seems a good spot to include this newbie swallower black hole. 0o'

**Comment by alexec** [comment]
You correct - these instructions are out of date - would you like to submit a PR?

**Comment by ricoms** [comment]
I would surely like to do that, :D as soon as I find the correct solution. I installed `https://github.com/argoproj/argo/blob/stable/manifests/install.yaml` and it still gives me the same error. Do you have any advice on what would be a nice solution for the documentation?
