### ISSUE TITLE
Create an example workflow which uses kubernetes secrets

### ISSUE THREAD

**Issue by bobhenkel** [argoproj/argo#592]
**Problem:**
When you go to the gui and click YAML you get to see the yaml, this is nice.  If that yaml has let's say a github token to clone a repo in it shows up in that yaml view, not nice.

**Idea/Solution:**
For parameters can that be annotated or marked private so that in the YAML view they show up as **** instead of plain open text?

**Comment by jessesuen** [comment]
Secret values are not expected to be stored directly into workflow manifests and we consider this a bad practice. Secrets are intended to be stored as normal kubernetes secrets, and *referenced* using secret selectors in the template's container spec. For example if you want to use a github token, you would do something like:
```
kubectl create secret generic my-github-token --from-file=./token
```
Then in the container spec, if you need access to it you could use normal kubernetes facilities like setting an environment variable from a secret, or volume mounting the secret as a file.

I will use this bug as an action item to create an example yaml which uses secrets in the container.

**Comment by jessesuen** [comment]
I created an example workflow which references a kubernetes secret at:

https://github.com/argoproj/argo/blob/master/examples/secrets.yaml

**Comment by bobhenkel** [comment]
@jessesuen that's awesome and ideal, thanks!  The example is highly appreciated.
