### ISSUE TITLE
Argo CLI features and improvements

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo#6]
This issue is for general improvements to argocli including:

- `argo app list` to display running apps
- `argo app show <appname>` to show details about an app
- `argo job logs <service_id>` to retrieve logs for container in a job

Also to improve the `argo job show --tree` view to be able to distinguish from parallel vs. sequential steps in a workflow.

**Comment by abhinavdas** [comment]
`argo scm add github`

**Comment by jessesuen** [comment]
Described improvements been added to versions 1.0.1 and 1.1.
