### ISSUE TITLE
Add option to run Argo workflows synchronously to completion

### ISSUE THREAD

**Issue by shrinandj** [argoproj/argo#603]
Hi,

I'm triggering Argo workflows from an external script. While submitting the argo workflows is easy, programmatically waiting for them to run to completion is not straightforward.

1. When the workflow is submitted, the returned output needs to be parsed to correctly get the exact name of the workflow that was created.
2. After that, the external script has to periodically poll the status of that workflow so that is runs to completion.

Instead, it'll be good if the "submit" command itself had an option (--sync?) that would only return when the workflow completed. Ideally, the return value should indicate whether the workflow succeeded or not (0 if succeeded, > 0 otherwise).

**Comment by jessesuen** [comment]
As discussed, let's add a `argo wait <workflow-name>` command to support this, as well as a `--wait` option to `argo submit`.  

Also, either in this bug or another, there is likely a need to do `argo submit -o json` to extract the generated worfklow name after submission.

**Comment by shrinandj** [comment]
Filed https://github.com/argoproj/argo/issues/604 for the output format.

**Comment by shrinandj** [comment]
Done with:
```
commit e5002b8286af2c1f7ec64953114e1d97c889ca37 (HEAD -> master, origin/master, origin/HEAD)
Author: Shri Javadekar <shrinand@applatix.com>
Date:   Tue Dec 19 16:16:20 2017 -0800

    Add '--wait' to argo submit.
```

Users can now use `argo submit wf.yaml --wait`.

**Comment by Ark-kun** [comment]
How can we follow the logs while the pipeline is running?

**Comment by jessesuen** [comment]
@Ark-kun something like this should work:
```
argo logs -f -w $(argo submit examples/hello-world.yaml -o name)
```

**Comment by Ark-kun** [comment]
Unfortunately, this does not work. See https://github.com/argoproj/argo/issues/989
