### ISSUE TITLE
Documentation Change

### ISSUE THREAD

**Issue by anshumanbh** [argoproj/argo#609]
Hello, 

The command to download argo v2.0 is `curl -sSL -o ./argo https://github.com/argoproj/argo/releases/download/v2.0.0-alpha2/argo-darwin-amd64` according to the documentation.

Now, the following instructions after that says `argo install`, but it should be `./argo install`

Thanks!

**Comment by mukulikak** [comment]
Updated it.

Thx.

**Comment by jessesuen** [comment]
Fixed in commit bb5ac7d
