### ISSUE TITLE
"net/http: TLS handshake timeout" during artifact save

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo#612]
The following error was encountered by a user multiple times during an artifact save:
```
time="2017-12-18T03:18:03Z" level=info msg="Saving from /argo/outputs/artifacts/sparksx-cambyses-alignment.tgz to s3 (endpoint: storage.googleapis.com, bucket: BUCKETNAME-REDACTED, key: hm-6zb47/hm-6zb47-734900164/sparksx-cambyses-alignment.tgz)"
time="2017-12-18T03:19:00Z" level=fatal msg="Error saving output artifacts, [ERR_INTERNAL] Get https://storage.googleapis.com/BUCKETNAME-REDACTED/?location=: net/http: TLS handshake timeout
github.com/argoproj/argo/errors.Wrap
	/root/go/src/github.com/argoproj/argo/errors/errors.go:86
github.com/argoproj/argo/errors.InternalWrapError
	/root/go/src/github.com/argoproj/argo/errors/errors.go:69
github.com/argoproj/argo/workflow/artifacts/s3.(*S3ArtifactDriver).Save
	/root/go/src/github.com/argoproj/argo/workflow/artifacts/s3/s3.go:53
github.com/argoproj/argo/workflow/executor.(*WorkflowExecutor).SaveArtifacts
	/root/go/src/github.com/argoproj/argo/workflow/executor/executor.go:174
github.com/argoproj/argo/cmd/argoexec/commands.saveArtifacts
	/root/go/src/github.com/argoproj/argo/cmd/argoexec/commands/artifacts.go:143
github.com/argoproj/argo/vendor/github.com/spf13/cobra.(*Command).execute
	/root/go/src/github.com/argoproj/argo/vendor/github.com/spf13/cobra/command.go:702
github.com/argoproj/argo/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/root/go/src/github.com/argoproj/argo/vendor/github.com/spf13/cobra/command.go:783
github.com/argoproj/argo/vendor/github.com/spf13/cobra.(*Command).Execute
	/root/go/src/github.com/argoproj/argo/vendor/github.com/spf13/cobra/command.go:736
main.main
	/root/go/src/github.com/argoproj/argo/cmd/argoexec/main.go:11
runtime.main
	/usr/local/go/src/runtime/proc.go:185
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:2337"
```

Need to investigate retries of artifact saving

**Comment by jessesuen** [comment]
The minio-go SDK already considers the error "net/http: TLS handshake timeout" something retryable. I need to check if this is something that is already retried by their client, or if we need to perform our own retries in the executor.

```
// isNetErrorRetryable - is network error retryable.
func isNetErrorRetryable(err error) bool {
	if err == nil {
		return false
	}
	switch err.(type) {
	case net.Error:
		switch err.(type) {
		case *net.DNSError, *net.OpError, net.UnknownNetworkError:
			return true
		case *url.Error:
			// For a URL error, where it replies back "connection closed"
			// retry again.
			if strings.Contains(err.Error(), "Connection closed by foreign host") {
				return true
			}
		default:
			if strings.Contains(err.Error(), "net/http: TLS handshake timeout") {
				// If error is - tlsHandshakeTimeoutError, retry.
				return true
			} else if strings.Contains(err.Error(), "i/o timeout") {
				// If error is - tcp timeoutError, retry.
				return true
			} else if strings.Contains(err.Error(), "connection timed out") {
				// If err is a net.Dial timeout, retry.
				return true
			}
		}
	}
	return false
}
```

**Comment by jessesuen** [comment]
Through code inspection, I do believe that minio is already retrying the "net/http: TLS handshake timeout" error: 
FPutObject -> putObjectCommon -> putObjectNoChecksum -> putObjectDo -> executeMethod -> isNetErrorRetryable

**Comment by jessesuen** [comment]
There is close to a 1 minute delay from:
```time="2017-12-18T03:18:03Z" level=info msg="Saving from...```
to the timeout error:
```time="2017-12-18T03:19:00Z" level=fatal msg="Error saving output artifacts, [ERR_INTERNAL] Get https://storage.googleapis.com/BUCKETNAME-REDACTED/?location=: net/http: TLS handshake timeout```

@javierbq -- how big is the sparksx-cambyses-alignment.tgz artifact file? Does this happen only on artifact saving? Or are you also seeing these errors during artifact loading?

**Comment by edlee2121** [comment]
Not able to reproduce yet.

**Comment by edlee2121** [comment]
Some questions that came up:
-- Exactly what is causing the errors?
-- Is the final error happening after lower levels have already retried? 
-- Retrying too aggressively could destabilize the system.

Any additional client-side logging that would help  determine exactly what is happening?

**Comment by sandeepbhojwani** [comment]
Verified through code inspection that minio client retries on s3 errors, http errors, and network errors for all s3 operations.

**Comment by jessesuen** [comment]
@sandeepbhojwani can you check with @javierbq to find out if this reoccurring problem before deciding if a fix is necessary?

**Comment by sandeepbhojwani** [comment]
@jessesuen no fix is required since minio client already retries a few times before giving up
