### ISSUE TITLE
Make resource watch more resilient

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo#627]
Our resource watching mechanism in argoexec relies on kubectl, which may or may not handle disconnects from the API server very well. This needs investigation to understand if we need to refork kubectl upon EOF, or if kubectl handles this us for us.

**Comment by jessesuen** [comment]
I experimented by killing the kube apiserver in the middle of `kubectl get pods -w`. After the api server was killed, kubectl completed with return code 0. This to us would be a silent failure because we would continue down of the workflow before the resource reached the desired state. In other words, the fix for this bug is needed.

**Comment by gaganapplatix** [comment]
Fixed in PR https://github.com/argoproj/argo/pull/690
