### ISSUE TITLE
UI should show workflow namespace

### ISSUE THREAD

**Issue by jlewi** [argoproj/argo#629]
The UI doesn't seem to show the namespace for workflows; either in the timeline view or details view.

Here's an example for a workflow in a namespace.

```
kubectl --namespace=kubeflow-test-infra get workflows.argoproj.io -o=custom-columns=Name:'.metadata.name',Namespace:'.metadata.namespace'
Name                Namespace
hello-world-tx7jj   kubeflow-test-infra
```

Here are screenshots of what I see in the timeline view and details page; which don't show namespace.

![timeline_view](https://user-images.githubusercontent.com/777219/34399841-30a0aef2-eb40-11e7-9cf3-46fff7d51d31.png)

![workflow_details](https://user-images.githubusercontent.com/777219/34399840-2bad4586-eb40-11e7-816d-8b18908992df.png)

**Comment by alexmt** [comment]
Namespace field had been added to workflow list and workflow details pages
