### ISSUE TITLE
Support copy and paste of Logs in UI

### ISSUE THREAD

**Issue by jlewi** [argoproj/argo#636]
I can't seem to copy and paste from the UI panel showing the logs for one of my workflow steps.

**Comment by alexmt** [comment]
It was impossible to copy logs due to backward backward incompatible change in xterm library. Issue is fixed now.

**Comment by jlewi** [comment]
Thanks for the quick fix.

**Comment by jlewi** [comment]
I'm using argoproj/argoui:v2.0.0-alpha3 and the issue doesn't seem to be fixed; should it be?

**Comment by jlewi** [comment]
My mistake this does appear to be working.
