### ISSUE TITLE
Global search/Deployments tab - select all checkbox doesn't work.

### ISSUE THREAD

**Issue by wokeGit** [argoproj/argo#64]
Open global search -> go to "Deployments" tab and try to select first checkbox (select all).

Expected result:
All the deployments on the list will be selected

Actual result:
All the deployments on the list are unselected

![xvpbee2qq1](https://user-images.githubusercontent.com/13086525/29773755-19a77730-8bff-11e7-8621-390d1a0a6e83.gif)

**Comment by alexmt** [comment]
@felixApplatix , can you take a look please?
