### ISSUE TITLE
[UI] Workflows With Many Steps Overflow Page

### ISSUE THREAD

**Issue by pnovotnak** [argoproj/argo#645]
Creating a workflow with many steps causes the steps to overflow off the right side of the page and since the page cannot be scrolled the hidden steps are impossible to view

**Comment by jessesuen** [comment]
@alexmt not sure if this fix is very involved or not. If it is too involved, you may want to focus efforts on the DAG based display of workflows instead.

**Comment by jessesuen** [comment]
Closing this since v2.1 will have completely rewritten UI (angular -> react) with completely different views.
