### ISSUE TITLE
Add macOS releases to Homebrew

### ISSUE THREAD

**Issue by 0xdevalias** [argoproj/argo#654]
It would be cool if this was available via [Homebrew](https://brew.sh/) on macOS.

The following could be used as an example layout for the Formula:
* https://github.com/Homebrew/homebrew-core/blob/master/Formula/faas-cli.rb

**Comment by jessesuen** [comment]
Yes, I agree. Would make getting started easier, reducing the barrier to entry, and help manage upgrades better.

**Comment by jessesuen** [comment]
A brew tap repo was created and argo CLI can be installed using the command:
```
$ brew install argoproj/tap/argo
```

**Comment by 0xdevalias** [comment]
Amazing, thankyou!

**Comment by dimm0** [comment]
Don't see this repo in brew... Did it get removed?

**Comment by kurtfunai** [comment]
Seeing the same as dimm0 - cannot install via `brew install argoproj/tap/argo`

**Comment by jessesuen** [comment]
Brew used to have implicit tapping, but it seems that it's been removed

The instructions should be:
```
brew tap argoproj/tap
brew install argoproj/tap/argo
```
