### ISSUE TITLE
Invalid margins on several pages

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo#66]
@rahuldhide :

Some components are overlapping due to the new margins. Specially the commits cards is not looking good with Create New Job and jobs numbers in two different lines. If we tweak the margins as per the attached specs, we will be able to resolve all these issues.

![2](https://user-images.githubusercontent.com/426437/29786231-37c4cfc6-8bdf-11e7-9ae7-3cdd6bfb5819.png)

**Comment by alexmt** [comment]
@rahuldhide  can you please clarify requirements for this change? Are you proposing to change global search results table width to 100% - 80px margins? and all other screens like commits, policies, templates should be centered?

**Comment by rahuldhide** [comment]
@alexmt @wokeGit For this issue, we just need to change the global search results table width to 100% with 80px (or our standard relative rem) margin. All other screens are already adjusted during the M10 release and they are looking fine. I am removing those specs (attachment) to avoid the confusion.

**Comment by wokeGit** [comment]
@alexmt @rahuldhide Thanks for answer.
Described changes are available here:
https://github.com/argoproj/argo/pull/121
