### ISSUE TITLE
example/artifact-passing.yaml not working

### ISSUE THREAD

**Issue by reasonthearchitect** [argoproj/argo#671]
Gents.

I am trying to run the example/artifact-passing.yaml, however, I am unable to execute it successfully. Please note that I am able to refactor the example to mount a volume and pass data that way... but I do not want to submit as I assume that is not the strategy. Please excuse the fact that I am unable to fix the issue as I am fairly new to your project and do not yet have the information available to suggest any way of correcting this.

In the end... this may be an issue with my configuration... I am using minikube version: v0.24.1... 
My kubectl is:
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:57:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"0b9efaeb34a2fc51ff8e4d34ad9bc6375459c4a4", GitTreeState:"clean", BuildDate:"2017-11-29T22:43:34Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}

Mac OS... but I will try to run it on my linux setup once I get home.

Any questions please let me know.
Rhys

**Comment by reasonthearchitect** [comment]
Additionally... the error message I am receiving is:

{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \"artifact-passing-9cpm7-1014716544\" not found","reason"
:"NotFound","details":{"name":"artifact-passing-9cpm7-1014716544","kind":"pods"},"code":404}

Obviously... its not a lot of information to go on.

**Comment by jessesuen** [comment]
Artifact passing is pretty basic and expected to work. Could you provide some more information? 

1. the output from `argo get <failedworkflowname>`. It should look like the following:
```
$ argo get artifact-passing-b8c8p
Name:             artifact-passing-b8c8p
Namespace:        default
Status:           Succeeded
Created:          Tue Jan 09 11:34:57 -0800 (5 hours ago)
Started:          Tue Jan 09 11:34:57 -0800 (5 hours ago)
Finished:         Tue Jan 09 11:35:08 -0800 (5 hours ago)
Duration:         11 seconds

STEP                       PODNAME                            MESSAGE
 ✔ artifact-passing-b8c8p
 ├---✔ generate-artifact   artifact-passing-b8c8p-3738913253
 └---✔ consume-artifact    artifact-passing-b8c8p-729415115
```

2. if there is a failed pod name in step 1, run:
```
kubectl logs <failedpodname> -c init
kubectl logs <failedpodname> -c wait
```
NOTE: init will only exist for the consume-artifact step.

**Comment by jessesuen** [comment]
BTW, feel free to join our slack channel, where you might get help there from folks who aren't actively monitoring the github issues.

**Comment by reasonthearchitect** [comment]
Hey Jesse. Thanks for the reply. I will see about getting on Slack later. I
have to shift gears for a while but will be coming back to Argo soon. Love
the project! Kudos to you and your team!

For your knowledge, running the argo get command returns the following.

Name:             artifact-passing-v4fdt

Namespace:        default

Status:           Error

Message:          controller is not configured with a default archive
location

Created:          Wed Jan 10 11:05:17 -0500 (2 minutes ago)

Started:          Wed Jan 10 11:05:17 -0500 (2 minutes ago)

Finished:         Wed Jan 10 11:05:17 -0500 (2 minutes ago)

Duration:         0 seconds


STEP                       PODNAME                            MESSAGE

 ⚠ artifact-passing-v4fdt

 └---⚠ generate-artifact   artifact-passing-v4fdt-2415956628  controller is
not configured with a default archive location

**Comment by jessesuen** [comment]
Ah yes this is the expected behavior when argo is not configured with an artifact repository. The getting started page explains how you can do this.
https://github.com/argoproj/argo/blob/master/demo.md

It uses Minio, but you can use any S3 compatible object store.
