### ISSUE TITLE
Stress testing Argo

### ISSUE THREAD

**Issue by shrinandj** [argoproj/argo#677]
It'll be good to test running of Argo workflows at scale. Based on offline discussions with a few folks, the following is a good set of tests to perform and see if the workflow controller is able to correctly process and complete all the workflows. Note that the lists below is not exhaustive, but this would be a good start.

**Environments**:

* Created different Kubernetes clusters with nodes resulting in 40vCPUs.

| vCPUs per node | Number of Nodes in the K8S Cluster |
| --- | --- |
| 2 | 20 |
| 4 | 10 |
| 8 | 5 |

**Tests to run on each cluster**:

* 10 parallel workflows, each workflow having 100 parallel steps.
* 1 workflow with 1000 parallel steps
* 100 workflows sequentially, each having 300 parallel steps.

**Expected results**:

* All the above should complete successfully, each workflow should complete.
* The Workflow controller should not crash/panic.

**Open questions**:

* What containers should be run in each step in the above workflows?

**Comment by edlee2121** [comment]
Let's limit the max size of the test cluster to 40 vCPU for now.

**Comment by jessesuen** [comment]
FYI we have a test/e2e/stress directory which is intended to contain yamls that stress the system.
