### ISSUE TITLE
Argo UI is  failing to render workflow which has not been picked up by workflow controller

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo#680]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT

**What happened**:

Argo UI is  failing to render workflow which has not been picked up by workflow controller

**What you expected to happen**:

Argo UI should successfully render workflows

**How to reproduce it (as minimally and precisely as possible)**:

Submit workflow and make sure it is not pick up by workflow controller (e.g. use workflow controller instance id)

**Environment**:
- Argo version: v2.0.0-alpha3

**Comment by jessesuen** [comment]
Fixed.
