### ISSUE TITLE
Proposal: argo resubmit

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo#694]
A common request/use case is to restart or resubmit a failed workflow, and reuse the progress which it already made, then retrying the failed steps and continuing where the workflow left off.

This proposal is for a `argo resubmit <workflowname>` command. This would be an entirely client-side feature which would formulate a new workflow based upon a previous, completed workflow, by filling-out the node statuses with results from the previous run, such that once received, the controller would operate on the workflow as if it were in the middle of operation.

**Comment by dvavili** [comment]
👍 Would be really good to have this feature. Any timeline planned for this feature?
