### ISSUE TITLE
`argo login` does not prompt user to proceed insecurely for SSL certificate related failures

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo#7]
The `argo login` command is supposed to prompt the user to proceed with an insecure configuration in the event he tries to login to a cluster with a self-signed certificate, which is the out-of-the box configuration of our clusters after a completed installation.

**Comment by abhinavdas** [comment]
How about we set the default as a symlink to the currently installed cluster if the file is currently a symlink. If not we can copy the default to default.bak and convert it symlink. This will allow fresh installs of our cluster to directly use the argo command without any additional steps

**Comment by jessesuen** [comment]
I agree that new installations should behave this way. If we are creating the `.argo` directory for them, or `.argo/default` does not yet exist, we will make `.argo/default` a symlink to the one created during installation. However, changing the meaning of `default` from underneath the user (if they already had a default config), is not desirable.

**Comment by jessesuen** [comment]
Fixed in 1.0.1 and 1.1.
