### ISSUE TITLE
BUG: retry-container crashes controller (dag branch)

### ISSUE THREAD

**Issue by gaganapplatix** [argoproj/argo#708]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT

**What happened**:
retry-container example crashes the controller

**What you expected to happen**:
controller to not crash

**How to reproduce it (as minimally and precisely as possible)**:
yes submit retry-container workflow in example

**Anything else we need to know?**:
Bug is in:
func (woc *wfOperationCtx) executeRetryContainer(nodeName string, tmpl *wfv1.Template, boundaryID string) error {
	node := woc.getNodeByName(nodeName)
	if node == nil {
		node := woc.initializeNode(nodeName, wfv1.NodeTypeRetry, boundaryID, wfv1.NodeRunning)
		node.RetryStrategy = tmpl.RetryStrategy
		woc.wf.Status.Nodes[node.ID] = *node
	}
	if err := woc.processNodeRetries(node); err != nil {
		return err
}

node := inside the if is in local scope

**Environment**:
local build

**Other debugging information (if applicable)**:
- workflow-controller logs:
INFO[0541] Processing workflow                           namespace=default workflow=retry-container-j5znd
INFO[0541] Updated phase  -> Running                     namespace=default workflow=retry-container-j5znd
WARN[0541] node is nil                                   namespace=default workflow=retry-container-j5znd
INFO[0541] node retry-container-j5znd (retry-container-j5znd) initialized Running  namespace=default workflow=retry-container-j5znd
WARN[0541] node is retry-container-j5znd (retry-container-j5znd)  namespace=default workflow=retry-container-j5znd
WARN[0541] node before process retries <nil>             namespace=default workflow=retry-container-j5znd
WARN[0541] Checking completed for retry %v<nil>          namespace=default workflow=retry-container-j5znd
INFO[0541] Updated phase Running -> Error                namespace=default workflow=retry-container-j5znd
INFO[0541] Updated message  -> runtime error: invalid memory address or nil pointer dereference  namespace=default workflow=retry-container-j5znd
INFO[0541] Marking workflow completed                    namespace=default workflow=retry-container-j5znd
ERRO[0541] Recovered from panic: runtime error: invalid memory address or nil pointer dereference
goroutine 33 [running]:
runtime/debug.Stack(0xc42027a6e0, 0x247e7c0, 0x24dc5a0)
        /usr/local/opt/go/libexec/src/runtime/debug/stack.go:24 +0xa7
github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).operate.func1(0xc42027a6e0)
        /Users/gprakash1/Develop/go/src/github.com/argoproj/argo/workflow/controller/operator.go:97 +0xb5
panic(0x1c37ba0, 0x24dc5a0)
        /usr/local/opt/go/libexec/src/runtime/panic.go:491 +0x283
github.com/argoproj/argo/pkg/apis/workflow/v1alpha1.v1alpha1.NodeStatus.Completed(...)
        /Users/gprakash1/Develop/go/src/github.com/argoproj/argo/workflow/controller/operator.go:275
github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).processNodeRetries(0xc42027a6e0, 0x0, 0x2, 0x2)
        /Users/gprakash1/Develop/go/src/github.com/argoproj/argo/workflow/controller/operator.go:275 +0xdb
github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).executeRetryContainer(0xc42027a6e0, 0xc4202d8ce0, 0x15, 0xc4200a4d20, 0x0, 0x0, 0x0, 0xc4201a7c20)
        /Users/gprakash1/Develop/go/src/github.com/argoproj/argo/workflow/controller/operator.go:914 +0x124
github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).executeTemplate(0xc42027a6e0, 0xc4206541c0, 0xf, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc4202d8ce0, ...)
        /Users/gprakash1/Develop/go/src/github.com/argoproj/argo/workflow/controller/operator.go:767 +0x7f0
github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).operate(0xc42027a6e0)
        /Users/gprakash1/Develop/go/src/github.com/argoproj/argo/workflow/controller/operator.go:131 +0x56f
github.com/argoproj/argo/workflow/controller.(*WorkflowController).processNextItem(0xc42010d6c0, 0x1434100)
        /Users/gprakash1/Develop/go/src/github.com/argoproj/argo/workflow/controller/controller.go:210 +0x27c
github.com/argoproj/argo/workflow/controller.(*WorkflowController).runWorker(0xc42010d6c0)
        /Users/gprakash1/Develop/go/src/github.com/argoproj/argo/workflow/controller/controller.go:176 +0x2b
github.com/argoproj/argo/workflow/controller.(*WorkflowController).(github.com/argoproj/argo/workflow/controller.runWorker)-fm()
        /Users/gprakash1/Develop/go/src/github.com/argoproj/argo/workflow/controller/controller.go:143 +0x2a
github.com/argoproj/argo/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc4202e40d0)
        /Users/gprakash1/Develop/go/src/github.com/argoproj/argo/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x5e
github.com/argoproj/argo/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc4202e40d0, 0x3b9aca00, 0x0, 0x11700000001, 0xc42026e060)
        /Users/gprakash1/Develop/go/src/github.com/argoproj/argo/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbd
github.com/argoproj/argo/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc4202e40d0, 0x3b9aca00, 0xc42026e060)
        /Users/gprakash1/Develop/go/src/github.com/argoproj/argo/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by github.com/argoproj/argo/workflow/controller.(*WorkflowController).Run
        /Users/gprakash1/Develop/go/src/github.com/argoproj/argo/workflow/controller/controller.go:143 +0x597
  namespace=default workflow=retry-container-j5znd
INFO[0542] Patch successful

**Comment by jessesuen** [comment]
Fixed
