### ISSUE TITLE
UI not showing onExit handler steps

### ISSUE THREAD

**Issue by jlewi** [argoproj/argo#710]
I have a worflow [workflow_spec.yaml.txt](https://github.com/argoproj/argo/files/1685973/workflow_spec.yaml.txt)

which has onExit specified but based on the [UI](http://testing-argo.kubeflow.io/timeline/kubeflow-test-infra/training-presubmit-1-5-01063400;tab=workflow) the workflow specified onExit isn't running.

The status however does indicate that teardown-cluster step ran.

I'm still using argoproj/argoui:v2.0.0-alpha3
Should I try upgrading to the beta?

@jessesuen

**Comment by alexmt** [comment]
@jlewi, unfortunately, UI does not render onExit workflow yet. We are redesigning workflow details page to support DAG workflows and plan to solve the issue during redesign.

**Comment by jlewi** [comment]
Thanks.

**Comment by jessesuen** [comment]
Closing issue since v2.1 UI is being completely rewritten for DAGs. onExit will be rendered as a continuation of the main DAG with some indicator that is the exit handler.

**Comment by Spenhouet** [comment]
@jessesuen We are on version 3.5.12, and the exit handler is not rendered on the UI. Is that expected?
