### ISSUE TITLE
script template should support env

### ISSUE THREAD

**Issue by vreon** [argoproj/argo#711]
**Is this a BUG REPORT or FEATURE REQUEST?**:

Feature request

**What happened**:

I wanted to use an existing Secret's values in a `script` template, so I tried to use `env` (in the same vein as the `container` template).

**What you expected to happen**:

`env` is ignored in the Workflow, and isn't present in the resulting container's `spec`.

**How to reproduce it (as minimally and precisely as possible)**:

```console
$ kubectl create secret generic my-secret --from-literal password=woooo
$ cat test.yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: test
spec:
  entrypoint: main
  templates:
  - name: main
    script:
      image: busybox
      command: [sh]
      source: |
        printenv
      env:
      - name: PASSWORD
        valueFrom:
          secretKeyRef:
            name: my-secret
            key: password
$ argo submit -w test.yaml && argo logs test | grep PASSWORD
```

**Anything else we need to know?**:

A couple of workarounds exist:

- Instead of `script`, use a `container` template and [include the script source as a `raw` artifact](https://gist.github.com/vreon/06c73e6f8e10e6e23819be25d011b281) :+1:
- Instead of `script`, use a `container` template and [inline the script with `args`](https://github.com/argoproj/argo/blob/d929e79f623017a923d1c4e120c363e08fe7a64a/examples/secrets.yaml#L29-L33) :neutral_face:
- Use `kubectl` binary as an input artifact and [read from the Secret in the script source](https://gist.github.com/vreon/3968a73d63f306fa80fd9f53dfa7020a) :dizzy_face:

I feel like `volumeMounts` should also be supported, though I don't need it for this use case.

**Environment**:
- Argo version:
```
$ argo version
argo: v2.0.0-beta1
  BuildDate: 2018-01-18T22:06:03Z
  GitCommit: 549870c1ee08138b20b8a4b0c026569cf1e6c19a
  GitTreeState: clean
  GitTag: v2.0.0-beta1
  GoVersion: go1.9.1
  Compiler: gc
  Platform: linux/amd64
```
- Kubernetes version :
```
$ kubectl version -o yaml                                                   
clientVersion:
  buildDate: 2017-09-28T22:57:57Z
  compiler: gc
  gitCommit: 6e937839ac04a38cac63e6a7a306c5d035fe7b0a
  gitTreeState: clean
  gitVersion: v1.8.0
  goVersion: go1.8.3
  major: "1"
  minor: "8"
  platform: linux/amd64
serverVersion:
  buildDate: 2017-11-29T22:43:34Z
  compiler: gc
  gitCommit: 0b9efaeb34a2fc51ff8e4d34ad9bc6375459c4a4
  gitTreeState: clean
  gitVersion: v1.8.0
  goVersion: go1.9.1
  major: "1"
  minor: "8"
  platform: linux/amd64
```

**Comment by jessesuen** [comment]
I agree with your use case especially secrets and environment variables. Being able to control `imagePullPolicy` in script templates is another that comes to mind. In other words, script templates should be pretty much be defined as a container object but with the extra `source` field for holding the script contents.

**Comment by JulienBalestra** [comment]
@jessesuen I'd like to control the `imagePullPolicy` setting, currently I have a value set to `Always` for my custom images.

Is it planned for soon ? Do you want me to open a dedicated issue for that ?
