### ISSUE TITLE
Argo 2 Helm Chart

### ISSUE THREAD

**Issue by bobhenkel** [argoproj/argo#712]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST

It would be really nice for users to be able to install Argo 2 via a helm chart. Argo command line is nice, but for installing Argo it's nice using one of the most standards methods/tools for installing onto K8s, which is Helm.

Thanks and great work!

**Comment by jessesuen** [comment]
Actually we do have it at https://github.com/argoproj/argo-helm
