### ISSUE TITLE
Use 'watch' based implementation for wait command

### ISSUE THREAD

**Issue by 0xdevalias** [argoproj/argo#715]
While exploring how the 'wait' feature is implemented, I came across the following notes in the source code:

https://github.com/argoproj/argo/blob/master/cmd/argo/commands/wait.go#L40-L41
> // Watch APIs on CRDs using fieldSelectors are only supported in Kubernetes v1.9.0 onwards.
> // https://github.com/kubernetes/kubernetes/issues/51046.

https://github.com/argoproj/argo/blob/master/cmd/argo/commands/wait.go#L112-L114
> // TODO(shri): When Kubernetes 1.9 support is added, this block should be executed
> // only for versions 1.8 and for 1.9, a new "watch" based implmentation should be
> // used.

I didn't see any open issues about it, so wanted to track it here so I can see how the 'wait' implementation looks when it's done.

**Comment by jessesuen** [comment]
Fixed. Can see implementation here:
https://github.com/argoproj/argo/blob/master/cmd/argo/commands/wait.go#L49
