### ISSUE TITLE
argo logs fails due to incorrect name

### ISSUE THREAD

**Issue by cliveseldon** [argoproj/argo#719]
**Is this a BUG REPORT or FEATURE REQUEST?**: bug report

**What happened**:
I ran https://github.com/argoproj/argo/blob/master/examples/volumes-pvc.yaml

```
argo list
NAME                STATUS    AGE   DURATION
volumes-pvc-52wqd   Running   3s    3s 
```
```
argo logs volumes-pvc-52wqd
Error from server (NotFound): pods "volumes-pvc-52wqd" not found
FATA[0001] exit status 1    
```

reason is maybe pod name is actually : 
```
volumes-pvc-52wqd-3954717052                        0/2       Completed   0          37s
```

**What you expected to happen**:

to see the logs

**How to reproduce it (as minimally and precisely as possible)**:

as above

**Anything else we need to know?**:

**Environment**:
- Argo version:
argo: v2.0.0-beta1
  BuildDate: 2018-01-18T22:06:03Z
  GitCommit: 549870c1ee08138b20b8a4b0c026569cf1e6c19a
  GitTreeState: clean
  GitTag: v2.0.0-beta1
  GoVersion: go1.9.1
  Compiler: gc
  Platform: linux/amd64

```
$ argo version
```
- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: 2017-09-28T22:57:57Z
  compiler: gc
  gitCommit: 6e937839ac04a38cac63e6a7a306c5d035fe7b0a
  gitTreeState: clean
  gitVersion: v1.8.0
  goVersion: go1.8.3
  major: "1"
  minor: "8"
  platform: linux/amd64
serverVersion:
  buildDate: 2018-01-25T21:58:21Z
  compiler: gc
  gitCommit: 192ccad06d24af9828cbf42330e1d915cb586406
  gitTreeState: clean
  gitVersion: v1.8.7-gke.0
  goVersion: go1.8.3b4
  major: "1"
  minor: 8+
  platform: linux/amd64

```

**Other debugging information (if applicable)**:
- workflow result:
```
$ argo get <workflowname>
```
- executor logs:
```
$ kubectl logs <failedpodname> -c init
$ kubectl logs <failedpodname> -c wait
```
- workflow-controller logs:
```
$ kubectl logs -n kube-system $(kubectl get pods -l app=workflow-controller -n kube-system -o name)
```

**Comment by jessesuen** [comment]
`argo logs` is actually just a convenience wrapper under `kubectl logs -c main`. It is expected to accept a pod name and not a workflow name, which is what you are seeing. The feature to be able to see logs of all pods in a workflow in a single stream, is being tracked by issue #660.
