### ISSUE TITLE
Argo CLI incorrectly render step names if step name has dot surrounded with parenthesis.

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo#731]
**Is this a BUG REPORT or FEATURE REQUEST?**:

BUG

**What happened**:

Argo CLI incorrectly render step names if step name has dot surrounded with parenthesis. Example: 
1. Submit ci.yaml example: `argo submit ~/root/go/src/github.com/argoproj/argo/examples/ci.yaml` Executed workflow will have steps named as `test(image:alpine,tag:3.6)`, `test(image:ubuntu,tag:17.10)` etc. 
2. Try to run `argo get <workflow-name>`
Output contains invalid step names:
```
 ✔ ci-example-kxzs4
 ├---✔ build         ci-example-kxzs4-815356921   28s
 └-·-✔ 1)            ci-example-kxzs4-3496544447  14s
   ├-✔ 10)           ci-example-kxzs4-3102090322  16s
   └-✔ 6)            ci-example-kxzs4-2788687772  4s
```

**What you expected to happen**:

Output should contain correct names:
```
 ✔ ci-example-kxzs4
 ├---✔ build                                                 ci-example-kxzs4-815356921   28s
 └-·-✔ test(image:debian,tag:9.1)            ci-example-kxzs4-3496544447  14s
   ├-✔   test(image:alpine,tag:3.6)           ci-example-kxzs4-3102090322  16s
   └-✔  test(image:ubuntu,tag:17.10)            ci-example-kxzs4-2788687772  4s

```

**How to reproduce it (as minimally and precisely as possible)**:

`argo submit ~/root/go/src/github.com/argoproj/argo/examples/ci.yaml` 

**Environment**:
- Argo version: v2.0.0
```
$ argo version

**Comment by jessesuen** [comment]
BTW, this should only be affecting 2.1

**Comment by gaganapplatix** [comment]
how is that legal name for a  step. I though we don't allow those characters in a step

**Comment by gaganapplatix** [comment]
Ah, I see it, withItems adds to the names after validation so it doesn't fail. Hmm, we should either adhere to the validation requirement or change the parsing in cli

**Comment by jessesuen** [comment]
Yes, I forgot that splitting by '.' is not always correct because of the withItems. In 2.0 I handled this by understanding the parent's name when rendering the node name in the CLI.  BTW, Alex wanted to take this bug to get his hands dirty with go
