### ISSUE TITLE
[feature request] Add badge and GitHub status link

### ISSUE THREAD

**Issue by gaocegege** [argoproj/argo#733]
**Is this a BUG REPORT or FEATURE REQUEST?**:

FEATURE REQUEST

**What you expected to happen**:

Add badge and GitHub status link

**Anything else we need to know?**:

Hi, I am a member from [kubeflow](https://github.com/kubeflow/kubeflow), and we are using argo to run our test. But I found that we can not set status link as Travis CI does and there is no badge for argo. Then we [implemented the status report in the workflow](https://github.com/kubeflow/testing/pull/17). I understand that argo is a general workflow engine but if we support badge and GitHub status link internally, it will be friendly for CI users.

**Comment by jessesuen** [comment]
@gaocegege, are you referring to the ability to post a response to github webhook commit/PR event and post a green checkmark or red X? For example:

![image](https://user-images.githubusercontent.com/12677113/36070750-7c39972c-0eb6-11e8-8494-0792dcc0f3bf.png)

If you are, we have a separate project, [argo-ci](https://github.com/argoproj/argo-ci), which is being developed specifically for the CI use case. In fact. all of argoproj/argo commit pass/fail results are posted using argo-ci, in lieu of travis, circle, etc...

Without argo-ci, the onExit handler of a workflow was intended to be used to post github results, send slack notifications, perform cleanup tasks, etc...  But based on the PR that you linked to, I think this is what kubeflow is doing.

As you mentioned, argo is intended to be a more general purpose workflow engine, and prefer that more purpose built applications be built on top.

**Comment by gaocegege** [comment]
@jessesuen 

Thanks for your reply, I think argo-ci is what I want to have a try 😄 

I am closing the issue.

**Comment by jp-gouin** [comment]
Hi , 
Since Argo-ci is deprecated , is there a way to have the workflow status in GitHub ? 
and the badge (same as argo-cd)

thanks

**Comment by alexec** [comment]
Maybe try widgets in v3?

**Comment by jp-gouin** [comment]
Thank you 🙏 that’s exactly what I was looking for

**Comment by agilgur5** [comment]
Superseded by Widgets, i.e. #4769
