### ISSUE TITLE
Publish statically linked argo binary

### ISSUE THREAD

**Issue by mthx** [argoproj/argo#735]
**Is this a BUG REPORT or FEATURE REQUEST?**:

FEATURE REQUEST

**What happened**:

I tried to run `argo` inside an alpine-based Docker image.  This fails with a cryptic `not found`.  This is because alpine uses `musl` instead of `glibc` and `argo` is dynamically linked.

I downloaded `kubectl` to see what approach other Go-based Kubnernetes tools take, and that binary is statically linked and runs fine in alpine.

**What you expected to happen**:

I hoped it would work 😄 

Although I could use a glibc-based image, providing a statically linked binary would make `argo` easier to use with a range of existing images and consistent with `kubectl`.

**How to reproduce it (as minimally and precisely as possible)**:

```sh
➜  ~ docker run -ti alpine
$ apk update && apk add curl
OK: 5 MiB in 14 packages
$ curl -sSL -o /usr/local/bin/argo https://github.com/argoproj/argo/releases/download/v2.0.0/argo-linux-amd64
$ chmod +x /usr/local/bin/argo
$ argo
/bin/sh: argo: not found
```

**Comment by jessesuen** [comment]
This makes sense. Linux binary should be built statically.
