### ISSUE TITLE
Difficulty finding documentation about policies

### ISSUE THREAD

**Issue by vicaire** [argoproj/argo#746]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG

**What happened**:

It seems that Argo supports policies to automate when a workflow get triggered. But I am having trouble finding the documentation. I found this page: https://applatix.com/open-source/argo/docs/yaml/ex_create_policy_4_workflow.html, but the links are broken. 

Clicking "Viewing, Enabling and Disabling Policies" leads back to the main page of the website.

Clicking "Using Policies to Trigger a Notification Message" leads to a 404.

Apologies if this is not the right forum for issues related to the Argo website.

Thanks!

**Comment by alexmt** [comment]
Policies are supported by Argo V1.x . Argo V2.x is only workflow engine and does not have policies. Documentation had been updated, but looks like you are seeing cached version. We have bug open to solve caching issue: https://github.com/argoproj/argo/issues/713

**Comment by vicaire** [comment]
Hi Alexander,

Do you have a recommendation about what are the best tools to use to achieve the same functionality as policies in Argo V2.X?  

Thanks!

**Comment by vicaire** [comment]
Hi Alexender, 

There would be two use cases: 

- A user would like to run an ML pipeline on a schedule (say once per hour). 
- A user would like to run an ML pipeline every time a Publish/Subscribe event was sent to a Webhook server). 

Thanks!
