### ISSUE TITLE
On timeline page, filter closes on every click. It should stay open.

### ISSUE THREAD

**Issue by felixApplatix** [argoproj/argo#75]
https://dev.applatix.net/app/timeline;view=job;days=1;date=1502953199;failed=true;delayed=true;succeeded=false;running=false;showMyOnly=false

On Timeline page, on the right-up corner, click filter icon, select/unselect filter only works once at a time

**Comment by wokeGit** [comment]
Done: https://github.com/argoproj/argo/pull/76
