### ISSUE TITLE
GUI Issue - Timeline view

### ISSUE THREAD

**Issue by mukulikak** [argoproj/argo#755]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Bug 
**What happened**:
http://argo.applatix.net/workflows/default/argo-ci-lmf7w?tab=timeline&nodeId=null
The workflow timeline show from 1:05 to 1:04 - how is that possible

Also when i click on one step and close the summary window, it leave gray image to the right which goes after resizing the browser

**Comment by alexmt** [comment]
Fixed
