### ISSUE TITLE
Argo CI workflow issue - dependency not working

### ISSUE THREAD

**Issue by mukulikak** [argoproj/argo#756]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Bug

**What happened**:
In the Argo-CI YAML, test depends on build. https://github.com/argoproj/argo/blob/master/.argo-ci/ci.yaml

But in the GUI both in timeline view as well as dependency view they are starting at the same time.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Argo version:
```
$ argo version
```
- Kubernetes version :
```
$ kubectl version -o yaml
```

**Other debugging information (if applicable)**:
- workflow result:
```
$ argo get <workflowname>
```
- executor logs:
```
$ kubectl logs <failedpodname> -c init
$ kubectl logs <failedpodname> -c wait
```
- workflow-controller logs:
```
$ kubectl logs -n kube-system $(kubectl get pods -l app=workflow-controller -n kube-system -o name)
```

**Comment by jessesuen** [comment]
User misunderstanding of the YAML
