### ISSUE TITLE
Better error message when output parameters are too large

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo#765]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

**What happened**:

There is an obtuse error message when an an output parameter is too large:

```
time="2018-02-23T21:13:51Z" level=info msg="Successfully saved output parameter: subdomains"
time="2018-02-23T21:13:51Z" level=info msg="Annotating pod with output"
time="2018-02-23T21:13:55Z" level=info msg="Alloc=5368 TotalAlloc=36926 Sys=15646 NumGC=14 Goroutines=6"
time="2018-02-23T21:13:55Z" level=fatal msg="Pod \"argosubdomainworker-g4mvc-645094894\" is invalid: metadata.annotations: Too long: must have at most 262144 characters"
```

**What you expected to happen**:

A nicer error message

**How to reproduce it (as minimally and precisely as possible)**:

Use a very large file as an output parameter

**Anything else we need to know?**:

**Environment**:
- Argo version: v2.1.0-alpha1

**Comment by simster7** [comment]
Closed with https://github.com/argoproj/argo/blob/4db1c4c8495d0b8e13c718207175273fe98555a2/workflow/executor/executor.go#L761-L766

**Comment by mac9416** [comment]
For folks landing here from Google, I wrote up a workaround for the size limit: https://stackoverflow.com/questions/62537126/how-can-i-work-around-argo-output-parameter-size-limit/62537127

**Comment by simster7** [comment]
@mac9416 this is great! Would you like to submit your example in a PR as well?

**Comment by mac9416** [comment]
Done! https://github.com/argoproj/argo/pull/3276
