### ISSUE TITLE
Installing Argo on AWS Kubernetes

### ISSUE THREAD

**Issue by sgentile** [argoproj/argo#771]
Is there a happy path for installing Argo on AWS Kubernetes ?

I just see 'on mac' and 'on linux' here https://github.com/argoproj/argo/blob/master/demo.md 

Would I ssh to the master and run the linux commands ?

Thank you!

**Comment by jessesuen** [comment]
@sgentile - you run argo (the CLI) from your desktop (wherever you would run normal kubectl commands). argo (the CLI) has a sub-command (`argo install`) to install the workflow-controller into *any* kubernetes cluster (AWS, GKE, minikube, etc...). So on your laptop you should run `brew install argoproj/tap/argo`. Whoever want to submit workflows (e.g. your teammates) should install the argo CLI binary on their workstation.

**Comment by jessesuen** [comment]
If you need further assistance with the install, please join our slack and there's plenty of folks to help out there!
