### ISSUE TITLE
UI should provide information about why workflows failed

### ISSUE THREAD

**Issue by jlewi** [argoproj/argo#776]
**FEATURE REQUEST**:

**What happened**:
Workflow failed because the template was invalid.

Here's relevant status information from `kubectl describe`

```
Status:
  Finished At:  2018-02-28T00:13:42Z
  Message:      invalid spec: spec.onExit template 'exit-handler' undefined
  Phase:        Failed
  Started At:   2018-02-28T00:13:42Z
```
This information doesn't show up in the UI

**What you expected to happen**:

I'd like this information to be surfaced in the UI so that users don't need kubectl access to see why their jobs failed.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Argo version:
```
$ argo version
```
argoproj/argoui:v2.0.0-alpha3

- Kubernetes version :
```
$ kubectl version -o yaml
```

**Comment by jessesuen** [comment]
The failure reason is now being displayed in the 2.1 UI:

![image](https://user-images.githubusercontent.com/12677113/36934166-33b019ce-1e9a-11e8-884a-e1202c07ecd9.png)
