### ISSUE TITLE
Add `argo ui` command

### ISSUE THREAD

**Issue by 0xdevalias** [argoproj/argo#787]
Currently to access the UI we have to go look up some convoluted `port-forward` commands:

* https://github.com/argoproj/argo/blob/master/demo.md#8-access-the-argo-ui

```
kubectl port-forward $(kubectl get pods -n kube-system -l app=argo-ui -o jsonpath='{.items[0].metadata.name}') -n kube-system 8001:8001
```

It would be really cool if we could just run `argo ui` and have this handled automatically for us. Potentially `argo ui 1234` would map it to the specified port. It would be good if it then echo'd the URL we should use to access it as well.

**Comment by alexec** [comment]
You can achieve this in v2.5 using `argo server`
