### ISSUE TITLE
draining nodes with (finished) workflows fails: error: Unknown controller kind "Workflow"

### ISSUE THREAD

**Issue by discordianfish** [argoproj/argo#789]
**BUG REPORT**

**What happened**:
Running `kubectl drain` on a node that has finished workflow pods fails with:
```
error: Unknown controller kind "Workflow": workflow-pod-xx
```

**Anything else we need to know?**:
Looks like this is an upstream issue but probably make sense to track here too?
https://github.com/kubernetes/kubernetes/issues/57049

**Environment**:
- Argo version: :v2.0.0-beta1
- Kubernetes version : 1.9.4
- kubectl version: 1.9.0
```

**Comment by discordianfish** [comment]
(As a workaround one have to remove the workflows manually first)

**Comment by sdtokkolabs** [comment]
Same problem for me while doing a rolling update on kops

**Environment:**

Argo version: :v2.1.0-beta2
Kubernetes version : 1.9.6
Kops: 1.9.0-alpha.3

**Comment by jessesuen** [comment]
According to this comment:
https://github.com/kubernetes/kubernetes/issues/57049#issuecomment-388161944
this is now fixed in kubectl 1.10+. Closing.

**Comment by discordianfish** [comment]
Yes, I haven't seen this anymore. Now it only requires to ignore local state which is fine.
