### ISSUE TITLE
Support for optional input artifacts

### ISSUE THREAD

**Issue by mthx** [argoproj/argo#805]
**FEATURE REQUEST**:

In order to support building workflows out of reusable templates, I'd like to see Argo support optional input artifacts.  At the moment, failing to provide an input artifact when a step calls a template is always an error.  Parameters are already optional if they have a default value.

Has this been considered?

**Comment by jessesuen** [comment]
In other words, are you asking for default field for artifacts? I think it is possible for artifacts to follow the same semantics as parameters. If there is a default value for an input artifact, then it becomes optional.

**Comment by jessesuen** [comment]
Fixed in https://github.com/argoproj/argo/pull/1277. 

Example: https://github.com/argoproj/argo/blob/master/test/e2e/functional/input-artifact-optional.yaml
