### ISSUE TITLE
Multiple namespaces for the same k8s cluster running argo?

### ISSUE THREAD

**Issue by andreimc** [argoproj/argo#828]
**Is this a BUG REPORT or FEATURE REQUEST?**:

QUESTION

**What happened**:

I want to use RBAC to separate argo workflows in multiple namespaces and have argo schedule jobs with service accounts only accessible to this namespace.

Can I deploy the workflow controller to each of the namespace and give it the service account that has access to just that namespace ?

**Comment by jessesuen** [comment]
@andreimc I mentioned this in your other bug, but workflows are already namespaced resources. So anything that the workflow references (volumes, secrets), must be available in that namespace which is running in. Generally, there shouldn't be a need to run multiple controllers except for the following circumstances:

1. the cluster-wide workflow controller config does not apply to all namespaces. (e.g. you want to use different artifact repositories)
2. you want to run different versions of argo workflow-controller
3. you are bundling the argo workflow-controller as part of your higher level application (similar to a database) and want the controller to only operate on application specific workflows. argo-ci does this.

Today, it is already possible to run multiple controllers in a cluster. The trick is how to prevent multiple controllers from fighting over the same workflow. We provide different mechanisms to do so.

Option 1: specify an arbitrary controller instance ID in the workflow-controller's configmap. workflows would then have to be submitted using the `--instanceid XXXX` flag. This is to prevent multiple controllers from fighting over the same workflow. The cluster-wide workflow-controller will not operate on any workflows which have an instance-id specified.

Option 2: specify a namespace in the workflow-controller's configmap. The controller will only operate on workflows in the specified namespace. However, if you do it this way, you need to shutdown any cluster-wide workflow-controllers. This prevents the in-fighting that would happen between a cluster-wide controller vs. a namespaced controller.

**Comment by andreimc** [comment]
@jessesuen thank you very much for your prompt and detailed answers!
