### ISSUE TITLE
Daemon DAG tasks are leaked

### ISSUE THREAD

**Issue by mthx** [argoproj/argo#832]
**Is this a BUG REPORT or FEATURE REQUEST?**:

Bug report

**What happened**:

We converted a steps-based workflow that uses a daemon to use a dag with Argo v2.1.0-beta2 but the daemon pod was reliably leaked.

This also holds if you convert the daemon example workflow, see [dag-with-daemon.txt](https://github.com/argoproj/argo/files/1928594/dag-with-daemon.txt).

The code in steps.go is steps-specific and dag.go doesn't seem to consider daemons as far as I can see.

**What you expected to happen**:

As the syntax for daemons works with dag tasks, we expected it to behave in the same way as for steps and be cleaned up automatically.

We've worked around it by starting the daemon in a steps template.

**How to reproduce it (as minimally and precisely as possible)**:

See example above.  The daemon pod will still be running after workflow completion.

**Anything else we need to know?**:

**Environment**:
- Argo version: 
```
$ argo version
argo: v2.1.0-beta2
  BuildDate: 2018-03-29T20:49:33Z
  GitCommit: fe23c2f651a61a2d7aa877a86edff9802d7b5b47
  GitTreeState: clean
  GitTag: v2.1.0-beta2
  GoVersion: go1.9.3
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: 2018-03-21T15:21:50Z
  compiler: gc
  gitCommit: 9f8ebd171479bec0ada837d7ee641dec2f8c6dd1
  gitTreeState: clean
  gitVersion: v1.9.6
  goVersion: go1.9.3
  major: "1"
  minor: "9"
  platform: darwin/amd64
serverVersion:
  buildDate: 2017-12-15T20:55:30Z
  compiler: gc
  gitCommit: 925c127ec6b946659ad0fd596fa959be43f0cc05
  gitTreeState: clean
  gitVersion: v1.9.0
  goVersion: go1.9.2
  major: "1"
  minor: "9"
  platform: linux/amd64
```

**Comment by jessesuen** [comment]
Yes, this was an oversight and should be fixed.
