### ISSUE TITLE
argo CLI error: invalid configuration: no configuration has been provided

### ISSUE THREAD

**Issue by bladerunner512** [argoproj/argo#838]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG 

**What happened**:
error: invalid configuration: no configuration has been provided

**What you expected to happen**:
installation

**How to reproduce it (as minimally and precisely as possible)**:
$  ./argo install
2018/04/25 18:13:01 invalid configuration: no configuration has been provided

**Anything else we need to know?**:
What is install doing? No Internet access from node . Is local install possible?

**Environment**:
- Argo version: 2.0.0

**Comment by jessesuen** [comment]
Do you have a ~/.kube/config? Also, can you try this with v2.1?

**Comment by bladerunner512** [comment]
Same error with v2.1.0-beta2:
blr512@xyz0055:~/argo$ ./argo-linux-amd64v2.1.0-beta2 install --namespace default
2018/04/26 10:48:47 invalid configuration: no configuration has been provided

blr512@xyz0055:~/argo$ ./argo-linux-amd64v2.1.0-beta2 install
2018/04/26 10:49:17 invalid configuration: no configuration has been provided

blr512@xyz0055:~/argo$ ll ~/.kube
total 20
drwxr-x--- 3 blr512 users 4096 Feb 23 17:01 cache
-rw-r----- 1 blr512 users 5453 Mar  5 10:34 config
drwxr-x--- 3 blr512 users 4096 Apr 25 19:11 http-cache

I was able to install by adding UI, Controller and Exec Argo docker images to our local registry and then use kubectl on yaml install/manifests files - ran docker/whalesay/hello-world successfully, but still can't use Argo CLI. Also not sure what else I might have missed installing this way.

**Comment by jessesuen** [comment]
Could you let me know what the auth provider is for your cluster (e.g. gcp, oidc, azure, etc...)? You can see this in your ~/.kube/config. We didn't include all the others yet (we should) and I'm wondering if that is the problem.

**Comment by bladerunner512** [comment]
This is on premise running k8s v1.9 open source, so auth provider is set as internal master node IP with certificate:
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: xxxxxxxxxxxx
    server: https://<internalIP>:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: kubernetes-admin
  name: kubernetes-admin@kubernetes
current-context: kubernetes-admin@kubernetes
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-certificate-data: xxxxx
    client-key-data: xxxxxx

**Comment by bladerunner512** [comment]
ok, I am able to use CLI with kubeconfig path provided:
blr512@xyz0055:~/argo$ ./argo list --kubeconfig  ~/.kube/config
NAME                STATUS      AGE   DURATION
hello-world-fnf5n   Succeeded   1d    18s
