### ISSUE TITLE
Workflow level timeouts

### ISSUE THREAD

**Issue by vicaire** [argoproj/argo#848]
**Is this a BUG REPORT or FEATURE REQUEST?**: FEATURE REQUEST

The following issue proposes to add an exponential backoff retry strategy at the container level: 

https://github.com/argoproj/argo/issues/700

Would it also make sense to provide retry strategies for whole workflows? 

Additionally, would it be possible to have timeouts for both containers and complete workflow so that (independently of retries) the container and/or workflows are cancelled if they do not complete within a specified duration? 
  
In some cases, it might be useful to specify different timeouts for the case where the execution of the container takes too long, or the scheduling of the container takes too long (due to a lack of ressources in the cluster).

**Comment by jessesuen** [comment]
At the container level this is already possible via the `activeDeadlineSeconds` flag which we carry forward.

**Comment by vicaire** [comment]
Sounds good. Thanks Jesse.

**Comment by vicaire** [comment]
Thanks!
