### ISSUE TITLE
Argo installer should set instance id env variable for argo-ui deployment

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo#863]
**Is this a BUG REPORT or FEATURE REQUEST?**:

FEATURE REQUEST

**What happened**:
If instance id is specified in installation options then Argo installer should set instance id env variable for argo-ui deployment.

**How to reproduce it (as minimally and precisely as possible)**:

Run `argo install instanceid <value>`

**Environment**:
- Argo version:
v2.1.0

**Comment by jessesuen** [comment]
We will be removing installer, see https://github.com/argoproj/argo/issues/928 for motivation.
