### ISSUE TITLE
No age > 1d in argo list command

### ISSUE THREAD

**Issue by niebniebnieb** [argoproj/argo#876]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug report
**What happened**:
argo list age max is 1d even if workflow older than on one day

**What you expected to happen**:
list > 1d
**How to reproduce it (as minimally and precisely as possible)**:
argo list
**Anything else we need to know?**:
Argo UI show correct start date of workflow
**Environment**:
- Argo version: 2.1.0
```
$ argo version
```
- Kubernetes version :
```
$ kubectl version -o yaml
```
clientVersion:
  buildDate: 2018-01-18T10:09:24Z
  compiler: gc
  gitCommit: 5fa2db2bd46ac79e5e00a4e6ed24191080aa463b
  gitTreeState: clean
  gitVersion: v1.9.2
  goVersion: go1.9.2
  major: "1"
  minor: "9"
  platform: darwin/amd64
serverVersion:
  buildDate: 2018-05-11T17:16:56Z
  compiler: gc
  gitCommit: 1883ce4eb0e057cfc2439ebeb9822da0a9d40405
  gitTreeState: clean
  gitVersion: v1.9.7-gke.1
  goVersion: go1.9.3b4
  major: "1"
  minor: 9+
  platform: linux/amd64
**Other debugging information (if applicable)**:
- workflow result:
```
$ argo get <workflowname>
```
- executor logs:
```
$ kubectl logs <failedpodname> -c init
$ kubectl logs <failedpodname> -c wait
```
- workflow-controller logs:
```
$ kubectl logs -n kube-system $(kubectl get pods -l app=workflow-controller -n kube-system -o name)
```

**Comment by jessesuen** [comment]
This is fixed in v2.1.1
