### ISSUE TITLE
Make tar.gz optional during artifacts inputs and outputs

### ISSUE THREAD

**Issue by aisensiy** [argoproj/argo#877]
**Is this a BUG REPORT or FEATURE REQUEST?**:

Feature Request

**What you expected to happen**:

Sometimes the artifacts may by a unit test report which is html format. It is good to make the s3 path public and let user to get the artifacts directly. So I think having an option in artifacts configuration to make the default tar and gzip behavior optional is necessary in this scenario.

**Comment by aisensiy** [comment]
Close this for a same open issue https://github.com/argoproj/argo/issues/784.

**Comment by fj-sanchez** [comment]
I would like to reopen this issue, I think it was only partially implemented. It seems that the current behaviour is to always untar/uncompress an input artifact if it is tarred/compressed: https://github.com/argoproj/argo/blob/1bd50fa2dfd828a04ff012868c98ba33bac41136/workflow/executor/executor.go#L164
