### ISSUE TITLE
Workflow Parameters Cannot be Viewed via Argo UI

### ISSUE THREAD

**Issue by dsmithbauer** [argoproj/argo#881]
**Is this a BUG REPORT or FEATURE REQUEST?**: Feature Request

**What happened**:
Currently, there is no way to view the workflow parameters via the Argo UI.  We use some defaulted workflow parameters, and we use some workflow parameters we require to be provided on the command line that flow through all of our workflow steps.  These parameters can be viewed with an ```argo get <workflow>``` via the command line, but it would be nice to view them via the GUI.

**What you expected to happen**:
When using workflow parameters, it would be nice if the workflow parameters were viewable in the Argo UI somewhere - perhaps the Summary View next to Artifacts and Status, Name, Namespace, etc.

**Environment**:
- Argo version:
```
argo: v2.1.1
  BuildDate: 2018-05-29T20:39:36Z
  GitCommit: ac241c95c13f08e868cd6f5ee32c9ce273e239ff
  GitTreeState: clean
  GitTag: v2.1.1
  GoVersion: go1.9.3
  Compiler: gc
  Platform: linux/amd64
```

**Other debugging information (if applicable)**:
N/A

**Comment by alexmt** [comment]
Implemented by https://github.com/argoproj/argo-ui/commit/2af7504ccd334228845aaee64a57910f909acac5 . Parameters are available on workflow summary tab
