### ISSUE TITLE
Nodename is not supported in Argo Workflow container

### ISSUE THREAD

**Issue by jewel77** [argoproj/argo#895]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

**What happened**:
Kubernetes supports Nodename for pod, pod can be sent to the server specified by the Nodename; However when adding Nodename to Argo Workflow container, the pod is still assigned to the node other than the specified one in Nodename.

**Comment by jewel77** [comment]
FYI, nodeSelector is working.

**Comment by jessesuen** [comment]
@jewel77 when adding nodeSelector I did notice the nodeName, but saw it as redundant to nodeSelector so it wasn't included. I believe the introduction of nodeSelector obsoletes nodeName. Given that kubernetes has a builtin selector label `kubernetes.io/hostname`, is there a use case which nodeName can handle and nodeSelector cannot?

**Comment by jewel77** [comment]
Thank you Jesse for the explanations.

**Comment by jessesuen** [comment]
Closing since `nodeSelector` can serve this purpose
