### ISSUE TITLE
Per template exit handler. 

### ISSUE THREAD

**Issue by vicaire** [argoproj/argo#906]
FEATURE REQUEST: Per template exit handler. 

Hi,

Could it be possible to have a per-template exit handler, instead of having a single exit handler per workflow? 

Here is a couple use cases: 

- We have a large workflow organized in templates, each executing a list of containers. Each template has its own clean up operations (e.g. terminate a Spark cluster that the template needed). These operations are not relevant to the other templates. 

- We want to compose workflows. Workflow 1 has an exit handler. Workflow 2 has an exit handler. When we programatically merge the workflows, there is no easy way to merge the workflow-level exit handlers.

**Comment by sudermanjr** [comment]
This would be really nice.  For example, running a CD pipeline where at certain points the rollback situation is different.

**Comment by wadejensen** [comment]
+1
I have a couple of similar use cases for variable cleanup behaviour, and even just specialising error notifications to our Slack channel announcing the state of the pipeline after certain failure conditions.

**Comment by qimingj** [comment]
+1. Any progress on this?

**Comment by TaylorHere** [comment]
+1.

**Comment by naiduasn** [comment]
+1

**Comment by samuelthan** [comment]
+5000

Dear Argo,  would love it if this feature is included in the roadmap.

It really enchance managing workflow

**Comment by songole** [comment]
+1 Is this on the roadmap?

**Comment by jpugliesi** [comment]
Looks like this is tracking in #1688

**Comment by sudermanjr** [comment]
> Looks like this is tracking in #1688

More specifically, https://github.com/argoproj/argo/pull/1716

**Comment by alexec** [comment]
Fixed in #1716.
