### ISSUE TITLE
Indicate Capacity Issues in CLI output and Workflow Status. 

### ISSUE THREAD

**Issue by vicaire** [argoproj/argo#907]
FEATURE REQUEST: In the status of the Argo Workflow (and in the Argo CLI output), would it be possible to indicate that a container is not being started because not enough capacity is available in the cluster to run the container? 

This problem is quite common and requires users to have a look at the cluster POD themselves to debug.

**Comment by jessesuen** [comment]
@vicaire currently we transition a workflow node directly to `Running` (after the pod is created), even though the pod is not yet `Running`. We've considered introducing a `Pending` phase to workflow pods. Would this help?

**Comment by vicaire** [comment]
Sorry for the delay answering this one. Yes, introducing a Pending state would work great as it would underline the provisioning issue.

**Comment by dcieslak19973** [comment]
Food for thought - if this solution can interoperate with the Cluster Autoscaler so that the Autoscaler could then provision more nodes to handle the Workflow

**Comment by jessesuen** [comment]
> Food for thought - if this solution can interoperate with the Cluster Autoscaler so that the Autoscaler could then provision more nodes to handle the Workflow

This should be happen naturally today, by virtue of the controller creating pods which exceed the resources of the cluster.

**Comment by jessesuen** [comment]
Closing as duplicate to #525.

Example outputs of new Pending phase:
```
$ argo get pod-limits-7pxjd
Name:                pod-limits-7pxjd
Namespace:           default
ServiceAccount:      default
Status:              Running
Created:             Tue Aug 21 17:13:31 -0700 (22 seconds ago)
Started:             Tue Aug 21 17:13:31 -0700 (22 seconds ago)
Duration:            22 seconds
Parameters:
  limit:             10

STEP                    PODNAME                      DURATION  MESSAGE
 ● pod-limits-7pxjd
 ├---✔ gen-number-list  pod-limits-7pxjd-4271121940  7s
 └-·-✔ run-pod(0:1)     pod-limits-7pxjd-888908971   6s
   ├-✔ run-pod(1:2)     pod-limits-7pxjd-1445873513  7s
   ├-✔ run-pod(2:3)     pod-limits-7pxjd-885794523   6s
   ├-◷ run-pod(3:4)     pod-limits-7pxjd-1672831789  13s       ContainerCreating
   ├-◷ run-pod(4:5)     pod-limits-7pxjd-4018617467  13s       ContainerCreating
   ├-◷ run-pod(5:6)     pod-limits-7pxjd-2713948161  13s       ContainerCreating
   ├-● run-pod(6:7)     pod-limits-7pxjd-2941735403  13s
   ├-◷ run-pod(7:8)     pod-limits-7pxjd-1369060285  13s       ContainerCreating
   ├-✔ run-pod(8:9)     pod-limits-7pxjd-1321697003  9s
   └-✔ run-pod(9:10)    pod-limits-7pxjd-3434540732  8s
```

Example with ImagePullBackOff and message extracted from the pod
```
$ argo get image-pull-fail-tb57d
Name:                image-pull-fail-tb57d
Namespace:           default
ServiceAccount:      default
Status:              Running
Created:             Tue Aug 21 17:25:07 -0700 (5 seconds ago)
Started:             Tue Aug 21 17:25:07 -0700 (5 seconds ago)
Duration:            5 seconds

STEP                      PODNAME                DURATION  MESSAGE
 ◷ image-pull-fail-tb57d  image-pull-fail-tb57d  5s        ImagePullBackOff: Back-off pulling image "alpine:doesntexist"
```

**Comment by vicaire** [comment]
This is great. Thanks!
