### ISSUE TITLE
cant set google storage as default artifact repository

### ISSUE THREAD

**Issue by amitgilad3** [argoproj/argo#916]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 Deploying workflow which uses artifacts in tutorial cant find secrets.

**What happened**:
I followed the tutorial for deploying default artifact storage (in my case google storage).

**this is my secret config:**
apiVersion: v1
kind: Secret
metadata:
  name: argo-artifacts-gs
data:
  accessKey: myAccessKey
  secretkey: mySecretKey

**and this is my configMap for argo:**
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  namespace: kube-system
data:
  config: |
    artifactRepository:
      s3:
        bucket: argo-artifacts-stg
        endpoint:  storage.googleapis.com
        insecure: true
        accessKeySecret:
          name: argo-artifacts-gs
          key: accesskey
        secretKeySecret:
          name: argo-artifacts-gs
          key: secretkey
    executorImage: argoproj/argoexec:latest

every time i run the workflow example :  argo submit https://raw.githubusercontent.com/argoproj/argo/master/examples/artifact-passing.yaml

the pod logs show the following message:
time="2018-07-23T18:54:34Z" level=fatal msg="secret 'argo-artifacts-gs' does not have the key 'accesskey'"

**Anything else we need to know?**:

**Environment**:
- Argo version:
argo: v2.1.1
  BuildDate: 2018-05-29T20:38:37Z
  GitCommit: ac241c95c13f08e868cd6f5ee32c9ce273e239ff
  GitTreeState: clean
  GitTag: v2.1.1
  GoVersion: go1.9.3
  Compiler: gc
  Platform: darwin/amd64

clientVersion:
  buildDate: 2018-04-19T00:05:56Z
  compiler: gc
  gitCommit: dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92
  gitTreeState: clean
  gitVersion: v1.9.7
  goVersion: go1.9.3
  major: "1"
  minor: "9"
  platform: darwin/amd64
serverVersion:
  buildDate: 2018-06-21T14:11:26Z
  compiler: gc
  gitCommit: f4c74e18e57148052c59cc0467bb7e99dcc46399
  gitTreeState: clean
  gitVersion: v1.10.5-gke.0
  goVersion: go1.9.3b4
  major: "1"
  minor: 10+
  platform: linux/amd64

**Comment by jessesuen** [comment]
@amitgilad3 the error message "secret 'argo-artifacts-gs' does not have the key 'accesskey'" is accurate. It's complaining that your secret, `argo-artifacts-gs`, is missing the key `accesskey`. If you store your secret value in a different key in the secret, then the config should be changed accordingly.

**Comment by amitgilad3** [comment]
Hey @jessesuen , thanks for the quick response

thanks for pointing out my issue, i fixed it and the workflow ran without any issues :)

awsome project
