### ISSUE TITLE
Pods cut off by whitespace

### ISSUE THREAD

**Issue by EdanSneh** [argoproj/argo#917]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug report

**What happened**:
extra white space at the bottom of an argo workflow
(Additionally the X, used to close out a window, that appears when clicking on a pod will rise above the intended scope of its div)
**What you expected to happen**:
no whitespace at bottom of page

**How to reproduce it (as minimally and precisely as possible)**:
run a workflow, and click on a pod with a summary tab that is longer than your window supports and scroll all the way to the bottom.

Example:

![argoissue](https://user-images.githubusercontent.com/14003534/43172946-f650a65a-8f66-11e8-8eca-e166dc8535be.jpg)

**Anything else we need to know?**:

**Environment**:
- Argo version:
```
$ argo version
argo: v2.1.1
  BuildDate: 2018-05-29T20:38:37Z
  GitCommit: ac241c95c13f08e868cd6f5ee32c9ce273e239ff
  GitTreeState: clean
  GitTag: v2.1.1
  GoVersion: go1.9.3
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: 2018-06-27T22:29:25Z
  compiler: gc
  gitCommit: 91e7b4fd31fcd3d5f436da26c980becec37ceefe
  gitTreeState: clean
  gitVersion: v1.11.0
  goVersion: go1.10.3
  major: "1"
  minor: "11"
  platform: darwin/amd64
serverVersion:
  buildDate: 2018-06-21T14:11:26Z
  compiler: gc
  gitCommit: f4c74e18e57148052c59cc0467bb7e99dcc46399
  gitTreeState: clean
  gitVersion: v1.10.5-gke.0
  goVersion: go1.9.3b4
  major: "1"
  minor: 10+
  platform: linux/amd64
```
@alexmt

**Comment by jessesuen** [comment]
I think the whitespace must have been already resolved by @alexmt. I'm going through visual testing before the v2.2 release and I haven't seen it come up, whereas before I would see it frequently.
