### ISSUE TITLE
Upgrade package dependicies

### ISSUE THREAD

**Issue by shrinandj** [argoproj/argo#918]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Umm... FEATURE REQUEST

**What happened**:
Argo is currently using Kubernetes package versions which are not latest. See below. And argo itself is used in other projects like `argo-events` as a package. For some other reasons, `argo-events` needs to upgrade to newer versions of the following packages.

```
[[constraint]]
  name = "k8s.io/api"
  branch = "release-1.9"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  branch = "release-1.9"

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.9"

[[constraint]]
  name = "k8s.io/code-generator"
  branch = "release-1.9"
```

**What you expected to happen**:

It will be great if there is a new release of `argo` with the above constraints bumped up the latest releases (or at least 1.10).

**Comment by jessesuen** [comment]
Duping to #908
