### ISSUE TITLE
Support conditions with DAG tasks

### ISSUE THREAD

**Issue by qimingj** [argoproj/argo#921]
Does argo support conditions in dag mode? For example, the following seems not working for me?

  templates:
  - dag:
      tasks:
      - arguments:
          parameters:
          - name: message
            value: '{{inputs.parameters.message}}'
        name: get-Frequent
        template: get-Frequent
      - arguments:
          parameters:
          - name: get-Frequent-word
            value: '{{tasks.get-Frequent.outputs.parameters.get-Frequent-word}}'
          - name: outputpath
            value: '{{inputs.parameters.outputpath}}'
        dependencies:
        - get-Frequent
        name: save
        template: save
        when: '{{tasks.get-Frequent.outputs.parameters.get-Frequent-word}} == hut'
    ...

**Comment by jessesuen** [comment]
Not yet. Will be working on this for v2.2

**Comment by jessesuen** [comment]
Implemented in 11024318c0e2a9106f8a8b4a719daba12adf9f36.
