### ISSUE TITLE
[BUG REPORT] The static site argoproj.github.io does not work

### ISSUE THREAD

**Issue by silvin-lubecki** [argoproj/argo#924]
The static site linked in the main README.md https://argoproj.github.io/argo-site seems to be broken.

<img width="654" alt="screen shot 2018-07-30 at 18 22 44" src="https://user-images.githubusercontent.com/31478878/43409942-96c22588-9425-11e8-9871-ae0f7b1f2c45.png">

**Comment by alexmt** [comment]
Working on it

**Comment by jessesuen** [comment]
Link has been updated to https://argoproj.github.io. Pretty soon we'll be moving to just https://argoproj.io using GitHub pages with custom domains.
