### ISSUE TITLE
Remove installer/uninstaller in favor of kubectl apply

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo#928]
**Is this a BUG REPORT or FEATURE REQUEST?**: FEATURE REQUEST

**What happened**:

The argo installer/uninstaller is not totally useful for the following reasons:
* we will never accommodate everyone's desired installations. For example, customizing argo to have resource quotas is not possible via instalelr.
* the installer does not benefit from `kubectl apply` semantics since it uses REST update instead of patch. 
* the uninstaller is too easy to shoot yourself in the foot by blowing away the CRD (and all workflows in the cluster).

This proposal is to remove the `argo install` and `argo uninstall` commands completely, and direct users to running `kubectl apply` to install argo instead.

**Comment by andreimc** [comment]
@jessesuen I have written some helm charts for this that kinda provide a very easy way to configure and install argo. I am happy to adapt that for a more generic way.

**Comment by jessesuen** [comment]
Thanks for offering @andreimc, looks like we are just now getting some help on the Argo Helm front (See: https://github.com/argoproj/argo-helm/pull/14). Feel free to chime in there if you have any suggestions for improvements.

As for this issue, `argo install` and `argo uninstall` have now been removed so closing out this bug.
