### ISSUE TITLE
[Featutre Request] Argo workflow controller with Role not ClusterRole for security reasons.

### ISSUE THREAD

**Issue by andreimc** [argoproj/argo#932]
**Is this a BUG REPORT or FEATURE REQUEST?**:

Feature request.

**What happened**:

I would like to use a Role not a ClusterRole for an argo workflow deployment.

When namespace and instance id is present.

**What you expected to happen**:

Be able to use argo workflow controller with a cluster role when instanceid and namespace are present.

This is very good for security where as the cluster role can manage heaps of namespaces this would isolate all the permissions to the given namespace. It does require you to run one wf controller per namespace. For argo UI you can have a cluster role that can query across namespaces.

**How to reproduce it (as minimally and precisely as possible)**:

Install argo from templates but change ClusterRole to Role and ClusterRoleBinding to RoleBinding.

**Anything else we need to know?**:

**Environment**:
- Argo version: 2.1.1
- Kubernetes version : 1.10.4

**Comment by andreimc** [comment]
@jessesuen I have tried it I do get some errors that it's trying to query the workflows cluster wide.

I think in some of the queries the. I don't use the installer at all I have my own helm chart

```
E0803 03:12:01.871710       1 reflector.go:205] github.com/argoproj/argo/workflow/controller/controller.go:139: Failed to list *unstructured.Unstructured: workflows.argoproj.io is forbidden: User "system:serviceaccount:kube37af2e26:kube37af2e26-kubebuild-launcher" cannot list workflows.argoproj.io at the cluster scope
E0803 03:12:02.871326       1 reflector.go:205] github.com/argoproj/argo/workflow/controller/controller.go:140: Failed to list *v1.Pod: pods is forbidden: User "system:serviceaccount:kube37af2e26:kube37af2e26-kubebuild-launcher" cannot list pods at the cluster scope
E0803 03:12:02.874571       1 reflector.go:205] github.com/argoproj/argo/workflow/controller/controller.go:139: Failed to list *unstructured.Unstructured: workflows.argoproj.io is forbidden: User "system:serviceaccount:kube37af2e26:kube37af2e26-kubebuild-launcher" cannot list workflows.argoproj.io at the cluster scope
E0803 03:12:03.874197       1 reflector.go:205] github.com/argoproj/argo/workflow/controller/controller.go:140: Failed to list *v1.Pod: pods is forbidden: User "system:serviceaccount:kube37af2e26:kube37af2e26-kubebuild-launcher" cannot list pods at the cluster scope
```

I do get the following.

**Comment by jessesuen** [comment]
Hmmm, it's expected to work. I'm not sure if you are aware, the workflow-controller-configmap has a namespace field which should restrict all queries to the namespace:

https://github.com/argoproj/argo/blob/master/workflow/controller/controller.go#L58

But I haven't tried it in a while so it's possible that something broke.  Let me give a try.

**Comment by andreimc** [comment]
@jessesuen that's what I am missing I believe.

**Comment by andreimc** [comment]
thanks

**Comment by andreimc** [comment]
Works as expected closing
