### ISSUE TITLE
Permission issue with ClusterRole `admin`

### ISSUE THREAD

**Issue by bappr** [argoproj/argo#949]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG

**What happened**:
Permission issue with ClusterRole `admin`. Ok with ClusterRole `cluster-admin`.
```
$ argo list
2018/08/14 11:30:11 workflows.argoproj.io is forbidden: User "system:serviceaccount:default:default" cannot list workflows.argoproj.io in the namespace "test": Unknown user "system:serviceaccount:default:default"
```

**What you expected to happen**:
Should not have any issue using argo with ClusterRole `admin

**How to reproduce it (as minimally and precisely as possible)**:
`kubectl create rolebinding default-admin --clusterrole=admin --serviceaccount=default:default`
Deploy a pod with `kubectl` and `argo` available. Try `argo list` from this container.

**Environment**:
- Argo version:
```
$ argo version
argo: v2.1.1
  BuildDate: 2018-05-29T20:38:37Z
  GitCommit: ac241c95c13f08e868cd6f5ee32c9ce273e239ff
  GitTreeState: clean
  GitTag: v2.1.1
  GoVersion: go1.9.3
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: 2018-06-27T22:29:25Z
  compiler: gc
  gitCommit: 91e7b4fd31fcd3d5f436da26c980becec37ceefe
  gitTreeState: clean
  gitVersion: v1.11.0
  goVersion: go1.10.3
  major: "1"
  minor: "11"
  platform: darwin/amd64
serverVersion:
  buildDate: 2018-08-02T23:42:40Z
  compiler: gc
  gitCommit: 9b635efce81582e1da13b35a7aa539c0ccb32987
  gitTreeState: clean
  gitVersion: v1.9.7-gke.5
  goVersion: go1.9.3b4
  major: "1"
  minor: 9+
  platform: linux/amd64
```

**Comment by jessesuen** [comment]
@bappr - This will be resolved when we aggregate RBAC to the admin/edit/view roles. See:
https://github.com/argoproj/argo/issues/960

Will dupe this to that bug. It should be possible to do what you're asking today, by simply creating those cluster roles and adding the annotation. But we will make it part of the standard install so users don't have to figure that out for themselves.
