### ISSUE TITLE
Workflow-controller opening wrong APIServer url

### ISSUE THREAD

**Issue by gupash** [argoproj/argo#951]
**This a BUG REPORT**:

**Environment**:
- argo: v2.1.1

- Kubernetes version : v1.10

The problem is described in this stackoverflow link:

[https://stackoverflow.com/questions/51851808/argo-workflow-controller-cant-connect-to-kubernetes-apiserver](https://stackoverflow.com/questions/51851808/argo-workflow-controller-cant-connect-to-kubernetes-apiserver)

**Comment by jessesuen** [comment]
@gupash I have to believe this is somehow specific to your environment. The workflow controller simply uses the go-client InClusterConfig() to obtain it's rest client, which is the standard way for creating a client to the API server when in-cluster. 

If you look at the implementation, you'll notice it relies on KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT instead of kubernetes.default, for talking to the API server:

https://github.com/kubernetes/client-go/blob/master/rest/config.go#L313

**Comment by gupash** [comment]
Hi,
Yes I saw the IP was coming from KUBERNETES_SERVICE_HOST from within container.
I also modified it to reflect "kubernetes.default". Later on I had a word with our cluster admin.
They let me know that "kubernetes.default" also resolves to "192.168.0.1" which should work.
I also added a open all ingress and egress policy. 
But still the connection is not working and I am getting a tcp timeout.

`time="2018-08-16T18:23:55Z" level=fatal msg="Get https://kubernetes.default:443/api/v1/namespaces/2304613691/configmaps/workflow-controller-configmap: dial tcp: i/o timeout\ngithub.com/argoproj/argo/errors.Wrap\n\t/root/go/src/github.com/argoproj/argo/errors/errors.go:87\ngithub.com/argoproj/argo/errors.InternalWrapError\n\t/root/go/src/github.com/argoproj/argo/errors/errors.go:70\ngithub.com/argoproj/argo/workflow/controller.(*WorkflowController).ResyncConfig\n\t/root/go/src/github.com/argoproj/argo/workflow/controller/controller.go:295\nmain.Run\n\t/root/go/src/github.com/argoproj/argo/cmd/workflow-controller/main.go:96\ngithub.com/argoproj/argo/vendor/github.com/spf13/cobra.(*Command).execute\n\t/root/go/src/github.com/argoproj/argo/vendor/github.com/spf13/cobra/command.go:750\ngithub.com/argoproj/argo/vendor/github.com/spf13/cobra.(*Command).ExecuteC\n\t/root/go/src/github.com/argoproj/argo/vendor/github.com/spf13/cobra/command.go:831\ngithub.com/argoproj/argo/vendor/github.com/spf13/cobra.(*Command).Execute\n\t/root/go/src/github.com/argoproj/argo/vendor/github.com/spf13/cobra/command.go:784\nmain.main\n\t/root/go/src/github.com/argoproj/argo/cmd/workflow-controller/main.go:68\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:195\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:2337" `

**Comment by gupash** [comment]
Hi,
This issue was resolved. Actually the kubernetes.default is also resolved to 192.168.0.1.
The main cause was with the network policy. I had defined them correctly, but the pod selector was wrong. Hence the TCP connection exception.
