### ISSUE TITLE
Error: unknown flag --executor-image

### ISSUE THREAD

**Issue by melosalz** [argoproj/argo#958]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT
**What happened**:
When install argo with manifests/install.yaml, the deployment of workflow-controller return an error as `unknown flag --executor-image`
**What you expected to happen**:
Workflow-controller successfully deployed
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Argo version:2.1.1

**Comment by jessesuen** [comment]
@melosalz you've stumbled upon our v2.2 manifests. Until v2.2 is released (next week?), you should install using `argo install`, which is still what documented in our getting started guide. There is also a community maintained helm chart, if you prefer:

https://github.com/argoproj/argo-helm

In v2.2, the installer is removed, and one of the changes was to explicitly set the executor image as arg to the deployment, to make upgrades (kubectl apply) work (which was previously handled in `argo install --upgrade`).

Another thing that won't work if you try to install using these manifests right now, is that the v2.2 controller supports an empty configmap, whereas the v2.1 controller cannot tolerate it. So for now, please use `argo install` or the helm chart.

**Comment by melosalz** [comment]
@jessesuen Thank you very much! It works!
