### ISSUE TITLE
Possible to reuse artifact across workflows?

### ISSUE THREAD

**Issue by jackfengji** [argoproj/argo#961]
FEATURE REQUEST

I'm trying to build an machine learning platform based on argo. Usually there are three steps: prepare-data, train and test

I'm wondering if I can create a workflow for prepare-data and then use it in another training workflow? Being able to get the artifact path should be enough but can I get it in the workflow definition?

**Comment by jessesuen** [comment]
@jackfengji i think you should be able to reference parameters in an artifact location. So the parameter to another workflow could be a bucket and key. The you would reference these variables when describing the input artifact to a step.

**Comment by jackfengji** [comment]
@jessesuen The issue is that I cannot get the key easily in the workflow so I can save it to database. Now I'm trying to get the artifact key by getting the whole workflow detail from k8s

**Comment by jackfengji** [comment]
Yes. I think so. Thanks
