### ISSUE TITLE
Utilize pod process namespace sharing instead of docker executor

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo#970]
**Is this a BUG REPORT or FEATURE REQUEST?**: FEATURE REQUEST

**What happened**:

Currently, artifact saving is performed through the docker executor, which implements artifact copying via a `docker cp` command to copy out artifacts from the main container. The problem with this approach is it requires mounting of `docker.sock` of the host, which is insecure, and unacceptable in some secure environments.

In K8s, there is an (alpha) feature to share the process namespace and the filesystem between containers in a pod:
https://kubernetes.io/docs/tasks/configure-pod-container/share-process-namespace/

Instead of utilizing the docker executor, we could simply create the pod spec with `shareProcessNamespace: true` and access the filesystem of the main container to copy files directly. Similarly, the actual waiting and killing of the process, would only need to be done via normal kill command from the argoexec sidecar, as opposed to a `docker kill`. 

Using process namespace sharing provides us an ideal solution which addresses a lot of the security, and scalability concerns with our current docker, kubelet, or k8s API server approaches.

NOTE that this is an alpha feature and needs an feature gate (`--feature-gates=PodShareProcessNamespace=true`) configured for it to be enabled.

**Comment by jessesuen** [comment]
/cc @edlee2121 @JulienBalestra @gaganapplatix 

I don't think we need to spend any effort around a pure K8s API server executor implementation, since I think this should be the future of how we do artifact management, process waiting, process killing. Longer term, I think the docker/kubelet executors will eventually go away if the argoexec sidecar can already access the main container's filesystem easily through process namespace sharing.

**Comment by edlee2121** [comment]
For copying artifacts, we would share process namespaces and access files via /proc/pid/root?

**Comment by jessesuen** [comment]
That’s right

**Comment by srikumar-b** [comment]
I have quickly tested process namespace sharing (now beta feature enabled by default) on k8s v1.12 and is working as expected to access other container's filesystem.

**Comment by srikumar-b** [comment]
Could you let us know, any further development on finalizing the approach from the above list?

**Comment by xianlubird** [comment]
@jessesuen Any update on this ?    Is there a PR for thie issue?

**Comment by animeshsingh** [comment]
Coming to this from kubeflow pipeline community.
https://github.com/kubeflow/pipelines/issues/678

We have phased out Docker support in IBM Kubernetes Service, and are now relying on containerd, This is one blocking issue currently impacting the adotption for us. Any further updates on thsi?

**Comment by zmhassan** [comment]
Seems like this might be the problem:

https://github.com/argoproj/argo/blob/23d733bae386db44ec80639daf91b29dbf86b335/workflow/controller/workflowpod.go#L71-L79

Users shouldn't be required to mount hostpath.

**Comment by zmhassan** [comment]
Perhaps you can pass in an option into your Custom Resource to disable this as some users might just be using argo just for running workflows and might not require copying files.

**Comment by llegolas** [comment]
> Perhaps you can pass in an option into your Custom Resource to disable this as some users might just be using argo just for running workflows and might not require copying files. One option could be to have the code within the container running the job connect to s3 or some cloud storage to store these files. or even minio could be a drop in option.

Do you know how this option can be passed or is it existing at all ?

**Comment by jessesuen** [comment]
Fixed. 

K8s, Kubelete, and PNS executors will no longer mount docker.sock. The docker executor still needs docker.sock access even if not copying out artifacts, in order to perform a `docker wait` for waiting for the container to complete.

**Comment by animeshsingh** [comment]
Thanks @jessesuen - can we now use either K8s and PNS executors, and get same functional behaviour from Argo, if not scalability?

**Comment by jessesuen** [comment]
> can we now use either K8s and PNS executors, and get same functional behaviour from Argo, if not scalability?

The main difference is the K8s executor puts some additional polling load on k8s API server for waiting for container completion, whereas PNS is polling the local linux kernel (procfs) for container completion. Also PNS requires K8s 1.12 for PNS support (without the feature gate).

I'm copying my pro/con list from the other issue.

1. Docker:
```
+ supports all workflow examples
+ most reliable and well tested
+ very scalable. communicates to docker daemon for heavy lifting
- least secure. requires docker.sock of host to be mounted (often rejected by OPA)
```

2. kubelet
```
+ secure. cannot escape privileges of pod's service account
+ medium scalability - log retrieval and container polling is done against kubelet
- additional kubelet configuration may be required
- can only save params/artifacts in volumes (e.g. emptyDir), and not the base image layer (e.g. /tmp)
```

3. K8s API
```
+ secure. cannot escape privileges of pod's service account
+ no extra configuration
- least scalable - log retrieval and container polling is done against k8s API server
- can only save params/artifacts in volumes (e.g. emptyDir), and not the base image layer (e.g. /tmp)
```

4. PNS
```
+ secure. cannot escape privileges of service account
+ artifact collection can be collected from base image layer
+ scalable - process polling is done over procfs and not kubelet/k8s API
- processes will no longer run with pid 1
- artifact collection from base image may fail for containers which complete too fast
- cannot capture artifact directories from base image layer which has a volume mounted under it
- immature
```
