### ISSUE TITLE
[UI] Present timestamps in browser's locale

### ISSUE THREAD

**Issue by jiuchongxiao** [argoproj/argo#974]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT
**What happened**:
the workflow show time is not native time.it is utc
![1535612395 1](https://user-images.githubusercontent.com/13093730/44835142-cd400780-ac65-11e8-8907-b0689d77989a.jpg)

**What you expected to happen**:
i hope it is set cst
**How to reproduce it (as minimally and precisely as possible)**:
install argo as offical says

**Environment**:
- Argo version:
```
$ argo version
argo: v2.1.1
  BuildDate: 2018-05-29T20:39:36Z
  GitCommit: ac241c95c13f08e868cd6f5ee32c9ce273e239ff
  GitTreeState: clean
  GitTag: v2.1.1
  GoVersion: go1.9.3
  Compiler: gc
  Platform: linux/amd64

```
- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: 2018-08-07T23:17:28Z
  compiler: gc
  gitCommit: bb9ffb1654d4a729bb4cec18ff088eacc153c239
  gitTreeState: clean
  gitVersion: v1.11.2
  goVersion: go1.10.3
  major: "1"
  minor: "11"
  platform: linux/amd64
serverVersion:
  buildDate: 2018-07-17T18:43:26Z
  compiler: gc
  gitCommit: b1b29978270dc22fecc592ac55d903350454310a
  gitTreeState: clean
  gitVersion: v1.11.1
  goVersion: go1.10.3
  major: "1"
  minor: "11"
  platform: linux/amd64

```

**Comment by DaveKriegerEmerald** [comment]
We also desire this enhancement.

**Comment by alexec** [comment]
This is for Argo v2.1.1, and now shows time relative. 
<img width="1039" alt="Screen Shot 2020-02-25 at 11 00 49 AM" src="https://user-images.githubusercontent.com/1142830/75278093-1f5fdb80-57be-11ea-92b7-bc862318d833.png">

**Comment by DaveKriegerEmerald** [comment]
Thanks, @alexec ! We're using v2.4.3 of argo-ui and we're still seeing the UTC timestamps; is there a configuration change we need to make to get the relative ones? I'm not finding documentation about it.
<img width="832" alt="Screen Shot 2020-02-25 at 11 33 23 AM" src="https://user-images.githubusercontent.com/42977661/75280668-bb8be180-57c2-11ea-9b5e-070752b586ff.png">
