### ISSUE TITLE
argo logs --follow exits immediately when workflow status is still Pending

### ISSUE THREAD

**Issue by Ark-kun** [argoproj/argo#989]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Bug

**What happened**:
A script submits pipeline and I want to follow the logs. Unfortunately, the command returns right away.

```
wf=$(argo submit ... --output name)
argo logs --follow --workflow $wf
argo get $wf
I0910 18:49:57.420] Name:                build-images-6rqvs
I0910 18:49:57.420] Namespace:           default
I0910 18:49:57.420] ServiceAccount:      default
I0910 18:49:57.420] Status:              Pending
I0910 18:49:57.421] Created:             Mon Sep 10 18:49:56 +0000 (1 second ago)
I0910 18:49:57.421] Parameters:          

```
**What you expected to happen**:
I expected argo logs --follow to follow the workflow from submit to finish.

**How to reproduce it (as minimally and precisely as possible)**:
The workflow is private, but simple ~5 similar parallel steps. The workflow is started by the prow test.

**Environment**:
- Argo version:
```
$ argo version
argo: v2.2.0
  BuildDate: 2018-08-30T08:52:05Z
  GitCommit: af636ddd8455660f307d835814d3112b90815dfd
  GitTreeState: clean
  GitTag: v2.2.0
  GoVersion: go1.10.3
  Compiler: gc
  Platform: linux/amd64
```

**Comment by Ark-kun** [comment]
Here is the problematic code:
https://github.com/argoproj/argo/blob/master/cmd/argo/commands/logs.go#L104

	if p.follow && wf.Status.Phase == v1alpha1.NodeRunning {
		p.printLiveWorkflowLogs(wf, timeByPod)
	}
	return nil

So, how can we run the pipeline synchronously while following the logs?

**Comment by alexmt** [comment]
Fixed by https://github.com/argoproj/argo/pull/1142
