### ISSUE TITLE
Feature Proposal: add admission control for workflows

### ISSUE THREAD

**Issue by jackywu** [argoproj/argo#993]
Feature Proposal
> add admission control for workflows.

My Usecase
> I have millions datasets to be processed by one workflow. I wanna submit one job for one dataset, so there must be millions jobs. I don't have a admission controller or scheduling controller. so I think the most convenient approach is implement a admission controller running in Kubernetes. And after research I found etcd is a good component to store the submitted jobs, because of the [queue feature of etcd](
https://github.com/etcd-io/etcd/blob/6acb3d67fbe131b3b2d5d010e00ec80182be4628/Documentation/v2/api.md#atomically-creating-in-order-keys). I put five thousand job in one queue and get all of them, it's much fast enough  for store jobs.

**Comment by fj-sanchez** [comment]
Does currently exists any alternative way to get this behaviour?

**Comment by Farkal** [comment]
Any new on this ? Currently we saturate etcd and it's impossible to recover our cluster.

**Comment by sarabala1979** [comment]
Cronworkflow feature has been implemented. It will be included in next release v2.5. you can schedule the workflows with crontap. #1758
